import type {Asset} from '../core/types';import {Grid} from '../core/grid';import {assetBoundsM} from '../core/sky';import {validateRig} from '../core/rig';import {AvatarModel} from './avatar-model';import {cap} from './wearable-caps';import {eyewear,faceCover} from './wearable-face';import {hairPin,earrings} from './wearable-jewelry';import {atlasSource,type AtlasRecipe} from './atlas-life';import {productionReference,productionStyleRevision} from './style';
type Params=Record<string,string|number>;const param=(values:string[],description:string)=>({type:'string',enum:values,default:values[0],description});
export function wearableParameters(id:string):Record<string,any>{const n=Number(id.slice(5));if(n<=106)return{wearFit:param(['adult','child'],'作者成人066/学龄儿童068头部及CHAR085短发适配')};if(n===107)return{pinLength:param(['long','short'],'0.36/0.30m实体细簪；对应CHAR100已抽簪槽')};if(n===110)return{earFit:param(['adult','child','elder'],'三种独立耳部位置')};return{headFit:param(['adult','child','elder'],'匹配066/068 school/069实际眼高和面部')};}
export function wearableVariants(id:string):Params[]{return Object.entries(wearableParameters(id)).reduce<Params[]>((rows,[k,p])=>rows.flatMap(r=>p.enum.map((v:string)=>({...r,[k]:v}))),[{}]);}
const features:Record<string,string>={'CHAR-101':'宽顶制帽；独立徽章；真开底帽腔和连续斜舌','CHAR-102':'金属护盔；独立软垫和下颌织带','CHAR-103':'塑料防护帽；帽顶收起护目框和透明镜片','CHAR-104':'连续草编斗笠；真内腔和下颌带','CHAR-105':'高褶厨房帽；真实空腔和卫生织围','CHAR-106':'医护布帽；独立卫生织带和织入徽记','CHAR-107':'独立花簪；真实细杆和垂链玻璃饰','CHAR-108':'成对近视镜片；独立金属框和镜腿','CHAR-109':'独立防护镜片；真实密封环和后脑带','CHAR-110':'成对耳夹、金属垂链和玻璃嵌片','CHAR-111':'真实双面褶布口罩；耳挂和鼻梁织边','CHAR-112':'真实面罩壳；独立滤盒、滤材、金属格栅和后脑带'};
const limits='作者穿戴候选：最小细块5mm体素，斜面/曲面连续网格，镜片与框/密封分别保存。全部非碰撞，单head关节刚性绑定，无软带动力学、镜片光学度数、防护效能或呼吸模拟。帽/盔/眼镜/面罩不包含头发和头部；限指定头型和作者接口，原骨骼/制服规则/控制器未收件，人工美术验收待定。';
const counts:Record<string,number>={'CHAR-101':3,'CHAR-102':4,'CHAR-103':2,'CHAR-104':2,'CHAR-105':2,'CHAR-106':1,'CHAR-107':3,'CHAR-108':2,'CHAR-109':2,'CHAR-110':4,'CHAR-111':2,'CHAR-112':9};export const wearableExpectedComponents=(id:string,p:Params)=>counts[id]??1;
export const wearableRecipes:Record<string,AtlasRecipe>=Object.fromEntries(Object.entries(features).map(([id,f])=>[id,{size:[.38,.40,.40],pitch:.005,features:f,limits,expectedComponents:counts[id]??1,draw:()=>{throw new Error('通过穿戴混合工厂创建');}}]));
const roles:Record<string,string[]>={'CHAR-101':['helmetPad','hatCloth','hatHardware','hatBadgeGlass'],'CHAR-102':['helmetPad','guardHelmet','helmetStrap','hatHardware','hatBadgeGlass'],'CHAR-103':['helmetPad','workHelmet','hatHardware','gogglesFrame','gogglesLens'],'CHAR-104':['helmetPad','strawWeave','helmetStrap','hatHardware'],'CHAR-105':['helmetPad','hygieneCapCloth','hatHardware'],'CHAR-106':['helmetPad','hygieneCapCloth','hygieneCapBand','medicalEmblem'],'CHAR-107':['hairOrnament','hairGem'],'CHAR-108':['spectaclesFrame','spectaclesLens'],'CHAR-109':['gogglesFrame','gogglesLens','gogglesSeal','helmetStrap','hatHardware'],'CHAR-110':['earringMetal','earringGem'],'CHAR-111':['medicalMask','maskElastic'],'CHAR-112':['respiratorShell','respiratorFilter','respiratorGrille','helmetStrap','hatHardware']};
export function inspectWearableMaterials(id:string,a:Asset,s:Record<string,number>){if(!wearableRecipes[id])return null;for(const material of [...new Grid(a.chunks).cells()].map(([,m])=>m).concat(a.meshes!.map(m=>m.material)))if(!roles[id].some(r=>s[r]===material))throw new Error(id+'穿戴用途错误 '+material);return{revision:1,method:'actual-voxel-and-mesh-role-check',roles:roles[id],note:'帽布、金属/塑料盔壳、草编、卫生织物、镜框、玻璃/塑料镜片、密封、滤材和耳饰分别赋值；全部非碰撞和零发光。'};}
export function makeWearableAsset(catalogId:string,name:string,id:string,style:Record<string,number>,input:Params={}):Asset{const r=wearableRecipes[catalogId];if(!r)throw new Error('未实现穿戴配方');const defs=wearableParameters(catalogId);for(const[k,v]of Object.entries(input))if(!defs[k]?.enum.includes(v))throw new Error('未验证穿戴参数 '+k);const p={...Object.fromEntries(Object.entries(defs).map(([k,v])=>[k,v.default])),...input},s=new Proxy(style,{get(t,k){if(typeof k==='symbol')return Reflect.get(t,k);if(!Number.isInteger(t[k])||t[k]<1)throw new Error('缺少用途材质 '+k);return t[k];}}),m=new AvatarModel(s),n=Number(catalogId.slice(5));if(n<=106)cap(m,catalogId,String(p.wearFit));else if(n===107)hairPin(m,String(p.pinLength));else if(n<=109)eyewear(m,catalogId,String(p.headFit));else if(n===110)earrings(m,String(p.earFit));else faceCover(m,catalogId,String(p.headFit));
 m.bind('humanoid');m.joint('head',null,[0,0,0]);m.rig!.meshJoints=Object.fromEntries(m.meshes.map(v=>[v.name,'head']));m.rig!.voxelJoints=[{joint:'head',region:m.b.g.bounds()!}];m.rig!.sockets=Object.fromEntries(m.ports.map(v=>[v.id,'head']));
 const a:Asset={id,name,version:1,category:'base',cellSize:.005,origin:[0,0,0],chunks:m.b.g.serialize(),parts:[{id:'root',name:'最小细块；连续帽盔、镜框和面罩另列',parent:null,region:m.b.g.bounds()!},...m.b.parts],meshes:m.meshes,rig:m.rig,ports:m.ports,openings:[],source:{kind:'catalog-recipe',catalogId,recipeRevision:1,styleReference:productionReference,styleRevision:productionStyleRevision,parameters:p,features:r.features,geometryStage:'candidate',reference:atlasSource(catalogId),referenceStage:'candidate',limitations:limits,units:'metres',front:'-Z',gameIntegration:false,animationClips:false,manualRigidBinding:'single author head joint; no soft strap or cloth dynamics',collision:'none; visual-only',detail:m.detail}};validateRig(a);const b=assetBoundsM(a)!;a.source!.dimensionsM=b.max.map((v,i)=>v-b.min[i]);a.source!.materialAssignmentReview=inspectWearableMaterials(catalogId,a,style);return a;
}
