import {profilePrism} from '../core/authored-mesh';
import {Shapes} from './shapes';
import {Grid} from '../core/grid';
import type {Asset,Bounds,V3} from '../core/types';
import {assetBoundsM,type SkyDescriptor} from '../core/sky';
import {atlasSource,type AtlasRecipe} from './atlas-life';
import {productionReference,productionStyleRevision} from './style';
type Params=Record<string,string|number>;type Detail={openings:Bounds[];[key:string]:unknown};
const pitch=.2,q=(n:number)=>Math.round(n/pitch);
const physicalLimits='基础块件保留0.2m体素；坡面使用独立连续网格，显示及碰撞导出同一网格。作者技术候选，待人工美术验收；原地形、FloorPlan、controller、usePoint、照明供电均未绑定。量化尺寸不是施工或承载认证；近远保留体素块件与连续坡面。';
const skyLimits='原生 sky 描述为权威，非体素、无物理碰撞；米制全尺寸网格，GLB为保存时刻快照。原14000/68/38数值的半径或直径含义未获源码核实，本作明确采用作者半径解释。作者预览时刻不代表SimState接入；不是HDRI、真实天文、月相、云/天气模拟或GPU粒子实例。待人工画面验收。';
export const landscapeDefaults:Record<string,Params>={'ENV-086':{substrate:'rock'},'ENV-088':{transition:'fill',roadWidth:4},'ENV-091':{drainForm:'straight'},'ENV-094':{pavingForm:'court'},'ENV-096':{planterForm:'long'},'ENV-097':{vesselForm:'square'},'ENV-098':{seatForm:'wood'},'ENV-104':{lampForm:'pole'},'ENV-110':{hour:17.8,weather:'clear',visibility:1},'ENV-112':{hour:12,weather:'clear',visibility:1},'ENV-113':{hour:0,weather:'clear',visibility:1},'ENV-114':{hour:0,weather:'clear',visibility:1}};
export function landscapeParameters(id:string):Record<string,any>{const choice=(values:(string|number)[],value:string|number,description:string)=>({type:typeof value,enum:values,default:value,description});switch(id){case'ENV-086':return{substrate:choice(['rock','soil'],'rock','真实院廊外缘岩土支撑，含0.2m量化立柱')};case'ENV-088':return{transition:choice(['fill','cut','elevated'],'fill','填方/挖方/留河下通道三种作者路肩'),roadWidth:choice([4,8],4,'作者道路/宽路床净宽米，非原跑道规格')};case'ENV-091':return{drainForm:choice(['straight','corner','collection'],'straight','贯通直沟/转沟/集水节点，顶篦与路齐平')};case'ENV-094':return{pavingForm:choice(['court','opening'],'court','完整广场或保留真实中央孔洞')};case'ENV-096':return{planterForm:choice(['long','tree'],'long','独立长槽或开底树池边框')};case'ENV-097':return{vesselForm:choice(['square','jar','bonsai'],'square','独立方盆/矮缸/盆景浅盆；参数形态不增加清单母版')};case'ENV-098':return{seatForm:choice(['wood','stone'],'wood','木椅/石凳，共0.6m顶面作者座面接口')};case'ENV-104':return{lampForm:choice(['pole','stone'],'pole','独立落地灯杆/石灯；未接供电保持零发光')};default:return landscapeDefaults[id]?{hour:{type:'number',minimum:0,maximum:24,default:landscapeDefaults[id].hour,description:'作者保存快照时刻，连续0到24小时'},weather:choice(['clear','overcast'],'clear','仅背景外观，不编造天气状态'),visibility:{type:'number',minimum:0,maximum:1,default:1,description:'仅背景可见度'}}:{};}}
export function landscapeVariants(id:string):Params[]{if(Number(id.slice(4))>=110)return[{}];let all:Params[]=[{}];for(const[k,d]of Object.entries(landscapeParameters(id)))all=all.flatMap(p=>d.enum.map((v:string|number)=>({...p,[k]:v})));return all;}
function parameters(id:string,input:Params){const defs=landscapeParameters(id);for(const[k,v]of Object.entries(input)){const d=defs[k];if(!d||(d.enum?!d.enum.includes(v):typeof v!=='number'||!Number.isFinite(v)||v<d.minimum||v>d.maximum))throw new Error('未验证景观参数 '+k);}return{...landscapeDefaults[id],...input};}
function rim(b:Shapes,p:Params,d:Detail){const rock=p.substrate==='rock';b.part('实际接地连续岩土缘，外侧阶层不构成楼板',()=>{for(let x=0;x<40;x++)for(let z=0;z<15;z++){const h=z>=10?9:z>=5?6:3;for(let y=0;y<h;y++)b.g.set([x,y,z],y<2?b.s.bedrock:rock?(y%4===0?b.s.weatheredRock:b.s.bedrock):y===h-1?b.s.surfaceSoil:b.s.soilSubstrate);}});
 b.part('八根真实0.2米方柱，柱顶承接地面院廊',()=>{for(let x=3;x<40;x+=5)b.b(x*.2,1.8,2.4,.2,.6,.2,b.s.weatheredRock);});d.supportSitesM=Array.from({length:8},(_,i)=>[.6+i,2.4,2.4]);d.columnWidthM=.2;d.courtyardGroundOnly=true;d.allEntrancesCertified=false;}
function shoulder(b:Shapes,p:Params,d:Detail){const W=Number(p.roadWidth),form=String(p.transition),z0=2,z1=2+W,H=form==='elevated'?3.2:1.8;
 b.part('路床最小块件与连续岩底，铺装留在交通域',()=>{b.b(0,0,0,8,.2,W+4,b.s.bedrock);if(form==='elevated'){for(const x of[0,7]){b.b(x,.2,z0,1,H-.4,W,b.s.soilSubstrate);b.b(x,H-.2,z0,1,.2,W,b.s.drainAggregate);}}else{b.b(0,.2,z0,8,H-.4,W,b.s.soilSubstrate);b.b(0,H-.2,z0,8,.2,W,b.s.drainAggregate);}});
 if(form==='elevated')d.openings.push({min:[5,1,q(z0)],max:[35,q(H),q(z1)]});d.roadBed={min:[0,H,z0],max:[8,H,z1],widthM:W};d.transition=form;d.pavementIncluded=false;d.originalTerrainBound=false;d.slopes='continuous authored meshes, not staircase voxels';}
function shoulderMeshes(p:Params,s:Record<string,number>){const W=Number(p.roadWidth),form=String(p.transition),H=form==='elevated'?3.2:1.8,outer=form==='cut'?2.8:.4,inner=form==='cut'?1.8:H,spans=form==='elevated'?[[0,1],[7,8]]:[[0,8]],meshes=[];for(const[x0,x1]of spans)for(const[z0,z1,h0,h1]of[[0,2,outer,inner],[W+2,W+4,inner,outer]]){meshes.push(profilePrism('连续路肩土体',s.soilSubstrate,x0,x1,[[z0,.2],[z1,.2],[z1,h1-.1],[z0,h0-.1]]));meshes.push(profilePrism('连续坡面表土层',s.surfaceSoil,x0,x1,[[z0,h0-.1],[z1,h1-.1],[z1,h1],[z0,h0]]));}return meshes;}
function drainage(b:Shapes,p:Params,d:Detail){const form=String(p.drainForm),W=form==='straight'?6:4,D=form==='straight'?2:4,channel:Bounds[]=form==='straight'?[{min:[0,.2,.6],max:[W,.8,1.4]}]:form==='corner'?[{min:[0,.2,.6],max:[2.4,.8,1.4]},{min:[1.6,.2,.6],max:[2.4,.8,D]}]:[{min:[0,.2,1.6],max:[4,.8,2.4]},{min:[1.6,.2,0],max:[2.4,.8,4]},{min:[.6,.2,.6],max:[3.4,.8,3.4]}];
 b.part('完整排水石床及与路齐高的沟边',()=>b.b(0,0,0,W,1,D,b.s.wall));
 b.part('真实贯通沟腔与顶部开口',()=>{for(const r of channel)b.b(r.min[0],r.min[1],r.min[2],r.max[0]-r.min[0],1,r.max[2]-r.min[2],0);});
 b.part('真实金属孔篦，每条横杆实接沟壁',()=>{for(let x=0;x<q(W);x++)for(let z=0;z<q(D);z++)if(!b.g.get([x,3,z])&&(x%2===0||z%2===0))b.g.set([x,4,z],b.s.drainGrate);});
 // All void assertions stop below the actual bars; top holes checked separately.
 d.openings.push(...channel.map(r=>({min:r.min.map(q) as V3,max:r.max.map(q) as V3})));d.flushTopYM=1;d.grateHoleM=.2;d.channel=channel;d.flowSimulated=false;}
function paving(b:Shapes,p:Params,d:Detail){b.part('实际岩基层和厚石板地坪',()=>{b.b(0,0,0,8,.2,8,b.s.bedrock);b.b(0,.2,0,8,.4,8,b.s.wall);});b.part('逐格石缝与连续深色石嵌纹',()=>{for(let x=0;x<40;x++)for(let z=0;z<40;z++)if(x%8===0||z%8===0)b.g.set([x,2,z],b.s.mortar);for(const k of[5,6,33,34]){b.b(k*.2,.4,1, .2,.2,6,b.s.stone);b.b(1,.4,k*.2,6,.2,.2,b.s.stone);}});
 // Hui helper is a vertical motif; only author a horizontal ground motif here.
 for(const[v]of [...b.g.cells()])if(v[1]>=3)b.g.set(v,0);
 b.part('水平面真实回纹石线',()=>{for(const[x,z,w,h]of[[2.4,2.4,3.2,.2],[2.4,2.4,.2,3.2],[2.4,5.4,3.2,.2],[5.4,3,.2,2.6],[3,3,2.6,.2],[3,3,.2,1.8],[3,4.6,1.8,.2]])b.b(x,.4,z,w,.2,h,b.s.stone);});if(p.pavingForm==='opening'){b.b(2.8,0,2.8,2.4,.6,2.4,0);d.openings.push({min:[14,0,14],max:[26,12,26]});}d.walkTopYM=.6;d.centralOpening=p.pavingForm==='opening';}
function planter(b:Shapes,p:Params,d:Detail){const tree=p.planterForm==='tree',W=tree?3.6:6,D=tree?3.6:2,H=tree?.6:1.4;
 b.part('真正空心且厚0.4米的独立石框',()=>{b.b(0,0,0,W,H,D,b.s.wall);b.b(.4,tree?0:.2,.4,W-.8,H,D-.8,0);});b.part('底脚石带与可读石缝',()=>{for(const[v,m]of [...b.g.cells()])if(v[1]===0)b.g.set(v,b.s.stone);else if(v[1]===q(H)-2&&(v[0]%7===0||v[2]%7===0))b.g.set(v,b.s.mortar);});if(!tree)b.part('两个实际底排水孔及正面回纹',()=>{for(const x of[1.2,4.4])b.b(x,0,.8,.2,.4,.2,0);b.hui(1.8,.4,-.2,2.4,.8,b.s.stone);});d.openings.push({min:[2,q(H),2],max:[q(W)-2,q(H)+4,q(D)-2]});d.soilCavityM={min:[.4,tree?0:.2,.4],max:[W-.4,H-.2,D-.4]};d.plantIncluded=false;}
function vessel(b:Shapes,p:Params,d:Detail){if(p.vesselForm==='bonsai'){b.part('浅盆陶壁、独立石承脚和底排水孔',()=>{for(const x of[0,1.2])for(const z of[0,.72])b.b(x,0,z,.16,.08,.16,b.s.stone);b.b(.04,.08,.04,1.28,.08,.80,b.s.stone);b.b(.04,.16,.04,1.28,.12,.80,b.s.ceramicWhite);b.b(0,.28,0,1.36,.04,.88,b.s.ceramicWhite);b.b(.12,.16,.12,1.12,.20,.64,0);b.b(.60,.08,.36,.16,.12,.16,0);});b.part('盆沿石压线和正面回纹',()=>{for(const x of[.04,1.28])b.b(x,.28,.04,.04,.04,.80,b.s.stone);b.hui(.20,.16,0,.32,.12,b.s.stone,.02);b.hui(.84,.16,0,.32,.12,b.s.stone,.02);});d.openings.push({min:[15,2,9],max:[19,4,12]},{min:[3,8,3],max:[31,10,19]});d.soilCavityM={min:[.12,.16,.12],max:[1.24,.28,.76]};d.authorPublicScale=false;d.plantIncluded=false;d.bonsaiDependencyVariant=true;return;}const square=p.vesselForm==='square';b.part('真实厚壁、底座和敞口',()=>{if(square){b.b(0,0,0,2.4,.2,2.4,b.s.stone);b.b(.2,.2,.2,2,1.4,2,b.s.ceramicWhite);b.b(0,1.6,0,2.4,.2,2.4,b.s.ceramicWhite);b.b(.6,.4,.6,1.2,1.6,1.2,0);}else{b.cylinder(1.2,0,1.2,1,.2,b.s.stone);for(let y=1;y<7;y++){const r=y<3?1:1.2;b.cylinder(1.2,y*.2,1.2,r,.2,b.s.ceramicWhite,y===1?0:r-.4);}b.cylinder(1.2,1.4,1.2,1,.2,b.s.ceramicWhite,.6);}});b.part('真实贯通底部排水孔',()=>b.b(1,0,1,.4,.4,.4,0));if(square)b.part('正面实体陶瓷边饰，非贴纸',()=>{b.b(.4,.6,0,1.6,.8,.2,b.s.ceramicWhite);b.b(.6,.8,0,1.2,.4,.2,b.s.stone);});d.openings.push({min:[5,0,5],max:[7,2,7]},{min:[5,square?8:6,5],max:[7,10,7]});d.soilCavityM={min:[.6,.4,.6],max:[1.8,square?1.6:1.2,1.8]};d.authorPublicScale=true;d.plantIncluded=false;}
function seat(b:Shapes,p:Params,d:Detail){const wood=p.seatForm==='wood';b.part('两个真实接地石承脚和座板',()=>{for(const x of[0,3])b.b(x,0,0,.6,.6,1.2,b.s.wall);b.b(.6,.2,.2,2.4,.2,.8,wood?b.s.wood:b.s.wall);b.b(.4,.4,.2,2.8,.2,.8,wood?b.s.fabric:b.s.wall);});b.part('木纹向背靠、扶手和铜锁件',()=>{if(wood){for(const x of[.2,3.2]){b.b(x,.6,.8,.2,1,.2,b.s.wood);b.b(x,.6,0,.2,.4,1.2,b.s.wood);}b.b(.4,1.2,.8,2.8,.4,.2,b.s.wood);b.b(.4,.8,.8,2.8,.2,.2,b.s.woodEdge);}for(const x of[0,3.2])b.b(x,.6,0,.4,.2,.2,b.s.bronze);});d.seatPlaneM={min:[.6,.6,.2],max:[3,.6,.8]};d.interactive=false;d.usePointBound=false;}
function lamp(b:Shapes,p:Params,d:Detail){const pole=p.lampForm==='pole';const x=pole?1.8:.2,y=pole?2.8:1.2;
 b.part('真实接地基座、灯杆或石柱',()=>{b.b(0,0,0,1.2,.2,1.2,b.s.wall);b.b(.2,.2,.2,.8,.4,.8,b.s.stone);b.b(.4,.6,.4,.4,pole?3.6:.6,.4,pole?b.s.wood:b.s.wall);if(pole){b.b(.4,4,.4,2.4,.2,.4,b.s.metal);b.b(2,3.8,.4,.2,.2,.2,b.s.bronze);}});
 b.part('灯体金属底顶与四根边梃',()=>{for(const Y of[y,y+1])b.b(x,Y,.2,.8,.2,.8,b.s.metal);for(const X of[x,x+.6])for(const Z of[.2,.8])b.b(X,y+.2,Z,.2,.8,.2,b.s.metal);});
 b.part('独立透明硬玻璃四面与内部光学灯芯',()=>{for(const X of[x,x+.6])b.b(X,y+.2,.4,.2,.8,.4,b.s.landscapeGlass);for(const Z of[.2,.8])b.b(x+.2,y+.2,Z,.4,.8,.2,b.s.landscapeGlass);b.b(x+.2,y+.2,.4,.4,.8,.4,b.s.landscapeEmitter);});
 b.part('铜件及石灯挑檐',()=>{if(!pole){b.b(0,y+1.2,0,1.2,.2,1.2,b.s.wall);b.b(.4,y+1.4,.4,.4,.2,.4,b.s.stone);}for(const Y of[y,y+1])b.b(x+.2,Y,0,.4,.2,.2,b.s.bronze);});d.powerBound=false;d.defaultEmission=0;d.opticalLayers=['landscapeGlass','landscapeEmitter'];}
function draw(b:Shapes,id:string,p:Params,d:Detail){switch(id){case'ENV-086':return rim(b,p,d);case'ENV-088':return shoulder(b,p,d);case'ENV-091':return drainage(b,p,d);case'ENV-094':return paving(b,p,d);case'ENV-096':return planter(b,p,d);case'ENV-097':return vessel(b,p,d);case'ENV-098':return seat(b,p,d);case'ENV-104':return lamp(b,p,d);default:throw new Error('天空使用程序描述，不可写为体素');}}
const defs:[string,V3,string][]=[['ENV-086',[8,2.4,3],'地面院廊岩土缘与真实0.2米细柱支撑'],['ENV-088',[8,3.2,12],'实际填挖路肩及保留河下空域的高架接边'],['ENV-091',[6,1,2],'贯通边沟、转角和集水节点的真实金属孔篦'],['ENV-094',[8,.6,8],'真实厚石板、水平回纹和不覆盖中央洞口的地坪'],['ENV-096',[6,1.4,2],'真空长槽及开底树池厚石框'],['ENV-097',[2.4,1.8,2.4],'真口、厚陶瓷壁、排水孔的公共花盆/矮缸'],['ENV-098',[3.6,1.6,1.2],'分材质木椅与石凳，共同座面和真实承脚'],['ENV-104',[2.8,4.2,1.2],'独立灯杆/石灯、透明玻璃和分离光学芯'],['ENV-110',[28000,28000,28000],'作者连续昼夜渐变球壳'],['ENV-112',[136,136,136],'按作者日向放置的太阳视觉球'],['ENV-113',[76,76,76],'反日向月亮视觉球与作者表面斑纹'],['ENV-114',[26036,26036,26036],'固定种子600星点烘入一张透明天空贴图']];
export const landscapeRecipes:Record<string,AtlasRecipe>=Object.fromEntries(defs.map(([id,size,features])=>[id,{size,pitch,features,limits:Number(id.slice(4))>=110?skyLimits:physicalLimits,expectedComponents:Number(id.slice(4))>=110?0:1,draw:(b:Shapes)=>draw(b,id,landscapeDefaults[id],{openings:[]})}]));
const skyConfig:Record<string,{kind:SkyDescriptor['kind'];radius:number;roles:Record<string,string>}>={'ENV-110':{kind:'dome',radius:14000,roles:{zenith:'skyZenith',horizon:'skyHorizon',dusk:'skyDusk',night:'skyNight'}},'ENV-112':{kind:'sun',radius:68,roles:{surface:'sunSurface',edge:'sunEdge'}},'ENV-113':{kind:'moon',radius:38,roles:{surface:'moonSurface',maria:'moonMaria'}},'ENV-114':{kind:'stars',radius:13000,roles:{points:'starPoint'}}};
const roleSets:Record<string,string[]>={'ENV-086':['bedrock','weatheredRock','surfaceSoil','soilSubstrate'],'ENV-088':['bedrock','soilSubstrate','surfaceSoil','drainAggregate','earthCutaway'],'ENV-091':['wall','drainGrate'],'ENV-094':['bedrock','wall','mortar','stone'],'ENV-096':['wall','stone','mortar'],'ENV-097':['stone','ceramicWhite'],'ENV-098':['wall','wood','woodEdge','fabric','bronze'],'ENV-104':['wall','stone','wood','metal','bronze','landscapeGlass','landscapeEmitter']};
export function inspectLandscapeMaterials(id:string,a:Asset,s:Record<string,number>){if(!landscapeRecipes[id])return null;const allowed=skyConfig[id]?Object.values(skyConfig[id].roles):roleSets[id],used=new Set(a.sky?Object.values(a.sky.materials):[...[...new Grid(a.chunks).cells()].map(([,m])=>m),...(a.meshes??[]).map(m=>m.material)]);for(const m of used)if(!allowed.some(r=>s[r]===m))throw new Error(id+' 错误用途材质 '+m);if(a.sky)for(const[k,role]of Object.entries(skyConfig[id].roles))if(a.sky.materials[k]!==s[role])throw new Error(id+' 天空用途映射错位');return{revision:1,method:a.sky?'procedural-role-binding-and-derived-colour-check':'authored-use-and-actual-voxel-check',note:'金属孔篦、陶瓷容器、石材、座垫织物、硬玻璃与光学芯独立；天空角色是非碰撞视觉色层，原生描述保存映射，零物理格不代表空模型。'};}
export function makeLandscapeAsset(catalogId:string,name:string,id:string,style:Record<string,number>,input:Params={}):Asset{const r=landscapeRecipes[catalogId];if(!r)throw new Error('尚无景观/天空配方');const p=parameters(catalogId,input),s=new Proxy(style,{get(t,k){if(typeof k==='symbol')return Reflect.get(t,k);if(!Number.isInteger(t[k])||t[k]<1)throw new Error('缺少用途材质 '+k);return t[k];}}),d:Detail={openings:[]},source={kind:'catalog-recipe',catalogId,recipeRevision:3,styleReference:productionReference,styleRevision:productionStyleRevision,parameters:p,nominalDesignSizeM:r.size,features:r.features,geometryStage:'candidate',reference:atlasSource(catalogId),referenceStage:'candidate',limitations:r.limits,units:'metres',front:'-Z',gameIntegration:false,animation:false,detail:d};let a:Asset;
 if(skyConfig[catalogId]){const c=skyConfig[catalogId];a={id,name,version:1,category:'base',cellSize:pitch,origin:[0,0,0],chunks:{},parts:[],openings:[],ports:[],source,sky:{version:1,kind:c.kind,radiusM:c.radius,distanceM:c.kind==='sun'||c.kind==='moon'?12000:0,segments:[64,32],seed:104,starCount:c.kind==='stars'?600:0,materials:Object.fromEntries(Object.entries(c.roles).map(([k,v])=>[k,s[v]])),hour:Number(p.hour),weather:p.weather as 'clear'|'overcast',visibility:Number(p.visibility),clockSource:'author-preview',originalStateBound:false}};d.originalNumericSize=c.kind==='stars'?null:c.radius;d.originalSizeMeaningVerified=false;d.authorSizeInterpretation='radius';d.originalStarPrimitive='600 seeded points';d.authoredStarPrimitive='600 seeded stars baked into one RGBA sky texture';d.nativeAuthority='sky descriptor and exported RGBA texture';d.autoLOD=false;
 }else{if(catalogId==='ENV-097'&&p.vesselForm==='bonsai')source.limitations=physicalLimits.replace('基础块件保留0.2m体素','盆景浅盆的基础块件保留0.04m体素');const b=new Shapes(catalogId==='ENV-097'&&p.vesselForm==='bonsai'?.04:pitch,s);draw(b,catalogId,p,d);a=b.finish(id,name,source);if(catalogId==='ENV-088')a.meshes=shoulderMeshes(p,s);a.openings=d.openings;a.ports[0].position=[0,0,0];a.source!.terrain={physicalPitchM:a.cellSize,editPitchM:a.cellSize,layer:'voxel blocks only',displaySource:'native voxel blocks',continuousMeshSource:a.meshes?'asset.meshes positions and indices':null,collisionSource:a.meshes?'solid cells plus authored collision mesh triangles':'solid native cells',originalWorldBound:false,autoLOD:false};}
 const bounds=assetBoundsM(a)!;a.source!.dimensionsM=bounds.max.map((n,i)=>n-bounds.min[i]);a.source!.materialAssignmentReview=inspectLandscapeMaterials(catalogId,a,style);return a;}
