import {Shapes} from './shapes';
import {Grid} from '../core/grid';
import {connectedLine,bladeLeaf} from '../core/voxel-shapes';
import type {Asset,V3} from '../core/types';
import type {AtlasRecipe} from './atlas-life';
import {atlasSource} from './atlas-life';
import {productionReference,productionStyleRevision} from './style';
const pitch=.2, q=(n:number)=>Math.round(n/pitch), mod=(n:number,m:number)=>(n%m+m)%m;
type Params=Record<string,number|string>;
type Segment={from:V3;to:V3;radii:[number,number]};
type Crown={center:V3;radii:V3;role:string;seed:number};
type Anatomy={segments:Segment[];crowns:Crown[];[key:string]:unknown};
const limits='完整0.2m原生占用为编辑/显示/固体碰撞权威，米制Y向上。作者几何候选，未获人工美术验收。原terrainHeight、坡度/湿度分区、道路建筑排除、生态状态和384m森林驻留控制器未收件；无自动距离LOD、风动或生长模拟。远景仅精确共面合并，保留所有原生冠量。';
export const ecologyDefaults:Record<string,Params>={'ENV-037':{waterWidth:4},'ENV-038':{bankProfile:'gentle'},'ENV-043':{foamShape:'patch'},'ENV-050':{height:16},'ENV-052':{},'ENV-054':{},'ENV-055':{},'ENV-056':{},'ENV-057':{},'ENV-059':{rootForm:'rockGrip'},'ENV-060':{},'ENV-061':{habit:'spreading'}};
export function ecologyParameters(id:string):Record<string,any>{const choice=(values:(number|string)[],value:number|string,description:string)=>({type:typeof value==='string'?'string':'number',enum:values,default:value,description});switch(id){case'ENV-037':return{waterWidth:choice([4,24],4,'作者4米源溪/24米主瀑岩唇，不绑定原世界高程')};case'ENV-038':return{bankProfile:choice(['gentle','steep','shingle'],'gentle','自然缓坡/岩壁/砾岸断面')};case'ENV-043':return{foamShape:choice(['patch','crest'],'patch','静态泡沫斑/泡沫脊，同一母版族')};case'ENV-050':return{height:choice([16,24,31],16,'作者树高研究；原16–31m高程参数含义未获原代码核实')};case'ENV-059':return{rootForm:choice(['buttress','shallow','rockGrip'],'rockGrip','板根/浅根/附岩根接口族，含明确作者承托岩样')};case'ENV-061':return{habit:choice(['low','spreading'],'spreading','低矮/展开花灌木，不按花色计模型')};default:return{};}}
export function ecologyVariants(id:string):Params[]{let all:Params[]=[{}];for(const[k,d]of Object.entries(ecologyParameters(id)))all=all.flatMap(p=>d.enum.map((v:number|string)=>({...p,[k]:v})));return all;}
function parameters(id:string,p:Params){const defs=ecologyParameters(id);for(const[k,v]of Object.entries(p))if(!defs[k]?.enum.includes(v))throw new Error('未验证的水岸/植被参数 '+k);return{...ecologyDefaults[id],...p};}
/** Face-connected tapered native branch. Leaf writes never erase this wood skeleton. */
function limb(b:Shapes,a:V3,end:V3,r0:number,r1:number,m:number,an?:Anatomy){const line=new Grid();connectedLine(line,pitch,a,end,m);const d=end.map((v,i)=>v-a[i]),length2=d.reduce((s,v)=>s+v*v,0);for(const[c]of line.cells()){const t=length2?Math.max(0,Math.min(1,c.reduce((s,v,i)=>s+(v*pitch-a[i])*d[i],0)/length2)):0,r=Math.max(.11,r0+(r1-r0)*t),n=Math.ceil(r/pitch);for(let x=-n;x<=n;x++)for(let y=-n;y<=n;y++)for(let z=-n;z<=n;z++)if((x*x+y*y+z*z)*pitch*pitch<=r*r+1e-8&&c[1]+y>=0)b.g.set([c[0]+x,c[1]+y,c[2]+z],m);}an?.segments.push({from:a,to:end,radii:[r0,r1]});}
function cluster(b:Shapes,c:V3,r:V3,role:string,seed:number,an?:Anatomy){const min=c.map((v,i)=>Math.floor((v-r[i])/pitch)),max=c.map((v,i)=>Math.ceil((v+r[i])/pitch));for(let x=min[0];x<max[0];x++)for(let y=Math.max(0,min[1]);y<max[1];y++)for(let z=min[2];z<max[2];z++){const v:V3=[x,y,z],D=v.map((n,i)=>((n+.5)*pitch-c[i])/r[i]),norm=D.reduce((s,n)=>s+n*n,0),angle=Math.atan2(D[2],D[0]),edge=1-.10*(1+Math.sin(3*angle+seed)*Math.cos(D[1]*4+seed));if(norm<=edge&&!b.g.get(v))b.g.set(v,norm>.65&&y>q(c[1])&&mod(Math.floor(x/3)+Math.floor(z/3)+seed,5)===0?b.s.canopyLeafTip:b.s[role]);}an?.crowns.push({center:c,radii:r,role,seed});}
function roots(b:Shapes,radius:number,m:number,an:Anatomy){for(let i=0;i<6;i++){const a=i*Math.PI/3+.2,tip:V3=[radius*Math.cos(a),0,radius*Math.sin(a)];limb(b,[0,.8,0],tip,.42,.13,m,an);}}
function tree(b:Shapes,id:string,height:number,an:Anatomy){const bark=b.s.treeBark,scale=height/16;
 b.part('树干与真实多点接地根脚',()=>{roots(b,id==='ENV-057'?2.4:1.6*scale,bark,an);const pts:V3[]=id==='ENV-054'?[[0,0,0],[.1,3,0],[-.7,6,.2],[-.2,9,.2],[.8,12,0]]:id==='ENV-055'?[[0,0,0],[0,4,0],[.1,8,.2],[.1,12,0]]:id==='ENV-057'?[[0,0,0],[.2,2.4,0],[-.3,4.8,.2]]:[[0,0,0],[.2*scale,height*.2,0],[-.4*scale,height*.4,.2*scale],[.2*scale,height*.62,0],[-.3*scale,height*.87,.3*scale]];for(let i=1;i<pts.length;i++)limb(b,pts[i-1],pts[i],(id==='ENV-057'?.85:.65*scale)*(1-(i-1)/pts.length),.16+(pts.length-i)*.1*scale,bark,an);});
 const crowns:Crown[]=[];
 b.part('独立主枝和分叉次级枝架，保留冠间开口',()=>{
 if(id==='ENV-055'){for(let i=0;i<9;i++){const a=i*2.4,y=4+i*.72,end:V3=[Math.cos(a)*(1.15-i*.05),9+i*.37,Math.sin(a)*(1.15-i*.05)];limb(b,[0,y,0],end,.25,.12,bark,an);crowns.push({center:end,radii:[.8,2.6-i*.11,.8],role:'cypressScale',seed:i});}crowns.push({center:[.1,12.6,0],radii:[.7,1.4,.7],role:'cypressScale',seed:10});}
 else if(id==='ENV-057'){limb(b,[.1,2.4,0],[-.3,7.9,.2],.5,.18,bark,an);crowns.push({center:[-.3,7.9,.2],radii:[2.4,1.8,2.3],role:'canopyLeaf',seed:23});for(let i=0;i<6;i++){const a=i*1.047+.3,end:V3=[Math.cos(a)*3.6,6.3+(i%3)*.6,Math.sin(a)*3.6];limb(b,[.1,2.4,0],end,.55,.23,bark,an);for(const k of[-1,1]){const e:V3=[end[0]+Math.cos(a+k*.6)*1.5,end[1]+1.2,end[2]+Math.sin(a+k*.6)*1.5];limb(b,end,e,.24,.11,bark,an);crowns.push({center:e,radii:[2,1.35,1.65],role:'canopyLeaf',seed:i*2+k+1});}}}
 else for(let level=0;level<4;level++){const y=id==='ENV-054'?4+level*2.35:height*(.31+level*.17),reach=(id==='ENV-054'?4.0-level*.55:id==='ENV-052'?3.6-level*.45:4.1-level*.55)*scale;for(let i=0;i<3;i++){const angle=i*2.094+level*.95+(id==='ENV-052'?.55:0),start:V3=[-.2*scale,y,0],end:V3=[Math.cos(angle)*reach,y+(id==='ENV-054'?.65:1.15*scale),Math.sin(angle)*reach];limb(b,start,end,.3*scale,.13*scale,bark,an);for(const sign of[-1,1]){const e:V3=[end[0]+Math.cos(angle+sign*.8)*.8*scale,end[1]+.4*scale,end[2]+Math.sin(angle+sign*.8)*.8*scale];limb(b,end,e,.14*scale,.11,bark,an);crowns.push({center:e,radii:[(id==='ENV-054'?1.75:1.65)*scale,(id==='ENV-054'?.55:.85)*scale,1.4*scale],role:id==='ENV-054'?'pineNeedle':'canopyLeaf',seed:level*6+i*2+(sign+1)/2});}}}
 });
 b.part('枝端真实量化叶簇，成熟叶与新梢分材质',()=>{for(const c of crowns)cluster(b,c.center,c.radii,c.role,c.seed,an);});
 b.part('连续顶梢和顶端冠，不把细杆顶盒当树种',()=>{if(id==='ENV-050'||id==='ENV-052'){const top:V3=[-.3*scale,height-1.2*scale,.3*scale];limb(b,[-.3*scale,height*.87,.3*scale],top,.17*scale,.11,bark,an);cluster(b,top,[1.3*scale,1.2*scale,1.2*scale],'canopyLeaf',31,an);}else if(id==='ENV-054'){limb(b,[.8,12,0],[.9,13.2,0],.2,.11,bark,an);cluster(b,[.9,13.2,0],[1.3,.8,1.2],'pineNeedle',32,an);}});
}
function bamboo(b:Shapes,an:Anatomy){const culms=[{x:0,z:0,height:8.4},{x:2,z:1,height:6.8},{x:-1.8,z:1.2,height:4.8}];an.culms=culms;an.hollowCellWidthM=.2;an.nodeSpacingM=.8;
 b.part('三竿共生根茎，底锚连接不以土台替代竹根',()=>{for(const c of culms)limb(b,[0,0,0],[c.x,0,c.z],.14,.11,b.s.bambooCulm,an);});
 b.part('真实中空竹竿，0.6m量化外径和0.2m内孔',()=>{for(const c of culms)for(let y=0;y<q(c.height);y++)for(let x=-1;x<=1;x++)for(let z=-1;z<=1;z++)if(x||z)b.g.set([q(c.x)+x,y,q(c.z)+z],b.s.bambooCulm);});
 b.part('每0.8m实竹节与内部节隔，上切口保持空腔',()=>{for(const c of culms)for(let y=0;y<q(c.height)-1;y+=4)for(let x=-1;x<=1;x++)for(let z=-1;z<=1;z++)b.g.set([q(c.x)+x,y,q(c.z)+z],b.s.bambooNode);});
 const leaves:{base:V3;angle:number}[]=[];
 b.part('竹节上实接细枝，不借普通树干配方',()=>{for(const[ci,c]of culms.entries())for(let y=2.4;y<c.height-.6;y+=1.6)for(const sign of[-1,1]){const angle=y+ci+sign*.9,start:V3=[c.x+Math.cos(angle)*.2,y,c.z+Math.sin(angle)*.2],end:V3=[c.x+Math.cos(angle)*1.2,y+.35,c.z+Math.sin(angle)*1.2];limb(b,start,end,.11,.11,b.s.bambooCulm,an);for(let k=0;k<3;k++)leaves.push({base:end.map((v,i)=>v-(end[i]-start[i])*k*.22) as V3,angle:angle+(k%2?-.6:.6)});}});
 b.part('带空隙的尖长竹叶，原生细格叶片和中脉相连',()=>{for(const l of leaves)bladeLeaf(b.g,pitch,l.base,1.25,.4,l.angle,-.3,b.s.bambooBlade,.12);});
}
function shrubs(b:Shapes,id:string,habit:string,an:Anatomy){const low=id==='ENV-060',scale=low?1:habit==='low'?1.15:1.65,centres:V3[]=low?[[0,1.2,.1],[-.75,1.0,.05],[.75,1.05,.05],[-.4,.95,-.6],[.45,.95,.75]]:[[0,1.35,.1],[-.9,1,.1],[.9,1.1,0],[-.4,1,-.8],[.5,1,.8]];
 b.part('多根分叉木质细枝与连续接地根颈',()=>{limb(b,[0,0,0],[0,.7*scale,0],.14,.11,b.s.shrubTwig,an);for(const c of centres){const e=c.map(n=>n*scale) as V3;limb(b,[0,.3*scale,0],e,.13,.11,b.s.shrubTwig,an);for(const d of[-1,1])limb(b,[e[0]*.7,e[1]*.8,e[2]*.7],[e[0]+d*.3*scale,e[1]+.1*scale,e[2]],.11,.11,b.s.shrubTwig,an);}});
 b.part('彼此交错且保留根际透空的真实灌木叶簇',()=>{for(const[i,c]of centres.entries())cluster(b,c.map(n=>n*scale) as V3,[.72*scale,.6*scale,.55*scale],'shrubLeaf',i,an);});
 if(!low)b.part('枝端量化花簇与独立花药，均非灯芯和非自发光',()=>{for(const[i,c]of centres.entries())for(const side of[-1,1]){const v:V3=[q(c[0]*scale+side*.3*scale),q((c[1]+.35)*scale),q(c[2]*scale)],base:V3=[v[0],v[1]-1,v[2]];connectedLine(b.g,pitch,c.map(n=>n*scale) as V3,base.map(n=>n*pitch) as V3,b.s.shrubLeaf);for(const d of[[1,0,0],[-1,0,0],[0,0,1],[0,0,-1],[0,1,0]])b.g.set(v.map((n,k)=>n+d[k]) as V3,b.s.shrubBlossom);b.g.set(v,b.s.pollenAnther);}});
 else b.part('原给定2.8×1.8×2.2米的边缘叶梢',()=>{for(const[a,e]of[[[-.7,1,.05],[-1.4,1,0]],[[.7,1,.05],[1.2,1,0]],[[0,1.2,.1],[0,1.6,0]],[[-.4,.95,-.6],[-.4,1,-1]],[[.45,.95,.75],[.4,1,1]]] as [V3,V3][])connectedLine(b.g,pitch,a,e,b.s.shrubLeaf);});
}
function rootStudy(b:Shapes,form:string,an:Anatomy){const rock=form==='rockGrip';
 b.part('明确作者支承岩样，不冒称原terrainHeight',()=>{if(rock){for(let x=-17;x<18;x++)for(let z=-14;z<15;z++){const X=(x+.5)*pitch,Z=(z+.5)*pitch;let h=0;for(const[cx,cz,r,top]of[[-1.6,-.6,2.1,2],[.4,.2,2.2,2.8],[2,1,1.8,1.6]]){const d=(X-cx)**2+(Z-cz)**2;if(d<r*r)h=Math.max(h,top*Math.sqrt(1-d/(r*r)));}for(let y=0;y<q(h);y++)b.g.set([x,y,z],y<3?b.s.bedrock:b.s.weatheredRock);}}else b.b(-3.6,0,-3.2,7.2,.2,6.4,b.s.bedrock);});
 const surface=new Map<string,number>();for(const[v]of b.g.cells())surface.set(v[0]+','+v[2],Math.max(surface.get(v[0]+','+v[2])??0,v[1]+1));const top=(x:number,z:number)=>(surface.get(q(x)+','+q(z))??0)*pitch,neck=top(0,0);an.supportSample='explicit authored rock geometry';an.rootEndpoints=[];
 b.part('截桩树皮与独立切面心材',()=>{b.cylinder(0,neck,0,.8,1.6,b.s.treeBark);b.cylinder(0,neck+1.4,0,.6,.2,b.s.rootHeartwood);});
 b.part('六向贴岩主根和实际落地点',()=>{for(let i=0;i<6;i++){const angle=i*Math.PI/3+.15;let previous:V3=[0,neck+.6,0];for(let k=1;k<=12;k++){const r=k*.3,X=Math.cos(angle)*r,Z=Math.sin(angle)*r,y=rock?top(X,Z):.2+(form==='buttress'?1.2: .25)*(1-k/12),end:V3=[X,y,Z];limb(b,previous,end,.4*(1-k/15),.13,b.s.treeBark,an);previous=end;}(an.rootEndpoints as V3[]).push(previous);}});
 b.part('接根端分叉，根皮和心材不借通用木色',()=>{for(const e of an.rootEndpoints as V3[]){limb(b,e,[e[0]-.3,Math.max(0,e[1]-.2),e[2]+.2],.12,.11,b.s.treeBark,an);}});
}
function reeds(b:Shapes,sites:V3[]){for(const[i,p]of sites.entries())for(const side of[-1,1])bladeLeaf(b.g,pitch,p,1.2+(i%3)*.2,.25,i*1.7+side*.5,1.1,b.s.reedBlade,.1);}
function headwater(b:Shapes,width:number){const half=width/2,nz=60,bankSites:V3[]=[];
 b.part('源溪与岩唇同源岩床，真实厚岩和曲折岸肩',()=>{for(let z=0;z<nz;z++){const Z=(z+.5)*pitch,c=Math.sin(Z*Math.PI/12)*.6,outer=half+1.8+.4*Math.sin(Z*.8);for(let x=Math.floor((-outer+c)/pitch);x<Math.ceil((outer+c)/pitch);x++){const X=(x+.5)*pitch,wet=Math.abs(X-c)<=half,h=wet?20:22+mod(Math.floor(z/7)+Math.floor(x/5),4);for(let y=0;y<h;y++)b.g.set([x,y,z],y<9?b.s.bedrock:y<17?b.s.weatheredRock:b.s.waterWornRock);if(!wet&&Math.abs(X-c)>half+.6&&z%17===8&&x%7===0)bankSites.push([x*pitch,h*pitch,z*pitch]);}}});
 b.part('由同源河床派生的0.2m流水层及岩唇泡沫',()=>{for(let z=0;z<nz;z++){const c=Math.sin((z+.5)*pitch*Math.PI/12)*.6;for(let x=Math.floor((c-half)/pitch);x<Math.ceil((c+half)/pitch);x++)if(b.g.get([x,19,z])&&!b.g.get([x,20,z]))b.g.set([x,20,z],z<2&&mod(x,4)<2?b.s.waterFoam:b.s.flowWater);}});
 b.part('岸肩湿土和薄苔面，保持水床高度一致',()=>{for(const p of bankSites){b.g.set([q(p[0]),q(p[1])-1,q(p[2])],b.s.wetSoil);b.g.set([q(p[0])+1,q(p[1])-1,q(p[2])],b.s.moss);}});
 b.part('实际根接岸肩的挺水叶，不悬空放置',()=>reeds(b,bankSites));
}
function bank(b:Shapes,profile:string){const tops=new Map<string,number>(),sites:V3[]=[];
 b.part('自然起伏水岸断面，完整岩基和有厚度岸土',()=>{for(let x=0;x<40;x++)for(let z=0;z<60;z++){const X=(x+.5)*pitch,Z=(z+.5)*pitch,shore=2.8+.4*Math.sin(Z*.6)+.2*Math.sin(Z*1.2),d=X-shore,h=d<0?.6+Math.max(0,d+1)*.6:profile==='steep'?3.6+.4*Math.sin(Z*.8):profile==='shingle'?1.2+d*.17:1.2+d*.38,H=Math.max(2,q(h));tops.set(x+','+z,H);for(let y=0;y<H;y++)b.g.set([x,y,z],y<2?b.s.bedrock:y===H-1?(d<.5?b.s.wetSoil:profile==='steep'?b.s.weatheredRock:b.s.surfaceSoil):profile==='steep'?b.s.waterWornRock:b.s.soilSubstrate);if(d>1&&d<3&&x%8===0&&z%14===6)sites.push([x*pitch,H*pitch,z*pitch]);}});
 b.part('实河床上的水层，不穿土岩或悬空',()=>{for(let x=0;x<40;x++)for(let z=0;z<60;z++){const h=tops.get(x+','+z)!;for(let y=h;y<6;y++)b.g.set([x,y,z],b.s.flowWater);}});
 b.part('岸边实接水蚀砾，石滩另有完整角砾带',()=>{for(let z=4;z<57;z+=7){const x=profile==='shingle'?19+mod(z,5):14+mod(z,3),h=tops.get(x+','+z)!;b.b(x*pitch,h*pitch,z*pitch,.6,.4,.6,b.s.waterWornRock);b.b((x+1)*pitch,(h+2)*pitch,(z+1)*pitch,.2,.2,.2,b.s.weatheredRock);}});
 b.part('自然岸土上的实根挺水叶',()=>reeds(b,sites));
}
function foam(b:Shapes,shape:string){b.part('连续静态泡沫主体，无独立水床和碰撞',()=>{for(let x=-2;x<(shape==='patch'?2:5);x++)for(let z=-2;z<2;z++)if(!(x===-2&&z===-2)&&!(x===(shape==='patch'?1:4)&&z===1))b.g.set([x,0,z],b.s.waterFoam);});b.part('真细格起伏泡脊，复用数量不增加母版',()=>{for(let x=-1;x<(shape==='patch'?1:4);x++)b.g.set([x,1,0],b.s.waterFoam);if(shape==='crest')for(let x=0;x<3;x++)b.g.set([x,2,0],b.s.waterFoam);});}
const definitions:[string,V3,string,string][]=[
 ['ENV-037',[8.4,6.8,12],'曲折上游来水、厚岩床和一致瀑口岩唇','4/24m水宽参数；原水源与世界岩崖高程未收件，明确作者流向-Z与4.2m水位。'],
 ['ENV-038',[8,5.4,12],'缓坡、陡岩与砾岸三个真实断面','自然岸线起伏；断面外边是样段裁边，需续接原地形，不能冒称完整自然岸。'],
 ['ENV-043',[.8,.4,.8],'静态体素泡沫斑及泡脊','80源放置共享一个母版，样件编译为原生并集；非GPU实例、非粒子寿命或冲击模拟。'],
 ['ENV-050',[14,16,14],'四级错层实分枝乔木与量化叶簇','16/24/31m为作者树高研究，原“高程参数”含义未获原源码核实，不声称原树高复原。'],
 ['ENV-052',[12,14,12],'保持完整树冠的近远林冠代理','原近4/远2层、384m批次是源清单描述。本作完整原生冠量近远精确共面合并，没有自动距离切换。'],
 ['ENV-054',[14,14,14],'斜干、长侧枝与扁平松针簇','松针与成熟阔叶用途独立；真实分枝和冠间透空。'],
 ['ENV-055',[5,14,5],'上举分枝、紧密柱冠与独立柏鳞叶','柏柱冠与松类平展针簇结构独立。'],
 ['ENV-056',[8,8.4,7],'三竿竹丛、实节隔、中空节间与尖长竹叶','完整0.2m量化令竿外径0.6m、内孔0.2m，为可编辑巨竹作者样件；不是普通树干换色。'],
 ['ENV-057',[15,10,15],'粗干开叉、宽展次枝和阔叶冠','低分叉与宽冠；真实根脚，多点接地，城市通路应另验安装距离。'],
 ['ENV-059',[8,4.6,8],'板根、浅根和附岩根接口族','含明确作者岩样以核实贴附；装饰不替代原地形或原承托。'],
 ['ENV-060',[2.8,1.8,2.2],'保留源包络的细枝低灌木','源2.8×1.8×2.2m包络，改为真实分枝和分簇叶冠。'],
 ['ENV-061',[6,3.6,5],'低矮/展开分枝花灌木','木质细枝、成熟叶、嫩梢、花瓣与花药分别归类；换花色不新增模型。']
];
function draw(b:Shapes,id:string,p:Params,an:Anatomy){switch(id){case'ENV-037':return headwater(b,Number(p.waterWidth));case'ENV-038':return bank(b,String(p.bankProfile));case'ENV-043':return foam(b,String(p.foamShape));case'ENV-056':return bamboo(b,an);case'ENV-059':return rootStudy(b,String(p.rootForm),an);case'ENV-060':case'ENV-061':return shrubs(b,id,String(p.habit),an);default:return tree(b,id,id==='ENV-050'?Number(p.height):id==='ENV-052'?14:16,an);}}
export const ecologyRecipes:Record<string,AtlasRecipe>=Object.fromEntries(definitions.map(([id,size,features,note])=>[id,{size,pitch,features,limits:note+limits,draw:(b:Shapes)=>draw(b,id,ecologyDefaults[id],{segments:[],crowns:[]})}]));
const roleSets:Record<string,string[]>={'ENV-037':['bedrock','weatheredRock','waterWornRock','wetSoil','moss','flowWater','waterFoam','reedBlade'],'ENV-038':['bedrock','weatheredRock','waterWornRock','soilSubstrate','surfaceSoil','wetSoil','flowWater','reedBlade'],'ENV-043':['waterFoam'],'ENV-050':['treeBark','canopyLeaf','canopyLeafTip'],'ENV-052':['treeBark','canopyLeaf','canopyLeafTip'],'ENV-054':['treeBark','pineNeedle','canopyLeafTip'],'ENV-055':['treeBark','cypressScale','canopyLeafTip'],'ENV-056':['bambooCulm','bambooNode','bambooBlade'],'ENV-057':['treeBark','canopyLeaf','canopyLeafTip'],'ENV-059':['bedrock','weatheredRock','treeBark','rootHeartwood'],'ENV-060':['shrubTwig','shrubLeaf','canopyLeafTip'],'ENV-061':['shrubTwig','shrubLeaf','canopyLeafTip','shrubBlossom','pollenAnther']};
export function inspectEcologyMaterials(id:string,a:Asset,s:Record<string,number>){if(!ecologyRecipes[id])return null;const allowed=roleSets[id],p=a.source?.parameters as Params,required=allowed.filter(r=>!(id==='ENV-038'&&(p.bankProfile==='steep'?['soilSubstrate','surfaceSoil']:[]).includes(r))&&!(id==='ENV-059'&&p.rootForm!=='rockGrip'&&r==='weatheredRock')),used=new Set([...new Grid(a.chunks).cells()].map(([,m])=>m));for(const r of required)if(!used.has(s[r]))throw new Error(id+' 缺少实际用途材质 '+r);for(const m of used)if(!allowed.some(r=>s[r]===m))throw new Error(id+' 非约定用途材质 '+m);return{revision:1,method:'authored-use-and-actual-voxel-check',note:'树皮/成熟阔叶/松针/柏鳞叶/竹竿/竹节/竹叶/灌木枝叶/花瓣/花药/湿土/挺水叶按实际用途独立；不按颜色借用，非碰撞植物叶花及水体零发光。'};}
export function makeEcologyAsset(catalogId:string,name:string,id:string,style:Record<string,number>,params:Params={}):Asset{const r=ecologyRecipes[catalogId];if(!r)throw new Error('尚无该水岸/生态母版');const p=parameters(catalogId,params),s=new Proxy(style,{get(t,k){if(typeof k==='symbol')return Reflect.get(t,k);if(!Number.isInteger(t[k])||t[k]<1||t[k]>65535)throw new Error('缺少用途材质 '+k);return t[k];}}),b=new Shapes(pitch,s),an:Anatomy={segments:[],crowns:[]};draw(b,catalogId,p,an);if(b.g.count>1_000_000)throw new Error('生态单母版超过百万原生占用格预算');const bounds=b.g.bounds()!,a=b.finish(id,name,{kind:'catalog-recipe',catalogId,recipeRevision:3,styleReference:productionReference,styleRevision:productionStyleRevision,parameters:p,dimensionsM:bounds.max.map((n,i)=>(n-bounds.min[i])*pitch),envelopeM:r.size,features:r.features,geometryStage:'candidate',reference:atlasSource(catalogId),referenceStage:'candidate',limitations:r.limits,units:'metres',front:'-Z',gameIntegration:false,animation:false,anatomy:an,terrain:{physicalPitchM:pitch,editPitchM:pitch,displaySource:'native occupancy',collisionSource:'native occupied solid materials',originalWorldBound:false,autoLOD:false}});
 a.ports[0].position=[0,0,0];a.source!.anchor='local root foot origin / section bottom; full occupied support checked in authored installations';
 if(catalogId==='ENV-037'||catalogId==='ENV-038'){const points:V3[]=catalogId==='ENV-037'?[[0,4.2,12],[.6,4.2,6],[0,4.2,0]]:[[1.2,1.2,12],[1.2,1.2,0]];a.source!.waterFlow={routes:[{points,startDistanceM:0}],materialIds:[s.flowWater,s.waterFoam],animated:false,originalRouteBound:false};for(const[k,index,normal]of[['inlet',0,[0,0,1]],['outlet',points.length-1,[0,0,-1]]] as [string,number,V3][])a.ports.push({id:k,kind:'water-route',position:points[index],normal,size:[catalogId==='ENV-037'?Number(p.waterWidth):2.4,.2,0],pitch});}
 if(catalogId==='ENV-043'){a.source!.waterFlow={routes:[{points:[[-.4,.2,0],[1,.2,0]],startDistanceM:0}],materialIds:[s.waterFoam],animated:false,originalRouteBound:false};a.source!.foamUV='author local metre frame only; impact and fluid direction unbound';}
 if(catalogId==='ENV-052')a.source!.forestProxy={legacyNearLayers:4,legacyFarLayers:2,legacyBatchM:384,originalRuntimeBound:false,fullNativeCanopyPreserved:true};
 a.source!.materialAssignmentReview=inspectEcologyMaterials(catalogId,a,style);return a;}
