import type {Asset} from '../core/types';import {Grid} from '../core/grid';import {assetBoundsM} from '../core/sky';import {validateRig} from '../core/rig';import {AvatarModel} from './avatar-model';import {garmentRig} from './garment-shapes';import {buildCostume} from './costume-cuts';import {atlasSource,type AtlasRecipe} from './atlas-life';import {productionReference,productionStyleRevision} from './style';
type Params=Record<string,string|number>;
export function costumeParameters(id:string):Record<string,any>{return id==='CHAR-125'?{}:{costumeFit:{type:'string',enum:id==='CHAR-126'?['child','teen']:['adultA','adultB'],default:id==='CHAR-126'?'child':'adultA',description:'作者独立年龄/成人体型，非原游戏年龄或职业控制器'}};}
export function costumeVariants(id:string):Params[]{return id==='CHAR-125'?[{}]:costumeParameters(id).costumeFit.enum.map((costumeFit:string)=>({costumeFit}));}
const features:Record<string,string>={'CHAR-125':'独立婴儿包衣；自身年龄比例，双布系带与真袖口','CHAR-126':'学堂童装长襟；双肩织带、书签袋与腰扣','CHAR-127':'警务立领制服；胸袋、织带与独立身份扣','CHAR-128':'守卫防护衣；分区金属胸板、肩板与软垫','CHAR-129':'驾驶调度衣；斜挂织带、长口袋与身份扣','CHAR-130':'工坊劳动衣；耐磨肘片、工具袋与收束袖口','CHAR-131':'田作交领短袖衣；浅袖、种袋和斜襟加固','CHAR-132':'医生偏襟诊疗衣；窄器械袋与可换身份扣','CHAR-133':'护理长襟衣；独立前袋、织腰带与身份扣','CHAR-134':'实验前敞口外套；长下摆和双大袋','CHAR-135':'店员短上衣；独立围腰和工具袋','CHAR-136':'独立胸兜围裙；真穿颈/腰环与开口工具袋'};
const limits='技术候选：最小扣件/织标为5mm原生体素，衣面/斜襟/口袋/护板为连续网格。单分件刚性关节，不含软布、软权重、动作片段或原骨架控制器；不夹带图中头、帽、背包或工具。视觉层非碰撞，人工美术验收0。穿戴范围须以本批实际验证报告为准。';
// Fixed after explicit component and attachment study, before production.
export const costumeComponents:Record<string,number>={'CHAR-125':2,'CHAR-126':4,'CHAR-127':4,'CHAR-128':5,'CHAR-129':4,'CHAR-130':5,'CHAR-131':2,'CHAR-132':6,'CHAR-133':7,'CHAR-134':4,'CHAR-135':4,'CHAR-136':5};
export const costumeExpectedComponents=(id:string,params:Params)=>costumeComponents[id];
export const costumeRecipes:Record<string,AtlasRecipe>=Object.fromEntries(Object.entries(features).map(([id,features])=>[id,{size:[.65,1.2,.5],pitch:.005,features,limits,expectedComponents:costumeComponents[id],draw:()=>{throw new Error('使用模块服装混合工厂');}}]));
export function inspectCostumeMaterials(id:string,a:Asset,s:Record<string,number>){if(!costumeRecipes[id])return null;const specific:Record<string,string[]>={'CHAR-125':['infantWrap'],'CHAR-126':['schoolCloth'],'CHAR-127':['uniformCloth','uniformIdBack','uniformIdPrint'],'CHAR-128':['uniformCloth','armorPlate','armorPad'],'CHAR-129':['uniformCloth','uniformIdBack','uniformIdPrint'],'CHAR-130':['workReinforcement','uniformInsignia'],'CHAR-131':['fieldCloth','workReinforcement'],'CHAR-132':['medicalCloth','uniformIdBack','uniformIdPrint'],'CHAR-133':['medicalCloth','medicalTrim','uniformIdBack','uniformIdPrint'],'CHAR-134':['labCoat'],'CHAR-135':['serviceCloth','apronCloth','uniformIdBack','uniformIdPrint'],'CHAR-136':['apronCloth']},roles=[...specific[id],'garmentOuter','garmentLight','garmentLining','garmentTrim','garmentStrap','garmentBuckle'],used=new Set([...new Grid(a.chunks).cells()].map(([,m])=>m).concat(a.meshes!.map(m=>m.material)));for(const mat of used)if(!roles.some(r=>s[r]===mat))throw new Error(id+'服装材质用途混用 '+mat);return{revision:1,method:'actual-voxel-and-mesh-role-check',roles:roles.filter(r=>used.has(s[r])),note:'织物/耐磨片/护板金属/软垫/塑料身份扣/印刷图形独立；全部非碰撞零发光，不借镜片、灯芯、食品或建筑类别。'};}
export function makeCostumeAsset(catalogId:string,name:string,id:string,style:Record<string,number>,input:Params={}):Asset{const recipe=costumeRecipes[catalogId];if(!recipe)throw new Error('未实现模块衣装');const defs=costumeParameters(catalogId);for(const[k,v]of Object.entries(input))if(!defs[k]?.enum.includes(v))throw new Error('未验证衣装参数 '+k);const params={...Object.fromEntries(Object.entries(defs).map(([k,v])=>[k,v.default])),...input},fit=catalogId==='CHAR-125'?'infant':String(params.costumeFit),s=new Proxy(style,{get(t,k){if(typeof k==='symbol')return Reflect.get(t,k);if(!Number.isInteger(t[k])||t[k]<1)throw new Error('缺少衣装用途材质 '+k);return t[k];}}),m=new AvatarModel(s);garmentRig(m,fit);buildCostume(m,catalogId,fit);const a:Asset={id,name,version:1,category:'base',cellSize:.005,origin:[0,0,0],chunks:m.b.g.serialize(),parts:[{id:'root',name:'原生最小扣件和织标',parent:null,region:m.b.g.bounds()!},...m.b.parts],meshes:m.meshes,rig:m.rig,ports:m.ports,openings:[],source:{kind:'catalog-recipe',catalogId,recipeRevision:1,styleReference:productionReference,styleRevision:productionStyleRevision,parameters:params,features:recipe.features,geometryStage:'candidate',reference:atlasSource(catalogId),referenceStage:'candidate',limitations:limits,units:'metres',front:'-Z',gameIntegration:false,animationClips:false,collision:'none; visual-only',detail:m.detail,...(catalogId==='CHAR-128'?{referenceCaptionMismatch:'Automated atlas description incorrectly describes a railing; actual M037 image and catalogue name identify guard protective clothing. No railing geometry was inferred.'}:{})}};validateRig(a);const b=assetBoundsM(a)!;a.source!.dimensionsM=b.max.map((v,i)=>v-b.min[i]);a.source!.materialAssignmentReview=inspectCostumeMaterials(catalogId,a,style);return JSON.parse(JSON.stringify(a));}
