import type {Asset,V3} from '../core/types';import {Grid} from '../core/grid';import {assetBoundsM} from '../core/sky';import {validateRig} from '../core/rig';import {AvatarModel} from './avatar-model';import {attireRig} from './attire-shapes';import {attireRobe} from './attire-robes';import {rainCape,scarf,rescueVest,pilotWear} from './attire-outer';import {glove} from './attire-gloves';import {bandages,limbBrace} from './attire-supports';import {travelBag} from './attire-bags';import {atlasSource,type AtlasRecipe} from './atlas-life';import {productionReference,productionStyleRevision} from './style';
type Params=Record<string,string|number>;
const param=(values:string[])=>({type:'string',enum:values,default:values[0],description:'作者核验形态；不代表原控制器或尺寸矩阵'});
export function attireParameters(id:string):Record<string,any>{return ['CHAR-147','CHAR-148'].includes(id)?{lid:param(['closed','open'])}:id==='CHAR-142'?{wearFit:param(['adult','child'])}:{costumeFit:param(['adultA','adultB'])};}
export function attireVariants(id:string):Params[]{const[k,d]=Object.entries(attireParameters(id))[0];return d.enum.map((v:string)=>({[k]:v}));}
const features:Record<string,string>={'CHAR-137':'官署礼常服：独立长襟、浅叠片与宽边钟袖','CHAR-138':'婚礼礼服：扩展后摆、前垂绶与大钟袖','CHAR-139':'丧礼素服：窄直衣摆、深色臂带与简洁织边','CHAR-140':'雨披：透明膜与接缝、真面孔、帽腔和侧开披片','CHAR-141':'围巾披肩：真颈环、长短垂片与原生最小流苏','CHAR-142':'防护手套：独立指节真空腔、腕孔和护块','CHAR-143':'水上救生穿戴：分离织壳泡棉、肩带和前扣','CHAR-144':'飞行员护具：皮衣羊绒边、工具袋和束带','CHAR-145':'身体绷带挂件：独立缠布与斜固定带','CHAR-146':'肢体支具：软衬织带、侧杆与实际膝轴','CHAR-147':'旅行背包：真袋腔、衬里、卷毯、侧袋和铰盖','CHAR-148':'细体素挎包：独立长肩带、袋腔和真实铰盖'};
const limits='技术候选：5mm原生最小组件，连续衣面/斜面/曲面；透明雨膜实际alpha导出。角色外观全非碰撞，设备光学片未绑定且零发光。每分件刚性关节；原骨骼、尺寸矩阵与控制器缺失。有限穿戴和开合研究按报告范围，不含软布、IK、防护/医疗/浮力模拟；人工美术验收0。';
export const attireComponents:Record<string,number>={'CHAR-137':5,'CHAR-138':5,'CHAR-139':5,'CHAR-140':1,'CHAR-141':8,'CHAR-142':6,'CHAR-143':2,'CHAR-144':6,'CHAR-145':3,'CHAR-146':5,'CHAR-147':10,'CHAR-148':6};
export const attireExpectedComponents=(id:string,params:Params)=>id==='CHAR-142'&&params.wearFit==='child'?5:attireComponents[id];
/** Default posed extents in metres; parameter variants report their own actual bounds. */
const defaultSizes:Record<string,V3>={"CHAR-137":[0.99828833,1.306,0.35],"CHAR-138":[1.022569988,1.371,0.478],"CHAR-139":[0.99828833,1.276,0.35],"CHAR-140":[0.87835957,1.345,0.522],"CHAR-141":[0.2565,0.918,0.343997451],"CHAR-142":[0.142831917,0.191,0.085],"CHAR-143":[0.38,0.47778543,0.462],"CHAR-144":[0.762944774,0.589,0.297720844],"CHAR-145":[0.719580742,0.383638656,0.240234754],"CHAR-146":[0.22,0.3797,0.197142537],"CHAR-147":[0.504,0.722808988,0.667958507],"CHAR-148":[0.498,1.056821356,0.38599965]};
export const attireRecipes:Record<string,AtlasRecipe>=Object.fromEntries(Object.entries(features).map(([id,features])=>[id,{size:defaultSizes[id],pitch:.005,features,limits,expectedComponents:attireComponents[id],draw:()=>{throw new Error('使用独立衣护具混合工厂');}}]));
export function inspectAttireMaterials(id:string,a:Asset,s:Record<string,number>){if(!attireRecipes[id])return null;const specific:Record<string,string[]>={'CHAR-137':['courtCloth','ceremonyTrim'],'CHAR-138':['weddingCloth','ceremonyTrim'],'CHAR-139':['mourningCloth'],'CHAR-140':['rainMembrane','rainSeam'],'CHAR-141':['scarfCloth','scarfFringe'],'CHAR-142':['gloveLeather','glovePad','equipmentCase','equipmentIndicator'],'CHAR-143':['rescueShell','rescueFoam','rescueReflective'],'CHAR-144':['pilotLeather','pilotFleece','equipmentCase','equipmentIndicator'],'CHAR-145':['bandageCloth'],'CHAR-146':['braceMetal','bracePad'],'CHAR-147':['travelCanvas','travelLeather','bagHardware','bagLining','equipmentCase','equipmentIndicator'],'CHAR-148':['travelCanvas','travelLeather','bagHardware','bagLining','equipmentCase','equipmentIndicator']},roles=[...specific[id],'garmentLight','garmentLining','garmentTrim','garmentStrap','garmentBuckle'],used=new Set([...new Grid(a.chunks).cells()].map(([,m])=>m).concat(a.meshes!.map(m=>m.material)));for(const mat of used)if(!roles.some(r=>s[r]===mat))throw new Error(id+'衣护具材质用途混用 '+mat);return{revision:1,method:'actual-voxel-and-mesh-role-check',roles:roles.filter(r=>used.has(s[r])),note:'织物、皮革、塑料膜、橡胶、泡棉、金属和未绑定光学片独立；全部非碰撞零发光。'};}
export function makeAttireAsset(catalogId:string,name:string,id:string,style:Record<string,number>,input:Params={}):Asset{const recipe=attireRecipes[catalogId];if(!recipe)throw new Error('未实现衣护具');const defs=attireParameters(catalogId);for(const[k,v]of Object.entries(input))if(!defs[k]?.enum.includes(v))throw new Error('未验证衣护具参数 '+k);const params={...Object.fromEntries(Object.entries(defs).map(([k,v])=>[k,v.default])),...input},fit=String(params.costumeFit??params.wearFit??'adultA'),s=new Proxy(style,{get(t,k){if(typeof k==='symbol')return Reflect.get(t,k);if(!Number.isInteger(t[k])||t[k]<1)throw new Error('缺少衣护具用途材质 '+k);return t[k];}}),m=new AvatarModel(s),n=Number(catalogId.slice(5));if(n!==142&&n<147)attireRig(m,fit,catalogId);if(n<=139)attireRobe(m,catalogId,fit);else if(n===140)rainCape(m,fit);else if(n===141)scarf(m,fit);else if(n===142)glove(m,fit);else if(n===143)rescueVest(m,fit);else if(n===144)pilotWear(m,fit);else if(n===145)bandages(m,fit);else if(n===146)limbBrace(m,fit);else travelBag(m,catalogId,String(params.lid));const a:Asset={id,name,version:1,category:'base',cellSize:.005,origin:[0,0,0],chunks:m.b.g.serialize(),parts:[{id:'root',name:'原生最小扣件/织花/护块',parent:null,region:m.b.g.bounds()!},...m.b.parts],meshes:m.meshes,rig:m.rig,ports:m.ports,openings:[],source:{kind:'catalog-recipe',catalogId,recipeRevision:1,styleReference:productionReference,styleRevision:productionStyleRevision,parameters:params,features:recipe.features,geometryStage:'candidate',reference:atlasSource(catalogId),referenceStage:'candidate',limitations:limits,units:'metres',front:n===142?'hand local +Z dorsal / -Z palm':'-Z',gameIntegration:false,animationClips:false,collision:'none; visual-only',detail:m.detail}};validateRig(a);const b=assetBoundsM(a)!;a.source!.dimensionsM=b.max.map((v,i)=>v-b.min[i]);a.source!.materialAssignmentReview=inspectAttireMaterials(catalogId,a,style);return JSON.parse(JSON.stringify(a));}
