import type {Asset,V3} from '../core/types';import {Grid} from '../core/grid';import {gridComponents} from '../core/checks';import {assetBoundsM} from '../core/sky';import {validateRig} from '../core/rig';import {AvatarModel} from './avatar-model';import {Shapes} from './shapes';import {makeLifeAsset} from './life';import {ROOT,heldModel} from './held-shapes';import {toolBelt,badge,umbrella,cane,crutch,chopsticks,broom} from './held-tools';import {shoppingBag,foodPackage,cup,ladle} from './held-containers';import {atlasSource,type AtlasRecipe} from './atlas-life';import {productionReference,productionStyleRevision} from './style';
type Params=Record<string,string|number>;
const definitions:Record<string,[string,string,string[]]>={'CHAR-149':['职业工具腰带：独立皮环、软衬、双工具袋、挂环与扣件','beltFit',['adultA','adultB']],'CHAR-150':['职业胸牌腰牌：实体印墨、塑料牌底、开放背夹与挂孔','badgeType',['chest','waist']],'CHAR-177':['角色手持伞：连续油纸伞面、八条金属伞骨与木杆','canopy',['open','folded']],'CHAR-178':['角色手持拐杖：T形握把、伸缩止挡与独立胶脚','length',['full','compact']],'CHAR-179':['角色手持腋拐：分叉侧杆、横握把、腋垫与胶脚','length',['full','compact']],'CHAR-180':['角色购物袋：帆布真腔、两条真握孔提带与折叠形态','bag',['open','collapsed']],'CHAR-181':['角色食品包：真纸袋、独立菜茎叶、根菜与长面包','contents',['filled','empty']],'CHAR-182':['角色餐碗：直接复用 LIFE046 白釉碗母版，配空碗或静态餐食','contents',['empty','meal']],'CHAR-183':['角色筷子：独立双木筷、尾箍与最小方块','pair',['parallel','working']],'CHAR-184':['角色茶杯水杯：独立有把杯、真腔、色釉口与可移除杯盖','lid',['closed','removed']],'CHAR-185':['角色烹饪勺：金属真勺腔、倾斜木柄与悬挂孔','length',['full','compact']],'CHAR-186':['角色扫帚：木柄、独立纤维束、三道束带与挂环','length',['full','compact']]};
export const heldIds=Object.keys(definitions);export function heldParameters(id:string){if(!definitions[id])throw new Error('未实现持物');const[,key,values]=definitions[id];return{[key]:{type:'string',enum:values,default:values[0],description:'已制作的作者静态形态；不是原控制器或连续模拟'}};}
export const heldVariants=(id:string)=>{const[,key,values]=definitions[id];return values.map(v=>({[key]:v}));};
const limits='技术候选：最小细件原生体素，伞面/器壁/斜柄/提带连续网格；CHAR182保留LIFE046原10mm方格碗形，不冒称新连续曲面碗。角色视觉层非碰撞、光学未绑定且零发光。原尺寸矩阵/骨架/持物控制器未收件，作者有限摆放另验；无医疗、承载、布料/流体/库存功能。人工美术验收0。';
const defaultSizes:Record<string,V3>={"CHAR-149":[0.536,0.159,0.393],"CHAR-150":[0.091587026,0.235557649,0.04],"CHAR-177":[1.021879394,0.9520000000000001,1.021879394],"CHAR-178":[0.15,0.885,0.06],"CHAR-179":[0.252,1.338,0.088],"CHAR-180":[0.31,0.498,0.155],"CHAR-181":[0.208077806,0.435207058,0.142],"CHAR-182":[0.2,0.11,0.2],"CHAR-183":[0.034678494,0.250132283,0.014],"CHAR-184":[0.159,0.152,0.11499999999999999],"CHAR-185":[0.12,0.390121677,0.458121677],"CHAR-186":[0.271040774,1.208,0.096]};
const defaultComponents:Record<string,number>={"CHAR-149":5,"CHAR-150":6,"CHAR-177":11,"CHAR-178":7,"CHAR-179":9,"CHAR-180":7,"CHAR-181":1,"CHAR-182":1,"CHAR-183":2,"CHAR-184":5,"CHAR-185":1,"CHAR-186":5};
export const heldRecipes:Record<string,AtlasRecipe>=Object.fromEntries(Object.entries(definitions).map(([id,[features]])=>[id,{size:defaultSizes[id],pitch:id==='CHAR-182'?.01:.005,features,limits,expectedComponents:defaultComponents[id],...(id==='CHAR-182'?{primaryMasterId:'LIFE-046'}:{}),draw:()=>{throw new Error('使用持物混合工厂');}}]));
const roles:Record<string,string[]>={'CHAR-149':['toolBeltLeather','toolBeltLiner','garmentBuckle','equipmentCase','equipmentIndicator','heldFitting','utensilFerrule'],'CHAR-150':['equipmentCase','badgePlate','badgeInk','badgeClip','garmentStrap','garmentBuckle','utensilFerrule'],'CHAR-177':['umbrellaPaper','umbrellaWood','umbrellaRib','umbrellaEdge','equipmentCase','utensilFerrule','garmentStrap'],'CHAR-178':['mobilityShaft','mobilityGrip','mobilityTip','heldFitting','garmentStrap','utensilFerrule'],'CHAR-179':['mobilityShaft','mobilityGrip','mobilityTip','crutchPad','heldFitting','utensilFerrule'],'CHAR-180':['shoppingCanvas','shoppingStrap','heldLabelInk','utensilFerrule'],'CHAR-181':['foodPackagePaper','heldLabelInk','heldLeafFood','heldRootFood','breadCrust','breadScore'],'CHAR-182':['heldCeramic','heldCeramicGlaze','heldSoup','heldLeafFood','heldTofu'],'CHAR-183':['chopstickWood','heldFitting','utensilFerrule'],'CHAR-184':['heldCeramic','heldCeramicGlaze','heldVesselLid','equipmentCase','heldLabelInk','utensilFerrule'],'CHAR-185':['ladleBowl','ladleHandle','garmentStrap','utensilFerrule'],'CHAR-186':['broomFibre','broomBinding','broomHandle','garmentStrap','utensilFerrule']};
export function inspectHeldMaterials(id:string,a:Asset,s:Record<string,number>){const used=new Set([...new Grid(a.chunks).cells()].map(([,v])=>v).concat((a.meshes??[]).map(m=>m.material)));for(const v of used)if(!roles[id].some(r=>s[r]===v))throw new Error(id+'持物材质用途混用 '+v);return{revision:1,method:'actual-voxel-and-mesh-role-check',roles:roles[id].filter(r=>used.has(s[r])),note:'纸/织物/木/金属/橡胶/陶瓷/食品与印墨分别归类；共享碗几何显式映射为非碰撞持物釉料。'};}
function sharedBowl(name:string,id:string,s:Record<string,number>,contents:string){const mapped={...s,ceramicWhite:s.heldCeramic,ceramicTeal:s.heldCeramicGlaze},a=makeLifeAsset('LIFE-046',name,id,mapped),m=new AvatarModel(s);m.b=new Shapes(.01,s);if(contents==='meal'){m.add('静态汤汁实体','heldSoup',[{x:.1,y:.043,z:.1,rx:.048,rz:.048},{x:.1,y:.064,z:.1,rx:.062,rz:.062}]);for(const[x,z]of[[.073,.073],[.11,.080],[.09,.116]])m.box('真实豆腐细块'+x,'heldTofu',x,.064,z,.020,.015,.020);for(const[x,z]of[[.084,.096],[.118,.111],[.117,.06]])m.add('食用菜叶'+x+'-'+z,'heldLeafFood',[{x,y:.062,z,rx:.012,rz:.009},{x,y:.072,z,rx:.008,rz:.006}]);const g=new Grid(a.chunks);for(const[p,v]of m.b.g.cells())g.set(p,v);a.chunks=g.serialize();a.meshes=m.meshes;a.openings=[];a.parts.push(...m.b.parts.map((p,i)=>({...p,id:'meal-'+i})));}
 a.ports=[{id:'bowl-mouth',kind:'held-vessel',position:[.1,.10,.1],normal:[0,1,0],size:[.15,.01,.15],pitch:.01},{id:'bowl-support',kind:'held-vessel',position:[.1,0,.1],normal:[0,-1,0],size:[.1,.01,.1],pitch:.01}];a.source={...a.source,primaryMasterId:'LIFE-046',primaryGeometry:'Exact shared canonical LIFE046 cells at original 10mm pitch; no resampling or new bowl geometry master',primaryMaterialRemap:{ceramicWhite:'heldCeramic',ceramicTeal:'heldCeramicGlaze'},contents};return a;}
export function makeHeldAsset(catalogId:string,name:string,id:string,style:Record<string,number>,input:Params={}):Asset{const r=heldRecipes[catalogId];if(!r)throw new Error('未实现持物资产');const defs=heldParameters(catalogId);for(const[k,v]of Object.entries(input))if(!defs[k]?.enum.includes(String(v)))throw new Error('未验证持物参数 '+k);const parameters={...Object.fromEntries(Object.entries(defs).map(([k,d])=>[k,d.default])),...input},value=String(Object.values(parameters)[0]),s=new Proxy(style,{get(t,k){if(typeof k==='symbol')return Reflect.get(t,k);if(!Number.isInteger(t[k])||t[k]<1)throw new Error('缺少持物用途材质 '+k);return t[k];}});let a:Asset;
 if(catalogId==='CHAR-182')a=sharedBowl(name,id,s,value);else{const m=heldModel(s),n=Number(catalogId.slice(5));if(n===149)toolBelt(m,value);if(n===150)badge(m,value);if(n===177)umbrella(m,value);if(n===178)cane(m,value);if(n===179)crutch(m,value);if(n===180)shoppingBag(m,value);if(n===181)foodPackage(m,value);if(n===183)chopsticks(m,value);if(n===184)cup(m,value);if(n===185)ladle(m,value);if(n===186)broom(m,value);a={id,name,version:1,category:'base',cellSize:.005,origin:[0,0,0],chunks:m.b.g.serialize(),parts:[{id:'root',name:'最小扣件/箍销/标签原生块',parent:null,region:m.b.g.bounds()!},...m.b.parts],meshes:m.meshes,rig:m.rig,ports:m.ports,openings:[],source:{detail:m.detail}};a.rig!.voxelJoints=[{region:m.b.g.bounds()!,joint:ROOT}];validateRig(a);}
 a.source={...a.source,kind:'catalog-recipe',catalogId,recipeRevision:1,styleReference:productionReference,styleRevision:productionStyleRevision,parameters,features:r.features,geometryStage:'candidate',reference:atlasSource(catalogId),referenceStage:'candidate',limitations:limits,units:'metres',front:'-Z',gameIntegration:false,animationClips:false,collision:'none; visual-only'};const b=assetBoundsM(a)!;a.source.dimensionsM=b.max.map((v,i)=>v-b.min[i]);a.source.materialAssignmentReview=inspectHeldMaterials(catalogId,a,style);return JSON.parse(JSON.stringify(a));}
