import {Grid} from '../core/grid';
import type {Asset} from '../core/types';

/** Manual material/use decisions for individually reviewed reference candidates. These notes
 * describe authored choices, not an inference of physical materials from RGB.
 * A stored revision is added only after checking actual generated voxel IDs. */
export const materialAssignmentRevision=1;
export const atlasMaterialNotes:Record<number,string>={
 8:'衣柜内胆为木板、金属挂杆和黄铜承托；未混入外壳库存。',
 9:'石芯台座、木框、金属连接件与镜玻璃分开；镜反射仍未实现。',
 19:'浅色及深色键帽为两种硬塑料；木掌托、金属壳和状态灯独立。',
 20:'石座、木臂、金属销轴、显示底面和灯芯各自独立。',
 23:'软垫和包边都是织物；腿为木，套箍为金属，脚垫采用石材。',
 24:'鞋柜木框、石芯门、金属连接件和控制显示图形分开。',
 25:'木层板与挡边、金属托臂和铜销；没有默认陈列物。',
 26:'轨道为金属，浅色端盖为涂装金属，不再借用石材。',
 27:'帘面、包边及米白织入纹样均为织物，不使用纸。',
 28:'木边、金属安装背壳、铜角与漫射灯芯；没有独立玻璃罩层。',
 29:'木背板、金属背架、黄铜笼骨与灯芯分开。',
 30:'插座面板及摇臂为硬塑料，边框为木金属，状态像素独立。',
 31:'地毯、包边、回纹、短穗和穗结均为织物，不使用陶瓷。',
 32:'石芯工作面、木抽屉与木槽、金属挂架和控制显示图形分开。',
 37:'厨房下柜为木框石芯门；木抽屉的阴槽仍为木。',
 38:'石质台面及挡水条，金属嵌装边与铜角；保留两处通孔。',
 39:'灶、锅架、烟罩与格栅为金属；炉圈和照明为独立发光角色。',
 40:'钢盆带石质台面翻边，排水篦及水嘴为金属；盆腔为空。',
 41:'石芯门和玻璃门分别赋值；玻璃下压条为金属，柜框为木。',
 42:'食品柜木框、石芯门、金属铰件；不包含食品库存。',
 43:'冷藏柜外门为涂装金属，内衬为塑料，密封与脚垫为橡胶；不使用木和石。',
 44:'锅体与卷口都是金属，木握和铜铆钉独立，不使用石槽色。',
 45:'玻璃盖芯、金属沿、铜压环和木握把；盖子静态。',
 46:'白釉碗壁与青色釉线都是陶瓷；可分别换釉色。',
 47:'保温壶外身为涂装金属；杯身与纹样为陶瓷，杯足为黄铜，托盘为木。',
 48:'钢制刀片与刃线、木柄和砧面、铜铆钉独立。',
 49:'陶壶与白瓷杯、青釉纹样、木盘及黄铜连接件分开。',
 50:'石芯门抽屉与木柜框、金属拉手分开；不焊入盆和瓶。',
 51:'本母版明确选用白釉陶瓷盆；水嘴和排水件为金属，非图片材质识别结论。',
 52:'盆体水箱为陶瓷；座圈和盖内板为硬塑料，铰轴及外框为金属。',
 53:'浴缸采用石质内盆和唇口、金属外裙、橡胶软靠；没有静态假水。',
 54:'玻璃与玻璃蚀刻纹样独立；蚀刻纹不使用棉布或纸。',
 55:'镜玻璃、木背、金属框、青色和暖色灯芯独立；无平面镜反射。',
 56:'管、法兰及阀件为金属，青色阀柄为涂装金属，不是布料。',
 57:'两种毛巾、包边与织入纹样为织物；木杆与金属墙架独立。',
 64:'木柜与石芯台面、金属细框、玻璃和暖灯分开。',
 65:'食品、叶片、纸价签、印字与木承盘分开；价签不是棉布或金属字。',
 66:'浅色承板为涂装金属；木柱木围边、金属托与石脚保留。',
 67:'木抽屉和石芯抽屉的面板及阴槽分别归类。',
 68:'硬透明塑料护片、纸价签、红与深色油墨、金属夹和木轨分开。',
 69:'篮筐按木编条制作；提耳及包角为金属，铆点为黄铜。',
 70:'棚布和米白织边都是织物；挂梁为木、挂扣为金属。',
 71:'木箱分板与固定织带分开；纸标签和油墨不借金属色。',
 72:'金属货箱、橡胶盖封、纸标签和油墨分开。',
 73:'硬塑料编码牌及封条，纸标签、油墨和金属扣件分开。',
 74:'棉布袋体、固定织带与青色印字分开；木金属承架和石脚独立。',
 75:'托盘为木墩、木板、金属角鞍与铜铆件。',
 76:'全部带体为固定织带，扣钩为金属，不与软垫包边共用。',
 77:'承板为木，木柱与金属拉撑、石脚分开。',
 78:'橡胶输送带、金属板链和滚筒、金属电机栅、显示像素独立。',
 79:'钢质耐磨台、金属剪架、木控制柱与石脚；黄色警示为油墨而非黄铜。',
 80:'承盘为钢，支架和读数壳为金属，显示内容是像素，不是石材。',
 81:'石芯工作台与木抽屉石芯门、金属夹件、控制像素分开。',
 82:'围壳为涂装金属，检修边槽为金属，观察玻璃与显示像素独立；仅脚座是石。',
 83:'洞孔挂板为涂装金属，木框石芯抽屉与金属工具分开。',
 84:'刀盘刃齿为钢，检修框槽为金属，浅色臂条为涂装金属；仅脚座是石。',
 85:'石质矿料的主基质、深基质与含铜矿脉独立，不用金属硬件模拟矿脉。',
 86:'木采收箱与木收边、金属包角和石脚；内部为空。',
 87:'网绳使用独立纤维角色，捕捞箱为硬塑料；木网骨、石脚与金属边分开。',
 88:'硬塑料保温壳、橡胶密封、金属包角及油墨冷链标记分开。',
 89:'石木终端框与硬塑料键帽、显示底面、青白像素和侧灯独立。',
 90:'玻璃屏、金属传声栅、木框石脚、显示角标和照明各自独立。',
 91:'石木终端框与硬塑料键帽、显示底面、青白像素和侧灯独立。',
 92:'深浅谷粒均为食材；保留此前各层独立碰撞设置，没有散体物理。',
 93:'白菜梗为食材，叶面为植物；不借米白纸或棉布。',
 94:'鱼身、背鳍、腹部、眼圈及瞳孔都是食材；不是未知采样色、纸或泥土。',
 95:'包装硬壳选择涂装金属；纸标签与红油墨独立于箱体及黄铜扣件。',
 96:'纸包与织带、青油墨、琥珀玻璃瓶、塑料盖分别赋值；瓶体仍为实心静态简化，未表达内容物。',
 106:'纸质封面、纸页、页边、书脊布、油墨和铜包角分开，不借魚身颜色。',
 107:'卷纸与纸边、青深油墨、木轴和铜箍分开；画面不是布或石。',
 109:'木嵌板及阴槽、金属话筒、铜纹、石脚、显示图形分开。',
 110:'木柜门及木槽、石脚、金属框、青白显示像素和侧灯独立。',
 159:'木金属柜、玻璃门、涂红钢瓶、橡胶盘管、红塑料急救箱、纸标签和印字分别赋值；不是同一种红材质。',
 169:'展架为木金属，画轴为纸面和独立绘画颜料，石脚、灯芯独立；画面是简化格子。',
 170:'绷布为织物，画面为绘画颜料，笔杆为木、笔尖为合成纤维；不借纸张和石材做画布。',
 171:'宣纸和印墨、砚石、墨色、木笔杆与合成纤维筆尖分别独立；桌面器具没有重复合入整张桌。',
 172:'钢辊、橡胶辊、木金属机架、纸路和印墨、塑料按键及显示像素分开。',
 173:'展签采用纸面、绘画颜料、印墨和玻璃护面，未把纸质展签当发光屏。',
 174:'木共鸣箱、金属琴弦、木琴桥及铜尾扣分开；只有小状态显示使用像素。',
 175:'朱红木胎、合成聚合物鼓膜、黄铜钉、木槌与膜面油墨分别赋值。',
 176:'台面和踏板为木，边框桁架为金属，脚为石，灯窗使用灯芯；连接槽为空格。',
 177:'音箱采用聚合物振膜，橡胶悬边与线圈、塑料运输箱、木机架、铜轴和显示机盒分别赋值。',
 178:'供台本体采用木面和木嵌纹，金属角鞍、铜嵌条、石脚独立；不合入可独立放置的供具。',
 179:'铜炉、土质灰层、植物香材和余烬独立，灯框为铜、灯芯为电发光层；无蜡、燃烧或烟。',
 180:'纸本和印墨、木框石面、塑料话筒头、静态显示像素分开。',
 181:'十九路棋线为油墨，黑白棋子为独立釉面陶瓷，棋盘和屉盒为木；不借金属、石材做棋子。',
 182:'球皮选合成聚合物，尼龙网弦、尼龙羽球裙片、软木头与橡胶接缝分别赋值。',
 183:'杠轴及配重为金属，握把橡胶、凳面织物、木石基架和显示像素分开。',
 184:'绿台呢是织物，牌为硬塑料与印墨，不使用陶瓷或纸张假代牌。',
 185:'红蓝旗面、浅金织纹和流苏为织物，横杆木、扣件铜，不借红果实或红塑料。',
 186:'灯罩玻璃、电灯芯、铜框和红布穗分开；不是蜡烛，不用蜡角色。',
 187:'布幔和织纹、纸礼盒和独立缎带、石芯木桌分别归类。',
 188:'红色软座和覆布、织入图形、缎穗、木格架与铜件独立。',
 189:'木棺、白色覆布、织入图形、铜提环、石脚和电灯芯独立，内部无遗体。',
 190:'石质牌面、独立印墨、陶瓷花盆、植物花叶、香材和余烬分离。',
 191:'糕体、奶油、糖饰属于食材；蜡、棉芯、火焰、瓷杯、纸卡、印墨、花枝各自独立。',
 192:'陶瓷壶杯、金属罐、独立干茶叶和茶汤、木盘与印纹分开。',
 193:'石芯台面及门面、木框抽屉、铜连接和显示像素分开；无重复显示器。',
 194:'软垫、织边、木石框与骨形铜牌分开，铜牌不是动物食物。',
 195:'陶瓷盆、食物颗粒、水、金属水嘴、木框与显示像素独立。',
 196:'涂装钢壳、塑料、橡胶、尼龙刷纤维、清洁液、纸标签和显示像素分开。',
 197:'木腿、金属杆、铜轴、棉布和青灰织物分开；不是纸或石。',
 198:'洗衣机外壳为涂装金属，滚筒钢、门封橡胶、玻璃舷窗、塑料控制面及显示像素独立。',
 199:'镜片为独立背镀玻璃，木石台框、灯芯、塑料梳、纸标签与空玻璃瓶分开。',
 200:'红蓝包布、米白缎带、纸板内芯、铜扣及织纹各自独立，不共用红礼盒纸。',
 227:'石槽口壁、土壤和钢挂扣分开；植物由种植组合复用，不并入槽体。',

};
const required:Record<number,string[]>={
 192:['ceramicWhite','teaLeaf','teaLiquid','metalTeal','printedWarning'],193:['wood','wall','displayGlyph'],194:['fabric','fabricEdge','bronze'],195:['petKibble','water','ceramicWhite','displayGlyph'],196:['cleanerFibre','cleanerLiquid','rubber','enamel','rigidClear','paperSheet'],197:['metalBright','cottonWhite','fabric','wovenLight'],198:['enamel','metalBright','rubber','glass','polymer','displayGlyph'],199:['mirrorGlass','glass','paperSheet','polymerDark','warm'],200:['giftWrapRed','giftWrapBlue','giftWrapBand','giftBoard','wovenLight'],227:['wall','stone','soil','metal'],
 180:['paperSheet', 'printedDark', 'displayGlyph', 'polymerDark'],
 181:['gameWhite', 'gameBlack', 'printedDark'],
 182:['ballOrange', 'ballWhite', 'ballBlue', 'ballYellow', 'ballDark', 'ballRed', 'racketString', 'shuttleVanes', 'shuttleCork', 'rubber'],
 183:['metalBright', 'rubber', 'fabric'],
 184:['gameFelt', 'polymer', 'printedRed', 'inkTeal'],
 185:['festivalRed', 'bannerCloth', 'bannerPattern'],
 186:['glass', 'warm', 'festivalRed'],
 187:['giftPaper', 'giftRibbon', 'festivalRed', 'bannerPattern'],
 188:['festivalRed', 'bannerPattern', 'giftRibbon'],
 189:['cottonWhite', 'fabricEdge', 'wood'],
 190:['printedDark', 'ceramicWhite', 'flowerWhite', 'flowerAmber', 'incense'],
 191:['cakeCrumb', 'cakeCream', 'cakeGlaze', 'candleWax', 'candleWick', 'candleFlame', 'ceramicRed', 'paperSheet', 'printedRed', 'ceramicWhite'],

 159:['safetyMetal','redHose','polymerRed','paperSheet','printedMark','displayGlyph','glass'],169:['paperSheet','pigmentInk','pigmentMist'],170:['canvas','pigmentInk','brushFibre'],171:['paperSheet','printedDark','brushFibre','pigmentInk'],172:['metalBright','rubber','paperSheet','printedDark','displayGlyph'],173:['paperSheet','pigmentInk','glass'],174:['instrumentWire','wood','bronze'],175:['lacquerWood','drumSkin','printedWarning'],176:['wood','metal','warm'],177:['speakerCone','rubber','polymerDark','displayGlyph'],178:['wood','woodEdge','bronze'],179:['incense','ember','warm','soil'],
 19:['polymer','polymerDark'],26:['enamel'],27:['wovenLight'],30:['polymer','polymerDark','displayGlyph'],31:['wovenLight'],43:['enamel','polymer','rubber','displayGlyph'],44:['metalBright'],46:['ceramicWhite','ceramicTeal'],47:['enamel','ceramicWhite','ceramicTeal'],48:['metalBright'],49:['ceramicWhite','ceramicTeal'],51:['ceramicWhite'],52:['ceramicWhite','polymer'],53:['rubber'],54:['glassEtch'],56:['metalTeal'],57:['cottonWhite','wovenLight'],65:['paperSheet','printedDark','printedRed','foodRoot','fruitRed'],66:['enamel'],68:['rigidClear','paperSheet','printedDark'],71:['webbing'],72:['rubber'],73:['polymer','polymerDark'],74:['cottonWhite','webbing','inkTeal'],76:['webbing'],78:['rubber','displayGlyph'],79:['metalBright','printedWarning'],80:['metalBright','displayGlyph'],82:['enamel','displayGlyph'],83:['enamel'],84:['metalBright','enamel'],85:['oreVein','oreMatrix'],87:['rope','polymer'],88:['polymer','rubber','inkTeal','printedMark'],89:['polymer','displayGlyph','displayWhite'],90:['displayGlyph'],91:['polymer','displayGlyph','displayWhite'],92:['grain','grainPale'],93:['vegetableStalk'],94:['fish','fishBack','fishPale','fishEye'],95:['enamel','paperSheet'],96:['paperSheet','webbing','inkTeal','bottleAmber','polymer'],106:['bookCover','paperSheet','paperEdge','bookCloth','inkTeal'],107:['paperSheet','paperEdge','inkTeal','printedDark'],109:['displayGlyph'],110:['displayGlyph','displayWhite'],
};
const only:Record<number,string[]>={27:['fabric','fabricEdge','wovenLight'],31:['fabric','fabricEdge','wovenLight'],46:['ceramicWhite','ceramicTeal'],76:['webbing','metal','bronze'],85:['stone','oreMatrix','oreVein'],92:['grain','grainPale'],93:['leaf','leafAlt','vegetableStalk'],94:['fish','fishBack','fishPale','fishEye'],106:['bookCover','paperSheet','paperEdge','bookCloth','inkTeal','printedMark','bronze'],107:['paperSheet','paperEdge','inkTeal','printedDark','wood','bronze']};
const forbidden:Record<number,string[]>={19:['wall','stone','recess'],26:['wall','stone'],43:['wall','stone','recess','wood','woodEdge'],44:['recess','stone'],47:['wall','recess'],48:['recess'],49:['recess','wall'],51:['wall','stone'],52:['wall','stone'],53:['fabric','fabricEdge'],54:['fabric','fabricEdge'],56:['fabric','fabricEdge'],57:['recess','wall','stone'],68:['fabric','glass'],73:['wall','stone','fabricEdge'],78:['fabricEdge','recess'],80:['wall','stone'],84:['stone','recess','wood'],87:['fabricEdge','recess'],88:['wall','stone','recess','wood','fabric','fabricEdge'],89:['fabric','fabricEdge'],90:['recess'],91:['fabric','fabricEdge'],95:['wall','stone','recess'],96:['grain','leafAlt','recess','wall'],109:['recess'],110:['recess','fabric','fabricEdge']};
export function inspectAtlasMaterialAssignments(n:number,a:Asset,roles:Record<string,number>){
 const note=atlasMaterialNotes[n];if(!note)return null;
 const used=new Set([...new Grid(a.chunks).cells()].map(([,m])=>m));
 const reject=(role:string)=>{if(used.has(roles[role]))throw new Error(`${a.id}: 禁止借用材质角色 ${role}`);};
 if(n!==191)for(const role of ['cakeCrumb','cakeCream','cakeGlaze','candleWax','candleWick','candleFlame'])reject(role);
 reject('paper');for(const role of forbidden[n]??[])reject(role);
 if(![65,92,93,94].includes(n))for(const role of ['foodRoot','fruitRed','grain','grainPale','vegetableStalk','fish','fishBack','fishPale','fishEye'])reject(role);
 for(const role of required[n]??[])if(roles[role]===undefined||!used.has(roles[role]))throw new Error(`${a.id}: 缺少实际材质格 ${role}`);
 if(only[n]){const permitted=new Set(only[n].map(role=>roles[role]));for(const id of used)if(!permitted.has(id))throw new Error(`${a.id}: 非预期材质 ${id}`);}
 return{revision:materialAssignmentRevision,method:'authored-use-and-actual-voxel-check',note};
}
