import type {Asset,V3} from '../core/types';import {Grid} from '../core/grid';import {assetBoundsM} from '../core/sky';import {validateRig} from '../core/rig';import {axisPose,AvatarModel} from './avatar-model';import {makeLifeAsset} from './life';import {ROOT,heldModel,slab} from './held-shapes';import {cloth,bucket,brush,terminal,clipboard} from './service-daily';import {stethoscope,firstAid,probe} from './service-medical';import {lantern,radio,baton} from './service-patrol';import {atlasSource,type AtlasRecipe} from './atlas-life';import {productionReference,productionStyleRevision} from './style';
type Params=Record<string,string|number>;
const definitions:Record<string,[string,string,string[]]>={
 'CHAR-187':['角色抹布：连续厚布、折弯与织入条带','clothForm',['draped','folded']],
 'CHAR-188':['角色提桶：开口金属真壁底、提把与独立静态水','contents',['empty','water']],
 'CHAR-189':['角色持书：共享 LIFE106 原硬封书，另存有限展开形态','bookForm',['closed','open']],
 'CHAR-190':['角色粗毛笔：木杆、合成毫束、金属箍与真实挂孔','brushTip',['inked','dry']],
 'CHAR-191':['角色终端：独立壳、密封框、未绑定显示底与后握带','orientation',['landscape','portrait']],
 'CHAR-192':['角色记录板：真纸、实体木板、上夹与后握带','paperForm',['ruled','blank']],
 'CHAR-193':['角色诊察器：连续耳管、胶管、耳塞与独立听头','hoseForm',['looped','extended']],
 'CHAR-194':['角色急救箱：真空腔、软衬、独立箱盖及提把','lid',['closed','removed']],
 'CHAR-195':['角色诊疗探头：斜颈、握胶、光学片与静态端线','cableForm',['cabled','bare']],
 'CHAR-196':['角色照明器：金属笼框、透明罩、未绑定灯芯与提把','handleForm',['raised','lowered']],
 'CHAR-197':['角色通信器：机壳、真按键、开放背夹与包胶天线','antennaForm',['long','short']],
 'CHAR-198':['角色勤务棍：连续杆、独立握胶凸环、光学条与防失环','length',['full','compact']]
};
export const serviceIds=Object.keys(definitions);export function serviceParameters(id:string){const d=definitions[id];if(!d)throw new Error('未实现角色勤务持物');const[,key,values]=d;return{[key]:{type:'string',enum:values,default:values[0],description:'作者有限静态形态，原控制器未绑定'}};}
export const serviceVariants=(id:string)=>{const[,key,values]=definitions[id];return values.map(v=>({[key]:v}));};
const limits='技术候选：最小细件5mm原生体素，折布、管线、器壁、斜面和曲面使用连续网格；持书合拢态保留 LIFE106 旧原生占用，展开为明确作者派生。全为视觉非碰撞，电源/通信/医疗功能未绑定且零发光。无原尺寸矩阵、骨架、持物控制器或保护净空；有限手部研究不等于完整角色动作。人工美术验收0。';
const sizes:Record<string,V3>={"CHAR-187": [0.24, 0.315179025, 0.101990127], "CHAR-188": [0.328, 0.431, 0.272], "CHAR-189": [0.23500000000000001, 0.06, 0.31], "CHAR-190": [0.04, 0.45, 0.045], "CHAR-191": [0.34, 0.235, 0.11299999999999999], "CHAR-192": [0.247, 0.321, 0.10500000000000001], "CHAR-193": [0.20596213800000002, 0.446538085, 0.037000000000000005], "CHAR-194": [0.35, 0.328, 0.19], "CHAR-195": [0.269598236, 0.38035955600000004, 0.112], "CHAR-196": [0.17, 0.383, 0.14], "CHAR-197": [0.07, 0.345, 0.055], "CHAR-198": [0.096, 0.602, 0.063]};const components:Record<string,number>={"CHAR-187": 1, "CHAR-188": 6, "CHAR-189": 1, "CHAR-190": 3, "CHAR-191": 13, "CHAR-192": 4, "CHAR-193": 3, "CHAR-194": 12, "CHAR-195": 3, "CHAR-196": 10, "CHAR-197": 13, "CHAR-198": 3};
export const serviceRecipes:Record<string,AtlasRecipe>=Object.fromEntries(Object.entries(definitions).map(([id,[features]])=>[id,{size:sizes[id],pitch:.005,features,limits,expectedComponents:components[id],...(id==='CHAR-189'?{primaryMasterId:'LIFE-106'}:{}),draw:()=>{throw new Error('使用角色勤务混合工厂');}}]));
const common=['utensilFerrule','heldFitting','garmentStrap'];const roles:Record<string,string[]>={
 'CHAR-187':['cleaningCloth','cleaningStripe'], 'CHAR-188':['bucketMetal','bucketWater','bucketGrip'],
 'CHAR-189':['heldBookCover','heldBookPaper','heldBookEdge','heldBookSpine','heldBookInk','heldBookTrim','heldBookCorner'],
 'CHAR-190':['writingWood','writingFibre','writingInk'], 'CHAR-191':['equipmentCase','deviceSeal','deviceDisplay','deviceButton'],
 'CHAR-192':['recordBoard','recordPaper','recordInk'], 'CHAR-193':['diagnosticMetal','diagnosticEarTip','diagnosticHose','equipmentCase','deviceLens','deviceButton'],
 'CHAR-194':['firstAidShell','firstAidLiner','firstAidMark'], 'CHAR-195':['deviceGrip','diagnosticMetal','diagnosticShell','equipmentCase','deviceLens','deviceDisplay','deviceButton','diagnosticHose'],
 'CHAR-196':['portableFrame','portableGlazing','portableLamp'], 'CHAR-197':['equipmentCase','deviceGrip','deviceSeal','deviceDisplay','deviceButton','radioAntenna'], 'CHAR-198':['batonShaft','batonGrip','equipmentCase','equipmentIndicator']};
export function inspectServiceMaterials(id:string,a:Asset,s:Record<string,number>){const used=new Set([...new Grid(a.chunks).cells()].map(([,v])=>v).concat((a.meshes??[]).map(m=>m.material))),allowed=[...roles[id],...common];for(const v of used)if(!allowed.some(r=>s[r]===v))throw new Error(id+'勤务持物材质用途混用 '+v);return{revision:1,method:'actual-voxel-and-mesh-role-check',roles:allowed.filter(r=>used.has(s[r])),note:'抹布/纸页/封皮/印墨/塑料/胶管/玻璃/未绑定光学用途分别保存。'};}
export const bookRemap={bookCover:'heldBookCover',paperSheet:'heldBookPaper',paperEdge:'heldBookEdge',bookCloth:'heldBookSpine',printedMark:'heldBookInk',inkTeal:'heldBookTrim',bronze:'heldBookCorner'};
function sharedBook(name:string,id:string,s:Record<string,number>,mode:string){const map={...s,...Object.fromEntries(Object.entries(bookRemap).map(([from,to])=>[from,s[to]]))},a=makeLifeAsset('LIFE-106',name,id,map);a.openings=[];a.ports=[{id:'book-support',kind:'held-book',position:[.115,0,.155],normal:[0,-1,0],size:[.18,.01,.27],pitch:.005}];if(mode==='open'){const m=heldModel(s);m.joint('upper-pages',ROOT,[.010,.030,0]);slab(m,'展开书脊真实装帧内桥','heldBookSpine',-.012,.025,.02,.044,.005,.27);a.meshes=m.meshes;a.rig=m.rig;a.rig!.sockets={'book-support':ROOT};const b=new Grid(a.chunks).bounds()!;a.rig!.voxelJoints=[{joint:ROOT,region:{min:b.min,max:[b.max[0],6,b.max[2]]}},{joint:ROOT,region:{min:[b.min[0],6,b.min[2]],max:[5,b.max[1],b.max[2]]}},{joint:'upper-pages',region:{min:[5,6,b.min[2]],max:b.max}}];a.rig!.pose['upper-pages']=axisPose([0,0,1],Math.PI);validateRig(a);}a.source={...a.source,primaryMasterId:'LIFE-106',primaryMaterialRemap:bookRemap,primaryGeometry:'Exact 5mm native LIFE106 cells retained; closed form identical modulo visual material remap',bookForm:mode,openingStudy:mode==='open'?'Original upper cover/page cells rotated 180 degrees around authored Z spine, added continuous inner cloth web; no resampling, no page animation, not original rig':'Original closed book has no opening rig'};return a;}
export function makeServiceAsset(catalogId:string,name:string,id:string,style:Record<string,number>,input:Params={}):Asset{const r=serviceRecipes[catalogId];if(!r)throw new Error('未实现角色勤务持物');const defs=serviceParameters(catalogId);for(const[k,v]of Object.entries(input))if(typeof v!=='string'||!defs[k]?.enum.includes(v))throw new Error('未验证勤务参数 '+k);const parameters={...Object.fromEntries(Object.entries(defs).map(([k,d])=>[k,d.default])),...input},value=String(Object.values(parameters)[0]),s=new Proxy(style,{get(t,k){if(typeof k==='symbol')return Reflect.get(t,k);if(!Number.isInteger(t[k])||t[k]<1)throw new Error('缺少勤务材质用途 '+k);return t[k];}});let a:Asset;if(catalogId==='CHAR-189')a=sharedBook(name,id,s,value);else{const m=heldModel(s),n=Number(catalogId.slice(5));const f:Record<number,(m:AvatarModel,v:string)=>void>={187:cloth,188:bucket,190:brush,191:terminal,192:clipboard,193:stethoscope,194:firstAid,195:probe,196:lantern,197:radio,198:baton};f[n](m,value);a={id,name,version:1,category:'base',cellSize:.005,origin:[0,0,0],chunks:m.b.g.serialize(),parts:[{id:'root',name:'最小原生销/扣/织标',parent:null,region:m.b.g.bounds()!},...m.b.parts],meshes:m.meshes,rig:m.rig,ports:m.ports,openings:[],source:{detail:m.detail}};a.rig!.voxelJoints=[{region:m.b.g.bounds()!,joint:ROOT}];validateRig(a);}
 a.source={...a.source,kind:'catalog-recipe',catalogId,recipeRevision:1,styleReference:productionReference,styleRevision:productionStyleRevision,parameters,features:r.features,geometryStage:'candidate',reference:atlasSource(catalogId),referenceStage:'candidate',limitations:limits,units:'metres',front:'-Z',gameIntegration:false,animationClips:false,collision:'none; visual-only'};const b=assetBoundsM(a)!;a.source.dimensionsM=b.max.map((v,i)=>v-b.min[i]);a.source.materialAssignmentReview=inspectServiceMaterials(catalogId,a,style);return JSON.parse(JSON.stringify(a));}
