import type {Asset} from '../core/types';import {Grid} from '../core/grid';import {assetBoundsM} from '../core/sky';import {validateRig} from '../core/rig';import {AvatarModel} from './avatar-model';import {garmentRig} from './garment-shapes';import {upperGarment} from './garment-upper';import {trousers,skirt,sash} from './garment-lower';import {footwear} from './garment-shoes';import {atlasSource,type AtlasRecipe} from './atlas-life';import {productionReference,productionStyleRevision} from './style';
type Params=Record<string,string|number>;
export function garmentParameters(id:string):Record<string,any>{return id==='CHAR-123'?{}:{bodyFit:{type:'string',enum:['adultA','adultB'],default:'adultA',description:'作者CHAR059/060身体比例；不是原游戏性别或年龄控制器'}};}
export function garmentVariants(id:string):Params[]{return id==='CHAR-123'?[{}]:[{bodyFit:'adultA'},{bodyFit:'adultB'}];}
const features:Record<string,string>={'CHAR-113':'独立交领短上衣；真领/腰/袖口和分件织带','CHAR-114':'独立长袍上身；蓝布胸背与浅色袖','CHAR-115':'独立长袍细褶下摆；贯通腰圈与布质纹样','CHAR-116':'前开口外搭长衫；连续衣摆和内层空间','CHAR-117':'无袖马甲；真实双侧臂孔与交领','CHAR-118':'成对日常裤腿；实际腰孔、膝分件和裤脚','CHAR-119':'独立长裙；真实褶片、腰口和下摆','CHAR-120':'独立织带腰封；真实环孔与三条垂带','CHAR-121':'成对皮质短靴；真鞋腔、布衬与橡胶底','CHAR-122':'成对布鞋；独立织物鞋面、内衬与橡胶底','CHAR-123':'学龄儿童成对搭带鞋；独立鞋腔和鞋底','CHAR-124':'交领寝衣上装和成对寝裤；独立轻布用途'};
const limits='技术候选：最小扣件/织标5mm原生体素，衣面、斜领、褶片和鞋壳连续网格。全部非碰撞。作者逐组件刚性关节，未绑定软布、原骨骼、动作片段、原受保护净空或游戏运行；长下摆仅站姿作者适配。服装不包含头、头发、手足或原身体；原图中的配件不夹带成新母版。人工美术验收0。';
const components:Record<string,number>={'CHAR-113':5,'CHAR-114':7,'CHAR-115':3,'CHAR-116':6,'CHAR-117':3,'CHAR-118':5,'CHAR-119':3,'CHAR-120':4,'CHAR-121':8,'CHAR-122':2,'CHAR-123':2,'CHAR-124':1};export const garmentExpectedComponents=(id:string,params:Params)=>components[id];
export const garmentRecipes:Record<string,AtlasRecipe>=Object.fromEntries(Object.entries(features).map(([id,f])=>[id,{size:[.65,1.5,.50],pitch:.005,features:f,limits,expectedComponents:components[id],draw:()=>{throw new Error('使用服装混合工厂');}}]));
export function inspectGarmentMaterials(id:string,a:Asset,s:Record<string,number>){if(!garmentRecipes[id])return null;const roles=['garmentOuter','garmentLight','garmentLining','garmentTrim','garmentPattern','garmentStrap','garmentBuckle','trouserCloth','bootUpper','shoeCloth','shoeLining','footwearSole','footwearEdge','sleepCloth'],allowed=new Set(roles.map(r=>s[r]));for(const material of [...new Grid(a.chunks).cells()].map(([,m])=>m).concat(a.meshes!.map(m=>m.material)))if(!allowed.has(material))throw new Error(id+'服装用途混用 '+material);return{revision:1,method:'actual-voxel-and-mesh-role-check',roles:roles.filter(r=>a.meshes!.some(m=>m.material===s[r])||[...new Grid(a.chunks).cells()].some(([,m])=>m===s[r])),note:'服装织物、织入纹样、固定带、金属扣、裤布、靴皮、鞋布、鞋衬、橡胶鞋底/鞋沿及寝衣布独立；全部非碰撞零发光。'};}
export function makeGarmentAsset(catalogId:string,name:string,id:string,style:Record<string,number>,input:Params={}):Asset{const recipe=garmentRecipes[catalogId];if(!recipe)throw new Error('未实现服装配方');const defs=garmentParameters(catalogId);for(const[k,v]of Object.entries(input))if(!defs[k]?.enum.includes(v))throw new Error('未验证服装参数 '+k);const params={...Object.fromEntries(Object.entries(defs).map(([k,v])=>[k,v.default])),...input},fit=catalogId==='CHAR-123'?'child':String(params.bodyFit),s=new Proxy(style,{get(t,k){if(typeof k==='symbol')return Reflect.get(t,k);if(!Number.isInteger(t[k])||t[k]<1)throw new Error('缺少服装用途材质 '+k);return t[k];}}),m=new AvatarModel(s);garmentRig(m,fit);const n=Number(catalogId.slice(5));if([113,114,116,117,124].includes(n))upperGarment(m,catalogId,fit);if(n===118||n===124)trousers(m,fit,n===124);if(n===115||n===119)skirt(m,catalogId,fit);if(n===120)sash(m,fit);if(n>=121&&n<=123)footwear(m,catalogId,fit);
 const a:Asset={id,name,version:1,category:'base',cellSize:.005,origin:[0,0,0],chunks:m.b.g.serialize(),parts:[{id:'root',name:'原生最小扣件与织标；连续衣面另列',parent:null,region:m.b.g.bounds()!},...m.b.parts],meshes:m.meshes,rig:m.rig,ports:m.ports,openings:[],source:{kind:'catalog-recipe',catalogId,recipeRevision:1,styleReference:productionReference,styleRevision:productionStyleRevision,parameters:params,features:recipe.features,geometryStage:'candidate',reference:atlasSource(catalogId),referenceStage:'candidate',limitations:limits,units:'metres',front:'-Z',originConvention:'author body rest origin, ground Y0; shoe sole extends below ground by its stated thickness',gameIntegration:false,animationClips:false,manualRigidBinding:true,collision:'none; visual-only',detail:m.detail}};validateRig(a);const b=assetBoundsM(a)!;a.source!.dimensionsM=b.max.map((v,i)=>v-b.min[i]);a.source!.materialAssignmentReview=inspectGarmentMaterials(catalogId,a,style);return JSON.parse(JSON.stringify(a)) as Asset;
}
