import type {Asset,V3} from '../core/types';import {Grid} from '../core/grid';import {assetBoundsM} from '../core/sky';import {validateRig} from '../core/rig';import {ROOT,heldModel} from './held-shapes';import {rabbit,squirrel,pig,ungulate} from './fauna-mammals';import {chicken,waterBird,smallBird} from './fauna-birds';import {ornamentalFish} from './fauna-fish';import {atlasSource,type AtlasRecipe} from './atlas-life';import {productionReference,productionStyleRevision} from './style';import type {AvatarModel} from './avatar-model';
const definitions:Record<string,[string,string,string[]]>={
 'CHAR-308':['兔独立坐姿比例、长耳内外皮、后腿大蹠和短圆尾','rabbitEars',['upright','back']],
 'CHAR-309':['活体观赏鱼、分叉扇尾、背胸腹鳍、鳃缘及白色鳞区','fishFins',['spread','folded']],
 'CHAR-310':['鸡冠与肉垂、颈羽、分层翼、真实趾足及弯镰尾','chickenTail',['fan','narrow']],
 'CHAR-311':['鸭横宽躯干、绿头、扁喙、蓝翼镜与真实蹼足','duckBill',['closed','open']],
 'CHAR-312':['鹅独立长躯、连续长颈、窄喙和分层白羽','gooseNeck',['alert','relaxed']],
 'CHAR-313':['猪宽厚裸皮躯干、鼻盘、耳内皮、分蹄和卷尾','pigEars',['ears-folded','ears-alert']],
 'CHAR-314':['山羊独立比例、后弯不分枝角、颌须和分蹄','goatHorns',['horn-high','horn-low']],
 'CHAR-315':['牛宽躯、斑色被毛、侧生角、乳房、分蹄及垂尾','cowHorns',['horn-up','horn-out']],
 'CHAR-316':['鹿细长四肢、斑色毛、独立细颈与真正分枝角','deerAntlers',['wide-antlers','narrow-antlers']],
 'CHAR-317':['野猪厚肩、背鬃、长口鼻、弯曲獠牙和分蹄','boarTusks',['long-tusks','short-tusks']],
 'CHAR-318':['松鼠坐姿、曲前臂、静态坚果壳和蓬松大尾','squirrelTail',['upright','arched']],
 'CHAR-319':['小鸟独立小型比例、蓝翼尾、黄胸、尖喙及真实趾','birdWings',['folded','raised']]
};
export const faunaIds=Object.keys(definitions);
export function faunaParameters(id:string){const d=definitions[id];if(!d)throw new Error('未实现动物候选');const[,key,values]=d;return{[key]:{type:'string',enum:values,default:values[0],description:'有限静态作者形态，非骨骼动画或生态状态'}};}
export const faunaVariants=(id:string)=>{const[,k,v]=definitions[id];return v.map(value=>({[k]:value}));};
const limits='M042技术候选：独立物种比例；曲面、耳、翼、鳍、角、蹄用连续网格，最小瞳孔/鼻孔/趾爪保持5mm原生细件。全部视觉层非碰撞零发光。各件只保留一个prop根，不冒称四足/鸟/鱼骨骼或步态、飞行、游泳、生态、所有权及库存集成。米制作者尺度；原动物尺寸和运行契约未收件，人工美术验收0。';
const sizes:Record<string,V3>={"CHAR-308": [0.288, 0.682, 0.531], "CHAR-309": [0.2412769, 0.239, 0.44699999999999995], "CHAR-310": [0.317355242, 0.643928682, 0.726385721], "CHAR-311": [0.34083691, 0.52, 0.703577675], "CHAR-312": [0.354, 0.872, 0.8254019159999999], "CHAR-313": [0.35, 0.472298841, 0.8609438439999999], "CHAR-314": [0.353767752, 1.080426222, 1.040598416], "CHAR-315": [0.6, 1.460575638, 1.616053359], "CHAR-316": [0.701568076, 1.795076004, 1.241216908], "CHAR-317": [0.41, 0.663829714, 1.177055747], "CHAR-318": [0.228, 0.579642679, 0.604826916], "CHAR-319": [0.115683442, 0.245, 0.27878847100000004]};const components:Record<string,number>={"CHAR-308": 7, "CHAR-309": 5, "CHAR-310": 9, "CHAR-311": 10, "CHAR-312": 10, "CHAR-313": 4, "CHAR-314": 4, "CHAR-315": 4, "CHAR-316": 4, "CHAR-317": 4, "CHAR-318": 9, "CHAR-319": 7};
export const faunaRecipes:Record<string,AtlasRecipe>=Object.fromEntries(Object.entries(definitions).map(([id,[features]])=>[id,{size:sizes[id]??[1,1,1],pitch:.005,features,limits,expectedComponents:components[id]??1,draw:()=>{throw new Error('使用动物混合工厂');}}]));
const eyes=['eyeWhite','animalIris','animalPupil'],bird=['featherCream','featherOchre','featherDark','featherGreen','featherBlue','featherYellow','birdBeak','birdBeakDark','birdFoot','birdComb','animalNose','animalClaw'],mammal=['animalFurWhite','animalFurGinger','animalFurBrown','animalFurDark','faunaFurGray','animalSkin','animalNose','animalClaw','animalHoof','livestockSkin','livestockSnout','animalHorn','deerAntler','animalTusk','seedNutShell'];
export function inspectFaunaMaterials(id:string,a:Asset,s:Record<string,number>){const allowed=[...eyes,...(id==='CHAR-309'?['liveScaleOrange','liveScaleWhite','liveFin','liveGill','liveMouth']:['CHAR-310','CHAR-311','CHAR-312','CHAR-319'].includes(id)?bird:mammal)],used=new Set([...new Grid(a.chunks).cells()].map(([,v])=>v).concat((a.meshes??[]).map(m=>m.material)));for(const v of used)if(!allowed.some(r=>s[r]===v))throw new Error(id+'动物材质用途混用 '+v);return{revision:1,method:'actual-voxel-and-continuous-mesh-role-check',roles:allowed.filter(r=>used.has(s[r])),note:'羽片使用独立hair角色，鳞皮/喙/蹄/角/牙使用独立skin类别角色；类别为格式粗分类，不表示这些组织材质相同。眼白同用途共用；活鱼不用食材鱼角色，颜色相同不借布料/植物/金属。'};}
export function makeFaunaAsset(catalogId:string,name:string,id:string,style:Record<string,number>,input:Record<string,string|number>={}):Asset{
 const r=faunaRecipes[catalogId];if(!r)throw new Error('未实现动物候选');const defs=faunaParameters(catalogId);for(const[k,v]of Object.entries(input))if(typeof v!=='string'||!defs[k]?.enum.includes(v))throw new Error('未验证动物参数 '+k);const parameters={...Object.fromEntries(Object.entries(defs).map(([k,d])=>[k,d.default])),...input},s=new Proxy(style,{get(t,k){if(typeof k==='symbol')return Reflect.get(t,k);if(!Number.isInteger(t[k])||t[k]<1)throw new Error('缺少动物材质用途 '+k);return t[k];}}),m=heldModel(s),value=String(Object.values(parameters)[0]);
 const builders:Record<string,(m:AvatarModel,f:string)=>void>={'CHAR-308':rabbit,'CHAR-309':ornamentalFish,'CHAR-310':chicken,'CHAR-311':(m,f)=>waterBird(m,f),'CHAR-312':(m,f)=>waterBird(m,f,true),'CHAR-313':(m,f)=>pig(m,f),'CHAR-314':(m,f)=>ungulate(m,f,'goat'),'CHAR-315':(m,f)=>ungulate(m,f,'cow'),'CHAR-316':(m,f)=>ungulate(m,f,'deer'),'CHAR-317':(m,f)=>pig(m,f,true),'CHAR-318':squirrel,'CHAR-319':smallBird};builders[catalogId](m,value);
 const bounds=m.b.g.bounds();if(!bounds)throw new Error('动物缺原生最小细件');m.rig!.voxelJoints=[{joint:ROOT,region:bounds}];const a:Asset={id,name,version:1,category:'base',cellSize:.005,origin:[0,0,0],chunks:m.b.g.serialize(),parts:[{id:'root',name:'最小瞳孔/鼻孔/趾爪',parent:null,region:bounds},...m.b.parts],meshes:m.meshes,rig:m.rig,ports:m.ports,openings:[],source:{kind:'catalog-recipe',catalogId,recipeRevision:1,styleReference:productionReference,styleRevision:productionStyleRevision,parameters,features:r.features,geometryStage:'candidate',reference:atlasSource(catalogId),referenceStage:'candidate',limitations:limits,units:'metres',front:'-Z',gameIntegration:false,animationClips:false,collision:'none; visual-only',detail:m.detail,dimensionBasis:'Authored species-specific scale; single reference tile does not provide original dimensions'}};validateRig(a);const b=assetBoundsM(a)!;a.source!.dimensionsM=b.max.map((v,i)=>v-b.min[i]);a.source!.materialAssignmentReview=inspectFaunaMaterials(catalogId,a,style);return JSON.parse(JSON.stringify(a));
}
