import {environmentAssemblyIds,makeEnvironmentAssembly,environmentParameters} from './environment-assemblies';
import {residentialAssemblyIds,makeResidentialAssembly} from './residential-assemblies';
import type {Project} from '../core/types';
import {nearArchitecture,roofArchitecture} from './architecture-near-assembly';
import {distantArchitecture} from './architecture-distant';
import {civicLandmarkIds,makeCivicLandmark} from './civic-landmarks';
import {civicTransportIds,makeCivicTransport} from './civic-transport';
import {metropolisTowerIds,makeMetropolisTower} from './metropolis-towers';
import {metropolisAviationIds,makeMetropolisAviation} from './metropolis-aviation';
import {metropolisInfrastructureIds,makeMetropolisInfrastructure} from './metropolis-infrastructure';
import {districtConnectionIds,makeDistrictConnection} from './district-connections';
import {districtCourtIds,makeDistrictCourt} from './district-courts';
import {makeDistrictTerminal} from './district-terminal';
import {fleetAirportIds,makeFleetAirport} from './fleet-airports';
import {fleetVehicleIds,makeFleetVehicle} from './fleet-vehicles';
import {airportServiceIds,makeAirportService} from './airport-service-assemblies';
import {transportStructureIds,makeTransportStructure} from './transport-structures';
import {landscapeAssemblyIds,makeLandscapeAssembly} from './landscape-assemblies';
import {habitatAssemblyIds,makeHabitatAssembly} from './habitat-assemblies';
import {parkAssemblyIds,makeParkAssembly} from './park-assemblies';
export {habitatAssemblyIds,parkAssemblyIds,environmentAssemblyIds,residentialAssemblyIds};
export const regionalAssemblyIds=[...airportServiceIds,...transportStructureIds,...landscapeAssemblyIds];
export const fleetAssemblyIds=[...fleetAirportIds,...fleetVehicleIds];
export const districtAssemblyIds=[...districtConnectionIds,...districtCourtIds,'BUILT-265'];
export const metropolisAssemblyIds=[...metropolisTowerIds,...metropolisAviationIds,...metropolisInfrastructureIds];
export const architectureAssemblyIds=['BUILT-019','BUILT-020','BUILT-021','BUILT-022','BUILT-023','BUILT-024','BUILT-040','BUILT-042','BUILT-075','BUILT-076','BUILT-077','BUILT-078',...civicLandmarkIds,...civicTransportIds,...metropolisAssemblyIds,...districtAssemblyIds,...fleetAssemblyIds,...regionalAssemblyIds,...habitatAssemblyIds,...parkAssemblyIds,...environmentAssemblyIds,...residentialAssemblyIds];
export function architectureAssemblyParameters(id:string):Record<string,unknown>{
 if(environmentAssemblyIds.includes(id))return environmentParameters(id);
 if(id==='BUILT-023'||id==='BUILT-079')return{program:{enum:['bank','medical'],default:'bank'}};
 if(id==='BUILT-164')return{liftStop:{enum:['bottom','top'],default:'bottom'}};
 if(id==='BUILT-281')return{trainMode:{enum:['lightRail','maglev'],default:'lightRail'}};
 if(id==='BUILT-311')return{stationMode:{enum:['bus','rail'],default:'bus'}};
 if(id==='ENV-002')return{terrainDetail:{enum:['near','far'],default:'near'}};
 if(id==='ENV-053')return{layoutSeed:{enum:[7,19],default:7}};
 if(id==='ENV-087'||id==='ENV-102')return{entryTransition:{enum:['steps','ramp'],default:'steps'}};
 if(id==='BUILT-042')return{layoutSeed:{enum:[7,19],default:7}};
 if(['BUILT-075','BUILT-076','BUILT-077','BUILT-078'].includes(id))return{roofWidth:{enum:['standard','wide'],default:'standard'}};
 return{};
}
export function makeArchitectureAssembly(p:Project,catalogId:string,id:string,name:string,params:Record<string,string|number>={}){
 if(!architectureAssemblyIds.includes(catalogId))throw new Error('未知建筑组合配方');const schema=architectureAssemblyParameters(catalogId) as Record<string,{enum?:(number|string)[];type?:string;minimum?:number;maximum?:number}>;
 for(const[k,v]of Object.entries(params))if(!schema[k]||(schema[k].enum?!schema[k].enum!.includes(v):typeof v!=='number'||!Number.isFinite(v)||v<schema[k].minimum!||v>schema[k].maximum!))throw new Error('未经验证的建筑组合参数 '+k);
 if(environmentAssemblyIds.includes(catalogId))return makeEnvironmentAssembly(p,catalogId,id,name,params);
 if(residentialAssemblyIds.includes(catalogId))return makeResidentialAssembly(p,catalogId,id,name);
 if(parkAssemblyIds.includes(catalogId))return makeParkAssembly(p,catalogId,id,name,params);
 if(habitatAssemblyIds.includes(catalogId))return makeHabitatAssembly(p,catalogId,id,name,params);
 if(civicLandmarkIds.includes(catalogId))return makeCivicLandmark(p,catalogId,id,name,params);
 if(civicTransportIds.includes(catalogId))return makeCivicTransport(p,catalogId,id,name,params);
 if(metropolisTowerIds.includes(catalogId))return makeMetropolisTower(p,catalogId,id,name,params);
 if(metropolisAviationIds.includes(catalogId))return makeMetropolisAviation(p,catalogId,id,name);
 if(metropolisInfrastructureIds.includes(catalogId))return makeMetropolisInfrastructure(p,catalogId,id,name);
 if(districtConnectionIds.includes(catalogId))return makeDistrictConnection(p,catalogId,id,name);
 if(districtCourtIds.includes(catalogId))return makeDistrictCourt(p,catalogId,id,name);
 if(catalogId==='BUILT-265')return makeDistrictTerminal(p,id,name);
 if(fleetAirportIds.includes(catalogId))return makeFleetAirport(p,catalogId,id,name);
 if(fleetVehicleIds.includes(catalogId))return makeFleetVehicle(p,catalogId,id,name,params);
 if(airportServiceIds.includes(catalogId))return makeAirportService(p,catalogId,id,name);
 if(transportStructureIds.includes(catalogId))return makeTransportStructure(p,catalogId,id,name,params);
 if(landscapeAssemblyIds.includes(catalogId))return makeLandscapeAssembly(p,catalogId,id,name,params);
 if(catalogId==='BUILT-040'||catalogId==='BUILT-042')return distantArchitecture(p,catalogId,id,name,params);
 if(Number(catalogId.slice(6))>=75)return roofArchitecture(p,catalogId,id,name,String(params.roofWidth??'standard'));
 return nearArchitecture(p,catalogId,id,name,String(params.program??'default'));
}
