import type {Asset} from '../core/types';import {Grid} from '../core/grid';import {assetBoundsM} from '../core/sky';import {validateRig} from '../core/rig';import {AvatarModel} from './avatar-model';import {coiffure,sparseHair} from './headwear-hair';import {facialHair} from './headwear-face';import {softWrap,hairCrown} from './headwear-accessories';import {atlasSource,type AtlasRecipe} from './atlas-life';import {productionReference,productionStyleRevision} from './style';
type Params=Record<string,string|number>;const param=(values:string[],description:string)=>({type:'string',enum:values,default:values[0],description});
export function headwearParameters(id:string):Record<string,any>{const n=Number(id.slice(5));if(n>=89&&n<=93||n===99)return{hairFit:param(['adult','child'],'成人066/学龄儿童068头部适配；不同头宽与纵向比例')};if(n===94)return{headStage:param(['preschool','school'],'学龄前/学龄儿童双髻')};if(n===96||n===97)return{headFit:param(['adult','elder'],'胡须贴合成人066/老年069实际面颊')};if(n===98)return{headFit:param(['adult','child','elder'],'眉弓替换对应头部原生眉毛')};if(n===100)return{pinState:param(['inserted','removed'],'真贯通簪槽；横簪、端止挡及其流苏整体拆装')};return{};}
export function headwearVariants(id:string):Params[]{return Object.entries(headwearParameters(id)).reduce<Params[]>((rows,[k,p])=>rows.flatMap(r=>p.enum.map((v:string)=>({...r,[k]:v}))),[{}]);}
const features:Record<string,string>={'CHAR-089':'完整披肩长发；分离前束和后帘；金属玻璃发夹','CHAR-090':'三股连续绕编长辫；真实织带和辫梢扣','CHAR-091':'高束马尾；汇聚根与展开长束','CHAR-092':'独立盘髻主团与连续盘绕表束','CHAR-093':'束冠高髻；承冠织带和长后垂发','CHAR-094':'儿童双侧发髻；独立真织环与垂带','CHAR-095':'真实开放秃顶马蹄发区；少量顶梳细束','CHAR-096':'双侧胡髭和短下颌须；真实口间隙','CHAR-097':'双侧胡髭和长须；避开作者衣领','CHAR-098':'成对立体眉弓；对应头部眉毛实际替换','CHAR-099':'布巾软帽真空内腔；贯通帽带与后结尾','CHAR-100':'发冠空环；双侧贯通簪槽；可拆簪和流苏'};
const limits='作者混合三维候选：最小细块5mm体素，斜面/毛发/布褶为连续网格。全部非碰撞；实际单head关节刚性绑定，GLB保留skin和权重；无软发模拟、动画或原角色控制器。头部、胡须、眉毛、帽和发冠分开。长发仅在限定作者转头/头肩框内核净空，不冒称原受保护身体净空或所有姿态通过；原源码/尺寸/骨骼未收件，人工美术验收待定。';
const counts:Record<string,number>={'CHAR-089':2,'CHAR-090':3,'CHAR-091':2,'CHAR-092':2,'CHAR-093':2,'CHAR-094':3,'CHAR-095':2,'CHAR-096':5,'CHAR-097':7,'CHAR-098':2,'CHAR-099':2,'CHAR-100':4};
export const headwearExpectedComponents=(id:string,p:Params)=>id==='CHAR-100'&&p.pinState==='removed'?1:counts[id];
export const headwearRecipes:Record<string,AtlasRecipe>=Object.fromEntries(Object.entries(features).map(([id,f])=>[id,{size:[.35,.60,.55],pitch:.005,features:f,limits,expectedComponents:counts[id]??1,draw:()=>{throw new Error('通过头发穿戴混合工厂创建');}}]));
export function inspectHeadwearMaterials(id:string,a:Asset,s:Record<string,number>){if(!headwearRecipes[id])return null;const n=Number(id.slice(5)),allowed=n<=94?['hairMass','hairRidge','hairRibbon','hairOrnament','hairGem']:n===95?['sparseHair','sparseHairRidge']:n<=97?['beardHair']:n===98?['browHair']:n===99?['headWrap','headWrapBand','hairOrnament']:['hairOrnament','hairGem','hairRibbon'];for(const material of [...new Grid(a.chunks).cells()].map(([,m])=>m).concat(a.meshes!.map(m=>m.material)))if(!allowed.some(r=>s[r]===material))throw new Error(id+'毛发/穿戴用途错误 '+material);return{revision:1,method:'actual-voxel-and-mesh-role-check',roles:allowed,note:'头发、胡须、眉毛、稀疏发区、织带、帽布、金属和装饰玻璃可分别替换；玻璃不发光、全部非碰撞。'};}
export function makeHeadwearAsset(catalogId:string,name:string,id:string,style:Record<string,number>,input:Params={}):Asset{const r=headwearRecipes[catalogId];if(!r)throw new Error('未实现头部穿戴配方');const defs=headwearParameters(catalogId);for(const[k,v]of Object.entries(input))if(!defs[k]?.enum.includes(v))throw new Error('未验证头部穿戴参数 '+k);const p={...Object.fromEntries(Object.entries(defs).map(([k,v])=>[k,v.default])),...input},s=new Proxy(style,{get(t,k){if(typeof k==='symbol')return Reflect.get(t,k);if(!Number.isInteger(t[k])||t[k]<1)throw new Error('缺少用途材质 '+k);return t[k];}}),m=new AvatarModel(s),n=Number(catalogId.slice(5));if(n<=94)coiffure(m,catalogId,n===94?'child':String(p.hairFit),n===94?String(p.headStage):'school');else if(n===95)sparseHair(m);else if(n<=98)facialHair(m,catalogId,String(p.headFit));else if(n===99)softWrap(m,String(p.hairFit));else hairCrown(m,String(p.pinState));
 m.bind('humanoid');m.joint('head',null,[0,0,0]);m.rig!.meshJoints=Object.fromEntries(m.meshes.map(v=>[v.name,'head']));m.rig!.voxelJoints=[{joint:'head',region:m.b.g.bounds()!}];m.rig!.sockets=Object.fromEntries(m.ports.map(v=>[v.id,'head']));
 const a:Asset={id,name,version:1,category:'base',cellSize:.005,origin:[0,0,0],chunks:m.b.g.serialize(),parts:[{id:'root',name:'最小细块；连续毛发和服饰另列',parent:null,region:m.b.g.bounds()!},...m.b.parts],meshes:m.meshes,rig:m.rig,ports:m.ports,openings:[],source:{kind:'catalog-recipe',catalogId,recipeRevision:1,styleReference:productionReference,styleRevision:productionStyleRevision,parameters:p,features:r.features,geometryStage:'candidate',reference:atlasSource(catalogId),referenceStage:'candidate',limitations:limits,units:'metres',front:'-Z',gameIntegration:false,animationClips:false,manualRigidBinding:'single head joint; no hair dynamics',collision:'none; visual-only',detail:m.detail}};validateRig(a);const b=assetBoundsM(a)!;a.source!.dimensionsM=b.max.map((v,i)=>v-b.min[i]);a.source!.materialAssignmentReview=inspectHeadwearMaterials(catalogId,a,style);return a;
}
