import type {Asset,V3} from '../core/types';import {Grid} from '../core/grid';import {Shapes} from './shapes';import {assetBoundsM} from '../core/sky';import {validateRig} from '../core/rig';import {AvatarModel} from './avatar-model';import {makeLifeAsset} from './life';import {ROOT,heldModel} from './held-shapes';import {wrench,hammer,hoe} from './care-tools';import {basketAddition,parcel,bouquet,foodBag} from './care-goods';import {carrier,leash} from './care-carry';import {animal} from './care-animals';import {atlasSource,type AtlasRecipe} from './atlas-life';import {productionReference,productionStyleRevision} from './style';
const definitions:Record<string,[string,string,string[]]>={
 'CHAR-199':['可调开口扳手、真挂孔、螺杆与独立握胶','jawForm',['wide','narrow']],
 'CHAR-200':['工坊锤、木柄、金属头、承击面与握胶','hammerForm',['long','short']],
 'CHAR-201':['田作锄、连续倾斜钢刃、木杆与承颈套','hoeForm',['field','compact']],
 'CHAR-202':['共享 LIFE069 编织筐体，新增真实提梁和独立采收内容物','basketContents',['harvest','empty']],
 'CHAR-203':['独立物流纸箱、折盖、纸签印墨及捆带','parcelForm',['tall','flat']],
 'CHAR-204':['婚礼九头混色花束、包纸锥和红缎带','bouquetForm',['full','short']],
 'CHAR-205':['悼念五头白花、露茎叶和白织带','bouquetForm',['full','short']],
 'CHAR-206':['婴儿背带空座、软衬、前兜、侧翼和肩腰真环','carrierFit',['adultA','adultB']],
 'CHAR-207':['牵引皮带、腕环和有真实孔的金属扣','leashForm',['long','short']],
 'CHAR-208':['厚纸宠物食品袋、爪印墨、真腔和独立粮粒','foodBagForm',['open','sealed']],
 'CHAR-306':['独立猫比例、短口鼻、胡须、细四肢、长尾与自然被毛','catForm',['tail-up','tail-low']],
 'CHAR-307':['独立犬比例、长口鼻、尖耳、卷尾、舌和四足','dogForm',['open-mouth','closed-mouth']]
};
export const careIds=Object.keys(definitions);export function careParameters(id:string){const d=definitions[id];if(!d)throw new Error('未实现照护农作动物');const[,k,values]=d;return{[k]:{type:'string',enum:values,default:values[0],description:'作者有限静态形态，原控制器及骨架未绑定'}};}
export const careVariants=(id:string)=>{const[,k,v]=definitions[id];return v.map(value=>({[k]:value}));};
const limits='技术候选：最小细件原生体素，斜刃、花瓣、动物曲面和柔带使用连续网格。CHAR202保留LIFE069原生筐体及格距，新增提梁和独立内容物不另计筐母版。非碰撞、零发光。原尺寸/骨骼/控制器未收件；有限静态研究不等于完整动作、背负承载、婴儿安装验收、喂食或动物生态。人工美术验收0。';
const sizes:Record<string,V3>={"CHAR-199": [0.1, 0.308, 0.053000000000000005], "CHAR-200": [0.242, 0.477, 0.127], "CHAR-201": [0.24, 1.08, 0.261], "CHAR-202": [0.48, 0.43, 0.34], "CHAR-203": [0.4, 0.35, 0.303], "CHAR-204": [0.220063693, 0.40621136799999996, 0.220134923], "CHAR-205": [0.16837724799999998, 0.405735113, 0.18106414599999998], "CHAR-206": [0.406, 0.534194299, 0.64], "CHAR-207": [0.26, 1.141, 0.08892204], "CHAR-208": [0.22, 0.33, 0.14500000000000002], "CHAR-306": [0.240721874, 0.4977, 0.70039524], "CHAR-307": [0.332, 0.7781, 0.960975406]};const components:Record<string,number>={"CHAR-199": 7, "CHAR-200": 5, "CHAR-201": 2, "CHAR-202": 3, "CHAR-203": 2, "CHAR-204": 10, "CHAR-205": 6, "CHAR-206": 5, "CHAR-207": 2, "CHAR-208": 1, "CHAR-306": 15, "CHAR-307": 15};
export const careRecipes:Record<string,AtlasRecipe>=Object.fromEntries(Object.entries(definitions).map(([id,[features]])=>[id,{size:sizes[id],pitch:id==='CHAR-202'?.01:.005,features,limits,expectedComponents:components[id],...(id==='CHAR-202'?{primaryMasterId:'LIFE-069'}:{}),draw:()=>{throw new Error('使用照护农作动物混合工厂');}}]));
export const basketRemap={wood:'basketWood',woodEdge:'basketEdge',metal:'basketMetal',bronze:'basketTie'};
const common=['utensilFerrule','heldFitting','garmentStrap','equipmentIndicator'];const roles:Record<string,string[]>={
 'CHAR-199':['toolSteel','toolGrip'],'CHAR-200':['toolSteel','toolWood','toolGrip'],'CHAR-201':['toolSteel','toolWood'],
 'CHAR-202':['basketWood','basketEdge','basketMetal','basketTie','heldRootFood','heldLeafFood'],
 'CHAR-203':['parcelBoard','parcelTape','parcelLabel','parcelInk'],
 'CHAR-204':['bouquetStem','bouquetLeaf','weddingRed','weddingPink','bouquetWhite','bouquetPollen','bouquetPaper','bouquetRibbon'],
 'CHAR-205':['bouquetStem','bouquetLeaf','bouquetWhite','bouquetPollen','mourningTie'],
 'CHAR-206':['carrierFabric','carrierLiner','carrierWeb','carrierBuckle'],
 'CHAR-207':['leashWeb','leashMetal'], 'CHAR-208':['petFoodPaper','petFoodInk','parcelLabel','heldPetKibble'],
 'CHAR-306':['eyeWhite','animalFurWhite','animalFurBrown','animalFurDark','animalSkin','animalIris','animalPupil','animalClaw'],
 'CHAR-307':['eyeWhite','animalFurWhite','animalFurGinger','animalFurDark','animalSkin','animalNose','animalIris','animalPupil','animalClaw','animalTongue']};
export function inspectCareMaterials(id:string,a:Asset,s:Record<string,number>){const used=new Set([...new Grid(a.chunks).cells()].map(([,v])=>v).concat((a.meshes??[]).map(m=>m.material))),allowed=[...roles[id],...common];for(const v of used)if(!allowed.some(r=>s[r]===v))throw new Error(id+'材质用途混用 '+v);return{revision:1,method:'actual-voxel-and-mesh-role-check',roles:allowed.filter(r=>used.has(s[r])),note:(id==='CHAR-306'||id==='CHAR-307')?'眼白共用同用途eyeWhite；动物被毛、皮肤、虹膜、瞳孔、爪独立，眼白不随毛色修改。':'动物被毛、皮肤、眼、爪与人物材质独立；纸、印墨、植物、软带和金属按实物用途保存。'};}
export function makeCareAsset(catalogId:string,name:string,id:string,style:Record<string,number>,input:Record<string,string|number>={}):Asset{const r=careRecipes[catalogId];if(!r)throw new Error('未实现照护农作动物');const defs=careParameters(catalogId);for(const[k,v]of Object.entries(input))if(typeof v!=='string'||!defs[k]?.enum.includes(v))throw new Error('未验证照护参数 '+k);const parameters={...Object.fromEntries(Object.entries(defs).map(([k,d])=>[k,d.default])),...input},value=String(Object.values(parameters)[0]),s=new Proxy(style,{get(t,k){if(typeof k==='symbol')return Reflect.get(t,k);if(!Number.isInteger(t[k])||t[k]<1)throw new Error('缺少照护材质用途 '+k);return t[k];}}),m=heldModel(s);let a:Asset;
 if(catalogId==='CHAR-202'){a=makeLifeAsset('LIFE-069',name,id,{...s,...Object.fromEntries(Object.entries(basketRemap).map(([from,to])=>[from,s[to]]))});m.b=new Shapes(a.cellSize,s);basketAddition(m,value);const g=new Grid(a.chunks);for(const[p,v]of m.b.g.cells()){if(g.get(p)&&g.get(p)!==v)throw new Error('新增提梁覆盖源篮格');g.set(p,v);}a.chunks=g.serialize();a.parts.push(...m.b.parts.map((p,i)=>({...p,id:'bail-'+i})));a.parts[0].region=g.bounds()!;a.meshes=m.meshes;a.rig=m.rig;a.ports=m.ports;a.openings=[];a.source={...a.source,primaryMasterId:'LIFE-069',primaryMaterialRemap:basketRemap,primaryGeometry:'Original LIFE069 native cells and pitch retained; continuous tall bail and separate produce added without resampling',detail:m.detail};}
 else{const f:Record<string,(m:AvatarModel,v:string)=>void>={'CHAR-199':wrench,'CHAR-200':hammer,'CHAR-201':hoe,'CHAR-203':parcel,'CHAR-204':(m,v)=>bouquet(m,v),'CHAR-205':(m,v)=>bouquet(m,v,true),'CHAR-206':carrier,'CHAR-207':leash,'CHAR-208':foodBag,'CHAR-306':(m,v)=>animal(m,v),'CHAR-307':(m,v)=>animal(m,v,true)};f[catalogId](m,value);a={id,name,version:1,category:'base',cellSize:.005,origin:[0,0,0],chunks:m.b.g.serialize(),parts:[{id:'root',name:'原生最小销/扣/爪尖/花药',parent:null,region:m.b.g.bounds()!},...m.b.parts],meshes:m.meshes,rig:m.rig,ports:m.ports,openings:[],source:{detail:m.detail}};}
 a.rig!.voxelJoints=[{joint:ROOT,region:new Grid(a.chunks).bounds()!}];validateRig(a);a.source={...a.source,kind:'catalog-recipe',catalogId,recipeRevision:1,styleReference:productionReference,styleRevision:productionStyleRevision,parameters,features:r.features,geometryStage:'candidate',reference:atlasSource(catalogId),referenceStage:'candidate',limitations:limits,units:'metres',front:'-Z',gameIntegration:false,animationClips:false,collision:'none; visual-only'};const b=assetBoundsM(a)!;a.source.dimensionsM=b.max.map((v,i)=>v-b.min[i]);a.source.materialAssignmentReview=inspectCareMaterials(catalogId,a,style);return JSON.parse(JSON.stringify(a));}
