import {AvatarModel} from './avatar-model';
import {garmentFrame,bandMesh,surfaceRibbon} from './garment-shapes';
import {bodyTorso,bodyLeg,profileBand,axisMesh,ringAt} from './attire-shapes';
import {costumeButton} from './costume-details';
import {roundBand,type Ring,roundLoft,loft} from './mesh-shapes';
export function bandages(m:AvatarModel,fit:string){const f=garmentFrame(fit),rs=bodyTorso(fit),rounded=f.q.section==='rounded';for(let i=0;i<4;i++){const y=f.hip+.06+i*.069;profileBand(m,'躯干独立缠布-'+i,'bandageCloth',rs,y,y+.055,.003,.004,'chest',rounded);}const guide=rounded?roundLoft('作者躯干取样',m.s.skinSurface,rs.map(r=>({...r,rx:r.rx+.009,rz:r.rz+.009}))):loft('作者躯干取样',m.s.skinSurface,rs.map(r=>({...r,rx:r.rx+.009,rz:r.rz+.009})));surfaceRibbon(m,'绷带斜向固定带','garmentStrap',[guide],[-.12,f.sh-.08],[.10,f.hip+.10],.026,'chest');for(let i=0;i<3;i++)costumeButton(m,'绷带固定最小夹-'+i,m.meshes.filter(v=>v.name==='绷带斜向固定带'),-.12+.22*(i+1)/4,f.sh-.08+(f.hip+.10-f.sh+.08)*(i+1)/4,'garmentBuckle');
 for(const side of[-1,1]){const arm:Ring[]=[{y:f.wrist,rx:f.armR*.64,rz:f.armR*.68,x:side*f.wristX},{y:f.elbow,rx:f.armR*.84,rz:f.armR*.86,x:side*(f.q.shoulderHalfWidthM+f.armR*.48)}];for(let j=0;j<3;j++)profileBand(m,'前臂缠布-'+side+'-'+j,'bandageCloth',arm,f.wrist+.013+j*.06,f.wrist+.055+j*.06,.003,.004,'elbow'+side,rounded);}
 m.port('torso',[0,f.hip+.14,0],[0,1,0],[.24,.01,.16],'chest');m.detail={separateWraps:true,sourceBodySkinIsAuthorProfile:true,source:'CHAR-059/060 clothed torso and arm profiles reclassified only in retained installation derivative',medicalFunction:false};}
export function limbBrace(m:AvatarModel,fit:string){const f=garmentFrame(fit),rs:Ring[]=[{y:f.ankle+.025,rx:f.legR*.88,rz:f.legR*.98,x:f.q.hipHalfWidthM},{y:f.q.kneeYM*.65,rx:f.legR*.94,rz:f.legR*1.02,x:f.q.hipHalfWidthM},{y:f.q.kneeYM,rx:f.legR*1.05,rz:f.legR*1.1,x:f.q.hipHalfWidthM,z:-.005},{y:f.hip-(f.hip-f.q.kneeYM)*.33,rx:f.legR*1.17,rz:f.legR*1.27,x:f.q.hipHalfWidthM},{y:f.hip-.004,rx:f.legR*1.23,rz:f.depth*1.08,x:f.q.hipHalfWidthM}],knee=f.q.kneeYM,hipX=f.q.hipHalfWidthM,round=true;for(const[j,y]of[f.ankle+.09,knee-.095,knee+.070].entries()){const joint=j===2?'hip1':'knee1';profileBand(m,'支具软衬环-'+j,'bracePad',rs,y,y+.034,.005,.006,joint,round);profileBand(m,'支具固定织带-'+j,'garmentStrap',rs,y+.004,y+.030,.011,.004,joint,round);costumeButton(m,'支具最小束带扣-'+j,m.meshes.filter(v=>v.name.startsWith('支具固定织带-'+j)),hipX,y+.017,'garmentBuckle',joint,.020);for(const side of[-1,1])m.rod('支具束带承耳-'+j+'-'+side,'braceMetal',[hipX+side*(ringAt(rs,y+.017).rx+.010),y+.017,.006],[hipX+side*(f.legR*1.10+.022),y+.017,.006],.008,joint);}
 for(const side of[-1,1]){const x=hipX+side*(f.legR*1.10+.022);m.add('支具下侧金属杆-'+side,'braceMetal',[{y:f.ankle+.095,rx:.008,rz:.010,x,z:.006},{y:knee-.005,rx:.008,rz:.010,x,z:.006}],'knee1',false);m.add('支具上侧金属杆-'+side,'braceMetal',[{y:knee+.005,rx:.008,rz:.010,x,z:.006},{y:knee+.110,rx:.008,rz:.010,x,z:.006}],'hip1',false);const start:[number,number,number]=[x-.011,knee,.006],end:[number,number,number]=[x+.011,knee,.006];m.mesh(axisMesh(roundBand('支具真铰轴孔-'+side,m.s.braceMetal,[{y:0,rx:.020,rz:.020},{y:.022,rx:.020,rz:.020}],.009),start,end),'knee1');m.box('支具最小轴端-'+side,'garmentBuckle',Math.round((x-.010)/.005)*.005,Math.round((knee-.0075)/.005)*.005,.0,.020,.015,.015,'knee1');}
 m.port('knee-axis',[hipX,knee,-.005],[1,0,0],[.16,.02,.02],'knee1');m.detail={canonicalSide:'right leg only; opposite is derivative',trueStrapCavities:true,finiteRigidHinge:true,medicalFunction:false,footOrShoeExcluded:true};}
