import type {Asset,Project,V3} from '../core/types';
import {makeAttireAsset} from './atlas-attire';
import {makeGarmentAsset} from './atlas-garments';
import {makeFigureAsset} from './atlas-figure';
import {makeAvatarAsset} from './atlas-avatar';
import {reflectAvatar} from './avatar-assembly';
import {garmentBodyId,garmentFrame} from './garment-shapes';
import {garmentMount,garmentBodySlot,splitGarmentBodyMesh} from './garment-body';
import {axisPose} from './avatar-model';
import {bareHand} from './attire-gloves';
export const attireScenes=['robes','weather','rescue-pilot','bandage-brace','bags','gloves','bags-open'] as const;
export type AttireScene=typeof attireScenes[number];
export type AttireWearer={key:string;catalogId:string;fit:string;x?:number;lid?:string};
export function attireWearers(base:Project,actors:AttireWearer[],name='穿戴研究'):Project{const p=structuredClone(base);p.name='M038 · '+name;p.assets={};p.instances={};const s=p.styles.yunshan,keep=(a:Asset)=>p.assets[a.id]??(p.assets[a.id]=a),place=(a:Asset,position:V3,key:string,rotation:0|1|2|3=0)=>{keep(a);p.instances[key]={id:key,assetId:a.id,name:a.name,position,rotation,parent:null};};
 for(const{key,catalogId,fit,x=0,lid='closed'}of actors){const n=Number(catalogId.slice(5));if(n>=147&&lid==='open'){place(makeAttireAsset(catalogId,catalogId,catalogId.toLowerCase()+'-offbody-open',s,{lid}),[x,.020,0],key+'-'+catalogId);continue;}if(n===142){const raw=keep(makeAvatarAsset('CHAR-070','原精细手','hand-'+fit,s,{limbFit:fit})),skin=keep(bareHand(raw,raw.id+'-bare')),g=keep(makeAttireAsset(catalogId,'防护手套','glove-'+fit,s,{wearFit:fit}));for(const side of[-1,1]){const a=side>0?keep(reflectAvatar(g,g.id+'-reflected')):g,b=side>0?keep(reflectAvatar(skin,skin.id+'-reflected')):skin;place(a,[x+side*.11,.25,0],key+'-glove'+side);place(b,[x+side*.11,.25,0],key+'-skin'+side);}continue;}
 const f=garmentFrame(fit),long=n<=139,outer=[137,138,139,144].includes(n),skinBody=n===145,body=keep(makeFigureAsset(garmentBodyId(fit),'原独立身体','body-'+fit,s,{extremities:'sockets'})),slot=garmentBodySlot(body,fit,!outer&&!skinBody?['CHAR-113','CHAR-118']:['CHAR-113'],s,'slot-'+catalogId+'-'+fit);if(skinBody){const torso=structuredClone(body.meshes!.find(m=>m.name==='髋腹胸肩连续衣身')!);torso.material=s.skinSurface;torso.name='同源作者裸躯干轮廓';slot.meshes!.push(torso);slot.rig!.meshJoints[torso.name]='chest';for(const side of[-1,1])for(const high of[false,true]){const original=body.meshes!.find(m=>m.name==='肩肘腕连续袖身-'+side)!,piece=splitGarmentBodyMesh(original,f.elbow,high);piece.name='同源作者裸臂-'+side+'-'+high;piece.material=s.skinSurface;slot.meshes!.push(piece);slot.rig!.meshJoints[piece.name]=(high?'shoulder':'elbow')+side;}slot.source={...slot.source,kind:'author-bandage-body-skin',sourceClothedMasterRetained:true,skinInterpretation:'Author surface from original clothed body profiles, not an original naked-character mesh'};}
 const position:V3=[x,.020,0],setRest=(a:Asset)=>{if(long)for(const side of[-1,1])a.rig!.pose['shoulder'+side]=axisPose([0,0,1],side*Math.PI/9);return a;};place(keep(setRest(slot)),position,key+'-body');
 const a=keep(makeAttireAsset(catalogId,catalogId,catalogId.toLowerCase()+'-'+fit+'-'+lid,s,n>=147?{lid}:{costumeFit:fit}));if(n===147)place(a,[x,.740,.280],key+'-'+catalogId,2);else if(n===148)place(a,[x+.400,.430,0],key+'-'+catalogId);else place(a,position,key+'-'+catalogId);
 for(const id of [...(!outer&&!skinBody?['CHAR-113','CHAR-118']:[]),'CHAR-122']){const under=keep(makeGarmentAsset(id,id,id.toLowerCase()+'-'+fit,s,{bodyFit:fit}));place(under,position,key+'-'+id);}
 const head=keep(makeFigureAsset('CHAR-066','原独立成人头','head-'+fit,s)),hair=keep(makeAvatarAsset('CHAR-085','原独立短发','hair-'+fit,s)),mounted=(src:Asset,joint:string,offset:V3)=>keep(setRest(garmentMount(src,fit,joint,offset,s,'mounted-'+src.id+'-'+catalogId+'-'+joint)));place(mounted(head,'head',[0,f.neck,0]),position,key+'-head');place(mounted(hair,'head',[0,f.neck,0]),position,key+'-hair');for(const side of[-1,1])for(const type of['hand','foot'] as const){const raw=keep(makeAvatarAsset(type==='hand'?'CHAR-070':'CHAR-071','原精细'+type,type+'-'+fit,s)),original=skinBody&&type==='hand'?keep(bareHand(raw,raw.id+'-bare')):raw,reflected=type==='hand'?side>0:side<0,src=reflected?keep(reflectAvatar(original,original.id+'-reflected')):original;place(mounted(src,(type==='hand'?'wrist':'ankle')+side,type==='hand'?[side*f.wristX,f.wrist,0]:[side*f.q.hipHalfWidthM,f.ankle,0]),position,key+'-'+type+side);}
 }
 p.selection={assetId:Object.values(p.instances)[0].assetId,partId:null,region:null};return JSON.parse(JSON.stringify(p));}
export function attireScene(base:Project,kind:AttireScene){const row=(id:number,fit:string,x:number,lid='closed')=>({key:'char-'+id+'-'+fit+'-'+lid,catalogId:'CHAR-'+id,fit,x,lid});let rows:AttireWearer[]=[];if(kind==='robes')rows=[row(137,'adultA',-1.2),row(138,'adultB',0),row(139,'adultA',1.2)];if(kind==='weather')rows=[row(140,'adultA',-.65),row(141,'adultB',.65)];if(kind==='rescue-pilot')rows=[row(143,'adultB',-.65),row(144,'adultA',.65)];if(kind==='bandage-brace')rows=[row(145,'adultA',-.65),row(146,'adultB',.65)];if(kind==='bags'||kind==='bags-open')rows=[row(147,'adultA',-.65,kind==='bags-open'?'open':'closed'),row(148,'adultA',.65,kind==='bags-open'?'open':'closed')];if(kind==='gloves')rows=[row(142,'adult',-.25),row(142,'child',.25)];return attireWearers(base,rows,kind);}
