import {AvatarModel} from './avatar-model';
import {costumeTorso,costumeSleeves,cutBand} from './costume-frame';
import {costumeBelt,costumeButton,grid5} from './costume-details';
import {garmentFrame,bandMesh,sectorBand,garmentFront,surfaceRibbon} from './garment-shapes';
import {roundBand,type Ring} from './mesh-shapes';
export function attireRobe(m:AvatarModel,id:string,fit:string){const f=garmentFrame(fit),wedding=id==='CHAR-138',mourning=id==='CHAR-139',role=wedding?'weddingCloth':mourning?'mourningCloth':'courtCloth',hem=wedding?.075:mourning?.17:.14,cut={role,collar:'cross' as const};const {base}=costumeTorso(m,fit,cut);costumeSleeves(m,fit,cut);
 // Independent flared skirt has a true open hem, and a brighter inset over the front opening.
 const rings:(Ring&{power:number})[]=[{y:hem,power:.75,rx:wedding?.34:mourning?.26:.285,rz:wedding?.245:.18,z:wedding?.035:0},{y:f.hip-.27,power:.60,rx:wedding?.285:.25,rz:.172},{y:f.hip+.045,power:.55,rx:f.q.hipHalfWidthM+f.legR*1.25+.022,rz:f.depth*1.40}];m.mesh(cutBand('长礼服左右背部裁片',m.s[role],rings,.19*Math.PI,1.81*Math.PI,.004,26),'chest');m.mesh(cutBand('长礼服独立内衬',m.s.garmentLining,rings.map(r=>({...r,rx:r.rx-.0042,rz:r.rz-.0042})),.19*Math.PI,1.81*Math.PI,.002,26),'chest');m.mesh(cutBand('长礼服前中浅色叠片',m.s.garmentLight,rings.map((r,i)=>({...r,y:i===0&&wedding?.175:r.y,rx:r.rx-.012,rz:r.rz-.012})), -.23*Math.PI,.23*Math.PI,.004,10),'chest');
 const trim=mourning?'garmentTrim':'ceremonyTrim';for(const side of[-1,1]){const a=side*.19*Math.PI; m.mesh(cutBand('礼服连续下摆襟边-'+side,m.s[trim],rings,a-.028,a+.028,.006,2),'chest');const wrist=f.wrist-.008,x=side*f.wristX;bandMesh(m,'渐扩礼服钟袖-'+side,role,[{y:wrist,rx:f.armR*(wedding?1.65:1.45),rz:f.armR*1.45,x},{y:f.elbow-.045,rx:f.armR*1.07,rz:f.armR*1.08,x:side*(f.q.shoulderHalfWidthM+f.armR*.48)}],.004,'elbow'+side);bandMesh(m,'钟袖宽织边-'+side,trim,[{y:wrist,rx:f.armR*(wedding?1.65:1.45)+.001,rz:f.armR*1.45+.001,x},{y:wrist+.028,rx:f.armR*(wedding?1.65:1.45)-.002,rz:f.armR*1.45-.001,x}],.004,'elbow'+side);costumeButton(m,'肩部最小织花-'+side,base,side*.11,f.sh-.09,trim,'chest',.015);}
 costumeBelt(m,fit,base,mourning?'garmentTrim':'garmentStrap');const skirt=m.meshes.filter(v=>v.name==='长礼服前中浅色叠片');for(const side of[-1,1]){const x=side*.055,y=(wedding?.175:hem)+.08,z=garmentFront(skirt,x,y);m.box('前摆最小织纹-'+side,trim,grid5(x-.01),grid5(y),grid5(z)-.005,.020,wedding?.035:.020,.010,'chest');}
 if(wedding){for(const side of[-1,1]){const x=side*.08;surfaceRibbon(m,'婚服独立前垂绶-'+side,'ceremonyTrim',skirt,[x,f.hip-.03],[x,.215],.018,'chest');}}
 if(mourning){for(const side of[-1,1]){const x=side*(f.q.shoulderHalfWidthM+f.armR*.3);bandMesh(m,'素服上臂深色布带-'+side,'garmentTrim',[{y:f.elbow+.09,rx:f.armR*1.16,rz:f.armR*1.20,x},{y:f.elbow+.13,rx:f.armR*1.16,rz:f.armR*1.20,x}],.004,'shoulder'+side);}}
 m.port('hem',[0,hem,0],[0,-1,0],[rings[0].rx*2,.01,rings[0].rz*2],'chest');m.detail={cut:wedding?'flared ceremonial wedding robe':mourning?'plain narrow mourning robe':'formal straight-panel court robe',defaultShoulderAbductionDegrees:20,standingOnly:true,hemM:hem,headHairOrnamentsExcluded:true,softCloth:false};}
