import {Quaternion,Vector3,Vector2,ShapeUtils} from 'three';
import type {V3} from '../core/types';
import type {AuthoredMesh} from '../core/authored-mesh';
import {AvatarModel,axisPose,snap} from './avatar-model';
import {garmentFrame,garmentRig} from './garment-shapes';
import {emptyMesh,quad,triangle,roundBand,band,type Ring} from './mesh-shapes';
export function attireRig(m:AvatarModel,fit:string,id:string){garmentRig(m,fit);if(['CHAR-137','CHAR-138','CHAR-139'].includes(id))for(const side of[-1,1])m.rig!.pose['shoulder'+side]=axisPose([0,0,1],side*Math.PI/9);}
export function polygonPlate(name:string,material:number,outline:[number,number][],z0:number,z1:number){const mesh=emptyMesh(name,material),faces=ShapeUtils.triangulateShape(outline.map(p=>new Vector2(...p)),[]);for(const z of[z0,z1])for(const f of faces)triangle(mesh,...f.map(i=>[...outline[i],z] as V3) as [V3,V3,V3],[0,0,z===z0?-1:1]);const area=outline.reduce((s,a,i)=>{const b=outline[(i+1)%outline.length];return s+a[0]*b[1]-a[1]*b[0];},0);for(let i=0;i<outline.length;i++){const a=outline[i],b=outline[(i+1)%outline.length],normal:V3=[(b[1]-a[1])*Math.sign(area),-(b[0]-a[0])*Math.sign(area),0];quad(mesh,[[...a,z0],[...b,z0],[...b,z1],[...a,z1]] as V3[],normal);}return mesh;}
/** Closed constant-width strap along a YZ path; its thickness follows the local tangent. */
export function orientedQuad(mesh:AuthoredMesh,p:V3[]){for(const ids of[[0,1,2],[0,2,3]]){const[a,b,c]=ids.map(i=>p[i]),u=b.map((v,d)=>v-a[d]),v=c.map((n,d)=>n-a[d]);triangle(mesh,a,b,c,[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]]);}}
export function strapPath(m:AvatarModel,name:string,role:string,x:number,path:[number,number][],width:number,thickness:number,joint:string){const mesh=emptyMesh(name,m.s[role]),frames=path.map(([y,z],i)=>{const a=path[Math.max(0,i-1)],b=path[Math.min(path.length-1,i+1)],dy=b[0]-a[0],dz=b[1]-a[1],L=Math.hypot(dy,dz),ny=-dz/L*thickness/2,nz=dy/L*thickness/2;return[[-width/2,-1],[width/2,-1],[width/2,1],[-width/2,1]].map(([dx,s])=>[x+dx,y+s*ny,z+s*nz] as V3);});for(let i=0;i<path.length-1;i++)for(let j=0;j<4;j++){const k=(j+1)%4;orientedQuad(mesh,[frames[i][j],frames[i+1][j],frames[i+1][k],frames[i][k]]);}orientedQuad(mesh,frames[0]);orientedQuad(mesh,[...frames.at(-1)!].reverse());m.mesh(mesh,joint);return mesh;}
export function axisMesh(mesh:AuthoredMesh,start:V3,end:V3){const q=new Quaternion().setFromUnitVectors(new Vector3(0,1,0),new Vector3(...end).sub(new Vector3(...start)).normalize());for(let k=0;k<mesh.positions.length;k+=3){const p=new Vector3(...mesh.positions.slice(k,k+3)).applyQuaternion(q).add(new Vector3(...start)),n=new Vector3(...mesh.normals.slice(k,k+3)).applyQuaternion(q);mesh.positions.splice(k,3,...p.toArray().map(snap));mesh.normals.splice(k,3,...n.toArray().map(snap));}return mesh;}
export function bodyTorso(fit:string):Ring[]{const f=garmentFrame(fit),{q,hip,sh,depth,h,neck}=f;return[{y:hip-.014,rx:q.hipRadiusM*.87,rz:depth},{y:hip+.038,rx:q.hipRadiusM,rz:depth*1.03},{y:hip+(sh-hip)*.36,rx:q.waistHalfWidthM,rz:depth*.92},{y:sh-.055*h,rx:q.shoulderHalfWidthM*.88,rz:depth*1.06},{y:sh+.005,rx:q.shoulderHalfWidthM*.96,rz:depth*.88},{y:neck-.018,rx:q.headM*.19*1.1,rz:q.headM*.19*.96}];}
export function bodyLeg(fit:string,side=1):Ring[]{const{q,ankle,legR,hip,depth}=garmentFrame(fit),x=side*q.hipHalfWidthM;return[{y:ankle,rx:legR*.66,rz:legR*.75,x},{y:q.kneeYM*.65,rx:legR*.79,rz:legR*.87,x},{y:q.kneeYM,rx:legR*.91,rz:legR*.95,x,z:-.005},{y:hip-(hip-q.kneeYM)*.33,rx:legR*1.05,rz:legR*1.15,x},{y:hip+.028,rx:legR*1.12,rz:depth*.96,x}];}
export function ringAt(rs:Ring[],y:number):Ring{const i=rs.findIndex((r,i)=>i>0&&r.y>=y);if(i<1||y<rs[0].y)throw new Error('截面取样越界 '+y);const a=rs[i-1],b=rs[i],t=(y-a.y)/(b.y-a.y);return{y,rx:a.rx+(b.rx-a.rx)*t,rz:a.rz+(b.rz-a.rz)*t,x:(a.x??0)+((b.x??0)-(a.x??0))*t,z:(a.z??0)+((b.z??0)-(a.z??0))*t};}
export function profileBand(m:AvatarModel,name:string,role:string,rs:Ring[],bottom:number,top:number,clearance:number,thickness:number,joint:string,round=true){const points=[ringAt(rs,bottom),...rs.filter(r=>r.y>bottom&&r.y<top),ringAt(rs,top)].map(r=>({...r,rx:r.rx+clearance+thickness,rz:r.rz+clearance+thickness}));if(round)m.mesh(roundBand(name,m.s[role],points,thickness),joint);else for(let i=0;i<points.length-1;i++)m.mesh(band(name+'-'+i,m.s[role],points[i],points[i+1],thickness),joint);}
