import {Matrix4,Quaternion,Vector3} from 'three';import {AvatarModel,snap} from './avatar-model';import {hand} from './avatar-limbs';import {figureProportions} from './atlas-figure';import type {Bounds,V3} from '../core/types';import {roundBand} from './mesh-shapes';
export function abdomenProfile(fit:string){const q=figureProportions[fit==='adultA'?'CHAR-059':'CHAR-060'],bottom=q.hipYM+.038,top=q.shoulderYM-.055*q.heightM,depth=q.hipRadiusM*.65;return{q,bottom,top,rings:[{y:0,rx:q.hipRadiusM,rz:depth*1.03},{y:(top-bottom)*.27,rx:q.hipRadiusM*.99,rz:(.22+depth*.94)/2,z:(depth*.94-.22)/2},{y:(top-bottom)*.53,rx:q.hipRadiusM*.95,rz:(.25+depth*.92)/2,z:(depth*.92-.25)/2},{y:(top-bottom)*.77,rx:q.shoulderHalfWidthM*.85,rz:(.20+depth)/2,z:(depth-.20)/2},{y:top-bottom,rx:q.shoulderHalfWidthM*.88,rz:depth*1.06}]};}
export function abdomen(m:AvatarModel,fit:string){const p=abdomenProfile(fit);m.add('衣覆孕期腹部独立替换段','modelSuit',p.rings,undefined,p.q.section==='rounded');m.mesh(roundBand('腹段下接缝织边',m.s.modelSuitTrim,[{...p.rings[0],rx:p.rings[0].rx+.003,rz:p.rings[0].rz+.003},{...p.rings[0],y:.012,rx:p.rings[0].rx+.003,rz:p.rings[0].rz+.003}],.005));const mid=p.rings[2];m.box('最小腹段织标','modelSuitTrim',-.01,mid.y-.009,-.254,.020,.018,.020);m.port('abdomen-bottom',[0,0,0],[0,-1,0]);m.port('abdomen-top',[0,p.top-p.bottom,0]);m.detail={fit,authorBody:fit==='adultA'?'CHAR-059':'CHAR-060',replaceIntervalM:[p.bottom,p.top],replacementNotOverlay:true,fullyClothed:true,pregnancyWeeksInferred:false,growthControllerBound:false,growthVariantReservedFor:'CHAR-082',profiles:p.rings};}
/** Orthogonal reflected source hands preserve every native cell; only display poses use arbitrary rotations. */
export function firstPerson(m:AvatarModel,pose:string){m.bind('first-person');m.joint('view-root',null,[0,0,0]);for(const side of[-1,1]){const tag=side<0?'left':'right',src=new AvatarModel(m.s);hand(src,'adult',pose);const point=(p:V3,normal=false):V3=>[side*p[0]+(normal?0:side*.18),-p[2],p[1]+(normal?0:-.15)].map(snap) as V3,rotation=new Matrix4().set(side,0,0,0,0,0,-1,0,0,1,0,0,0,0,0,1),inverse=rotation.clone().invert();m.joint(tag+'-elbow','view-root',[side*.18,0,.15]);
 for(const j of src.rig!.joints){const id=tag+'-'+j.id;m.joint(id,j.parent?tag+'-'+j.parent:tag+'-elbow',point(src.world.get(j.id)!));if(src.rig!.pose[j.id]){const matrix=rotation.clone().multiply(new Matrix4().makeRotationFromQuaternion(new Quaternion(...src.rig!.pose[j.id]))).multiply(inverse);m.rig!.pose[id]=new Quaternion().setFromRotationMatrix(matrix).toArray();}}
 const region=(b:Bounds):Bounds=>{const corners:V3[]=[];for(const x of[b.min[0],b.max[0]])for(const y of[b.min[1],b.max[1]])for(const z of[b.min[2],b.max[2]])corners.push(point([x*.005,y*.005,z*.005]).map(v=>Math.round(v/.005)) as V3);return{min:[0,1,2].map(i=>Math.min(...corners.map(v=>v[i]))) as V3,max:[0,1,2].map(i=>Math.max(...corners.map(v=>v[i]))) as V3};};
 for(const[v,mat]of src.b.g.cells()){const c=point(v.map(n=>(n+.5)*.005) as V3).map(v=>Math.round(v/.005-.5)) as V3;m.b.g.set(c,mat);}for(const b of src.rig!.voxelJoints)m.rig!.voxelJoints.push({joint:tag+'-'+b.joint,region:region(b.region)});for(const p of src.b.parts)m.b.parts.push({...p,id:tag+'-'+p.id,name:tag+' '+p.name,region:region(p.region)});
 for(const srcMesh of src.meshes){const mesh=structuredClone(srcMesh);mesh.name=tag+' '+srcMesh.name;for(let i=0;i<mesh.positions.length;i+=3){mesh.positions.splice(i,3,...point(srcMesh.positions.slice(i,i+3) as V3));mesh.normals.splice(i,3,...point(srcMesh.normals.slice(i,i+3) as V3,true));}if(side<0)for(let i=0;i<mesh.indices.length;i+=3)[mesh.indices[i+1],mesh.indices[i+2]]=[mesh.indices[i+2],mesh.indices[i+1]];m.mesh(mesh,tag+'-'+src.rig!.meshJoints[srcMesh.name]);}
 m.rod(tag+' 前臂袖','characterCloth',[side*.18,0,-.135],[side*.18,0,.15],.052,tag+'-elbow');m.rod(tag+' 近肘袖口','characterLining',[side*.18,0,.123],[side*.18,0,.15],.058,tag+'-elbow');m.port('wrist-'+tag,[side*.18,0,-.15],[0,0,-1],[.082688,.01,.087856],tag+'-wrist');m.port('grip-'+tag,point([0,-.058,-.042]),[0,1,0],[.015,.015,.015],tag+'-palm');}
 m.detail={pose,sourceHands:'CHAR-070 adult',bothHandsIncluded:true,leftReflectionRewindsFaces:true,nativeQuarterTurnExact:true,viewFrame:'author view origin; hands point -Z, palm fronts +Y',playerCameraBound:false,controllerBound:false,armAnimation:false};}
