import type {Asset,Project,V3,Command} from '../core/types';import type {AuthoredMesh} from '../core/authored-mesh';
import {displayMesh} from '../core/mesh';import {mergeMeshes} from './mesh-shapes';import {makeCharacterAsset,characterProportions as P} from './atlas-character';import {makeLandscapeAsset} from './atlas-landscape';
export type CharacterPose='standing'|'seated'|'far'|'robe';
export type PosePlacement={catalogId:string;name:string;position:V3;rotationX:number;mirrorX:1|-1};
export function characterPlacements(pose:CharacterPose):PosePlacement[]{const seated=pose==='seated',hip=seated?.46:P.hipYM,root=hip-P.hipYM,items:PosePlacement[]=[];const add=(catalogId:string,name:string,position:V3,rotationX=0,mirrorX:1|-1=1)=>items.push({catalogId,name,position:position.map(n=>Math.round(n*1e9)/1e9||0) as V3,rotationX,mirrorX});add('CHAR-002','torso',[0,hip,0]);add('CHAR-003','head',[0,P.headBaseYM+root,0]);add('CHAR-010','short-back',[0,P.headBaseYM+root,0]);if(pose==='robe'){add('CHAR-011','long-extension',[0,P.headBaseYM+root+.055,.095]);add('CHAR-012','robe-hem',[0,hip,0]);}
 for(const side of[-1,1]){const x=side*P.hipHalfWidthM,knee:V3=[x,seated?hip:P.kneeYM,seated?-.4:0],ankle:V3=[x,knee[1]-.36,knee[2]];if(pose==='far')add('CHAR-007','whole-leg-'+side,[x,hip,0]);else{add('CHAR-004','thigh-'+side,[x,hip,0],seated?Math.PI/2:0);add('CHAR-005','calf-'+side,knee);}add('CHAR-006','boot-'+side,ankle,0,side>0?1:-1);
 const angle=seated?50*Math.PI/180:0,shoulder:V3=[side*P.shoulderHalfWidthM,P.shoulderYM+root,0];add('CHAR-008','arm-'+side,shoulder,angle,side>0?1:-1);add('CHAR-009','hand-'+side,[shoulder[0],shoulder[1]-P.armLengthM*Math.cos(angle),-P.armLengthM*Math.sin(angle)],angle,side>0?-1:1);}
 return items;
}
export function posePoint(v:V3,t:PosePlacement,normal=false):V3{const c=Math.cos(t.rotationX),s=Math.sin(t.rotationX),r:V3=[v[0]*t.mirrorX,v[1]*c-v[2]*s,v[1]*s+v[2]*c];return r.map((n,i)=>Math.round((n+(normal?0:t.position[i]))*1e9)/1e9||0) as V3;}
/** Bounded static study; editable master voxels are retained separately, not revoxelised at each angle. */
export function makeCharacterPose(p:Project,pose:CharacterPose):Asset{const pieces:AuthoredMesh[]=[],placements=characterPlacements(pose);for(const t of placements){const a=p.assets[t.catalogId.toLowerCase()];if(!a)throw new Error('缺少角色母版 '+t.catalogId);for(const b of displayMesh(a,p.materials,'far')){const m:AuthoredMesh={name:t.name,material:b.material,collision:false,positions:[],normals:[],uvs:[...b.uvs],indices:[...b.indices]};for(let k=0;k<b.positions.length;k+=3){m.positions.push(...posePoint(b.positions.slice(k,k+3) as V3,t));m.normals.push(...posePoint(b.normals.slice(k,k+3) as V3,t,true));}if(t.mirrorX===-1)for(let k=0;k<m.indices.length;k+=3)[m.indices[k+1],m.indices[k+2]]=[m.indices[k+2],m.indices[k+1]];pieces.push(m);}}
 const roles=[...new Set(pieces.map(m=>m.material))];return{id:'pose-'+pose,name:'作者静态装配 · '+pose,version:1,category:'import',cellSize:.005,origin:[0,0,0],chunks:{},parts:[],openings:[],ports:[],meshes:roles.map(id=>mergeMeshes('静态组件用途-'+id,pieces.filter(m=>m.material===id))),source:{kind:'derived-character-pose',pose,placements,sourceMasters:[...new Set(placements.map(t=>t.catalogId))].map(id=>({catalogId:id,assetId:id.toLowerCase(),version:p.assets[id.toLowerCase()].version,parameters:p.assets[id.toLowerCase()].source!.parameters})),geometryAuthority:'derived static mesh from separately retained voxel/mesh masters and rigid orthogonal transforms; native voxel accents are meshed, never resampled onto an angled grid',originalSkeletonBound:false,skinning:false,animation:false,collision:false,frontHairIncluded:false,robeVisible:pose==='robe',wholeLegReplacesSegments:pose==='far',limitations:'装配研究，非新增母版或完整角色；前额发片留给后续条目。坐姿小腿竖直、乘坐时衣摆不显示；静态摆臂不等于动画。'}};
}
export function characterScene(p:Project,pose:CharacterPose):Project{const doc=structuredClone(p);doc.assets={};doc.instances={};for(const id of new Set(characterPlacements(pose).map(t=>t.catalogId)))doc.assets[id.toLowerCase()]=makeCharacterAsset(id,id,id.toLowerCase(),doc.styles.yunshan,id==='CHAR-002'?{garment:pose==='robe'?2:1}:{});const a=makeCharacterPose(doc,pose);doc.assets[a.id]=a;doc.instances[a.id]={id:a.id,name:a.name,assetId:a.id,position:[0,0,0],rotation:0,parent:null};doc.name='M031 · '+pose+'静态组件装配';doc.selection={assetId:a.id,region:null,partId:null};return doc;}
export function bonsaiScene(p:Project):Project{const doc=structuredClone(p),plant=makeCharacterAsset('ENV-134','盆景','env-134',doc.styles.yunshan),pot=makeLandscapeAsset('ENV-097','独立浅盆','env-097',doc.styles.yunshan,{vesselForm:'bonsai'});doc.assets={[plant.id]:plant,[pot.id]:pot};doc.instances={plant:{id:'plant',assetId:plant.id,name:'独立盆景',position:[0,0,0],rotation:0,parent:null},pot:{id:'pot',assetId:pot.id,name:'ENV097浅盆',position:[-.68,0,-.44],rotation:0,parent:null}};doc.name='M031 · 盆景与独立浅盆';doc.selection={assetId:plant.id,region:null,partId:null};return doc;}
export function sceneCommands(scene:Project):Command[]{return [...Object.values(scene.assets).map(asset=>({op:'installAsset',asset,materials:scene.materials})),...Object.values(scene.instances).map(i=>({op:'instance',...i}))];}
