import type {Assembly,Project,V3} from '../core/types';
import {ArchitectureBuilder} from './architecture-near-assembly';
import {CivicComponent,civicPlate,civicRoof} from './civic-components';
import {civicAsset,civicPost,plate,roof,rail,stairs} from './civic-landmarks';

export const civicTransportIds=['BUILT-161','BUILT-162','BUILT-163','BUILT-164','BUILT-165'];
const plus=(a:V3,b:V3)=>a.map((v,d)=>v+b[d])as V3;
const shift=(p:V3,y:number)=>[p[0],p[1]+y,p[2]]as V3;
function strip(c:CivicComponent,name:string,role:string,a:V3,b:V3,width:number,depth:number,offset=0,cross=0){const dx=b[0]-a[0],dz=b[2]-a[2],l=Math.hypot(dx,dz),u=[dz/l,0,-dx/l],point=(p:V3,s:number)=>p.map((n,d)=>n+(d===1?offset:u[d]*(cross+s*width/2)))as V3;c.slab(name,role,[point(a,-1),point(b,-1),point(b,1),point(a,1)],depth);}
function guideway(b:ArchitectureBuilder,key:string,a:V3,z:V3,kind:'road'|'rail',guard=true){
 return b.place(civicAsset(b,key,id=>{const c=new CivicComponent(b.p,id,kind==='road'?'连续路段、实嵌线与肩条':'连续箱梁、双导轨与侧缘',['BUILT-'+(kind==='road'?'131':'140'),...(kind==='road'?['BUILT-132','BUILT-134']:['BUILT-141','BUILT-142','BUILT-135'])],{from:a,to:z,kind,authorRoute:true});
  if(kind==='road'){for(const side of[-1,1])strip(c,'中缝两侧路面承体','pavementConcrete',a,z,4.92,.5,0,side*2.54);strip(c,'嵌条下实承床','pavementConcrete',a,z,.16,.42,-.08);strip(c,'陶瓷中心嵌条','roadInlay',a,z,.16,.08);if(guard)for(const side of[-1,1])strip(c,'双肩路缘','pavementConcrete',a,z,.4,.2,.2,side*4.75);}
  else{strip(c,'真实1.4米路床','structuralConcrete',a,z,6,1.4,-.2);for(const side of[-1,1]){strip(c,'导轨安装脚','metal',a,z,.36,.08,-.12,side*1.8);strip(c,'承载导轨','metalBright',a,z,.28,.24,.12,side*1.8);strip(c,'未绑定青色引导条','civicGuideOptic',a,z,.05,.015,.135,side*1.8);strip(c,'侧缘实体保护条','structuralConcrete',a,z,.35,.5,.3,side*2.75);strip(c,'栏顶连续扶杆','metal',a,z,.10,.10,1.10,side*2.75);const count=Math.ceil(Math.hypot(z[0]-a[0],z[2]-a[2])/8);for(let j=0;j<=count;j++){const t=j/count,p=a.map((v,d)=>v+(z[d]-v)*t)as V3,dx=z[0]-a[0],dz=z[2]-a[2],len=Math.hypot(dx,dz);c.box('护栏立柱','metal',p[0]+dz/len*side*2.75-.05,p[1]+.2,p[2]-dx/len*side*2.75-.05,.10,.9,.10);}}}
  const dx=z[0]-a[0],dz=z[2]-a[2],len=Math.hypot(dx,dz);for(const t of[.02,.98])for(const side of[-1,1]){const p=a.map((v,d)=>v+(z[d]-v)*t)as V3;c.pin('端部定位销','bronze',[p[0]+dz/len*side*(kind==='road'?4.6:2.5),p[1]-(kind==='road'?.04:.24),p[2]-dx/len*side*(kind==='road'?4.6:2.5)]);}return c.finish();}),[0,0,0],0,kind==='road'?'road':'rail');
}
/** Independent roof frame with two actual centre-line columns and pitched trusses. */
function station(b:ArchitectureBuilder,key:string,center:V3,w=22,d=18,holes:Parameters<typeof civicPlate>[4]=[],height=6){
 const slab=civicAsset(b,key+'-deck',id=>civicPlate(b.p,id,w,d,holes,1));b.place(slab,center,0,'platform');
 const frame=civicAsset(b,key+'-frame',id=>{const c=new CivicComponent(b.p,id,'两柱站棚实梁与斜撑',['BUILT-154','BUILT-155'],{w,d,height});for(const x of[-w*.36,w*.36]){c.box('站棚石脚','stone',x-.35,0,-.35,.7,.4,.7);c.box('站棚木柱','wood',x-.18,.4,-.18,.36,height-.4,.36);c.beam('横向承梁','woodEdge',[x,height,-d*.3],[x,height,d*.3],.3,.3);c.beam('左坡撑','wood',[x,height,-d*.3],[x,height+1.6,0],.24);c.beam('右坡撑','wood',[x,height,d*.3],[x,height+1.6,0],.24);c.pin('柱梁锁销','bronze',[x-.04,height-.04,-.18]);}c.beam('柱间连梁','wood',[-w*.36,height,0],[w*.36,height,0],.3);return c.finish();});b.place(frame,center,0,'column');
 roof(b,w+1,d*.6,shift(center,height),1.6,'gable');
 if(center[1]>1)for(const x of[-w*.36,w*.36])for(const z of[-d*.36,d*.36])civicPost(b,center[1]-1,1,[center[0]+x,0,center[2]+z]);
 return{center,footprint:[w,d],walkY:center[1]};
}
function roads(p:Project,id:string,name:string){const b=new ArchitectureBuilder(p,id),xs=[[-64,0],[-53,0],[-43,0],[0,0],[43,2.4],[53,2.4],[64,3.2]],segments:any[]=[];
 for(let i=1;i<xs.length;i++){const a:V3=[xs[i-1][0],xs[i-1][1],0],z:V3=[xs[i][0],xs[i][1],0],junction=i===2||i===5;const instance=guideway(b,'ground-main-'+i,a,z,'road',!junction);segments.push({id:'main-'+i,from:a,to:z,instance,actualWidth:10});}
 const nodes:any[]=[];for(const[x,y]of[[-48,0],[48,2.4]])for(const side of[-1,1]){const edge:V3=[x,y,side*5],end:V3=[x,y,side*27],instance=guideway(b,'ground-branch-'+x+'-'+side,edge,end,'road');segments.push({id:'branch-'+x+'-'+side,from:[x,y,0],geometryFrom:edge,to:end,instance,actualWidth:10});nodes.push(station(b,'quarter-'+x+'-'+side,[x,y,side*36]));}
 return b.finish('BUILT-161',name,{parameters:{},authorNodes:nodes,authorSegments:segments,worldRoutesBound:false,sourceGrammar:'Orthogonal source rule represented by four explicit station junctions and a continuous author grade; source building doors/world obstacles unavailable.',originalFiveRecipesAndSavesModified:false,clearanceBasis:'Centre strip finite samples; no original getWalkHeight/controller simulation.'});}
function railway(p:Project,id:string,name:string){const b=new ArchitectureBuilder(p,id),routes:any[]=[],piers:any[]=[];
 for(const[mode,z]of[['maglev',-28],['lightRail',28]]as [string,number][]){const points:V3[]=[[-96,22,z],[-80,22,z],[0,24,z],[80,24,z],[96,24,z]];const instances:string[]=[];for(let i=1;i<points.length;i++)instances.push(guideway(b,'rail-'+mode+'-'+i,points[i-1],points[i],'rail'));
  for(const[x,y]of[[-80,22],[0,24],[80,24]]){const a=civicAsset(b,'rail-pier-'+y,id=>{const c=new CivicComponent(p,id,'实基础、墩柱、墩帽与独立支座',['BUILT-136','BUILT-137','BUILT-138','BUILT-308'],{trackDatum:y,bedCenterOffset:-.9,bedTopOffset:-.2,authorGround:0});c.box('七米石基础','stone',-3.5,0,-3.5,7,2,7);c.box('三米实体墩柱','structuralConcrete',-1.5,2,-1.5,3,y-5.6,3);c.box('墩帽','structuralConcrete',-2,y-3.6,-3.5,4,1.8,7);for(const zz of[-2.1,1.3])c.box('独立桥梁支座','bridgeBearing',-1,y-1.8,zz,2,.2,.8);c.pin('墩帽侧销','bronze',[-1.8,y-3.4,-3.51]);return c.finish();});const instance=b.place(a,[x,0,z],0,'pier');piers.push({instance,track:[x,y,z],bearingTop:y-1.6});}
  const stops:any[]=[];for(const[x,y]of[[-80,22],[80,24]]){const center:V3=[x,y+1.2,z],deck=civicAsset(b,'rail-platform',id=>civicPlate(p,id,22,18,[{min:[-11,-3.3],max:[11,3.3]}],.4));b.place(deck,center,0,'platform');for(const xx of[-8,8])for(const zz of[-6,6])civicPost(b,y+.8,1,[x+xx,0,z+zz]);for(const xx of[-8,8])for(const zz of[-7,7])civicPost(b,5.8,.3,[x+xx,center[1],z+zz]);roof(b,16,14,shift(center,5.8),1.8,'gable');stops.push({center,trackSlotWidth:6.6,boardingVehicleBound:false});}
  routes.push({mode,points,instances,stops,railAxisOffsets:[-1.8,1.8],maximumGrade:2/80});
 }
 return b.finish('BUILT-162',name,{parameters:{},authorRoutes:routes,piers,sourceRouteCounts:{maglev:4,lightRail:5},representedRouteSamples:2,originalEdgesAvailable:false,scope:'Two explicit author mode samples preserve 6m bed, 1.4m depth, centre -0.9m and paired guide axes. The original four/five routes and rolling stock are not reconstructed or marked operational. Canonical 2.8m bogie gauge is deliberately not falsely mated to the 3.6m guide axes.'});}
function cable(p:Project,id:string,name:string){const b=new ArchitectureBuilder(p,id),routes:any[]=[],car=civicAsset(b,'cable-interface-cabin',id=>{const c=new CivicComponent(p,id,'开放侧门的静态轿厢接口试架',['BUILT-177','BUILT-178','BUILT-290'],{completeVehicleTemplate:false,doorSide:'negative-X',walkY:0});c.box('舱底','metal',-1.2,-.18,-1.6,2.4,.18,3.2);for(const x of[-1.2,1.1])for(const z of[-1.6,1.5])c.box('舱角柱','metal',x,0,z,.1,2.6,.1);c.box('右独立薄玻璃','glass',1.16,.3,-1.48,.025,2.15,2.96);for(const z of[-1.56,1.54])c.box('端舱玻璃','glass',-1.1,.3,z,2.2,2.15,.02);for(const z of[-1.5,.75])c.box('侧门两侧玻璃','glass',-1.185,.3,z,.025,2.15,.75);c.box('顶框承板','metal',-1.2,2.4,-1.6,2.4,.2,3.2);for(const x of[-1.1,1.08])for(const z of[-1.5,1.48])c.pin('舱顶销','bronze',[x,2.58,z]);return c.finish();}),hanger=civicAsset(b,'cable-half-metre-clamp',id=>{const c=new CivicComponent(p,id,'半米真孔钢索夹与吊臂',['BUILT-290'],{clearHole:.5,cableDiameter:.45,gauge:1.6,notIdenticalToCanonicalClamp:true});for(const x of[-.8,.8]){for(const y of[-.43,.25])c.box('索夹上下板','metal',x-.43,y,-.6,.86,.18,1.2);for(const xx of[x-.43,x+.25])c.box('索夹侧板','metal',xx,-.25,-.6,.18,.5,1.2);c.box('垂直吊臂','metal',x-.10,-3,-.1,.2,2.57,.2);c.pin('夹板锁销','bronze',[x,.41,.2]);}c.box('舱顶实托','metal',-1.1,-3.1,-.5,2.2,.2,1);return c.finish();});
 const samples:[string,V3[],number,V3][]=[['government-to-summit',[[-80,0,0],[-68,0,0],[-18,36,0],[-6,36,0]],1,[-74,3.4,0]],['tianshu-to-summit',[[0,0,-80],[0,0,-68],[0,36,-18],[0,36,-6]],0,[0,3.4,-74]]];
 for(const[key,points,rot,carPos]of samples){const lines=civicAsset(b,'cable-route-'+key,id=>{const c=new CivicComponent(p,id,'连续双承载索与独立引导条',['BUILT-143'],{points,cableHeight:9,guideHeight:8.5,diameter:.45,authorGround:false});for(const side of[-1,1]){const sampled:V3[]=[];for(let i=1;i<points.length;i++)for(let j=0;j<=(i===points.length-1?16:15);j++){const t=j/16,a=points[i-1],z=points[i],sag=i===2?1.6*4*t*(1-t):0,q=a.map((n,d)=>n+(z[d]-n)*t)as V3;q[1]+=9-sag;q[rot===1?2:0]+=side*.8;sampled.push(q);}c.tube('四十五厘米承载钢索','suspensionCable',sampled,.225);c.tube('未绑定十五厘米引导条','civicGuideOptic',sampled.map(p=>shift(p,-.5)),.075);}return c.finish();});b.place(lines,[0,0,0],0,'cable');
  const cabinInstance=b.place(car,carPos,rot,'author-cabin');const clampInstance=b.place(hanger,shift(carPos,5.6),rot,'hanger');
  for(const support of[points[1],points[2]]){const supportAsset=civicAsset(b,'cable-pylon-'+rot,id=>{const c=new CivicComponent(p,id,'索路转点支柱与钢导轮',['BUILT-310'],{authorDatum:0,contactAtCableY:9});for(const side of[-1,1]){const x=rot===1?0:side*2.4,z=rot===1?side*2.4:0;c.box('导塔基础','stone',x-.6,-.5,z-.6,1.2,.5,1.2);c.box('导塔金属立柱','metal',x-.2,0,z-.2,.4,9.8,.4);}const aa:V3=rot===1?[0,9.7,-2.4]:[-2.4,9.7,0],zz:V3=rot===1?[0,9.7,2.4]:[2.4,9.7,0];c.beam('塔顶横梁','metal',aa,zz,.35);for(const side of[-1,1]){const at:V3=rot===1?[0,8.5,side*.8]:[side*.8,8.5,0],axis:V3=rot===1?[0,0,.15]:[.15,0,0];c.tube('独立钢导轮','cableSheave',[plus(at,axis.map(n=>-n)as V3),plus(at,axis)],.325);const mount=plus(at,axis.map(n=>n/.15*.40)as V3);c.beam('导轮侧轴','metal',at,mount,.10);c.beam('避开钢索的侧挂臂','metal',mount,shift(mount,1.2),.12);}return c.finish();});b.place(supportAsset,support,0,'pylon');}
  routes.push({key,points,cabinInstance,clampInstance,wireHeight:9,cabinWalkHeight:3.4,finiteParkedState:true});
 }
 station(b,'government-cable-station',[-74,3.4,10.2],22,18,[],7);station(b,'tianshu-cable-station',[-10.2,3.4,-74],18,22,[],7);
 const upper=plate(b,30,30,39.4,[4,4],[{min:[-15,-5.2],max:[-2, -2.8]},{min:[-5.2,-15],max:[-2.8,-2]}]);roof(b,26,26,[4,46.4,4],2,'hip');for(const x of[-9,17])for(const z of[-9,17])civicPost(b,7,.4,[x,39.4,z]);
 return b.finish('BUILT-163',name,{parameters:{},authorRoutes:routes,summitStation:{platform:upper,walkY:39.4,logicalNode:[0,36,0],separateTerminalOffsets:[[-6,0,0],[0,0,-6]]},sourceEdgeNames:['政府→山顶','天枢→山顶'],originalRouteAndTransferBound:false,scope:'Two actual author cable paths, separate terminals, 0.45m cables, 0.5m clear clamp holes and static boarding gauges. Existing canonical clamp remains unchanged; no all-travel wheel clearance, moving-car controller or walking-along-airline claim.'});}
function lift(p:Project,id:string,name:string,stop:string){const b=new ArchitectureBuilder(p,id),world:V3=[140,103.6,35],height=151,carY=stop==='top'?height:0;
 const shaft=civicAsset(b,'151m-lift-frame',id=>{const c=new CivicComponent(p,id,'151米同轴四柱开放井架',['BUILT-144','BUILT-145'],{worldBottom:world,worldTop:[140,254.6,35],verticalDelta:151});for(const x of[-2.5,2.5])for(const z of[-2.5,2.5])c.box('连续井架柱','metal',x-.3,-1,z-.3,.6,156,.6);for(let y=12;y<=144;y+=12){for(const z of[-2.5,2.5])c.box('前后横梁','metal',-2.8,y-.2,z-.2,5.6,.4,.4);c.box('左横梁','metal',-2.7,y-.2,-2.5,.4,.4,5);for(const z of[-2.5,1.2])c.box('右导轮通行断口横梁','metal',2.3,y-.2,z,.4,.4,1.3);}for(const x of[-2.5,2.5])c.box('顶部冠梁','metal',x-.3,154.6,-2.8,.6,.4,5.6);c.box('实际侧导轨','metal',3.05,0,-.2,.3,155,.4);c.box('未绑定导轨光学面','civicGuideOptic',3.35,0,-.12,.015,155,.24);for(const y of[0,150])c.pin('导轨固定销','bronze',[3.32,y+.1,.1]);return c.finish();});b.place(shaft,world,0,'shaft');
 const gauge=civicAsset(b,'lift-open-platform-gauge',id=>{const c=new CivicComponent(p,id,'静态开放乘舱与侧导向试架',['BUILT-177','BUILT-145'],{completeVehicleTemplate:false,walkY:0,stopBinding:false});c.box('乘舱地板','metal',-1.8,-.2,-1.9,3.6,.2,3.8);for(const x of[-1.8,1.7])for(const z of[-1.9,1.8])c.box('舱框竖柱','metal',x,0,z,.1,2.6,.1);for(const x of[-1.76,1.74])c.box('侧面玻璃','glass',x,.3,-1.8,.02,2.15,3.6);c.box('后舱玻璃','glass',-1.7,.3,1.84,3.4,2.15,.02);c.box('乘舱顶板','metal',-1.8,2.5,-1.9,3.6,.1,3.8);for(const y of[.5,2]){c.box('侧向连接托','metal',1.75,y,-.5,1.35,.18,1);for(const z of[-.28,.20])c.box('侧导向滑块','metal',2.98,y-.08,z,.42,.34,.08);}for(const x of[-1.7,1.68])c.pin('顶角销','bronze',[x,2.58,1.7]);return c.finish();});const car=b.place(gauge,plus(world,[0,carY,0]),0,'author-cabin');
 const docks:any[]=[];for(const y of[0,height]){const center=plus(world,[0,y,-7.5]),deck=civicAsset(b,'lift-station-platform',id=>civicPlate(p,id,8,10,[],.4));const platform=b.place(deck,center,0,'platform');const supports=civicAsset(b,'lift-landing-support-'+y,id=>{const c=new CivicComponent(p,id,'井架至接台实梁与斜撑',['BUILT-207','BUILT-308'],{landingY:y,terrainBound:false});for(const x of[-2.5,2.5]){c.box('接台纵向承梁','metal',x-.25,-.8,-12.5,.5,.4,10);if(y)c.beam('井架斜托','metal',[x,-10,-2.5],[x,-.7,-11.8],.4);else c.box('下站检修支脚','structuralConcrete',x-.3,-1.4,-11.5,.6,.6,.6);}return c.finish();});b.place(supports,plus(world,[0,y,0]),0,'landing-support');docks.push({platform,worldWalkY:world[1]+y,boardingEdge:plus(world,[0,y,-2.5])});}
 const bridge=civicAsset(b,'lift-boarding-bridge',id=>{const c=new CivicComponent(p,id,'停靠端有限登离接板',['BUILT-207','BUILT-293'],{length:.6,parkedOnly:true});c.box('接板','metal',-1.3,-.16,-2.5,2.6,.16,.6);for(const z of[-2.52,-1.92])c.box('端承舌','bridgeBearing',-1.2,-.2,z,2.4,.06,.04);c.pin('接板销','bronze',[1.1,-.02,-2.3]);return c.finish();});b.place(bridge,plus(world,[0,carY,0]),0,'boarding');
 return b.finish('BUILT-164',name,{parameters:{liftStop:stop},sourceEndpoints:{bottom:[140,103.6,35],top:[140,254.6,35]},verticalDeltaM:151,car,carWalkY:103.6+carY,stations:docks,worldSpace:'Provided source absolute metres; gallery translations are display only',completeVehicle:false,scope:'Same horizontal axis and exact 151m separation. Static bottom/top interface gauges and one parked boarding bridge, not original Vehicle lift/controller, stop gates, terrain or full travel certification.'});}
function ferry(p:Project,id:string,name:string){const b=new ArchitectureBuilder(p,id),berths:any[]=[],hull=b.original('BUILT-291'),guard=b.original('BUILT-292'),gangway=b.original('BUILT-293'),bollard=b.original('BUILT-300',{component:'bollard'}),fender=b.original('BUILT-300',{component:'fender'});
 const shore=civicAsset(b,'ferry-fixed-shore',id=>{const c=new CivicComponent(p,id,'带真实接板缺口的固定码头',['BUILT-312','BUILT-293'],{walkY:2.2,waterY:1.2});c.box('码头结构梁','metal',6.6,1.8,0,4,.2,10);for(const z of[0,6.2])c.box('码头实铺面','stone',6.6,2,z,4,.2,3.8);c.box('接板岸端连续铺面','stone',10,2,3.8,.6,.2,2.4);for(const x of[6.6,10.2])for(const z of[0,4.8,9.6])c.box('独立码头支柱','structuralConcrete',x,-.5,z,.4,2.3,.4);c.box('接板外端短托','metal',6,0,3.8,.2,2,2.4);for(const z of[1,7])c.box('护舷下托','metal',6,1.1,z,.6,.1,2);return c.finish();});
 for(const [label,offset]of[['清溪',[-60,0,0]],['千灯',[0,0,80]],['瀑云潭',[60,0,0]]]as [string,V3][]){const instances:string[]=[];for(const[a,pos,rot]of[[hull,[0,.2,0],0],[guard,[0,2.2,0],0],[gangway,[6,2,6.2],1],[shore,[0,0,0],0],[bollard,[6.8,2.2,.2],0],[bollard,[6.8,2.2,8.6],0],[fender,[6,1.2,3],1],[fender,[6,1.2,9],1]]as [string,V3,number][])instances.push(b.place(a,plus(pos,offset),rot,'berth'));
  for(const x of[6.9,10.3])for(const z of[.4,9.6])civicPost(b,2.4,.24,plus([x,2.2,z],offset));b.place(civicAsset(b,'dock-shelter',id=>civicRoof(p,id,9.2,3.4,1.4,'gable')),plus([8.6,4.6,5],offset),1,'roof');berths.push({name:label,offset,instances,shipWalkY:2.2,shoreWalkY:2.2,waterY:1.2,boardingLine:[plus([3,2.2,5],offset),plus([10.6,2.2,5],offset)]});}
 const water=civicAsset(b,'author-ferry-water-plane',id=>{const c=new CivicComponent(p,id,'明确作者平水面',[],{waterY:1.2,originalRiverBound:false,physical:false});c.box('非碰撞显示水面','water',-68,1.15,-8,148,.05,106);return c.finish();});b.place(water,[0,0,0],0,'water');
 const routes=[{from:'清溪',to:'千灯',points:[[-57,1.2,5],[-44,1.2,46],[3,1.2,85]]},{from:'瀑云潭',to:'千灯',points:[[63,1.2,5],[48,1.2,46],[3,1.2,85]]}];
 return b.finish('BUILT-165',name,{parameters:{},berths,authorRoutes:routes,originalThreePointRoutesAvailable:false,scope:'Two named three-point author routes and three actual finite hull/rail/gangway/dock installations. Native hull and deck masters are unchanged. Flat display water is not terrain, buoyancy, all-river navigability or operating ferry state; complete vehicle template remains separate.'});}
export function makeCivicTransport(p:Project,catalogId:string,id:string,name:string,params:Record<string,string|number>={}):Assembly{
 if(catalogId==='BUILT-161')return roads(p,id,name);if(catalogId==='BUILT-162')return railway(p,id,name);if(catalogId==='BUILT-163')return cable(p,id,name);if(catalogId==='BUILT-164')return lift(p,id,name,String(params.liftStop??'bottom'));if(catalogId==='BUILT-165')return ferry(p,id,name);throw new Error('Unknown civic transport');
}
