import {createHash} from 'node:crypto';
import {Grid} from '../core/grid';import {geometryData,assetBoundsM} from '../core/sky';import type {Asset,V3} from '../core/types';
import {ArchitectureBuilder} from './architecture-near-assembly';import {CivicComponent} from './civic-components';import {institutionalFurniture} from './institutional-components';import {garmentScene} from './garment-assembly';import {makeFlowerAsset} from './life';
export function communityFurniture(b:ArchitectureBuilder,n:number){const source=institutionalFurniture(b,n);if(![184,186,189,190,196].includes(n))return source;return b.asset('community-material-'+n,id=>{const old=b.p.assets[source],a=structuredClone(old),g=new Grid(a.chunks),s=b.p.styles.yunshan,changes:Record<string,number>={};for(const[cell,m]of g.cells()){const next=n===190?(m===s.leaf?s.plantStem:m===s.flowerAmber?s.pollenAnther:m):(m===s.energy?s.opticsGlow:m===s.warm?s.lightCore:m);if(next!==m){if(b.p.materials[m].solid!==b.p.materials[next].solid)throw new Error('Material-only derivative changes collision');g.set(cell,next);const k=m+'->'+next;changes[k]=(changes[k]??0)+1;}}a.id=id;a.name+=n===190?' · 独立茎叶与花药用途':' · 独立光学用途';a.chunks=g.serialize();a.source={kind:'assembly-derived-component',notCatalogMaster:true,baseCatalogIds:['LIFE-'+n],materialOnly:true,sourceAssetId:source,sourceGeometrySHA256:createHash('sha256').update(JSON.stringify(geometryData(old))).digest('hex'),materialChanges:changes,reason:n===190?'Original190 uses leaf for actual stems and flowerAmber for flower centres. This explicit derivative separates plantStem and pollenAnther while preserving every cell and metadata; original retained.':'Actual status indicator or enclosed lamp core only; original native occupancy and metadata preserved, zero emission and no state binding.'};return a;});}
/** One reusable flowering herb, three placements. Original auxiliary is retained separately. */
export function communityFlower(b:ArchitectureBuilder,petalRole='flowerWhite'){
 if(!['flowerWhite','shrubBlossom','flowerAmber'].includes(petalRole))throw new Error('Unknown blossom purpose');
 const original=b.asset('community-original-flower',id=>{const a=makeFlowerAsset(b.p.styles.yunshan);a.id=id;a.source={kind:'assembly-derived-component',baseCatalogIds:['LIFE-228'],notCatalogMaster:true,retainedOriginalAuxiliary:true,originalSource:a.source};return a;});
 return b.asset('community-continuous-flower-'+petalRole,id=>{const c=new CivicComponent(b.p,id,'连续草本茎叶与五瓣花',['LIFE-228'],{species:'unspecified flowering plant',sourceAuxiliary:original,sameAuxiliaryFamily:'community-flower',petalPurpose:petalRole,seedBinding:false});
  const stem:V3[]=[[0,-.06,0],[.012,.14,.004],[-.008,.32,.01],[.012,.52,.004],[.028,.71,0],[.015,.86,0]];c.tube('连续弯曲主茎','plantStem',stem,.009,12);
  for(let k=0;k<4;k++){const sign=k%2?-1:1,y=.19+k*.13,x=k%2?.005:-.002,end:V3=[sign*.13,y+.07,.025];c.tube('叶柄'+k,'plantStem',[[x,y,.007],end],.004,8);const tip:V3=[sign*.24,y+.095,.018];c.slab('独立连续叶片'+k,'leaf',[[sign*.08,y+.052,.025],[sign*.15,y+.075,-.015],tip,[sign*.15,y+.078,.075]],.004);}
  c.tube('连续花托','plantStem',[[.015,.83,0],[.015,.885,0]],.018,12);
  for(let j=0;j<5;j++){const angle=j*Math.PI*2/5,cs=Math.cos(angle),sn=Math.sin(angle),points=Array.from({length:12},(_,k)=>{const a=k*Math.PI/6,u=.042+.046*Math.cos(a),v=.025*Math.sin(a);return[.015+u*cs-v*sn,.885+.012*Math.cos(a),u*sn+v*cs]as V3;});c.slab('连续花瓣'+j,petalRole,points,.004);}
  for(const [x,y,z]of[[-.10,.67,.025],[.14,.76,.015]]){c.tube('分枝花梗','plantStem',[[.015,y-.16,.004],[x,y,z]],.004,8);for(let j=0;j<5;j++){const theta=j*Math.PI*2/5,cs=Math.cos(theta),sn=Math.sin(theta),points=Array.from({length:10},(_,k)=>{const v=k*Math.PI/5,u=.025+.029*Math.cos(v),t=.016*Math.sin(v);return[x+u*cs-t*sn,y+.008*Math.cos(v),z+u*sn+t*cs]as V3;});c.slab('侧枝连续花瓣'+j,petalRole,points,.003);}c.tube('侧枝花心','pollenAnther',[[x,y-.004,z],[x,y+.012,z]],.014,12);}
  c.tube('独立花心','pollenAnther',[[.015,.882,0],[.015,.90,0]],.022,16);const a=c.finish(),g=new Grid();g.set([2,178,-1],b.p.styles.yunshan.pollenAnther);a.cellSize=.005;a.chunks=g.serialize();a.source!.sourceAssetId=original;a.source!.minimumComponent='5mm native flower-centre detail, attached to continuous central disc';return a;});
}
/** Extract one verified wearer and its exact source graph, preserving actual rigs. */
export function communityResident(b:ArchitectureBuilder){
 const scene=garmentScene(b.p,'tops'),selected=Object.values(scene.instances).filter(i=>i.id.startsWith('top-0')),mapped=new Map<string,string>(),sources:any[]=[];
 function keep(key:string):string{if(mapped.has(key))return mapped.get(key)!;const old=scene.assets[key];if(!old)throw new Error('Missing resident source '+key);let id:string;
  if(old.source?.kind==='catalog-recipe'){id=b.original(String(old.source.catalogId),old.source.parameters as Record<string,string|number>);if(JSON.stringify(geometryData(b.p.assets[id]))!==JSON.stringify(geometryData(old)))throw new Error('Resident original recipe mismatch '+key);}
  else{const parent=keep(String(old.source!.sourceAssetId)),deps=(b.p.assets[parent].source?.baseCatalogIds??[b.p.assets[parent].source!.catalogId])as string[];id=b.asset('community-resident-'+key,aid=>{const a=structuredClone(old);a.id=aid;a.source={kind:'assembly-derived-component',baseCatalogIds:deps,notCatalogMaster:true,sourceAssetId:parent,retainedAuthorSource:structuredClone(old.source),sourceGeometrySHA256:createHash('sha256').update(JSON.stringify(geometryData(scene.assets[String(old.source!.sourceAssetId)]))).digest('hex'),rigidComponentDerivative:true,unchangedRig:true};return a;});}
  mapped.set(key,id);sources.push({sourceSceneAsset:key,retainedAsset:id});return id;
 }
 const chosen=selected.map(i=>({source:i,assetId:keep(i.assetId)})),minY=Math.min(...chosen.map(i=>assetBoundsM(b.p.assets[i.assetId])!.min[1])),offset=-minY,instances=chosen.filter(i=>i.source.id!=='top-0-body').map(i=>({sourceInstance:i.source.id,instance:b.place(i.assetId,[0,offset,0],0,'resident',i.source.name),assetId:i.assetId}));
 return{instances,sources,omittedRetainedInstances:[{sourceInstance:'top-0-body',assetId:chosen.find(i=>i.source.id==='top-0-body')!.assetId,reason:'After clothing replacement this asset contains only a short neck connector. CHAR066 already carries its real neck insert; retaining both caused actual overlap, so the redundant connector is retained but not installed.'}],sourceScene:'M036 garmentScene tops, complete top-0 only',bodyFit:'adultA',groundOffsetM:offset,declaredGroundY:0,originalBaseline:{catalogId:'CHAR-001',integratedCoarseSource:true,source:'external citizen-appearance.ts describeCitizen',coarsePitchM:.2,readOnlyInputs:['id','position','state','role','actorProfiles.age','alive']},originalRuntimeBound:false,authorRigidJoints:true,softSkin:false,animationClips:false,ageSeedRoleBinding:false,scope:'One author standing resident, not a recovered original describeCitizen implementation. Original canonical parts and exact derivative/rig graph retained; no gallery duplicates, no new base master.'};
}
