import {AvatarModel} from './avatar-model';
import {hollowLoft,type Ring} from './mesh-shapes';
import {garmentFront,garmentFrame,surfaceRibbon,sectorBand,bandMesh} from './garment-shapes';
import type {AuthoredMesh} from '../core/authored-mesh';
export const grid5=(n:number)=>Math.round(n/.005)*.005;
export function costumeButton(m:AvatarModel,name:string,base:AuthoredMesh[],x:number,y:number,role='garmentBuckle',joint='chest',size=.015){const z=garmentFront(base,x,y);if(z>=0)throw new Error('扣件须承接前衣面');m.box(name,role,grid5(x-size/2),grid5(y-size/2),grid5(z)-.005,size,size,.010,joint);}
export function costumeBadge(m:AvatarModel,base:AuthoredMesh[],x:number,y:number){const w=.030,h=.045,xx=grid5(x-w/2),yy=grid5(y),z=grid5(garmentFront(base,x,y+h*.5))-.005;m.box('身份扣塑料底板','uniformIdBack',xx,yy,z,w,h,.010,'chest');m.box('身份扣印刷竖条','uniformIdPrint',xx+.005,yy+.005,z-.005,.005,.030,.005,'chest');m.box('身份扣印刷横条','uniformIdPrint',xx+.010,yy+.025,z-.005,.015,.010,.005,'chest');m.box('身份扣最小上夹','garmentBuckle',xx+.010,yy+h,z,.010,.010,.010,'chest');}
/** Real open pocket with an independent lining and closed floor. */
export function costumePocket(m:AvatarModel,name:string,base:AuthoredMesh[],x:number,y:number,w:number,h:number,role:string,k=1){const depth=.018*k,t=.003*k,profiles:Ring[]=[y,y+h].map(yy=>{const z=garmentFront(base,x,yy);if(z>=0)throw new Error('口袋不能从前开口采到后背');return{y:yy,rx:w/2,rz:depth,x,z:z-depth+.001*k};}),inner=profiles.map((r,i)=>({...r,y:r.y+(i===0?t:0),rx:r.rx-t,rz:r.rz-t})),shell=hollowLoft(name,m.s[role],profiles,inner,'top',false);m.mesh(shell,'chest');m.mesh(hollowLoft(name+'独立衬里',m.s.garmentLining,inner.map((r,i)=>({...r,y:r.y+(i===0?.0003:0),rx:r.rx-.0003,rz:r.rz-.0003})),inner.map((r,i)=>({...r,y:r.y+(i===0?.0015:0),rx:r.rx-.0013,rz:r.rz-.0013})),'top',false),'chest');costumeButton(m,name+'最小止扣',[shell],x,y+h*.72,'garmentBuckle','chest',k<.8?.010:.015);return shell;}
export function costumeBelt(m:AvatarModel,fit:string,base:AuthoredMesh[],role='garmentStrap'){const f=garmentFrame(fit),k=f.h/1.7,y=f.hip+.055*k;surfaceRibbon(m,'前腰固定织带',role,base,[-f.q.hipRadiusM*.82,y],[f.q.hipRadiusM*.82,y],.033*k,'chest');costumeButton(m,'前腰最小扣',m.meshes,0,y,'garmentBuckle','chest',k<.8?.010:.020);}
export function costumeApronPanel(m:AvatarModel,fit:string,base:AuthoredMesh[],bib:boolean){const f=garmentFrame(fit),k=f.h/1.7,bottom=f.hip-.34*k,top=bib?f.sh-.095*k:f.hip+.065*k,topRx=bib?.12*k:f.q.hipRadiusM*.82,bottomZ=-f.depth*1.60,topZ=garmentFront(base,0,top)-.017*k;m.add(bib?'围裙胸兜及下摆':'服务衣独立围腰','apronCloth',[{y:bottom,rx:.18*k,rz:.004*k,z:bottomZ},{y:f.hip+.03*k,rx:.18*k,rz:.004*k,z:bottomZ},...(bib?[{y:f.hip+.140*k,rx:.16*k,rz:.004*k,z:garmentFront(base,0,f.hip+.140*k)-.016*k}]:[]),{y:top,rx:topRx,rz:.004*k,z:topZ}],'chest',false);const apron=m.meshes.at(-1)!;for(const side of[-1,1])costumePocket(m,'围裙工具袋-'+side,[apron],side*.085*k,f.hip-.24*k,.09*k,.115*k,'apronCloth',k);return apron;}
