import {emptyMesh,quad,type Ring} from './mesh-shapes';
import type {V3} from '../core/types';
import {AvatarModel} from './avatar-model';
import {garmentFrame,bandMesh,sectorBand,garmentFront,surfaceRibbon} from './garment-shapes';
export type CostumeCut={role:string;hem?:number;loose?:number;openFront?:boolean;sleeveRole?:string;shortSleeves?:boolean;collar?:'cross'|'stand'|'lapel'};
type CutRing=Ring&{power?:number};
/** Rounded rectangular lower cross-section accommodates two trouser legs without a circular balloon hem. */
function cutBand(name:string,material:number,rings:CutRing[],start:number,end:number,t:number,steps:number){const m=emptyMesh(name,material),full=end-start===Math.PI*2,count=full?steps:steps+1,points=(r:CutRing,inner=false)=>Array.from({length:count},(_,i)=>{const a=start+(end-start)*i/steps,pow=r.power??1,p=(n:number)=>Math.sign(n)*Math.abs(n)**pow;return[(r.x??0)+p(Math.sin(a))*(r.rx-(inner?t:0)),r.y,(r.z??0)-p(Math.cos(a))*(r.rz-(inner?t:0))] as V3;}),o=rings.map(r=>points(r)),ins=rings.map(r=>points(r,true));for(let k=0;k<rings.length-1;k++)for(let j=0;j<steps;j++){const next=(j+1)%count,a=start+(end-start)*(j+.5)/steps,n:V3=[Math.sin(a),0,-Math.cos(a)];quad(m,[o[k][j],o[k][next],o[k+1][next],o[k+1][j]],n);quad(m,[ins[k][j],ins[k][next],ins[k+1][next],ins[k+1][j]],n.map(v=>-v) as V3);}for(const k of[0,rings.length-1])for(let j=0;j<steps;j++){const next=(j+1)%count;quad(m,[o[k][j],o[k][next],ins[k][next],ins[k][j]],[0,k===0?-1:1,0]);}if(!full)for(const[j,a,sign]of [[0,start,-1],[steps,end,1]])for(let k=0;k<rings.length-1;k++)quad(m,[o[k][j],o[k+1][j],ins[k+1][j],ins[k][j]],[Math.cos(a)*sign,0,Math.sin(a)*sign]);return m;}
/** Dimensioned by each source body's own shoulder, waist and head dimensions. */
export function costumeProfiles(fit:string,cut:CostumeCut):CutRing[]{const f=garmentFrame(fit),k=f.h/1.7,L=cut.loose??0;return[{y:cut.hem??f.hip+.020*k,rx:f.q.hipHalfWidthM+f.legR*1.25+.014*k+L,rz:f.depth*1.30+L,power:.55},{y:f.hip+.034,rx:f.q.hipHalfWidthM+f.legR*1.25+.014*k+L,rz:f.depth*1.30+L,power:.55},{y:f.hip+(f.sh-f.hip)*.36,rx:f.q.waistHalfWidthM+.010*k+L,rz:f.depth*1.06+L},{y:f.sh-f.h*.060,rx:f.q.shoulderHalfWidthM*.94+L,rz:f.depth*1.15+L},{y:f.sh+.018*k,rx:f.q.shoulderHalfWidthM*.97+L,rz:f.depth*1.04+L},{y:f.neck-.014*k,rx:f.q.headM*.22+L,rz:f.q.headM*.205+L}];}
export function costumeTorso(m:AvatarModel,fit:string,cut:CostumeCut){const f=garmentFrame(fit),k=f.h/1.7,rings=costumeProfiles(fit,cut),start=m.meshes.length,t=.003*k;
 const patch=(name:string,rs:CutRing[],a:number,b:number,n:number)=>{m.mesh(cutBand(name,m.s[cut.role],rs,a,b,t,a===0&&b===Math.PI*2?16:n),'chest');m.mesh(cutBand(name+'内衬',m.s.garmentLining,rs.map(r=>({...r,rx:r.rx-t-.0002,rz:r.rz-t-.0002})),a,b,.0018*k,a===0&&b===Math.PI*2?16:n),'chest');};
 if(cut.openFront){patch('前开衣身连续左右背片',rings.slice(0,-2),Math.PI*.17,Math.PI*1.83,24);for(const[a,b]of [[Math.PI*.17,Math.PI/4],[Math.PI*3/4,Math.PI*5/4],[Math.PI*7/4,Math.PI*1.83]])patch('敞衣胸背片-'+a,rings.slice(-3),a,b,6);}
 else{patch('完整下胸腰腔',rings.slice(0,-2),0,Math.PI*2,32);for(const[a,b]of [[-Math.PI/4,Math.PI/4],[Math.PI*3/4,Math.PI*5/4]])patch('胸背接袖片-'+a,rings.slice(-3),a,b,4);}
 for(const[a,b]of [[Math.PI/4,Math.PI*3/4],[Math.PI*5/4,Math.PI*7/4]])patch('肩颈接合片-'+a,rings.slice(-2),a,b,4);
 const base=m.meshes.slice(start),a=rings.at(-2)!,b=rings.at(-1)!,at=(y:number)=>{const p=(y-a.y)/(b.y-a.y);return{y,rx:a.rx+(b.rx-a.rx)*p+.001*k,rz:a.rz+(b.rz-a.rz)*p+.001*k};};bandMesh(m,'真开低立领','garmentTrim',[at(f.neck-.029*k),at(f.neck-.015*k)],.004*k,'chest');
 if(!cut.openFront){if(cut.collar==='stand'){surfaceRibbon(m,'偏襟直织边','garmentTrim',base,[.024*k,f.neck-.039*k],[.024*k,f.hip+.04*k],.014*k,'chest');}else{surfaceRibbon(m,'连续交领主边','garmentLight',base,[-.024*k,f.neck-.036*k],[.09*k,f.hip+.05*k],.022*k,'chest');surfaceRibbon(m,'连续交领副边','garmentTrim',base,[.024*k,f.neck-.036*k],[-.06*k,f.sh-.12*k],.012*k,'chest');}}
 m.port('neck',[0,f.neck,0],[0,1,0],[.10*k,.01,.10*k],'chest');m.port('waist',[0,f.hip+.020*k,0],[0,-1,0],[rings[0].rx*2,.01,rings[0].rz*2],'chest');return{base,rings};
}
export function costumeSleeves(m:AvatarModel,fit:string,cut:CostumeCut){const f=garmentFrame(fit),{q,armR,elbow,sh,wrist,wristX}=f,k=f.h/1.7,L=cut.loose??0,role=cut.sleeveRole??cut.role;for(const side of[-1,1]){const x=side*(q.shoulderHalfWidthM+armR*.48),upper:Ring[]=[{y:elbow,rx:armR*.96+L,rz:armR*1.02+L,x},{y:sh-.03*f.h,rx:armR*1.13+L,rz:armR*1.17+L,x:side*q.shoulderHalfWidthM},{y:sh+.027*f.h,rx:armR*.75+L,rz:armR*.89+L,x:side*(q.shoulderHalfWidthM-.005)}],lower:Ring[]=[{y:wrist-.008*k,rx:armR*.99+L,rz:armR*1.06+L,x:side*wristX},{...upper[0]}];bandMesh(m,'上袖连续薄壳-'+side,role,upper,.003*k,'shoulder'+side);if(!cut.shortSleeves)bandMesh(m,'下袖连续薄壳-'+side,role,lower,.003*k,'elbow'+side);const end=cut.shortSleeves?upper[0]:lower[0];bandMesh(m,'袖端真实织边-'+side,'garmentTrim',[{...end,rx:end.rx+.002*k,rz:end.rz+.002*k},{...end,y:end.y+.024*k,rx:end.rx+.002*k,rz:end.rz+.002*k}],.005*k,cut.shortSleeves?'shoulder'+side:'elbow'+side);m.port((cut.shortSleeves?'sleeve-end':'wrist')+side,cut.shortSleeves?[x,elbow,0]:[side*wristX,wrist,0],[0,-1,0],[armR*2,.01,armR*2.1],(cut.shortSleeves?'shoulder':'elbow')+side);}}
