import {upperGarment} from './garment-upper';
import {AvatarModel} from './avatar-model';import {garmentFrame,garmentFront,torsoProfiles,surfaceRibbon,sectorBand,bandMesh} from './garment-shapes';import {costumeTorso,costumeSleeves,type CostumeCut} from './costume-frame';import {costumeButton,costumeBadge,costumePocket,costumeBelt,costumeApronPanel,grid5} from './costume-details';
export function costumeCut(id:string,fit:string):CostumeCut{const f=garmentFrame(fit),k=f.h/1.7,n=Number(id.slice(5)),roles=['infantWrap','schoolCloth','uniformCloth','uniformCloth','uniformCloth','garmentOuter','fieldCloth','medicalCloth','medicalCloth','labCoat','serviceCloth','apronCloth'],hem=[-.025,-.12,-.085,.018,-.06,.018,-.05,-.27,-.31,-.40,.014,.014][n-125];return{role:roles[n-125],hem:f.hip+hem*k,loose:n===134?.018:0,openFront:n===134,sleeveRole:[126,129,130,131,135].includes(n)?'garmentLight':roles[n-125],shortSleeves:n===131,collar:[127,128,129,132,133].includes(n)?'stand':n===134?'lapel':'cross'};}
export function buildCostume(m:AvatarModel,id:string,fit:string){const f=garmentFrame(fit),k=f.h/1.7,n=Number(id.slice(5)),cut=costumeCut(id,fit);
 if(n===136){const temp=new AvatarModel(m.s);upperGarment(temp,'CHAR-113',fit);const base=temp.meshes,panel=costumeApronPanel(m,fit,base,true),r=torsoProfiles(fit),a=r[3],b=r[4],at=(y:number)=>{const t=(y-a.y)/(b.y-a.y);return{y,rx:a.rx+(b.rx-a.rx)*t+.012*k,rz:a.rz+(b.rz-a.rz)*t+.012*k};},low=at(f.neck-.032*k),high=at(f.neck-.017*k);bandMesh(m,'围裙真正穿颈织环','garmentStrap',[low,high],.006*k,'chest');const raised=base.map(m=>({...m,positions:m.positions.map((v,i)=>v-(i%3===2?.012*k:0))}));for(const side of[-1,1]){const x=side*.045*k;surfaceRibbon(m,'围裙连续肩带-'+side,'garmentStrap',raised,[x,f.sh-.105*k],[x,low.y+.003*k],.022*k,'chest');costumeButton(m,'围裙胸带最小扣-'+side,[panel],x,f.sh-.115*k);}const waist=(y:number)=>{const t=(y-r[0].y)/(r[1].y-r[0].y);return{y,rx:r[0].rx+(r[1].rx-r[0].rx)*t+.012*k,rz:r[0].rz+(r[1].rz-r[0].rz)*t+.012*k};};bandMesh(m,'围裙背腰固定环','garmentStrap',[waist(f.hip+.125*k),waist(f.hip+.155*k)],.007*k,'chest');costumeButton(m,'围裙腰部最小扣',m.meshes,0,f.hip+.140*k);m.port('waist',[0,f.hip+.140*k,0],[0,-1,0],[waist(f.hip+.140*k).rx*2,.01,waist(f.hip+.140*k).rz*2],'chest');m.detail={independentApronOnly:true,targetUnderlayer:'CHAR-113',sourceBodyProportions:f.q,trueOpenNeckAndWaistLoops:true,openToolPockets:true,clothingDynamics:false};return;}
 const {base,rings}=costumeTorso(m,fit,cut);costumeSleeves(m,fit,cut);
 if(n===125){for(const side of[-1,1]){const x=side*.085*k;surfaceRibbon(m,'包衣系带-'+side,'garmentStrap',base,[x,f.sh-.060*k],[x,f.hip+.020*k],.018*k,'chest');costumeButton(m,'包衣最小布结-'+side,m.meshes,x,f.hip+.060*k,'garmentStrap','chest',.010);}m.detail={infantOwnBodyProportions:true,closure:'cloth ties; no metal buckle',sourceBody: 'CHAR-061'};}
 if(n===126){costumeBelt(m,fit,base);for(const side of[-1,1]){const x=side*.09*k;surfaceRibbon(m,'童装双肩织带-'+side,'garmentStrap',base,[x,f.sh-.06*k],[x,f.hip+.09*k],.022*k,'chest');costumeButton(m,'童装肩带最小扣-'+side,m.meshes,x,f.sh-.13*k,'garmentBuckle','chest',.010);}costumePocket(m,'童装前襟书签袋',base,-.08*k,f.hip-.025*k,.09*k,.075*k,'schoolCloth',k);}
 if([127,129].includes(n)){costumeBelt(m,fit,base);for(const side of[-1,1])costumePocket(m,(n===127?'警服胸袋':'调度侧袋')+side,base,side*.09*k,n===127?f.sh-.20*k:f.hip+.085*k,n===127?.09*k:.065*k,n===127?.105*k:.15*k,'uniformCloth',k);costumeBadge(m,base,-.075*k,f.sh-.11*k);if(n===129)surfaceRibbon(m,'调度服斜挂织带','garmentStrap',base,[-.10*k,f.sh-.06*k],[.095*k,f.hip+.13*k],.026*k,'chest');}
 if(n===128){const panels=[{y:f.hip+.10*k,rx:f.q.waistHalfWidthM*.84,rz:.008*k,z:-f.depth*1.20},{y:f.sh-.055*k,rx:f.q.shoulderHalfWidthM*.70,rz:.009*k,z:-f.depth*1.20}];m.add('分区胸部金属板','armorPlate',panels,'chest',false);const plate=m.meshes.at(-1)!;for(const side of[-1,1]){costumeButton(m,'胸甲最小铆扣-'+side,[plate],side*.07*k,f.sh-.12*k);const x=side*f.q.shoulderHalfWidthM;bandMesh(m,'肩部软垫-'+side,'armorPad',[{y:f.sh-.10*k,rx:f.armR*1.19,rz:f.armR*1.24,x},{y:f.sh+.03*k,rx:f.armR*.93,rz:f.armR*1.03,x}],.007*k,'shoulder'+side);bandMesh(m,'肩部独立护板-'+side,'armorPlate',[{y:f.sh-.08*k,rx:f.armR*1.21,rz:f.armR*1.27,x},{y:f.sh+.02*k,rx:f.armR*.98,rz:f.armR*1.08,x}],.004*k,'shoulder'+side);const y=f.sh-.055*k;costumeButton(m,'肩甲最小铆扣-'+side,m.meshes.filter(m=>m.name==='肩部独立护板-'+side),x,y,'garmentBuckle','shoulder'+side);}costumeBelt(m,fit,base);}
 if(n===130){costumeBelt(m,fit,base);for(const side of[-1,1]){costumePocket(m,'劳动衣工具袋-'+side,base,side*.095*k,f.hip+.08*k,.10*k,.115*k,'workReinforcement',k);const x=side*(f.q.shoulderHalfWidthM+f.armR*.48);bandMesh(m,'耐磨肘片-'+side,'workReinforcement',[{y:f.elbow+.004*k,rx:f.armR*.99,rz:f.armR*1.06,x},{y:f.elbow+.055*k,rx:f.armR*1.025,rz:f.armR*1.085,x}],.004*k,'shoulder'+side);costumeButton(m,'肘片最小织标-'+side,m.meshes.filter(m=>m.name==='耐磨肘片-'+side),x,f.elbow+.03*k,'uniformInsignia','shoulder'+side);}}
 if(n===131){costumeBelt(m,fit,base,'garmentLight');costumePocket(m,'田作侧边种袋',base,.09*k,f.hip+.085*k,.10*k,.13*k,'fieldCloth',k);surfaceRibbon(m,'田作斜襟加固带','workReinforcement',base,[-.075*k,f.sh-.09*k],[.09*k,f.hip+.08*k],.024*k,'chest');}
 if([132,133,134].includes(n)){const y=f.hip-.13*k,x=n===134?.185*k:.10*k;for(const side of[-1,1])costumePocket(m,(n===132?'诊疗窄器械袋':n===133?'护理前袋':'实验外套大袋')+side,base,side*x,y,n===132?.06*k:.10*k,n===132?.18*k:.14*k,cut.role,k);if(n!==134){costumeBadge(m,base,-.075*k,f.sh-.14*k);if(n===133)costumeBelt(m,fit,base,'medicalTrim');for(let j=0;j<3;j++)costumeButton(m,'偏襟最小扣-'+j,base,.025*k,f.hip+(.12+j*.085)*k);}else{for(const side of[-1,1]){const x=side*.16*k;costumeButton(m,'实验衣开襟最小扣-'+side,base,x,f.hip+.075*k);}}}
 if(n===135){costumeBadge(m,base,-.08*k,f.sh-.14*k);costumeBelt(m,fit,base);costumeApronPanel(m,fit,base,false);}
 m.detail={...m.detail,cut,sourceBodyProportions:f.q,upperClothingOnly:true,oldBodySurfaceMustBeReplaced:true,finiteRigidJoints:true,softCloth:false,minimumDetailPitchM:.005,frontPocketsAreActualOpenShells:true};
}
