import {CatmullRomCurve3,Vector3} from 'three';
import {AvatarModel} from './avatar-model';import {ROOT,pin} from './held-shapes';
import {emptyMesh,quad,triangle,roundLoft,mergeMeshes} from './mesh-shapes';import {axisMesh} from './attire-shapes';import {oval} from './care-goods';
import type {V3} from '../core/types';import type {AuthoredMesh} from '../core/authored-mesh';

/** An anatomically tapered closed tube. Ring order is fixed along the curve. */
export function faunaTube(m:AvatarModel,name:string,role:string,path:V3[],radius:number,tip=radius,flat=1,segments=14,sides=10){
 const c=new CatmullRomCurve3(path.map(p=>new Vector3(...p))),f=c.computeFrenetFrames(segments,false),centres=c.getPoints(segments),rings=centres.map((p,i)=>Array.from({length:sides},(_,j)=>p.clone().addScaledVector(f.normals[i],Math.cos(j/sides*Math.PI*2)*(radius+(tip-radius)*i/segments)).addScaledVector(f.binormals[i],Math.sin(j/sides*Math.PI*2)*(radius+(tip-radius)*i/segments)*flat))),mesh=emptyMesh(name,m.s[role]);
 const face=(a:Vector3,b:Vector3,c:Vector3)=>{const n=b.clone().sub(a).cross(c.clone().sub(a)).normalize(),k=mesh.positions.length/3;for(const p of[a,b,c]){mesh.positions.push(...p.toArray().map(n=>Math.round(n*1e9)/1e9||0));mesh.normals.push(...n.toArray());mesh.uvs.push(p.x,p.y);}mesh.indices.push(k,k+1,k+2);};
 for(let i=0;i<segments;i++)for(let j=0;j<sides;j++){const k=(j+1)%sides;face(rings[i][j],rings[i][k],rings[i+1][k]);face(rings[i][j],rings[i+1][k],rings[i+1][j]);}for(let j=0;j<sides;j++){const k=(j+1)%sides;face(centres[0],rings[0][k],rings[0][j]);face(centres[segments],rings[segments][j],rings[segments][k]);}m.mesh(mesh,ROOT);
}
/** Closed pointed feather/ear, oriented from its root to its tip without resampling. */
export function feather(m:AvatarModel,name:string,role:string,start:V3,end:V3,width:number,thickness:number){const length=new Vector3(...end).distanceTo(new Vector3(...start));m.mesh(axisMesh(roundLoft(name,m.s[role],[{y:0,rx:width*.38,rz:thickness*.5},{y:length*.32,rx:width,rz:thickness},{y:length*.72,rx:width*.78,rz:thickness*.68},{y:length,rx:.0015,rz:.0015}],10),start,end),ROOT);}
/** A fan-shaped solid fin with a convex planar outline and an actual narrow edge. */
export function fin(m:AvatarModel,name:string,role:string,outline:V3[],thickness:number){const a=outline.map(p=>new Vector3(...p)),normal=a[1].clone().sub(a[0]).cross(a[2].clone().sub(a[0])).normalize(),mid=a.reduce((c,p)=>c.add(p),new Vector3()).multiplyScalar(1/a.length),top=a.map(p=>p.clone().addScaledVector(normal,thickness/2)),bottom=a.map(p=>p.clone().addScaledVector(normal,-thickness/2)),mesh=emptyMesh(name,m.s[role]);for(let i=0;i<a.length;i++){const j=(i+1)%a.length;triangle(mesh,mid.clone().addScaledVector(normal,thickness/2).toArray(),top[i].toArray(),top[j].toArray(),normal.toArray());triangle(mesh,mid.clone().addScaledVector(normal,-thickness/2).toArray(),bottom[j].toArray(),bottom[i].toArray(),normal.clone().negate().toArray());const out=a[i].clone().add(a[j]).multiplyScalar(.5).sub(mid);quad(mesh,[top[i],bottom[i],bottom[j],top[j]].map(p=>p.toArray()),out.toArray());}m.mesh(mesh,ROOT);}
/** Coat/scales remain thin closed patches on the actual surface, not floating pebbles. */
export function surfacePatch(m:AvatarModel,name:string,role:string,source:AuthoredMesh,pick:(c:V3)=>boolean){const mesh=emptyMesh(name,m.s[role]);for(let k=0;k<source.indices.length;k+=3){const ids=source.indices.slice(k,k+3),v=ids.map(i=>new Vector3(...source.positions.slice(i*3,i*3+3))),c=v.reduce((a,b)=>a.add(b),new Vector3()).multiplyScalar(1/3);if(!pick(c.toArray()))continue;const n=new Vector3(...source.normals.slice(ids[0]*3,ids[0]*3+3));v.forEach(p=>p.lerp(c,.00001));const outer=v.map(p=>p.clone().addScaledVector(n,.0004)),inner=v.map(p=>p.clone().addScaledVector(n,-.001));triangle(mesh,...outer.map(p=>p.toArray()) as [V3,V3,V3],n.toArray());triangle(mesh,...inner.slice().reverse().map(p=>p.toArray()) as [V3,V3,V3],n.clone().negate().toArray());for(let j=0;j<3;j++){const h=(j+1)%3;quad(mesh,[outer[j],inner[j],inner[h],outer[h]].map(p=>p.toArray()),outer[h].clone().sub(outer[j]).cross(n).toArray());}}if(mesh.indices.length)m.mesh(mesh,ROOT);}
export function sideEyes(m:AvatarModel,c:V3,half:number,r=.012){for(const side of[-1,1]){oval(m,'眼白'+side,'eyeWhite',[side*half,c[1],c[2]],[r*.65,r,r]);oval(m,'侧向虹膜'+side,'animalIris',[side*(half+r*.46),c[1],c[2]],[r*.27,r*.75,r*.74]);pin(m,'最小瞳孔'+side,[side*(half+r*.63),c[1],c[2]],'animalPupil',r>.020?.010:.005);}}
export function splitHoof(m:AvatarModel,name:string,x:number,z:number,width:number,length:number,height:number){for(const side of[-1,1]){m.add(name+'分趾'+side,'animalHoof',[{x:x+side*width*.26,y:0,z:z-.012,rx:width*.24,rz:length*.52},{x:x+side*width*.24,y:height,z:z+.004,rx:width*.21,rz:length*.44}],ROOT,false);}}
export function compactRole(m:AvatarModel,role:string,label:string){const parts=m.meshes.filter(x=>x.material===m.s[role]);if(parts.length<2)return;m.detail.mergedParts??={};(m.detail.mergedParts as Record<string,string[]>)[label]=parts.map(x=>x.name);m.meshes=m.meshes.filter(x=>x.material!==m.s[role]);m.meshes.push(mergeMeshes(label,parts));m.rig!.meshJoints=Object.fromEntries(m.meshes.map(x=>[x.name,ROOT]));}
