import type {Asset,V3,Project} from '../core/types';import type {AuthoredMesh} from '../core/authored-mesh';import {Grid} from '../core/grid';import {AvatarModel,axisPose,snap} from './avatar-model';import {garmentRig,garmentFrame,torsoProfiles,sectorBand} from './garment-shapes';import {emptyMesh,triangle} from './mesh-shapes';
export type GarmentPose='standing'|'walking'|'seated'|'raisedArms';
/** Split actual source triangles, close their new section, and retain the source asset separately. */
export function splitGarmentBodyMesh(source:AuthoredMesh,y:number,upper:boolean){const out=emptyMesh(source.name+(upper?'上分件':'下分件'),source.material),cuts=new Map<string,V3>(),inside=(p:V3)=>upper?p[1]>=y-1e-10:p[1]<=y+1e-10;for(let k=0;k<source.indices.length;k+=3){const ids=source.indices.slice(k,k+3),poly=ids.map(i=>source.positions.slice(i*3,i*3+3) as V3),normal=source.normals.slice(ids[0]*3,ids[0]*3+3) as V3,clipped:V3[]=[];for(let i=0;i<3;i++){const a=poly[i],b=poly[(i+1)%3],A=inside(a),B=inside(b);if(A)clipped.push(a);if(A!==B){const t=(y-a[1])/(b[1]-a[1]),p=a.map((v,d)=>snap(v+(b[d]-v)*t)) as V3;p[1]=snap(y);clipped.push(p);cuts.set(p.join(','),p);}if(Math.abs(a[1]-y)<1e-9)cuts.set(a.join(','),a);}for(let i=1;i<clipped.length-1;i++){const a=clipped[0],b=clipped[i],c=clipped[i+1],u=b.map((v,d)=>v-a[d]),v=c.map((n,d)=>n-a[d]);if(Math.hypot(u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0])>1e-12)triangle(out,a,b,c,normal);}}
 const ring=[...cuts.values()],centre=ring.reduce((a,v)=>a.map((n,d)=>n+v[d]/ring.length) as V3,[0,0,0] as V3);ring.sort((a,b)=>Math.atan2(a[2]-centre[2],a[0]-centre[0])-Math.atan2(b[2]-centre[2],b[0]-centre[0]));for(let i=0;i<ring.length;i++)triangle(out,centre,ring[i],ring[(i+1)%ring.length],[0,upper?-1:1,0]);return out;
}
export function garmentPoseAsset(source:Asset,pose:GarmentPose,id=source.id):Asset{const a=structuredClone(source);if(!a.rig)throw new Error('衣装姿态缺实际绑定');a.id=id;if(id!==source.id){a.category='import';a.source={...a.source,kind:'author-garment-pose',notCatalogMaster:true,sourceAssetId:source.id,pose,originalSkeletonBound:false};}a.rig.pose={...source.rig!.pose};for(const side of[-1,1]){if(pose==='walking'){a.rig.pose['shoulder'+side]=axisPose([1,0,0],-side*Math.PI/12);a.rig.pose['hip'+side]=axisPose([1,0,0],side*Math.PI/15);if(side<0)a.rig.pose['knee'+side]=axisPose([1,0,0],-Math.PI/18);}if(pose==='raisedArms')a.rig.pose['shoulder'+side]=axisPose([0,0,1],side*Math.PI/4);if(pose==='seated'){a.rig.pose['hip'+side]=axisPose([1,0,0],Math.PI/2);a.rig.pose['knee'+side]=axisPose([1,0,0],-Math.PI/2);a.rig.pose['shoulder'+side]=axisPose([1,0,0],Math.PI/7);}}return a;}
export function garmentBodySlot(source:Asset,fit:string,ids:string[],s:Record<string,number>,id:string):Asset{const a=structuredClone(source),m=new AvatarModel(s),f=garmentRig(m,fit),upper=ids.some(id=>['CHAR-113','CHAR-114','CHAR-117','CHAR-124'].includes(id)),sleeved=ids.some(id=>['CHAR-113','CHAR-114','CHAR-124'].includes(id)),lower=ids.some(id=>['CHAR-115','CHAR-118','CHAR-119','CHAR-124'].includes(id)),vest=ids.includes('CHAR-117'),removed:string[]=[];a.meshes=[];for(const original of source.meshes!){const name=original.name,arm=name.startsWith('肩肘腕连续袖身-'),leg=name.startsWith('裤腿膝踝连续收束-');if(upper&&(name==='髋腹胸肩连续衣身'||name==='衣领承接颈部')||sleeved&&(arm||name.startsWith('袖口织边-'))||lower&&(leg||name.startsWith('裤脚织边-')||name.startsWith('膝前衣褶-'))){removed.push(name);continue;}const mesh=structuredClone(original),side=name.endsWith('--1')?-1:1;if(arm||leg){if(arm&&vest){mesh.material=s.skinSurface;mesh.name='作者暴露手臂-'+side;}for(const high of[false,true]){const piece=splitGarmentBodyMesh(mesh,arm?f.elbow:f.q.kneeYM,high);a.meshes.push(piece);m.rig!.meshJoints[piece.name]=(arm?(high?'shoulder':'elbow'):(high?'hip':'knee'))+side;}}else{if(vest&&name.startsWith('袖口织边-')){removed.push(name);continue;}a.meshes.push(mesh);m.rig!.meshJoints[mesh.name]=name.startsWith('袖口')?'elbow'+side:name.startsWith('裤脚')||name.startsWith('膝前')?'knee'+side:'chest';}}
 if(upper){m.add('作者颈部连接皮肤','skinSurface',[{y:f.neck-.030,rx:f.q.headM*.18,rz:f.q.headM*.175},{y:f.neck+.003,rx:f.q.headM*.18,rz:f.q.headM*.175}],'chest');a.meshes.push(...m.meshes);}
 const g=new Grid(source.chunks),hiddenParts=upper?source.parts.filter(p=>p.id!=='root'):[];for(const[v]of g.cells())if(hiddenParts.some(p=>v.every((n,d)=>n>=p.region.min[d]&&n<p.region.max[d])))g.set(v,0);a.chunks=g.serialize();a.parts=g.count?source.parts.filter(p=>!hiddenParts.includes(p)):[];a.rig=m.rig;a.rig!.voxelJoints=g.count?[{region:g.bounds()!,joint:'chest'}]:[];a.ports=[];a.rig!.sockets={};a.id=id;a.name='衣装替换身体框架 · '+fit;a.category='import';a.source={kind:'author-garment-body-slot',notCatalogMaster:true,sourceAssetId:source.id,originalBodyRetained:true,removedMeshes:removed,removedNativeParts:hiddenParts.map(p=>p.name),exposedArmsAreAuthorProfileStudy:vest,cutSourceMeshesAtActualElbowKnee:true,oldCoveredExtremitiesExcluded:true,hiddenBodyPolicy:'Replace covered torso/sleeve/trouser display surfaces; do not overlay duplicate old clothing'};return a;}
/** Place unchanged native cells at a metre-space origin, then bind the whole accessory to one body joint. */
export function garmentMount(source:Asset,fit:string,joint:string,offset:V3,s:Record<string,number>,id:string):Asset{const a=structuredClone(source),m=new AvatarModel(s);garmentRig(m,fit);a.id=id;a.name+=' · 衣装安装';a.category='import';a.origin=offset.map(snap) as V3;a.rig=m.rig;a.rig!.joints[0].translation=offset.map(v=>snap(-v)) as V3;if(joint.startsWith('wrist')){const side=joint.endsWith('-1')?-1:1;a.rig!.joints.push({id:'hand-basis',parent:joint,translation:[0,0,0]});a.rig!.pose['hand-basis']=axisPose([0,1,0],-side*Math.PI/3);joint='hand-basis';}a.rig!.meshJoints=Object.fromEntries(a.meshes!.map(m=>[m.name,joint]));const g=new Grid(a.chunks);a.rig!.voxelJoints=g.count?[{region:g.bounds()!,joint}]:[];a.rig!.sockets=Object.fromEntries(a.ports.map(p=>[p.id,joint]));a.source={kind:'author-garment-mounted-component',notCatalogMaster:true,sourceAssetId:source.id,originOnlyRelocation:true,rigidBodyJoint:joint,originalComponentRigRetainedInSource:true};return a;}
/** A coat installation replaces hidden under-shirt panels, while retaining its independent source master. */
export function garmentCoatUnderlayer(source:Asset,fit:string,s:Record<string,number>,id:string):Asset{const a=structuredClone(source),remove=(name:string)=>name.startsWith('上袖')||name.startsWith('下袖')||name.startsWith('独立袖口')||name.startsWith('肩顶桥片')||name==='衣腰织边'||name.startsWith('衣身独立胸背片-2.356'),removed=a.meshes!.filter(m=>remove(m.name)).map(m=>m.name);a.meshes=a.meshes!.filter(m=>!remove(m.name));for(const name of removed)delete a.rig!.meshJoints[name];
 const rings=torsoProfiles(fit).slice(0,3);for(const name of['衣身真实腰腔','衣身独立内衬']){const index=a.meshes.findIndex(m=>m.name===name),old=a.meshes[index],inner=name.endsWith('内衬'),r=inner?rings.map(v=>({...v,rx:v.rx-.0042,rz:v.rz-.0042})):rings;a.meshes[index]=sectorBand(name,old.material,r,-Math.PI*.30,Math.PI*.30,inner?.002:.004,12);}
 const hidden=a.parts.filter(p=>p.name.startsWith('袖部')||p.name==='衣腰最小搭扣'),g=new Grid(a.chunks);for(const[v]of g.cells())if(hidden.some(p=>v.every((n,d)=>n>=p.region.min[d]&&n<p.region.max[d])))g.set(v,0);a.chunks=g.serialize();a.parts=a.parts.filter(p=>!hidden.includes(p));a.parts.find(p=>p.id==='root')!.region=g.bounds()!;a.rig!.voxelJoints=a.rig!.voxelJoints.filter(r=>!hidden.some(p=>JSON.stringify(p.region)===JSON.stringify(r.region)));a.ports=a.ports.filter(p=>!p.id.startsWith('wrist'));for(const k of Object.keys(a.rig!.sockets))if(k.startsWith('wrist'))delete a.rig!.sockets[k];a.id=id;a.category='import';a.name+=' · 长衫内搭可见分件';a.source={...a.source,kind:'author-coat-underlayer',sourceAssetId:source.id,notCatalogMaster:true,sourceMasterRetained:true,removedHiddenMeshes:removed,removedHiddenNativeParts:hidden.map(p=>p.name),torsoRetainedSectorRadians:[-Math.PI*.30,Math.PI*.30],originalGarmentGeometryPreserved:false,reason:'Replace hidden sleeves, rear/shoulder panels and redundant waistband with its buckle in this explicit coat installation; retain the source master'};return a;}
