import {AvatarModel} from './avatar-model';
import {roundBand,type Ring} from './mesh-shapes';
import {garmentFrame,torsoProfiles,sectorBand,surfaceRibbon,garmentFront,bandMesh} from './garment-shapes';
export function upperGarment(m:AvatarModel,id:string,fit:string){const f=garmentFrame(fit),{q,hip,sh,neck,armR,elbow,wrist,wristX}=f,coat=id==='CHAR-116',vest=id==='CHAR-117',sleep=id==='CHAR-124',light=id==='CHAR-113'||sleep,role=sleep?'sleepCloth':light?'garmentLight':'garmentOuter',rings=torsoProfiles(fit,coat?.018:0),joint='chest',start=m.meshes.length;
 if(vest)rings[3].y=sh+.057;
 const inner=(r:Ring[])=>r.map(v=>({...v,rx:v.rx-.0042,rz:v.rz-.0042})),patch=(name:string,r:Ring[],a:number,b:number,steps:number)=>{m.mesh(sectorBand(name,m.s[role],r,a,b,.004,steps),joint);m.mesh(sectorBand(name+'独立内衬',m.s.garmentLining,inner(r),a,b,.002,steps),joint);};
 if(coat){const long:Ring[]=[{y:hip-.34,rx:q.hipRadiusM*1.30,rz:f.depth*1.27},...rings];patch('长衫真正前敞口',long.slice(0,4),Math.PI*.19,Math.PI*1.81,16);for(const[a,b]of [[Math.PI*.19,Math.PI/4],[Math.PI*3/4,Math.PI*5/4],[Math.PI*7/4,Math.PI*1.81]])patch('长衫肩片-'+a,rings.slice(2),a,b,4);}
 else{bandMesh(m,'衣身真实腰腔',role,rings.slice(0,3),.004,joint);bandMesh(m,'衣身独立内衬','garmentLining',inner(rings.slice(0,3)),.002,joint);for(const[a,b]of [[-Math.PI/4,Math.PI/4],[Math.PI*3/4,Math.PI*5/4]])patch('衣身独立胸背片-'+a,rings.slice(2),a,b,8);}
 for(const[a,b]of [[Math.PI/4,Math.PI*3/4],[Math.PI*5/4,Math.PI*7/4]])patch('肩顶桥片-'+a,rings.slice(3),a,b,4);
 const collar=(y:number)=>{const a=rings.at(-2)!,b=rings.at(-1)!,t=(y-a.y)/(b.y-a.y);return{y,rx:a.rx+(b.rx-a.rx)*t,rz:a.rz+(b.rz-a.rz)*t};};bandMesh(m,'真实开放领圈','garmentTrim',coat?[collar(neck-.025),collar(neck-.015)]:[{...rings.at(-1)!,y:neck-.025},{...rings.at(-1)!,y:neck-.015}],.004,joint);
 const torso=m.meshes.slice(start);
 if(!coat){surfaceRibbon(m,'交领斜向主织边',sleep?'garmentOuter':'garmentLight',torso,[-.026,neck-.036],[.092,hip+.08],.026,joint);surfaceRibbon(m,'交领另一襟边','garmentTrim',torso,[.025,neck-.036],[-.058,sh-.15],.014,joint);}
 if(!sleep)for(const side of[-1,1]){const x=side*(coat?(q.shoulderHalfWidthM*.88+.018)*.66:q.waistHalfWidthM*.72);surfaceRibbon(m,'肩前固定织带-'+side,'garmentStrap',torso,[x,coat?sh-.14:sh-.06],[x,coat?sh-.09:hip+.04],coat?.010:.026,joint);const y=coat?sh-.12:sh-.15,z=garmentFront(torso,x,y);m.box('肩带金属最小扣-'+side,'garmentBuckle',x-.0075,y-.01,z-.010,.015,.020,.010,joint);}
 if(!vest)for(const side of[-1,1]){const sx=side*q.shoulderHalfWidthM,ex=side*(q.shoulderHalfWidthM+armR*.48),wx=side*wristX,extra=coat?.026:0,upper:Ring[]=[{y:elbow,rx:armR*.98+extra,rz:armR*1.02+extra,x:ex},{y:sh-.045,rx:armR*1.20+extra,rz:armR*1.21+extra,x:sx},{y:sh+.027*q.heightM,rx:armR*.77+extra,rz:armR*.93+extra,x:side*(q.shoulderHalfWidthM-.005)}],lower:Ring[]=[{y:wrist-.008,rx:armR*1.04+extra,rz:armR*1.13+extra,x:wx},{y:elbow,rx:armR*.98+extra,rz:armR*1.02+extra,x:ex}],sleeveRole=coat?'garmentOuter':sleep?'sleepCloth':'garmentLight';
  bandMesh(m,'上袖真腔-'+side,sleeveRole,upper,.004,'shoulder'+side);bandMesh(m,'下袖真腔-'+side,sleeveRole,lower,.004,'elbow'+side);bandMesh(m,'独立袖口织边-'+side,'garmentTrim',[{...lower[0],rx:lower[0].rx+.003,rz:lower[0].rz+.003},{...lower[0],y:wrist+.025,rx:lower[0].rx+.003,rz:lower[0].rz+.003}],.007,'elbow'+side);
  if(!sleep){const y=elbow+.065,x=ex,rz=armR*1.10+extra; m.box('袖部最小织片-'+side,'garmentStrap',x-.015,y,-rz-.004,.030,.040,.010,'shoulder'+side);m.box('袖部最小扣-'+side,'garmentBuckle',x-.005,y+.015,-rz-.009,.010,.015,.005,'shoulder'+side);}
 }
 if(!coat){const r=rings[0];bandMesh(m,'衣腰织边','garmentTrim',[{...r,y:hip+.026,rx:r.rx+.003,rz:r.rz+.003},{...r,y:hip+.056,rx:r.rx+.003,rz:r.rz+.003}],.007,joint);if(!sleep)m.box('衣腰最小搭扣','garmentBuckle',-.0125,hip+.030,-r.rz-.009,.025,.020,.010,joint);}
 if(coat)for(const side of[-1,1]){const x=side*.15,y=hip-.19,z=garmentFront(torso,x,y);m.box('长衫下摆最小扣-'+side,'garmentBuckle',x-.0075,y,z-.010,.015,.025,.010,joint);}
 if(id==='CHAR-114')for(const side of[-1,1]){const x=side*.082;m.add('袍上身独立前襟垂片-'+side,'garmentOuter',[{y:hip-.17,rx:.028,rz:.004,x,z:-.210},{y:hip+.038,rx:.029,rz:.004,x,z:-.194},{y:hip+.105,rx:.029,rz:.004,x,z:garmentFront(torso,x,hip+.105)-.002}],'pelvis',false);m.box('袍襟最小织扣-'+side,'garmentBuckle',x-.0075,hip-.145,-.215,.015,.025,.010,'pelvis');}
 m.port('neck',[0,neck,0],[0,1,0],[.10,.01,.10],joint);m.port('waist',[0,hip+.020,0],[0,-1,0],[rings[0].rx*2,.01,rings[0].rz*2],joint);for(const side of[-1,1])if(!vest)m.port('wrist'+side,[side*wristX,wrist,0],[0,-1,0],[armR*2.08,.01,armR*2.26],'elbow'+side);
 m.detail={bodyFit:fit,torsoProfiles:rings,neckAndWaistOpen:true,realArmholeGaps:true,sleeveless:vest,openFront:coat,sourceBodyShellReplacement:!coat,coatRequiresIndependentUnderlayer:coat,restSleeveSeamY:elbow,clothDynamics:false};
}
