import type {V3} from '../core/types';
import type {AuthoredMesh} from '../core/authored-mesh';
import {AvatarModel,axisPose} from './avatar-model';
import {emptyMesh,quad,roundBand,ellipsePoints,type Ring} from './mesh-shapes';
import {figureProportions} from './atlas-figure';
export const garmentBodyId=(fit:string)=>fit==='child'?'CHAR-063':fit==='adultB'?'CHAR-060':'CHAR-059';
export function garmentFrame(fit:string){const q=figureProportions[garmentBodyId(fit)],h=q.heightM,hip=q.hipYM,sh=q.shoulderYM,armR=h*.038,legR=q.hipHalfWidthM*.69;return{q,h,hip,sh,armR,legR,depth:q.hipRadiusM*.65,neck:h-q.headM,ankle:h*.059,elbow:sh-(sh-hip)*.48,wrist:hip+.037,wristX:q.shoulderHalfWidthM+armR*.67};}
export function garmentRig(m:AvatarModel,fit:string){const f=garmentFrame(fit),{q,h,hip,sh,armR,elbow,wrist,wristX,ankle}=f;m.bind('humanoid');m.joint('root',null,[0,0,0]);m.joint('pelvis','root',[0,hip,0]);m.joint('chest','pelvis',[0,sh,0]);m.joint('head','chest',[0,f.neck,0]);for(const side of[-1,1]){const tag=String(side);m.joint('shoulder'+tag,'chest',[side*q.shoulderHalfWidthM,sh,0]);m.joint('elbow'+tag,'shoulder'+tag,[side*(q.shoulderHalfWidthM+armR*.48),elbow,0]);m.joint('wrist'+tag,'elbow'+tag,[side*wristX,wrist,0]);m.joint('hip'+tag,'pelvis',[side*q.hipHalfWidthM,hip,0]);m.joint('knee'+tag,'hip'+tag,[side*q.hipHalfWidthM,q.kneeYM,-.005]);m.joint('ankle'+tag,'knee'+tag,[side*q.hipHalfWidthM,ankle,0]);}for(const side of[-1,1])m.rig!.pose['shoulder'+side]=axisPose([0,0,1],side*Math.PI/22.5);return f;}
/** A closed thin angular patch. Shared boundaries stay real, with no voxel resampling. */
export function sectorBand(name:string,material:number,rings:Ring[],start:number,end:number,thickness=.004,steps=8):AuthoredMesh{const m=emptyMesh(name,material),points=(r:Ring,inner=false)=>Array.from({length:steps+1},(_,i)=>{const a=start+(end-start)*i/steps;return[(r.x??0)+Math.sin(a)*(r.rx-(inner?thickness:0)),r.y,(r.z??0)-Math.cos(a)*(r.rz-(inner?thickness:0))] as V3;}),o=rings.map(r=>points(r)),ins=rings.map(r=>points(r,true));for(let k=0;k<rings.length-1;k++)for(let j=0;j<steps;j++){const a=start+(end-start)*(j+.5)/steps,n:V3=[Math.sin(a),0,-Math.cos(a)];quad(m,[o[k][j],o[k][j+1],o[k+1][j+1],o[k+1][j]],n);quad(m,[ins[k][j],ins[k][j+1],ins[k+1][j+1],ins[k+1][j]],n.map(v=>-v) as V3);}for(const k of[0,rings.length-1])for(let j=0;j<steps;j++)quad(m,[o[k][j],o[k][j+1],ins[k][j+1],ins[k][j]],[0,k===0?-1:1,0]);for(const[j,a,sign]of [[0,start,-1],[steps,end,1]])for(let k=0;k<rings.length-1;k++)quad(m,[o[k][j],o[k+1][j],ins[k+1][j],ins[k][j]],[Math.cos(a)*sign,0,Math.sin(a)*sign]);return m;}
/** Frontmost actual triangle intersection at an XY point, used to seat trim and native buttons. */
export function garmentFront(meshes:AuthoredMesh[],x:number,y:number){let z=Infinity;for(const m of meshes)for(let k=0;k<m.indices.length;k+=3){const[a,b,c]=m.indices.slice(k,k+3).map(i=>m.positions.slice(i*3,i*3+3)),d=(b[1]-c[1])*(a[0]-c[0])+(c[0]-b[0])*(a[1]-c[1]);if(Math.abs(d)<1e-12)continue;const u=((b[1]-c[1])*(x-c[0])+(c[0]-b[0])*(y-c[1]))/d,v=((c[1]-a[1])*(x-c[0])+(a[0]-c[0])*(y-c[1]))/d,w=1-u-v;if(Math.min(u,v,w)>-1e-8)z=Math.min(z,u*a[2]+v*b[2]+w*c[2]);}if(!Number.isFinite(z))throw new Error('衣面饰边无承接面 '+x+','+y);return z;}
export function surfaceRibbon(m:AvatarModel,name:string,role:string,base:AuthoredMesh[],a:[number,number],b:[number,number],width:number,joint:string,steps=10){const mesh=emptyMesh(name,m.s[role]),dx=b[0]-a[0],dy=b[1]-a[1],L=Math.hypot(dx,dy),nx=-dy/L*width/2,ny=dx/L*width/2,front=Array.from({length:steps+1},(_,i)=>{const x=a[0]+dx*i/steps,y=a[1]+dy*i/steps;return[-1,1].map(side=>{const xx=x+nx*side,yy=y+ny*side;return[xx,yy,garmentFront(base,xx,yy)-.004] as V3;});}),back=front.map(row=>row.map(([x,y,z])=>[x,y,z+.006] as V3));for(let i=0;i<steps;i++){quad(mesh,[front[i][0],front[i][1],front[i+1][1],front[i+1][0]],[0,0,-1]);quad(mesh,[back[i][0],back[i][1],back[i+1][1],back[i+1][0]],[0,0,1]);for(const side of[0,1])quad(mesh,[front[i][side],front[i+1][side],back[i+1][side],back[i][side]],[nx*(side?1:-1),ny*(side?1:-1),0]);}for(const i of[0,steps])quad(mesh,[front[i][0],front[i][1],back[i][1],back[i][0]],[dx*(i?1:-1),dy*(i?1:-1),0]);m.mesh(mesh,joint);}
export function bandMesh(m:AvatarModel,name:string,role:string,rings:Ring[],thickness:number,joint:string){m.mesh(roundBand(name,m.s[role],rings,thickness),joint);}
export function torsoProfiles(fit:string,loose=0){const{q,hip,sh,depth,neck}=garmentFrame(fit);return[{y:hip+.020,rx:q.hipRadiusM*1.32+loose,rz:depth*1.40+loose},{y:hip+(sh-hip)*.36,rx:q.waistHalfWidthM+.006+loose,rz:depth*1.03+loose},{y:sh-.23,rx:q.shoulderHalfWidthM*.88+loose,rz:depth*1.13+loose},{y:sh+.030,rx:q.shoulderHalfWidthM*.98+loose,rz:depth+loose},{y:neck-.014,rx:q.headM*.22+loose,rz:q.headM*.205+loose}] as Ring[];}
