import type {Asset,Project,V3} from '../core/types';import {makeGarmentAsset} from './atlas-garments';import {makeFigureAsset} from './atlas-figure';import {makeAvatarAsset} from './atlas-avatar';import {reflectAvatar} from './avatar-assembly';import {garmentBodyId,garmentFrame} from './garment-shapes';import {garmentBodySlot,garmentCoatUnderlayer,garmentMount,garmentPoseAsset,type GarmentPose} from './garment-body';
export const garmentScenes=['tops','robe','skirt-sash','sleepwear','footwear','poses','layers'] as const;export type GarmentScene=typeof garmentScenes[number];
export function garmentScene(base:Project,kind:GarmentScene):Project{const p=structuredClone(base);p.name='M036 · '+kind+' 作者衣装';p.assets={};p.instances={};const s=p.styles.yunshan,keep=(a:Asset)=>p.assets[a.id]??(p.assets[a.id]=a),place=(a:Asset,position:V3,key:string)=>{keep(a);p.instances[key]={id:key,assetId:a.id,name:a.name,position,rotation:0,parent:null};},garment=(id:string,fit:string)=>keep(makeGarmentAsset(id,id,id.toLowerCase()+'-'+fit,s,id==='CHAR-123'?{}:{bodyFit:fit})),posed=(a:Asset,pose:GarmentPose)=>pose==='standing'?a:keep(garmentPoseAsset(a,pose,a.id+'-'+pose));
 const component=(type:'head'|'hair'|'hand'|'foot',fit:string)=>{const child=fit==='child',scale=child?'child':'adult',id=type+'-'+scale;if(p.assets[id])return p.assets[id];return keep(type==='head'?child?makeAvatarAsset('CHAR-068','独立学龄头',id,s,{headStage:'school'}):makeFigureAsset('CHAR-066','独立成人头',id,s):makeAvatarAsset(type==='hair'?'CHAR-085':type==='hand'?'CHAR-070':'CHAR-071','独立'+type,id,s,type==='hair'?{hairFit:scale}:{limbFit:scale}));};
 const mounted=(src:Asset,fit:string,joint:string,offset:V3)=>keep(garmentMount(src,fit,joint,offset,s,'mounted-'+src.id+'-'+fit+'-'+joint));
 function wearer(key:string,fit:string,ids:string[],pose:GarmentPose,x:number){const f=garmentFrame(fit),position:V3=[x,(pose==='seated'?f.q.kneeYM-f.hip:0)+.020,0],body=keep(makeFigureAsset(garmentBodyId(fit),'保留原身体','body-'+fit,s,{extremities:'sockets'})),slot=keep(garmentBodySlot(body,fit,ids,s,'slot-'+fit+'-'+ids.join('-')));place(posed(slot,pose),position,key+'-body');for(const id of ids){const a=garment(id,fit),installed=id==='CHAR-113'&&ids.includes('CHAR-116')?keep(garmentCoatUnderlayer(a,fit,s,a.id+'-coat-underlayer')):a;place(posed(installed,pose),position,key+'-'+id);}for(const type of['head','hair'] as const)place(posed(mounted(component(type,fit),fit,'head',[0,f.neck,0]),pose),position,key+'-'+type);for(const side of[-1,1]){for(const type of['hand','foot'] as const){const raw=component(type,fit),reflected=type==='hand'?side>0:side<0,src=reflected?keep(reflectAvatar(raw,raw.id+'-reflected')):raw,offset:V3=type==='hand'?[side*f.wristX,f.wrist,0]:[side*f.q.hipHalfWidthM,f.ankle,0],joint=(type==='hand'?'wrist':'ankle')+side;place(posed(mounted(src,fit,joint,offset),pose),position,key+'-'+type+side);}}}
 if(kind==='tops')for(const[i,id]of ['CHAR-113','CHAR-114','CHAR-117'].entries())wearer('top-'+i,'adultA',[id,'CHAR-118','CHAR-121'],'standing',(i-1)*.95);
 if(kind==='robe')for(const[i,fit]of ['adultA','adultB'].entries())wearer('robe-'+i,fit,['CHAR-114','CHAR-115','CHAR-121'],'standing',(i-.5)*1.1);
 if(kind==='skirt-sash'){wearer('skirt','adultB',['CHAR-113','CHAR-119','CHAR-122'],'standing',-.55);wearer('sash','adultA',['CHAR-117','CHAR-118','CHAR-120','CHAR-122'],'standing',.55);}
 if(kind==='sleepwear')for(const[i,fit]of ['adultA','adultB'].entries())wearer('sleep-'+i,fit,['CHAR-124','CHAR-122'],'standing',(i-.5)*.95);
 if(kind==='footwear')for(const[i,id]of ['CHAR-121','CHAR-122','CHAR-123'].entries()){const fit=id==='CHAR-123'?'child':'adultA',f=garmentFrame(fit),position:V3=[(i-1)*.48,.020,0];place(garment(id,fit),position,'shoe-'+i);for(const side of[-1,1]){const foot=component('foot',fit),src=side<0?keep(reflectAvatar(foot,foot.id+'-reflected')):foot;place(mounted(src,fit,'ankle'+side,[side*f.q.hipHalfWidthM,f.ankle,0]),position,'foot-'+i+'-'+side);}}
 if(kind==='poses'){wearer('walk','adultA',['CHAR-113','CHAR-118','CHAR-121'],'walking',-1);{const fit='adultB',f=garmentFrame(fit),position:V3=[0,f.q.kneeYM-f.hip+.020,0];for(const id of ['CHAR-118','CHAR-122'])place(posed(garment(id,fit),'seated'),position,'seated-lower-study-'+id);for(const side of[-1,1]){const raw=component('foot',fit),src=side<0?keep(reflectAvatar(raw,raw.id+'-reflected')):raw;place(posed(mounted(src,fit,'ankle'+side,[side*f.q.hipHalfWidthM,f.ankle,0]),'seated'),position,'seated-lower-study-foot'+side);}}wearer('raise','adultA',['CHAR-113','CHAR-118','CHAR-121'],'raisedArms',1);}
 if(kind==='layers'){wearer('coat-a','adultA',['CHAR-113','CHAR-118','CHAR-116','CHAR-121'],'standing',-.6);wearer('coat-b','adultB',['CHAR-113','CHAR-118','CHAR-116','CHAR-122'],'raisedArms',.6);}
 p.selection={assetId:Object.values(p.instances)[0].assetId,partId:null,region:null};return p;
}
