import type {Asset,Command,V3} from '../core/types';
import {Grid} from '../core/grid';
import {Shapes} from './shapes';
import {makeGroundscapeAsset,bearingPads,wallFront,weepXs} from './atlas-groundscape';
import {composeHydrology} from './hydrology-composition';
const q=(n:number)=>Math.round(n/.2);
const make=(catalogId:string,id:string,params:Record<string,number|string>={}):Command=>({op:'produceCatalogAsset',catalogId,id,params});
const put=(id:string,assetId:string,position:V3):Command=>({op:'instance',id,assetId,position,rotation:0});
const install=(asset:Asset):Command=>({op:'installAsset',asset});
function aux(s:Record<string,number>,id:string,name:string,draw:(b:Shapes)=>void){const b=new Shapes(.2,s);draw(b);return b.finish(id,name,{kind:'author-groundscape-fixture',originalTerrainBound:false,structuralCapacityVerified:false,hydraulicsVerified:false});}
function floor(s:Record<string,number>,x:number,z:number,w:number,d:number):Command[]{const a=aux(s,'ground','明确作者承托地面（辅助）',b=>b.b(x,0,z,w,.2,d,s.bedrock));return[install(a),put('ground-1',a.id,[0,0,0])];}
export function groundscapePlantsCommands(s:Record<string,number>):Command[]{const ground=aux(s,'ground','作者石路、地被土床与芦苇湿岸土带',b=>{b.b(-3,0,-3,28,.2,6,s.bedrock);b.b(-3,0,-1.8,28,.2,4.8,s.surfaceSoil);b.b(17,0,-1.8,6,.2,4.8,s.wetSoil);});return[install(ground),put('ground-1','ground',[0,0,0]),make('ENV-062','grass-short',{height:.4}),make('ENV-062','grass-tall',{height:.6}),make('ENV-064','fern',{groundcover:'fern'}),make('ENV-064','broadleaf',{groundcover:'broadleaf'}),make('ENV-065','reed'),...['grass-short','grass-tall','fern','broadleaf','reed'].map((id,i)=>put(id+'-1',id,[i*5,.2,0]))];}
export const groundscapePlantsClearances=[{name:'地被列前方1.2米通路，植株不侵入',min:[-3,.2,-3] as V3,max:[25,1.92,-1.8] as V3}];
export function groundscapePondsCommands(s:Record<string,number>):Command[]{return[.4,.8].flatMap((depth,i)=>{const plant=makeGroundscapeAsset('ENV-066','床面到水面的真实荷叶','lotus-'+i,s,{waterDepth:depth}),pg=new Grid(plant.chunks),pond=aux(s,'pond-'+i,'明确浅静水床；植物实际排开水格',b=>{b.b(-3,0,-3,6,.2,6,s.bedrock);b.b(-3,.2,-3,6,.2,6,s.wetSoil);b.b(-3,.4,-3,6,depth,6,s.water);for(const[v]of pg.cells())b.g.set([v[0],v[1]+2,v[2]],0);}),union=composeHydrology('pond-union-'+i,[{asset:pond,position:[0,0,0],instanceId:'pond-'+i},{asset:plant,position:[0,.4,0],instanceId:'lotus-'+i}],{routes:[{points:[[-3,depth+.4,0],[3,depth+.4,0]],startDistanceM:0}],materialIds:[s.water],animated:false,originalRouteBound:false});union.source!.plantInstallation={waterDepthM:depth,rootBottomYM:.4,bedTopYM:.4,waterSurfaceYM:depth+.4,stillWaterOnly:true,nativeDisplacement:true,originalPondBound:false};return[install(plant),install(pond),install(union),put('pond-'+i+'-1',union.id,[i*10,0,0])];});}
export const groundscapePondsClearances=[{name:'两种水深样池之间的空域',min:[3.2,0,-3] as V3,max:[6.8,1.72,3] as V3}];
export function groundscapeVinesCommands(s:Record<string,number>):Command[]{const wall=aux(s,'vine-wall','藤蔓实际附着的作者岩壁',b=>{b.b(-3,0,0,6,5.2,.6,s.bedrock);b.b(5,0,0,6,5.2,.6,s.weatheredRock);});return[install(wall),put('wall-1',wall.id,[0,0,0]),...[2.4,4.8].flatMap((vineDrop,i)=>[make('ENV-067','vine-'+i,{vineDrop}),put('vine-'+i+'-1','vine-'+i,[i*8,5,0])])];}
export const groundscapeVinesClearances=[{name:'藤叶外侧前方真实身体净空',min:[-3,0,-2] as V3,max:[11,1.72,-.8] as V3}];
export function groundscapeLitterCommands(s:Record<string,number>):Command[]{return[...floor(s,-2,-3,26,6),...['leaves','branches','log'].flatMap((litterForm,i)=>[make('ENV-069',litterForm,{litterForm}),put(litterForm+'-1',litterForm,[i*8,.2,0])])];}
export const groundscapeLitterClearances=[{name:'倒木与枯枝前方保持通行',min:[-2,.2,-3] as V3,max:[24,1.92,-1.8] as V3}];
export function groundscapeExcavationsCommands(s:Record<string,number>):Command[]{const approach=aux(s,'approach','与坑底同高的作者入口岩面',b=>{for(const x of[5,21])b.b(x,0,-3,2.4,.4,3,s.bedrock);});return[install(approach),put('approach-1',approach.id,[0,0,0]),...['courtyard','basement'].flatMap((excavation,i)=>[make('ENV-077',excavation,{excavation}),put(excavation+'-1',excavation,[i*16,0,0])])];}
export const groundscapeExcavationsClearances=[0,16].map(x=>({name:'原生入口至开挖区域身体通道 '+x,min:[x+5,.4,-3] as V3,max:[x+7.4,2.12,3] as V3}));
export function groundscapeShoulderCommands(s:Record<string,number>):Command[]{return[make('ENV-078','shoulder'),put('shoulder-1','shoulder',[0,0,0])];}
export const groundscapeShoulderClearances=Array.from({length:30},(_,i)=>({name:'岩质台阶第'+(i+1)+'级身体净空',min:[.8,(i+1)*.2,i*.4] as V3,max:[3.2,(i+1)*.2+1.72,(i+1)*.4] as V3}));
export function groundscapeFoundationsCommands(s:Record<string,number>):Command[]{const frame=aux(s,'building-frame','建筑域辅助四柱及楼板（不是ENV母版）',b=>{for(const p of bearingPads)b.b(p.x+.6,p.top,p.z+.6,.4,5.6-p.top,.4,s.metal);b.b(.8,5.6,.8,8.4,.2,6.4,s.structuralConcrete);});return[install(frame),...['rock','soil'].flatMap((substrate,i)=>[make('ENV-081',substrate,{substrate}),put(substrate+'-1',substrate,[i*14,0,0]),put('frame-'+i,frame.id,[i*14,0,0])])];}
export const groundscapeFoundationsClearances=[0,14].map(x=>({name:'辅助建筑板面身体净空 '+x,min:[x+.8,5.8,.8] as V3,max:[x+9.2,7.52,7.2] as V3}));
export function groundscapeWallsCommands(s:Record<string,number>):Command[]{return[2.4,3.6].flatMap((height,i)=>{const wall=makeGroundscapeAsset('ENV-082','厚基脚挡墙','wall-'+i,s,{height}),cap=makeGroundscapeAsset('ENV-084','压顶','cap-'+i,s,{detail:'cap'}),sleeve=makeGroundscapeAsset('ENV-084','泄水石套','sleeve-'+i,s,{detail:'weep'}),pieces=[{a:wall,p:[0,0,0] as V3},{a:cap,p:[0,height,wallFront(height-.2)-.2] as V3},...weepXs.map(x=>({a:sleeve,p:[x,.6,.4] as V3}))],occupied=new Set<string>();for(const{a,p}of pieces)for(const[v]of new Grid(a.chunks).cells())occupied.add(v.map((n,d)=>n+q(p[d])).join(','));const fill=aux(s,'backfill-'+i,'实接墙背的排水石层和回填土，预留贯通检查槽',b=>{b.b(-.4,-.2,-1,8.8,.2,7,s.bedrock);b.b(0,0,2.4,8,height-.2,.8,s.drainAggregate);b.b(0,0,3.2,8,height-.2,2.8,s.soilSubstrate);b.b(0,height-.2,3.2,8,.2,2.8,s.surfaceSoil);for(const k of occupied){const v=k.split(',').map(Number) as V3;b.g.set(v,0);}for(const x of weepXs)b.b(x+.2,.8,2.4,.2,.2,3.6,0);});return[install(wall),install(cap),install(sleeve),install(fill),put('wall-'+i+'-1',wall.id,[i*13,0,0]),put('cap-'+i+'-1',cap.id,[i*13,height,wallFront(height-.2)-.2]),...weepXs.map((x,j)=>put('sleeve-'+i+'-'+j,sleeve.id,[i*13+x,.6,.4])),put('backfill-'+i+'-1',fill.id,[i*13,0,0])];});}
export const groundscapeWallsClearances=[0,13].flatMap(x=>[{name:'墙前维护通路 '+x,min:[x,0,-1] as V3,max:[x+8,1.72,-.2] as V3},...weepXs.map(v=>({name:'穿墙石套及背土实际贯通槽 '+x+' '+v,min:[x+v+.2,.8,0] as V3,max:[x+v+.4,1,6] as V3}))]);
export function groundscapeTerracesCommands(s:Record<string,number>):Command[]{return[.8,1.2].flatMap((terraceHeight,i)=>{const steps=aux(s,'steps-'+i,'与田块通路同高的前方作者石阶',b=>{for(let j=0;j<q(terraceHeight);j++)b.b(3.2,0,-(q(terraceHeight)-j)*.4,1.2,(j+1)*.2,.4,s.weatheredRock);});return[make('ENV-085','terrace-'+i,{terraceHeight}),put('terrace-'+i+'-1','terrace-'+i,[i*12,0,0]),install(steps),put('steps-'+i+'-1',steps.id,[i*12,0,0])];});}
export const groundscapeTerracesClearances=[.8,1.2].map((h,i)=>({name:'田块内通路、跨沟石及身体净空 '+h,min:[i*12+3.2,h,0] as V3,max:[i*12+4.4,h+1.72,6] as V3}));
export const groundscapeScenarios=[['plants',groundscapePlantsCommands,groundscapePlantsClearances],['ponds',groundscapePondsCommands,groundscapePondsClearances],['vines',groundscapeVinesCommands,groundscapeVinesClearances],['litter',groundscapeLitterCommands,groundscapeLitterClearances],['excavations',groundscapeExcavationsCommands,groundscapeExcavationsClearances],['shoulder',groundscapeShoulderCommands,groundscapeShoulderClearances],['foundations',groundscapeFoundationsCommands,groundscapeFoundationsClearances],['walls',groundscapeWallsCommands,groundscapeWallsClearances],['terraces',groundscapeTerracesCommands,groundscapeTerracesClearances]] as const;
