import type {Assembly,Project,V3} from '../core/types';
import {Grid} from '../core/grid';
import {assetBoundsM} from '../core/sky';
import {ArchitectureBuilder} from './architecture-near-assembly';
import {civicAsset} from './civic-landmarks';
import {fleetSource,type FleetSource} from './fleet-components';
import {LandscapeComponent,terrainTile,terrainHeightAt,type HeightField} from './landscape-components';
import {floodedField,rootedPlant,groundRamp} from './habitat-components';
import {districtHouse,route} from './district-components';
import {makeFleetVehicle} from './fleet-vehicles';
import {makeMetropolisInfrastructure} from './metropolis-infrastructure';

export const habitatAssemblyIds=['ENV-030','ENV-031','ENV-036','ENV-049','ENV-053','ENV-070','ENV-071','ENV-072','ENV-076','ENV-079','ENV-080','ENV-087'];
export const pondBed:HeightField=(x,z)=>{const angle=Math.atan2(z,x),r=Math.hypot(x,z)/(1+.13*Math.sin(angle*3)+.10*Math.cos(angle*5)),basin=Math.min(9+.5*Math.sin(x/7)*Math.sin(z/8),1.4+Math.max(0,r-5)**2*.052);return z>7?Math.min(basin,4.5+Math.max(0,Math.abs(x-1.4*Math.sin(z/8))-2.2)**2*.45):basin;};
export const shoalBed:HeightField=(x,z)=>Math.min(7.4+.3*Math.sin(z/6)**2,2.9+Math.max(0,Math.abs(x-2*Math.sin(z/8))-3)**2*.075+3.3*Math.exp(-((x+1)**2/10+(z+5)**2/18))+2.8*Math.exp(-((x-3)**2/8+(z-8)**2/13)));
const leftLevel=(x:number)=>x<=-22?18:x>=-16?6:18-(x+22)*2,rightLevel=(x:number)=>x>=22?14:x<=16?6:6+(x-16)*4/3;
export const confluenceBed:HeightField=(x,z)=>Math.min(12+.22*(32-z)+.6*Math.sin(x/9)**2,4.4+Math.max(0,Math.abs(x)-5)**2*.12,x<=-8?leftLevel(x)-.8+Math.max(0,Math.abs(z+10)-2)**2*.45:100,x>=8?rightLevel(x)-.8+Math.max(0,Math.abs(z-12)-2)**2*.45:100);
const forestBed:HeightField=(x,z)=>4+Math.max(0,Math.abs(x)-5)*.08+.8*Math.sin(z/16)**2*Math.min(1,Math.max(0,Math.abs(x)-5)/8);
const mixedBed:HeightField=(x,z)=>4+Math.max(0,x+6)*.28+.6*Math.sin(z/13)**2;
function part(b:ArchitectureBuilder,key:string,name:string,draw:(c:LandscapeComponent)=>void){return b.place(civicAsset(b,'habitat-'+key,id=>{const c=new LandscapeComponent(b.p,id,name,['ENV-001'],{key});draw(c);return c.finish();}),[0,0,0],0,'habitat-ground');}
/** The house floor owns its interior top surface. Porch paving surrounds its
 * footprint and meets it edge-to-edge, so no terrain skin competes with the floor. */
function courtFoundation(c:LandscapeComponent,pad:[number,number,number,number],foot:[number,number,number,number],y:number,bottom:number){
 const[x,z,X,Z]=pad,[a,b,A,B]=foot;c.box('台基至楼板底的实体','bedrock',x,bottom,z,X-x,y-.4-bottom,Z-z);
 for(const[i,[loX,loZ,hiX,hiZ]]of[[x,z,a,Z],[A,z,X,Z],[a,z,A,b],[a,B,A,Z]].entries()){if(hiX<=loX||hiZ<=loZ)continue;c.box('楼板外独立廊台路基 '+i,'weatheredRock',loX,y-.4,loZ,hiX-loX,.32,hiZ-loZ);c.box('楼板外独立廊台铺面 '+i,'stone',loX,y-.08,loZ,hiX-loX,.08,hiZ-loZ);}c.rock(x,bottom,z);
}
function terrain(b:ArchitectureBuilder,s:FleetSource,key:string,height:HeightField,size=64,step=2){terrainTile(b,s,key,[0,0,0],height,step,'near',size);s.terrainDomain={size,step,origin:[-size/2,-size/2],continuousPhysicalSurface:true};}
function waters(s:FleetSource,entries:ReturnType<typeof floodedField>[]){s.waterBodies=entries;for(const e of entries)for(const r of e.samples.filter((_,j)=>j%13===0))s.contacts.push({name:'actual water bed '+e.instance,point:[r.point[0],r.bedY-.02,r.point[2]]});}
/** Preserve all real component assets while making local placement provenance explicit. */
function reuse(b:ArchitectureBuilder,source:Assembly,omit:(assetId:string)=>boolean=()=>false){const map:Record<string,string>={};for(const i of source.instances){if(omit(i.assetId))continue;map[i.id]=b.place(i.assetId,i.position,i.rotation,(source.source!.instanceGroups as Record<string,string>)[i.id]??'reused',i.name);}b.dependencies.add(String(source.source!.catalogId));for(const d of source.source!.dependencies as string[])b.dependencies.add(d);const remap=(v:any):any=>typeof v==='string'?(map[v]??v):Array.isArray(v)?v.map(remap):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,remap(x)])):v;return{catalogId:source.source!.catalogId,sourceInstanceMap:map,source:remap(source.source),omittedInstances:source.instances.filter(i=>!map[i.id]).map(i=>({id:i.id,assetId:i.assetId})),geometryResampled:false};}
function plantSet(b:ArchitectureBuilder,s:FleetSource,key:string,points:[number,number][],ids:[string,Record<string,string|number>][],height:HeightField,step=2,origin=-32){return points.map(([x,z],j)=>rootedPlant(b,s,key+'-'+j,ids[j%ids.length][0],ids[j%ids.length][1],x,z,height,step,origin));}
function street(b:ArchitectureBuilder,s:FleetSource,key:string,y=4,width=4,from=-30,to=30){groundRamp(b,key,[0,y,from],[0,y,to],width,y-.6);route(s,key+' actual public corridor',[[0,y,from+.5],[0,y,to-.5]],3);}

export function makeHabitatAssembly(p:Project,catalogId:string,id:string,name:string,params:Record<string,string|number>={}){
 const b=new ArchitectureBuilder(p,id),s=fleetSource();s.terrainAuthority='Actual closed continuous terrain triangles;0.2m minimum native rock cells. Canonical plants and transport components retain their full original grids.';s.kinematics='Static authored environment only. Original terrain, hydrology, ecology, residency, permissions and controllers remain unbound.';
 if(catalogId==='ENV-030'){
  terrain(b,s,'irregular-pond',pondBed,48,1);waters(s,[floodedField(b,'irregular-pond',pondBed,()=>5.2,[-24,-24,24,24])]);s.hydrology={kind:'irregular deep pool with real outlet',waterY:5.2,deepBedY:1.4,outlet:[1.4*Math.sin(24/8),5.2,24],sameBedTriangles:true};s.forest=plantSet(b,s,'pond-edge',[[-20,-12],[18,-14],[-20,12],[16,15]],[['ENV-054',{}],['ENV-055',{}],['ENV-050',{height:16}]],pondBed,1,-24);s.understory=plantSet(b,s,'pond-understory',[[-15,-15],[13,-15],[-16,8],[11,16],[-5,-18],[19,5]],[['ENV-064',{groundcover:'fern'}],['ENV-061',{habit:'low'}]],pondBed,1,-24);
 }else if(catalogId==='ENV-031'){
  for(const x of[-16,16])for(const z of[-16,16])terrainTile(b,s,'shared-confluence',[x,0,z],confluenceBed,1,'near',32);s.terrainDomain={size:64,step:1,origin:[-32,-32],continuousPhysicalSurface:true};const main=floodedField(b,'confluence-main',confluenceBed,()=>6,[-8,-32,8,32]);const left=[floodedField(b,'left-upper',confluenceBed,()=>18,[-32,-16,-22,-4],1,'flowWater','x',1,-32,0),floodedField(b,'left-fall',confluenceBed,(x)=>leftLevel(x),[-22,-16,-16,-4],1,'fallWater','x',Math.sqrt(5),-22,10),floodedField(b,'left-lower',confluenceBed,()=>6,[-16,-16,-8,-4],1,'flowWater','x',1,-16,10+6*Math.sqrt(5))],right=[floodedField(b,'right-upper',confluenceBed,()=>14,[22,6,32,18],1,'flowWater','x',-1,32,0),floodedField(b,'right-fall',confluenceBed,(x)=>rightLevel(x),[16,6,22,18],1,'fallWater','x',-5/3,22,10),floodedField(b,'right-lower',confluenceBed,()=>6,[8,6,16,18],1,'flowWater','x',-1,16,20)];waters(s,[main,...left,...right]);s.waterJunctions=[[-22,18,-10],[-16,6,-10],[-8,6,-10],[22,14,12],[16,6,12],[8,6,12]].map((point,j)=>({name:'same graph join '+j,point:[point[0],point[1]-.2,point[2]],minimumPieces:2}));s.hydrology={main:main.instance,branches:[{from:left[0].instance,fall:left[1].instance,to:left[2].instance,joins:main.instance,dropM:12},{from:right[0].instance,fall:right[1].instance,to:right[2].instance,joins:main.instance,dropM:8}],graphAuthored:true,originalGraphAvailable:false,interfaceCaps:'Only closed reach/material boundaries; no caps within a reach.'};s.forest=plantSet(b,s,'confluence-forest',[[-26,-26],[-14,12],[20,-22],[26,26]],[['ENV-055',{}],['ENV-054',{}]],confluenceBed,1,-32);s.understory=plantSet(b,s,'confluence-understory',[[-20,-24],[19,-24],[-24,10],[24,-2]],[['ENV-064',{groundcover:'fern'}]],confluenceBed,1,-32);
 }else if(catalogId==='ENV-036'){
  terrain(b,s,'shoal-islands',shoalBed,48,1);waters(s,[floodedField(b,'shoal-islands',shoalBed,()=>5.2,[-24,-24,24,24])]);part(b,'exposed-gravel','砾洲上真实散砾与水蚀石',c=>{for(const[x,z]of[[-1,-5],[-2,-5],[0,-5],[-1,-6],[-1,-4],[3,8],[2.5,8],[3,9]]){const y=terrainHeightAt(shoalBed,x,z,1,-24,-24);c.slab('连续多面砾石','waterWornRock',Array.from({length:6},(_,j)=>[x+.38*Math.cos(j*Math.PI/3),y+.25+.06*Math.sin(j*2),z+.3*Math.sin(j*Math.PI/3)]as V3),.4);}c.rock(-1,6,-5);});s.hydrology={kind:'cut water topology around exposed gravel islands',waterY:5.2,exposedSites:[[-1,-5],[3,8]],wadingControllerBound:false};s.forest=plantSet(b,s,'shoal-bank',[[-15,-8],[15,12]],[['ENV-065',{}],['ENV-061',{habit:'low'}]],shoalBed,1,-24);
 }else if(catalogId==='ENV-049'){
  const bed:HeightField=(x,z)=>x>=9?1.8:Math.max(-.4,-.4+(x-8)*2.2);terrain(b,s,'real-ferry-bed',bed,48,1);waters(s,[floodedField(b,'berth-water',bed,()=>1.2,[-24,-24,24,24])]);const reused=reuse(b,makeFleetVehicle(p,'BUILT-284',id+'-ferry','完整渡船局部安装'),asset=>asset.includes('fleet-ferry-author-water'));for(const k of['routes','contacts','clearBoxes','driverEyes','walkSamples']as const)(s[k]as any[]).push(...(reused.source[k]??[]));part(b,'berth-keel-and-shore','明确静态龙骨检修托与真实码头承脚',c=>{for(const z of[3,7])c.box('静态龙骨检修托','structuralConcrete',1.5,-.4,z,3,.6,.5);for(const x of[10,14])for(const z of[3,7])c.box('码头实承脚','wetPileWood',x-.2,1.6,z-.2,.4,.25,.4);c.rock(10,1.4,3);});groundRamp(b,'berth-access',[12,1.8,-18],[12,2.2,2.5],5,1);route(s,'shore to preserved boarding platform',[[12,1.8,-18],[12,2.2,2.5],[12,2.2,5]],3);for(const z of[3.25,7.25])s.contacts.push({name:'actual keel support and bed',point:[3,-.4,z]});s.berth={reused,waterY:1.2,deckY:2.2,bedY:-.4,inspectionSupportsNotBuoyancy:true,originalTransportIdentityBound:false};
 }else if(catalogId==='ENV-053'){
  const seed=Number(params.layoutSeed??7);s.parameters={layoutSeed:seed};terrain(b,s,'city-forest',forestBed,96,2);street(b,s,'forest-public-street',4.2,6,-46,46);const belts=[];for(let j=0;j<13;j++){const side=j%2?-1:1,z=-38+Math.floor(j/2)*12,x=side*(j<8?14:31),offset=seed===19?2:0,points:[number,number][]=[[x,z+offset],[x+side*10,z+4-offset]],plants=plantSet(b,s,'belt-'+seed+'-'+j,points,j<8?[['ENV-050',{height:16}],['ENV-057',{}]]:[['ENV-054',{}],['ENV-055',{}]],forestBed,2,-48);belts.push({kind:j<8?'urban':'shoulder',plants});}s.forestBelts={seed,belts,urbanBelts:8,shoulderBelts:5,actualTrees:26,sourceUpperLimit:5200,sourceAlgorithmBound:false,excludedPublicCorridor:{minX:-5,maxX:5}};
 }else if(catalogId==='ENV-070'){
  terrain(b,s,'bamboo-understory',forestBed,64,2);street(b,s,'bamboo-path',4.2,4);const points:[number,number][]=[];for(const x of[-21,-11,10,20])for(const z of[-22,-8,6,20])points.push([x,z]);s.bamboo=plantSet(b,s,'bamboo',points,[['ENV-056',{}]],forestBed);s.understory=plantSet(b,s,'bamboo-ferns',[[-17,-15],[-15,14],[15,-15],[15,14],[-25,1],[25,1]],[['ENV-064',{groundcover:'fern'}],['ENV-062',{height:.6}]],forestBed);s.path={width:4,verifiedPublicWidth:3,worldEcologyBound:false};
 }else if(catalogId==='ENV-071'){
  terrain(b,s,'mixed-elevation-zones',mixedBed,64,2);const bands=[{zone:'moist lower broadleaf',x:-22,plants:[['ENV-050',{height:16}],['ENV-057',{}]]},{zone:'middle mixed forest',x:-3,plants:[['ENV-052',{}],['ENV-054',{}]]},{zone:'higher pine and cypress',x:19,plants:[['ENV-054',{}],['ENV-055',{}]]}];s.ecologyBands=bands.map((r,j)=>({zone:r.zone,moistureAuthorIndex:1-j*.3,plants:plantSet(b,s,'mixed-'+j,[-22,-7,8,23].map(z=>[r.x,z]),r.plants as [string,Record<string,string|number>][],mixedBed)}));s.understory=plantSet(b,s,'mixed-low-plants',[[-12,-18],[-13,16],[9,-20],[10,18]],[['ENV-061',{habit:'low'}],['ENV-064',{groundcover:'broadleaf'}]],mixedBed);s.ecologyScope='Different canonical trunk and crown structures, finite authored moisture/altitude zones; no ecology simulator or distance residency binding.';
 }else if(catalogId==='ENV-072'){
  const h:HeightField=()=>4;terrain(b,s,'green-court',h,48,2);const house=districtHouse(b,s,'green-court-house',[0,4.4,6],18,14,1,false,undefined,false);part(b,'green-house-foot','实承院宅与开放门前石台',c=>{courtFoundation(c,[-10,-3,10,14],[-9,-1,9,13],4.4,3.4);});groundRamp(b,'green-court-entry',[0,4,-20],[0,4.4,-3],4,3.4);route(s,'unblocked green court entrance',[[0,4,-20],[0,4.4,-3],[0,4.4,-1]],3);
  const containers=[];for(const x of[-15,11]){const asset=b.original('ENV-096',{planterForm:'tree'}),container=b.place(asset,[x,4,-12],0,'planter'),soil=part(b,'court-soil-'+x,'石树池内真实独立表土',c=>{c.box('树池内土','surfaceSoil',x+.4,4,-11.6,2.8,.4,2.8);c.rock(x+.4,4,-11.6);}),plant=b.place(b.original('ENV-060'),[x+1.6,4.4,-10.4],0,'vegetation');s.contacts.push({name:'tree planter roots on soil',point:[x+1.6,4.38,-10.4],exclude:plant,role:'surfaceSoil'},{name:'open bottom planter soil contacts terrain',point:[x+1.6,3.98,-10.4],exclude:soil});containers.push({container,soil,plant,cavity:p.assets[asset].source!.detail,openBottom:true});}
  const vine=b.original('ENV-067',{vineDrop:2.4}),wall=part(b,'vine-wall','院界藤蔓真实附着石壁',c=>{c.box('不占门窗的院界实墙','wall',-15,3.8,15,30,3.2,.4);c.rock(-15,3.8,15);}),vines=[];for(const x of[-10,0,10]){const instance=b.place(vine,[x,6.8,15.4],2,'vine');for(const port of p.assets[vine].ports.filter(p=>p.id.startsWith('holdfast')))s.contacts.push({name:'vine actual wall attachment',point:[x-port.position[0]-.1,6.8+port.position[1]+.1,15.39],exclude:instance,role:'wall'});vines.push(instance);}s.greenCourt={house,containers,vines,wall,doorsAndWindowsRetained:true,waterViewDirection:'front -Z',permissionsBound:false};
 }else if(catalogId==='ENV-076'){
  const bed:HeightField=(x,z)=>3.2+Math.max(0,Math.abs(x)-3)**2*.07;terrain(b,s,'wildlife-habitat',bed,24,1);waters(s,[floodedField(b,'wildlife-water',bed,()=>4.8,[-12,-12,12,12])]);s.forest=plantSet(b,s,'wildlife-bank',[[-9,-5],[9,5]],[['ENV-065',{}],['ENV-061',{habit:'low'}]],bed,1,-12);const bird=b.original('CHAR-320',{heronNeck:'watchful'}),birdBounds=assetBoundsM(p.assets[bird])!,birdY=Math.round((4.8-birdBounds.min[1])/.005)*.005;const perch=part(b,'heron-perch','鹭鸟足下的真实近岸石台',c=>{c.box('实际浅水观测石','waterWornRock',5,3.6,-1,1.6,1.2,2);c.rock(5,3.8,-1);});const birdInstance=b.place(bird,[5.8,birdY,0],0,'wildlife'),fish=b.original('CHAR-321',{streamTail:'broad-tail'}),fishInstances=[b.place(fish,[0,4,0],0,'wildlife'),b.place(fish,[1,4.2,3],1,'wildlife')],butterfly=b.original('CHAR-322',{butterflyWings:'spread-wings'}),insect=b.place(butterfly,[8,9,5],0,'wildlife');s.wildlife={sourceStatus:'待核实',sourceSpeciesAndBehaviorAvailable:false,staticAuthorStudy:true,ecologySimulation:false,bird:{instance:birdInstance,perchY:4.8},fish:{instances:fishInstances,waterY:4.8,bedMinimumY:3.2},insects:{instances:[insect],pose:'static flight shape; no animation or pollination'},catalogDomain:'CHAR originals; no new animal base masters'};s.contacts.push({name:'heron perch terrain',point:[5.8,terrainHeightAt(bed,5.8,0,1,-12,-12)-.02,0],exclude:perch});
 }else if(catalogId==='ENV-079'){
  const sites=[{x:-20,z:7,y:8},{x:0,z:11,y:10},{x:20,z:7,y:8}],h:HeightField=(x,z)=>{let v=3.2+Math.max(0,z+14)*.11;for(const r of sites){const d=Math.max(Math.abs(x-r.x)/8,Math.abs(z-r.z)/9),t=Math.max(0,Math.min(1,(1.35-d)/.35));v=v*(1-t)+(r.y-.4)*t;}return v;};terrain(b,s,'three-local-courts',h,80,2);const houses=[];for(const r of sites){part(b,'local-terrace-'+r.x,'局部肩台与独立表土断面',c=>{courtFoundation(c,[r.x-7.8,r.z-8,r.x+7.8,r.z+8],[r.x-6,r.z-6,r.x+6,r.z+6],r.y,3.2);});houses.push(districtHouse(b,s,'local-house-'+r.x,[r.x,r.y,r.z],12,12,1,false,undefined,false));groundRamp(b,'local-approach-'+r.x,[r.x,4,-30],[r.x,r.y,r.z-8],4,2.4);route(s,'actual local house approach '+r.x,[[r.x,4,-30],[r.x,r.y,r.z-8],[r.x,r.y,r.z-6]],3);s.contacts.push({name:'local rock shoulder into terrain',point:[r.x,r.y-.42,r.z]});}s.localCourts={houses,localShoulderWidthM:15.6,sourceHouseRange:[3,8],sourceShoulderRangeM:[12,20],wholeRegionFlattened:false};
 }else if(catalogId==='ENV-080'){
  const h:HeightField=()=>0;terrain(b,s,'market-ground',h,80,2);const reused=reuse(b,makeMetropolisInfrastructure(p,'BUILT-211',id+'-market','原52m作者市集完整组件'));part(b,'market-solid-ground','52m市集实体路基和独立入地承脚',c=>{c.box('市集下层实体岩土路基','bedrock',-26,-.6,-12,52,1.4,24);c.rock(-26,-.6,-12);});groundRamp(b,'market-bank-entry',[9,0,-28],[9,1.2,-12],4,-.6);route(s,'market entrance to actual street',[[9,0,-28],[9,1.2,-12],[9,1.2,-6]],3);route(s,'preserved 51m market street',[[-25.5,1.2,-6],[25.5,1.2,-6]],3);s.marketGrounding={reused,sourceRecipe:'current-v5-market-block-01 opt-in',historicalStatus:'隔离原型未集成',originalSharedRecipeAvailable:false,streetLengthM:52,lowerY:1.2,upperY:4.4,originalFailureOverridden:false};
 }else if(catalogId==='ENV-087'){
  const mode=String(params.entryTransition??'steps');s.parameters={entryTransition:mode};terrain(b,s,'entry-height',()=>4,40,2);part(b,'entry-solid-foundation','真实入口台基及实开门轴',c=>{courtFoundation(c,[-9,0,9,16],[-8,1,8,15],5.2,3.6);});const house=districtHouse(b,s,'entry-house',[0,5.2,8],16,14,1,false,undefined,false);
  if(mode==='ramp'){groundRamp(b,'entry-slope',[0,4,-16],[0,5.2,0],4,3.4);route(s,'actual continuous entry ramp',[[0,4,-16],[0,5.2,0],[0,5.2,1]],3);}else{part(b,'six-entry-treads','六级实体0.2m入口踏步',c=>{for(let j=0;j<6;j++)c.box('完整实踏步 '+j,'stone',-2,3.8,-3.6+j*.6,4,.2+(j+1)*.2,.6);c.rock(-2,3.8,-3.6);});for(let j=0;j<6;j++)for(const x of[-1.4,0,1.4])s.walkSamples.push({name:'entry tread '+j+' public width '+x,point:[x,4.2+j*.2,-3.3+j*.6],width:.2});route(s,'entry stairs upper join',[[0,5.2,-.25],[0,5.2,1]],3);route(s,'public approach to first step',[[0,4,-16],[0,4,-5.2]],3);}
  s.entry={mode,house,publicWidthM:3,geometryWidthM:4,eyeHeightM:1.72,steps:mode==='steps'?6:0,rise:mode==='steps'?.2:0,doorAxis:[0,5.2,1],controllerBound:false};
 }else throw new Error('Unknown habitat template');
 return b.finish(catalogId,name,JSON.parse(JSON.stringify(s)));
}
