import {Vector3} from 'three';import type {V3} from '../core/types';import {emptyMesh,quad,triangle} from './mesh-shapes';import {snap} from './avatar-model';
/** Parallel-transport frame tube: a true continuous closed fibre, no rasterized slope. */
export function fibre(name:string,material:number,points:V3[],radii:number[],sides=8){if(points.length!==radii.length||points.length<2)throw new Error('发束路径不匹配');const m=emptyMesh(name,material),rings:V3[][]=[],tangents:Vector3[]=[];let previous:Vector3|undefined;
 for(let i=0;i<points.length;i++){const a=new Vector3(...points[Math.max(0,i-1)]),b=new Vector3(...points[Math.min(points.length-1,i+1)]),t=b.sub(a).normalize();tangents.push(t);let n=previous?previous.clone().addScaledVector(t,-previous.dot(t)):new Vector3(1,0,0).addScaledVector(t,-t.x);if(n.length()<.01)n=new Vector3(0,0,1).addScaledVector(t,-t.z);n.normalize();previous=n;const bin=new Vector3().crossVectors(t,n).normalize();rings.push(Array.from({length:sides},(_,k)=>new Vector3(...points[i]).addScaledVector(n,Math.cos(k/sides*2*Math.PI)*radii[i]).addScaledVector(bin,Math.sin(k/sides*2*Math.PI)*radii[i]).toArray().map(snap) as V3));}
 for(let i=0;i<rings.length-1;i++)for(let k=0;k<sides;k++){const j=(k+1)%sides,center=new Vector3(...points[i]).add(new Vector3(...points[i+1])).multiplyScalar(.5),normal=new Vector3(...rings[i][k]).add(new Vector3(...rings[i][j])).add(new Vector3(...rings[i+1][j])).add(new Vector3(...rings[i+1][k])).multiplyScalar(.25).sub(center).toArray() as V3;quad(m,[rings[i][k],rings[i][j],rings[i+1][j],rings[i+1][k]],normal);}
 for(const i of[0,points.length-1])for(let k=0;k<sides;k++)triangle(m,points[i],rings[i][k],rings[i][(k+1)%sides],tangents[i].clone().multiplyScalar(i===0?-1:1).toArray() as V3);return m;
}
/** Closed arc strip with open angular centre; used for real receding hairline, not scalp paint. */
export function arcShell(name:string,material:number,rows:{y:number;rx:number;rz:number}[],from:number,to:number,thickness=.008,segments=16){const m=emptyMesh(name,material),inner=rows.map(r=>Array.from({length:segments+1},(_,i)=>{const t=from+(to-from)*i/segments;return[Math.sin(t)*r.rx,r.y,-Math.cos(t)*r.rz].map(snap) as V3;})),outer=rows.map(r=>Array.from({length:segments+1},(_,i)=>{const t=from+(to-from)*i/segments;return[Math.sin(t)*(r.rx+thickness),r.y,-Math.cos(t)*(r.rz+thickness)].map(snap) as V3;}));
 for(let r=0;r<rows.length-1;r++)for(let i=0;i<segments;i++){const n:V3=[inner[r][i][0]+inner[r][i+1][0],0,inner[r][i][2]+inner[r][i+1][2]];quad(m,[outer[r][i],outer[r][i+1],outer[r+1][i+1],outer[r+1][i]],n);quad(m,[inner[r][i],inner[r][i+1],inner[r+1][i+1],inner[r+1][i]],n.map(v=>-v) as V3);}
 for(const r of[0,rows.length-1])for(let i=0;i<segments;i++)quad(m,[outer[r][i],outer[r][i+1],inner[r][i+1],inner[r][i]],[0,r===0?-1:1,0]);
 for(const i of[0,segments])for(let r=0;r<rows.length-1;r++){const t=from+(to-from)*i/segments,n:V3=[Math.cos(t)*(i===0?-1:1),0,Math.sin(t)*(i===0?-1:1)];quad(m,[outer[r][i],outer[r+1][i],inner[r+1][i],inner[r][i]],n);}return m;
}
