import type {Asset,Project,V3} from '../core/types';
import type {AuthoredMesh} from '../core/authored-mesh';
import {Grid} from '../core/grid';import {displayMesh} from '../core/mesh';
import {makeHeadwearAsset} from './atlas-headwear';import {makeAvatarAsset} from './atlas-avatar';import {makeFigureAsset,figureProportions} from './atlas-figure';import {fittingHead} from './headwear-face';import {snap,axisPose} from './avatar-model';
import {characterPlacements,posePoint} from './character-assembly';import {makeCharacterAsset} from './atlas-character';import {mergeMeshes} from './mesh-shapes';
export const headwearScenes=['long-hair','tied-hair','children-elder','facial-hair','soft-wrap','crown','turns-seated'] as const;
export type HeadwearScene=typeof headwearScenes[number];
/** The old eyebrow cells are removed on a derivative, never hidden under a second pair. */
export function browSlot(source:Asset,hairMaterial:number,id:string):Asset{const a=structuredClone(source),removed=a.parts.filter(p=>p.name.startsWith('眉毛')),g=new Grid(a.chunks);for(const[v,m]of g.cells())if(m===hairMaterial&&removed.some(p=>v.every((n,i)=>n>=p.region.min[i]&&n<p.region.max[i])))g.set(v,0);a.chunks=g.serialize();a.parts=a.parts.filter(p=>!removed.some(r=>r.id===p.id));if(a.parts.length)a.parts[0].region=g.bounds()!;a.id=id;a.name+=' · 原眉替换槽';a.category='import';a.source={kind:'author-brow-slot',notCatalogMaster:true,sourceAssetId:source.id,removedNativeParts:removed.map(p=>p.name),originalMasterRetained:true};return a;}
/** Bind the entire retained head/accessory rigidly at its own head socket; no resampling. */
export function turnHead(source:Asset,yaw:number,id:string):Asset{const a=structuredClone(source),region=new Grid(a.chunks).bounds();a.id=id;a.name+=' · 转头 '+yaw+'°';a.category='import';a.rig??={version:1,kind:'humanoid',joints:[{id:'head',parent:null,translation:[0,0,0]}],meshJoints:Object.fromEntries((a.meshes??[]).map(m=>[m.name,'head'])),voxelJoints:region?[{joint:'head',region}]:[],sockets:Object.fromEntries(a.ports.map(p=>[p.id,'head'])),pose:{},authority:'author',originalSkeletonBound:false};a.rig.pose={head:axisPose([0,1,0],yaw*Math.PI/180)};a.source={kind:'author-head-turn',notCatalogMaster:true,sourceAssetId:source.id,sourceParameters:source.source?.parameters,yawDegrees:yaw,originalMasterRetained:true,rigidAuthorBinding:true};return a;}
/** Actual seated M031 component geometry with its old head/hair omitted and sources retained. */
export function seatedHeadFrame(p:Project):Asset{const placements=characterPlacements('seated').filter(t=>!['head','short-back'].includes(t.name)),pieces:AuthoredMesh[]=[];for(const t of placements){const id=t.catalogId.toLowerCase(),a=p.assets[id]??=makeCharacterAsset(t.catalogId,t.catalogId,id,p.styles.yunshan,t.catalogId==='CHAR-002'?{garment:1}:{});for(const b of displayMesh(a,p.materials,'far')){const m:AuthoredMesh={name:t.name,material:b.material,collision:false,positions:[],normals:[],uvs:[...b.uvs],indices:[...b.indices]};for(let k=0;k<b.positions.length;k+=3){m.positions.push(...posePoint(b.positions.slice(k,k+3) as V3,t));m.normals.push(...posePoint(b.normals.slice(k,k+3) as V3,t,true));}if(t.mirrorX===-1)for(let k=0;k<m.indices.length;k+=3)[m.indices[k+1],m.indices[k+2]]=[m.indices[k+2],m.indices[k+1]];pieces.push(m);}}
 return{id:'seated-frame',name:'保留源件的作者坐姿身体',version:1,category:'import',cellSize:.005,origin:[0,0,0],chunks:{},parts:[],openings:[],ports:[],meshes:[...new Set(pieces.map(m=>m.material))].map(id=>mergeMeshes('坐姿身体用途-'+id,pieces.filter(m=>m.material===id))),source:{kind:'author-seated-head-frame',notCatalogMaster:true,placements,sourceMasters:[...new Set(placements.map(t=>t.catalogId.toLowerCase()))],headAndHairRemoved:true,originalSkeletonBound:false,animation:false}};
}
export function headwearScene(base:Project,kind:HeadwearScene):Project{const p=structuredClone(base);p.name='M034 · '+kind+' 作者穿戴';p.assets={};p.instances={};const s=p.styles.yunshan,retain=(a:Asset)=>{p.assets[a.id]=a;return a;},add=(a:Asset,position:V3,key=a.id)=>{retain(a);const id='i-'+key;p.instances[id]={id,assetId:a.id,name:a.name,position:position.map(snap) as V3,rotation:0,parent:null};return a;},hair=(id:string,key:string,params={})=>makeHeadwearAsset(id,id,key,s,params),head=(fit:string,key:string)=>({...fittingHead(s,fit),id:key});
 if(kind==='long-hair'||kind==='tied-hair'){const ids=kind==='long-hair'?['CHAR-089','CHAR-090']:['CHAR-091','CHAR-092','CHAR-093'];for(const[i,id]of ids.entries())for(const[j,fit]of ['adult','child'].entries()){const key=id+'-'+fit,pos:V3=[(i-(ids.length-1)/2)*.55,.34,j*.70];add(head(fit,'head-'+key),pos);add(hair(id,key,{hairFit:fit}),pos);}}
 if(kind==='children-elder'){for(const[i,stage]of ['preschool','school'].entries()){const pos:V3=[(i-1)*.5,.03,0];add(makeAvatarAsset('CHAR-068','儿童头','head-'+stage,s,{headStage:stage}),pos);add(hair('CHAR-094','buns-'+stage,{headStage:stage}),pos);}add(head('elder','elder-head'),[.5,.03,0]);add(hair('CHAR-095','sparse'),[.5,.03,0]);}
 if(kind==='facial-hair'){for(const[i,id]of ['CHAR-096','CHAR-097'].entries())for(const[j,fit]of ['adult','elder'].entries()){const key=id+'-'+fit,pos:V3=[(j-.5)*.48,.25,i*.65];add(head(fit,'head-'+key),pos);add(hair(id,key,{headFit:fit}),pos);}for(const[i,fit]of ['adult','child','elder'].entries()){const original=retain(head(fit,'brow-source-'+fit)),pos:V3=[(i-1)*.40,.03,1.30];add(browSlot(original,s.hairMass,'brow-slot-'+fit),pos);add(hair('CHAR-098','brows-'+fit,{headFit:fit}),pos);}}
 if(kind==='soft-wrap')for(const[i,fit]of ['adult','child'].entries()){const pos:V3=[(i-.5)*.65,.03,0];add(head(fit,'head-'+fit),pos);add(makeAvatarAsset('CHAR-085','帽内独立短发','under-hair-'+fit,s,{hairFit:fit}),pos);add(hair('CHAR-099','wrap-'+fit,{hairFit:fit}),pos);}
 if(kind==='crown')for(const[i,pinState]of ['inserted','removed'].entries()){const pos:V3=[(i-.5)*.65,.34,0],topknot=add(hair('CHAR-093','topknot-'+pinState),pos);add(head('adult','head-'+pinState),pos);const seat=topknot.ports.find(p=>p.id==='crown-seat')!.position;add(hair('CHAR-100','crown-'+pinState,{pinState}),pos.map((v,d)=>v+seat[d]) as V3);}
 if(kind==='turns-seated'){const frame=retain(seatedHeadFrame(p)),seat=characterPlacements('seated').find(t=>t.name==='head')!.position,originalHead=retain(head('adult','turn-head-source')),long=retain(hair('CHAR-089','long-source')),body=retain(makeFigureAsset('CHAR-059','站姿身体','standing-body',s));for(const[i,yaw]of [-30,0,30].entries()){const x=(i-1)*.80;add(frame,[x,0,.9],'seat-'+i);add(turnHead(originalHead,yaw,'seated-head-'+i),[x,seat[1],seat[2]+.9]);add(turnHead(long,yaw,'seated-hair-'+i),[x,seat[1],seat[2]+.9]);add(body,[x,0,0],'stand-'+i);const q=figureProportions['CHAR-059'];add(turnHead(originalHead,yaw,'standing-head-'+i),[x,q.heightM-q.headM,0]);add(turnHead(long,yaw,'standing-hair-'+i),[x,q.heightM-q.headM,0]);}}
 p.selection={assetId:Object.values(p.instances)[0].assetId,region:null,partId:null};return p;
}
