import {Ray,Vector3} from 'three';import type {Asset,V3} from '../core/types';import {AvatarModel} from './avatar-model';import {makeFigureAsset} from './atlas-figure';import {makeAvatarAsset} from './atlas-avatar';import {fibre} from './headwear-shapes';
export function fittingHead(s:Record<string,number>,fit:string):Asset{return fit==='adult'?makeFigureAsset('CHAR-066','成人头','head',s):makeAvatarAsset(fit==='elder'?'CHAR-069':'CHAR-068','匹配头','head',s,fit==='child'?{headStage:'school'}:{});}
/** Queries the actual cranium triangles; facial features are kept as separate clearance checks. */
export function faceSurface(head:Asset,x:number,y:number){const m=head.meshes![0],ray=new Ray(new Vector3(x,y,-1),new Vector3(0,0,1)),hits:number[]=[];for(let i=0;i<m.indices.length;i+=3){const v=m.indices.slice(i,i+3).map(j=>new Vector3(...m.positions.slice(j*3,j*3+3))),p=ray.intersectTriangle(v[0],v[1],v[2],false,new Vector3());if(p)hits.push(p.z);}if(!hits.length)throw new Error('头部表面采样超出颅面');return Math.min(...hits);}
export function facialHair(m:AvatarModel,id:string,fit:string){const head=fittingHead(m.s,fit),elder=fit==='elder',brow=id==='CHAR-098';
 if(brow){const y=fit==='child'?.139:elder?.153:.151;for(const side of[-1,1]){const points:V3[]=[[side*.014,y-.001,0],[side*.035,y+.003,0],[side*.057,y-.007,0]].map(([x,y])=>[x,y,faceSurface(head,x,y)-.009]);m.mesh(fibre('立体独立眉弓-'+side,m.s.browHair,points,[.004,.005,.003]));const p=points[1];m.box('眉梳最小块-'+side,'browHair',p[0]-.005,p[1]-.0025,p[2]-.005,.010,.005,.010);}m.detail={headFit:fit,headMaster:fit==='adult'?'CHAR-066':fit==='elder'?'CHAR-069':'CHAR-068 school',pairedBrowsOnly:true,replaceNativeBrowParts:true,colorIsPalette:true};}
 else{for(const side of[-1,1]){const points:V3[]=[[side*.012,.067,0],[side*.036,.065,0],[side*.056,.054,0]].map(([x,y])=>[x,y,faceSurface(head,x,y)-.013]);m.mesh(fibre('口上独立胡髭-'+side,m.s.beardHair,points,[.005,.008,.004]));}
 const long=id==='CHAR-097',count=long?7:5;for(let k=0;k<count;k++){const x=(k-(count-1)/2)*(long?.014:.020),rootY=.025+Math.abs(x)*.8,z=faceSurface(head,x,rootY)-.020,drop=long?-.222:-.058,points:V3[]=[[x,rootY,z],[x*.92,.004,-.100],[x*.8,-.035,long?-.132:-.103],[x*.45,drop+Math.abs(x)*.55,long?-.236:-.130]];m.mesh(fibre('独立下颌须束-'+k,m.s.beardHair,points,[.008,.010,.011,.003]));m.box('须根最小梳束-'+k,'beardHair',x-.005,rootY-.005,z-.005,.010,.010,.010);}m.detail={headFit:fit,headMaster:elder?'CHAR-069':'CHAR-066',longBeard:long,mouthGapReal:true,colorIsPalette:true,headExcluded:true};}
 m.port('face-hair',[0,0,0],[0,-1,0]);
}
