import {Grid} from '../core/grid';
import {Shapes} from './shapes';import type {Asset,Command,V3} from '../core/types';import {makeLandscapeAsset,landscapeVariants} from './atlas-landscape';import {makeGroundscapeAsset} from './atlas-groundscape';
const install=(asset:Asset):Command=>({op:'installAsset',asset}),put=(assetId:string,position:V3):Command=>({op:'instance',id:assetId+'-1',assetId,position,rotation:0}),make=(catalogId:string,id:string,params={})=>({op:'produceCatalogAsset',catalogId,id,params});
const aux=(s:Record<string,number>,id:string,draw:(b:Shapes)=>void)=>{const b=new Shapes(.2,s);draw(b);return b.finish(id,'作者安装样件 · '+id,{kind:'author-landscape-fixture',originalRuntimeBound:false});};
function rim(s:Record<string,number>):Command[]{const slab=aux(s,'courtyard-slab',b=>{for(const x of[0,11])b.b(x,2.4,2,8,.2,1.2,s.structuralConcrete);});return[install(slab),put(slab.id,[0,0,0]),...['rock','soil'].flatMap((substrate,i)=>[make('ENV-086','rim-'+substrate,{substrate}),put('rim-'+substrate,[i*11,0,0])])];}
function shoulders(s:Record<string,number>):Command[]{return landscapeVariants('ENV-088').flatMap((params,i)=>{const a=makeLandscapeAsset('ENV-088','连续路肩','shoulder-'+i,s,params),d=(a.source!.detail as any).roadBed,slab=aux(s,'road-'+i,b=>b.b(0,d.min[1],2,8,.2,Number(params.roadWidth),s.pavementConcrete));return[install(a),put(a.id,[i%3*12,0,Math.floor(i/3)*16]),install(slab),put(slab.id,[i%3*12,0,Math.floor(i/3)*16])];});}
function drains(s:Record<string,number>):Command[]{return['straight','corner','collection'].flatMap((drainForm,i)=>{const a=makeLandscapeAsset('ENV-091','排水节点','drain-'+i,s,{drainForm}),size=a.source!.dimensionsM as V3,ground=aux(s,'drain-ground-'+i,b=>{b.b(-1,-.2,-1,size[0]+2,.2,size[2]+2,s.bedrock);b.b(0,0,-1,size[0],1,1,s.wall);b.b(0,0,size[2],size[0],1,1,s.wall);});return[install(a),put(a.id,[i*10,.2,0]),install(ground),put(ground.id,[i*10,.2,0])];});}
function garden(s:Record<string,number>):Command[]{const ground=aux(s,'garden-ground',b=>b.b(-1,0,-1,24,.2,8,s.bedrock)),commands:Command[]=[install(ground),put(ground.id,[0,0,0])];for(const[id,params,x]of[['ENV-096',{planterForm:'long'},0],['ENV-096',{planterForm:'tree'},8],['ENV-097',{vesselForm:'square'},14],['ENV-097',{vesselForm:'jar'},19]] as const){const a=makeLandscapeAsset(id,'独立容器','container-'+x,s,params),c=(a.source!.detail as any).soilCavityM as {min:V3;max:V3},top=Math.round(c.max[1]/.2)*.2,soil=aux(s,'soil-'+x,b=>{b.b(c.min[0],c.min[1],c.min[2],c.max[0]-c.min[0],top-c.min[1],c.max[2]-c.min[2],s.surfaceSoil);for(const[v]of new Grid(a.chunks).cells())b.g.set(v,0);});commands.push(install(a),put(a.id,[x,.2,1]),install(soil),put(soil.id,[x,.2,1]));const plant=makeGroundscapeAsset('ENV-064','复用地被母版','plant-'+x,s,{groundcover:x%2?'broadleaf':'fern'}),cx=Math.round((c.min[0]+c.max[0])/.4)*.2,cz=Math.round((c.min[2]+c.max[2])/.4)*.2;commands.push(install(plant),put(plant.id,[x+cx,.2+top,1+cz]));}return commands;}
function court(s:Record<string,number>):Command[]{return[make('ENV-094','paving'),put('paving',[0,0,0]),make('ENV-098','wood-seat',{seatForm:'wood'}),put('wood-seat',[1,.6,4]),make('ENV-098','stone-seat',{seatForm:'stone'}),put('stone-seat',[1,.6,2]),make('ENV-104','pole-lamp',{lampForm:'pole'}),put('pole-lamp',[.4,.6,6.4]),make('ENV-104','stone-lamp',{lampForm:'stone'}),put('stone-lamp',[6,.6,6])];}
export const landscapeScenarios=[['rim',rim,[{name:'院廊柱顶实际承板上方',min:[0,2.6,2] as V3,max:[8,4.32,3.2] as V3}]],['shoulders',shoulders,[]],['drains',drains,[]],['garden',garden,[{name:'花槽前方公共净空',min:[-1,.2,-1] as V3,max:[23,1.92,.8] as V3}]],['court',court,[{name:'座椅前方公共通路',min:[0,.6,0] as V3,max:[8,2.32,1.8] as V3}]]] as const;
