import type {V3} from '../core/types';
import type {AuthoredMesh} from '../core/authored-mesh';
/** Small metre-space building blocks. Inclinations remain continuous triangles. */
export type Ring={y:number;rx:number;rz:number;x?:number;z?:number;bevel?:number};
export const ringPoints=(r:Ring):V3[]=>{const b=r.bevel??Math.min(r.rx,r.rz)*.32;return[[-r.rx+b,-r.rz],[r.rx-b,-r.rz],[r.rx,-r.rz+b],[r.rx,r.rz-b],[r.rx-b,r.rz],[-r.rx+b,r.rz],[-r.rx,r.rz-b],[-r.rx,-r.rz+b]].map(([x,z])=>[x+(r.x??0),r.y,z+(r.z??0)]);};
export function emptyMesh(name:string,material:number,collision=false):AuthoredMesh{return{name,material,collision,positions:[],normals:[],uvs:[],indices:[]};}
export function triangle(m:AuthoredMesh,a:V3,b:V3,c:V3,outward:V3){let u=b.map((v,i)=>v-a[i]),v=c.map((v,i)=>v-a[i]),n:V3=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];if(n.reduce((s,v,i)=>s+v*outward[i],0)<0){[b,c]=[c,b];n=n.map(v=>-v) as V3;}const l=Math.hypot(...n);if(l<1e-12)throw new Error('退化构造面 '+m.name);n=n.map(v=>v/l||0) as V3;const k=m.positions.length/3;for(const p of[a,b,c]){m.positions.push(...p.map(v=>Math.round(v*1e9)/1e9));m.normals.push(...n);m.uvs.push(p[0],p[1]);}m.indices.push(k,k+1,k+2);}
export function quad(m:AuthoredMesh,p:V3[],outward:V3){triangle(m,p[0],p[1],p[2],outward);triangle(m,p[0],p[2],p[3],outward);}
export function loft(name:string,material:number,rings:Ring[],collision=false):AuthoredMesh{const m=emptyMesh(name,material,collision),points=rings.map(ringPoints);for(let i=0;i<rings.length-1;i++)for(let j=0;j<8;j++){const a=points[i][j],b=points[i][(j+1)%8],c=points[i+1][(j+1)%8],d=points[i+1][j],center=[((rings[i].x??0)+(rings[i+1].x??0))/2,0,((rings[i].z??0)+(rings[i+1].z??0))/2];quad(m,[a,b,c,d],[(a[0]+b[0]+c[0]+d[0])/4-center[0],0,(a[2]+b[2]+c[2]+d[2])/4-center[2]]);}for(const i of[0,rings.length-1]){const r=rings[i],c:V3=[r.x??0,r.y,r.z??0];for(let j=0;j<8;j++)triangle(m,c,points[i][j],points[i][(j+1)%8],[0,i===0?-1:1,0]);}return m;}
/** A hollow band with real inner walls, not a solid ring with a drawn hole. */
export function band(name:string,material:number,bottom:Ring,top:Ring,thickness:number,collision=false){const m=emptyMesh(name,material,collision),out=[bottom,top].map(ringPoints),inner=[bottom,top].map(r=>ringPoints({...r,rx:r.rx-thickness,rz:r.rz-thickness,bevel:Math.min(r.rx-thickness,r.rz-thickness)*.32}));for(let j=0;j<8;j++){const k=(j+1)%8,normal:V3=[(out[0][j][0]+out[0][k][0])/2-(bottom.x??0),0,(out[0][j][2]+out[0][k][2])/2-(bottom.z??0)];quad(m,[out[0][j],out[0][k],out[1][k],out[1][j]],normal);quad(m,[inner[0][j],inner[0][k],inner[1][k],inner[1][j]],normal.map(v=>-v) as V3);quad(m,[out[0][j],out[0][k],inner[0][k],inner[0][j]],[0,-1,0]);quad(m,[out[1][j],out[1][k],inner[1][k],inner[1][j]],[0,1,0]);}return m;}
export function mergeMeshes(name:string,meshes:AuthoredMesh[]):AuthoredMesh{if(!meshes.length)throw new Error('空网格合并');const m=emptyMesh(name,meshes[0].material,meshes[0].collision);for(const src of meshes){if(src.material!==m.material||src.collision!==m.collision)throw new Error('跨用途网格合并');const offset=m.positions.length/3;m.positions.push(...src.positions);m.normals.push(...src.normals);m.uvs.push(...src.uvs);m.indices.push(...src.indices.map(i=>i+offset));}return m;}
