import type {Assembly,Project,V3} from '../core/types';
import {ArchitectureBuilder} from './architecture-near-assembly';
import {CivicComponent,type Opening} from './civic-components';
import {civicAsset} from './civic-landmarks';
import {modernFacade,modernPlate,modernPost,modernRail,modernRoof,metalOpticColumn,modernStairs as stairs} from './metropolis-components';
export const metropolisTowerIds=['BUILT-220','BUILT-221','BUILT-222','BUILT-223'];
export const modernStairHole:Opening={min:[-2.8,-4.2],max:[2.8,4.2]};
function guard(b:ArchitectureBuilder,w:number,d:number,y:number,at:[number,number]=[0,0]){for(const z of[-d/2,d/2])modernRail(b,w,[at[0]-w/2,y,at[1]+z]);for(const x of[-w/2,w/2])modernRail(b,d,[at[0]+x,y,at[1]-d/2],3);}
function wellGuard(b:ArchitectureBuilder,hole:Opening,y:number,at:[number,number]=[0,0]){for(const x of[hole.min[0],hole.max[0]])modernRail(b,hole.max[1]-hole.min[1],[at[0]+x,y,at[1]+hole.min[1]],3);modernRail(b,hole.max[0]-hole.min[0],[at[0]+hole.min[0],y,at[1]+hole.max[1]]);}
function offsetNew(b:ArchitectureBuilder,start:number,at:V3){for(const i of b.instances.slice(start))i.position=i.position.map((n,d)=>n+at[d])as V3;}
/** The same crown geometry seats on an actual tower roof in both standalone and main-tower assemblies. */
export function metalCrown(b:ArchitectureBuilder,at:V3){const start=b.instances.length;
 modernPlate(b,20,18,[0,0,0],[modernStairHole]);modernFacade(b,20,18,0,4.2,false);modernPlate(b,20,18,[0,4.2,0],[modernStairHole]);modernFacade(b,18,16,4.2,4.2,false,true);stairs(b,4.2,[-2.6,0,-4.2]);wellGuard(b,modernStairHole,4.2);
 modernRoof(b,24,22,[0,3,0],1,'hip',[20,18]);modernRoof(b,18,16,[0,8.4,0],2.5);
 for(const x of[-9,9])for(const z of[-8,8])modernPost(b,8.4,.55,[x,0,z]);
 const spire=civicAsset(b,'modern-crown-spire',id=>{const c=new CivicComponent(b.p,id,'塔冠金属脊座与零发光光学饰面',['BUILT-246','BUILT-247'],{height:13.2,powerBound:false});c.box('实接脊座','metal',-.45,10.48,-.4,.9,.42,.8);c.box('中式冠顶金属立饰','bronze',-.16,10.9,-.16,.32,2.3,.32);c.box('独立未绑定光学饰条','architectureOptic',-.11,11.1,-.175,.22,1.6,.015);c.pin('冠顶最小铜销','bronze',[0,13.18,0]);return c.finish();});b.place(spire,[0,0,0],0,'roof');offsetNew(b,start,at);return{base:at,topY:at[1]+13.2,upperWalkY:at[1]+4.2,instanceIds:b.instances.slice(start).map(i=>i.id)};}
function standaloneCrown(p:Project,id:string,name:string){const b=new ArchitectureBuilder(p,id);for(const y of[0,4.2]){modernPlate(b,20,18,[0,y,0],[modernStairHole]);modernFacade(b,20,18,y,4.2,y===0);stairs(b,4.2,[-2.6,y,-4.2]);}const crown=metalCrown(b,[0,8.4,0]);return b.finish('BUILT-220',name,{parameters:{},crown,authorSupportTower:{floors:2,pitch:4.2,footprint:[20,18]},scope:'Actual two-storey support tower and metal/ceramic Chinese crown, all metre-space authored alternatives. No original floor program, world placement or permission binding.'});}
function podium(p:Project,id:string,name:string){const b=new ArchitectureBuilder(p,id),well:Opening={min:[-18,-4.2],max:[-12.4,4.2]},atrium:Opening={min:[-6,-4],max:[6,4]},floors:any[]=[];
 for(let level=0;level<3;level++){const y=level*4.2,w=level===2?40:48,d=level===2?32:40;modernPlate(b,48,40,[0,y,0],level?[well,atrium]:[well]);modernFacade(b,w,d,y,4.2,level!==1);stairs(b,4.2,[-17.8,y,-4.2]);wellGuard(b,well,y);if(level)guard(b,12,8,y);if(level===2)guard(b,48,40,y);floors.push({level,walkY:y,facadeFootprint:[w,d],program:'author-public-lobby/gallery',permissions:'unbound'});}
 modernPlate(b,40,32,[0,12.6,0],[well,atrium]);guard(b,40,32,12.6);guard(b,12,8,12.6);wellGuard(b,well,12.6);
 for(const x of[-20,20])for(const z of[-16,16])metalOpticColumn(b,8.2,[x,.1,z]);
 const can=civicAsset(b,'podium-entry-canopy',id=>{const c=new CivicComponent(p,id,'公共入口薄金属雨棚',['BUILT-236'],{clearWidth:8});c.box('连续雨棚承板','architecturalCladding',-5,3.15,-4,10,.20,4);for(const x of[-4.5,4.5])c.box('入口钢柱','facadeFrame',x-.12,0,-3.3,.24,3.15,.24);for(const z of[-3.9,-.2])c.box('雨棚横梁','metal',-5,3,z,10,.15,.16);c.pin('雨棚柱顶销','bronze',[-4.5,3.12,-3.32]);return c.finish();});b.place(can,[0,0,-20],0,'canopy');modernPlate(b,14,6,[0,0,-23]);
 return b.finish('BUILT-221',name,{parameters:{},floors,roofWalkY:12.6,atrium,stairwell:well,sourceProgramsAvailable:false,scope:'Author three-level public podium with open atrium, real doors and stairs. Program labels are proposed uses; no source commerce/permissions/runtime connection.'});}
function mainTower(p:Project,id:string,name:string){const b=new ArchitectureBuilder(p,id),levels:any[]=[],pitch=4.2;
 for(let level=0;level<54;level++){const w=level<3?48:level<36?36:level<48?28:20,d=level<3?40:level<36?30:level<48?24:18,y=level*pitch;const prior=level===3?[48,40]:level===36?[36,30]:level===48?[28,24]:[w,d];modernPlate(b,prior[0],prior[1],[0,y,0],[modernStairHole]);if(prior[0]!==w)guard(b,prior[0],prior[1],y);modernFacade(b,w,d,y,pitch,level===0||prior[0]!==w);stairs(b,pitch,[-2.6,y,-4.2]);if(level===0||level===3||level===36||level===48)wellGuard(b,modernStairHole,y);levels.push({level:level+1,walkY:y,footprint:[w,d],program:level<3?'author-public-base':'unassigned',permissions:'unbound'});}
 for(const [w,d,start,end]of[[36,30,12.6,151.2],[28,24,151.2,201.6],[20,18,201.6,226.8]])for(const x of[-w/2,w/2])for(const z of[-d/2-.15,d/2+.15])metalOpticColumn(b,end-start,[x,start,z]);
 const crown=metalCrown(b,[0,226.8,0]);b.dependencies.add('BUILT-220');return b.finish('BUILT-222',name,{parameters:{},levels,crown,authorDimensions:{totalHeight:240,occupiedFloors:54,floorPitch:pitch,base:[48,40],upper:[20,18]},separateFromHistoricTianshu:true,scope:'New authored glass/metal main tower; 54 equal-pitch occupied floors plus crown walk deck. No historic wooden tower scaled or relabelled; original CBD world plan and identities unavailable.'});}
function secondaryTower(b:ArchitectureBuilder,key:string,at:V3,tiers:{floors:number;w:number;d:number;dx:number;dz:number}[],cap:'flat'|'hip'|'gable'){
 const start=b.instances.length,levels:any[]=[];let level=0,previous:typeof tiers[number]|undefined;for(const tier of tiers)for(let j=0;j<tier.floors;j++,level++){const y=level*4.2,offset:[number,number]=[tier.dx,tier.dz],well:Opening={min:[modernStairHole.min[0]-tier.dx,modernStairHole.min[1]-tier.dz],max:[modernStairHole.max[0]-tier.dx,modernStairHole.max[1]-tier.dz]};if(j===0&&previous){const oldWell:Opening={min:[-2.8-previous.dx,-4.2-previous.dz],max:[2.8-previous.dx,4.2-previous.dz]};modernPlate(b,previous.w,previous.d,[previous.dx,y,previous.dz],[oldWell]);guard(b,previous.w,previous.d,y,[previous.dx,previous.dz]);}else modernPlate(b,tier.w,tier.d,[tier.dx,y,tier.dz],[well]);modernFacade(b,tier.w,tier.d,y,4.2,level===0||j===0,false,offset);stairs(b,4.2,[-2.6,y,-4.2]);levels.push({level:level+1,walkY:y,footprint:[tier.w,tier.d],offset});previous=tier;}
 const last=tiers.at(-1)!,top=level*4.2,well:Opening={min:[-2.8-last.dx,-4.2-last.dz],max:[2.8-last.dx,4.2-last.dz]};modernPlate(b,last.w,last.d,[last.dx,top,last.dz],[well]);guard(b,last.w,last.d,top,[last.dx,last.dz]);wellGuard(b,modernStairHole,top);
 if(cap==='flat'){const equipment=civicAsset(b,'secondary-roof-mechanical-'+key,id=>{const c=new CivicComponent(b.p,id,'独立屋顶检修设备实体壳',['BUILT-237'],{key});c.box('检修设备实体壳','architecturalCladding',-8,0,3,4,3.4,3);c.box('真实屋面风道底','metal',-7.8,.1,3.2,3.6,.1,2.6);for(const z of[3.2,5.5])c.box('设备侧通风百叶','sunshadeMetal',-7.8,.4,z,3.6,.10,.1);c.pin('设备壳固定销','bronze',[-7.9,3.38,3.1]);return c.finish();});b.place(equipment,[last.dx,top,last.dz],0,'fixture');}
 else{for(const x of[-last.w/2+.4,last.w/2-.4])for(const z of[-last.d/2+.4,last.d/2-.4])modernPost(b,3.6,.4,[last.dx+x,top,last.dz+z]);modernRoof(b,last.w-.8,last.d-.8,[last.dx,top+3.6,last.dz],cap==='hip'?2.4:1.8,cap);}
 offsetNew(b,start,at);return{key,position:at,tiers,levels,roofWalkY:at[1]+top,cap,instanceIds:b.instances.slice(start).map(i=>i.id)};
}
function secondaryGroup(p:Project,id:string,name:string){const b=new ArchitectureBuilder(p,id),sites:[string,V3,{floors:number;w:number;d:number;dx:number;dz:number}[],'flat'|'hip'|'gable'][]=[['low-wide',[-26,0,-27],[{floors:12,w:28,d:24,dx:0,dz:0},{floors:6,w:22,d:20,dx:-2,dz:1}],'flat'],['slender',[26,0,-27],[{floors:24,w:20,d:22,dx:0,dz:0},{floors:4,w:16,d:18,dx:0,dz:0}],'hip'],['stepped',[-26,0,27],[{floors:8,w:28,d:26,dx:0,dz:0},{floors:8,w:24,d:22,dx:2,dz:-1},{floors:6,w:18,d:18,dx:4,dz:-2}],'gable'],['tall-shoulder',[26,0,27],[{floors:14,w:24,d:24,dx:0,dz:0},{floors:10,w:20,d:18,dx:-1,dz:2}],'flat']];
 const holes=sites.map(([,at,tiers])=>({min:[at[0]-tiers[0].w/2,at[2]-tiers[0].d/2],max:[at[0]+tiers[0].w/2,at[2]+tiers[0].d/2]}as Opening));modernPlate(b,112,116,[0,0,0],holes);const towers=sites.map(([key,at,tiers,cap])=>secondaryTower(b,key,at,tiers,cap));return b.finish('BUILT-223',name,{parameters:{},towers,authorPlaza:[112,116],minimumCentralStreetWidth:24,usesActualMetreComponents:true,scope:'Four separately dimensioned tower profiles with fixed 4.2m floors, real setbacks and three crown constructions. No scaled copy of the main tower; street spacing is an explicit author alternative, not original city density.'});}
export function makeMetropolisTower(p:Project,catalogId:string,id:string,name:string,params:Record<string,string|number>={}):Assembly{if(catalogId==='BUILT-220')return standaloneCrown(p,id,name);if(catalogId==='BUILT-221')return podium(p,id,name);if(catalogId==='BUILT-222')return mainTower(p,id,name);if(catalogId==='BUILT-223')return secondaryGroup(p,id,name);throw new Error('Unknown modern tower template');}
