import type {Asset,Project,V3} from '../core/types';
import {ArchitectureBuilder} from './architecture-near-assembly';
import {architectureRail} from './architecture-components';
import {CivicComponent,civicRoof,civicPlate,civicStair,type Opening} from './civic-components';
import {civicAsset} from './civic-landmarks';

/** Distinct metal construction, never recolour the existing wooden tower template. */
export function modernWall(p:Project,id:string,w:number,h=4.2,door=false,open=false):Asset{
 const c=new CivicComponent(p,id,'金属框、密封环与独立幕墙玻璃',['BUILT-218'],{w,h,door,open,construction:'metal-frame-curtainwall'});
 const region=(left:number,right:number)=>{const n=Math.max(1,Math.ceil((right-left)/3)),bay=(right-left)/n;for(let j=0;j<n;j++){const x=left+j*bay;c.box('实际金属立梃','facadeFrame',x,0,-.12,.14,h,.38);c.box('金属窗下实裙','architecturalCladding',x,0,0,bay,open?1.1:.65,.18);if(open)continue;const z=.1,x0=x+.16,ww=bay-.32,y0=.7,hh=h-1.15;c.box('上部金属覆板','architecturalCladding',x,h-.4,0,bay,.4,.18);for(const xx of[x0,x0+ww-.035])c.box('幕墙侧封环','facadeSeal',xx,y0,z,.035,hh,.035);for(const yy of[y0,y0+hh-.035])c.box('幕墙上下封环','facadeSeal',x0,yy,z,ww,.035,.035);c.box('独立幕墙玻璃','glass',x0+.035,y0+.035,z+.008,ww-.07,hh-.07,.016);c.box('窗间横梃','facadeFrame',x+.14,h*.54,.06,bay-.14,.08,.14);}};
 if(door){region(-w/2,-1.8);region(1.8,w/2);c.box('实开门洞过梁','facadeFrame',-1.8,3,-.12,3.6,.2,.38);if(h>3.2)c.box('入口上覆板','architecturalCladding',-1.8,3.2,0,3.6,h-3.2,.18);c.ports.push({id:'door',kind:'modern-walk',position:[0,0,0],normal:[0,0,-1],size:[3.6,3,0],pitch:.02});}else region(-w/2,w/2);
 c.box('端部立梃','facadeFrame',w/2-.14,0,-.12,.14,h,.38);c.box('通长结构顶梁','metal',-w/2,h-.22,-.12,w,.22,.38);for(const x of[-w/2+.04,w/2-.06])c.pin('幕墙框角最小铜销','bronze',[x,h-.1,-.13]);return c.finish();
}
export function modernFacade(b:ArchitectureBuilder,w:number,d:number,y:number,h=4.2,door=true,open=false,center:[number,number]=[0,0]){for(const[width,x,z,rot]of[[w,0,-d/2,0],[w,0,d/2,2],[d,-w/2,0,3],[d,w/2,0,1]])b.place(civicAsset(b,'modern-wall-'+width+'-'+h+'-'+(door&&rot===0)+'-'+open,id=>modernWall(b.p,id,width,h,door&&rot===0,open)),[center[0]+x,y,center[1]+z],rot,'facade');}
export function modernPost(b:ArchitectureBuilder,height:number,width:number,pos:V3){return b.place(civicAsset(b,'metal-column-'+height+'-'+width,id=>{const c=new CivicComponent(b.p,id,'混凝土足与金属柱',['BUILT-059','BUILT-089'],{height,width});c.box('真实混凝土柱足','structuralConcrete',-width*.7,0,-width*.7,width*1.4,.3,width*1.4);c.box('钢柱','metalBright',-width/2,.3,-width/2,width,height-.3,width);for(const y of[.3,height-.18]){c.box('钢柱承箍','metal',-width*.55,y,-width*.55,width*1.1,.15,width*1.1);c.pin('柱箍最小铜销','bronze',[0,y+.06,-width*.55-.01]);}return c.finish();}),pos,0,'column');}
export function modernRoof(b:ArchitectureBuilder,w:number,d:number,pos:V3,rise=2,form:'hip'|'gable'='hip',inner?:[number,number]){return b.place(civicAsset(b,'modern-roof-'+w+'-'+d+'-'+rise+'-'+form+'-'+(inner?.join('-')??'closed'),id=>{const a=civicRoof(b.p,id,w,d,rise,form,inner),map=new Map([[b.p.styles.yunshan.wood,b.p.styles.yunshan.architecturalCladding],[b.p.styles.yunshan.woodEdge,b.p.styles.yunshan.metalBright]]);a.name='连续瓦檐与金属承板、钢梁';for(const m of a.meshes??[])m.material=map.get(m.material)??m.material;for(const r of a.source!.componentIndexRanges as any[]){r.material=map.get(r.material)??r.material;r.name=r.name.replaceAll('木','金属').replaceAll('望板','承板');}a.source!.construction='Ceramic tile, membrane, metal deck and steel beams; explicit derivative, no change to wooden source assets';return a;}),pos,0,'roof');}
export function modernRail(b:ArchitectureBuilder,w:number,pos:V3,rotation=0){return b.place(civicAsset(b,'modern-rail-'+w,id=>{const a=architectureRail(b.p,id,w),map=new Map([[b.p.styles.yunshan.wood,b.p.styles.yunshan.facadeFrame],[b.p.styles.yunshan.woodEdge,b.p.styles.yunshan.metalBright]]);for(const m of a.meshes??[])m.material=map.get(m.material)??m.material;for(const r of a.source!.componentIndexRanges as any[])r.material=map.get(r.material)??r.material;a.name='石脚与连续金属护栏';a.source!.construction='Metal rail derived from rail layout; existing wooden master unchanged';return a;}),pos,rotation,'guard');}
export function modernPlate(b:ArchitectureBuilder,w:number,d:number,pos:V3,holes:Opening[]=[],depth=.4){return b.place(civicAsset(b,'modern-plate-'+w+'-'+d+'-'+depth+'-'+JSON.stringify(holes),id=>civicPlate(b.p,id,w,d,holes,depth)),pos,0,'floor');}
export function metalOpticColumn(b:ArchitectureBuilder,height:number,pos:V3){return b.place(civicAsset(b,'architectural-optic-column-'+height,id=>{const c=new CivicComponent(b.p,id,'独立建筑光学槽与承框',['BUILT-117'],{height,powerBound:false});c.box('光学槽金属背框','facadeFrame',-.16,0,-.1,.32,height,.2);c.box('未绑定建筑光学面','architectureOptic',-.10,.08,-.115,.20,height-.16,.015);c.pin('框端铜销','bronze',[.12,.04,-.12]);return c.finish();}),pos,0,'fixture');}

export function modernStairs(b:ArchitectureBuilder,h:number,pos:V3){return b.place(civicAsset(b,'modern-stair-'+h,id=>{const a=civicStair(b.p,id,h),old=b.p.styles.yunshan.woodEdge,replacement=b.p.styles.yunshan.facadeFrame;for(const m of a.meshes??[])if(m.material===old)m.material=replacement;for(const r of a.source!.componentIndexRanges as any[])if(r.material===old)r.material=replacement;a.source!.construction='Concrete flights and metal handrails';return a;}),pos,0,'stair');}
