import type {Assembly,Project,V3} from '../core/types';
import {ArchitectureBuilder} from './architecture-near-assembly';
import {CivicComponent} from './civic-components';
import {emptyMesh,quad as meshQuad,triangle} from './mesh-shapes';
import {civicAsset} from './civic-landmarks';
export const metropolisAviationIds=['BUILT-169','BUILT-181','BUILT-184','BUILT-185'];

/** Exactly three main proxy boxes. It deliberately remains distinct from a detailed aircraft. */
export function publicVehicleProxy(b:ArchitectureBuilder,mode:'road'|'flight',position:V3){
 const w=mode==='flight'?14:2.5,l=mode==='flight'?17:5.5,h=mode==='flight'?.8:1.5;
 const asset=civicAsset(b,'public-three-box-'+mode,id=>{const c=new CivicComponent(b.p,id,'公共载具体 body/head/trim 三盒代理',['BUILT-169'],{mode,bodyM:[w,h,l],headAndTrimPlacement:'author',completeVehicle:false});
 c.box('body · 原用途尺寸盒','metalTeal',-w/2,0,-l/2,w,h,l);c.box('head · 独立玻璃头盒','glass',mode==='flight'?-1.5:-.95,h,-l*.35,mode==='flight'?3:1.9,mode==='flight'?1.8:.8,mode==='flight'?5:2.2);c.box('trim · 未绑定光学饰面盒','vehicleInactiveOptic',-w*.42,h*.62,-l/2-.025,w*.84,.12,.025);c.pin('本体最小接销','bronze',[w/2-.04,h-.02,l/2-.04]);return c.finish();});return b.place(asset,position,0,'vehicle-proxy');
}
function proxy(p:Project,id:string,name:string){const b=new ArchitectureBuilder(p,id),instance=publicVehicleProxy(b,'road',[0,0,0]);return b.finish('BUILT-169',name,{parameters:{},instance,mode:'road',sourceParts:['body','head','trim'],authorHeadAndTrimPlacement:true,scope:'Source road body envelope with exactly three display boxes and a native detail pin. No wheels, working doors, driving cockpit, fleet identity or Simulation state; this remains a geometry proxy.'});}
function pad(p:Project,id:string,name:string){const b=new ArchitectureBuilder(p,id),a=civicAsset(b,'seven-metre-rental-pad',id=>{const c=new CivicComponent(p,id,'七米机位、三条金色实涂线与连续街接坡',['BUILT-181','BUILT-183'],{sourcePadM:[7,.2,7],streetEntry:'author',identityBound:false});
 c.box('站台混凝土承体','structuralConcrete',-3.5,0,-3.5,7,.15,7);c.box('石铺面','stone',-3.5,.15,-3.5,7,.05,7);for(const z of[-2,0,2])c.box('金色实际涂线','airfieldYellow',-2.6,.2,z-.09,5.2,.004,.18);
 c.slab('连续缓坡','pavementConcrete',[[-.9,.2,-3.5],[.9,.2,-3.5],[.9,0,-7.5],[-.9,0,-7.5]],.15);
 c.box('空白机位牌立杆','metal',3,.2,2.8,.2,3,.2);c.box('空白实体机位牌','metal',2.2,2.4,2.75,1.8,.8,.10);c.pin('牌杆连接销','bronze',[3.08,2.44,2.73]);return c.finish();});b.place(a,[0,0,0],0,'pad');return b.finish('BUILT-181',name,{parameters:{},sourcePadM:[7,.2,7],authorEntry:[0,0,-7.5],authorPadWalkY:.2,goldStrips:3,scope:'A real seven-metre pad with three paint strips, blank sign and author street ramp. Original pad ID, terrain flattening/exclusion, rental and boarding controller are unavailable.'});}

function aircraftCabin(b:ArchitectureBuilder,kind:'quad'|'service'){
 const service=kind==='service',w=service?2:1.6,l=service?7.2:2.8;
 const body=civicAsset(b,'aircraft-hollow-body-'+kind,id=>{const c=new CivicComponent(b.p,id,'连续倒角机身与真实足舱',['BUILT-'+(service?'185':'184')],{bodyM:[w,.8,l],bodyBottomY:.8,walkY:.9,sideDoor:{x:-w/2,z:[-.55,.55]},authorInterior:true});
 const x=w/2,z=l/2,poly:V3[]=[[-x+.18,.9,-z],[x-.18,.9,-z],[x,.9,-z+.28],[x,.9,z-.28],[x-.18,.9,z],[-x+.18,.9,z],[-x,.9,z-.28],[-x,.9,-z+.28]];c.slab('闭合薄壁机腹与实际足舱底','aircraftSkin',poly,.1);
 c.box('右侧机身裙壳','aircraftSkin',x-.12,.9,-z+.28,.12,.7,l-.56);for(const zz of[-z+.28,.55])c.box('左门两侧机身裙壳','aircraftSkin',-x,.9,zz,.12,.7,z-.83);
 for(const side of[-1,1]){const front=side===-1?-z:z-.28;c.slab('连续倒角首尾封壳','aircraftSkin',side===-1?[[-x+.18,1.6,-z],[x-.18,1.6,-z],[x,1.6,-z+.28],[-x,1.6,-z+.28]]:[[-x,1.6,z-.28],[x,1.6,z-.28],[x-.18,1.6,z],[-x+.18,1.6,z]],.7);}
 if(service){c.box('机尾封闭甲板','aircraftSkin',-x+.12,1.48,1.2,w-.24,.12,z-1.48);c.box('前鼻封闭甲板','aircraftSkin',-x+.12,1.48,-z+.28,w-.24,.12,z-1.58);}
 for(const xx of[-x+.16,x-.18])c.pin('蒙皮最小锁销','bronze',[xx,.86,-z+.08]);c.ports.push({id:'entry',kind:'author-aircraft-entry',position:[-x,.9,0],normal:[-1,0,0],size:[0,1.82,1.1],pitch:.02});return c.finish();});const bodyInstance=b.place(body,[0,0,0],0,'aircraft-body');
 const glazing=civicAsset(b,'aircraft-open-cabin-'+kind,id=>{const c=new CivicComponent(b.p,id,'分离舱窗、真实侧门与独立密封',['BUILT-189','BUILT-190'],{doorOpen:true,hingeBound:false,sidePair:true,roofM:[1.8,.2,2.4]});
 for(const side of[-1,1]){const xx=side*.85;for(const z of[-1.05,1])c.box('独立窗角金属柱','metal',xx-.05,1.6,z,.1,1.2,.05);c.box('舱侧顶梁','aircraftSkin',xx-.05,2.72,-1.05,.1,.08,2.1);const spans=side<0?[[-1.0,-.55],[.55,1.0]]:[[-1,1]];for(const [lo,hi]of spans){for(const y of[1.6,2.68])c.box('上下窗封','vehicleSeal',xx-.025,y,lo,.05,.04,hi-lo);for(const z of[lo,hi-.04])c.box('独立竖窗封','vehicleSeal',xx-.025,1.6,z,.05,1.1,.04);c.box('独立舱侧玻璃','glass',xx-.012,1.64,lo+.04,.024,1.04,hi-lo-.08);}}
 for(const z of[-1.04,1.025]){c.box('端窗下框','aircraftSkin',-.8,1.6,z,1.6,.1,.025);c.box('前后独立薄玻璃','glass',-.8,1.7,z,1.6,1,.025);}c.box('顶盖实承框','metal',-.9,2.8,-1.2,1.8,.08,2.4);c.box('连续舱顶蒙皮','aircraftSkin',-.9,2.88,-1.2,1.8,.12,2.4);for(const x of[-.86,.84])c.pin('顶盖铜锁销','bronze',[x,2.98,1.1]);return c.finish();});b.place(glazing,[0,0,0],0,'glazing');
 // Low static controls and a single seat preserve a real left-to-centre boarding space.
 const interior=civicAsset(b,'aircraft-interior-'+kind,id=>{const c=new CivicComponent(b.p,id,'低操纵台与单座静态舱内',['BUILT-195'],{eye:[.1,2.1,.65],controlsBound:false});c.box('实接座脚','metal',-.12,.9,.48,.32,.36,.35);c.box('座面','fabric',-.30,1.26,.4,.70,.12,.48);c.box('座背','fabric',-.30,1.38,.78,.70,.75,.10);c.box('低操纵台支脚','metal',.26,.9,-.86,.12,.32,.2);c.slab('连续倾斜操纵台','aircraftSkin',[[-.45,1.28,-.96],[.55,1.28,-.96],[.55,1.17,-.6],[-.45,1.17,-.6]],.05);c.box('未绑定黑色显示底','screen',-.2,1.276,-.9,.5,.012,.12);c.pin('操纵台安装销','bronze',[.28,1.20,-.85]);return c.finish();});b.place(interior,[0,0,0],0,'cockpit');return{bodyInstance,bodyM:[w,.8,l],floorY:.9,sideDoorX:-w/2,seatEye:[.1,2.1,.65],authorInterior:true};
}
function quad(p:Project,id:string,name:string){const b=new ArchitectureBuilder(p,id),cabin=aircraftCabin(b,'quad'),foot=b.original('BUILT-188'),feet:string[]=[],arms:any[]=[];
 for(const x of[-.7,.5])for(const z of[-1.1,.9])feet.push(b.place(foot,[x,0,z],0,'landing-leg'));
 for(const sx of[-1,1])for(const sz of[-1,1]){const from:V3=[sx*.72,1.48,sz*1.0],to:V3=[sx*(.72+1.8*Math.cos(Math.PI/6)),1.48,sz*1.9],asset=civicAsset(b,'quad-continuous-arm-'+sx+'-'+sz,id=>{const c=new CivicComponent(p,id,'连续斜置支臂、静态轮毂与两米旋翼',['BUILT-186','BUILT-187'],{from,to,armLength:1.8,bladeSpan:2,rotorSweepRadius:1,staticOnly:true});c.beam('真实一米八连续支臂','metal',from,to,.2);c.tube('闭合电机轮毂','metalBright',[[to[0],1.4,to[2]],[to[0],1.84,to[2]]],.13);c.slab('连续收尖金色旋翼','rotorBlade',[[to[0]-.1,1.92,to[2]-1],[to[0]+.1,1.92,to[2]-.85],[to[0]+.1,1.92,to[2]+1],[to[0]-.1,1.92,to[2]+.85]],.08);c.pin('轮毂最小锁销','bronze',[to[0],1.90,to[2]]);return c.finish();});const instance=b.place(asset,[0,0,0],0,'rotor');arms.push({instance,from,to,hub:[to[0],1.84,to[2]],sweepRadius:1});}
 return b.finish('BUILT-184',name,{parameters:{},cabin,feet,arms,staticConfiguration:'parked-open-left-door',sourceBodyM:[1.6,.8,2.8],sourceCounts:{arms:4,rotors:4,feet:4},scope:'Continuous body, tapered rotor surfaces and diagonally placed 1.8m arms; original four 0.8m native leg masters preserved. Authored door/seat placement; finite parked clearances only, no original aircraft ID, rental/controller, propulsion or airborne dynamics.'});
}
function continuousWing(b:ArchitectureBuilder,w:number,d:number,key:string,pos:V3){return b.place(civicAsset(b,'continuous-aircraft-wing-'+key,id=>{const c=new CivicComponent(b.p,id,'连续后掠翼面与独立承梁',['BUILT-'+(key==='main'?'191':'193')],{span:w,depth:d,thickness:.2});const poly:V3[]=[[-w/2,.2,-d*.12],[-w*.13,.2,-d/2],[w*.13,.2,-d/2],[w/2,.2,-d*.12],[w/2,.2,d*.27],[w*.13,.2,d/2],[-w*.13,.2,d/2],[-w/2,.2,d*.27]];c.slab('连续闭合航空蒙皮','aircraftSkin',poly,.14);c.box('真实翼根承梁','metal',-.3,0,-.3,.6,.08,.6);for(const x of[-w/2+.05,w/2-.09]){c.box('独立翼尖未绑定光学面','vehicleInactiveOptic',x,.20,-d*.07,.04,.015,d*.22);c.pin('翼尖最小蒙皮销','bronze',[x,.18,0]);}return c.finish();}),pos,0,'wing');}
function service(p:Project,id:string,name:string){const b=new ArchitectureBuilder(p,id),cabin=aircraftCabin(b,'service'),feet:string[]=[],foot=b.original('BUILT-188');for(const x of[-.84,.64])for(const z of[-2.8,2.4])feet.push(b.place(foot,[x,0,z],0,'landing-leg'));
 const mainWing=continuousWing(b,8.4,2.4,'main',[0,.60,.15]),tailWing=continuousWing(b,4,1,'tail',[0,1.60,2.85]);
 const fin=civicAsset(b,'continuous-service-fin',id=>{const c=new CivicComponent(p,id,'连续后掠垂尾与实体翼根',['BUILT-192'],{envelopeM:[.4,1.8,2]});c.box('真实垂尾根座','metal',-.2,0,-1,.4,.16,2);c.beam('连续后掠垂尾主脊','metal', [0,.1,-.8],[0,1.7,.2],.1);const mesh=emptyMesh('连续实体后掠垂尾',c.role('aircraftSkin')),ends=[-.07,.07].map(x=>[[x,0,-1],[x,0,1],[x,1.8,.35]]as V3[]);triangle(mesh,...ends[0]as[V3,V3,V3],[-1,0,0]);triangle(mesh,...ends[1]as[V3,V3,V3],[1,0,0]);const cy=.6,cz=.35/3;for(let j=0;j<3;j++){const k=(j+1)%3;meshQuad(mesh,[ends[0][j],ends[0][k],ends[1][k],ends[1][j]],[0,(ends[0][j][1]+ends[0][k][1])/2-cy,(ends[0][j][2]+ends[0][k][2])/2-cz]);}c.mesh(mesh);c.pin('尾根最小连接销','bronze',[0,.14,.8]);return c.finish();});b.place(fin,[0,1.6,2.55],0,'tail');
 const power=civicAsset(b,'service-power-box-pair',id=>{const c=new CivicComponent(p,id,'两侧一米六真通风动力盒',['BUILT-194'],{sideLength:1.6,powerBound:false,authorPosition:true});for(const x of[-1.4,1.0]){for(const y of[0,.54])c.box('动力盒上下壳','metal',x,y,0,.4,.06,1.6);for(const xx of[x,x+.34])c.box('动力盒侧壳','metal',xx,.06,0,.06,.48,1.6);c.box('箱体实接侧托','metal',x<0?x+.4:x-.2,.12,.35,.2,.12,.9);c.pin('盒体最小锁销','bronze',[x+.1,.58,.1]);}return c.finish();});b.place(power,[0,1.0,1.45],0,'power-box');
 return b.finish('BUILT-185',name,{parameters:{},cabin,feet,mainWing,tailWing,sourceBodyM:[2,.8,7.2],sourceMainWingSpan:8.4,staticConfiguration:'parked-open-left-door',scope:'Separate authored service aircraft with continuous fuselage, swept main/tail wings, fin and open power ducts. Four source leg masters form a static service stand; no invented retracting wheels, airborne flight, aircraft identity or driving binding.'});}
export function makeMetropolisAviation(p:Project,catalogId:string,id:string,name:string):Assembly{if(catalogId==='BUILT-169')return proxy(p,id,name);if(catalogId==='BUILT-181')return pad(p,id,name);if(catalogId==='BUILT-184')return quad(p,id,name);if(catalogId==='BUILT-185')return service(p,id,name);throw new Error('Unknown metropolis aviation template');}
