import type{Asset,V3}from'../core/types';
import {Grid}from'../core/grid';
import {displayMesh}from'../core/mesh';
import {emptyMesh,ellipsePoints,roundBand}from'./mesh-shapes';
import {orientedQuad}from'./attire-shapes';
import {makeAttireAsset}from'./atlas-attire';
import {makeHeldAsset}from'./atlas-held';
import {garmentMount}from'./garment-body';
import {garmentFrame}from'./garment-shapes';
import {accessoryInstaller,annularPoints,clipAxis,clothesInstance,fitSource,preserveShoulderPose,triangles,type ProfessionBase,type ProfessionContact}from'./profession-fit';

function childBag(b:ProfessionBase,source:Asset,clothes:Asset){const a=structuredClone(source),points:V3[]=[];for(const t of triangles(b.p,[clothes])){let poly=t.points;for(const[axis,value,above]of[[0,.086,true],[0,.114,false],[2,-.12,true],[2,.13,false]]as[number,number,boolean][])poly=clipAxis(poly,axis,value,above);points.push(...poly);}const contact=points.reduce((a,b)=>a[1]>b[1]?a:b),h=contact[1]+.003-.150,old=a.meshes!.find(m=>m.name==='挎包实际长肩带')!,mesh=emptyMesh(old.name,old.material),pts:V3[]=[[-.19,.24,0],[-.19,.40,-.16],[-.30,.60,-.20],[-.30,h,-.12],[-.30,h,.13],[-.10,.55,.18],[.19,.40,.14],[.19,.24,0]],frames=pts.map(([x,y,z],i)=>{const A=pts[Math.max(0,i-1)],B=pts[Math.min(pts.length-1,i+1)],dy=B[1]-A[1],dz=B[2]-A[2],length=Math.hypot(dy,dz),ny=i===3||i===4?-.003:-dz/length*.003,nz=i===3||i===4?0:dy/length*.003;return[[-1,-1],[1,-1],[1,1],[-1,1]].map(([w,t])=>[x+w*.014,y+t*ny,z+t*nz]as V3);});for(let i=0;i<pts.length-1;i++)for(let j=0;j<4;j++){const k=(j+1)%4;orientedQuad(mesh,[frames[i][j],frames[i+1][j],frames[i+1][k],frames[i][k]]);}orientedQuad(mesh,frames[0]);orientedQuad(mesh,[...frames.at(-1)!].reverse());a.meshes=a.meshes!.map(m=>m===old?mesh:m);a.id=source.id+'-school-strap';a.name+=' · 学龄实际肩带';fitSource(a,source,{actualShoulderContact:contact,replacedMeshes:[old.name],preservedNativeCells:true,preservedBagBody:true,positionRelativeToBody:[.4,.15,0],reason:'Keep the original bag body, lid, anchors, native details and source. Lower its placement to clear the actual child hand and rebuild only the continuous shoulder strap from the child garment surface. Adult body and bag geometry are not scaled.'});return{asset:a,contact};}

function scarfFit(b:ProfessionBase,source:Asset,clothes:Asset){const f=garmentFrame(b.fit),outer=ellipsePoints({y:0,rx:.096,rz:.087}),inner=ellipsePoints({y:0,rx:.089,rz:.080}),rows=annularPoints(b.p,[clothes],outer,inner),contact=rows.reduce((a,b)=>a.point[1]>b.point[1]?a:b).point,a=structuredClone(source),old=a.meshes!.find(m=>m.name==='围巾真穿颈环')!;if(contact[1]>f.neck-.018+1e-8||contact[1]<f.neck-.05)throw new Error('Scarf fit exceeds verified neck range');a.meshes=a.meshes!.map(m=>m===old?roundBand(old.name,old.material,[{y:contact[1],rx:.096,rz:.087},{y:f.neck+.028,rx:.096,rz:.087}],.007):m);a.id=source.id+'-fit-'+b.recipe.clothing;a.name+=' · 实际衣领承接';fitSource(a,source,{contact,replacedMeshes:[old.name],oldBottomY:f.neck-.018,newBottomY:contact[1],preservedNativeCells:true,reason:'Lower only the existing neck-ring bottom to the exact maximum displayed garment surface inside its annular footprint. Upper ring, hanging strips, fringe and all original fasteners retained.'});return{asset:a,contact};}

function beltFit(b:ProfessionBase,source:Asset,clothes:Asset){const height=1.08,points:V3[]=[];for(const t of triangles(b.p,[clothes])){const poly=clipAxis(clipAxis(t.points,1,height+.003,true),1,height+.071,false);points.push(...poly.filter(v=>(v[0]/.215)**2+(v[2]/.148)**2<1.01));}const ratio=(thickness:number)=>{const ring=ellipsePoints({y:0,rx:.215-thickness,rz:.148-thickness});return points.map(point=>({point,value:Math.max(...ring.map((a,i)=>{const b=ring[(i+1)%16],nx=b[2]-a[2],nz=a[0]-b[0];return(nx*point[0]+nz*point[2])/(nx*a[0]+nz*a[2]);}))})).reduce((a,b)=>a.value>b.value?a:b);};let lo=.004,hi=.10;if(ratio(lo).value>1+1e-8)throw new Error('Original belt liner crosses torso');for(let j=0;j<44;j++){const mid=(lo+hi)/2;if(ratio(mid).value<=1)lo=mid;else hi=mid;}const a=structuredClone(source),old=a.meshes!.find(m=>m.name==='腰带软衬真实内缘')!;a.meshes=a.meshes!.map(m=>m===old?roundBand(old.name,old.material,[{y:.003,rx:.215,rz:.148},{y:.071,rx:.215,rz:.148}],lo):m);a.id=source.id+'-worker-liner';a.name+=' · 工作服腰内衬';const contact=ratio(lo).point;fitSource(a,source,{contact,replacedMeshes:[old.name],originalLinerThicknessM:.004,linerThicknessM:lo,preservedNativeCells:true,preservedOuterRingAndTools:true,mountY:height,shoulderRestDegrees:24,reason:'Fit only the inner soft liner to actual posed workwear. Original leather outer band, tool pockets, fittings, equipment case and native details retained at finite24-degree standing shoulder rest.'});return{asset:a,contact};}

/** Closed tab follows the actual front envelope, including all clipped face breakpoints. */
function badgeTab(b:ProfessionBase,clothes:Asset){const[x,y,z]=[-.10,1.28,-.18],m=emptyMesh('实际衣面承接的3mm夹持织带',b.p.styles.yunshan.garmentStrap),points:V3[]=[],polys=triangles(b.p,[clothes]).map(t=>clipAxis(clipAxis(t.points,0,x-.012,true),0,x+.012,false)).filter(p=>p.length),low=y-.10,high=y+.055,ys=[...new Set([low,high,y+.02,y-.03,y-.06,...polys.flatMap(p=>p.map(v=>v[1])).filter(v=>v>low&&v<high)].map(v=>Math.round(v*1e10)/1e10))].sort((a,b)=>b-a);
 const front=(yy:number)=>{const pts:V3[]=[];for(const poly of polys)for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length];if(Math.abs(a[1]-yy)<1e-9)pts.push(a);if((a[1]<yy&&b[1]>yy)||(a[1]>yy&&b[1]<yy)){const t=(yy-a[1])/(b[1]-a[1]);pts.push(a.map((v,k)=>v+t*(b[k]-v))as V3);}}if(!pts.length)throw new Error('No actual garment face below tab');return pts.reduce((a,b)=>a[2]<b[2]?a:b);};
 const frames=ys.map(yy=>{const touch=front(yy),blend=Math.max(0,Math.min(1,(y-.03-yy)/.03)),free=z+.011,back=Math.min(touch[2],free+(touch[2]-free)*blend);if(Math.abs(back-touch[2])<1e-10)points.push(touch);return[-1,1].flatMap(side=>[[x+side*.012,yy,back-.003],[x+side*.012,yy,back]]as V3[]);});for(let i=0;i<frames.length-1;i++)for(const[j,k]of[[0,2],[2,3],[3,1],[1,0]])orientedQuad(m,[frames[i][j],frames[i+1][j],frames[i+1][k],frames[i][k]]);orientedQuad(m,[frames[0][0],frames[0][2],frames[0][3],frames[0][1]]);orientedQuad(m,[frames.at(-1)![0],frames.at(-1)![1],frames.at(-1)![3],frames.at(-1)![2]]);
 const a=structuredClone(clothes);a.id='m058-badge-tab-'+clothes.id;a.name='衣装实际前表面夹牌织带';a.meshes=[m];a.chunks={};a.parts=[];a.ports=[];a.rig!.meshJoints={[m.name]:'chest'};a.rig!.voxelJoints=[];a.rig!.sockets={};fitSource(a,clothes,{clothContacts:points,clipBridgeContact:[x,y+.055,z+.010],clipSlotThicknessM:.003,clipSlotM:.004,reason:'Actual closed tab follows the displayed clothing front envelope across all clipped face breakpoints, including native hardware. Its free end reaches the real badge clip bridge; no floating test coupon or live identity.'});return a;
}

export function addProfessionAttachments(b:ProfessionBase,contacts:ProfessionContact[]){if(b.recipe.accessory===149)preserveShoulderPose(b,24);const put=accessoryInstaller(b),ci=clothesInstance(b),clothes=b.p.assets[ci.assetId],n=b.recipe.accessory,s=b.p.styles.yunshan;
 if(n===148){const source=makeAttireAsset('CHAR-148','原完整挎包','m058-school-bag',s,{lid:'closed'});b.p.assets[source.id]=source;const f=childBag(b,source,clothes),i=put(f.asset,[.4,.15,0]);contacts.push({kind:'child-shoulder-strap',point:f.contact,left:[ci.id],right:[i.id],rightMeshes:['挎包实际长肩带']});}
 if(n===141){const source=makeAttireAsset('CHAR-141','原独立围巾','m058-scarf',s,{costumeFit:b.fit});b.p.assets[source.id]=source;const f=scarfFit(b,source,clothes),i=put(f.asset);contacts.push({kind:'scarf-clothing',point:f.contact,left:[ci.id],right:[i.id],rightMeshes:['围巾真穿颈环']});}
 if(n===149){const source=makeHeldAsset('CHAR-149','原完整工具腰带','m058-worker-belt',s,{beltFit:b.fit});b.p.assets[source.id]=source;const f=beltFit(b,source,clothes);b.p.assets[f.asset.id]=f.asset;const i=put(garmentMount(f.asset,b.fit,'pelvis',[0,1.08,0],s,f.asset.id+'-mounted'));contacts.push({kind:'workwear-belt-liner',point:f.contact,left:[ci.id],right:[i.id],rightMeshes:['腰带软衬真实内缘']});}
 if(n===150){const source=makeHeldAsset('CHAR-150','原职业夹牌','m058-badge-waist',s,{badgeType:'waist'});b.p.assets[source.id]=source;const badge=put(garmentMount(source,b.fit,'chest',[-.10,1.28,-.18],s,source.id+'-mounted')),tab=badgeTab(b,clothes),ti=put(tab);for(const point of tab.source!.clothContacts as V3[])contacts.push({kind:'badge-clothing-tab',point,left:[ci.id],right:[ti.id]});contacts.push({kind:'badge-clip-bridge',point:tab.source!.clipBridgeContact as V3,left:[ti.id],right:[badge.id],rightMeshes:['背夹上桥']});}
}
