import {geometryData}from'../core/sky';
import {displayMesh}from'../core/mesh';
import type{Asset,Project,V3,Instance}from'../core/types';
import {outfitHash}from'./outfit-components';
import type{professionBaseScene}from'./profession-components';
export type ProfessionBase=ReturnType<typeof professionBaseScene>;
export type ProfessionContact={kind:string;point:V3;left:string[];right:string[];leftMeshes?:string[];rightMeshes?:string[]};
export function fitSource(a:Asset,source:Asset,details:Record<string,unknown>){a.source={kind:'author-profession-fit',notCatalogMaster:true,sourceAssetId:source.id,sourceGeometrySHA256:outfitHash(geometryData(source)),originalRetained:true,...details};return a;}
export function fromCatalog(p:Project,a:Asset,id:string):boolean{const seen=new Set<string>();while(a&&!seen.has(a.id)){if(a.source?.catalogId===id)return true;seen.add(a.id);a=p.assets[String(a.source?.sourceAssetId)];}return false;}
export function clothesInstance(b:ProfessionBase){const i=b.items.find(i=>fromCatalog(b.p,b.p.assets[i.assetId],'CHAR-'+b.recipe.clothing));if(!i)throw new Error('Missing actual clothing');return i;}
export function clipAxis(poly:V3[],axis:number,value:number,above:boolean){const out:V3[]=[];for(let j=0;j<poly.length;j++){const a=poly[j],b=poly[(j+1)%poly.length],A=above?a[axis]>=value:a[axis]<=value,B=above?b[axis]>=value:b[axis]<=value;if(A)out.push(a);if(A!==B){const t=(value-a[axis])/(b[axis]-a[axis]);out.push(a.map((v,k)=>v+t*(b[k]-v))as V3);}}return out;}
/** Clip to one convex edge in an explicitly selected projection. */
export function clipEdge(poly:V3[],a:V3,b:V3,inside:boolean,axes:[number,number]=[0,2]){const[u,v]=axes,nx=b[v]-a[v],ny=a[u]-b[u],d=nx*a[u]+ny*a[v],value=(p:V3)=>(nx*p[u]+ny*p[v]-d)*(inside?1:-1),out:V3[]=[];for(let j=0;j<poly.length;j++){const A=poly[j],B=poly[(j+1)%poly.length],va=value(A),vb=value(B);if(va<=1e-12)out.push(A);if((va<0)!==(vb<0)){const t=va/(va-vb);out.push(A.map((n,k)=>n+t*(B[k]-n))as V3);}}return out;}
export function triangles(p:Project,assets:Asset[]){return assets.flatMap(a=>displayMesh(a,p.materials).flatMap(mesh=>Array.from({length:mesh.indices.length/3},(_,j)=>({name:mesh.meshName??'native',points:mesh.indices.slice(j*3,j*3+3).map(i=>mesh.positions.slice(i*3,i*3+3)as V3)}))));}
export function annularPoints(p:Project,assets:Asset[],outer:V3[],inner:V3[],axes:[number,number]=[0,2]){const rows:{point:V3;mesh:string}[]=[];for(const t of triangles(p,assets)){let poly=t.points;for(let k=0;k<outer.length;k++)poly=clipEdge(poly,outer[k],outer[(k+1)%outer.length],true,axes);for(let k=0;k<inner.length;k++)rows.push(...clipEdge(poly,inner[k],inner[(k+1)%inner.length],false,axes).map(point=>({point,mesh:t.name})));}if(!rows.length)throw new Error('No actual surface in annular contact footprint');return rows;}
export function preserveShoulderPose(b:ProfessionBase,degrees:number){const changes=[];for(const i of b.items){const source=b.p.assets[i.assetId];if(!source.rig?.joints.some(j=>j.id==='shoulder-1'))continue;const a=structuredClone(source);a.id='m058-pose-'+degrees+'-'+outfitHash(source.id).slice(0,16);a.name+=' · 有限站姿肩角';for(const side of[-1,1]){const t=side*degrees*Math.PI/360;a.rig!.pose['shoulder'+side]=[0,0,Math.sin(t),Math.cos(t)];}fitSource(a,source,{shoulderAngleDegrees:degrees,preservedNativeCells:true,reason:'Explicit finite standing shoulder-angle derivative. Bind geometry, canonical source rig and material purposes retained; no general animation claim.'});b.p.assets[a.id]=a;i.assetId=a.id;changes.push({instance:i.id,source:source.id,posed:a.id});}return changes;}
export function accessoryInstaller(b:ProfessionBase){const origin=b.items[0].position;return(a:Asset,offset:V3=[0,0,0],rotation=0)=>{b.p.assets[a.id]=a;const i:Instance={id:'m058-'+a.id,assetId:a.id,name:a.name,position:[origin[0]+offset[0],origin[1]+offset[1],origin[2]+offset[2]],rotation,parent:null};b.items.push(i);return i;};}
