import type{Asset,V3}from'../core/types';
import {makeCostumeAsset}from'./atlas-costumes';
import {cutBand}from'./costume-frame';
import {garmentFront}from'./garment-shapes';
import {accessoryInstaller,clipAxis,clipEdge,clothesInstance,fitSource,triangles,type ProfessionBase,type ProfessionContact}from'./profession-fit';

export function addProfessionApron(b:ProfessionBase,contacts:ProfessionContact[]){if(b.recipe.accessory!==136)return;const ci=clothesInstance(b),clothes=b.p.assets[ci.assetId],source=makeCostumeAsset('CHAR-136','原独立胸兜围裙','m058-bib-apron',b.p.styles.yunshan,{costumeFit:b.fit});b.p.assets[source.id]=source;const a=structuredClone(source),old=a.meshes!.find(m=>m.name==='围裙背腰固定环')!,low=.985,high=1.015,rx=.183245281,rz=.135925758,power=.7,polygon=(t:number)=>Array.from({length:16},(_,i)=>{const angle=i/16*Math.PI*2,f=(x:number)=>Math.sign(x)*Math.abs(x)**power;return[f(Math.sin(angle))*(rx-t),0,-f(Math.cos(angle))*(rz-t)]as V3;}),outer=polygon(0),points:V3[]=[];
 for(const t of triangles(b.p,[clothes])){let poly=clipAxis(clipAxis(t.points,1,low,true),1,high,false);for(let i=0;i<16;i++)poly=clipEdge(poly,outer[i],outer[(i+1)%16],true);points.push(...poly);}
 const ratio=(thickness:number)=>{const ring=polygon(thickness);return points.map(point=>({point,value:Math.max(...ring.map((a,i)=>{const b=ring[(i+1)%16],nx=b[2]-a[2],nz=a[0]-b[0];return(nx*point[0]+nz*point[2])/(nx*a[0]+nz*a[2]);}))})).reduce((a,b)=>a.value>b.value?a:b);};let lo=.007,hi=.060;if(ratio(lo).value>1+1e-8)throw new Error('Apron outer waist profile does not clear actual clothing');for(let i=0;i<44;i++){const mid=(lo+hi)/2;if(ratio(mid).value<=1)lo=mid;else hi=mid;}
 const band=cutBand(old.name,old.material,[{y:low,rx,rz,power},{y:high,rx,rz,power}],0,Math.PI*2,lo,16);a.meshes=a.meshes!.map(m=>m===old?band:m);const strips=a.meshes.filter(m=>m.name.startsWith('围裙连续肩带')),bib=a.meshes.find(m=>m.name==='围裙胸兜及下摆')!,strapContacts:{mesh:string;point:V3;lowerShiftM:number}[]=[];
 for(const mesh of strips){const ys=mesh.positions.filter((_,k)=>k%3===1),bottom=Math.min(...ys),top=Math.max(...ys),lower=Array.from({length:mesh.positions.length/3},(_,i)=>mesh.positions.slice(i*3,i*3+3)as V3).filter(p=>Math.abs(p[1]-bottom)<1e-10).reduce((a,b)=>a[2]>b[2]?a:b),z=garmentFront([bib],lower[0],bottom),shift=lower[2]-z;if(shift<0||shift>.03)throw new Error('Apron lower strap fit exceeds verified bib connection');strapContacts.push({mesh:mesh.name,point:[lower[0],bottom,z],lowerShiftM:shift});for(let k=0;k<mesh.positions.length;k+=3){const t=(mesh.positions[k+1]-bottom)/(top-bottom);mesh.positions[k+2]-=.008*Math.sin(Math.PI*t)+shift*(1-t);}for(let j=0;j<mesh.indices.length;j+=3){const[a,b,c]=mesh.indices.slice(j,j+3).map(i=>mesh.positions.slice(i*3,i*3+3)),u=b.map((v,k)=>v-a[k]),v=c.map((v,k)=>v-a[k]),n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],L=Math.hypot(...n);for(const i of mesh.indices.slice(j,j+3))mesh.normals.splice(i*3,3,...n.map(v=>v/L));}}
 a.id=source.id+'-service-fit';a.name+=' · 原服务衣外穿拟合';const contact=ratio(lo).point;fitSource(a,source,{contact,preservedNativeCells:true,replacedMeshes:[old.name,...strips.map(m=>m.name)],waist:{low,high,rx,rz,power,thicknessM:lo},shoulderStripFrontBendM:.008,strapContacts,reason:'Fit the independent waist ring to actual service clothing using rounded rectangular corners and a real inner contact. Bend original shoulder strips forward and reconnect their lower ends to the actual bib front, preserving upper endpoints, bib, neck loop, pockets and native fasteners. Complete original136 retained; covered duplicate135 apron and catches are removed only in a separate preserved-source underlayer derivative.'});const item=accessoryInstaller(b)(a);contacts.push({kind:'apron-waist-clothing',point:contact,left:[ci.id],right:[item.id],rightMeshes:['围裙背腰固定环']});for(const c of strapContacts)contacts.push({kind:'apron-strap-bib',point:c.point,left:[item.id],right:[item.id],leftMeshes:[bib.name],rightMeshes:[c.mesh]});}
