import type{Project,V3}from'../core/types';
import {assetBoundsM}from'../core/sky';
import {ArchitectureBuilder}from'./architecture-near-assembly';
import {professionBaseScene,professionRecipes}from'./profession-components';
import {outfitSourceImporter}from'./outfit-components';
import {addProfessionAttachments}from'./profession-attachments';
import {addProfessionHeadwear}from'./profession-headwear';
import {addProfessionApron}from'./profession-apron';
import type{ProfessionContact}from'./profession-fit';
export const professionAssemblyIds=Object.keys(professionRecipes).map(n=>'CHAR-'+n);
export function makeProfessionAssembly(p:Project,catalogId:string,id:string,name:string){const n=Number(catalogId.slice(5)),base=professionBaseScene(p,n),contacts:ProfessionContact[]=[];addProfessionAttachments(base,contacts);addProfessionHeadwear(base,contacts);addProfessionApron(base,contacts);const builder=new ArchitectureBuilder(p,id),importer=outfitSourceImporter(builder,base.p),origin=base.items[0].position,minimumY=Math.min(...base.items.map(i=>assetBoundsM(base.p.assets[i.assetId])!.min[1]+i.position[1])),placed=base.items.map(i=>({sourceInstance:i.id,sourceAsset:i.assetId,assetId:importer.keep(i.assetId),position:[i.position[0]-origin[0],i.position[1]-minimumY,i.position[2]]as V3,rotation:i.rotation})),instances=placed.map(i=>({...i,instance:builder.place(i.assetId,i.position,i.rotation,'wearer')})),omitted=base.omitted.map(i=>({sourceInstance:i.id,retainedAsset:importer.keep(base.p.assets[i.assetId].meshes?.length?i.assetId:String(base.p.assets[i.assetId].source!.sourceAssetId)),reason:i.id.endsWith('-hair')?'Original short hair retained; actual093 crown hairstyle substitutes its installation.':'Original source and omitted duplicate neck/solid trousers retained separately.'})),map=(key:string)=>{const i=instances.find(i=>i.sourceInstance===key);if(!i)throw new Error('Missing actual contact component '+key);return i.instance;};
 return builder.finish(catalogId,name,{parameters:{},profession:{bodyFit:base.fit,pose:'finite standing',shoulderRestDegrees:[168,170].includes(n)?24:n===172||n===173?20:8,clothing:'CHAR-'+base.recipe.clothing,accessory:'CHAR-'+base.recipe.accessory,sourceScene:base.sourceScene,sourceSelection:base.sourceSelection,sourceGraph:importer.sources,instances,omitted,groundY:0,groundShiftY:-minimumY,contacts:contacts.map(c=>({...c,point:[c.point[0],c.point[1]+origin[1]-minimumY,c.point[2]]as V3,left:c.left.map(map),right:c.right.map(map)})),sharedGeometryFamily:[168,170].includes(n)?'CHAR130 plus CHAR149 tool belt at the same finite24-degree standing pose':null},physical:false,originalBaseline:{readOnly:['Citizen.id','position','state','role','actorProfiles.age','alive']},ageSeedRoleBinding:false,softCloth:false,animationClips:false,scope:'Twelve catalogue outfit contracts with eleven distinct configurations;165 uses independent school-child proportions and actual child head/hands/feet, all other templates adultA. Canonical sources, exact installation fitting and finite rigid poses retained. No new human base master, all-age fit, soft cloth, identity/wages/permissions/inventory binding or human art acceptance.'});}
