import type {V3} from '../core/types';import {AvatarModel} from './avatar-model';import {emptyMesh,quad,hollowLoft,roundBand,type Ring,band,rigidMesh,loft} from './mesh-shapes';import {fibre} from './headwear-shapes';
export const wearScale=(fit:string)=>fit==='child'?.215/.24:1;
export function clothTube(m:AvatarModel,name:string,role:string,points:V3[],radius=.005){m.mesh(fibre(name,m.s[role],points,points.map(()=>radius)));}
export function hatShell(m:AvatarModel,name:string,role:string,outer:Ring[],thickness=.008){const inner=outer.map((r,i)=>({...r,y:r.y-(i?thickness:0),rx:r.rx-thickness,rz:r.rz-thickness}));m.mesh(hollowLoft(name,m.s[role],outer,inner,'bottom'));return inner;}
/** Rectangular/rounded ring whose normal axis is Z; actual empty lens aperture. */
export function faceRing(m:AvatarModel,name:string,role:string,x:number,y:number,z:number,w:number,h:number,depth:number,t:number){m.mesh(rigidMesh(band(name,m.s[role],{y:-depth/2,rx:w/2,rz:h/2},{y:depth/2,rx:w/2,rz:h/2},t),[x,y,z],Math.PI/2));}
export function facePlate(m:AvatarModel,name:string,role:string,x:number,y:number,z:number,w:number,h:number,depth:number){m.mesh(rigidMesh(loft(name,m.s[role],[{y:-depth/2,rx:w/2,rz:h/2},{y:depth/2,rx:w/2,rz:h/2}]),[x,y,z],Math.PI/2));}
/** Closed curved thin panel, with independently authored inner and outer surfaces. */
export function curvedPanel(name:string,material:number,rows:{y:number;halfWidth:number;centerZ:number;edgeZ:number}[],thickness=.004){const m=emptyMesh(name,material),N=8,front=rows.map(r=>Array.from({length:N+1},(_,i)=>{const x=(i/N*2-1)*r.halfWidth;return[x,r.y,r.centerZ+(r.edgeZ-r.centerZ)*(x/r.halfWidth)**2] as V3;})),back=front.map(row=>row.map(([x,y,z])=>[x,y,z+thickness] as V3));for(let r=0;r<rows.length-1;r++)for(let i=0;i<N;i++){quad(m,[front[r][i],front[r][i+1],front[r+1][i+1],front[r+1][i]],[0,0,-1]);quad(m,[back[r][i],back[r][i+1],back[r+1][i+1],back[r+1][i]],[0,0,1]);}for(const r of[0,rows.length-1])for(let i=0;i<N;i++)quad(m,[front[r][i],front[r][i+1],back[r][i+1],back[r][i]],[0,r===0?-1:1,0]);for(const i of[0,N])for(let r=0;r<rows.length-1;r++)quad(m,[front[r][i],front[r+1][i],back[r+1][i],back[r][i]],[i===0?-1:1,0,0]);return m;}
export function chinStrap(m:AvatarModel,sy:number){for(const side of[-1,1])clothTube(m,'下颌织带-'+side,'helmetStrap',[[side*.158,.18*sy,.02],[side*.145,.055*sy,-.060],[side*.050,-.017,-.090],[0,-.026,-.092]],.007);m.box('下颌扣','hatHardware',-.0125,-.032,-.105,.025,.020,.015);}
export function bandLiner(m:AvatarModel,sy:number){m.mesh(roundBand('独立帽盔内衬环',m.s.helmetPad,[{y:.160*sy,rx:.158,rz:.151},{y:.185*sy,rx:.158,rz:.151}],.009));}
/** Open back visor built as an inclined annular sector, never a solid disk over the scalp. */
export function visor(m:AvatarModel,name:string,role:string,sy:number){const mesh=emptyMesh(name,m.s[role]),N=12,rings=[0,1].map(r=>Array.from({length:N+1},(_,i)=>{const a=-Math.PI/2+i/N*Math.PI;return[Math.sin(a)*(r?.18:.153),(r?.165:.184)*sy,-Math.cos(a)*(r?.245:.148)] as V3;})),bottom=rings.map(row=>row.map(([x,y,z])=>[x,y-.008,z] as V3));for(let i=0;i<N;i++){quad(mesh,[rings[0][i],rings[0][i+1],rings[1][i+1],rings[1][i]],[0,1,0]);quad(mesh,[bottom[0][i],bottom[0][i+1],bottom[1][i+1],bottom[1][i]],[0,-1,0]);for(const r of[0,1]){const a=rings[r][i],b=rings[r][i+1];quad(mesh,[a,b,bottom[r][i+1],bottom[r][i]],[(a[0]+b[0])*(r?1:-1),0,(a[2]+b[2])*(r?1:-1)]);}}for(const i of[0,N])quad(mesh,[rings[0][i],rings[1][i],bottom[1][i],bottom[0][i]],[0,0,1]);m.mesh(mesh);}
