import type {Asset,Project,V3} from '../core/types';import {makeWearableAsset} from './atlas-wearables';import {makeHeadwearAsset} from './atlas-headwear';import {makeAvatarAsset} from './atlas-avatar';import {makeFigureAsset,figureProportions} from './atlas-figure';import {fittingHead} from './headwear-face';import {turnHead} from './headwear-assembly';import {snap} from './avatar-model';
export const wearableScenes=['uniforms','hygiene-straw','eyewear','pins','earrings','masks','combinations'] as const;export type WearableScene=typeof wearableScenes[number];
export const wearableCombinations=[{fit:'adult',body:'CHAR-059',ids:['CHAR-101','CHAR-108'],yaw:-30},{fit:'adult',body:'CHAR-060',ids:['CHAR-103','CHAR-112'],yaw:0},{fit:'elder',body:'CHAR-065',ids:['CHAR-104','CHAR-110'],yaw:30},{fit:'child',body:'CHAR-063',ids:['CHAR-106','CHAR-111'],yaw:0}];
export function wearableFitParams(id:string,fit:string):Record<string,string>{const n=Number(id.slice(5));return n<=106?{wearFit:fit==='child'?'child':'adult'}:n===110?{earFit:fit}:{headFit:fit};}
export function wearableScene(base:Project,kind:WearableScene):Project{const p=structuredClone(base);p.name='M035 · '+kind+' 作者穿戴';p.assets={};p.instances={};const s=p.styles.yunshan,retain=(a:Asset)=>{p.assets[a.id]=a;return a;},add=(a:Asset,position:V3,key=a.id)=>{retain(a);const id='i-'+key;p.instances[id]={id,assetId:a.id,name:a.name,position:position.map(snap) as V3,rotation:0,parent:null};return a;},make=(id:string,key:string,fit:string)=>makeWearableAsset(id,id,key,s,wearableFitParams(id,fit)),head=(fit:string,key:string)=>({...fittingHead(s,fit),id:key}),hair=(fit:string,key:string)=>makeAvatarAsset('CHAR-085','独立短发',key,s,{hairFit:fit==='child'?'child':'adult'}),headPair=(fit:string,key:string,pos:V3)=>{add(head(fit,'head-'+key),pos);add(hair(fit,'hair-'+key),pos);};
 if(kind==='uniforms'||kind==='hygiene-straw'){const ids=kind==='uniforms'?['CHAR-101','CHAR-102','CHAR-103']:['CHAR-104','CHAR-105','CHAR-106'];for(const[i,id]of ids.entries())for(const[j,fit]of ['adult','child'].entries()){const key=id+'-'+fit,pos:V3=[(i-1)*.80,.040+j*.65,0];headPair(fit,key,pos);add(make(id,key,fit),pos);}}
 if(kind==='eyewear'||kind==='masks'){const ids=kind==='eyewear'?['CHAR-108','CHAR-109']:['CHAR-111','CHAR-112'];for(const[i,id]of ids.entries())for(const[j,fit]of ['adult','child','elder'].entries()){const key=id+'-'+fit,pos:V3=[(j-1)*.48,.035+i*.43,0];headPair(fit,key,pos);add(make(id,key,fit),pos);}}
 if(kind==='earrings')for(const[j,fit]of ['adult','child','elder'].entries()){const pos:V3=[(j-1)*.48,.035,0];headPair(fit,fit,pos);add(make('CHAR-110','earrings-'+fit,fit),pos);}
 if(kind==='pins')for(const[i,pinLength]of ['long','short'].entries()){const key=pinLength,pos:V3=[(i-.5)*.75,.33,0];add(head('adult','head-'+key),pos);add(makeHeadwearAsset('CHAR-093','独立高髻','topknot-'+key,s),pos);add(makeHeadwearAsset('CHAR-100','已抽簪独立冠','crown-'+key,s,{pinState:'removed'}),[pos[0],pos[1]+.305,.06]);add(makeWearableAsset('CHAR-107','独立花簪','pin-'+key,s,{pinLength}),[pos[0],pos[1]+.420,.06]);}
 if(kind==='combinations')for(const[i,c]of wearableCombinations.entries()){const x=(i-1.5)*.8,q=figureProportions[c.body],pos:V3=[x,q.heightM-q.headM,0];add(makeFigureAsset(c.body,'原身体','body-'+i,s),[x,0,0]);const originals=[retain(head(c.fit,'head-source-'+i)),retain(hair(c.fit,'hair-source-'+i)),...c.ids.map(id=>retain(make(id,id+'-source-'+i,c.fit)))];for(const a of originals)add(turnHead(a,c.yaw,a.id+'-worn'),pos);}
 p.selection={assetId:Object.values(p.instances)[0].assetId,region:null,partId:null};return p;
}
