import {Matrix4,Vector3,Color} from 'three';
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {NodeIO} from '@gltf-transform/core';import {KHRMaterialsUnlit,KHRMaterialsEmissiveStrength,KHRLightsPunctual} from '@gltf-transform/extensions';import sharp from 'sharp';
import {Engine,validateProject} from '../src/core/engine';import {newProject} from '../src/core/materials';import {Grid} from '../src/core/grid';import type {Project,Assembly,Command} from '../src/core/types';import {productionProject,productionStyleCommands} from '../src/production/style';import {referenceFinishCommands} from '../src/production/reference-finish';import {makeArchitectureAssembly,environmentAssemblyIds,residentialAssemblyIds} from '../src/production/atlas-architecture-assemblies';import {environmentVariants,atmosphereCard} from '../src/production/environment-assemblies';import {ArchitectureBuilder} from '../src/production/architecture-near-assembly';import {parseCatalogCSV} from '../src/core/catalog';import {geometryData} from '../src/core/sky';import {makeCatalogAsset} from '../src/production/catalog-assets';import {architectureClosed,architectureComponents} from '../scripts/lib/architecture-audit';import {nativeIslandAttachments} from '../src/production/mixed-review';import {CivicAudit,civicSupports} from '../scripts/lib/civic-audit';import {districtClearance} from '../scripts/lib/district-audit';import {environmentAudit} from '../scripts/lib/environment-audit';import {habitatAudit} from '../scripts/lib/habitat-audit';import {activeAuthorEnvironment,authorEnvironmentState} from '../src/core/author-environment';import {buildGLB} from '../src/export/exporter';import {displayMesh} from '../src/core/mesh';import {atmospherePixels} from '../src/core/atmosphere-texture';
const catalog=Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r])),cache=new Map<string,{p:Project;a:Assembly}>(),hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex'),io=new NodeIO().registerExtensions([KHRMaterialsUnlit,KHRMaterialsEmissiveStrength,KHRLightsPunctual]);
const commit=(e:Engine,commands:Command[])=>{const r={expectedVersion:e.project.version,requestId:crypto.randomUUID(),commands},d=e.execute({...r,dryRun:true});return e.execute({...r,previewToken:d.previewToken});};
function make(id:string,params:Record<string,string|number>={}){const key=JSON.stringify([id,params]);if(!cache.has(key)){const p=productionProject(id);p.catalog={sourceName:'catalog',importedAt:'test',entries:structuredClone(catalog)};const a=makeArchitectureAssembly(p,id,id.toLowerCase(),id,params);p.assemblies={[a.id]:a};p.instances=Object.fromEntries(a.instances.map(i=>[i.id,i]));validateProject(p);cache.set(key,{p,a});}return cache.get(key)!;}
const forms=[...environmentAssemblyIds,...residentialAssemblyIds].flatMap(id=>environmentVariants(id).map(params=>({id,params})));
test('M052 22 finite forms retain closed physical parts, attached minimum cells and reversible quarter turns',()=>{assert.equal(forms.length,22);for(const{id,params}of forms){const {p,a}=make(id,params);for(const asset of Object.values(p.assets).filter(a=>a.source?.kind==='assembly-derived-component'&&!a.source?.openVisualSurface&&!a.source?.materialOnly)){assert.ok(architectureClosed(asset).every(x=>x.closed&&x.oriented),id+' '+asset.id);const connected=nativeIslandAttachments({...asset,meshes:architectureComponents(asset)});if(asset.meshes?.length)assert.ok(connected.every(x=>x.attached),asset.id);else{assert.equal(connected.length,1,asset.id+' is one face-connected native cabinet');assert.equal(connected[0].cells,new Grid(asset.chunks).count);}}const e=new Engine(p),geometry=hash(e.project.assets);commit(e,[{op:'instantiateAssembly',assemblyId:a.id,prefix:'quarter',position:[60,0,60],rotation:1}]);assert.equal(hash(e.project.assets),geometry);commit(e,[{op:'undo'}]);assert.deepEqual(e.project.instances,p.instances);}});
test('M052 actual rooms, bearings, drain, terrain contacts, water and body routes pass independently',()=>{for(const{id,params}of forms){const{p,a}=make(id,params),q=new CivicAudit(p,a),routes=districtClearance(q),extra=environmentAudit(p,a);assert.ok(civicSupports(q).every(x=>x.supported),id);assert.ok(routes.checks.every(x=>x.clear),id+JSON.stringify(routes.checks.filter(x=>!x.clear)));assert.ok(routes.contacts.every(x=>x.supported),id);assert.ok(extra.uses.every(x=>x.clear&&x.footPresent),id+JSON.stringify(extra.uses));assert.ok(extra.seats.every(x=>x.seatPresent&&x.torsoClear&&x.approachClear&&x.footPresent),id+JSON.stringify(extra.seats));assert.ok(extra.bearings.every(x=>x.lowerPresent&&x.upperPresent),id+JSON.stringify(extra.bearings));assert.ok(extra.mounts.every(x=>x.wallPresent&&x.fixtureTouchesWall),id);assert.ok(extra.bonsai.every(x=>x.soilPresent&&x.potBearing),id);if(extra.drain)assert.ok(extra.drain.clear);if(extra.kitchen){assert.ok(extra.kitchen.bowlClear.clear);assert.ok(extra.kitchen.hoodOpen.clear&&extra.kitchen.hoodOpen.grillePresent,JSON.stringify(extra.kitchen));}assert.ok(extra.atmospheric.every(x=>x.nonphysical&&x.actualTriangles===2&&x.alphaRange[0]===0&&x.alphaRange[1]>0&&x.alphaRange[1]<255&&x.clearOfTerrain),id+JSON.stringify(extra.atmospheric));const habitat=habitatAudit(p,a);assert.ok(habitat.water.every(x=>x.waterPresent&&x.bedPresent&&!x.terrainAboveWater.length),id);assert.ok(habitat.plants.every(x=>x.actualRoot&&x.actualSoil),id);}});
test('M052 original assets and exact sink cabinet deletion are preserved',()=>{for(const id of [...environmentAssemblyIds,...residentialAssemblyIds]){const{p,a}=make(id);for(const asset of Object.values(p.assets).filter(x=>x.source?.kind==='catalog-recipe')){const expected=makeCatalogAsset(String(asset.source!.catalogId),asset.name,asset.id,p.styles.yunshan,asset.source!.parameters as any);assert.deepEqual(geometryData(asset),geometryData(expected),id+' '+asset.id);}if(id==='LIFE-061'){const room=a.source!.room as any,derived=p.assets[a.instances.find(i=>i.id===room.kitchen.installedCabinet)!.assetId],original=p.assets[room.kitchen.canonicalCabinet],old=new Grid(original.chunks),next=new Grid(derived.chunks),removed=derived.source!.removedCells as any[];assert.ok(removed.length>0);for(const r of removed){assert.equal(old.get(r.cell),r.material);assert.equal(next.get(r.cell),0);old.set(r.cell,0);}assert.deepEqual(old.serialize(),next.serialize());}}});
test('M052 public creation preserves foreign IDs, supports continuous time, rejects invalid states and undoes atomically',()=>{const p=newProject();p.catalog={sourceName:'catalog',importedAt:'test',entries:structuredClone(catalog)};for(let id=533;id<=537;id++)p.materials[id]={...p.materials[1],id,name:'foreign-'+id};const e=new Engine(p),before=hash(e.project);commit(e,[{op:'produceCatalogAssembly',catalogId:'ENV-115',id:'clock',params:{hour:17.35},place:true}]);assert.equal(Object.keys(e.project.styles.yunshan).length,511);for(let id=533;id<=537;id++)assert.equal(e.project.materials[id].name,'foreign-'+id);assert.equal((e.project.assemblies!.clock.source!.environment as any).hour,17.35);const generated=hash(e.project);for(const params of[{hour:25},{hour:NaN},{weather:'snow'},{winterCover:'frost'}]){assert.throws(()=>commit(e,[{op:'produceCatalogAssembly',catalogId:'ENV-115',id:'invalid',params}]));assert.equal(hash(e.project),generated);}commit(e,[{op:'undo'}]);for(const key of['materials','styles','assets','assemblies','instances']as const)assert.deepEqual(e.project[key],p[key]);const counts=productionStyleCommands().filter(c=>c.op==='materialBatch').map(c=>c.entries.length);assert.deepEqual(counts,[256,255]);for(const id of residentialAssemblyIds){const e=new Engine(p);commit(e,[{op:'produceCatalogAssembly',catalogId:id,id:id.toLowerCase(),place:true}]);assert.ok(e.project.assemblies![id.toLowerCase()].source?.room);}});
test('M052 atmospheric RGBA textures survive GLB unchanged and never merge different descriptors',async()=>{const p=productionProject('textures'),b=new ArchitectureBuilder(p,'fx');for(const [j,kind]of(['cloud','fog','rain','cloud']as const).entries())atmosphereCard(b,'test-'+j,kind,[[j*3,0,0],[j*3+2,0,0],[j*3+2,2,0],[j*3,2,0]],.7,1,.4,80+j);const twin=structuredClone(Object.values(p.assets)[3].meshes![0]);Object.values(p.assets)[0].meshes!.push(twin);p.instances=Object.fromEntries(b.instances.map(i=>[i.id,i]));const e=new Engine(p);commit(e,referenceFinishCommands(p));commit(e,[{op:'palette',name:'参考材质试作'}]);const doc=await io.readBinary((await buildGLB(e.project)).glb);for(const i of b.instances){const a=e.project.assets[i.assetId],buckets=displayMesh(a,e.project.materials),node=doc.getRoot().listNodes().find(n=>n.getExtras().instanceId===i.id)!,primitives=node.getMesh()!.listPrimitives();assert.equal(primitives.length,buckets.length);for(const [j,bucket]of buckets.entries()){const primitive=primitives[j],material=primitive.getMaterial()!,pixels=await sharp(Buffer.from(material.getBaseColorTexture()!.getImage()!)).ensureAlpha().raw().toBuffer();assert.deepEqual(pixels,Buffer.from(bucket.texture!.data));assert.equal(material.getAlphaMode(),'BLEND');assert.ok(material.getExtension('KHR_materials_unlit'));const uv=Array.from(primitive.getAttribute('TEXCOORD_0')!.getArray()!);assert.deepEqual(uv,bucket.uvs);assert.deepEqual(geometryData(e.project.assets[a.id]),geometryData(p.assets[a.id]));}}const first=Object.values(e.project.assets)[0],texture=atmospherePixels(first.meshes![0].atmosphere!,e.project.materials[first.meshes![0].material]);e.project.materials[first.meshes![0].material].color='#ff1122';assert.notDeepEqual(atmospherePixels(first.meshes![0].atmosphere!,e.project.materials[first.meshes![0].material]).data,texture.data);});
test('M052 day-night use one curve, preserve foreground and export actual directional lights',async()=>{const day=make('ENV-115',{hour:12}),night=make('ENV-115',{hour:0}),d=activeAuthorEnvironment(day.p)!,n=activeAuthorEnvironment(night.p)!;assert.ok(d.state.sunIntensity>n.state.sunIntensity);assert.ok(n.state.moonIntensity>d.state.moonIntensity);for(const asset of Object.values(day.p.assets).filter(a=>!a.sky&&!a.source?.openVisualSurface&&!a.source?.materialOnly))assert.deepEqual(geometryData(asset),geometryData(night.p.assets[asset.id]));const doc=await io.readBinary((await buildGLB(day.p)).glb),lights=doc.getRoot().listNodes().filter(n=>n.getExtension('KHR_lights_punctual'));assert.equal(lights.length,2);assert.equal((lights.find(n=>n.getName()==='author-sun')!.getExtension('KHR_lights_punctual')as any).getIntensity(),d.state.sunIntensity);assert.equal((doc.getRoot().listScenes()[0].getExtras().authorEnvironment as any).environment.originalStateBound,false);assert.deepEqual(authorEnvironmentState(d.environment,1).sun,[d.state.sun[2],d.state.sun[1],-d.state.sun[0]]);const turnSource=make('ENV-115',{hour:17.35}),turnEngine=new Engine(turnSource.p);commit(turnEngine,[...Object.values(turnSource.p.instances).map(i=>({op:'removeInstance',id:i.id})as Command),{op:'instantiateAssembly',assemblyId:turnSource.a.id,prefix:'turned-light',position:[60,0,60],rotation:1}]);const rotated=turnEngine.project;const active=activeAuthorEnvironment(rotated)!;assert.equal(active.rotation,1);const rotatedGLB=await io.readBinary((await buildGLB(rotated)).glb);for(const lightNode of rotatedGLB.getRoot().listNodes().filter(n=>n.getExtension('KHR_lights_punctual'))){const color=lightNode.getName()==='author-sun'?active.state.sunColor:active.state.moonColor;assert.ok((lightNode.getExtension('KHR_lights_punctual')as any).getColor().every((v:number,k:number)=>Math.abs(v-new Color(color).toArray()[k])<1e-7));const actual=new Vector3(0,0,-1).transformDirection(new Matrix4().fromArray(lightNode.getWorldMatrix())).toArray(),expected=lightNode.getName()==='author-sun'?active.state.sun:active.state.moon;assert.ok(actual.every((v,k)=>Math.abs(v+expected[k])<1e-7));}const fake=structuredClone(day.p);fake.assemblies!.second={...fake.assemblies!['env-115'],id:'second'};assert.equal(activeAuthorEnvironment(fake),null);});

// Material corrections are checked against every source cell, not a visual colour match.
test('M052 furniture material derivatives preserve every occupancy and assign actual semantic uses',()=>{
 const seen=new Set<string>();for(const id of residentialAssemblyIds){const{p}=make(id);for(const a of Object.values(p.assets).filter(a=>a.source?.materialOnly)){
  const original=p.assets[String(a.source!.sourceAssetId)],before=new Grid(original.chunks),after=new Grid(a.chunks);seen.add(String(original.source!.catalogId));
  assert.equal(before.count,after.count);for(const key of ['origin','cellSize','parts','ports','openings']as const)assert.deepEqual(a[key],original[key]);
  assert.equal(hash(geometryData(original)),a.source!.sourceGeometrySHA256);let changed=0;for(const[cell,m]of before.cells()){const next=after.get(cell);assert.ok(next);assert.equal(p.materials[next].solid,p.materials[m].solid);if(next!==m)changed++;}assert.ok(changed>0);assert.equal(changed,Object.values(a.source!.materialChanges as Record<string,number>).reduce((s,n)=>s+n,0));
  const at=(point:number[])=>after.get(point.map((v,k)=>Math.floor((v-a.origin[k])/a.cellSize))as [number,number,number]),role=p.styles.yunshan;
  if(original.source!.catalogId==='LIFE-002'){assert.equal(at([.5,.11,.5]),role.cottonWhite);assert.equal(at([.5,.04,.5]),role.fabricEdge);}
  if(original.source!.catalogId==='LIFE-003')assert.equal(at([1.575,.695,-.055]),role.displayGlyph);
  if(original.source!.catalogId==='LIFE-004')assert.equal(at([.2,.065,1.7]),role.cottonWhite);
  if(original.source!.catalogId==='LIFE-018'){assert.equal(at([.045,.185,.035]),role.displayGlyph);assert.equal(at([.3,.445,.045]),role.opticsGlow);}
  if(original.source!.catalogId==='LIFE-108'){assert.equal(at([.15,.80,.15]),role.paperSheet);assert.equal(at([.135,.80,.105]),role.bookCover);assert.equal(at([.24,.80,.105]),role.bookCloth);assert.equal(at([.14,1.34,.10]),role.wall);}
 }}assert.deepEqual([...seen].sort(),['LIFE-002','LIFE-003','LIFE-004','LIFE-018','LIFE-108']);
});
