import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Engine,validateProject} from '../src/core/engine';
import {newProject} from '../src/core/materials';
import {geometryData} from '../src/core/sky';
import {rotateY,type Project,type Assembly,type Command} from '../src/core/types';
import {productionProject} from '../src/production/style';
import {parseCatalogCSV} from '../src/core/catalog';
import {makeArchitectureAssembly} from '../src/production/atlas-architecture-assemblies';
import {livingAssemblyIds,livingVariants} from '../src/production/living-assemblies';
import {livingComponents} from '../src/production/living-wear';
import {makeCatalogAsset} from '../src/production/catalog-assets';
import {outfitHash} from '../src/production/outfit-components';
import {referenceFinishCommands} from '../src/production/reference-finish';
import {nativeIslandAttachments} from '../src/production/mixed-review';
import {wildlifeClosed,wildlifeComponents} from '../scripts/lib/wildlife-audit';
import {livingAudit,livingViewAudit} from '../scripts/lib/living-audit';
const same=(a:unknown,b:unknown,message?:string)=>assert.equal(outfitHash(a??null),outfitHash(b??null),message);
const catalog=Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r])),cache=new Map<string,{p:Project;a:Assembly}>();
function make(id:string,params:Record<string,string>={}){const key=JSON.stringify([id,params]);if(!cache.has(key)){const p=productionProject(id);p.catalog={sourceName:'catalog',importedAt:'test',entries:structuredClone(catalog)};const a=makeArchitectureAssembly(p,id,id.toLowerCase(),id,params);p.assemblies={[a.id]:a};p.instances=Object.fromEntries(a.instances.map(i=>[i.id,i]));validateProject(p);cache.set(key,{p,a});if(cache.size>1)cache.delete(cache.keys().next().value!);}return cache.get(key)!;}
function* forms(){for(const id of livingAssemblyIds)for(const params of livingVariants(id))yield{id,params,...make(id,params)};}
const commit=(e:Engine,commands:Command[])=>{const req={expectedVersion:e.project.version,requestId:crypto.randomUUID(),commands},dry=e.execute({...req,dryRun:true});return e.execute({...req,previewToken:dry.previewToken});};

test('M059 six assembly contracts expose twelve finite forms with closed surfaces, real rigs and attached smallest components',()=>{assert.equal(livingAssemblyIds.length,6);assert.equal(livingAssemblyIds.flatMap(livingVariants).length,12);for(const{id,p,a}of forms()){assert.equal(a.source!.notCatalogBase,true);for(const asset of Object.values(p.assets)){assert.ok(wildlifeClosed(asset).every(r=>r.closed&&r.oriented),id+' '+asset.id);assert.ok(nativeIslandAttachments({...asset,meshes:wildlifeComponents(asset)}).every(r=>r.attached),id+' '+asset.id);}}});

test('M059 all actual posed body and accessory pairs clear and eighteen fitted surface contacts meet',()=>{let pairs=0,contacts=0;for(const{id,params,p,a}of forms()){const q=livingAudit(p,a);assert.ok(q.pairs.every(r=>!r.contained&&!r.crossing),id+JSON.stringify(params));assert.ok(q.contactsPassed&&q.groundPassed&&q.animalGroundPassed&&q.nonphysical&&q.rigsRetained,id);pairs+=q.pairs.length;contacts+=q.contacts.length;}assert.equal(pairs,112);assert.equal(contacts,18);});

test('M059 every canonical source and parent geometry hash is exact and animal fitting preserves outer parts and native cells',()=>{let edges=0;for(const{p}of forms())for(const a of Object.values(p.assets)){if(a.source?.kind==='catalog-recipe'){const canonical=makeCatalogAsset(String(a.source.catalogId),a.name,a.id,p.styles.yunshan,a.source.parameters as any);same(geometryData(a),geometryData(canonical));for(const k of['ports','parts','openings','cellSize','origin']as const)same(a[k],canonical[k]);}if(a.source?.sourceAssetId){const parent=p.assets[String(a.source.sourceAssetId)];assert.ok(parent);assert.equal(a.source.sourceGeometrySHA256,outfitHash(geometryData(parent)));edges++;const fit=a.source.retainedAuthorSource as any;if(fit?.kind==='author-animal-wear-fit'){same(a.chunks,parent.chunks);same(a.parts,parent.parts);same(a.ports,parent.ports);const replaced=new Set(fit.contacts.map((c:any)=>c.mesh));for(const mesh of livingComponents(parent))if(!replaced.has(mesh.name))same(a.meshes!.find(m=>m.name===mesh.name),mesh);}}}assert.ok(edges>40);});

test('M059 patient uses actual pajamas and retained145 with reconstructed native clamps and valid torso socket',()=>{const{p,a}=make('CHAR-174'),d=a.source!.living as any,bandage=a.instances.map(i=>p.assets[i.assetId]).find(a=>(a.source?.retainedAuthorSource as any)?.kind==='author-patient-wrap-fit')!,fit=bandage.source!.retainedAuthorSource as any,old=p.assets[String(bandage.source!.sourceAssetId)];assert.equal(d.bodyFit,'adultA');assert.equal(d.clothing,'CHAR-124');assert.equal(d.contacts.length,10);assert.equal(d.omitted.length,1);assert.equal(old.source!.catalogId,'CHAR-145');same(bandage.ports,old.ports);same(bandage.rig!.sockets,old.rig!.sockets);assert.ok(fit.minimumClampMove.length>0);assert.ok(fit.minimumClampMove.every((r:any)=>r.to[2]===r.from[2]-1&&r.to[0]===r.from[0]&&r.to[1]===r.from[1]));assert.equal(fit.contacts.length,10);assert.notEqual(outfitHash(bandage.chunks),outfitHash(old.chunks));assert.ok(Object.values(p.assets).some(a=>a.source?.catalogId==='CHAR-059'));});

test('M059 first-person actual hand triangles leave the centre clear and never invent inventory props',()=>{let count=0;for(const{p,a}of forms()){const q=livingViewAudit(p,a);if(!q)continue;assert.equal(a.instances.length,1);assert.equal(q.heldObjects,0);assert.equal(q.centerHits,0);assert.ok(q.visibleHandFraction>.08&&q.visibleHandFraction<.12);assert.ok(q.maxZ<-.05);assert.equal(a.source!.inventoryBound,false);count++;}assert.equal(count,4);});

test('M059 player observer exactly shares NPC components and first-person sleeves share actual113 material purposes',()=>{const observer=make('CHAR-176',{view:'observer'}),d=observer.a.source!.living as any;assert.equal(d.sharedBodyCatalogId,'CHAR-001');assert.equal(d.thirdPersonGameplay,false);same(observer.a.instances.map(i=>({assetId:i.assetId,position:i.position,rotation:i.rotation})),d.retainedNPCAssembly.instances.map((i:any)=>({assetId:i.assetId,position:i.position,rotation:i.rotation})));for(const view of['first-person-open','first-person-grip']){const{p,a}=make('CHAR-176',{view}),hands=p.assets[a.instances[0].assetId],old=p.assets[String(hands.source!.sourceAssetId)],s=p.styles.yunshan;same(hands.chunks,old.chunks);same(hands.rig,old.rig);same(hands.ports,old.ports);for(let j=0;j<hands.meshes!.length;j++){const m=hands.meshes![j],source=old.meshes![j];same({...m,material:source.material},source);assert.equal(m.material,source.material===s.characterCloth?s.garmentLight:source.material===s.characterLining?s.garmentLining:source.material);}assert.ok((a.source!.living as any).retainedNPCAssembly.instances.length>1);}});

test('M059 pet and livestock groups preserve independent species and explicit unbound age, ownership and media',()=>{for(const wear of['collars','harnesses']){const{p,a}=make('CHAR-332',{wear}),d=a.source!.living as any;same(d.animals.map((r:any)=>r.species),['cat','dog','rabbit']);assert.equal(d.rabbitHarness,false);assert.equal(d.animals[2].kind,'collar');assert.equal(d.tagInstalled,false);for(const r of d.animals)assert.equal(outfitHash(geometryData(p.assets[r.sourceBody])),r.sourceBodyGeometrySHA256);}for(const id of['CHAR-333','CHAR-334'])for(const params of livingVariants(id)){const{p,a}=make(id,params),d=a.source!.living as any;assert.equal(d.ageHealthProductionBound,false);assert.equal(d.ecologyBound,false);for(const r of d.animals){assert.equal(outfitHash(geometryData(p.assets[r.assetId])),r.geometrySHA256);assert.ok(r.age.includes('no age-state'));assert.ok(r.health.includes('unspecified'));}}});

test('M059 public creation preserves foreign material IDs and invalid parameters roll back completely with one undo',()=>{const p=newProject();p.catalog={sourceName:'catalog',importedAt:'test',entries:structuredClone(catalog)};p.materials[74]={...p.materials[1],id:74,name:'foreign-74'};const e=new Engine(p);commit(e,[{op:'produceCatalogAssembly',catalogId:'CHAR-332',id:'pets',place:true,params:{wear:'harnesses'}}]);assert.equal(e.project.materials[74].name,'foreign-74');assert.equal(Object.keys(e.project.styles.yunshan).length,512);for(const[id,params]of [['CHAR-174',{bodyFit:'baby'}],['CHAR-175',{inventory:'lantern'}],['CHAR-176',{view:'third-person-game'}],['CHAR-332',{wear:'rabbit-harness'}],['CHAR-333',{group:'newborn'}],['CHAR-334',{habitat:'air'}]]as[string,Record<string,string>][]){const before=outfitHash(e.project);assert.throws(()=>commit(e,[{op:'material',id:e.project.styles.yunshan.petWebbing,properties:{color:'#ff0000'}},{op:'produceCatalogAssembly',catalogId:id,id:'invalid',params}]));assert.equal(outfitHash(e.project),before);}commit(e,[{op:'undo'}]);for(const k of['assets','instances','assemblies','materials','styles']as const)same(e.project[k],p[k]);});

test('M059 component metadata agrees across documents, and public turns and palettes preserve geometry and undo',()=>{const seen=new Map<string,string>();for(const{p}of forms())for(const asset of Object.values(p.assets)){const hash=outfitHash(asset);if(seen.has(asset.id))assert.equal(hash,seen.get(asset.id),'Shared component conflict '+asset.id);else seen.set(asset.id,hash);}const{p,a}=make('CHAR-174'),e=new Engine(p);commit(e,[{op:'instantiateAssembly',assemblyId:a.id,prefix:'quarter',position:[4,0,4],rotation:1}]);same(e.project.assets,p.assets);for(const i of a.instances)same(e.project.instances['quarter-'+i.id].position,rotateY(i.position,1).map((v,k)=>v+[4,0,4][k]));commit(e,[{op:'undo'}]);same(e.project.instances,p.instances);commit(e,[...referenceFinishCommands(p),{op:'palette',name:'参考材质试作'}]);for(const k of['assets','instances','assemblies','styles']as const)same(e.project[k],p[k]);commit(e,[{op:'undo'}]);same(e.project.materials,p.materials);});
