import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';
import{Engine,validateProject}from'../src/core/engine';import{newProject}from'../src/core/materials';import{Grid}from'../src/core/grid';import{geometryData}from'../src/core/sky';import{rotateY,type Project,type Assembly,type Command}from'../src/core/types';import{productionProject}from'../src/production/style';import{parseCatalogCSV}from'../src/core/catalog';import{makeArchitectureAssembly,professionAssemblyIds}from'../src/production/atlas-architecture-assemblies';import{makeCatalogAsset}from'../src/production/catalog-assets';import{outfitHash}from'../src/production/outfit-components';import{referenceFinishCommands}from'../src/production/reference-finish';import{architectureClosed,architectureComponents}from'../scripts/lib/architecture-audit';import{nativeIslandAttachments}from'../src/production/mixed-review';import{professionAudit}from'../scripts/lib/profession-audit';
const catalog=Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r])),cache=new Map<string,{p:Project;a:Assembly}>();function make(id:string){if(!cache.has(id)){const p=productionProject(id);p.catalog={sourceName:'catalog',importedAt:'test',entries:structuredClone(catalog)};const a=makeArchitectureAssembly(p,id,id.toLowerCase(),id);p.assemblies={[a.id]:a};p.instances=Object.fromEntries(a.instances.map(i=>[i.id,i]));validateProject(p);cache.set(id,{p,a});}return cache.get(id)!;}const commit=(e:Engine,commands:Command[])=>{const req={expectedVersion:e.project.version,requestId:crypto.randomUUID(),commands},dry=e.execute({...req,dryRun:true});return e.execute({...req,previewToken:dry.previewToken});};

test('M058 complete reusable outfits retain closed oriented surfaces, attached native parts and valid actual rigs',()=>{assert.equal(professionAssemblyIds.length,12);for(const id of professionAssemblyIds){const{p,a}=make(id);assert.equal(a.source!.notCatalogBase,true);for(const asset of Object.values(p.assets))if(asset.meshes?.length){assert.ok(architectureClosed(asset).every(r=>r.closed&&r.oriented),id+' '+asset.id);assert.ok(nativeIslandAttachments({...asset,meshes:architectureComponents(asset)}).every(r=>r.attached),id+' '+asset.id);}}});

test('M058 every whole posed wearer clears actual triangle pairs and retains genuine declared attachment contacts',()=>{let pairs=0,contacts=0;for(const id of professionAssemblyIds){const{p,a}=make(id),q=professionAudit(p,a);assert.ok(q.pairs.every(r=>r.contained===0&&r.crossing===0),id);assert.ok(q.contactsPassed,id+' '+JSON.stringify(q.contacts));assert.ok(q.shoeGroundPassed&&q.rigsRetained&&q.nonphysical,id);assert.ok(Math.abs(q.minY)<1e-8);pairs+=q.pairs.length;contacts+=q.contacts.length;}assert.ok(pairs>450&&contacts>=16);});

test('M058 every canonical source and fitting edge is exact, with explicit native move/removal maps',()=>{let canonical=0,moved=0,removed=0;for(const id of professionAssemblyIds){const{p}=make(id);for(const a of Object.values(p.assets)){if(a.source?.kind==='catalog-recipe'){const source=makeCatalogAsset(String(a.source.catalogId),a.name,a.id,p.styles.yunshan,a.source.parameters as any);assert.deepEqual(geometryData(a),geometryData(source));for(const k of['origin','cellSize','ports','openings','parts']as const)assert.deepEqual(a[k],source[k]);canonical++;}if(a.source?.sourceAssetId){const parent=p.assets[String(a.source.sourceAssetId)];assert.ok(parent);assert.equal(a.source.sourceGeometrySHA256,outfitHash(geometryData(parent)));const fit=a.source.retainedAuthorSource as any;if(fit?.preservedNativeCells)assert.deepEqual(a.chunks,parent.chunks);if(fit?.nativeMoves||fit?.removedNativeCells){const old=new Grid(parent.chunks),next=new Grid(a.chunks),moves=new Map((fit.nativeMoves??[]).map((r:any)=>[r.from.join(','),r])),removals=new Map((fit.removedNativeCells??[]).map((r:any)=>[r.cell.join(','),r]));assert.equal(next.count,old.count-removals.size);for(const[cell,material]of old.cells()){if(removals.has(cell.join(','))){assert.equal(next.get(cell),0);removed++;}else{const m=moves.get(cell.join(','))as any;assert.equal(next.get(m?m.to:cell),material);if(m)moved++;}}}}}}assert.ok(canonical>100&&moved>0&&removed>0);});

test('M058 student uses actual independent school-child sources and an explicit child-frame trouser derivative',()=>{const{p,a}=make('CHAR-165'),o=a.source!.profession as any,source=(id:string)=>Object.values(p.assets).find(a=>a.source?.catalogId===id)!;assert.equal(o.bodyFit,'child');assert.ok(source('CHAR-063'));assert.equal(source('CHAR-059'),undefined);assert.equal((source('CHAR-068').source!.parameters as any).headStage,'school');for(const id of['CHAR-070','CHAR-071'])assert.equal((source(id).source!.parameters as any).limbFit,'child');assert.ok(source('CHAR-123'));const pants=Object.values(p.assets).find(a=>(a.source?.retainedAuthorSource as any)?.kind==='author-child-hollow-pants')!;assert.ok(pants);assert.ok((pants.source!.baseCatalogIds as string[]).includes('CHAR-063'));assert.equal(source('CHAR-118'),undefined);assert.ok(professionAudit(p,a).maxY<1.35);});

test('M058 chef retains original service apron but omits only covered duplicate parts and their native catches',()=>{const{p}=make('CHAR-169'),derived=Object.values(p.assets).find(a=>(a.source?.retainedAuthorSource as any)?.removedNativeCells)!,old=p.assets[String(derived.source!.sourceAssetId)],fit=derived.source!.retainedAuthorSource as any;assert.ok(old.meshes!.some(m=>m.name==='服务衣独立围腰'));assert.ok(derived.meshes!.every(m=>m.name!=='服务衣独立围腰'&&!m.name.startsWith('围裙工具袋')));assert.equal(fit.removedParts.length,2);assert.ok(fit.removedParts.every((r:any)=>r.name.startsWith('围裙工具袋')));assert.ok(derived.parts.some(p=>p.name==='身份扣塑料底板'));assert.ok(Object.values(p.assets).some(a=>a.source?.catalogId==='CHAR-136'));});

test('M058 engineer and logistics contracts share one tool-belt geometry with retained canonical shoulder rest',()=>{const configurations=(id:string)=>{const{p,a}=make(id),o=a.source!.profession as any;assert.equal(o.shoulderRestDegrees,24);assert.ok(o.sharedGeometryFamily);assert.equal(a.source!.ageSeedRoleBinding,false);const original=Object.values(p.assets).find(a=>a.source?.catalogId==='CHAR-130')!,posed=a.instances.map(i=>p.assets[i.assetId]).find(a=>(a.source?.retainedAuthorSource as any)?.shoulderAngleDegrees===24&&(a.source!.baseCatalogIds as string[]).includes('CHAR-130'))!;assert.ok(posed);assert.notDeepEqual(posed.rig!.pose['shoulder1'],original.rig!.pose['shoulder1']);return a.instances.map(i=>({geometry:geometryData(p.assets[i.assetId]),position:i.position,rotation:i.rotation}));};assert.deepEqual(configurations('CHAR-168'),configurations('CHAR-170'));});

test('M058 public school creation preserves foreign IDs and invalid variants roll back with one undo',()=>{const p=newProject();p.catalog={sourceName:'catalog',importedAt:'test',entries:structuredClone(catalog)};p.materials[74]={...p.materials[1],id:74,name:'foreign-74'};const e=new Engine(p);commit(e,[{op:'produceCatalogAssembly',catalogId:'CHAR-165',id:'student',place:true}]);assert.equal(e.project.materials[74].name,'foreign-74');assert.equal(Object.keys(e.project.styles.yunshan).length,512);const before=outfitHash(e.project);assert.throws(()=>commit(e,[{op:'material',id:e.project.styles.yunshan.schoolCloth,properties:{color:'#ff0000'}},{op:'produceCatalogAssembly',catalogId:'CHAR-165',id:'wrong-age',params:{bodyFit:'adultA'}}]));assert.equal(outfitHash(e.project),before);commit(e,[{op:'undo'}]);for(const k of['assets','instances','assemblies','materials','styles']as const)assert.deepEqual(e.project[k],p[k]);});

test('M058 actual public quarter turns and role palettes preserve complete native and continuous authority',()=>{for(const id of professionAssemblyIds){const{p,a}=make(id),e=new Engine(p),before=outfitHash(p.assets);commit(e,[{op:'instantiateAssembly',assemblyId:a.id,prefix:'quarter',position:[4,0,4],rotation:1}]);assert.equal(outfitHash(e.project.assets),before);for(const i of a.instances)assert.deepEqual(e.project.instances['quarter-'+i.id].position,rotateY(i.position,1).map((v,k)=>v+[4,0,4][k]));commit(e,[{op:'undo'}]);assert.deepEqual(e.project.instances,p.instances);}const{p}=make('CHAR-162'),e=new Engine(p);commit(e,[...referenceFinishCommands(p),{op:'palette',name:'参考材质试作'}]);for(const k of['assets','instances','assemblies','styles']as const)assert.deepEqual(e.project[k],p[k]);assert.equal(Object.keys(e.project.palettes['参考材质试作']).length,512);commit(e,[{op:'undo'}]);assert.deepEqual(e.project.materials,p.materials);});

test('M058 independently produced documents agree on shared component metadata and eleven distinct configurations',()=>{const seen=new Map<string,unknown>(),configurations=new Set<string>();for(const id of professionAssemblyIds){const{p,a}=make(id);for(const asset of Object.values(p.assets)){if(seen.has(asset.id))assert.deepEqual(asset,seen.get(asset.id),'Shared component conflict '+asset.id);else seen.set(asset.id,asset);}configurations.add(outfitHash(a.instances.map(i=>({geometry:geometryData(p.assets[i.assetId]),position:i.position,rotation:i.rotation}))));}assert.equal(configurations.size,11);});
