import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createHash} from 'node:crypto';
import {NodeIO} from '@gltf-transform/core';
import {KHRMaterialsEmissiveStrength} from '@gltf-transform/extensions';
import {productionProject} from '../src/production/style';
import {makeCatalogAsset} from '../src/production/catalog-assets';
import {vesselRecipes,vesselVariants,selectVesselRecipe} from '../src/production/atlas-vessels';
import {builtWidthParameter} from '../src/production/atlas-built';
import * as assembly from '../src/production/vessel-assembly';
import {newProject} from '../src/core/materials';
import {referenceFinishCommands} from '../src/production/reference-finish';
import {Engine,validateProject} from '../src/core/engine';
import {Grid} from '../src/core/grid';
import {checkGeometry,gridComponents} from '../src/core/checks';
import {parseCatalogCSV} from '../src/core/catalog';
import {exportProject} from '../src/export/exporter';
import {eachCell,rotateY,type Asset,type Command,type Project,type V3} from '../src/core/types';
const p=productionProject('M025'),s=p.styles.yunshan,cache=new Map<string,{a:Asset;g:Grid}>();
const model=(id:string,component?:string)=>{const key=id+':'+(component??'default');if(!cache.has(key)){const a=makeCatalogAsset(id,id,id.toLowerCase(),s,component?{component}:{});cache.set(key,{a,g:new Grid(a.chunks)});}return cache.get(key)!;};
const at=(id:string,v:V3,component?:string)=>{const {a,g}=model(id,component);return g.get(v.map(x=>Math.floor((x+1e-8)/a.cellSize)) as V3);};
const commit=(e:Engine,commands:Command[])=>{const req={expectedVersion:e.project.version,requestId:crypto.randomUUID(),commands},dry=e.execute({...req,dryRun:true});return e.execute({...req,previewToken:dry.previewToken});};
const catalogue=Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]));
function doc(name:string){const p=productionProject(name);p.catalog={sourceName:'city-assets.csv',importedAt:'test',entries:structuredClone(catalogue)};return p;}
function clean(c:ReturnType<typeof checkGeometry>){for(const k of['unsupported','collisions','gaps','warnings']as const)assert.deepEqual(c[k],[],k);assert.ok(c.openings.every(o=>!o.ownSolidCells&&!o.blockedBy.length),JSON.stringify(c.openings));assert.ok(c.clearances.every(o=>o.clear),JSON.stringify(c.clearances.filter(o=>!o.clear)));}
const supportGrids=new WeakMap<Asset,Grid>();
function solidAt(p:Project,world:V3){return Object.values(p.instances).some(i=>{const a=p.assets[i.assetId],local=rotateY(world.map((v,d)=>v-i.position[d]) as V3,4-i.rotation),v=local.map((n,d)=>Math.floor((n-a.origin[d]+1e-8)/a.cellSize)) as V3,m=(supportGrids.get(a)??(supportGrids.set(a,new Grid(a.chunks)),supportGrids.get(a)!)).get(v);return !!m&&p.materials[m].solid;});}
import {meshAsset} from '../src/core/mesh';
test('M025 twelve source families and eighteen native shapes have exact dimensions, unique connected geometry, real openings and reference provenance',async()=>{
 const sha=createHash('sha256').update(await readFile('projects/reference-atlas/images/M025.png')).digest('hex'),hashes=new Set<string>();assert.equal(Object.keys(vesselRecipes).length,12);
 for(const[slot,id]of Object.keys(vesselRecipes).entries())for(const component of Object.keys(vesselVariants[id]??{default:1})){
  const c=component==='default'?undefined:component,{a,g}=model(id,c),recipe=selectVesselRecipe(id,c)!,ref=a.source!.reference as any;assert.equal(ref.sheet,'M025');assert.equal(ref.slot,slot+1);assert.equal(ref.imageSHA256,sha);assert.equal(a.source!.gameIntegration,false);assert.equal(gridComponents(g).length,1,id+component);assert.ok(g.count<1_000_000);assert.ok(a.parts.length>=5);const b=g.bounds()!;assert.ok(b.max.every((v,i)=>Math.abs((v-b.min[i])*a.cellSize-recipe.size[i])<1e-10),id+component);for(const box of a.openings)eachCell(box,v=>assert.equal(g.get(v),0,id+' '+v));const hash=createHash('sha256').update(JSON.stringify(a.chunks)).digest('hex');assert.ok(!hashes.has(hash));hashes.add(hash);if(a.source!.triangleBudget)assert.ok(meshAsset(a,p.materials).reduce((n,b)=>n+b.indices.length/3,0)<=Number(a.source!.triangleBudget));const d=doc(id);d.assets[a.id]=a;validateProject(d);
 }assert.equal(hashes.size,18);
});
const probes:[string,V3,string,string?][]=[['BUILT-289',[.1,.55,.15],'railWheel'],['BUILT-289',[.925,.275,.425],'maglevCoil','maglevBase'],['BUILT-290',[1.1,.5,.5],'metal'],['BUILT-291',[.05,1.4,3],'marineHull'],['BUILT-291',[3,.1,3],'marineAntifouling'],['BUILT-291',[.05,1.05,3],'printedMark'],['BUILT-292',[.15,.5,3],'glass'],['BUILT-293',[.225,.175,1],'printedWarning'],['BUILT-294',[.05,.6,.05],'rubber'],['BUILT-295',[.05,.35,1.65],'navPortLamp'],['BUILT-295',[6.95,.35,1.65],'navStarboardLamp','starboardWing'],['BUILT-296',[.8,1.575,.3],'aircraftSkin'],['BUILT-297',[3,.2,1],'metal'],['BUILT-300',[.9,.475,.6],'mooringLine'],['BUILT-300',[1,.4,.05],'dockFender','fender'],['BUILT-307',[1,1.95,4.3],'bridgeBearing'],['BUILT-308',[2.5,1,.95],'jointSeal']];
test('native coordinates distinguish steel wheels, rubber tires, coils, marine coatings, rope, fender and unbound navigation roles',()=>{
 for(const[id,v,r,c]of probes)assert.equal(at(id,v,c),s[r],id+' '+r+' '+v);for(const r of['navPortLamp','navStarboardLamp']){assert.equal(p.materials[s[r]].intensity,0);assert.equal(p.materials[s[r]].solid,false);}assert.equal(p.materials[s.mooringLine].solid,false);assert.equal(p.materials[s.railWheel].category,'metal');assert.equal(p.materials[s.dockFender].category,'rubber');assert.notEqual(s.dockFender,s.rubber);assert.notEqual(s.navPortLamp,s.signalStopLamp);
});
test('verified modes are recipe-specific; rebuild keeps origin and supports atomic rollback and one undo',()=>{
 assert.deepEqual((builtWidthParameter('BUILT-294') as any).component.enum,['gearDeployed','gearCompressed','gearRetracted']);const e=new Engine(doc('variants'));commit(e,[{op:'produceCatalogAsset',catalogId:'BUILT-289',id:'base'},{op:'metadata',assetId:'base',origin:[.05,0,0]}]);const before=structuredClone(e.project.assets.base);commit(e,[{op:'rebuildCatalogAsset',assetId:'base',params:{component:'maglevBase'}}]);assert.equal(e.project.assets.base.source!.component,'maglevBase');assert.deepEqual(e.project.assets.base.origin,before.origin);commit(e,[{op:'undo'}]);assert.deepEqual({...e.project.assets.base,version:before.version},before);
 for(const[catalogId,component]of[['BUILT-289','gearDeployed'],['BUILT-294','maglevBase'],['BUILT-291','portWing'],['BUILT-295','horizontalTail']]){const snapshot=structuredClone(e.project);assert.throws(()=>commit(e,[{op:'produceCatalogAsset',catalogId,id:'bad',params:{component}}]));assert.deepEqual(e.project,snapshot);}
});
test('steel wheel treads contact real rails and distinct U-guides preserve 0.1m gaps with explicit inspection supports',()=>{
 for(const[name,fn,clear]of[assembly.vesselScenarios[0],assembly.vesselScenarios[1]]){const e=new Engine(doc(name));commit(e,fn(s));const c=checkGeometry(e.project,clear);clean(c);assert.equal(c.contacts['car-1'].length,2);if(name==='rail'){for(const x of[.1,2.9])for(const z of[.6,2.6,7.4,9.4]){assert.ok(solidAt(e.project,[x,.225,z]));assert.ok(solidAt(e.project,[x,.275,z]));}assert.equal((e.project.assets.bogie.source!.guide as any).mode,'wheel-rail');}else{assert.equal((e.project.assets.base.source!.guide as any).airGapM,.1);assert.equal((e.project.assets.base.source!.guide as any).levitationImplemented,false);assert.ok(![...new Grid(e.project.assets.base.chunks).cells()].some(([,m])=>m===s.railWheel));for(const x of[1.05,1.95])assert.equal(solidAt(e.project,[x,.9,1]),false);}}
});
test('cables pass through real clamp bores and carry a supported cabin roof without entering body clearance',()=>{
 const e=new Engine(doc('cable'));commit(e,assembly.vesselCableCommands(s));const c=checkGeometry(e.project,assembly.vesselCableClearances);clean(c);assert.ok(c.contacts['hanger-1'].includes('rig-1'));assert.ok(c.contacts['cabin-1'].includes('hanger-1'));for(const x of[.4,2]){assert.equal(at('BUILT-290',[x,2.6,.6]),0);assert.ok(solidAt(e.project,[x,5.925,.6]));assert.ok(solidAt(e.project,[x,5.975,.6]));}assert.equal(assembly.authoredCableRoute.originalRouteBound,false);assert.ok(solidAt(e.project,[.8,3.375,.6]));assert.ok(solidAt(e.project,[.8,3.425,.6]));
});
function exteriorVoid(g:Grid){const b=g.bounds()!,min=b.min.map(n=>n-1),max=b.max.map(n=>n+1),key=(v:number[])=>v.join(','),seen=new Set<string>([key(min)]),q=[min];for(let i=0;i<q.length;i++)for(let d=0;d<3;d++)for(const sign of[-1,1]){const v=[...q[i]];v[d]+=sign;const k=key(v);if(v.some((n,j)=>n<min[j]||n>=max[j])||seen.has(k)||g.get(v as V3))continue;seen.add(k);q.push(v);}return seen;}
test('closed hull excludes exterior flood fill; actual waterline, boarding gap, fixed landing and fenders align without changing public access state',()=>{
 const {g}=model('BUILT-291');assert.equal(g.get([30,8,30]),0);assert.equal(exteriorVoid(g).has('30,8,30'),false);const e=new Engine(doc('ferry'));commit(e,assembly.vesselFerryCommands(s));clean(checkGeometry(e.project,assembly.vesselFerryClearances));for(const x of[5.95,6.05,6.65,9.95,10.05])assert.ok(solidAt(e.project,[x,2.175,5]));for(const x of[5.95,6.025,6.575,6.625])assert.ok(solidAt(e.project,[x,1.6,2]));assert.equal((e.project.assets.hull.source!.hull as any).waterlineYM+e.project.instances['hull-1'].position[1],1.2);assert.equal((e.project.assets.gangway.source!.boarding as any).stoppedStateBound,false);assert.equal((e.project.assets.bollard.source!.dock as any).ropeAttachedToShip,false);
});
const portWorld=(p:Project,i:string,id:string)=>{const inst=p.instances[i],port=p.assets[inst.assetId].ports.find(p=>p.id===id)!;return rotateY(port.position,inst.rotation).map((v,d)=>v+inst.position[d]);};
test('18m authored wings carry engines through real slots; left/right navigation, hollow ducts and horizontal/vertical tails remain separate',()=>{
 const e=new Engine(doc('airliner'));commit(e,assembly.vesselAirlinerCommands(s));const c=checkGeometry(e.project,assembly.vesselAirlinerClearances);clean(c);for(const side of['left','right']){assert.ok(c.contacts['engine-'+side].includes('wing-'+side));const a=portWorld(e.project,'wing-'+side,'engine'),b=portWorld(e.project,'engine-'+side,'wing');assert.ok(a.every((v,i)=>Math.abs(v-b[i])<1e-8));}assert.ok(c.contacts['fin-1'].includes('tail-1'));assert.equal(assembly.authoredAirliner.wingSpanM,18);assert.equal(assembly.authoredAirliner.legacy17mProxyUsed,false);for(const[x,component]of[[3.8,'portWing'],[3.2,'starboardWing']]as const)assert.equal(at('BUILT-295',[x,.2,1.8],component),0);for(const z of[.1,3.1])assert.equal(at('BUILT-296',[.8,.8,z]),0);assert.equal((e.project.assets.engine.source!.engine as any).smokeIncluded,false);
});
test('gear compression keeps both tires unchanged and retraction is an exact rigid quarter-turn, while all three poses have real supports',()=>{
 const a=model('BUILT-294','gearDeployed'),b=model('BUILT-294','gearCompressed'),c=model('BUILT-294','gearRetracted');assert.equal(a.g.count,c.g.count);for(const[v,m]of a.g.cells()){assert.equal(c.g.get([v[0],v[2],48-v[1]-1]),m);if(m===s.rubber)assert.equal(b.g.get(v),m);}assert.equal((b.a.source!.gear as any).compressionM,.4);for(const[name,fn,clear]of[assembly.vesselScenarios[5],assembly.vesselScenarios[6]]){const e=new Engine(doc(name));commit(e,fn(s));clean(checkGeometry(e.project,clear));assert.equal((e.project.assets.gear.source!.gear as any).flightStateBound,false);}
});
test('shore abutment follows all three terrain bands and actual bearing stack carries the common bridge surface with full-body clearance',()=>{
 const e=new Engine(doc('bridge'));commit(e,assembly.vesselBridgeCommands(s));const c=checkGeometry(e.project,assembly.vesselBridgeClearances);clean(c);assert.ok(c.contacts['span-1'].includes('abutment-1'));assert.ok(c.contacts['span-1'].includes('bearing-1'));for(let i=0;i<3;i++){const y=.2+i*.4;assert.ok(solidAt(e.project,[3,y-.05,i*1.6+.8]));assert.ok(solidAt(e.project,[3,y+.05,i*1.6+.8]));}for(let z=-10;z<130;z++)for(let x=-3;x<=3;x++)assert.ok(solidAt(e.project,[3+x*.1,2.55,z*.1]));assert.equal((e.project.assets.abutment.source!.abutment as any).terrainOriginal,false);assert.equal((e.project.assets.bearing.source!.bearing as any).structuralAnalysis,false);
});
test('new surface roles survive palette and GLB/native export, respect occupied 174–181 slots, and undo or roll back atomically',async()=>{
 const foreign=newProject();foreign.catalog={sourceName:'city-assets.csv',importedAt:'test',entries:structuredClone(catalogue)};for(let id=174;id<=181;id++)foreign.materials[id]={...foreign.materials[1],id,name:'foreign '+id};const e=new Engine(foreign),initial=structuredClone(e.project),commands:Command[]=[{op:'produceCatalogAsset',catalogId:'BUILT-291',id:'hull'},{op:'produceCatalogAsset',catalogId:'BUILT-295',id:'wing'}];assert.throws(()=>commit(e,[...commands,{op:'produceCatalogAsset',catalogId:'BUILT-294',id:'bad',params:{component:'portWing'}}]));assert.deepEqual(e.project,initial);commit(e,commands);for(let id=174;id<=181;id++)assert.deepEqual(e.project.materials[id],initial.materials[id]);assert.notEqual(e.project.styles.yunshan.marineHull,174);commit(e,[{op:'undo'}]);for(const k of['assets','styles','materials']as const)assert.deepEqual(e.project[k],initial[k]);commit(e,commands);commit(e,referenceFinishCommands(e.project));const before=structuredClone(e.project);commit(e,[{op:'palette',name:'参考材质试作'}]);assert.deepEqual(e.project.assets,before.assets);assert.deepEqual(e.project.styles,before.styles);for(const[id,m]of Object.entries(before.materials)){assert.equal(e.project.materials[id].category,m.category);assert.equal(e.project.materials[id].solid,m.solid);}assert.equal(e.project.materials[e.project.styles.yunshan.navPortLamp].intensity,0);
 const dir=await mkdtemp(path.join(os.tmpdir(),'m025-export-'));try{const ex=await exportProject(e.project,dir),round=JSON.parse(await readFile(path.join(ex.directory,'voxels.ysvox.json'),'utf8'));validateProject(round);assert.deepEqual(round.assets,e.project.assets);assert.deepEqual(round.materials,e.project.materials);const glb=await new NodeIO().registerExtensions([KHRMaterialsEmissiveStrength]).read(path.join(ex.directory,'visual.glb'));for(const role of['marineHull','marineAntifouling','navPortLamp'])assert.ok(glb.getRoot().listMaterials().some(m=>(m.getExtras().materialRoles as string[]).includes('yunshan.'+role)));}finally{await rm(dir,{recursive:true,force:true});}commit(e,[{op:'undo'}]);assert.deepEqual(e.project.materials,before.materials);
});
