import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {ArchitectureBuilder} from '../src/production/architecture-near-assembly';import {thinCanopy} from '../src/production/district-components';
import {productionProject} from '../src/production/style';import {makeArchitectureAssembly,districtAssemblyIds} from '../src/production/atlas-architecture-assemblies';import {parseCatalogCSV} from '../src/core/catalog';import {Engine,validateProject} from '../src/core/engine';import {Grid} from '../src/core/grid';import {architectureClosed,architectureComponents,architecturePointRoles} from '../scripts/lib/architecture-audit';import {nativeIslandAttachments} from '../src/production/mixed-review';import {CivicAudit,civicSupports,civicStairClearance,civicFloorOpenings} from '../scripts/lib/civic-audit';import {districtClearance} from '../scripts/lib/district-audit';import {referenceFinishCommands} from '../src/production/reference-finish';import type {Project,Command} from '../src/core/types';
const entries=Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(e=>[e.id,e])),cache=new Map<string,Project>();
function model(id:string){if(!cache.has(id)){const p=productionProject(id);p.catalog={sourceName:'catalog',importedAt:'test',entries:structuredClone(entries)};const a=makeArchitectureAssembly(p,id,id.toLowerCase(),id);p.assemblies={[a.id]:a};p.instances=Object.fromEntries(a.instances.map(i=>[i.id,i]));validateProject(p);cache.set(id,p);}return cache.get(id)!;}
const commit=(e:Engine,commands:Command[])=>{const r={expectedVersion:e.project.version,requestId:crypto.randomUUID(),commands},d=e.execute({...r,dryRun:true});return e.execute({...r,previewToken:d.previewToken});};
test('M047 twelve assemblies have closed continuous solids, area UVs and attached minimum native components',()=>{assert.equal(districtAssemblyIds.length,12);for(const id of districtAssemblyIds){const p=model(id);for(const a of Object.values(p.assets)){assert.ok(architectureClosed(a).every(r=>r.closed&&r.oriented),a.id);assert.ok(nativeIslandAttachments({...a,meshes:architectureComponents(a)}).every(r=>r.attached),a.id);for(const m of a.meshes??[])for(let k=0;k<m.indices.length;k+=3){const[a,b,c]=m.indices.slice(k,k+3).map(i=>m.uvs.slice(i*2,i*2+2));assert.ok(Math.abs((b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]))>1e-12,id+' UV');}for(const[,mat]of new Grid(a.chunks).cells())assert.equal(mat,p.styles.yunshan.architecturePin);}}});
test('M047 actual doors, floors, stairs, columns, skylights and metre-space routes remain clear and supported',()=>{for(const id of districtAssemblyIds){const p=model(id),a=Object.values(p.assemblies!)[0],q=new CivicAudit(p,a),supports=civicSupports(q),stairs=civicStairClearance(q),holes=civicFloorOpenings(q),r=districtClearance(q);assert.ok(supports.every(r=>r.supported),id+JSON.stringify(supports.filter(r=>!r.supported)));assert.ok(stairs.every(r=>r.clear),id+JSON.stringify(stairs.filter(r=>!r.clear)));assert.ok(holes.every(r=>r.clear),id+' floor holes');assert.ok(r.checks.every(r=>r.clear),id+JSON.stringify(r.checks.filter(r=>!r.clear)));assert.ok(r.contacts.every(r=>r.supported),id+JSON.stringify(r.contacts.filter(r=>!r.supported)));}});
test('M047 source dimensions, proposed uses and unbound source-runtime constraints are explicit',()=>{const s=(id:string)=>Object.values(model(id).assemblies!)[0].source as any;assert.equal(s('BUILT-229').houseCount,5);assert.equal(s('BUILT-227').houseCount,3);assert.equal(s('BUILT-228').chamfer.angleDegrees,45);assert.equal(s('BUILT-224').bridge.walkY,12.6);assert.ok(s('BUILT-236').canopy.clearWidth>=3);assert.equal(s('BUILT-236').canopy.beamDepth,.3);assert.equal(s('BUILT-237').internalFurnitureIncluded,false);assert.equal(s('BUILT-239').energyBoundary.energized,false);assert.equal(s('BUILT-239').originalWorldPhysicsModified,false);assert.equal(s('BUILT-265').originalAirportRetained,true);assert.equal(s('BUILT-231').governmentHallRelabelled,false);for(const id of districtAssemblyIds)assert.equal(s(id).originalRuntimeBound,false);assert.throws(()=>makeArchitectureAssembly(productionProject('bad'),'BUILT-239','bad','bad',{levitating:1}));});
test('M047 actual metal, insulation, winding and glass roles survive palette replacement with one undo',()=>{for(const[id,key,point,role]of[['BUILT-239','magnetic-test-core',[0,1,0],'magneticCore'],['BUILT-239','magnetic-test-core',[0,.40,0],'coilInsulator'],['BUILT-239','magnetic-test-core',[.72,.65,0],'maglevCoil'],['BUILT-236','district-thin-canopy',[0,.255,0],'architecturalCladding'],['BUILT-237','roof-mechanical-shell',[-1.5,1.75,-1.51],'architectureOptic']]as const){const p=model(id),asset=Object.values(p.assets).find(a=>a.id.includes(key))!;assert.ok(architecturePointRoles(p,asset,[...point]).includes(p.styles.yunshan[role]),id+' '+role);const e=new Engine(structuredClone(p));commit(e,referenceFinishCommands(e.project));const before=structuredClone(e.project);commit(e,[{op:'palette',name:'参考材质试作'}]);assert.deepEqual(e.project.assets,before.assets);assert.deepEqual(e.project.assemblies,before.assemblies);commit(e,[{op:'undo'}]);assert.deepEqual(e.project.materials,before.materials);}});
test('M047 all templates can be quarter-turned through public instantiation and undone without changing geometry',()=>{for(const id of districtAssemblyIds){const p=model(id),e=new Engine(structuredClone(p)),a=Object.values(p.assemblies!)[0];commit(e,[{op:'instantiateAssembly',assemblyId:a.id,prefix:'turned',position:[2000,0,0],rotation:1}]);assert.equal(Object.keys(e.project.instances).length,a.instances.length*2);assert.deepEqual(e.project.assets,p.assets);commit(e,[{op:'undo'}]);assert.deepEqual(e.project.instances,p.instances);assert.deepEqual(e.project.assemblies,p.assemblies);}});

test('M047 differently spaced canopy columns keep distinct matching rafter assets',()=>{const p=productionProject('spacing'),b=new ArchitectureBuilder(p,'spacing');const first=thinCanopy(b,20,5,[0,0,0],[-9,0,9]),second=thinCanopy(b,20,5,[30,0,0],[-9,-4.5,0,4.5,9]);const a=p.assets[b.instances.find(i=>i.id===first.instanceIds[0])!.assetId],c=p.assets[b.instances.find(i=>i.id===second.instanceIds[0])!.assetId];assert.notEqual(a.id,c.id);assert.ok(c.meshes!.reduce((n,m)=>n+m.indices.length,0)>a.meshes!.reduce((n,m)=>n+m.indices.length,0));assert.equal(new Grid(a.chunks).count,3);assert.equal(new Grid(c.chunks).count,5);});
