import test from 'node:test';import assert from 'node:assert/strict';import {readFile,mkdir,writeFile,rm} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {productionProject} from '../src/production/style';import {makeArchitectureAssembly,architectureAssemblyIds} from '../src/production/atlas-architecture-assemblies';import {architectureRoof} from '../src/production/architecture-roofs';import {architectureFloor,architectureWall} from '../src/production/architecture-components';import {architectureClosed,architectureClearance,architecturePointRoles,architectureRoofSupports} from '../scripts/lib/architecture-audit';import {geometryData} from '../src/core/sky';import {Grid} from '../src/core/grid';import {Engine,validateProject} from '../src/core/engine';import {parseCatalogCSV} from '../src/core/catalog';import {newProject} from '../src/core/materials';import {referenceFinishCommands} from '../src/production/reference-finish';import {assemblyGeometryData} from '../src/production/assembly-geometry';import {readProductionLibrary} from '../src/production/library';import type {Project,Command} from '../src/core/types';
const catalog=Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(e=>[e.id,e])),hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const project=()=>{const p=productionProject('M044');p.catalog={sourceName:'catalog',importedAt:'test',entries:structuredClone(catalog)};return p;};
const cache=new Map<string,Project>();function model(id:string,params:Record<string,string|number>={}){const key=id+JSON.stringify(params);if(!cache.has(key)){const p=project(),a=makeArchitectureAssembly(p,id,id.toLowerCase(),id,params);p.assemblies={[a.id]:a};p.instances=Object.fromEntries(a.instances.map(i=>[i.id,i]));validateProject(p);cache.set(key,p);}return cache.get(key)!;}
const commit=(e:Engine,commands:Command[])=>{const r={expectedVersion:e.project.version,requestId:crypto.randomUUID(),commands},d=e.execute({...r,dryRun:true});return e.execute({...r,previewToken:d.previewToken});};
test('M044 new solids have consistently oriented closed surfaces, true door apertures and independently assigned structural layers',()=>{
 const p=project(),s=p.styles.yunshan,f=architectureFloor(p,'f'),wall=architectureWall(p,'w','window'),door=architectureWall(p,'d','door');for(const a of[f,wall,door,architectureRoof(p,'roof','hip',12.8,6.4),architectureRoof(p,'skylight','gable',12.8,6.4,true)])assert.ok(architectureClosed(a).every(r=>r.closed&&r.oriented),a.id);
 for(const[a,point,role]of[[f,[.4,.08,.4],'structuralConcrete'],[f,[.4,.17,.4],'mortar'],[f,[.4,.19,.4],'wall'],[wall,[1.2,1.3,.12],'glass'],[wall,[1.32,1.3,.12],'wood']]as const)assert.ok(architecturePointRoles(p,a,[...point]).includes(s[role]),role);
 for(const point of [[1.6,1.3,.1],[1.6,.1,.1],[1.6,2.4,.1]]as [number,number,number][])assert.deepEqual(architecturePointRoles(p,door,point),[]);
 for(const a of[f,wall,door,architectureRoof(p,'uv-roof','hip',12.8,6.4)])for(const m of a.meshes??[])for(let k=0;k<m.indices.length;k+=3){const [a,b,c]=m.indices.slice(k,k+3).map(i=>m.uvs.slice(i*2,i*2+2));assert.ok(Math.abs((b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]))>1e-12,'UV projection must preserve actual surface area');}
 const pins=[...new Grid(f.chunks).cells()];assert.equal(pins.length,4);assert.ok(pins.every(([,id])=>id===s.architecturePin));assert.equal(p.materials[s.architecturePin].solid,false);
 const roof=architectureRoof(p,'skylight','gable',12.8,6.4,true);for(let y=.1;y<2;y+=.05)assert.deepEqual(architecturePointRoles(p,roof,[6.1,y,1.8]),[],'skylight is cut through all three layers');
});
test('six near buildings retain true repeated instances, original stairs and explicit curb-removal provenance; finite human routes and full-height courts stay clear',()=>{
 for(const id of architectureAssemblyIds.slice(0,6)){const p=model(id),a=p.assemblies![id.toLowerCase()],r=architectureClearance(p,a);assert.ok(r.every(c=>c.clear),JSON.stringify(r.filter(c=>!c.clear)));assert.ok(a.instances.length>80);assert.ok(new Set(a.instances.map(i=>i.assetId)).size<20);const original=p.assets['source-built-014'],derived=p.assets['architecture-stair-shell-side-exit'],src=derived.source!,og=new Grid(original.chunks),dg=new Grid(derived.chunks);assert.equal(src.sourceGeometrySHA256,hash(geometryData(original)));const removed=src.removedCells as {cell:[number,number,number];material:number}[];assert.equal(removed.length,1980);assert.equal(og.count-dg.count,removed.length);for(const r of removed){assert.equal(og.get(r.cell),r.material);assert.equal(dg.get(r.cell),0);}assert.equal(a.source!.originalRuntimeBound,false);}
});
test('bank and medical H layouts differ; all four wide roof alternatives regenerate actual metric geometry without becoming base masters',()=>{
 const bank=model('BUILT-023'),medical=model('BUILT-023',{program:'medical'});assert.notEqual(hash(bank.instances),hash(medical.instances));assert.ok(architectureClearance(medical,medical.assemblies!['built-023']).every(r=>r.clear));for(const id of architectureAssemblyIds.slice(8,12)){const narrow=model(id),wide=model(id,{roofWidth:'wide'});assert.notEqual(hash(assemblyGeometryData(narrow,narrow.assemblies![id.toLowerCase()])),hash(assemblyGeometryData(wide,wide.assemblies![id.toLowerCase()])));for(const p of[narrow,wide]){assert.ok(architectureRoofSupports(p,p.assemblies![id.toLowerCase()]).every(r=>r.supported),id+' column head support');for(const a of Object.values(p.assets))assert.ok(architectureClosed(a).every(r=>r.closed&&r.oriented));}}for(const params of[{roofWidth:'giant'},{program:'medical'},{layoutSeed:4}]as Record<string,string|number>[])assert.throws(()=>makeArchitectureAssembly(project(),'BUILT-075','bad','bad',params));
});
test('far structural derivatives retain separate nonphysical families and deterministic actual 24-site transforms with exclusion volumes',()=>{
 const p=model('BUILT-040');assert.equal(Object.keys(p.assets).length,6);for(const a of Object.values(p.assets)){assert.equal(new Grid(a.chunks).count,0);assert.equal(a.source!.physical,false);assert.ok(a.meshes!.every(m=>!m.collision&&!p.materials[m.material].solid));assert.ok((a.source!.sourceInstances as any[]).length>80);}
 const a=model('BUILT-042'),b=model('BUILT-042',{layoutSeed:19});assert.notEqual(hash(a.instances),hash(b.instances));for(const p of[a,b]){const assembly=p.assemblies!['built-042'],source=assembly.source!;assert.equal(assembly.instances.length,24);assert.equal(source.originalRuntimeBound,false);for(const item of source.placements as any[])for(const zone of source.exclusion as any[])assert.ok(item.bounds.max[0]<=zone.min[0]||item.bounds.min[0]>=zone.max[0]||item.bounds.max[2]<=zone.min[2]||item.bounds.min[2]>=zone.max[2]);const repeat=makeArchitectureAssembly(structuredClone(p),'BUILT-042','built-042','BUILT-042',source.parameters as any);assert.deepEqual(repeat.instances,assembly.instances);}
});
test('assembly transaction preserves foreign role IDs, rejects wrong types, rolls back, applies once, rotates real instances and undoes together',()=>{
 const p=newProject();p.catalog={sourceName:'catalog',importedAt:'test',entries:structuredClone(catalog)};for(let id=503;id<=517;id++)p.materials[id]={...p.materials[1],id,name:'foreign '+id};const e=new Engine(p),before=structuredClone(e.project),c={op:'produceCatalogAssembly',catalogId:'BUILT-075',id:'roof',place:true};assert.throws(()=>commit(e,[c,{op:'material',id:1,properties:{roughness:-1}}]));assert.deepEqual(e.project,before);assert.throws(()=>commit(e,[{op:'produceCatalogAsset',catalogId:'BUILT-075',id:'wrong'}]));const r={expectedVersion:0,requestId:'m044-create',commands:[c]},d=e.execute({...r,dryRun:true});assert.deepEqual(e.project,before);const made=e.execute({...r,previewToken:d.previewToken});assert.deepEqual(e.execute(r),made);assert.throws(()=>e.execute({...r,requestId:'stale'}));for(let id=503;id<=517;id++)assert.deepEqual(e.project.materials[id],before.materials[id]);assert.equal(Object.keys(e.project.styles.yunshan).length,511);assert.ok(e.project.styles.yunshan.architecturePin>517);const single=structuredClone(e.project);commit(e,[{op:'instantiateAssembly',assemblyId:'roof',prefix:'turned',position:[40,0,0],rotation:1}]);assert.equal(Object.keys(e.project.instances).length,2*Object.keys(single.instances).length);commit(e,[{op:'undo'}]);assert.deepEqual(e.project.instances,single.instances);commit(e,[{op:'undo'}]);for(const k of['assets','instances','assemblies','materials','styles','catalog']as const)assert.deepEqual(e.project[k],before[k]);
});
test('appearance replacement keeps assembly authority unchanged and edited dependencies are rejected instead of silently labelled canonical',()=>{
 const e=new Engine(structuredClone(model('BUILT-075')));commit(e,referenceFinishCommands(e.project));const before=structuredClone(e.project);commit(e,[{op:'definePalette',name:'audit',materials:{[e.project.styles.yunshan.architecturePin]:{color:'#1188aa'}}},{op:'palette',name:'audit'}]);assert.deepEqual(e.project.assets,before.assets);assert.deepEqual(e.project.assemblies,before.assemblies);commit(e,[{op:'undo'}]);assert.deepEqual(e.project.materials,before.materials);e.project.assets['architecture-floor-3p2-3p2'].meshes![0].positions[0]+=.01;const changed=structuredClone(e.project);assert.throws(()=>commit(e,[{op:'produceCatalogAssembly',catalogId:'BUILT-076',id:'second',place:true}]),/依赖已编辑/);assert.deepEqual(e.project,changed);
});
test('atlas assembly overlay adds generated templates without changing base-master or alias counts',async()=>{
 const dir='work/m044/library-'+crypto.randomUUID();await mkdir(dir,{recursive:true});try{await writeFile(dir+'/production-index.json',await readFile('projects/production-index.json'));const index=JSON.parse(await readFile('projects/production/atlas-20261004180151/index.json','utf8'));await writeFile(dir+'/atlas-production-index.json',JSON.stringify(index));const before:any=await readProductionLibrary(dir,{});index.entries.push({kind:'assembly',id:'BUILT-075',sheet:'M044',slot:9,assemblyId:'roof',assetIds:['parts'],dependencyCatalogIds:['BUILT-011'],instances:19,file:'test.ysvox.json'});await writeFile(dir+'/atlas-production-index.json',JSON.stringify(index));const after:any=await readProductionLibrary(dir,{query:'BUILT-075'});assert.equal(after.counts.baseModels,before.counts.baseModels);assert.equal(after.counts.assemblies,before.counts.assemblies+1);assert.equal(after.counts.generatedEntries,before.counts.generatedEntries+1);assert.equal(after.counts.atlasUniqueMasters,before.counts.atlasUniqueMasters);assert.equal(after.entries[0].stage,'layout-candidate');index.entries.at(-1).kind='base';await writeFile(dir+'/atlas-production-index.json',JSON.stringify(index));await assert.rejects(()=>readProductionLibrary(dir,{}));}finally{await rm(dir,{recursive:true,force:true});}
});
