import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {Grid} from '../src/core/grid';
import {Engine} from '../src/core/engine';
import {newProject} from '../src/core/materials';
import {generateTemplate,templateCatalog} from '../src/core/templates';
import {meshChunk} from '../src/core/mesh';
import {demoProject} from '../src/core/demo';
import {checkGeometry} from '../src/core/checks';
import type {Command,Envelope,Project,V3} from '../src/core/types';
function apply(e:Engine,commands:Command[],label='test'){const x:Envelope={expectedVersion:e.project.version,requestId:crypto.randomUUID(),commands,label};const p=e.execute({...x,dryRun:true});return e.execute({...x,previewToken:p.previewToken});}
function empty(){const e=new Engine(newProject());apply(e,[{op:'createAsset',id:'a',name:'A',template:'empty',cellSize:.1}]);return e;}
function contentHash(p:Project){const q=structuredClone(p);q.version=0;q.modifiedAt='';for(const a of Object.values(q.assets))a.version=0;return createHash('sha256').update(JSON.stringify(q)).digest('hex');}
test('sparse chunks round-trip negative coordinates and seam dirty neighbours',()=>{const g=new Grid();for(const p of[[-17,-1,16],[0,0,0],[15,15,15],[16,16,16]] as V3[])g.set(p,4);assert.equal(g.count,4);assert.deepEqual(new Grid(g.serialize()).serialize(),g.serialize());assert.equal(g.get([-17,-1,16]),4);assert.ok(g.dirty.has('-1,0,0'));g.set([0,0,0],0);assert.equal(new Grid(g.serialize()).count,3);});
test('greedy solid block is six quads; cross-chunk internal faces are culled',()=>{const e=empty();apply(e,[{op:'voxels',assetId:'a',mode:'fill',region:{min:[0,0,0],max:[2,2,2]},material:1}]);const g=new Grid(e.project.assets.a.chunks);assert.equal(meshChunk(g,'0,0,0',e.project.materials).reduce((n,b)=>n+b.quads,0),6);const seam=new Grid();seam.set([15,0,0],1);seam.set([16,0,0],1);const output=['0,0,0','1,0,0'].flatMap(k=>meshChunk(seam,k,e.project.materials));assert.equal(output.reduce((n,b)=>n+b.quads,0),10);});
test('opacity material batches preserve visible opaque surface behind glass',()=>{const e=empty(),g=new Grid();g.set([0,0,0],1);g.set([1,0,0],6);const b=meshChunk(g,'0,0,0',e.project.materials);assert.equal(b.find(x=>x.material===1)!.quads,6);assert.equal(b.find(x=>x.material===6)!.quads,5);});
test('batch atomic rollback on missing material / no version advance',()=>{const e=empty(),before=JSON.stringify(e.project);assert.throws(()=>apply(e,[{op:'voxels',assetId:'a',mode:'add',cells:[[0,0,0]],material:1},{op:'assignMaterial',assetId:'a',material:999}]));assert.equal(JSON.stringify(e.project),before);});
test('dry-run does not mutate and large modification requires exact preview',()=>{const e=empty(),v=e.project.version,env:Envelope={expectedVersion:v,requestId:'large',commands:[{op:'voxels',assetId:'a',mode:'fill',region:{min:[0,0,0],max:[20,20,20]},material:1}]};const preview=e.execute({...env,dryRun:true});assert.equal(preview.modifiedVoxels,8000);assert.equal(e.project.version,v);assert.throws(()=>e.execute(env),/先 dry-run/);const r=e.execute({...env,previewToken:preview.previewToken});assert.equal(r.modifiedVoxels,8000);});
test('version conflict and idempotency replay / payload conflict',()=>{const e=empty(),env:Envelope={expectedVersion:e.project.version,requestId:'idempotent',commands:[{op:'voxels',assetId:'a',mode:'add',cells:[[0,0,0]],material:2}]};const r=e.execute(env);assert.deepEqual(e.execute(env),r);assert.throws(()=>e.execute({...env,requestId:'fresh'}),/版本冲突/);assert.throws(()=>e.execute({...env,commands:[{op:'renameProject',name:'changed'}]}),/requestId/);});
test('transaction undo redo restores all voxel/material/instance edits in one step',()=>{const e=new Engine(demoProject()),before=contentHash(e.project);apply(e,[{op:'regenerate',assetId:'window',params:{openingWidth:2}},{op:'assignMaterial',assetId:'sidewall',fromMaterial:2,material:1},{op:'instance',id:'p2',assetId:'planter',position:[2.8,0,-1.1]},{op:'material',id:11,properties:{intensity:.7}}]);assert.equal(e.undoStack.length,1);apply(e,[{op:'undo'}]);assert.equal(contentHash(e.project),before);apply(e,[{op:'redo'}]);assert.equal(e.project.assets.window.template!.params.openingWidth,2);assert.ok(e.project.instances.p2);});
test('voxel replace, mirrored brush, bounded connected fill and surface rules',()=>{const e=empty();apply(e,[{op:'voxels',assetId:'a',mode:'add',cells:[[0,0,0]],material:1,symmetry:{axes:[0],pivot:[0,0,0]}}]);let g=new Grid(e.project.assets.a.chunks);assert.equal(g.get([-1,0,0]),1);apply(e,[{op:'voxels',assetId:'a',mode:'flood',cells:[[1,0,0]],region:{min:[-1,0,0],max:[4,2,1]},material:2}]);g=new Grid(e.project.assets.a.chunks);assert.equal(g.get([3,1,0]),2);assert.equal(g.get([0,0,0]),1);apply(e,[{op:'assignMaterial',assetId:'a',fromMaterial:2,direction:[0,1,0],material:3}]);assert.equal(new Grid(e.project.assets.a.chunks).get([3,1,0]),3);assert.equal(new Grid(e.project.assets.a.chunks).get([3,0,0]),2);});
test('integer rotation, mirror, move, copy array and collision rollback',()=>{const e=empty();apply(e,[{op:'voxels',assetId:'a',mode:'fill',region:{min:[0,0,0],max:[2,1,3]},material:1}]);apply(e,[{op:'transform',assetId:'a',rotation:{axis:1,quarterTurns:1}}]);assert.deepEqual(new Grid(e.project.assets.a.chunks).bounds(),{min:[0,0,0],max:[3,1,2]});apply(e,[{op:'transform',assetId:'a',copy:true,count:2,translation:[4,0,0],step:[4,0,0]}]);assert.equal(new Grid(e.project.assets.a.chunks).count,18);const b=JSON.stringify(e.project);assert.throws(()=>apply(e,[{op:'transform',assetId:'a',copy:true,translation:[0,0,0]}]),/相撞/);assert.equal(JSON.stringify(e.project),b);});
test('extrude adds exposed face columns and is undoable',()=>{const e=empty();apply(e,[{op:'voxels',assetId:'a',mode:'add',cells:[[0,0,0]],material:1}]);apply(e,[{op:'extrude',assetId:'a',region:{min:[0,0,0],max:[1,1,1]},direction:[0,1,0],distance:3}]);assert.equal(new Grid(e.project.assets.a.chunks).count,4);apply(e,[{op:'undo'}]);assert.equal(new Grid(e.project.assets.a.chunks).count,1);});
test('all general templates generate legal structures and unknown parameters reject',()=>{const p=newProject();for(const type of Object.keys(templateCatalog).filter(t=>!t.startsWith('atelier-'))){const pitch=type.startsWith('kit-')?.02:.1,a=generateTemplate(type,type,type,{},pitch,p.styles.yunshan);assert.ok(new Grid(a.chunks).count>0);assert.equal(a.cellSize,pitch);}assert.throws(()=>generateTemplate('a','A','wall',{bogus:1},.1,p.styles.yunshan),/未知/);});
test('assembly template instantiation shares masters and preserves relative placement',()=>{const e=new Engine(demoProject()),assets=Object.keys(e.project.assets).length;apply(e,[{op:'instantiateAssembly',assemblyId:'qinglan',prefix:'second',position:[8,0,0],rotation:0}]);assert.equal(Object.keys(e.project.assets).length,assets);assert.equal(Object.keys(e.project.instances).length,32);assert.deepEqual(e.project.instances['second-entry-1'].position,[8,.6,0]);assert.equal(e.project.instances['second-window-1'].assetId,'window');});
test('mixed-resolution opening obstruction detects subcell blocking geometry',()=>{const p=demoProject();p.assets.block=generateTemplate('block','subcell blocker','slab',{width:.05,height:.05,depth:.05},.05,p.styles.yunshan);p.instances.block={id:'block',assetId:'block',name:'block',position:[.8,1,0],rotation:0,parent:null};const r=checkGeometry(p);assert.ok(r.openings.find(x=>x.instanceId==='entry-1')!.blockedBy.includes('block'));});
test('interfaces require common pitch, normal and footprint; detach preserves master',()=>{const e=new Engine(newProject());apply(e,[{op:'createAsset',id:'a',name:'A',template:'wall',cellSize:.1},{op:'createAsset',id:'b',name:'B',template:'wall',cellSize:.2},{op:'instance',id:'i1',assetId:'a',position:[0,0,0]}]);assert.throws(()=>apply(e,[{op:'connect',id:'bad',assetId:'b',portId:'left',targetInstanceId:'i1',targetPortId:'right',rotation:0}]),/格距/);apply(e,[{op:'connect',id:'i2',assetId:'a',portId:'left',targetInstanceId:'i1',targetPortId:'right',rotation:0}]);assert.deepEqual(e.project.instances.i2.position,[3,0,0]);apply(e,[{op:'detach',instanceId:'i2',newAssetId:'independent'}]);assert.equal(e.project.instances.i1.assetId,'a');assert.equal(e.project.instances.i2.assetId,'independent');});
test('metadata transforms preserve port/part spatial relationship; cyclic parents rejected',()=>{const e=new Engine(newProject());apply(e,[{op:'createAsset',id:'wall',name:'W',template:'wall',cellSize:.1}]);apply(e,[{op:'transform',assetId:'wall',translation:[2,0,0]}]);assert.equal(e.project.assets.wall.ports[0].position[0],.2);assert.equal(e.project.assets.wall.parts[0].region.min[0],2);assert.throws(()=>apply(e,[{op:'metadata',assetId:'wall',parts:[{id:'a',name:'a',parent:'a',region:{min:[0,0,0],max:[1,1,1]}}]}]),/环/);});
test('schema rejects pathological selection, decimals, unknown fields and invalid materials',()=>{const e=empty();for(const cmd of[{op:'voxels',assetId:'a',mode:'add',cells:[[.5,0,0]],material:1},{op:'voxels',assetId:'a',mode:'fill',region:{min:[0,0,0],max:[300,300,300]},material:1},{op:'material',id:1,properties:{opacity:2}},{op:'select',assetId:'a',region:{min:[3,0,0],max:[2,1,1]},partId:null},{op:'renameProject',name:'foo',shell:'rm'}])assert.throws(()=>apply(e,[cmd]));});
test('demo has enterable door, window and stairs clearances without collisions',()=>{const p=demoProject(),r=checkGeometry(p,[{name:'door',min:[.8,.6,-.6],max:[2.2,2.8,.4]},{name:'stairs lower clearance',min:[.8,.2,-1.2],max:[2.2,2.2,-.8]},{name:'stairs upper clearance',min:[.8,.6,-.4],max:[2.2,2.6,0]}]);assert.equal(r.collisions.length,0,JSON.stringify(r.collisions));assert.equal(r.unsupported.length,0,JSON.stringify(r.unsupported));assert.ok(r.clearances.every(x=>x.clear),JSON.stringify(r.clearances));assert.equal(r.openings.find(o=>o.instanceId==='entry-1')!.ownSolidCells,0);assert.ok(r.openings.every(o=>o.blockedBy.length===0));});
