import assert from 'node:assert/strict';import {Vector3} from 'three';
import type {Asset,Project,V3} from '../../src/core/types';
import {attireScene,attireScenes,attireWearers} from '../../src/production/attire-assembly';
import {makeAttireAsset,attireRecipes,attireVariants} from '../../src/production/atlas-attire';
import {garmentFrame} from '../../src/production/garment-shapes';
import {productionProject} from '../../src/production/style';
import {posedRigPorts} from '../../src/core/rig';
import {displayMesh} from '../../src/core/mesh';
import {axisPose} from '../../src/production/avatar-model';
import {garmentShapes} from './garment-audit';
import {auditShape,penetration} from './mesh-audit';import {rayHits} from './headwear-audit';
const base=productionProject('M038 actual triangle audit');
export function attireCatalogSource(p:Project,a:Asset):string{if(a.source?.catalogId)return String(a.source.catalogId);const source=p.assets[String(a.source?.sourceAssetId)];return source?attireCatalogSource(p,source):'';}
export function auditAttireInstallation(q:Project,kind:string){const rows=[],instances=Object.values(q.instances),shapes=new Map(instances.map(i=>[i.id,displayMesh(q.assets[i.assetId],q.materials).map((b,j)=>{const points:number[]=[];for(let k=0;k<b.positions.length;k+=3)points.push(...new Vector3(...b.positions.slice(k,k+3)).applyAxisAngle(new Vector3(0,1,0),i.rotation*Math.PI/2).add(new Vector3(...i.position)).toArray());return auditShape(b.meshName??'native-'+j,points,b.indices);})])),clothing=(a:Asset)=>/^CHAR-1(1[3-9]|[23][0-9]|4[0-8])$/.test(attireCatalogSource(q,a));for(let i=0;i<instances.length;i++)for(let j=i+1;j<instances.length;j++){const a=instances[i],b=instances[j];if(!clothing(q.assets[a.assetId])&&!clothing(q.assets[b.assetId]))continue;const r={kind,a:a.id,b:b.id,...penetration(shapes.get(a.id)!,shapes.get(b.id)!)};assert.equal(r.contained+r.crossing,0,JSON.stringify(r));rows.push(r);}return rows;}
export function attireSceneFitAudit(){return attireScenes.flatMap(kind=>auditAttireInstallation(attireScene(base,kind),kind));}
export function attireVariantFitAudit(){return Object.keys(attireRecipes).flatMap(id=>attireVariants(id).flatMap(params=>{const fit=String(params.costumeFit??params.wearFit??'adultA');return auditAttireInstallation(attireWearers(base,[{key:'wear',catalogId:id,fit,lid:String(params.lid??'closed')}]),id+'/'+JSON.stringify(params));}));}
export function attireLidAudit(){const rows=[];for(const id of['CHAR-147','CHAR-148'])for(const angle of[0,15,30,45,60,75,90,105]){const a=makeAttireAsset(id,id,id,base.styles.yunshan);a.rig!.pose.lid=axisPose([1,0,0],-angle*Math.PI/180);const buckets=displayMesh(a,base.materials),joint=(b:typeof buckets[number])=>b.meshName?a.rig!.meshJoints[b.meshName]:b.bindingJoint,shapes=(list:typeof buckets)=>list.map((b,i)=>auditShape(b.meshName??'native-'+i,b.positions,b.indices)),lid=shapes(buckets.filter(b=>joint(b)==='lid')),root=shapes(buckets.filter(b=>joint(b)==='root'&&b.meshName!=='袋盖实际前铰轴')),r={id,angleDegrees:-angle,excludedIntentionalAxle:'袋盖实际前铰轴; lid contact at its actual pivot is expected',...penetration(lid,root)};assert.equal(r.contained+r.crossing,0,JSON.stringify(r));rows.push(r);}return rows;}
export function attireApertureAudit(){const rows:any[]=[];for(const id of Object.keys(attireRecipes))for(const params of attireVariants(id)){const fit=String(params.costumeFit??params.wearFit??'adultA'),f=garmentFrame(fit),a=makeAttireAsset(id,id,id,base.styles.yunshan,params),meshes=garmentShapes(a),n=Number(id.slice(5)),open=(name:string,p:V3,d:V3)=>{assert.equal(rayHits(meshes,p,d).length,0,id+' '+name);rows.push({id,params,opening:name,open:true});};if([137,138,139,141,143,144,145].includes(n))open('neck-axis',[0,n===141?f.neck:f.hip+.10,0],[0,1,0]);if(n===140){open('hood-face',[0,f.neck+.14,0],[0,0,-1]);open('cape-bottom',[0,.46,0],[0,-1,0]);}if(n===142){const sy=fit==='child'?.70:1,sx=fit==='child'?.72:1;open('true-wrist',[0,-.04*sy,0],[0,1,0]);for(let k=0;k<4;k++){const point:V3=[(-.030+k*.020)*sx,(-.08-[.060,.075,.071,.056][k]*.90)*sy,0];assert.ok(rayHits(meshes,point,[0,-1,0]).length>0);open('finger-'+k+'-to-palm',point,[0,1,0]);rows.push({id,params,closedTip:k,trueEndCap:true});}}if(n===146)open('leg-through-straps',[f.q.hipHalfWidthM,f.ankle+.03,0],[0,1,0]);for(const port of posedRigPorts(a).filter(p=>p.id.startsWith('wrist')&&n!==142))open(port.id,port.position,port.normal);
 if(n>=147){const p=a.ports.find(p=>p.id==='bag-mouth')!.position,point:V3=[p[0],p[1]-.001,p[2]],up=rayHits(meshes,point,[0,1,0]);assert.equal(up.length===0,params.lid==='open');assert.ok(rayHits(meshes,point,[0,-1,0]).length>0);rows.push({id,params,opening:'bag-mouth',open:params.lid==='open',realFloor:true});}
 for(const m of a.meshes!.filter(m=>/工具袋--?1$|前袋真腔$|独立侧袋--?1$/.test(m.name))){const shape=auditShape(m.name,m.positions,m.indices),top=shape.box.max.y,pts=shape.vs.filter(v=>Math.abs(v.y-top)<1e-8),point:V3=[(Math.min(...pts.map(v=>v.x))+Math.max(...pts.map(v=>v.x)))/2,top-.0001,(Math.min(...pts.map(v=>v.z))+Math.max(...pts.map(v=>v.z)))/2];assert.equal(rayHits([shape],point,[0,1,0]).length,0,id+' '+m.name);assert.ok(rayHits([shape],point,[0,-1,0]).length>0);rows.push({id,params,opening:m.name,open:true,realFloor:true});}}
 return rows;}
