import {careScene,careScenes} from '../../src/production/care-assembly';
import assert from 'node:assert/strict';import {Vector3} from 'three';import type {V3} from '../../src/core/types';import {productionProject} from '../../src/production/style';import {careIds,careVariants,makeCareAsset} from '../../src/production/atlas-care';import {serviceShapes} from './service-audit';import {inside,penetration} from './mesh-audit';import {shapeDistance} from './held-audit';
export function careApertureAudit(){const p=productionProject('M041 openings'),rows=[];for(const id of careIds)for(const params of careVariants(id)){const a=makeCareAsset(id,id,id,p.styles.yunshan,params),sh=serviceShapes(a,p.materials),checks:{name:string;point:V3;solid:boolean;filter?:RegExp}[]=[],add=(name:string,point:V3,solid=false,filter?:RegExp)=>checks.push({name,point,solid,filter});
 if(id==='CHAR-199'){add('jaw opening',[.009,.282,0]);add('movable jaw',[params.jawForm==='wide'?-.029:-.012,.283,0],true,/活动颚$/);add('hanging aperture',[0,.025,0]);}
 if(id==='CHAR-200'){add('metal striking head',[.055,params.hammerForm==='long'?.44:.31,0],true,/独立加厚锤头/);add('wood shaft',[0,.21,0],true,/锤木柄/);}
 if(id==='CHAR-201'){add('real shaft',[0,.4,0],true,/长木杆/);add('shaft socket radial hole',[0,params.hoeForm==='field'?1.04:.71,0],false,/金属套/);}
 if(id==='CHAR-202'){add('retained cavity',[.24,.16,.26]);add('tall bail aperture',[.24,.32,.17]);add('retained native floor',[.243,.013,.183],true,/native/);add('woven wall real gap',[.101,.061,.030]);}
 if(id==='CHAR-203'){const h=params.parcelForm==='tall'?.34:.23;add('closed box true interior',[0,h*.5,0]);add('box floor',[0,.003,0],true,/真实壁底/);add('closed fold lid',[.1,h-.001,0],true,/顶折盖/);}
 if(id==='CHAR-204'){add('paper cone inner space',[0,.21,0],false,/真实包纸锥/);add('bow loop',[.03,.134,-.025],false,/花结真实空环/);}
 if(id==='CHAR-205'){add('white bow loop',[.03,.134,-.025],false,/花结真实空环/);add('bundle real stem',[0,.04,.01],true,/bouquetStem/);}
 if(id==='CHAR-206'){const x=params.carrierFit==='adultA'?.184:.169;add('empty infant seat space',[0,1.08,-.30]);add('true padded seat',[0,.931,-.30],true,/软座垫/);add('shoulder ring passage',[x,1.21,.015],false,/肩背真环/);add('waist ring passage',[0,.97,0]);add('real back waist strap',[0,.97,.205],true,/真实腰环/);}
 if(id==='CHAR-207'){add('wrist loop centre',[0,params.leashForm==='long'?1.08:.65,0]);add('clip aperture',[.195,.036,.058]);}
 if(id==='CHAR-208'){add('bag interior',[0,.15,0]);add('bag mouth',[0,.33,0],params.foodBagForm==='sealed');add('real floor',[0,.002,0],true,/真壁底/);add('separate food',[.014,.014,.015],params.foodBagForm==='open',/独立粮粒/);}
 if(id==='CHAR-306'||id==='CHAR-307'){const dog=id==='CHAR-307';add('between forefeet',[0,.035,dog?-.20:-.17]);add('real body',[0,dog?.36:.22,.03],true,/连续躯干/);add('ear gap',[0,dog?.70:.43,dog?-.24:-.165]);if(dog)add('canine tongue',[0,.525-.076,-.24-.175],params.dogForm==='open-mouth',/犬舌面/);}
 for(const c of checks){const hit=sh.filter(m=>!c.filter||c.filter.test(m.name)).some(m=>inside(new Vector3(...c.point),m));assert.equal(hit,c.solid,id+JSON.stringify(params)+' '+c.name);rows.push({id,params,...c,filter:c.filter?.source,actualSolid:hit});}}
 return rows;}

export const careGripFilters:Record<string,RegExp>={'CHAR-199':/扳手独立握胶/,'CHAR-200':/锤独立握胶|锤握胶纹/,'CHAR-201':/锄连续长木杆/,'CHAR-202':/新增提梁横握柄/,'CHAR-204':/花束同用途分件-bouquetStem/,'CHAR-205':/花束同用途分件-bouquetStem/,'CHAR-207':/牵引真实腕环/};
export function careSceneAudit(){const p=productionProject('M041 hand audit'),rows=[];for(const kind of careScenes){const q=careScene(p,kind),shapes=Object.values(q.instances).map(i=>({a:q.assets[i.assetId],key:i.id,sh:serviceShapes(q.assets[i.assetId],q.materials,i.position)}));for(let i=0;i<shapes.length;i++)for(let j=i+1;j<shapes.length;j++){const r=penetration(shapes[i].sh,shapes[j].sh);assert.equal(r.contained+r.crossing,0,JSON.stringify({kind,a:shapes[i].key,b:shapes[j].key,...r}));}for(const h of shapes.filter(x=>x.a.source?.careCatalogId)){const id=String(h.a.source!.careCatalogId),prop=shapes.find(x=>x.a.source?.catalogId===id&&x.a.category==='base')!,target=prop.sh.filter(x=>careGripFilters[id].test(x.name)),distances=h.sh.filter(t=>/独立指节|拇指|裸露掌面/.test(t.name)).map(t=>({part:t.name,metres:Math.min(...target.map(x=>shapeDistance(t,x)))})).sort((a,b)=>a.metres-b.metres);assert.ok(distances[1].metres<.006,id);rows.push({kind,id,mode:'finite grip',distances,nonpenetration:true,noPhysicalLoadClaim:true});}}return rows;}
