import {Box3,Vector3} from 'three';
import type {Assembly,Asset,Instance,Project,V3} from '../../src/core/types';
import {rotateY} from '../../src/core/types';
import {Grid} from '../../src/core/grid';
import {architectureComponents} from './architecture-audit';
import {auditShape,inside,type Shape} from './mesh-audit';

/** Queries closed component solids separately: a material bucket can contain overlapping solids. */
export class CivicAudit {
 assets=new Map<string,{shapes:(Shape&{material:number;collision:boolean})[];grid:Grid;physicalCells:[V3,number][];box:Box3}>();
 constructor(public p:Project,public assembly:Assembly){for(const id of new Set(assembly.instances.map(i=>i.assetId))){const a=p.assets[id],shapes=architectureComponents(a).map(m=>({...auditShape(m.name,m.positions,m.indices),material:m.material,collision:m.collision})),grid=new Grid(a.chunks),box=new Box3();for(const s of shapes)box.union(s.box);for(const[v]of grid.cells()){const min=new Vector3(...v.map((n,d)=>a.origin[d]+n*a.cellSize));box.expandByPoint(min);box.expandByPoint(min.clone().addScalar(a.cellSize));}this.assets.set(id,{shapes,grid,physicalCells:[...grid.cells()].filter(([,mat])=>p.materials[mat].solid),box});}}
 local(i:Instance,v:V3):V3{return rotateY(v.map((n,d)=>n-i.position[d])as V3,(4-i.rotation)%4);}
 world(i:Instance,v:V3):V3{return rotateY(v,i.rotation).map((n,d)=>n+i.position[d])as V3;}
 point(v:V3,exclude?:string,surface=false){const hits:{instance:string;part:string;material:number}[]=[];for(const i of this.assembly.instances){if(i.id===exclude)continue;const a=this.p.assets[i.assetId],cached=this.assets.get(i.assetId)!,local=this.local(i,v),q=new Vector3(...local);if(!cached.box.clone().expandByScalar(surface?1e-7:0).containsPoint(q))continue;const mat=cached.grid.get(local.map((n,d)=>Math.floor((n-a.origin[d])/a.cellSize))as V3);if(mat&&this.p.materials[mat].solid)hits.push({instance:i.id,part:'native-cell',material:mat});for(const s of cached.shapes)if(s.collision&&(inside(q,s)||(surface&&s.box.clone().expandByScalar(1e-7).containsPoint(q)&&s.ts.some(t=>t.closestPointToPoint(q,new Vector3()).distanceToSquared(q)<1e-14))))hits.push({instance:i.id,part:s.name,material:s.material});}return hits;}
 clear(name:string,min:V3,max:V3,exclude:string[]=[]){const blocked:{instance:string;part:string}[]=[];for(const i of this.assembly.instances){if(exclude.includes(i.id))continue;const cached=this.assets.get(i.assetId)!,corners=[min,max,[min[0],min[1],max[2]],[max[0],max[1],min[2]]]as V3[],box=new Box3().setFromPoints(corners.map(v=>new Vector3(...this.local(i,v))));if(!box.intersectsBox(cached.box))continue;for(const s of cached.shapes)if(s.collision&&box.intersectsBox(s.box)&&(s.ts.some(t=>box.intersectsTriangle(t))||inside(box.getCenter(new Vector3()),s)))blocked.push({instance:i.id,part:s.name});if(cached.physicalCells.length){const a=this.p.assets[i.assetId],lo=box.min.toArray().map((n,d)=>Math.floor((n-a.origin[d])/a.cellSize)),hi=box.max.toArray().map((n,d)=>Math.floor((n-a.origin[d])/a.cellSize));if(cached.physicalCells.some(([v])=>v.every((n,d)=>n>=lo[d]&&n<=hi[d])))blocked.push({instance:i.id,part:'native-cell'});}}
 return{name,min,max,excludedInstances:exclude,clear:!blocked.length,blocked};}
 head(name:string,walk:V3,width=.45,height=1.9){return this.clear(name,[walk[0]-width/2,walk[1]+.025,walk[2]-width/2],[walk[0]+width/2,walk[1]+height,walk[2]+width/2]);}
}
export function civicSupports(a:CivicAudit){const groups=a.assembly.source!.instanceGroups as Record<string,string>;return a.assembly.instances.filter(i=>groups[i.id]==='column'&&typeof(a.p.assets[i.assetId].source?.parameters as any)?.width==='number').map(i=>{const {height,width}=a.p.assets[i.assetId].source!.parameters as any,contacts=[];for(const x of[-.4,0,.4])for(const z of[-.4,0,.4]){const point=a.world(i,[x*width,height,z*width]);for(const h of a.point(point,i.id,true))contacts.push({...h,point});}return{column:i.id,headY:i.position[1]+height,supported:!!contacts.length,contacts};});}
export function civicStairClearance(a:CivicAudit){const groups=a.assembly.source!.instanceGroups as Record<string,string>,checks=[];for(const i of a.assembly.instances.filter(i=>groups[i.id]==='stair')){const params=a.p.assets[i.assetId].source?.parameters as any;if(!params?.stepsPerFlight)continue;const {height,stepsPerFlight:n,step,tread,totalD}=params,points:V3[]=[[1.2,0,1.2],[4,height,1.2],[2.6,height/2,totalD-1.2]];for(let j=0;j<n;j++){points.push([1.2,(j+1)*step,2.4+(j+.5)*tread],[4,height/2+(j+1)*step,2.4+(n-1-j+.5)*tread]);}for(const[j,v]of points.entries())checks.push(a.head(i.id+' walk-'+j,a.world(i,v),j<3?.45:.20));}return checks;}
export function civicFloorOpenings(a:CivicAudit){const checks=[];for(const i of a.assembly.instances){const asset=a.p.assets[i.assetId],params=asset.source?.parameters as any;if(!params?.holes?.length)continue;for(const[j,h]of params.holes.entries()){const point=a.world(i,[(h.min[0]+h.max[0])/2,-params.depth/2,(h.min[1]+h.max[1])/2]);const hit=a.point(point).filter(h=>h.instance===i.id);checks.push({floor:i.id,hole:j,point,clear:hit.length===0});}}return checks;}

export function civicTransportClearance(a:CivicAudit){const s=a.assembly.source as any,id=s.catalogId??a.assembly.id.toUpperCase(),checks:ReturnType<CivicAudit['head']>[]=[],walks:{name:string;point:V3;contacts:ReturnType<CivicAudit['point']>;supported:boolean}[]=[];
 const walk=(name:string,v:V3)=>{checks.push(a.head(name,v));const point:V3=[v[0],v[1]-.02,v[2]],contacts=a.point(point);walks.push({name,point,contacts,supported:!!contacts.length});};
 if(id==='BUILT-161'){for(const r of s.authorSegments){const aa=r.geometryFrom??r.from,z=r.to;for(const t of[.03,.25,.5,.75,.97])walk(r.id+'-'+t,aa.map((n:number,d:number)=>n+(z[d]-n)*t)as V3);}for(const n of s.authorNodes){const [x,y,z]=n.center;for(const dz of[-.08,.08])walk('station-seam-'+x+'-'+z+'-'+dz,[x,y,Math.sign(z)*27+dz]);}}
 if(id==='BUILT-163'){for(const r of s.authorRoutes){const car=a.assembly.instances.find(i=>i.id===r.cabinInstance)!;for(const x of[-.9,-1.18,-1.22,-1.5,-2.5])walk(r.key+'-boarding-'+x,a.world(car,[x,0,0]));const clamp=a.assembly.instances.find(i=>i.id===r.clampInstance)!;for(const x of[-.8,.8]){const point=a.world(clamp,[x,0,0]),hits=a.point(point);if(hits.some(h=>h.instance===clamp.id))throw new Error('Cable clamp hole is obstructed');if(!hits.some(h=>h.material===a.p.styles.yunshan.suspensionCable))throw new Error('Cable absent from actual clamp hole');}}}
 if(id==='BUILT-164'){const car=a.assembly.instances.find(i=>i.id===s.car)!;for(const z of[0,-1,-1.85,-1.95,-2.3,-2.55,-3,-7,-11])walk('parked-lift-boarding-'+z,a.world(car,[0,0,z]));const parked=[car.id,...a.assembly.instances.filter(i=>(s.instanceGroups as Record<string,string>)[i.id]==='boarding').map(i=>i.id)];checks.push(a.clear('151m central shaft corridor with parked car and bridge excluded',[138.21,103.63,33.11],[141.79,257.19,36.89],parked));}
 if(id==='BUILT-165'){for(const r of s.berths)for(let x=3.2;x<10.5;x+=.25)walk(r.name+'-boarding-'+x.toFixed(2),[r.offset[0]+x,2.2,r.offset[2]+5]);}
 return{checks,walks};}
