import assert from 'node:assert/strict';
import {Grid} from '../../src/core/grid';
import {geometryData,assetBoundsM} from '../../src/core/sky';
import {faceAtlasPixels,faceAtlasRolePixels,faceAtlasRoles} from '../../src/core/face-atlas';
import type {Project,Assembly,V3} from '../../src/core/types';
import {outfitHash as hash} from '../../src/production/outfit-components';
import {architectureClosed} from './architecture-audit';
import {nativeIslandAttachments} from '../../src/production/mixed-review';

export function auditFaceVariant(p:Project,a:Assembly){
 const id=String(a.source!.catalogId),tile=Number(id.slice(-3))-24;assert.ok(Number.isInteger(tile)&&tile>=0&&tile<6);const d=a.source!.faceAtlasVariant as any,resource=p.assets[d.parentResourceAssetId],old=p.assets[d.headSourceAssetId],head=p.assets[d.installedHeadAssetId],change=head.source!.faceAtlasDerivation as any,face=head.meshes!.find(m=>m.faceAtlas)!;
 assert.equal(a.source!.kind,'catalog-variant');assert.equal(a.source!.parentCatalogId,'CHAR-023');assert.equal(a.source!.parentKind,'material');assert.deepEqual(a.source!.parameters,{faceCell:tile});assert.equal(d.tile,tile);assert.equal(d.head,['CHAR-066','CHAR-069','CHAR-068'][tile%3]);assert.equal(old.source!.catalogId,d.head);if(tile%3===2)assert.equal((old.source!.parameters as any).headStage,'school');assert.equal(resource.source!.kind,'catalog-material');assert.equal(resource.source!.catalogId,'CHAR-023');assert.equal(hash(geometryData(resource)),d.parentResourceGeometrySHA256);assert.equal(hash(geometryData(old)),d.headSourceGeometrySHA256);assert.deepEqual(resource.meshes![0].faceAtlas,face.faceAtlas);assert.deepEqual(face.faceAtlas!.materials,Object.fromEntries(faceAtlasRoles.map(r=>[r,p.styles['face-atlas-char-023'][r]])));
 assert.equal(a.instances.length,1);assert.equal(a.instances[0].assetId,head.id);assert.equal(head.cellSize,.005);assert.equal(head.rig,undefined);assert.deepEqual(head.ports,old.ports);assert.deepEqual(head.openings,old.openings);assert.deepEqual(head.origin,old.origin);
 const restored=structuredClone(head),g=new Grid(restored.chunks);assert.ok(g.count>0&&g.count<new Grid(old.chunks).count);assert.equal(change.retainedNativeEarCells,g.count);assert.equal(head.parts.length,3);assert.ok(head.parts.filter(part=>part.id!=='root').every(part=>part.name.startsWith('耳内')));assert.deepEqual(head.parts.find(p=>p.id==='root')!.region,g.bounds());
 const removed=new Set<string>();for(const row of change.removedCells as {cell:V3;material:number}[]){assert.equal(g.get(row.cell),0);assert.equal(new Grid(old.chunks).get(row.cell),row.material);assert.ok(!removed.has(row.cell.join(',')));removed.add(row.cell.join(','));g.set(row.cell,row.material);}const serial=g.serialize();restored.chunks=Object.fromEntries(change.originalChunkOrder.map((key:string)=>[key,serial[key]]));const restoredFace=restored.meshes!.find(m=>m.name===change.faceMesh)!;restoredFace.uvs=change.originalUV;delete restoredFace.faceAtlas;assert.equal(hash(geometryData(restored)),hash(geometryData(old)));
 for(let k=0;k<face.uvs.length;k+=2){assert.ok(face.uvs[k]>=((tile*32+.5)/192)-1e-10&&face.uvs[k]<=((tile*32+31.5)/192)+1e-10);assert.ok(face.uvs[k+1]>=.5/16&&face.uvs[k+1]<=15.5/16);}
 for(const m of head.meshes!)assert.equal(m.collision,false);for(const[,id]of new Grid(head.chunks).cells()){assert.equal(p.materials[id].solid,false);assert.equal(p.materials[id].intensity,0);}
 const closed=architectureClosed(head),native=nativeIslandAttachments(head);assert.ok(closed.length&&closed.every(r=>r.closed&&r.oriented));assert.ok(native.length&&native.every(r=>r.attached));const b=assetBoundsM(head)!;assert.ok(Math.abs(b.max[1]-(tile%3===2?.215:.24))<1e-10);assert.ok(Math.abs(b.min[1]+.022)<1e-10);
 const texture=faceAtlasPixels(face.faceAtlas!,p.materials),rolePixels=faceAtlasRolePixels(),roleCounts:Record<string,number>={};for(let y=0;y<16;y++)for(let x=0;x<32;x++){const role=faceAtlasRoles[rolePixels[y*192+tile*32+x]];roleCounts[role]=(roleCounts[role]??0)+1;}
 assert.ok(roleCounts.eyeWhite&&roleCounts.eyeIris&&roleCounts.eyePupil&&roleCounts.skinLip&&roleCounts.browHair);assert.equal(!!roleCounts.sparseHair,tile%3===1);
 return{passed:true,catalogId:id,tile,age:['adult','elder','child'][tile%3],stressed:tile>=3,headSource:d.head,sourceGeometrySHA256:d.headSourceGeometrySHA256,originalHeadHeightM:b.max[1],nativeCells:new Grid(head.chunks).count,removedNativeFaceCells:removed.size,originalShapeRecoveredExactly:true,closedContinuousMeshes:closed.length,nativeAttachments:native,roleCounts,atlasPixelsSHA256:hash([...texture.data]),sharedAtlasSize:[192,16],independentSemanticRoles:9,originalPixelsProvided:false,originalControllerBound:false};
}
