import assert from 'node:assert/strict';import {Vector3} from 'three';import {productionProject} from '../../src/production/style';import {faunaIds,faunaVariants,makeFaunaAsset} from '../../src/production/atlas-fauna';import {auditShape,inside} from './mesh-audit';import {displayMesh} from '../../src/core/mesh';import type {V3} from '../../src/core/types';
/** Actual triangles, including the gaps that a display-only collision list cannot verify. */
export function faunaAnatomyAudit(){const p=productionProject('fauna anatomy'),rows:{id:string;params:Record<string,string>;name:string;point:V3;expectedSolid:boolean;actualSolid:boolean}[]=[];for(const id of faunaIds)for(const params of faunaVariants(id)){const a=makeFaunaAsset(id,id,id,p.styles.yunshan,params),shapes=displayMesh(a,p.materials).map((b,i)=>auditShape(b.meshName??'native-'+i,b.positions,b.indices));const check=(name:string,point:V3,expected:boolean,filter?:RegExp)=>{const actual=shapes.filter(s=>!filter||filter.test(s.name)).some(s=>inside(new Vector3(...point),s));assert.equal(actual,expected,id+' '+JSON.stringify(params)+' '+name);rows.push({id,params,name,point,expectedSolid:expected,actualSolid:actual});};
 if(id==='CHAR-308'){check('gap between long ears',[0,.55,-.080],false);check('solid rabbit torso',[0,.205,.075],true,/兔梨形后躯/);}
 if(id==='CHAR-309'){check('bifurcated caudal centre remains empty',[0,.155,.265],false);check('actual fish body',[0,.155,0],true,/鱼独立纺锤身/);}
 if(['CHAR-310','CHAR-311','CHAR-312','CHAR-319'].includes(id)){check('two feet remain separate',[0,.025,-.040],false);if(id==='CHAR-311'||id==='CHAR-312')check('true webbed membrane',[id==='CHAR-311'?.064:.071,.014,-.040],true,/足/);}
 if(['CHAR-313','CHAR-314','CHAR-315','CHAR-316','CHAR-317'].includes(id)){const x=id==='CHAR-313'?.114:id==='CHAR-317'?.131:id==='CHAR-315'?.204:id==='CHAR-316'?.1156:.1088,z=id==='CHAR-313'?-.135:id==='CHAR-317'?-.25:id==='CHAR-315'?-.3654:id==='CHAR-316'?-.2494:-.203,w=id==='CHAR-313'?.072:id==='CHAR-317'?.082:id==='CHAR-315'?.107:id==='CHAR-316'?.067:.068;check('separate left and right front legs',[0,.025,z],false);check('split hoof central cleft',[x,.022,z-.012],false,/分蹄/);check('solid outer hoof toe',[x+w*.26,.022,z-.012],true,/分蹄/);}
 if(id==='CHAR-318'){check('squirrel solid tail base',[0,.15,.18],true,/蓬松大尾/);check('independent nut inside paw contact',[0,.235,-.185],true,/坚果壳/);}
 }return rows;}
