import assert from 'node:assert/strict';
import {garmentScene,garmentScenes} from '../../src/production/garment-assembly';
import {makeGarmentAsset,garmentRecipes,garmentVariants} from '../../src/production/atlas-garments';
import {makeAvatarAsset} from '../../src/production/atlas-avatar';
import {reflectAvatar} from '../../src/production/avatar-assembly';
import {garmentFrame} from '../../src/production/garment-shapes';
import {productionProject} from '../../src/production/style';
import {displayMesh} from '../../src/core/mesh';
import {auditShape,penetration} from './mesh-audit';
import {rayHits} from './headwear-audit';
import type {Asset} from '../../src/core/types';
const p=productionProject('garment triangle audit'),s=p.styles.yunshan;
export const garmentShapes=(a:Asset,x=0,y=0)=>displayMesh(a,p.materials).map((b,i)=>auditShape(b.meshName??'native-'+i,b.positions.map((v,k)=>v+(k%3===0?x:k%3===1?y:0)),b.indices));
export function garmentSceneFitAudit(){const rows=[];for(const kind of garmentScenes){const q=garmentScene(p,kind),shapes=new Map(Object.values(q.assets).map(a=>[a.id,garmentShapes(a)])),instances=Object.values(q.instances);for(let i=0;i<instances.length;i++)for(let j=i+1;j<instances.length;j++){const a=instances[i],b=instances[j],aa=q.assets[a.assetId],bb=q.assets[b.assetId],garment=(v:Asset)=>/^CHAR-1(1[3-9]|2[0-4])$/.test(String(v.source?.catalogId??''));if(JSON.stringify(a.position)!==JSON.stringify(b.position)||!garment(aa)&&!garment(bb))continue;const r={kind,a:a.id,b:b.id,...penetration(shapes.get(a.assetId)!,shapes.get(b.assetId)!)};assert.equal(r.contained+r.crossing,0,JSON.stringify(r));rows.push(r);}}return rows;}
export function garmentFootFitAudit(){const rows=[];for(const id of ['CHAR-121','CHAR-122','CHAR-123'])for(const fit of id==='CHAR-123'?['child']:['adultA','adultB']){const a=makeGarmentAsset(id,id,id,s,id==='CHAR-123'?{}:{bodyFit:fit}),{q,ankle}=garmentFrame(fit);for(const side of[-1,1]){const f=makeAvatarAsset('CHAR-071','foot','foot',s,{limbFit:fit==='child'?'child':'adult'}),foot=side<0?reflectAvatar(f,'left'):f,r={id,fit,side,...penetration(garmentShapes(a),garmentShapes(foot,side*q.hipHalfWidthM,ankle))};assert.equal(r.contained+r.crossing,0,JSON.stringify(r));rows.push(r);}}return rows;}
export function garmentApertureAudit(){const rows=[];for(const id of Object.keys(garmentRecipes))for(const params of garmentVariants(id)){const fit=id==='CHAR-123'?'child':String(params.bodyFit),f=garmentFrame(fit),a=makeGarmentAsset(id,id,id,s,params),meshes=garmentShapes(a),n=Number(id.slice(5));if([113,114,116,117,124].includes(n)){assert.equal(rayHits(meshes,[0,f.hip+.10,0],[0,1,0]).length,0,id+' neck');rows.push({id,params,opening:'neck',openAxis:true});}if([115,119,120].includes(n)){assert.equal(rayHits(meshes,[0,-.05,0],[0,1,0]).length,0,id+' skirt/sash');rows.push({id,params,opening:'waist-and-hem',openAxis:true});}if([118,124].includes(n))for(const side of[-1,1]){assert.equal(rayHits(meshes,[side*f.q.hipHalfWidthM,f.ankle+.05,0],[0,-1,0]).length,0,id+' ankle');rows.push({id,params,side,opening:'ankle',openAxis:true});}if([121,122,123].includes(n))for(const side of[-1,1]){const point=[side*f.q.hipHalfWidthM,f.ankle+.01,0];assert.equal(rayHits(meshes,point,[0,1,0]).length,0,id+' shoe entrance');const floor=rayHits(meshes,point,[0,-1,0]);assert.ok(floor.some(p=>p[1]<0));rows.push({id,params,side,opening:'shoe-entrance',openAxis:true,realSoleBelowFoot:true});}}return rows;}
