import {Vector3} from 'three';
import type {Assembly,Project,V3} from '../../src/core/types';
import {assetBoundsM} from '../../src/core/sky';
import {inside} from './mesh-audit';
import {CivicAudit} from './civic-audit';

/** Visual water and animal geometry is deliberately nonphysical: inspect its
 * actual triangles/native cells instead of accepting an empty collision list. */
export function habitatAudit(p:Project,a:Assembly){
 const q=new CivicAudit(p,a),s=a.source as any;
 const visual=(point:V3,instanceIds:string[])=>a.instances.filter(i=>instanceIds.includes(i.id)).flatMap(i=>{const local=q.local(i,point),v=new Vector3(...local),asset=p.assets[i.assetId],cache=q.assets.get(i.assetId)!,hits:string[]=[];if(cache.grid.get(local.map((n,d)=>Math.floor((n-asset.origin[d])/asset.cellSize))as V3))hits.push(i.id+':native');for(const shape of cache.shapes)if(inside(v,shape)||shape.ts.some(t=>t.closestPointToPoint(v,new Vector3()).distanceToSquared(v)<1e-14))hits.push(i.id+':'+shape.name);return hits;});
 const water=[];for(const body of s.waterBodies??[])for(const sample of body.samples){const point:V3=[sample.point[0],(sample.point[1]+sample.bedY)/2,sample.point[2]],wet=visual(point,[body.instance]),ground=q.point([point[0],sample.bedY-.015,point[2]],undefined,true),above=q.point([point[0],sample.point[1]+.015,point[2]]);water.push({point,bedY:sample.bedY,waterY:sample.point[1],depth:sample.depth,waterPresent:wet.length>0,bedPresent:ground.length>0,terrainAboveWater:above.filter(h=>a.source!.instanceGroups&&(a.source!.instanceGroups as Record<string,string>)[h.instance]==='terrain')});}
 const exposed=[];for(const [x,z]of s.hydrology?.exposedSites??[]){const point:V3=[x,s.hydrology.waterY,z],hits=visual(point,(s.waterBodies??[]).map((r:any)=>r.instance));exposed.push({point,dry:!hits.length,actualStone:q.point(point).length>0});}
 const plants:any[]=[];const visit=(v:any)=>{if(!v||typeof v!=='object')return;if(v.rootSamples&&v.instance){const i=a.instances.find(i=>i.id===v.instance)!;for(const point of v.rootSamples){const root=visual([point[0],point[1]+.05,point[2]],[i.id]),soil=q.point([point[0],point[1]-.02,point[2]],i.id,true).filter(r=>r.material===p.styles.yunshan.surfaceSoil);plants.push({instance:i.id,point,actualRoot:!!root.length,actualSoil:!!soil.length});}}else for(const r of Object.values(v))visit(r);};visit(s.forest);visit(s.forestBelts);visit(s.bamboo);visit(s.understory);visit(s.ecologyBands);
 for(const planted of s.greenCourt?.containers??[]){const i=a.instances.find(i=>i.id===planted.plant)!,asset=p.assets[i.assetId],cells=[...q.assets.get(i.assetId)!.grid.cells()],minY=cells.reduce((y,[v])=>Math.min(y,asset.origin[1]+v[1]*asset.cellSize),Infinity);for(const[v]of cells.filter(([v])=>Math.abs(asset.origin[1]+v[1]*asset.cellSize-minY)<1e-7)){const point=q.world(i,v.map((n,d)=>asset.origin[d]+(n+(d===1?0:.5))*asset.cellSize)as V3),root=visual([point[0],point[1]+.05,point[2]],[i.id]),soil=q.point([point[0],point[1]-.02,point[2]],i.id,true).filter(r=>r.material===p.styles.yunshan.surfaceSoil);plants.push({instance:i.id,point,actualRoot:!!root.length,actualSoil:!!soil.length});}}
 const vines=[];for(const instance of s.greenCourt?.vines??[]){const i=a.instances.find(i=>i.id===instance)!,asset=p.assets[i.assetId];for(const port of asset.ports.filter(p=>p.id.startsWith('holdfast'))){const x=Math.round(port.position[0]/asset.cellSize)*asset.cellSize+asset.cellSize/2,y=Math.round(port.position[1]/asset.cellSize)*asset.cellSize+asset.cellSize/2,root=q.world(i,[x,y,-asset.cellSize/2]),wall=q.world(i,[x,y,0]);vines.push({instance,root,wall,actualAnchor:!!visual(root,[i.id]).length,actualWall:q.point(wall,i.id,true).some(r=>r.material===p.styles.yunshan.wall)});}}
 const wildlife:any[]=[];if(s.wildlife){const bird=a.instances.find(i=>i.id===s.wildlife.bird.instance)!,asset=p.assets[bird.assetId],bounds=assetBoundsM(asset)!,bottom=asset.meshes!.flatMap(m=>{const points:V3[]=[];for(let k=0;k<m.positions.length;k+=3)if(Math.abs(m.positions[k+1]-bounds.min[1])<.00001)points.push(q.world(bird,m.positions.slice(k,k+3)as V3));return points;});for(const[v]of q.assets.get(asset.id)!.grid.cells())if(Math.abs(asset.origin[1]+v[1]*asset.cellSize-bounds.min[1])<.00001)bottom.push(q.world(bird,v.map((n,d)=>asset.origin[d]+(n+(d===1?0:.5))*asset.cellSize)as V3));for(const point of bottom)wildlife.push({kind:'bird foot',point,supported:!!q.point(point,bird.id,true).length});
  for(const instance of s.wildlife.fish.instances){const i=a.instances.find(i=>i.id===instance)!,asset=p.assets[i.assetId];for(const m of asset.meshes??[])for(let k=0;k<m.positions.length;k+=30){const point=q.world(i,m.positions.slice(k,k+3)as V3);wildlife.push({kind:'fish surface',point,inActualWater:!!visual(point,s.waterBodies.map((r:any)=>r.instance)).length,landIntersection:!!q.point(point).length});}}
  for(const instance of s.wildlife.insects.instances){const i=a.instances.find(i=>i.id===instance)!,bounds=assetBoundsM(p.assets[i.assetId])!;const report=q.clear('actual insect air volume',q.world(i,bounds.min),q.world(i,bounds.max),[i.id]);wildlife.push({kind:'insect static air volume',clear:report.clear});}
 }
 return{water,exposed,plants,vines,wildlife,scope:'Finite actual visual/physical geometry only; no flow, ecology, wading or source world binding.'};
}
