import assert from 'node:assert/strict';import {Matrix4,Vector3,Ray} from 'three';import {productionProject} from '../../src/production/style';import {makeHeadwearAsset,headwearRecipes,headwearVariants} from '../../src/production/atlas-headwear';import {makeAvatarAsset} from '../../src/production/atlas-avatar';import {makeFigureAsset,figureProportions} from '../../src/production/atlas-figure';import {fittingHead} from '../../src/production/headwear-face';import {browSlot,seatedHeadFrame} from '../../src/production/headwear-assembly';import {characterPlacements} from '../../src/production/character-assembly';import {displayMesh} from '../../src/core/mesh';import {auditShape,penetration,type Shape} from './mesh-audit';import type {Asset} from '../../src/core/types';
const p=productionProject('headwear triangle audit'),s=p.styles.yunshan;
export const headwearShapes=(a:Asset,M=new Matrix4())=>displayMesh(a,p.materials).map((m,i)=>auditShape(m.meshName??'native-'+i,Array.from({length:m.positions.length/3},(_,i)=>new Vector3(...m.positions.slice(i*3,i*3+3)).applyMatrix4(M).toArray()).flat(),m.indices));
export function headwearFitAudit(){const rows=[];for(const id of Object.keys(headwearRecipes))for(const params of headwearVariants(id)){const n=Number(id.slice(5)),a=makeHeadwearAsset(id,id,id,s,params),fit=n===95?'elder':n===94?'child':String(params.headFit??params.hairFit??'adult');let head=n===94?makeAvatarAsset('CHAR-068','head','head',s,{headStage:params.headStage}):fittingHead(s,fit);if(n===98)head=browSlot(head,s.hairMass,'slot');const target=n===100?makeHeadwearAsset('CHAR-093','topknot','topknot',s):head,M=n===100?new Matrix4().makeTranslation(0,.305,.06):new Matrix4(),r={id,params,...penetration(headwearShapes(a,M),headwearShapes(target))};assert.equal(r.contained+r.crossing,0,JSON.stringify(r));rows.push(r);if(n===99){const under=makeAvatarAsset('CHAR-085','hair','hair',s,{hairFit:fit}),r={id,params,underHair:true,...penetration(headwearShapes(a),headwearShapes(under))};assert.equal(r.contained+r.crossing,0,JSON.stringify(r));rows.push(r);}}return rows;}
export function headwearTurnAudit(){const rows=[],seat=seatedHeadFrame(structuredClone(p)),seatY=characterPlacements('seated').find(t=>t.name==='head')!.position[1];for(const fit of ['adult','child'])for(const id of ['CHAR-089','CHAR-090','CHAR-091','CHAR-092','CHAR-093','CHAR-097']){if(id==='CHAR-097'&&fit==='child')continue;const a=makeHeadwearAsset(id,id,id,s,id==='CHAR-097'?{headFit:'adult'}:{hairFit:fit}),q=figureProportions[fit==='adult'?'CHAR-059':'CHAR-063'],body=makeFigureAsset(fit==='adult'?'CHAR-059':'CHAR-063','body','body',s);for(const yaw of[-30,0,30])for(const mode of fit==='adult'?['standing','seated']:['standing']){const r={id,fit,yaw,mode,...penetration(headwearShapes(a,new Matrix4().makeTranslation(0,mode==='standing'?q.heightM-q.headM:seatY,0).multiply(new Matrix4().makeRotationY(yaw*Math.PI/180))),headwearShapes(mode==='standing'?body:seat))};assert.equal(r.contained+r.crossing,0,JSON.stringify(r));rows.push(r);}}return rows;}
export function rayHits(shapes:Shape[],point:number[],direction:number[]){const ray=new Ray(new Vector3(...point),new Vector3(...direction));return shapes.flatMap(m=>m.ts.flatMap(t=>{const hit=ray.intersectTriangle(t.a,t.b,t.c,false,new Vector3());return hit?[hit.toArray()]:[];}));}
export function headwearOpeningAudit(){const removed=makeHeadwearAsset('CHAR-100','crown','removed',s,{pinState:'removed'}),inserted=makeHeadwearAsset('CHAR-100','crown','inserted',s),shapes=headwearShapes(removed);assert.equal(rayHits(shapes,[-.25,.115,0],[1,0,0]).length,0);assert.ok(rayHits(headwearShapes(inserted),[-.25,.115,0],[1,0,0]).length>0);for(const name of ['左右贯通簪槽--1','左右贯通簪槽-1']){const slot=shapes.filter(m=>m.name===name);assert.equal(slot.length,1);assert.ok(rayHits(slot,[-.25,.115,.018],[1,0,0]).length>0);}const pin=headwearShapes(inserted).filter(m=>m.name.startsWith('native-')&&m.box.min.y>=.1&&m.box.max.y<=.13),test=penetration(pin,shapes.filter(m=>m.name.startsWith('左右贯通簪槽')));assert.ok(pin.length>0);assert.equal(test.contained+test.crossing,0);
 const bearing=headwearShapes(makeHeadwearAsset('CHAR-093','topknot','topknot',s));for(const x of[-.074,.074]){const hits=rayHits(bearing,[x,.310,.06],[0,-1,0]);assert.ok(hits.some(p=>Math.abs(p[1]-.305)<1e-8));const base=rayHits(shapes,[x,-.005,0],[0,1,0]);assert.ok(base.some(p=>Math.abs(p[1])<1e-8));}
 const bald=headwearShapes(makeHeadwearAsset('CHAR-095','sparse','sparse',s));assert.equal(rayHits(bald,[.025,.35,-.020],[0,-1,0]).length,0);for(const id of ['CHAR-096','CHAR-097'])assert.equal(rayHits(headwearShapes(makeHeadwearAsset(id,id,id,s)),[0,.051,-.5],[0,0,1]).length,0);return{crownBearingContactAtSeat:true,crownThroughSlotRayClear:true,insertedPinActuallyOccupiesPassage:true,bothSlotWallsReal:true,pinSlotPenetrations:0,baldCrownOpen:true,beardMouthGapOpen:true};}
