import assert from 'node:assert/strict';import{Vector3}from'three';import{Grid}from'../../src/core/grid';import{meshAsset,displayMesh}from'../../src/core/mesh';import{dirs,type Asset,type Material,type Project}from'../../src/core/types';import{auditShape,inside,crossings,penetration,type Shape}from'./mesh-audit';import{heldScene,heldScenes}from'../../src/production/held-assembly';import{productionProject}from'../../src/production/style';import{heldIds,heldVariants,makeHeldAsset}from'../../src/production/atlas-held';
function contact(a:Shape,b:Shape){if(!a.box.clone().expandByScalar(1e-7).intersectsBox(b.box))return false;if(a.vs.some(v=>inside(v,b))||b.vs.some(v=>inside(v,a)))return true;const point=new Vector3();if(a.vs.some(v=>b.ts.some(t=>t.closestPointToPoint(v,point).distanceToSquared(v)<1e-12))||b.vs.some(v=>a.ts.some(t=>t.closestPointToPoint(v,point).distanceToSquared(v)<1e-12)))return true;return crossings(a,b)+crossings(b,a)>0;}

export function heldContactGroups(a:Asset,materials:Record<string,Material>){const shapes=(a.meshes??[]).map(m=>auditShape(m.name,m.positions,m.indices)),cells=new Map([...new Grid(a.chunks).cells()].map(([v,m])=>[v.join(','),{v,m}]));let n=0;while(cells.size){const first=cells.values().next().value!,group=[first],g=new Grid();cells.delete(first.v.join(','));for(let k=0;k<group.length;k++){const {v,m}=group[k];g.set(v,m);for(const d of dirs){const key=v.map((n,j)=>n+d[j]).join(','),c=cells.get(key);if(c){group.push(c);cells.delete(key);}}}const buckets=meshAsset({...a,meshes:undefined,rig:undefined,chunks:g.serialize()},materials),pos:number[]=[],ind:number[]=[];for(const b of buckets){const offset=pos.length/3;pos.push(...b.positions);ind.push(...b.indices.map(i=>i+offset));}shapes.push(auditShape('native-island-'+n++,pos,ind));}
 const edges=shapes.map(()=>[] as number[]);for(let i=0;i<shapes.length;i++)for(let j=i+1;j<shapes.length;j++)if(contact(shapes[i],shapes[j])){edges[i].push(j);edges[j].push(i);}const visited=new Set<number>(),groups=[];for(let i=0;i<shapes.length;i++){if(visited.has(i))continue;const group=[i];visited.add(i);for(let k=0;k<group.length;k++)for(const j of edges[group[k]])if(!visited.has(j)){visited.add(j);group.push(j);}groups.push(group.map(i=>shapes[i].name));}return groups;}
export function shapeDistance(a:Shape,b:Shape){const p=new Vector3();let d=Infinity;for(const v of a.vs)for(const t of b.ts)d=Math.min(d,t.closestPointToPoint(v,p).distanceTo(v));for(const v of b.vs)for(const t of a.ts)d=Math.min(d,t.closestPointToPoint(v,p).distanceTo(v));return d;}
const filters:Record<string,RegExp>={'CHAR-177':/^握柄外套$/,'CHAR-178':/^T形握把$/,'CHAR-179':/^腋拐独立橡胶握把$/,'CHAR-180':/^提带真握孔-1$/,'CHAR-183':/^(独立木筷|筷尾套箍)/,'CHAR-185':/^连续倾斜木柄$/,'CHAR-186':/^扫帚独立木柄$/};
export function heldSceneAudit(){const records=[],p=productionProject('held audit');for(const kind of heldScenes){const q=heldScene(p,kind),shapes=Object.values(q.instances).map(i=>({a:q.assets[i.assetId],key:i.id,sh:displayMesh(q.assets[i.assetId],q.materials).map((b,n)=>auditShape(b.meshName??'native-'+n,b.positions.map((v,k)=>v+i.position[k%3]),b.indices))}));for(let i=0;i<shapes.length;i++)for(let j=i+1;j<shapes.length;j++){if(kind==='belt'&&!shapes[i].key.endsWith('-belt')&&!shapes[j].key.endsWith('-belt'))continue;const x=shapes[i],y=shapes[j],r=penetration(x.sh,y.sh);assert.equal(r.contained+r.crossing,0,JSON.stringify({kind,a:x.key,b:y.key,...r}));if(r.pairs)records.push({kind,a:x.key,b:y.key,...r});}
 for(const h of shapes.filter(x=>x.a.source?.heldCatalogId)){const id=String(h.a.source!.heldCatalogId),prop=shapes.find(x=>x.a.source?.catalogId===id&&x.a.category==='base')!,target=prop.sh.filter(t=>!filters[id]||filters[id].test(t.name)),distances=h.sh.filter(t=>/独立指节|拇指|裸露掌面/.test(t.name)).map(t=>({part:t.name,metres:Math.min(...target.map(x=>shapeDistance(t,x)))})).sort((a,b)=>a.metres-b.metres);if(filters[id])assert.ok(distances[1].metres<.006,id+' needs at least two nearby skin segments');else assert.ok(distances.find(x=>x.part==='裸露掌面')!.metres<=.0061,id+' palm-root proximity');records.push({kind,id,distances,mode:filters[id]?'finite grip':'palm-root support',noPhysicalLoadClaim:true});}}
 return records;}
export function heldApertureAudit(){const p=productionProject('apertures'),rows=[];for(const id of heldIds)for(const params of heldVariants(id)){const a=makeHeldAsset(id,id,id,p.styles.yunshan,params),meshes=displayMesh(a,p.materials).map((b,n)=>auditShape(b.meshName??'native-'+n,b.positions,b.indices)),checks:{name:string;point:[number,number,number];solid:boolean;filter?:RegExp}[]=[];const add=(name:string,point:[number,number,number],solid=false,filter?:RegExp)=>checks.push({name,point,solid,filter});
 if(id==='CHAR-149'){const rz=params.beltFit==='adultB'?.177:.158,k=params.beltFit==='adultB'?1.1:1;add('waist through',[0,.035,0]);for(const side of[-1,1]){add('pouch cavity'+side,[side*.15*k,-.03,-rz-.04]);add('pouch floor'+side,[side*.15*k,-.083,-rz-.04],true);}}
 if(id==='CHAR-150'){const H=params.badgeType==='chest'?.118:.07;add('4mm clip slot',[0,H-.035,.010]);add('clip bridge',[0,H-.010,.010],true);}
 if(id==='CHAR-177'){const edge=params.canopy==='open'?.64:.27;add('canopy underside clear',[params.canopy==='open'?.15:.035,edge-.020,0]);}
 if(id==='CHAR-180'){const h=params.bag==='open'?.3:.055,rz=params.bag==='open'?.07:.045;add('bag cavity',[0,h*.5,0]);add('bag real floor',[0,.002,0],true);add('handle through',[0,params.bag==='open'?.357:.068,-rz+.009]);}
 if(id==='CHAR-181'){add('paper cavity',[0,.1,0],false,/食品纸袋真壁底/);add('paper floor',[0,.001,0],true,/食品纸袋真壁底/);}
 if(id==='CHAR-182'){add('canonical bowl cavity',[.105,.085,.105],false,/native/);add('canonical bowl floor',[.105,.025,.105],true,/native/);}
 if(id==='CHAR-183')add('separate chopsticks gap',[0,.125,0]);
 if(id==='CHAR-184'){add('cup internal cavity',[0,.065,0]);add('cup solid floor',[0,.002,0],true);add('cup handle through',[.075,.071,0]);if(params.lid==='removed')add('uncovered mouth',[0,.135,0]);else add('closed lid',[0,.135,0],true);}
 if(id==='CHAR-185'){add('ladle real cavity',[0,.025,0]);add('ladle solid floor',[0,.0015,0],true);}
 if(id==='CHAR-186')add('broom loop through',[.032,(params.length==='full'?1.22:.66)-.085,0]);
 for(const c of checks){const hit=meshes.filter(m=>!c.filter||c.filter.test(m.name)).some(m=>inside(new Vector3(...c.point),m));assert.equal(hit,c.solid,id+JSON.stringify(params)+' '+c.name);rows.push({id,params,name:c.name,point:c.point,expectedSolid:c.solid,actualSolid:hit});}}return rows;}
