import {Vector3} from 'three';import type {Project,Assembly,V3} from '../../src/core/types';import {CivicAudit} from './civic-audit';import {inside} from './mesh-audit';
export function institutionalAudit(p:Project,a:Assembly){
 const q=new CivicAudit(p,a),r=(a.source as any).room;
 const visual=(point:V3,id:string)=>{const i=a.instances.find(i=>i.id===id)!;if(!i)throw new Error('Missing actual instance '+id);const asset=p.assets[i.assetId],local=q.local(i,point),v=new Vector3(...local),c=q.assets.get(i.assetId)!;return!!c.grid.get(local.map((n,k)=>Math.floor((n-asset.origin[k])/asset.cellSize))as V3)||c.shapes.some(sh=>inside(v,sh)||sh.ts.some(t=>t.closestPointToPoint(v,new Vector3()).distanceToSquared(v)<1e-14));};
 const bundledSeats=(r.bundledSeats??[]).map((s:any)=>{const v=s.point as V3;return{...s,seatPresent:visual([v[0],v[1]-.015,v[2]],s.instance),lowerBody:q.clear('finite lower body including entire bundled seat',[v[0]-.14,v[1]+.03,v[2]-.17],[v[0]+.14,s.lowerTop,v[2]+.17]),torso:q.clear('finite upper torso above armrests including entire bundled seat',[v[0]-.19,s.lowerTop+.01,v[2]-.19],[v[0]+.19,v[1]+.96,v[2]+.19]),approach:q.head('bundled-seat approach',s.approach,.7,1.72),wholeSetExcluded:false};});
 const volumes=(r.clearVolumes??[]).map((v:any)=>q.clear(v.key,v.min,v.max));
 const stage=(r.stageChecks??[]).flatMap((s:any)=>{const instance=a.instances.find(i=>i.id===s.instance)!,asset=p.assets[instance.assetId],part=(asset.source!.componentIndexRanges as any[]).find(c=>c.name==='连续木坡道'),mesh=asset.meshes!.find(m=>m.name===part.mesh)!,ys=[];let slope=0;for(const index of mesh.indices.slice(part.firstIndex,part.firstIndex+part.indexCount)){const normal=mesh.normals.slice(index*3,index*3+3);if(normal[1]>.01){slope=Math.max(slope,Math.hypot(normal[0],normal[2])/normal[1]);ys.push(mesh.positions[index*3+2]);}}const endZ=Math.max(...ys);return s.points.map((v:V3)=>({point:v,actualStageBearing:visual([v[0],v[1]-.015,v[2]],s.instance),independentSlope:slope,declaredSlopeMatches:Math.abs(slope-s.actualRampSlope)<1e-8,actualFootprintSlope:v[2]<endZ?slope:0,body:q.clear('stage actual body above sloped footprint',[v[0]-.3,v[1]+.025+(v[2]<endZ?slope*.3:0),v[2]-.3],[v[0]+.3,v[1]+1.72,v[2]+.3])}));});
 return{bundledSeats,volumes,stage,scope:'Finite author body envelopes with complete bundled desk/chair sets included. Static actual vault cavity, fixed bunk opening, open partition and supported ramp do not establish clinical, security, engineering, accessibility or runtime functionality.'};
}
