import {Vector3} from 'three';
import type {Project,Assembly,V3} from '../../src/core/types';
import {CivicAudit} from './civic-audit';
import {inside} from './mesh-audit';

/** Nonphysical foods are inspected as visible geometry, never via an empty collision list. */
export function lifeSpaceAudit(p:Project,a:Assembly){
 const q=new CivicAudit(p,a),s=a.source as any,r=s.room;
 const visual=(point:V3,id:string)=>{const i=a.instances.find(i=>i.id===id)!;if(!i)throw new Error('Missing audit instance '+id);const asset=p.assets[i.assetId],local=q.local(i,point),c=q.assets.get(i.assetId)!,v=new Vector3(...local);return!!c.grid.get(local.map((n,k)=>Math.floor((n-asset.origin[k])/asset.cellSize))as V3)||c.shapes.some(sh=>inside(v,sh)||sh.ts.some(t=>t.closestPointToPoint(v,new Vector3()).distanceToSquared(v)<1e-14));};
 const students=(r?.studentStations??[]).map((st:any)=>{const v=st.seat as V3,body=q.clear('seated torso with own desk and chair included',[v[0]-.21,v[1]+.06,v[2]-.21],[v[0]+.21,v[1]+.98,v[2]+.21]),approach=q.head('station side approach',st.approach,.7,1.72);return{...st,seatPresent:visual([v[0],v[1]-.015,v[2]],st.instance),body,approach,footPresent:!!q.point([st.approach[0],-.02,st.approach[2]]).length,deskPresent:visual([st.deskTop[0],st.deskTop[1]-.005,st.deskTop[2]],st.instance),wholeStationExcluded:false};});
 const drain=r?.drain?q.clear('through actual floor, waterproofing, sleeve and grate',r.drain.clearMin,r.drain.clearMax):null,basin=r?.basin?q.clear('actual empty wash basin',r.basin.clearMin,r.basin.clearMax):null;
 const door=r?.privacyDoor?{state:r.privacyDoor.state,entry:q.clear('finite entry body',[r.dimensions[0]/2-.35,.03,-.12],[r.dimensions[0]/2+.35,1.72,.45]),occluded:q.point([r.dimensions[0]/2,1.1,0],undefined,true).some(h=>h.instance===r.privacyDoor.instance),hinge:r.privacyDoor.hinge,entryOcclusionOnly:true}:null;
 const meals=s.meal?{tabletopOnly:s.meal.tabletopOnly,bearings:s.meal.bearings.map((v:any)=>({...v,lowerPresent:visual([v.point[0],v.point[1]-.002,v.point[2]],v.lower),upperPresent:visual([v.point[0],v.point[1]+.002,v.point[2]],v.upper)})),vessels:s.meal.vessels.map((v:any)=>{const[x,y,z]=v.center,liquidOrRice=v.food==='rice'||v.food==='soup',ingredientAsset=p.assets[a.instances.find(i=>i.id===v.ingredient)!.assetId],shapes=q.assets.get(ingredientAsset.id)!.shapes,base=shapes.find(sh=>/食材基底|米饭|汤汁/.test(sh.name))!,ingredientContacts=shapes.filter(sh=>sh!==base).map(sh=>({part:sh.name,contact:sh.ts.some(t=>[t.a,t.b,t.c,t.getMidpoint(new Vector3())].some(v=>inside(v,base)||base.ts.some(t=>t.closestPointToPoint(v,new Vector3()).distanceToSquared(v)<1e-14)))}));return{...v,ingredientContacts,bottomPresent:visual([x,y+.003,z],v.instance),ingredientPresent:visual([x,y+(liquidOrRice?v.level/2:.016),z],v.ingredient),ingredientTouchesBowl:visual([x,y+.009,z],v.instance)&&visual([x,y+.009,z],v.ingredient),airAbove:q.clear('space above dish',[x-.018,y+v.h+.06,z-.018],[x+.018,y+v.h+.09,z+.018]),cavityProbeNotBowl:!visual([x,y+v.h*.6,z],v.instance),rimPresent:visual([x,y+v.h-.004,z-v.r+.003],v.instance)};})}:null;
 let awning:any=null;if(r?.awning){const contacts=[];for(const x of[.2775,3.2775])for(const z of[1.9775,3.5275]){const matches=q.point([x,2.40+(z-1.9)*.36+.035*Math.sin((z-1.9)/1.7*Math.PI)-.009,z]).filter(v=>v.instance===r.awning);contacts.push({point:[x,z],fabricAndSupport:matches.some(v=>v.material===p.styles.yunshan.canvas)&&matches.some(v=>v.material===p.styles.yunshan.metalBright)});}awning={contacts};}
 return{students,drain,basin,door,meals,awning,scope:'Actual occupied cells, independent closed-part triangles and finite body volumes. Seated student checks include the complete two-island workstation; foods are queried despite nonphysical roles. No control, inventory, fluid, full privacy or structural certification.'};
}
