import {Vector3} from 'three';
import type {Assembly,Project,V3} from '../../src/core/types';
import {CivicAudit} from './civic-audit';

/** These checks query actual triangles/native cells. Descriptors choose the places,
 * but cannot make an absent rail, chair contact, drain opening or route become real. */
export function parkAudit(p:Project,a:Assembly){
 const q=new CivicAudit(p,a),s=(a.source as any).park,pads=[],guards=[],seats=[],rocks=[],drains=[],views=[],activities=[],maps=[];
 for(const pad of s.pads){const[x,z,X,Z]=pad.rect;for(const xx of[x+Math.min(.8,(X-x)/3),X-Math.min(.8,(X-x)/3)])for(const zz of[z+Math.min(.8,(Z-z)/3),Z-Math.min(.8,(Z-z)/3)]){const point:V3=[xx,pad.bottom-.02,zz],hits=q.point(point,pad.instance,true);pads.push({instance:pad.instance,point,bearingPresent:!!hits.length,hits});}}
 for(const g of s.guards){const count=Math.ceil(g.width/.35);for(let j=1;j<count;j++){const point=g.from.map((n:number,d:number)=>n+(g.to[d]-n)*j/count)as V3,body=q.clear(g.key+' body obstruction',[point[0]-.25,point[1]+.2,point[2]-.25],[point[0]+.25,point[1]+1.5,point[2]+.25]);guards.push({instance:g.instance,point,actualRailObstructsBody:body.blocked.some(h=>h.instance===g.instance)});}}
 for(const seat of s.seats){const v=seat.point as V3,ap=seat.approach as V3,foot=q.point([v[0],v[1]-.02,v[2]],undefined,true),body=q.clear('actual seated torso',[v[0]-.22,v[1]+.06,v[2]-.18],[v[0]+.22,v[1]+1.15,v[2]+.18]),approach=q.clear('actual seat approach',[ap[0]-.3,ap[1]+.025,ap[2]-.3],[ap[0]+.3,ap[1]+1.72,ap[2]+.3]);seats.push({...seat,seatPresent:foot.some(h=>h.instance===seat.instance),torsoClear:body.clear,approachClear:approach.clear,approachSupported:!!q.point([ap[0],ap[1]-.02,ap[2]],seat.instance,true).length,blocked:body.blocked.concat(approach.blocked)});}
 for(const rock of s.rockContacts){const samples=rock.samples.map((point:V3)=>({point,lower:q.point([point[0],point[1]-.01,point[2]],rock.instance,true),upper:q.point([point[0],point[1]+.01,point[2]],undefined,true).filter(h=>h.instance===rock.instance)}));rocks.push({...rock,samples,actualContactCount:samples.filter((r:any)=>r.lower.length&&r.upper.length).length,contactsPresent:samples.filter((r:any)=>r.lower.length&&r.upper.length).length>=rock.minimumContacts});}
 for(const drain of s.drains)for(const point of [...drain.points,...drain.openEnds]){const body=q.clear('real open drain',[point[0]-.08,point[1]-.07,point[2]-.08],[point[0]+.08,point[1]+.07,point[2]+.08]),base=q.point([point[0],point[1]-.16,point[2]],undefined,true);drains.push({point,open:body.clear,actualBottom:base.some(h=>h.instance===drain.instance),blocked:body.blocked});}
 for(const view of s.viewRays){const samples=[];for(let j=1;j<40;j++){const v=view.from.map((n:number,d:number)=>n+(view.to[d]-n)*j/40)as V3;samples.push({point:v,blocked:q.point(v).filter(h=>!view.exclude.includes(h.instance))});}views.push({...view,samples,clear:samples.every(r=>!r.blocked.length)});}
 for(const activity of s.activityPoints){const v=activity.point as V3,r=activity.radius,body=q.clear('actual finite activity place',[v[0]-r,v[1]+.025,v[2]-r],[v[0]+r,v[1]+1.72,v[2]+r]);activities.push({...activity,clear:body.clear,footPresent:!!q.point([v[0],v[1]-.02,v[2]],undefined,true).length,boundSocialState:false,blocked:body.blocked});}
 for(const map of s.wayfinding){const i=a.instances.find(i=>i.id===map.instance)!,asset=p.assets[i.assetId],ink=asset.meshes!.filter(m=>m.material===p.styles.yunshan.printedMark),points=map.segments.map((r:any)=>{const mid=r.from.map((n:number,d:number)=>(n+r.to[d])/2)as V3,point:V3=[map.at[0]+mid[0]*.105,map.at[1]+2-mid[2]*.07,map.at[2]-.096],shapes=q.assets.get(i.assetId)!.shapes.filter(m=>m.material===p.styles.yunshan.printedMark),v=new Vector3(...q.local(i,point));return{point,route:r.route,sourceRouteExists:(a.source!.routes as any[]).some(r2=>r2.name===r.route),inkPresent:shapes.some(shape=>shape.ts.some(t=>t.closestPointToPoint(v,new Vector3()).distanceTo(v)<.025))};});maps.push({instance:i.id,inkMeshes:ink.length,points,actualRouteInk:points.every((r:any)=>r.sourceRouteExists&&r.inkPresent),originalPlaceIdentityBound:false});}
 return{pads,guards,seats,rocks,drains,views,activities,maps,scope:'Finite actual collision obstruction/contact/clearance and physical printed routes. No public safety, equilibrium, ecology or social simulation certification.'};
}
