import assert from 'node:assert/strict';import {Vector3} from 'three';import type {V3,Asset,Material} from '../../src/core/types';import {displayMesh} from '../../src/core/mesh';import {productionProject} from '../../src/production/style';import {serviceIds,serviceVariants,makeServiceAsset} from '../../src/production/atlas-service';import {auditShape,inside,penetration} from './mesh-audit';import {shapeDistance} from './held-audit';import {serviceScene,serviceScenes} from '../../src/production/service-assembly';
/** Material buckets may be open by themselves: merge native surfaces by actual rigid owner before solid-ray checks. */
export function serviceShapes(a:Asset,materials:Record<string,Material>,offset:V3=[0,0,0]){const native=new Map<string,{positions:number[];indices:number[]}>(),out=[];for(const b of displayMesh(a,materials)){const positions=b.positions.map((v,k)=>v+offset[k%3]);if(b.meshName)out.push(auditShape(b.meshName,positions,b.indices));else{const key='native-'+(b.bindingJoint??'root'),m=native.get(key)??{positions:[],indices:[]},start=m.positions.length/3;m.positions.push(...positions);m.indices.push(...b.indices.map(i=>i+start));native.set(key,m);}}for(const[name,m]of native)out.push(auditShape(name,m.positions,m.indices));return out;}
export const serviceGripFilters:Record<string,RegExp>={'CHAR-188':/提桶塑料握柄/,'CHAR-190':/独立粗毛笔木杆/,'CHAR-193':/听头短握柄/,'CHAR-194':/急救箱提把横握柄/,'CHAR-195':/诊疗探头握柄/,'CHAR-196':/提灯提把横握柄/,'CHAR-197':/通信器连续侧握胶|通信器独立机壳/,'CHAR-198':/勤务棍独立握胶|握胶连续凸环/};
export function serviceSceneAudit(){const p=productionProject('M040 hand audit'),records=[];for(const kind of serviceScenes){const q=serviceScene(p,kind),shapes=Object.values(q.instances).map(i=>({a:q.assets[i.assetId],key:i.id,sh:serviceShapes(q.assets[i.assetId],q.materials,i.position)}));for(let i=0;i<shapes.length;i++)for(let j=i+1;j<shapes.length;j++){const x=shapes[i],y=shapes[j],r=penetration(x.sh,y.sh);assert.equal(r.contained+r.crossing,0,JSON.stringify({kind,a:x.key,b:y.key,...r}));}for(const h of shapes.filter(x=>x.a.source?.serviceCatalogId)){const id=String(h.a.source!.serviceCatalogId),prop=shapes.find(x=>x.a.source?.catalogId===id&&x.a.category==='base')!,filter=serviceGripFilters[id],strap=['CHAR-191','CHAR-192'].includes(id),target=prop.sh.filter(t=>filter?filter.test(t.name):!strap||t.name==='背部真空握带'),distances=h.sh.filter(t=>/独立指节|拇指|裸露掌面/.test(t.name)).map(t=>({part:t.name,metres:Math.min(...target.map(x=>shapeDistance(t,x)))})).sort((a,b)=>a.metres-b.metres);if(filter)assert.ok(distances[1].metres<.006,id+' two skin segments must be near the actual grip');else assert.ok(distances.find(x=>x.part==='裸露掌面')!.metres<.0061,id+' palm support gap');records.push({kind,id,mode:filter?'finite grip':strap?'rear-strap support':'palm-root support',distances,nonpenetration:true,noPhysicalLoadClaim:true});}}return records;}
export function serviceApertureAudit(){const p=productionProject('M040 apertures'),rows=[];for(const id of serviceIds)for(const params of serviceVariants(id)){const a=makeServiceAsset(id,id,id,p.styles.yunshan,params),meshes=serviceShapes(a,p.materials),checks:{name:string;point:V3;solid:boolean;filter?:RegExp}[]=[];const add=(name:string,point:V3,solid=false,filter?:RegExp)=>checks.push({name,point,solid,filter});
if(id==='CHAR-187')add('fold interior',[0,params.clothForm==='draped'?.10:.055,0]);
if(id==='CHAR-188'){add('metal floor',[0,.003,0],true,/金属壁底/);add('open mouth',[0,.245,0]);add('vessel cavity',[0,.10,0],false,/金属壁底/);add('real handle through',[0,.35,0]);if(params.contents==='water')add('water is separate',[0,.10,0],true,/静态水体/);}
if(id==='CHAR-189'){add('original lower page block',[.1023,.0221,.1527],true,/native/);if(params.bookForm==='open')add('rigidly opened upper page block',[-.1023,.0211,.1527],true,/native/);if(params.bookForm==='open'){const r=penetration(meshes.filter(m=>m.name==='native-root'),meshes.filter(m=>m.name==='native-upper-pages'));assert.equal(r.contained+r.crossing,0,'opened book rigid page blocks must not intersect');}add('reading space above',[.10,.08,.15]);}
if(id==='CHAR-190')add('brush hanging eye',[0,.423,0]);
if(id==='CHAR-191'||id==='CHAR-192'){const h=id==='CHAR-191'?(params.orientation==='landscape'?.235:.32):.32,z=id==='CHAR-191'?.016:.008;add('rear strap passage',[0,h*.5,z+.04]);add('rear strap real outer strip',[0,h*.5,z+.068],true);if(id==='CHAR-192')add('physical paper',[0,.15,-.0095],true,/独立记录纸/);}
if(id==='CHAR-193'){add('ear tube central space',[0,.40,0]);add('chestpiece solid centre',[params.hoseForm==='extended'?.20:.075,.23,0],true,/诊察金属圆头/);}
if(id==='CHAR-194'){add('case cavity',[0,.10,0]);add('case solid floor',[0,.004,0],true);add('lid closed or removed',[0,.23,0],params.lid==='closed');add('raised handle through',[params.lid==='removed'?.43:0,.285,0]);}
if(id==='CHAR-195'){add('probe front optics',[0,.24,-.0795],true,/前光学片/);add('probe solid grip',[0,.09,0],true,/探头握柄/);}
if(id==='CHAR-196'){add('glass front',[0,.15,-.059],true,/透明玻璃罩/);add('inside lamp free volume',[.045,.15,0]);add('physical core',[0,.15,0],true,/未绑定灯芯/);add('base floor',[0,.012,0],true);if(params.handleForm==='raised')add('raised handle void',[0,.325,0]);else add('lowered handle void',[0,.275,.083]);}
if(id==='CHAR-197'){add('back clip slot',[0,.10,.023]);add('back clip outer piece',[0,.10,.028],true);add('back clip bridge',[0,.15,.023],true);}
if(id==='CHAR-198')add('wrist loop real aperture',[.046,.074,0]);
for(const c of checks){const hit=meshes.filter(m=>!c.filter||c.filter.test(m.name)).some(m=>inside(new Vector3(...c.point),m));assert.equal(hit,c.solid,id+JSON.stringify(params)+' '+c.name);rows.push({id,params,name:c.name,point:c.point,expectedSolid:c.solid,actualSolid:hit});}}return rows;}
