import type {Asset,Material,V3} from './types';
import type {MeshBucket} from './mesh';
/** Metre-space vertices are authoritative; these faces are not voxel proxies. */
export type AuthoredMesh={name:string;material:number;positions:number[];normals:number[];uvs:number[];indices:number[];collision:boolean};
export function validateAuthoredMeshes(a:Asset,materials?:Record<string,Material>){if(!a.meshes)return;if(a.sky||!Array.isArray(a.meshes)||a.meshes.length>64)throw new Error('无效混合网格组件');let triangles=0;for(const m of a.meshes){const n=m.positions?.length/3;if(!m.name||!Number.isInteger(m.material)||m.material<1||typeof m.collision!=='boolean'||!Number.isInteger(n)||n<3||n>150000||m.normals?.length!==n*3||m.uvs?.length!==n*2||!m.indices?.length||m.indices.length%3||[...m.positions,...m.normals,...m.uvs].some(x=>!Number.isFinite(x)||Math.abs(x)>65536)||m.indices.some(i=>!Number.isInteger(i)||i<0||i>=n))throw new Error('网格数组、坐标或预算无效');for(let i=0;i<m.normals.length;i+=3)if(Math.abs(Math.hypot(...m.normals.slice(i,i+3))-1)>.001)throw new Error('网格法线无效');if(materials&&(!materials[m.material]||m.collision!==materials[m.material].solid))throw new Error('网格用途材质/碰撞声明不一致');triangles+=m.indices.length/3;}if(triangles>100000)throw new Error('混合网格超出预算');}
export function authoredBuckets(a:Asset):MeshBucket[]{return(a.meshes??[]).map(m=>({material:m.material,positions:m.positions.map((v,i)=>v+a.origin[i%3]),normals:[...m.normals],uvs:[...m.uvs],indices:[...m.indices],quads:0}));}
/** Closed, flat-shaded convex prism; top surfaces may slope continuously. */
export function profilePrism(name:string,material:number,x0:number,x1:number,profile:[number,number][]):AuthoredMesh{const points:V3[]=[x0,x1].flatMap(x=>profile.map(([z,y])=>[x,y,z] as V3)),N=profile.length,faces:number[][]=[Array.from({length:N},(_,i)=>i),Array.from({length:N},(_,i)=>N+i),...profile.map((_,i)=>[i,(i+1)%N,(i+1)%N+N,i+N])],center=points.reduce((s,p)=>s.map((v,i)=>v+p[i]/points.length) as V3,[0,0,0]),m:AuthoredMesh={name,material,positions:[],normals:[],uvs:[],indices:[],collision:true};
 for(let face of faces){let p=face.map(i=>points[i]);const u=p[1].map((v,i)=>v-p[0][i]),v=p[2].map((v,i)=>v-p[0][i]);let n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];const fc=p.reduce((s,p)=>s.map((v,i)=>v+p[i]/p.length) as V3,[0,0,0] as V3);if(n.reduce((s,v,i)=>s+v*(fc[i]-center[i]),0)<0){p=p.reverse();n=n.map(v=>-v);}const L=Math.hypot(...n);if(L<1e-10)throw new Error('退化坡面');n=n.map(v=>v/L||0);const start=m.positions.length/3;for(const point of p){m.positions.push(...point);m.normals.push(...n);m.uvs.push(point[Math.abs(n[0])>.9?2:0],Math.abs(n[1])>.5?point[2]:point[1]);}for(let i=1;i<p.length-1;i++)m.indices.push(start,start+i,start+i+1);
 }return m;}
