import {Matrix4,Quaternion,Vector3} from 'three';
import {Grid} from './grid';
import type {Asset,Bounds,Material,V3} from './types';
import type {MeshBucket} from './mesh';
export type RigJoint={id:string;parent:string|null;translation:V3};
/** Rigid per-component skinning: native blocks remain in bind space, never revoxelised. */
export type RigDescriptor={version:1;kind:'humanoid'|'hand'|'first-person'|'prop';joints:RigJoint[];meshJoints:Record<string,string>;voxelJoints:{region:Bounds;joint:string}[];sockets:Record<string,string>;pose:Record<string,[number,number,number,number]>;authority:'author';originalSkeletonBound:false};
const finiteV=(v:unknown,n:number,limit=100)=>Array.isArray(v)&&v.length===n&&v.every(x=>typeof x==='number'&&Number.isFinite(x)&&Math.abs(x)<limit);
export function validateRig(a:Asset,materials?:Record<string,Material>){const r=a.rig;if(!r)return;if(r.version!==1||!['humanoid','hand','first-person','prop'].includes(r.kind)||r.authority!=='author'||r.originalSkeletonBound!==false||!Array.isArray(r.joints)||!r.joints.length||r.joints.length>128||!a.meshes?.length||a.sky)throw new Error('无效绑定描述或预算');
 const ids=new Set<string>();for(const j of r.joints){if(!/^[a-zA-Z0-9_-]{1,64}$/.test(j.id)||ids.has(j.id)||j.parent!==null&&!ids.has(j.parent)||!finiteV(j.translation,3))throw new Error('关节须唯一、父级在前且局部平移有效');ids.add(j.id);}if(r.joints.filter(j=>j.parent===null).length!==1)throw new Error('绑定须有单一根关节');
 const names=new Set(a.meshes.map(m=>m.name));if(names.size!==a.meshes.length||Object.keys(r.meshJoints).length!==names.size||Object.entries(r.meshJoints).some(([n,j])=>!names.has(n)||!ids.has(j)))throw new Error('每个连续组件须唯一绑定到实际关节');if(a.meshes.some(m=>m.collision)||a.openings.length)throw new Error('当前关节绑定仅支持非碰撞视觉组件');
 if(!Array.isArray(r.voxelJoints)||r.voxelJoints.length>256)throw new Error('原生块绑定区域无效');for(const b of r.voxelJoints)if(!ids.has(b.joint)||![b.region?.min,b.region?.max].every(v=>finiteV(v,3,65536))||[...b.region.min,...b.region.max].some(v=>!Number.isInteger(v))||b.region.max.some((v,i)=>v<=b.region.min[i]))throw new Error('原生块绑定区域须是整数半开格范围');
 for(const[v,m]of new Grid(a.chunks).cells()){if(materials?.[m]?.solid)throw new Error('绑定块不得为物理碰撞');if(r.voxelJoints.filter(b=>v.every((n,i)=>n>=b.region.min[i]&&n<b.region.max[i])).length!==1)throw new Error('每个原生块须恰有一个关节绑定');}
 if(Object.keys(r.sockets).length!==a.ports.length||Object.entries(r.sockets).some(([port,j])=>!a.ports.some(p=>p.id===port)||!ids.has(j)))throw new Error('挂点须关联实际关节');
 for(const[id,q]of Object.entries(r.pose))if(!ids.has(id)||!finiteV(q,4)||Math.abs(Math.hypot(...q)-1)>1e-6)throw new Error('关节姿态四元数无效');
}
export function rigMatrices(a:Asset){const r=a.rig!;const bind:Matrix4[]=[],posed:Matrix4[]=[],indices=new Map(r.joints.map((j,i)=>[j.id,i]));for(const j of r.joints){const local=new Matrix4().makeTranslation(...j.translation),position=new Vector3(...j.translation);if(j.parent===null){position.add(new Vector3(...a.origin));local.setPosition(position);}const current=new Matrix4().compose(position,new Quaternion(...(r.pose[j.id]??[0,0,0,1])),new Vector3(1,1,1)),parent=j.parent===null?-1:indices.get(j.parent)!;bind.push(parent<0?local:bind[parent].clone().multiply(local));posed.push(parent<0?current:posed[parent].clone().multiply(current));}return{bind,posed,skin:bind.map((b,i)=>posed[i].clone().multiply(b.clone().invert())),indices};}
const rounded=(v:Vector3)=>v.toArray().map(x=>Math.round(x*1e9)/1e9||0) as V3;
export function rigPoint(a:Asset,p:V3,joint:string,normal=false):V3{const m=rigMatrices(a),v=new Vector3(...p),matrix=m.skin[m.indices.get(joint)!];return rounded(normal?v.transformDirection(matrix):v.applyMatrix4(matrix));}
export function posedRigPorts(a:Asset){if(!a.rig)return a.ports;return a.ports.map(p=>({...p,position:rigPoint(a,p.position.map((v,i)=>v+a.origin[i]) as V3,a.rig!.sockets[p.id]),normal:rigPoint(a,p.normal,a.rig!.sockets[p.id],true),space:'posed asset metres including origin'}));}
/** Ownership is attached before material grouping, keeping coincident joints independent. */
export function rigBuckets(a:Asset,buckets:MeshBucket[],bindPose=false):MeshBucket[]{const r=a.rig!;const matrices=rigMatrices(a);return buckets.map(b=>{const out={...b,positions:[...b.positions],normals:[...b.normals],joints:[] as number[],weights:[] as number[]};for(let i=0;i<b.positions.length;i+=3){const point=b.positions.slice(i,i+3) as V3;const joint=b.meshName?r.meshJoints[b.meshName]:b.bindingJoint;if(!joint)throw new Error('网格桶缺少组件绑定');const index=matrices.indices.get(joint)!;out.joints.push(index,0,0,0);out.weights.push(1,0,0,0);if(!bindPose){const p=new Vector3(...point).applyMatrix4(matrices.skin[index]),n=new Vector3(...b.normals.slice(i,i+3)).transformDirection(matrices.skin[index]);out.positions.splice(i,3,...rounded(p));out.normals.splice(i,3,...rounded(n));}}return out;});}
export function rigBounds(a:Asset):Bounds|null{const m=rigMatrices(a),points:Vector3[]=[],r=a.rig!;for(const mesh of a.meshes??[]){const matrix=m.skin[m.indices.get(r.meshJoints[mesh.name])!];for(let k=0;k<mesh.positions.length;k+=3)points.push(new Vector3(...mesh.positions.slice(k,k+3).map((v,i)=>v+a.origin[i])).applyMatrix4(matrix));}for(const[v]of new Grid(a.chunks).cells()){const owner=r.voxelJoints.find(b=>v.every((n,i)=>n>=b.region.min[i]&&n<b.region.max[i]))!;for(const x of[0,1])for(const y of[0,1])for(const z of[0,1])points.push(new Vector3(...v.map((n,i)=>(n+[x,y,z][i])*a.cellSize+a.origin[i])).applyMatrix4(m.skin[m.indices.get(owner.joint)!]));}if(!points.length)return null;const min:V3=[Infinity,Infinity,Infinity],max:V3=[-Infinity,-Infinity,-Infinity];for(const p of points)for(let d=0;d<3;d++){min[d]=Math.min(min[d],p.getComponent(d));max[d]=Math.max(max[d],p.getComponent(d));}return{min:min.map(v=>Math.round(v*1e9)/1e9||0) as V3,max:max.map(v=>Math.round(v*1e9)/1e9||0) as V3};}
