import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {chromium} from 'playwright';
import {validationBrowserOptions} from './browser-options';
import {productionProject} from '../src/production/style';
import {parseCatalogCSV} from '../src/core/catalog';
import {referenceFinishCommands} from '../src/production/reference-finish';
import {outfitHash as rawHash} from '../src/production/outfit-components';
import {auditBuildingVariant} from './lib/building-variant-audit';
import {Grid} from '../src/core/grid';
import type {Project} from '../src/core/types';
const hash=(value:unknown)=>rawHash(value??null);
const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),verification=JSON.parse(await readFile(latest.evidence+'/variant-verification.json','utf8')),out=latest.evidence,runtime=path.join(out,'variant-mcp-completion-runtime'),url='http://127.0.0.1:4401',rows=latest.models;assert.equal(rows.length,6);
const recovery=JSON.parse(await readFile(out+'/interrupted-mcp-recovery.json','utf8')),digest=(data:Uint8Array)=>createHash('sha256').update(data).digest('hex');
assert.equal(recovery.status,'completed-prefix-verified');assert.equal(recovery.run,latest.run);assert.equal(recovery.quarterTurns.length,38);assert.equal(recovery.views.length,51);
assert.equal(digest(await readFile(recovery.originalVerifier)),recovery.originalVerifierSHA256);assert.equal(digest(await readFile(out+'/'+recovery.log)),recovery.logSHA256);
for(const view of recovery.views.slice(0,48))assert.equal(digest(await readFile(out+'/'+view.file)),view.sha256);
await mkdir(runtime,{recursive:true});for(const file of['atlas-production-index.json','production-index.json','architecture-index.json','material-index.json',...rows.map((r:any)=>r.file)])await copyFile('projects/'+file,runtime+'/'+file);await cp('projects/reference-atlas',runtime+'/reference-atlas',{recursive:true});await copyFile('projects/'+rows[0].file,runtime+'/autosave.ysvox.json');

const empty=productionProject('M059 MCP building variants');empty.catalog={sourceName:'catalog',importedAt:latest.createdAt,entries:Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]))};await writeFile(runtime+'/empty.ysvox.json',JSON.stringify(empty));
let server:ChildProcess|undefined,client:Client|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,log='';const report:any={run:latest.run,status:'running',checks:[],errors:[],views:recovery.views.slice(0,48),quarterTurns:recovery.quarterTurns,interruptedRecovery:{report:'interrupted-mcp-recovery.json',status:recovery.status,originalCapturedViewsRetained:48,publicCasesRepeated:true},completionVerifierSHA256:digest(await readFile('scripts/finish-building-variants-mcp.ts')),notifications:[],expectedInvalidationVersions:[]},state=async():Promise<Project>=>(await fetch(url+'/api/state').then(r=>r.json())).project;
async function start(){server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4401',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok)return;}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}throw new Error('startup timeout');}
async function stop(){if(server&&server.exitCode===null){const closed=once(server,'exit');server.kill();await closed;}}
try{
 await start();client=new Client({name:'building-variants-verification',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],cwd:process.cwd(),env:{...process.env as Record<string,string>,VOXEL_URL:url},stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const r:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(name,r.isError?'ERROR':'OK');return{...JSON.parse(r.content[0].text),isError:!!r.isError};},call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 browser=await chromium.launch(validationBrowserOptions());report.browser=browser.version();const page=await browser.newPage({viewport:{width:1400,height:1000}});page.setDefaultTimeout(240000);page.on('pageerror',e=>report.errors.push(e.message));page.on('websocket',socket=>socket.on('framereceived',f=>{const n=JSON.parse(f.payload.toString());report.notifications.push({event:n.event,version:n.version,bytes:Buffer.byteLength(f.payload.toString()),fullProject:!!n.project});}));await page.goto(url+'/?atlas=1&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready);
 const sync=async(v:number)=>page.waitForFunction(n=>(window as any).voxelStudio.performance.renderedVersion===n,v),frames=async()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))),edit=async(commands:any[])=>{const req={expectedVersion:(await state()).version,requestId:crypto.randomUUID(),commands},dry=await call('edit_transaction',{...req,dryRun:true}),result=await call('edit_transaction',{...req,previewToken:dry.previewToken});await sync(result.version);report.expectedInvalidationVersions.push(result.version);return result;},load=async(file:string)=>{const r=await call('load_project',{filename:file,expectedVersion:(await state()).version});await sync(r.version);report.expectedInvalidationVersions.push(r.version);return state();};
 const capture=async(key:string,view='isometric',clip:number=Infinity,assetId?:string)=>{await page.evaluate(async ({view,clip,assetId})=>{const v=(window as any).voxelStudio;await v.mode(assetId?'asset':'scene',assetId);v.view(view);v.clip(clip);v.clay(false);v.studio(true);v.ao(false);v.bloom(false);},{view,clip,assetId});await frames();const clipBox=await page.locator('#viewport').boundingBox();assert.ok(clipBox);await page.screenshot({path:out+'/variant-'+key+'.png',clip:clipBox,timeout:240000});const perf=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.equal(perf.meshError,null);report.views.push({key,file:'variant-'+key+'.png',assetId,triangles:perf.triangles,evidence:'fresh completion run'});await writeFile(out+'/variant-mcp-completion-progress.json',JSON.stringify(report,null,2));};
 report.webgl=await page.evaluate(()=>{const g=(document.querySelector('#viewport canvas')as HTMLCanvasElement).getContext('webgl2')!,ext=g.getExtension('WEBGL_debug_renderer_info');return g.getParameter(ext?.UNMASKED_RENDERER_WEBGL??g.RENDERER);});
 const lib=await call('read_production_library',{query:'BUILT-025'});assert.equal(lib.counts.atlasReferenceCandidates,708);assert.equal(lib.counts.atlasAssemblyCandidates,186);assert.equal(lib.counts.atlasVariantCandidates,6);assert.equal(lib.counts.atlasVariantForms,38);assert.equal(lib.counts.baseModels,532);
 const recipes=await call('list_production_recipes',{query:'BUILT-025',limit:100}),recipe=recipes.entries.find((r:any)=>r.id==='BUILT-025');assert.equal(recipe.kind,'variant');assert.equal(recipe.parentCatalogId,'BUILT-019');assert.deepEqual(recipe.parameters.buildingPlan.enum,['quarter-1','quarter-2','quarter-3','quarter-4']);report.libraryCounts=lib.counts;await writeFile('docs/tool-schemas.json',JSON.stringify((await client.listTools()).tools,null,2));report.checks.push('Actual MCP distinguishes708 reference candidates,186 assemblies,6 new variants and38 forms;532 base count unchanged. Recipes expose parent and finite parameter contracts.');
 await page.locator('#atlas-sheet').selectOption('M059');await page.locator('[data-atlas-open][data-catalog="BUILT-025"]').first().click();await page.waitForFunction(()=>Object.values((window as any).voxelStudio.project.assemblies??{}).some((a:any)=>a.source?.catalogId==='BUILT-025'));const opened=await state();await sync(opened.version);report.expectedInvalidationVersions.push(opened.version);const listed=await call('list_assets');assert.equal(listed.counts.variants,1);assert.equal(listed.counts.assemblies,0);report.checks.push('Actual atlas button opens whole variant scene; list_assets identifies one variant and zero new assemblies.');
 report.checks.push('Original completed38-form public quarter-turn/undo loop and48 default/detail/nondefault views recovered from the exact297-line unchanged-verifier log prefix, source hashes, final native bytes and capture hashes; original browser performance counters are not reconstructed.');
 await load('empty.ysvox.json');const before=await state(),request={expectedVersion:before.version,requestId:crypto.randomUUID(),commands:[{op:'produceCatalogVariant',catalogId:'BUILT-026',id:'farm',place:true,params:{sizeCase:'expanded'}}]},dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(before));const made=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(made.version);report.expectedInvalidationVersions.push(made.version);assert.equal((await call('edit_transaction',request)).version,made.version);assert.equal((await raw('edit_transaction',{...request,requestId:crypto.randomUUID()})).code,'VERSION_CONFLICT');const farm=await state(),audit=auditBuildingVariant(farm,farm.assemblies!.farm);assert.ok(audit.passed);report.publicFarm=audit;
 for(const bad of[{op:'produceCatalogVariant',catalogId:'BUILT-025',id:'bad',params:{buildingPlan:'quarter-2',floors:4}},{op:'produceCatalogVariant',catalogId:'BUILT-028',id:'bad',params:{seed:17}},{op:'produceCatalogAssembly',catalogId:'BUILT-026',id:'bad'},{op:'produceCatalogAsset',catalogId:'BUILT-026',id:'bad'}]){assert.ok((await raw('edit_transaction',{expectedVersion:farm.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:farm.styles.yunshan.roof,properties:{color:'#ff0000'}},bad]})).isError);assert.equal(hash(await state()),hash(farm));}
 await capture('farm-public-create');report.checks.push('Actual variant creation validates dry-run, CAS, idempotency and geometry. Invalid quarter floor, unsupported seed, wrong assembly/base kind roll back preceding material edit.');
 await edit([{op:'instantiateAssembly',assemblyId:'farm',prefix:'turn',position:[50,0,50],rotation:1}]);const placed=await state();await capture('farm-quarter-turn');const exported=await call('export_project',{name:'building-variant-quarter-turn-'+Date.now()}),native=JSON.parse(await readFile(exported.directory+'/voxels.ysvox.json','utf8'));for(const k of['assets','instances','assemblies','styles']as const)assert.equal(hash(native[k]),hash(placed[k]));report.export=exported;await edit([{op:'undo'}]);assert.equal(hash((await state()).instances),hash(farm.instances));await edit([{op:'undo'}]);for(const k of['assets','instances','assemblies','materials']as const)assert.equal(hash((await state())[k]),hash(before[k]));report.checks.push('Public quarter-turn export retains exact native definitions; placement and variant creation each undo as one transaction.');
 const original=await load(rows.find((r:any)=>r.id==='BUILT-026').file),pinAsset=Object.values(original.assets).find(a=>a.id.startsWith('architecture-variant')&&new Grid(a.chunks).count)!,cell=[...new Grid(pinAsset.chunks).cells()][0][0],query=await call('query_voxels',{assetId:pinAsset.id,region:{min:cell,max:cell.map(v=>v+1)}});assert.equal(query.cells[0][1],original.styles.yunshan.architecturePin);
 await edit([{op:'definePalette',name:'M059建筑用途',materials:{[original.styles.yunshan.roof]:{color:'#758ca1'},[original.styles.yunshan.wall]:{color:'#ddb993'},[original.styles.yunshan.stone]:{color:'#718276'},[original.styles.yunshan.glass]:{color:'#90b2b7'}}},{op:'palette',name:'M059建筑用途'}]);const changed=await state();for(const k of['assets','instances','assemblies','styles']as const)assert.equal(hash(changed[k]),hash(original[k]));await capture('farm-purpose-palette');await edit([{op:'undo'}]);assert.equal(hash((await state()).materials),hash(original.materials));report.checks.push('Native pin query and separate roof/render/paving/glass purpose palette preserve all geometry; one undo restores materials.');
 const authority=hash(await state());report.details=[];for(const mode of['far','near']){await page.evaluate(async mode=>(window as any).voxelStudio.meshMode(mode),mode);await frames();const perf=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.equal(perf.meshMode,mode);report.details.push({mode,triangles:perf.triangles});}assert.equal(hash(await state()),authority);report.checks.push('Renderer near/far modes preserve source authority and continuous roof geometry.');
 const formBoard=verification.records.map((r:any)=>({id:r.id,params:r.params,file:r.isDefault?'screenshots/'+r.id+'-material.png':'variant-'+r.id+'-'+Object.values(r.params).join('-')+'.png'}));
 const boardHTMLFor=(items:any[])=>'<!doctype html><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;background:#dfe1dd;color:#273d34;font:17px system-ui}header,footer{padding:24px}main{display:grid;grid-template-columns:repeat(4,1fr)}figure{margin:0;border:1px solid #b7c0b6}img{display:block;width:100%}figcaption{padding:12px}</style><header><h1>M059 · 六类建筑 / 38种有限形态</h1>实际编辑器截图 · 各模型独立构图，不共用比例尺 · 原生最小细件与连续坡面</header><main>'+items.map((r:any)=>'<figure><img src="'+r.file+'"><figcaption>'+r.id+'<br>'+Object.values(r.params).join(' / ')+'</figcaption></figure>').join('')+'</main><footer>父模板与公开参数分别保存；人工美术验收0，原游戏FloorPlan和控制器未绑定。</footer>';
 await writeFile(out+'/building-variants.html',boardHTMLFor(formBoard));const board=await browser.newPage({viewport:{width:2000,height:1300}});await board.goto(pathToFileURL(path.resolve(out+'/building-variants.html')).href);await board.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await board.screenshot({path:out+'/building-variants.png',fullPage:true});await board.close();report.formBoard=formBoard;report.formBoardPages=[];
 for(let start=0;start<formBoard.length;start+=12){const key='building-variants-'+(Math.floor(start/12)+1),items=formBoard.slice(start,start+12);await writeFile(out+'/'+key+'.html',boardHTMLFor(items));const p=await browser.newPage({viewport:{width:2000,height:1300}});await p.goto(pathToFileURL(path.resolve(out+'/'+key+'.html')).href);await p.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await p.screenshot({path:out+'/'+key+'.png',fullPage:true});await p.close();report.formBoardPages.push({file:key+'.png',items});}

 const doc=await state(),saved=await call('save_project',{filename:'verified-variant.ysvox.json'});assert.equal(hash(JSON.parse(await readFile(saved.path,'utf8'))),hash(doc));await stop();await start();assert.equal(hash(await state()),hash(doc));report.checks.push('Native save and real server restart preserve parent, parameters, components, instances and materials.');assert.equal(report.expectedInvalidationVersions.length,9);assert.deepEqual(report.notifications.map((n:any)=>n.version),report.expectedInvalidationVersions);assert.ok(report.notifications.every((n:any)=>n.event==='state-invalidated'&&!n.fullProject&&n.bytes<65536));assert.deepEqual(report.errors,[]);report.status='passed';console.log(JSON.stringify({status:report.status,checks:report.checks.length,views:report.views.length}));
}catch(e){report.status='failed';report.errors.push(String(e));throw e;}finally{await browser?.close();await client?.close();await stop();await writeFile(out+'/variant-mcp-verification.json',JSON.stringify(report,null,2));await writeFile(out+'/variant-mcp-server.txt',log);}
