"""Package verified atlas masters for the existing editor, without test runtimes.

Every active ID is resolved through the merged production index. A later batch
must not accidentally drop masters generated by earlier runs.
"""
import hashlib
import json
import re
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit
from zipfile import ZipFile, ZIP_DEFLATED

root = Path(__file__).resolve().parents[1]
index = json.loads((root / 'projects/atlas-production-index.json').read_text())
latest = json.loads((root / 'artifacts/atlas/latest.json').read_text())
atlas = json.loads((root / 'projects/reference-atlas/index.json').read_text())
out = (root / latest['evidence']).resolve()
assert out.is_relative_to(root / 'artifacts/atlas')
assert index['run'] == latest['run']
ids = [e['id'] for e in index['entries']]
assert len(ids) == len(set(ids))
sheets = sorted({e['sheet'] for e in index['entries']})
files = {
    root / 'projects/atlas-production-index.json',
    root / 'projects/reference-atlas/index.json',
    root / 'projects/reference-atlas/source.csv',
    root / 'docs/ATLAS-PRODUCTION.md', root / 'docs/FORMAT.md',
    root / 'docs/MCP.md', root / 'docs/mcp.example.json',
    root / 'AGENTS.md', root / 'docs/MATERIAL-ROLES.md',
    root / 'docs/tool-schemas.json',
    root / 'artifacts/atlas/reference-audit.json',
    root / 'artifacts/atlas/full-tests.log', root / 'artifacts/atlas/build.log',
    root / 'artifacts/atlas/commerce-precision-tests.log', root / 'artifacts/atlas/civic-tests.log',
    root / 'artifacts/atlas/render-materials-tests.log',
    root / 'artifacts/atlas/public-service-tests.log', root / 'artifacts/atlas/public-service-audit-first.json',
    root / 'artifacts/atlas/public-service-audit.json',
}
for row in index['entries']:
    files.add(root / 'projects' / row['file'])
    match = re.fullmatch(r'(atlas-\d{14})-(?:life|built)-\d{3}\.ysvox\.json', row['file'])
    assert match, row['file']
    run = match[1]
    for name in ['visual.glb', 'voxels.ysvox.json', 'collision.json',
                 'interfaces.json', 'atlas.png', 'atlas.json']:
        files.add(root / 'projects/production' / run / 'exports' / row['id'] / name)
    files.add(root / 'projects/production' / run / 'production.json')
for row in index['studies']:
    files.add(root / 'projects' / row['file'])
for sheet in sheets:
    for ext in ['html', 'png']:
        files.add(out / (sheet + '.' + ext))
    image = root / 'projects/reference-atlas/images' / (sheet + '.png')
    source = next(s for s in atlas['sheets'] if s['id'] == sheet)
    assert hashlib.sha256(image.read_bytes()).hexdigest() == source['sha256']
    files.add(image)
previews = json.loads((out / 'previews.json').read_text())
assert {e['id'] for e in previews['items']} == set(ids)
assert not previews['errors']
verification = json.loads((out / 'mcp-verification.json').read_text())
assert verification['status'] == 'passed' and not verification['errors']
assert verification['run'] == index['run']
for item in previews['items']:
    for name in item['files'].values():
        files.add(out / 'screenshots' / name)
for name in ['before-after.html', 'before-after.png', 'atlas-editor.png',
             'mcp-editor.png', 'mcp-created-machine.png', 'mcp-workshop-editor.png',
             'mcp-created-fish.png', 'mcp-commerce-editor.png', 'gallery-check.json', 'live-geometry.json',
             'mcp-created-microscope.png', 'mcp-research-editor.png', 'materials.html', 'materials.png',
             'mcp-material-roles.png', 'mcp-material-roles-restored.png', 'mcp-civic-roles-restored.png', 'live-asset.png', 'mcp-civic-roles.png', 'mcp-civic-editor.png', 'mcp-created-stretcher.png',
             'mcp-created-camera.png', 'mcp-public-roles.png', 'mcp-public-roles-restored.png', 'mcp-public-editor.png',
             'mcp-verification.json', 'previews.json',
             'production.json', 'material-audit.json', 'live-editor.png', 'live-editor.json']:
    files.add(out / name)
# Preserve the original evidence dates; do not relabel historical repairs as
# freshly captured in a later geometry batch.
classification_history = root / 'artifacts/atlas/atlas-20261003063047'
for name in ['visual-revision.html', 'visual-revision.png', 'visual-revision.json',
             'material-classification.html', 'material-classification-overview.html',
             'material-classification-overview.png', 'material-classification-comparison.json',
             'material-classification-report.json', 'material-audit.json',
             'mcp-classification-roles.png', 'mcp-classification-roles-restored.png']:
    files.add(classification_history / name)
for asset in ['LIFE-147', 'LIFE-148', 'LIFE-158']:
    files.add(classification_history / ('review-before-' + asset + '.png'))
    files.add(classification_history / 'screenshots' / (asset + '-isometric.png'))
    files.add(classification_history / 'screenshots' / (asset + '-material.png'))
    files.add(root / 'projects' / ('atlas-20261003052906-' + asset.lower() + '.ysvox.json'))
files.update(p for p in classification_history.glob('classification-before-*.png') if p.is_file())
for asset in ['LIFE-046', 'LIFE-057', 'LIFE-106', 'LIFE-107', 'LIFE-043', 'LIFE-082', 'LIFE-085', 'LIFE-096']:
    files.add(classification_history / 'screenshots' / (asset + '-isometric.png'))
for name in ['gallery-support-audit.json', 'mcp-classification-roles.png', 'mcp-classification-roles-restored.png',
             'mcp-culture-roles.png', 'mcp-culture-roles-restored.png', 'mcp-created-calligraphy.png', 'mcp-culture-editor.png']:
    files.add(out / name)
# M010's comparison predates M011; keep its original evidence directory.
culture_revision = root / 'artifacts/atlas/atlas-20261003072623'
for name in ['culture-revision.html', 'culture-revision.png', 'culture-revision.json']:
    files.add(culture_revision / name)
files.update(p for p in culture_revision.glob('culture-before-*.png') if p.is_file())
# First M010 native files and captures are the measurable geometry baseline.
culture_history = root / 'artifacts/atlas/atlas-20261003071620'
files.add(culture_history / 'previews.json')
files.add(culture_history / 'production.json')
old_index_path = root / 'projects/production/atlas-20261003071620/index.json'
files.add(old_index_path)
for row in json.loads(old_index_path.read_text())['entries']:
    if row['sheet'] == 'M010':
        files.add(root / 'projects' / row['file'])
files.update(p for p in (root / 'artifacts/atlas/culture-study').glob('*') if p.is_file())
festival_revision = root / 'artifacts/atlas/atlas-20261003081509'
for name in ['festival-revision.html', 'festival-revision.png', 'festival-revision.json']:
    files.add(festival_revision / name)
files.update(p for p in festival_revision.glob('festival-before-*.png') if p.is_file())
for name in ['mcp-festival-roles.png', 'mcp-festival-roles-restored.png',
             'mcp-created-celebration.png', 'mcp-festival-editor.png']:
    files.add(out / name)

# Preserve the first M011 captures and editable baseline used in the comparison.
festival_history = root / 'artifacts/atlas/atlas-20261003080834'
for name in ['previews.json', 'production.json']:
    files.add(festival_history / name)
festival_index_path = root / 'projects/production/atlas-20261003080834/index.json'
files.add(festival_index_path)
for row in json.loads(festival_index_path.read_text())['entries']:
    if row['sheet'] == 'M011':
        files.add(root / 'projects' / row['file'])
files.update(p for p in (root / 'artifacts/atlas/festival-study').glob('*') if p.is_file())
# M012 first preview and actual failures remain available for review.
domestic_history = root / 'artifacts/atlas/atlas-20261003085620'
for name in ['previews.json', 'production.json']:
    files.add(domestic_history / name)
domestic_index = root / 'projects/production/atlas-20261003085620/index.json'
files.add(domestic_index)
for row in json.loads(domestic_index.read_text())['entries']:
    if row['sheet'] == 'M012':
        files.add(root / 'projects' / row['file'])
files.update(p for p in (root / 'artifacts/atlas/domestic-study').glob('*') if p.is_file())
domestic_final = root / 'artifacts/atlas/atlas-20261003092028'
for name in ['domestic-revision.html', 'domestic-revision.png', 'domestic-revision.json',
             'domestic-mcp-verification.json', 'mcp-domestic-roles.png', 'mcp-domestic-roles-restored.png',
             'mcp-domestic-editor.png', 'mcp-domestic-route.png', 'domestic-route.ysvox.json',
             'domestic-route-view-0.png', 'domestic-route-view-1.png']:
    files.add(domestic_final / name)
assert json.loads((domestic_final / 'domestic-mcp-verification.json').read_text())['status'] == 'passed'
files.update(p for p in domestic_final.glob('domestic-before-*.png') if p.is_file())
files.update(p for p in (domestic_final / 'domestic-route-export').glob('*') if p.is_file())
# M013 evidence, preserving the first native/capture pass and its real failures.
structure_first = root / 'artifacts/atlas/atlas-20261003104125'
for name in ['previews.json', 'production.json', 'structure-mcp-verification.json']:
    files.add(structure_first / name)
structure_index = root / 'projects/production/atlas-20261003104125/index.json'
files.add(structure_index)
for row in json.loads(structure_index.read_text())['entries']:
    if row['sheet'] == 'M013':
        files.add(root / 'projects' / row['file'])
files.update(p for p in (root / 'artifacts/atlas/structure-study').glob('*') if p.is_file() and not p.name.startswith('package'))
structure_final = root / 'artifacts/atlas/atlas-20261003104805'
for name in ['structure-revision.html', 'structure-revision.png', 'structure-revision.json',
             'structure-mcp-verification.json', 'mcp-structure-roles.png', 'mcp-structure-roles-restored.png',
             'mcp-structure-window-rebuilt.png', 'mcp-structure-route.png', 'structure-route.ysvox.json',
             'structure-route-view-0.png', 'structure-route-view-1.png']:
    files.add(structure_final / name)
assert json.loads((structure_final / 'structure-mcp-verification.json').read_text())['status'] == 'passed'
files.update(p for p in (structure_final / 'structure-route-export').glob('*') if p.is_file())

# M014 preserves the first native geometry, gallery alignment warning and captures.
legacy_first = root / 'artifacts/atlas/atlas-20261003115837'
for name in ['previews.json', 'production.json', 'gallery-support-audit.json']:
    files.add(legacy_first / name)
legacy_index = root / 'projects/production/atlas-20261003115837/index.json'
files.add(legacy_index)
for row in json.loads(legacy_index.read_text())['entries']:
    if row['sheet'] == 'M014':
        files.add(root / 'projects' / row['file'])
files.add(root / 'projects/atlas-20261003115837-m014-gallery.ysvox.json')
files.update(p for p in (legacy_first / 'screenshots').glob('BUILT-0[56]*.png') if p.is_file())
files.update(p for p in (root / 'artifacts/atlas/legacy-building-study').glob('*') if p.is_file() and not p.name.startswith('package'))
legacy_final = root / 'artifacts/atlas/atlas-20261003120646'
for name in ['legacy-building-revision.html', 'legacy-building-revision.png', 'legacy-building-revision.json',
             'legacy-building-mcp-verification.json', 'mcp-legacy-paper-roles.png', 'mcp-legacy-paper-restored.png']:
    files.add(legacy_final / name)
assert json.loads((legacy_final / 'legacy-building-mcp-verification.json').read_text())['status'] == 'passed'
for assembly in ['legacy-stair-assembly', 'legacy-gate-assembly']:
    for name in [assembly + '.ysvox.json', 'mcp-' + assembly + '.png', assembly + '-view-0.png', assembly + '-view-1.png']:
        files.add(legacy_final / name)
    files.update(p for p in (legacy_final / (assembly + '-export')).glob('*') if p.is_file())

# M015 source, first preview and diagnostic evidence remain available.
joinery_first = root / 'artifacts/atlas/atlas-20261003124003'
for name in ['production.json', 'previews.json', 'joinery-mcp-verification.json', 'gallery-support-audit.json']:
    files.add(joinery_first / name)
joinery_index = root / 'projects/production/atlas-20261003124003/index.json'
files.add(joinery_index)
for row in json.loads(joinery_index.read_text())['entries']:
    if row['sheet'] == 'M015':
        files.add(root / 'projects' / row['file'])
files.add(root / 'projects/atlas-20261003124003-m015-gallery.ysvox.json')
files.update(p for p in (root / 'artifacts/atlas/joinery-study').glob('*') if p.is_file() and not p.name.startswith('package'))
joinery_final = root / 'artifacts/atlas/atlas-20261003124439'
for name in ['joinery-revision.html', 'joinery-revision.png', 'joinery-revision.json',
             'joinery-mcp-verification.json', 'mcp-joinery-roles.png', 'mcp-joinery-roles-restored.png']:
    files.add(joinery_final / name)
assert json.loads((joinery_final / 'joinery-mcp-verification.json').read_text())['status'] == 'passed'
for assembly in ['joinery-assembly', 'giant-column-assembly']:
    for name in [assembly + '.ysvox.json', 'mcp-' + assembly + '.png', assembly + '-view-0.png', assembly + '-view-1.png']:
        files.add(joinery_final / name)
    files.update(p for p in (joinery_final / (assembly + '-export')).glob('*') if p.is_file())

# M016 uses actual metre-scale geometry and independently replaceable roles.
files.update(p for p in (root / 'artifacts/atlas/exterior-study').glob('*') if p.is_file() and not p.name.startswith('package'))
for name in ['exterior-mcp-verification.json', 'mcp-exterior-roles.png', 'mcp-exterior-roles-restored.png']:
    files.add(out / name)
assert json.loads((out / 'exterior-mcp-verification.json').read_text())['status'] == 'passed'
for assembly in ['exterior-assembly', 'exterior-corridors', 'exterior-starport']:
    for name in [assembly + '.ysvox.json', 'mcp-' + assembly + '.png', assembly + '-view-0.png', assembly + '-view-1.png']:
        files.add(out / name)
    files.update(p for p in (out / (assembly + '-export')).glob('*') if p.is_file())

for name in ['before-index.json', 'candidate-comparison.json', 'saved-comparison.json', 'correction-tests.log', 'm002-gallery-support-failure.log']:
    files.add(root / 'artifacts/material-classification' / name)
for prefix in ['material-rebuild-baseline-', 'material-reuse-swiftshader-']:
    files.update(p for p in out.glob(prefix + '*') if p.is_file())
for name in ['material-rebuild-baseline.log', 'material-reuse-swiftshader.log']:
    if (out / name).is_file():
        files.add(out / name)
history = root / 'artifacts/atlas/atlas-20261003043231'
for pattern in ['material-rebuild-baseline-*', 'material-reuse-swiftshader-*', 'material-rebuild-baseline.log', 'material-reuse-swiftshader.log']:
    files.update(p for p in history.glob(pattern) if p.is_file())
study = root / 'artifacts/microscope-study'
assert json.loads((study / 'after.json').read_text())['status'] == 'passed'
for phase in ['before', 'ao-fixed', 'after']:
    for suffix in ['.json', '.ysvox.json', '-flat.png', '-material.png',
                   '-material-ao.png', '-material-glow.png']:
        files.add(study / (phase + suffix))
for name in ['comparison.html', 'comparison.png', 'comparison.json', 'after-material.ysvox.json']:
    files.add(study / name)
for name in ['visual.glb', 'voxels.ysvox.json', 'collision.json',
             'interfaces.json', 'atlas.png', 'atlas.json']:
    files.add(study / 'after-material-export' / name)

class LocalReferences(HTMLParser):
    def __init__(self):
        super().__init__()
        self.paths = []

    def handle_starttag(self, tag, attrs):
        for key, value in attrs:
            if key not in ('src', 'href') or not value:
                continue
            target = urlsplit(value)
            if target.scheme or target.netloc or not target.path or target.path.startswith('/'):
                continue
            self.paths.append(unquote(target.path))

# Include actual local dependencies of comparison pages, even when their
# screenshots belong to an older run. Never silently ship broken HTML images.
parsed_pages = set()
html_dependencies = {}
while True:
    pending = [p for p in files if p.suffix == '.html' and p not in parsed_pages]
    if not pending:
        break
    for page in pending:
        parsed_pages.add(page)
        parser = LocalReferences()
        parser.feed(page.read_text())
        dependencies = []
        for reference in parser.paths:
            dependency = (page.parent / reference).resolve()
            assert dependency.is_relative_to(root), (page, reference)
            assert dependency.is_file() and not dependency.is_symlink(), (page, reference)
            files.add(dependency)
            dependencies.append(dependency.relative_to(root).as_posix())
        html_dependencies[page.relative_to(root).as_posix()] = dependencies
for p in files:
    assert p.is_file() and not p.is_symlink(), p
    assert p.resolve().is_relative_to(root), p
records = [{'path': p.relative_to(root).as_posix(),
            'sha256': hashlib.sha256(p.read_bytes()).hexdigest(),
            'bytes': p.stat().st_size} for p in sorted(files)]
manifest = {
    'format': 'yunshan.atlas-asset-delivery', 'version': 1,
    'run': index['run'], 'baseCandidates': len(ids), 'newCatalogIds': 0,
    'accepted': 0, 'pendingReferences': len(atlas['entries']) - len(ids),
    'nativeDocuments': len(index['entries']) + len(index['studies']),
    'singleAssetExports': len(ids), 'includedReferenceSheets': sheets,
    'voxels': sum(e['voxels'] for e in index['entries']),
    'triangles': sum(e['triangles'] for e in index['entries']),
    'files': records,
}
archive = out / f'云山-{len(ids)}件图册体素候选包.zip'
temporary = archive.with_suffix('.zip.tmp')
with ZipFile(temporary, 'w', ZIP_DEFLATED, compresslevel=6) as z:
    for p in sorted(files):
        z.write(p, p.relative_to(root).as_posix())
    z.writestr('manifest.json', json.dumps(manifest, ensure_ascii=False, indent=2))
    z.writestr('使用说明.txt',
        f'本包包含 {len(ids)} 个清单基础 ID 的按图重建候选，'
        f'{manifest["nativeDocuments"]} 份原生文档（含总览），尚未通过人工美术验收。\n'
        '这是已有体素工坊的资产包，不是独立应用安装包。应用源码与启动方式在 voxel-studio 工作区。\n'
        '按相对路径复制到已有工作区，保留已有原件；project 文件均带制作时间戳。\n'
        '在编辑器“图册”中打开新版，或从“恢复”选择具体 ysvox.json 文件。\n'
        '每件保存“原始素色”“参考材质试作”配色。默认无纹理验形，材质和光照可后续修改。\n'
        'projects/production/ 对应制作批次含逐件 GLB、无损体素、碰撞、接口与色彩图集。\n'
        'artifacts/atlas/ 含真实 WebGL 截图、前后对照和测试报告。\n'
        '只随包附带本批已经制作的参考图，全部 67 张原图留在现有工作区；索引保留完整来源关联。\n'
        '图像不能确定实测尺寸或不可见构造；当前尺寸为作者设定的米制尺寸。\n'
        '动画、布料、流体、平面镜反射和真实折射未实现。详细局限见 docs/ATLAS-PRODUCTION.md。\n')
with ZipFile(temporary) as z:
    assert z.testzip() is None
    assert len(z.namelist()) == len(set(z.namelist())) == len(files) + 2
    for record in records:
        assert hashlib.sha256(z.read(record['path'])).hexdigest() == record['sha256']
    archive_paths = set(z.namelist())
    for page, dependencies in html_dependencies.items():
        assert page in archive_paths and set(dependencies) <= archive_paths
temporary.replace(archive)
result = {'path': str(archive), 'bytes': archive.stat().st_size,
          'entries': len(files) + 2, 'baseCandidates': len(ids),
          'nativeDocuments': manifest['nativeDocuments'],
          'singleAssetExports': len(ids),
          'verifiedHTMLPages': len(html_dependencies),
          'verifiedLocalHTMLReferences': sum(map(len, html_dependencies.values())),
          'sha256': hashlib.sha256(archive.read_bytes()).hexdigest()}
(out / 'package.json').write_text(json.dumps(result, ensure_ascii=False, indent=2))
print(json.dumps(result, ensure_ascii=False))
