import {mkdir,readFile,writeFile,copyFile,cp} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawn} from 'node:child_process';
import {pathToFileURL} from 'node:url';
import {chromium} from 'playwright';
import {validationBrowserOptions} from './browser-options';
import assert from 'node:assert/strict';

const report=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),atlas=JSON.parse(await readFile('projects/reference-atlas/index.json','utf8')),out=report.evidence,runtime=path.join(out,'preview-runtime'),url='http://127.0.0.1:4345',pilots=new Set(['LIFE-024','LIFE-026','LIFE-039','LIFE-049','LIFE-053','LIFE-056']);
const selectedSheets=process.argv.find(a=>a.startsWith('--sheets='))?.slice(9).split(',');
if(selectedSheets){
 if(selectedSheets.some(s=>!/^M[0-9]{3}$/.test(s)))throw new Error('Invalid sheet ID');
 index.entries=index.entries.filter((e:any)=>selectedSheets.includes(e.sheet));
 index.studies=index.studies.filter((s:any)=>selectedSheets.some(id=>s.id===id+'-gallery'));
 assert.ok(index.entries.length,'No produced entries in selected sheets');
}
await mkdir(runtime,{recursive:true});await mkdir(path.join(out,'screenshots'),{recursive:true});
const files=new Set<string>([...index.entries.map((r:any)=>r.file),...index.studies.map((r:any)=>r.file),'atlas-production-index.json']);for(const e of atlas.entries)if(pilots.has(e.id)&&e.legacy)files.add(e.legacy.file);
for(const f of files)await copyFile(path.join('projects',f),path.join(runtime,f));await cp('projects/reference-atlas',path.join(runtime,'reference-atlas'),{recursive:true});await copyFile(path.join(runtime,index.entries[0].file),path.join(runtime,'autosave.ysvox.json'));
const server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4345',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});let log='';server.stdout.on('data',d=>log+=d);server.stderr.on('data',d=>log+=d);let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
const result:any={run:index.run,captureVersion:2,viewport:{width:900,height:800},items:[],errors:[],scope:selectedSheets??'all-produced',appearance:'base colour / no texture, scene lights, AO or bloom',framing:'each asset independently fitted to viewport; isometric direction shared, not a common real-world scale'};
const reuseRun=process.argv.find(a=>a.startsWith('--reuse='))?.slice(8);
if(reuseRun&&!/^atlas-[0-9]{14}$/.test(reuseRun))throw new Error('Invalid preview reuse run');
const reuseRoot=reuseRun?path.resolve('artifacts/atlas',reuseRun):undefined;
const prior=reuseRoot?JSON.parse(await readFile(path.join(reuseRoot,'previews.json'),'utf8')):null;
const priorIndex=reuseRun?JSON.parse(await readFile(path.join('projects/production',reuseRun,'index.json'),'utf8')):null;
const stableHash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
async function reusable(row:any){
 if(!prior||!priorIndex||prior.captureVersion!==result.captureVersion||prior.errors.length||prior.webgl!==result.webgl||prior.browser!==result.browser)return null;
 const previous=priorIndex.entries.find((e:any)=>e.id===row.id),item=prior.items.find((e:any)=>e.id===row.id);
 if(!previous||!item||previous.sha256!==row.sha256)return null;
 const [oldDoc,newDoc]=await Promise.all([previous.file,row.file].map(f=>readFile(path.join('projects',f),'utf8').then(JSON.parse)));
 for(const field of['materials','styles','palettes'])if(stableHash(oldDoc[field])!==stableHash(newDoc[field]))return null;
 if(stableHash(oldDoc.assets[previous.assetId])!==stableHash(newDoc.assets[row.assetId]))return null;
 for(const filename of Object.values(item.files) as string[]){assert.equal(path.basename(filename),filename);await copyFile(path.join(reuseRoot!,'screenshots',filename),path.join(out,'screenshots',filename));}
 return {...item,reusedFrom:reuseRun,reuseEvidence:{geometrySHA256:row.sha256,materialsSHA256:stableHash(newDoc.materials),sameNativeAsset:true,samePalettes:true,sameBrowserAndRenderer:true}};
}
const call=async(name:string,args:any={})=>{const r=await fetch(url+'/api/tool',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,arguments:args})}),x=await r.json();assert.ok(r.ok,JSON.stringify(x));return x;};
try{
 for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok)break;}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch(validationBrowserOptions());result.browser=browser.version();const page=await browser.newPage({viewport:{width:900,height:800}});page.setDefaultTimeout(120000);page.on('pageerror',e=>result.errors.push(e.message));await page.goto(url+'/?preview=1&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready,null,{timeout:120000});
 result.webgl=await page.evaluate(()=>{const gl=(document.querySelector('#viewport canvas') as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return gl.getParameter(ext?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);});
 const open=async(file:string,assetId:string)=>{const p=await fetch(url+'/api/state').then(r=>r.json()),r=await call('load_project',{filename:file,expectedVersion:p.project.version});await page.waitForFunction(v=>(window as any).voxelStudio?.performance.renderedVersion===v,r.version,{timeout:120000});await page.evaluate(async id=>{const v=(window as any).voxelStudio;await v.mode('asset',id);v.clay(true);v.view('isometric');},assetId);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));};
 for(const row of index.entries){
  const reusableItem=await reusable(row);if(reusableItem){result.items.push(reusableItem);console.log('REUSED VERIFIED '+row.id);continue;}
  const files:Record<string,string>={};await open(row.file,row.assetId);
  for(const view of['isometric','front']){await page.evaluate(v=>(window as any).voxelStudio.view(v),view);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const file=row.id+'-'+view+'.png';await page.locator('#viewport').screenshot({path:path.join(out,'screenshots',file)});files[view]=file;}
  const perf=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.equal(perf.meshError,null);assert.ok(perf.assetIds.includes(row.assetId));
  if(pilots.has(row.id)){const legacy=atlas.entries.find((e:any)=>e.id===row.id).legacy;if(legacy){await open(legacy.file,legacy.assetIds[0]);const file=row.id+'-legacy.png';await page.locator('#viewport').screenshot({path:path.join(out,'screenshots',file)});files.legacy=file;}}
  if(report.models.some((m:any)=>m.id===row.id)||['BUILT-090','BUILT-091','BUILT-094','BUILT-095','BUILT-096','BUILT-097','BUILT-098','BUILT-099','BUILT-100','BUILT-101','BUILT-102','BUILT-103','BUILT-065','BUILT-066','BUILT-067','BUILT-068','BUILT-069','BUILT-070','BUILT-071','BUILT-072','BUILT-073','BUILT-074','BUILT-088','BUILT-089','BUILT-053','BUILT-054','BUILT-055','BUILT-056','BUILT-057','BUILT-058','BUILT-059','BUILT-060','BUILT-061','BUILT-062','BUILT-063','BUILT-064','BUILT-008','BUILT-009','BUILT-010','BUILT-011','BUILT-012','BUILT-013','BUILT-014','BUILT-015','BUILT-016','BUILT-017','BUILT-018','BUILT-045','LIFE-192','LIFE-193','LIFE-194','LIFE-195','LIFE-196','LIFE-197','LIFE-198','LIFE-199','LIFE-200','LIFE-227','BUILT-003','BUILT-007','LIFE-180','LIFE-181','LIFE-182','LIFE-183','LIFE-184','LIFE-185','LIFE-186','LIFE-187','LIFE-188','LIFE-189','LIFE-190','LIFE-191','LIFE-159','LIFE-169','LIFE-170','LIFE-171','LIFE-172','LIFE-173','LIFE-174','LIFE-175','LIFE-176','LIFE-177','LIFE-178','LIFE-179','LIFE-019','LIFE-027','LIFE-031','LIFE-043','LIFE-044','LIFE-046','LIFE-051','LIFE-052','LIFE-054','LIFE-057','LIFE-068','LIFE-076','LIFE-078','LIFE-080','LIFE-085','LIFE-088','LIFE-096','LIFE-107','LIFE-024','LIFE-056','LIFE-065','LIFE-082','LIFE-084','LIFE-089','LIFE-094','LIFE-106','LIFE-113','LIFE-114','LIFE-115','LIFE-117','LIFE-119','LIFE-122','LIFE-124','LIFE-125','LIFE-127','LIFE-140','LIFE-145','LIFE-146','LIFE-147','LIFE-148','LIFE-150','LIFE-152','LIFE-156','LIFE-158'].includes(row.id)){
   await open(row.file,row.assetId);const state=await fetch(url+'/api/state').then(r=>r.json()),applied=await call('edit_transaction',{expectedVersion:state.project.version,requestId:crypto.randomUUID(),commands:[{op:'palette',name:'参考材质试作'}]});await page.waitForFunction(v=>(window as any).voxelStudio.performance.renderedVersion===v,applied.version,{timeout:120000});
   await page.evaluate(()=>{const v=(window as any).voxelStudio;v.clay(false);v.studio(true);v.referenceLighting(true);v.ao(false);v.bloom(false);v.view('isometric');});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));files.material=row.id+'-material.png';await page.locator('#viewport').screenshot({path:path.join(out,'screenshots',files.material)});
  }
  result.items.push({id:row.id,sheet:row.sheet,name:atlas.entries.find((e:any)=>e.id===row.id).name,files,voxels:row.voxels,cellSizeM:row.cellSizeM??.01,boundsM:row.boundsM,performance:perf});await writeFile(path.join(out,'previews.partial.json'),JSON.stringify({...result,status:'capturing'},null,2));console.log('CAPTURED '+row.id);
 }
 await page.close();
 for(const sheet of[...new Set<string>(index.entries.map((e:any)=>e.sheet))]){
  const entries=result.items.filter((r:any)=>r.sheet===sheet),html=`<!doctype html><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;background:#dfe1dd;color:#273d34;font:18px system-ui,'PingFang SC'}header{padding:26px 36px}h1{font-size:30px;margin:0 0 10px}main{display:grid;grid-template-columns:repeat(4,1fr)}figure{margin:0;border:1px solid #b7c0b6;background:#d4d8d1}img{display:block;width:100%}figcaption{padding:13px 22px 18px;font-size:19px}small{display:block;font-size:13px;margin-top:5px}footer{padding:24px 36px}</style><header><h1>云山 · ${sheet} · 按参考图重建的 12 件体素候选</h1>真实编辑器截图 · 保留基础色 · 无纹理 / AO / 辉光 · 原生体素网格（格距标在各模型下方）</header><main>${entries.map((e:any)=>`<figure><img src="screenshots/${e.files.isometric}"><figcaption><b>${e.id} ${e.name}</b><small>${e.cellSizeM*1000} mm 格距 · ${e.voxels.toLocaleString()} 格 · 实际边界 ${e.boundsM.max.map((v:number,i:number)=>(v-e.boundsM.min[i]).toFixed(2)).join(' × ')} m</small></figcaption></figure>`).join('')}</main><footer>每格独立适配画幅；柜体、灯具和器具比例不是同一个画幅比例尺。几何候选，尚未通过人工美术验收。无图片重绘或贴图冒充几何。</footer>`;
  const file=path.join(out,sheet+'.html');await writeFile(file,html);const sheetPage=await browser.newPage({viewport:{width:2200,height:1300}});await sheetPage.goto(pathToFileURL(file).href);await sheetPage.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await sheetPage.screenshot({path:path.join(out,sheet+'.png'),fullPage:true});await sheetPage.close();
 }
 const examples=result.items.filter((r:any)=>r.files.legacy);if(examples.length){const comparison=`<!doctype html><meta charset="utf-8"><style>body{margin:0;background:#dbe0d6;color:#263c30;font:18px system-ui}header,footer{padding:22px}main{display:grid;grid-template-columns:1fr 1fr}figure{margin:0;border:1px solid #adb9a5}img{width:100%;display:block}figcaption{padding:14px}</style><header><h1>旧粗模 / 按图重建 · 实际体素对照</h1>同一观察方向 · 各自适配画幅 · 不是材质滤镜</header><main>${examples.flatMap((r:any)=>['legacy','isometric'].map(view=>`<figure><img src="screenshots/${r.files[view]}"><figcaption>${r.id} ${r.name} · ${view==='legacy'?'旧版':'新版'}</figcaption></figure>`)).join('')}</main><footer>共 ${index.entries.length} 个清单 ID 的参考候选；已有模型升级不重复计数，首次建模的清单条目单独计数。镜面反射、流体、开合和布料动画尚未实现。</footer>`;await writeFile(path.join(out,'before-after.html'),comparison);const comp=await browser.newPage({viewport:{width:1700,height:1100}});await comp.goto(pathToFileURL(path.join(out,'before-after.html')).href);await comp.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await comp.screenshot({path:path.join(out,'before-after.png'),fullPage:true});await comp.close();}
 const materialTrials=result.items.filter((r:any)=>r.files.material&&report.models.some((m:any)=>m.id===r.id));
 if(materialTrials.length){
  const html=`<!doctype html><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;background:#dce0d8;color:#273b32;font:18px system-ui,'PingFang SC'}header,footer{padding:24px 34px}h1{margin:0 0 10px;font-size:28px}main{display:grid;grid-template-columns:1fr 1fr}article{border:1px solid #aebbae}h2{font-size:20px;margin:18px 24px}section{display:flex}figure{margin:0;width:50%}img{width:100%;display:block}figcaption{padding:12px 22px}</style><header><h1>云山 · 本批模型的素色 / 材质试作</h1>相同原生体素 · 相同观察方向 · 两种显示方案 · 实际 WebGL 截图</header><main>${materialTrials.map((r:any)=>`<article><h2>${r.id} ${r.name}</h2><section>${['isometric','material'].map(v=>`<figure><img src="screenshots/${r.files[v]}"><figcaption>${v==='isometric'?'素色检查：无纹理、AO、辉光':'参考材质试作：PBR、透明与棚光'}</figcaption></figure>`).join('')}</section></article>`).join('')}</main><footer>材质试作不等于参考图达标。尚无真实折射、全局光照、光学成像或设备动画。纯色模式将玻璃显示为实色，便于检查占用格。</footer>`;
  await writeFile(path.join(out,'materials.html'),html);const p=await browser.newPage({viewport:{width:2200,height:1300}});await p.goto(pathToFileURL(path.join(out,'materials.html')).href);await p.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await p.screenshot({path:path.join(out,'materials.png'),fullPage:true});await p.close();result.materialTrials=materialTrials.map((r:any)=>r.id);
 }
 const ui=await browser.newPage({viewport:{width:1600,height:1050}});ui.on('pageerror',e=>result.errors.push(e.message));await ui.goto(url+'/?atlas=1&flat=1&view=isometric');await ui.waitForFunction(()=>!!(window as any).voxelStudio?.ready,null,{timeout:120000});await ui.locator('#atlas-sheet').selectOption(index.entries[0].sheet);await ui.locator('[data-atlas-open][data-catalog="'+index.entries[0].id+'"]').first().click();await ui.waitForFunction(id=>(window as any).voxelStudio.performance.assetIds.includes(id),index.entries[0].assetId,{timeout:120000});await ui.waitForFunction(id=>document.querySelector('#atlas-reference')?.textContent?.includes(id),index.entries[0].id,{timeout:30000});await ui.screenshot({path:path.join(out,'atlas-editor.png')});assert.ok((await ui.locator('#atlas-reference').innerText()).includes(index.entries[0].id));await ui.close();
 result.reusedImages=result.items.filter((e:any)=>e.reusedFrom).reduce((n:number,e:any)=>n+Object.keys(e.files).length,0);result.imageCount=result.items.reduce((n:number,item:any)=>n+Object.keys(item.files).length,0);assert.deepEqual(result.errors,[]);await writeFile(path.join(out,'previews.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({images:result.imageCount,errors:result.errors,out}));
}finally{await browser?.close();server.kill('SIGTERM');await writeFile(path.join(out,'preview-server.log'),log);}
