import {readFile,writeFile,mkdir,copyFile,rename,stat} from 'node:fs/promises';
import path from 'node:path';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
import {NodeIO} from '@gltf-transform/core';import {KHRMaterialsEmissiveStrength,KHRMaterialsUnlit,KHRLightsPunctual} from '@gltf-transform/extensions';
import {Engine,validateProject} from '../src/core/engine';import {Grid} from '../src/core/grid';import {displayMesh} from '../src/core/mesh';
import {productionProject} from '../src/production/style';import {referenceFinishCommands} from '../src/production/reference-finish';
import {readAtlasIndex,readAtlasProduction,type AtlasProduction,type AtlasAssemblyBuild} from '../src/production/atlas';
import {architectureAssemblyIds} from '../src/production/atlas-architecture-assemblies';import {assemblyGeometryData,assemblyBoundsM,assemblyExportToleranceM} from '../src/production/assembly-geometry';
import {parseCatalogCSV} from '../src/core/catalog';import {readProductionLibrary} from '../src/production/library';import {exportProject} from '../src/export/exporter';
import {gltfPoints,pointBounds} from './lib/skin-audit';import type {Project,Command} from '../src/core/types';
const resume=process.argv.find(v=>v.startsWith('--resume='))?.slice(9);if(resume&&!/^atlas-\d{14}$/.test(resume))throw new Error('Invalid resume run');
const started=performance.now(),root=path.resolve('projects'),run=resume??'atlas-'+new Date().toISOString().replace(/\D/g,'').slice(0,14),evidence='artifacts/atlas/'+run,out='projects/production/'+run,hash=(x:unknown)=>createHash('sha256').update(typeof x==='string'?x:JSON.stringify(x)).digest('hex');
const source=(await readAtlasIndex(root))!,old=await readAtlasProduction(root),catalog=Object.fromEntries(parseCatalogCSV(await readFile(root+'/catalog/city-assets.csv','utf8')).map(e=>[e.id,e]));
const ids=process.argv.find(v=>v.startsWith('--ids='))?.slice(6).split(','),sheets=process.argv.find(v=>v.startsWith('--sheets='))?.slice(9).split(',');
if(ids?.some(id=>!/^(LIFE|BUILT|ENV|CHAR)-\d{3}$/.test(id))||sheets?.some(s=>!/^M\d{3}$/.test(s)))throw new Error('Invalid assembly selection');
const rows=source.entries.filter(e=>architectureAssemblyIds.includes(e.id)&&(!ids||ids.includes(e.id))&&(!sheets||sheets.includes(e.sheet)));assert.ok(rows.length);if(ids)assert.equal(rows.length,new Set(ids).size);assert.ok(rows.every(e=>e.type==='组合模板'));
const before=await readProductionLibrary(root,{limit:5000}),activeSheets=[...new Set(rows.map(e=>e.sheet))],index:AtlasProduction={format:'yunshan.atlas-production',version:1,run,createdAt:new Date().toISOString(),entries:(old?.entries??[]).filter(e=>!rows.some(r=>r.id===e.id)),studies:(old?.studies??[]).filter(s=>!activeSheets.some(id=>s.id===id+'-gallery'))};
await mkdir(evidence,{recursive:true});await mkdir(out,{recursive:true});const files:any[]=[],models:any[]=[],projects=new Map<string,Project>(),io=new NodeIO().registerExtensions([KHRMaterialsEmissiveStrength,KHRMaterialsUnlit,KHRLightsPunctual]);
function commit(e:Engine,commands:Command[]){const request={expectedVersion:e.project.version,requestId:crypto.randomUUID(),commands},dry=e.execute({...request,dryRun:true});return e.execute({...request,previewToken:dry.previewToken});}
async function save(p:Project,file:string){validateProject(p);const text=JSON.stringify(p);if(resume){try{assert.equal(await readFile(root+'/'+file,'utf8'),text);}catch(e:any){if(e.code!=='ENOENT')throw e;await writeFile(root+'/'+file,text,{flag:'wx'});}}else await writeFile(root+'/'+file,text,{flag:'wx'});files.push({file,sha256:hash(text),bytes:Buffer.byteLength(text)});}
for(const row of rows){
 const t=performance.now(),existingFile=run+'-'+row.id.toLowerCase()+'.ysvox.json';let reused:Project|undefined;if(resume){try{reused=JSON.parse(await readFile(root+'/'+existingFile,'utf8'));validateProject(reused!);}catch(e:any){if(e.code!=='ENOENT')throw e;}}const p=reused??productionProject(row.name);if(!reused)p.catalog={sourceName:'city-assets.csv',importedAt:index.createdAt,entries:structuredClone(catalog)};if(!reused&&row.id==='BUILT-042'){try{const family:Project=JSON.parse(await readFile(root+'/'+run+'-built-040.ysvox.json','utf8'));assert.deepEqual(family.styles,p.styles);p.assets=family.assets;}catch(error:any){if(error.code!=='ENOENT')throw error;}}const e=new Engine(p),assemblyId=row.id.toLowerCase();
 if(!reused){commit(e,[{op:'produceCatalogAssembly',catalogId:row.id,id:assemblyId,place:true}]);commit(e,[...referenceFinishCommands(e.project),{op:'palette',name:'原始素色'}]);}
 const doc=e.project,assembly=doc.assemblies![assemblyId],deps=assembly.source!.dependencies as string[],referenced=new Set([row.id,...deps,...Object.values(doc.assets).map(a=>a.source?.catalogId).filter((v):v is string=>typeof v==='string')]);doc.catalog!.entries=Object.fromEntries(Object.entries(doc.catalog!.entries).filter(([id])=>referenced.has(id)));
 const assetIds=[...new Set(assembly.instances.map(i=>i.assetId))].sort(),boundsM=assemblyBoundsM(doc,assembly),sha256=hash(assemblyGeometryData(doc,assembly)),voxels=assetIds.reduce((s,id)=>s+new Grid(doc.assets[id].chunks).count,0),meshCounts=new Map(assetIds.map(id=>[id,displayMesh(doc.assets[id],doc.materials).reduce((n,b)=>n+b.indices.length/3,0)])),triangles=assembly.instances.reduce((n,i)=>n+meshCounts.get(i.assetId)!,0),file=run+'-'+assemblyId+'.ysvox.json';
 await save(doc,file);let exported;const directory=out+'/exports/'+row.id;if(reused){assert.equal(hash(JSON.parse(await readFile(directory+'/voxels.ysvox.json','utf8')).assets),hash(doc.assets),'Resumed export asset hash');exported={directory,glbBytes:(await stat(directory+'/visual.glb')).size};}else exported=await exportProject(doc,directory);const g=await io.read(exported.directory+'/visual.glb'),nodes=g.getRoot().listScenes()[0].listChildren();assert.equal(nodes.length,assembly.instances.length);const actual=pointBounds(nodes.flatMap(n=>gltfPoints(n))),error=Math.max(...boundsM.min.map((v,i)=>Math.abs(v-actual.min[i])),...boundsM.max.map((v,i)=>Math.abs(v-actual.max[i])));assert.ok(error<assemblyExportToleranceM(doc,assembly),'Actual GLB assembly bounds '+row.id);const roundtrip=JSON.parse(await readFile(exported.directory+'/voxels.ysvox.json','utf8'));assert.equal(hash(roundtrip.assets),hash(doc.assets),'Native asset hash');assert.equal(hash(roundtrip.instances),hash(doc.instances),'Native placement hash');assert.equal(hash(roundtrip.assemblies),hash(doc.assemblies),'Native assembly hash');
 const record:AtlasAssemblyBuild={kind:'assembly',id:row.id,sheet:row.sheet,slot:row.slot,file,assemblyId,assetIds,dependencyCatalogIds:deps,instances:assembly.instances.length,revision:1,referenceSHA256:row.imageSHA256,voxels,triangles,sha256,boundsM,note:'真实组合模板；依赖母版、明确派生组件及重复实例分别保存，不新增基础清单母版。作者尺寸与布局，未绑定原 FloorPlan / 控制器 / 世界地形，待人工美术验收。'};
 index.entries.push(record);models.push({...record,representation:'assembly',componentAssets:assetIds.length,glbBoundsMaxErrorM:error,glbBoundsToleranceM:assemblyExportToleranceM(doc,assembly),glbBytes:exported.glbBytes,reusedExistingDocument:!!reused,totalMs:performance.now()-t});console.log(JSON.stringify({id:row.id,components:assetIds.length,instances:record.instances,storedVoxels:voxels,displayTriangles:triangles,ms:Math.round(performance.now()-t)}));
}
for(const sheet of activeSheets){
 const selected=index.entries.filter((e):e is AtlasAssemblyBuild=>e.kind==='assembly'&&e.sheet===sheet);const gallery=productionProject(sheet+' · '+selected.length+'组资产组合');gallery.catalog={sourceName:'city-assets.csv',importedAt:index.createdAt,entries:{}};gallery.assemblies={};
 const framingBounds=new Map<string,ReturnType<typeof assemblyBoundsM>>();
 for(const row of selected){const doc=JSON.parse(await readFile(root+'/'+row.file,'utf8'));const assembly=doc.assemblies[row.assemblyId];framingBounds.set(row.id,assemblyBoundsM(doc,{instances:assembly.instances.filter((i:any)=>!doc.assets[i.assetId].sky)}));}
 const strideX=Math.ceil((Math.max(...selected.map(e=>{const b=framingBounds.get(e.id)!;return b.max[0]-b.min[0];}))+12)/.2)*.2,strideZ=Math.ceil((Math.max(...selected.map(e=>{const b=framingBounds.get(e.id)!;return b.max[2]-b.min[2];}))+12)/.2)*.2;
 for(const[j,row]of selected.entries()){
  const doc=projects.get(row.id)??JSON.parse(await readFile(root+'/'+row.file,'utf8'));Object.assign(gallery.catalog.entries,doc.catalog.entries);gallery.palettes=structuredClone(doc.palettes);
  for(const[id,a]of Object.entries(doc.assets) as [string,Project['assets'][string]][]){if(gallery.assets[id])assert.deepEqual(gallery.assets[id],a,'Conflicting reused component '+id);else gallery.assets[id]=structuredClone(a);}
  gallery.assemblies[row.assemblyId]=structuredClone(doc.assemblies[row.assemblyId]);const frame=framingBounds.get(row.id)!,offset=[j%4*strideX-Math.floor(frame.min[0]/.2)*.2,-Math.floor(frame.min[1]/.2)*.2,Math.floor(j/4)*strideZ-Math.floor(frame.min[2]/.2)*.2];
  for(const i of Object.values(doc.instances) as Project['instances'][string][])gallery.instances[i.id]={...structuredClone(i),position:i.position.map((v,d)=>Math.round((v+offset[d])*1e8)/1e8) as [number,number,number]};
 }
 const file=run+'-'+sheet.toLowerCase()+'-gallery.ysvox.json';await save(gallery,file);index.studies.push({id:sheet+'-gallery',name:sheet+' · '+selected.length+'组真实组合模板',file,assetIds:Object.keys(gallery.assets),note:'每组保留自身米制布局，组间仅作陈列平移；组间按最大实际包围盒留出陈列间隔。派生组件与重复实例均不新增基础母版。',group:'67 张完整图册'});
}
index.entries.sort((a,b)=>a.sheet.localeCompare(b.sheet)||a.slot-b.slot);try{await copyFile(root+'/atlas-production-index.json',out+'/previous-index.json');}catch(e:any){if(e.code!=='ENOENT')throw e;}await writeFile(out+'/index.json',JSON.stringify(index,null,2));await writeFile(root+'/atlas-production-index.json.tmp',JSON.stringify(index));await rename(root+'/atlas-production-index.json.tmp',root+'/atlas-production-index.json');
const report={run,createdAt:index.createdAt,kind:'assembly-batch',counts:{references:793,rebuiltThisRun:rows.length,newCatalogIds:rows.filter(r=>before.entries.find(e=>e.id===r.id)?.stage==='not-produced').length,newIndependentMasters:0,newAssemblies:rows.filter(r=>before.entries.find(e=>e.id===r.id)?.stage==='not-produced').length,sharedMasterReferences:0,referenceCandidates:index.entries.length,pendingReference:793-index.entries.length,accepted:0,nativeDocuments:files.length},elapsedMs:performance.now()-started,nativeVoxels:models.reduce((s,m)=>s+m.voxels,0),triangles:models.reduce((s,m)=>s+m.triangles,0),glbBoundsMaxErrorM:Math.max(...models.map(m=>m.glbBoundsMaxErrorM)),files,models,out,evidence};
await writeFile(evidence+'/production.json',JSON.stringify(report,null,2));await writeFile(out+'/production.json',JSON.stringify(report,null,2));await writeFile('artifacts/atlas/latest.json',JSON.stringify(report,null,2));await writeFile(evidence+'/catalog-counts.json',JSON.stringify((await readProductionLibrary(root,{limit:1})).counts,null,2));console.log(JSON.stringify({...report,models:undefined,files:undefined},null,2));
