import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,rename} from 'node:fs/promises';
import {NodeIO} from '@gltf-transform/core';
import {KHRMaterialsEmissiveStrength,KHRMaterialsUnlit} from '@gltf-transform/extensions';
import {Engine,validateProject} from '../src/core/engine';
import {parseCatalogCSV} from '../src/core/catalog';
import {Grid} from '../src/core/grid';
import {assetBoundsM,geometryData} from '../src/core/sky';
import {displayMesh} from '../src/core/mesh';
import {productionProject} from '../src/production/style';
import {roofWallFinishCommands} from '../src/production/roof-wall-finish';
import {outfitHash as hash} from '../src/production/outfit-components';
import {exportProject} from '../src/export/exporter';
import {gltfPoints,pointBounds} from './lib/skin-audit';
import {architectureClosed,architectureComponents} from './lib/architecture-audit';
import {nativeIslandAttachments} from '../src/production/mixed-review';
import {roofWallClearBox} from './lib/roof-wall-variant-audit';
import type {Command} from '../src/core/types';

const run=process.argv.find(a=>a.startsWith('--run='))?.slice(6);assert.ok(run&&/^atlas-\d{14}$/.test(run));
const root='projects',out=root+'/production/'+run,evidence='artifacts/atlas/'+run,id='BUILT-004',assetId='built-004',file=run+'-built-004.ysvox.json',directory=out+'/exports/'+id;
const index=JSON.parse(await readFile(root+'/production-index.json','utf8')),entry=index.entries.find((r:any)=>r.id===id);assert.equal(entry.type,'基础组件');assert.equal(entry.stage,'not-produced','Do not overwrite an already produced canonical parent');
const p=productionProject('共享分段实体墙 · 新作者父母版');p.catalog={sourceName:'city-assets.csv',importedAt:new Date().toISOString(),entries:Object.fromEntries(parseCatalogCSV(await readFile(root+'/catalog/city-assets.csv','utf8')).filter(r=>r.id===id).map(r=>[r.id,r]))};
const e=new Engine(p),commit=(commands:Command[])=>{const req={expectedVersion:e.project.version,requestId:crypto.randomUUID(),commands},dry=e.execute({...req,dryRun:true});return e.execute({...req,previewToken:dry.previewToken});};
commit([{op:'produceCatalogAsset',catalogId:id,id:assetId}]);commit([...roofWallFinishCommands(e.project),{op:'palette',name:'原始素色'}]);const a=e.project.assets[assetId];validateProject(e.project);
const closed=architectureClosed(a),native=nativeIslandAttachments({...a,meshes:architectureComponents(a)});assert.ok(closed.every(r=>r.closed&&r.oriented)&&native.every(r=>r.attached));assert.deepEqual(roofWallClearBox(a,[.65,.01,-.1],[1.35,1.73,.5]),[]);assert.deepEqual(roofWallClearBox(a,[3.21,.91,-.1],[5.59,2.39,.5]),[]);
await mkdir(out,{recursive:true});await mkdir(evidence,{recursive:true});await writeFile(root+'/'+file,JSON.stringify(e.project),{flag:'wx'});const exported=await exportProject(e.project,directory,assetId),io=new NodeIO().registerExtensions([KHRMaterialsEmissiveStrength,KHRMaterialsUnlit]),g=await io.read(directory+'/visual.glb'),actual=pointBounds(g.getRoot().listScenes()[0].listChildren().flatMap(n=>gltfPoints(n))),bounds=assetBoundsM(a)!;
const error=Math.max(...bounds.min.map((v,k)=>Math.abs(v-actual.min[k])),...bounds.max.map((v,k)=>Math.abs(v-actual.max[k])));assert.ok(error<1e-5);
const saved=JSON.parse(await readFile(directory+'/voxels.ysvox.json','utf8')),collision=JSON.parse(await readFile(directory+'/collision.json','utf8'));assert.equal(hash(saved.assets[assetId]),hash(a));const c=collision.assets.find((r:any)=>r.id===assetId);assert.equal(hash(c.meshes),hash(a.meshes!.filter(m=>m.collision).map(m=>({name:m.name,positions:m.positions,indices:m.indices,material:m.material}))));assert.equal(hash(c.cells),hash([...new Grid(a.chunks).cells()].filter(([,m])=>e.project.materials[m].solid).map(([v])=>v)));
const record={id,kind:'base',file,assetId,assetIds:[assetId],exportDirectory:directory,dependencyCatalogIds:[],sha256:hash(geometryData(a)),boundsM:bounds,voxels:new Grid(a.chunks).count,triangles:displayMesh(a,e.project.materials).reduce((n,m)=>n+m.indices.length/3,0),note:'新独立作者父母版；0.4m墙身及实际门窗开洞。无参考图格位，原FloorPlan未提供，不冒称历史原件。'};
await copyFile(root+'/production-index.json',out+'/previous-production-index.json');Object.assign(entry,{stage:'geometry-candidate',file,assetIds:[assetId],voxels:record.voxels,triangles:record.triangles,sha256:record.sha256,note:record.note});index.counts.baseModels++;index.counts.generatedEntries++;index.counts.notProduced--;await writeFile(root+'/production-index.json.tmp',JSON.stringify(index));await rename(root+'/production-index.json.tmp',root+'/production-index.json');
const report={run,status:'passed',newIndependentMasters:1,atlasReferenceEntries:0,record,actualExportFiles:exported.files,glbBoundsMaxErrorM:error,closedParts:closed.length,nativeAttachments:native,canonicalNativeAndCollisionIdentical:true};await writeFile(evidence+'/new-base-production.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
