import {readFile,writeFile,copyFile} from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';

const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),comparison=JSON.parse(await readFile('artifacts/material-classification/saved-comparison.json','utf8')),audit=JSON.parse(await readFile(path.join(latest.evidence,'material-audit.json'),'utf8')),previews=JSON.parse(await readFile(path.join(latest.evidence,'previews.json'),'utf8'));
assert.equal(comparison.currentRun,index.run);assert.equal(audit.run,index.run);assert.equal(audit.reviewedCandidates,108);assert.equal(audit.pendingCandidates,0);assert.equal(previews.errors.length,0);
const out=latest.evidence,ids=['LIFE-046','LIFE-057','LIFE-106','LIFE-107','LIFE-043','LIFE-082','LIFE-085','LIFE-096'];
const descriptions=['白釉 / 青釉都属于陶瓷','毛巾与织入纹样均为织物','封皮、纸页、书脊布、油墨独立','卷纸与画面油墨分开','涂装金属、塑料内衬、橡胶门封','浅壳是涂装金属，石材只在脚座','矿石基质与矿脉不借硬件金属','纸包、玻璃瓶、塑料盖与标签独立'];
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const cards=[];
for(const [i,id]of ids.entries()){
 const row=index.entries.find((r:any)=>r.id===id),record=audit.records.find((r:any)=>r.id===id),file='classification-before-'+id+'.png';
 await copyFile(path.join('artifacts/atlas',comparison.baselineRun,'screenshots',id+'-isometric.png'),path.join(out,file));
 cards.push({id,description:descriptions[i],before:file,after:'screenshots/'+id+'-isometric.png',native:row.file,assignments:record.assignments,change:comparison.records.find((r:any)=>r.id===id)});
}
await copyFile('artifacts/material-classification/saved-comparison.json',path.join(out,'material-classification-comparison.json'));
const summary=`${comparison.compared} 件逐格对照 · ${comparison.changedCandidates} 件修正 · ${comparison.modifiedVoxels.toLocaleString()} 个材质格重新赋值 · 几何占用、尺寸、接口和孔洞不变`;
const tableRows=audit.records.map((r:any)=>{const c=comparison.records.find((v:any)=>v.id===r.id),name=previews.items.find((v:any)=>v.id===r.id).name;return `<tr data-changed="${c.changedMaterialCells>0}"><td>${r.id}<small>${esc(name)}</small></td><td>${esc(r.authoredDecision)}</td><td>${r.assignments.map((m:any)=>`<span class="tag">${esc(m.roles.join(' / ').replaceAll('yunshan.',''))} <b>#${m.id}</b> ${esc(m.category)} · ${m.occupiedCells.toLocaleString()} 格</span>`).join('')}</td><td>${c.changedMaterialCells.toLocaleString()}<small>碰撞标记修正 ${c.changedCollisionCells.toLocaleString()}</small></td></tr>`;}).join('');
const style=`*{box-sizing:border-box}body{margin:0;font:16px system-ui,'PingFang SC';background:#eef0eb;color:#283b35}header{padding:32px 42px;background:#243c33;color:#eef3eb}h1{font-size:32px;margin:0 0 13px}header p{margin:8px 0;max-width:1200px}main{padding:24px 28px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}article{border:1px solid #c6cec3;background:white;border-radius:6px;overflow:hidden}article img{display:block;width:100%}h2{font-size:18px;margin:0;padding:16px 18px 6px}article p{margin:0;padding:0 18px 18px;line-height:1.6;color:#536458}nav{display:flex;gap:12px;align-items:center;margin:0 0 18px}button{background:white;color:#284135;border:1px solid #b7c4b8;border-radius:4px;padding:8px 15px;font:inherit;cursor:pointer}button.active{background:#365847;color:white}section.note{padding:20px;margin:24px 0;background:#e0e8dc;line-height:1.8}a{color:#306454}table{width:100%;border-collapse:collapse;background:#fff}th,td{text-align:left;vertical-align:top;padding:14px;border:1px solid #c7d0c3}th{background:#dce5d7}th:first-child{width:180px}th:nth-child(2){width:30%}small{display:block;font-size:12px;color:#657267;margin-top:5px}.tag{display:inline-block;margin:2px 4px 2px 0;padding:3px 7px;border-radius:3px;background:#edf0e9;font-size:12px}footer{padding:28px 42px;color:#5d6b60}`;
const top=`<header><h1>云山 · 材质分类整改</h1><p>${summary}</p><p>真实原生体素与 WebGL 截图。颜色相近也保持独立用途 ID；这些是候选资产，没有新增母版或通过美术验收。</p></header>`;
const cardHTML=`<div class="cards">${cards.map(c=>`<article><img data-before="${c.before}" data-after="${c.after}" src="${c.after}" alt="${c.id} 编辑器素色截图"><h2>${c.id} · ${c.description}</h2><p>${c.change.changedMaterialCells.toLocaleString()} 格改分类。占用位置全部保留。<br>保存记录：${esc(c.native)}</p></article>`).join('')}</div>`;
const note=`<section class="note"><b>验证范围</b><br>只更换织物外观时，陶瓷、纸、玻璃、显示像素保持原样；MCP 与 UI 的材质哈希一致，一次撤销恢复。<br>本轮纠正了 ${comparison.collisionChanges.toLocaleString()} 个格子的碰撞标记，主要涉及显示像素、错误食材绑带和透明硬塑料护片。这是分类整改；后续材质包换装不会改碰撞。<br>所有截图为素色，不含纹理、AO、辉光。玻璃在此模式下显示为实色。瓶的空腔、细节密度、设备动画与参考美术差距仍需继续制作。</section>`;
const overview='<!doctype html><meta charset="utf-8"><style>'+style+'</style>'+top+'<main>'+cardHTML+note+'</main>';
await writeFile(path.join(out,'material-classification-overview.html'),overview);
const html=overview.replace('</main>',`<nav><button id="after" class="active">修正后素色</button><button id="before">修正前素色</button><span>同一观察方向、各自适配画幅；修改分类不是重新塑形</span></nav><p><a href="material-classification-comparison.json">逐格比较 JSON</a> · <a href="material-audit.json">实际格子的材质 ID / 类别</a> · <a href="mcp-classification-roles.png">MCP 织物独立换色</a> · <a href="mcp-classification-roles-restored.png">一次撤销</a></p><h2>逐件作者分类决定</h2><label><input type="checkbox" id="changed"> 只看本轮改变 ID 的 54 件</label><table><thead><tr><th>母版</th><th>材料与用途决定</th><th>实际材质格</th><th>重赋值格数</th></tr></thead><tbody>${tableRows}</tbody></table></main><footer>分类基于明确制作决定，不是从参考图片自动识别物理材料。旧原件、源图及此前失败案例保留。</footer><script>for(const key of ['before','after'])document.getElementById(key).onclick=()=>{for(const i of document.querySelectorAll('img[data-before]'))i.src=i.dataset[key];for(const k of ['before','after'])document.getElementById(k).classList.toggle('active',k===key)};document.getElementById('changed').onchange=e=>{for(const r of document.querySelectorAll('tr[data-changed]'))r.hidden=e.target.checked&&r.dataset.changed==='false'};</script>`);
await writeFile(path.join(out,'material-classification.html'),html);
const browser=await chromium.launch({headless:true,channel:'chromium'});try{const page=await browser.newPage({viewport:{width:2200,height:1250}});await page.goto(pathToFileURL(path.join(out,'material-classification-overview.html')).href);await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await page.screenshot({path:path.join(out,'material-classification-overview.png'),fullPage:true});}finally{await browser.close();}
await writeFile(path.join(out,'material-classification-report.json'),JSON.stringify({run:index.run,...comparison,records:undefined,cards,reviewed:audit.reviewedCandidates,pending:audit.pendingCandidates},null,2));console.log(path.join(out,'material-classification.html'));
