import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {NodeIO} from '@gltf-transform/core';
import {KHRMaterialsEmissiveStrength} from '@gltf-transform/extensions';
import {validationBrowserOptions} from './browser-options';
import {parseCatalogCSV} from '../src/core/catalog';
import {productionProject} from '../src/production/style';
import * as assembly from '../src/production/neighborhood-assembly';
import type {Command,Project,V3} from '../src/core/types';

const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),out=latest.evidence,runtime=path.join(out,`neighborhood-mcp-${Date.now()}-runtime`),url='http://127.0.0.1:4359',gallery=index.studies.find((s:any)=>s.id==='M023-gallery');assert.ok(gallery);
await mkdir(runtime,{recursive:true});for(const f of['atlas-production-index.json','production-index.json',gallery.file,...index.entries.filter((e:any)=>e.sheet==='M023').map((e:any)=>e.file)])await copyFile(path.join('projects',f),path.join(runtime,f));
await cp('projects/reference-atlas',path.join(runtime,'reference-atlas'),{recursive:true});await copyFile(path.join(runtime,gallery.file),path.join(runtime,'autosave.ysvox.json'));
const empty=productionProject('M023 · 真实 MCP 拼装');empty.catalog={sourceName:'city-assets.csv',importedAt:'verification',entries:Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]))};await writeFile(path.join(runtime,'empty.ysvox.json'),JSON.stringify(empty));
const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),state=async():Promise<Project>=>(await fetch(url+'/api/state').then(r=>r.json())).project;
const report:any={run:index.run,startedAt:new Date().toISOString(),status:'running',checks:[],errors:[],uiSync:[],assemblies:[]};let server:ChildProcess|undefined,client:Client|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,log='';
async function start(){server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4359',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok)return;}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}throw new Error('Server startup timeout');}
async function stop(){if(server&&server.exitCode===null){const closed=once(server,'exit');server.kill('SIGTERM');await closed;}}
function clean(c:any,unsupported:string[]=[],nearPairs:string[][]=[]){assert.deepEqual(c.unsupported,unsupported);assert.deepEqual(c.gaps.map((g:any)=>g.instances),nearPairs);for(const g of c.gaps)assert.ok(Math.abs(g.distanceM-.1)<1e-8);for(const k of['collisions','warnings'])assert.deepEqual(c[k],[],k);assert.ok(c.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));assert.ok(c.clearances.every((o:any)=>o.clear));}
try{
 await start();client=new Client({name:'neighborhood-semantic-validation',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],env:{...process.env as Record<string,string>,VOXEL_URL:url},cwd:process.cwd(),stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const t=performance.now(),r:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(JSON.stringify({tool:name,ms:performance.now()-t,error:!!r.isError}));return{...JSON.parse(r.content[0].text),isError:!!r.isError};};
 const call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 browser=await chromium.launch(validationBrowserOptions());report.browser=browser.version();const page=await browser.newPage({viewport:{width:1600,height:1050}});page.setDefaultTimeout(120000);page.on('pageerror',e=>report.errors.push(e.message));await page.goto(url+'/?atlas=1&sheet=M023&asset=built-245&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready,null,{timeout:120000});
 report.webgl=await page.evaluate(()=>{const gl=(document.querySelector('#viewport canvas') as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return gl.getParameter(ext?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);});
 const sync=async(v:number)=>{const t=performance.now();await page.waitForFunction(n=>(window as any).voxelStudio.performance.renderedVersion===n,v,{timeout:120000});report.uiSync.push({version:v,ms:performance.now()-t});};
 const before=await state(),roles=before.styles.yunshan,check=await call('check_geometry');clean(check);assert.equal(check.collisionGrids.length,12);report.gallery=check;
 for(const [assetId,point,role]of[
  ['built-225',[2,3.05,1],'bridgeBearing'],['built-232',[.55,1.55,.55],'wall'],['built-233',[1,.775,2],'wall'],['built-234',[1,.675,6.075],'wall'],
  ['built-235',[2,2.7,.2],'woodEdge'],['built-240',[1,.475,.2],'waterproofMembrane'],['built-241',[.5,1.15,.5],'projectorLens'],['built-241',[.5,1.075,.5],'projectorEmitter'],
  ['built-242',[.125,.4,.2],'glass'],['built-243',[1,.75,.175],'metal'],['built-244',[.5,1.12,.1],'woodEdge'],['built-245',[.175,.8,.1],'timberWindowSeal'],['built-246',[.1,.525,.01],'roof'],
 ] as [string,V3,string][]){const a=before.assets[assetId],v=point.map(n=>Math.floor((n+1e-8)/a.cellSize)),r=await call('query_voxels',{assetId,region:{min:v,max:v.map(n=>n+1)}});assert.equal(r.cells[0]?.[1],roles[role]);}
 for(const z of[.1,.16]){const a=before.assets['built-245'],v=[.5,.8,z].map(n=>Math.floor((n+1e-8)/a.cellSize)),r=await call('query_voxels',{assetId:'built-245',region:{min:v,max:v.map(n=>n+1)}});assert.equal(r.total,0,'Both window glass faces are clear of opaque seal cells');}
 assert.equal(before.materials[roles.projectorEmitter].intensity,0);assert.equal((before.assets['built-241'].source!.projector as any).powerBound,false);
 report.checks.push('Twelve M023 families verified from native coordinates: bearing, stone, wood grain, waterproof liner, independent projector lens and inactive emitter, timber window seal and roof tiles');
 const changed=['projectorLens','projectorEmitter','timberWindowSeal','woodEdge'],request={expectedVersion:before.version,requestId:crypto.randomUUID(),label:'M023街区木构独立外观包验证',commands:[{op:'definePalette',name:'街区独立材质',materials:Object.fromEntries(changed.map((r,i)=>[roles[r],{color:['#703943','#33806b','#455456','#85abb6'][i]}]))},{op:'palette',name:'街区独立材质'}]};
 const dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(before));const applied=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(applied.version);const after=await state();assert.equal(applied.modifiedVoxels,0);for(const k of['assets','styles']as const)assert.equal(hash(after[k]),hash(before[k]));
 for(const[id,m]of Object.entries(before.materials)){assert.equal(after.materials[id].solid,m.solid);assert.equal(after.materials[id].category,m.category);if(!changed.some(r=>String(roles[r])===id))assert.deepEqual(after.materials[id],m);}assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(after.materials));
 await page.locator('#material-category-filter').selectOption('glass');const buttons=await page.locator('[data-material]').evaluateAll(nodes=>nodes.map(n=>Number((n as HTMLElement).dataset.material)));assert.ok(buttons.includes(roles.projectorLens));for(const id of buttons)assert.equal(after.materials[id].category,'glass');await page.locator('[data-material="'+roles.projectorLens+'"]').click();assert.match(await page.locator('#material-role').innerText(),/yunshan.projectorLens/);await page.screenshot({path:path.join(out,'mcp-neighborhood-roles.png')});
 assert.equal((await call('edit_transaction',request)).version,applied.version);assert.equal((await raw('edit_transaction',{...request,requestId:crypto.randomUUID()})).code,'VERSION_CONFLICT');const failed=await raw('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:roles.projectorLens,properties:{color:'#ff00ff'}},{op:'produceCatalogAsset',catalogId:'BUILT-242',id:'bad',params:{component:'cap'}}]});assert.ok(failed.isError);assert.equal(hash(await state()),hash(after));
 const undo=await call('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(undo.version);for(const k of['assets','styles','materials','palettes']as const)assert.equal(hash((await state())[k]),hash(before[k]));await page.screenshot({path:path.join(out,'mcp-neighborhood-roles-restored.png')});report.checks.push('Four independent architectural appearance roles, canonical UI hashes, glass filtering, dry run, version conflicts, idempotency, failure rollback and one undo all verified');
 const scenario=async(name:string,commands:Command[],clearances:{name:string;min:V3;max:V3}[],unsupported:string[]=[],nearPairs:string[][]=[])=>{
  const loaded=await call('load_project',{filename:'empty.ysvox.json',expectedVersion:(await state()).version});await sync(loaded.version);const request={expectedVersion:loaded.version,requestId:crypto.randomUUID(),commands},initial=await state(),dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(initial));const built=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(built.version);await page.evaluate(()=>(window as any).voxelStudio.mode('scene'));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const geometry=await call('check_geometry',{clearances});clean(geometry,unsupported,nearPairs);const doc=await state();assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets)),hash(doc.assets));await page.screenshot({path:path.join(out,'mcp-'+name+'.png')});
  const saved=await call('save_project',{filename:name+'.ysvox.json'});await copyFile(saved.path,path.join(out,name+'.ysvox.json'));const exported=await call('export_project',{name}),round=JSON.parse(await readFile(path.join(exported.directory,'voxels.ysvox.json'),'utf8'));for(const k of['assets','instances','materials','styles']as const)assert.equal(hash(round[k]),hash(doc[k]));await cp(exported.directory,path.join(out,name+'-export'),{recursive:true});
  const previews=await call('generate_previews',{appearance:'baseColor',views:['isometric','front']});assert.equal(previews.files.length,2);for(let i=0;i<2;i++){assert.ok((await readFile(previews.files[i])).length>1000);await copyFile(previews.files[i],path.join(out,name+'-view-'+i+'.png'));}report.assemblies.push({name,masters:Object.keys(doc.assets).length,placements:Object.keys(doc.instances).length,geometry,expectedUnsupported:unsupported,expectedNearPairs:nearPairs,exported,previews});return doc;
 };
 await page.locator('#material-category-filter').selectOption('all');
 const definitions=await client.listTools();await writeFile('docs/tool-schemas.json',JSON.stringify(definitions.tools,null,2));
 const recipes=await call('list_production_recipes',{query:'BUILT-242'});assert.deepEqual(recipes.entries[0].parameters.component.enum,['stairFlight','halfTurn','upperWell']);report.checks.push('MCP advertises recipe-specific flight, half-turn and upper-well guard components without inflating catalogue master counts');
 const skywalk=await scenario('neighborhood-skywalk',assembly.neighborhoodSkywalkCommands(roles),assembly.neighborhoodSkywalkClearances);assert.deepEqual(skywalk.assets.bearing.source!.storeyBearingTopsM,[3.2,6.4]);report.checks.push('The same solid end support contacts both floor levels and connected skywalks; actual 1.72m routes stay clear');
 const terrain=await scenario('neighborhood-terrain',assembly.neighborhoodTerrainCommands(roles),assembly.neighborhoodTerrainClearances);assert.equal((terrain.assets.platform.source!.terrainFixture as any).originalTerrain,false);assert.equal((terrain.assets.ramp.source!.ramp as any).analyticSlope,false);report.checks.push('Finite L-shaped platform contacts four explicit terrain height bands; eight real 0.2m rises and a solid voxel ramp connect to the common platform without original-terrain or controller claims');
 const garden=await scenario('neighborhood-garden',assembly.neighborhoodGardenCommands(roles),assembly.neighborhoodGardenClearances);assert.equal((garden.assets.planter.source!.planting as any).plantsIncluded,false);assert.equal((garden.assets.emitter.source!.projector as any).hologramIncluded,false);assert.equal(garden.materials[roles.projectorEmitter].intensity,0);report.checks.push('Open courtyard portal, empty planter shells and through-drains preserve body routes; physical emitter has no hologram or bound power');
 const stairs=await scenario('neighborhood-stairs',assembly.neighborhoodStairsCommands(roles),assembly.neighborhoodStairClearances);assert.equal(stairs.assets.well.source!.component,'upperWell');assert.equal(stairs.assets.turn.source!.component,'halfTurn');report.checks.push('Four flight rails, a half-turn rail and an upper-well rail attach to actual stair surfaces; upper opening, normal exit and separate roof public exit remain clear');
 const closed=await scenario('neighborhood-joinery-closed',assembly.neighborhoodJoineryCommands(roles,false),[]),closedCheck=await call('check_geometry',{clearances:[assembly.neighborhoodClosedDoorClearance]});assert.equal(closedCheck.clearances[0].clear,false);assert.ok(closedCheck.clearances[0].blockedBy.includes('door-1'));
 const opened=await scenario('neighborhood-joinery-open',assembly.neighborhoodJoineryCommands(roles,true),assembly.neighborhoodJoineryClearances),openCheck=await call('check_geometry',{clearances:[assembly.neighborhoodClosedDoorClearance]});assert.equal(openCheck.clearances[0].clear,true);assert.equal(hash(opened.assets.door),hash(closed.assets.door));assert.equal((opened.assets.door.source!.door as any).runtimeOperation,false);report.doorStateProbes={closed:closedCheck.clearances,open:openCheck.clearances,sameNativeLeaf:true,sharedRuntimeBound:false};
 const glb=await new NodeIO().registerExtensions([KHRMaterialsEmissiveStrength]).read(path.join(out,'neighborhood-joinery-open-export','visual.glb')),node=glb.getRoot().listNodes().find(n=>n.getExtras().instanceId==='eave-1')!;assert.ok(node);assert.deepEqual(node.getTranslation(),[.8,3.2,-.2]);const positions=node.getMesh()!.listPrimitives().flatMap(p=>Array.from(p.getAttribute('POSITION')!.getArray()!).filter((_,i)=>i%3===1)),top=Math.max(...positions)+node.getTranslation()[1];assert.ok(Math.abs(top-4)<1e-6);report.eaveGLB={translation:node.getTranslation(),worldTopYM:top};
 report.checks.push('Identical door leaf explicitly closes or clears the authored opening around one real hinge axis, while window and thin 4.8m eave retain true supports; no runtime door-state claim');
 report.checks.push('All six scenarios save real stdio MCP multiview previews plus GLB/native/collision/interface/material-atlas exports');
 const last=await call('save_project',{filename:'verified-neighborhood-joinery.ysvox.json'}),saved=await state();assert.equal(hash(JSON.parse(await readFile(last.path,'utf8'))),hash(saved));await stop();await start();assert.equal(hash(await state()),hash(saved));report.checks.push('Native save and server restart restore the exact canonical document');
 assert.deepEqual(report.errors,[]);report.status='passed';report.completedAt=new Date().toISOString();console.log(JSON.stringify({status:report.status,checks:report.checks.length,out}));
}catch(error){report.status='failed';report.errors.push(String(error));throw error;}finally{await browser?.close();await client?.close();await stop();await writeFile(path.join(out,'neighborhood-mcp-verification.json'),JSON.stringify(report,null,2));await writeFile(path.join(out,'neighborhood-mcp-server.log'),log);}
