import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {NodeIO} from '@gltf-transform/core';
import {KHRMaterialsEmissiveStrength,KHRMaterialsUnlit,KHRLightsPunctual} from '@gltf-transform/extensions';
import {Engine,validateProject} from '../src/core/engine';
import {Grid} from '../src/core/grid';
import {geometryData} from '../src/core/sky';
import {displayMesh} from '../src/core/mesh';
import {buildGLB,exportProject} from '../src/export/exporter';
import {assemblyGeometryData,assemblyBoundsM,assemblyExportToleranceM} from '../src/production/assembly-geometry';
import {makeArchitectureAssembly} from '../src/production/atlas-architecture-assemblies';
import {livingVariants} from '../src/production/living-assemblies';
import {productionProject} from '../src/production/style';
import {referenceFinishCommands} from '../src/production/reference-finish';
import {parseCatalogCSV} from '../src/core/catalog';
import {outfitHash} from '../src/production/outfit-components';
import {nativeIslandAttachments} from '../src/production/mixed-review';
import {wildlifeClosed,wildlifeComponents} from './lib/wildlife-audit';
import {livingAudit} from './lib/living-audit';
import {gltfPoints,pointBounds} from './lib/skin-audit';
import type {Project,Command} from '../src/core/types';
const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),rows=latest.models,hash=outfitHash,io=new NodeIO().registerExtensions([KHRMaterialsEmissiveStrength,KHRMaterialsUnlit,KHRLightsPunctual]),catalog=Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(e=>[e.id,e]));
assert.equal(latest.kind,'assembly-batch');assert.equal(rows.length,6);assert.ok(rows.every((r:any)=>r.sheet==='M059'));
const records:any[]=[],variants:any[]=[],materialChecks:any[]=[],configurations=new Set<string>(),shapeConfigurations=new Set<string>();
const commit=(e:Engine,commands:Command[])=>{const req={expectedVersion:e.project.version,requestId:crypto.randomUUID(),commands},dry=e.execute({...req,dryRun:true});return e.execute({...req,previewToken:dry.previewToken});};
for(const row of rows)for(const[form,params]of livingVariants(row.id).entries()){
 let p:Project,directory:string;
 if(form===0){p=JSON.parse(await readFile('projects/'+row.file,'utf8'));directory=latest.out+'/exports/'+row.id;}
 else{p=productionProject(row.id+' '+JSON.stringify(params));p.catalog={sourceName:'city-assets.csv',importedAt:latest.createdAt,entries:structuredClone(catalog)};const e=new Engine(p);commit(e,[{op:'produceCatalogAssembly',catalogId:row.id,id:row.assemblyId,place:true,params}]);commit(e,[...referenceFinishCommands(e.project),{op:'palette',name:'原始素色'}]);p=JSON.parse(JSON.stringify(e.project));const deps=new Set([row.id,...p.assemblies![row.assemblyId].source!.dependencies as string[]]);p.catalog!.entries=Object.fromEntries(Object.entries(p.catalog!.entries).filter(([id])=>deps.has(id)));directory=latest.out+'/variants/'+row.id+'-'+Object.values(params).join('-');await exportProject(p,directory);}
 const a=p.assemblies![row.assemblyId];validateProject(p);if(!form)assert.equal(hash(assemblyGeometryData(p,a)),row.sha256);assert.deepEqual(a.source!.parameters,params);
 const audit=livingAudit(p,a);assert.ok(audit.pairs.every(r=>r.contained===0&&r.crossing===0),row.id+JSON.stringify(params));assert.ok(audit.contactsPassed&&audit.groundPassed&&audit.animalGroundPassed&&audit.nonphysical&&audit.rigsRetained);if(audit.view)assert.ok(audit.view.centerHits===0&&audit.view.visibleHandFraction<.12&&audit.view.maxZ<-.05&&audit.view.heldObjects===0);
 const closed=[],pins=[],provenance=[];
 for(const asset of Object.values(p.assets)){
  const c=wildlifeClosed(asset);assert.ok(c.every(r=>r.closed&&r.oriented),asset.id);closed.push({assetId:asset.id,parts:c.length});const n=nativeIslandAttachments({...asset,meshes:wildlifeComponents(asset)});assert.ok(n.every(r=>r.attached),asset.id);pins.push({assetId:asset.id,islands:n.length,cells:n.reduce((n,r)=>n+r.cells,0)});
  if(asset.source?.sourceAssetId){const parent=p.assets[String(asset.source.sourceAssetId)];assert.ok(parent);assert.equal(asset.source.sourceGeometrySHA256,hash(geometryData(parent)));provenance.push({assetId:asset.id,parentId:parent.id,parentGeometrySHA256:hash(geometryData(parent)),preservedOriginal:true});}
  for(const m of asset.meshes??[]){assert.ok(p.materials[m.material]);assert.equal(m.collision,p.materials[m.material].solid);}
 }
 const native=JSON.parse(await readFile(directory+'/voxels.ysvox.json','utf8')),interfaces=JSON.parse(await readFile(directory+'/interfaces.json','utf8')),collision=JSON.parse(await readFile(directory+'/collision.json','utf8'));
 for(const k of['assets','instances','assemblies','styles','materials','palettes']as const)assert.deepEqual(native[k],p[k]);assert.deepEqual(interfaces.assemblies,p.assemblies);assert.deepEqual(interfaces.instances,Object.values(p.instances));assert.deepEqual(collision.instances,Object.values(p.instances));
 for(const asset of Object.values(p.assets)){const c=collision.assets.find((r:any)=>r.id===asset.id);assert.ok(c);assert.deepEqual(c.cells,[...new Grid(asset.chunks).cells()].filter(([,m])=>p.materials[m].solid).map(([v])=>v));if(asset.meshes){assert.equal(c.voxelProxy,false);assert.deepEqual(c.meshes,asset.meshes.filter(m=>m.collision).map(m=>({name:m.name,positions:m.positions,indices:m.indices,material:m.material})));}}
 const e=new Engine(p);commit(e,[{op:'palette',name:'参考材质试作'}]);assert.deepEqual(e.project.assets,p.assets);const bounds=assemblyBoundsM(p,a),tolerance=assemblyExportToleranceM(p,a),exports=[];
 for(const[key,doc,mode]of[['visual',p,'near'],['visual-far',p,'far'],['visual-material',e.project,'near']]as const){let bytes:Uint8Array;if(key==='visual')bytes=await readFile(directory+'/visual.glb');else{const data=await buildGLB(doc,undefined,mode);bytes=data.glb;await writeFile(directory+'/'+key+'.glb',bytes);}const gltf=await io.readBinary(bytes),nodes=gltf.getRoot().listScenes()[0].listChildren();assert.equal(nodes.length,a.instances.length);assert.deepEqual(gltf.getRoot().listScenes()[0].getExtras().assemblyDefinitions,p.assemblies);const actual=pointBounds(nodes.flatMap(n=>gltfPoints(n))),error=Math.max(...bounds.min.map((v,k)=>Math.abs(v-actual.min[k])),...bounds.max.map((v,k)=>Math.abs(v-actual.max[k])));assert.ok(error<tolerance);exports.push({key,bytes:bytes.length,boundsErrorM:error,toleranceM:tolerance,independentSkinEvaluation:true});}
 for(const i of a.instances){const asset=p.assets[i.assetId],ids=[...new Set([...new Grid(asset.chunks).cells()].map(([,m])=>m).concat((asset.meshes??[]).map(m=>m.material)))];assert.ok(ids.every(id=>!p.materials[id].solid&&p.materials[id].intensity===0));materialChecks.push({id:row.id,params,assetId:asset.id,purposeRoles:Object.entries(p.styles.yunshan).filter(([,m])=>ids.includes(m)).map(([role])=>role),nonphysical:true,zeroEmission:true});}
 const configuration=a.instances.map(i=>({geometry:geometryData(p.assets[i.assetId]),position:i.position,rotation:i.rotation}));configurations.add(hash(configuration));shapeConfigurations.add(hash(a.instances.map(i=>{const asset=p.assets[i.assetId];return{origin:asset.origin,cellSize:asset.cellSize,positions:(asset.meshes??[]).map(m=>m.positions),indices:(asset.meshes??[]).map(m=>m.indices),native:[...new Grid(asset.chunks).cells()].map(([v])=>v),rig:asset.rig,position:i.position,rotation:i.rotation};})));const near=a.instances.reduce((n,i)=>n+displayMesh(p.assets[i.assetId],p.materials).reduce((n,m)=>n+m.indices.length/3,0),0),far=a.instances.reduce((n,i)=>n+displayMesh(p.assets[i.assetId],p.materials,'far').reduce((n,m)=>n+m.indices.length/3,0),0);assert.ok(far<=near);
 const record={id:row.id,params,isDefault:form===0,directory,file:form===0?row.file:directory+'/voxels.ysvox.json',assemblyId:a.id,dependencyCatalogIds:a.source!.dependencies,instances:a.instances.length,closed,pins,provenance,living:audit,nearTriangles:near,farTriangles:far,exports,geometrySHA256:hash(assemblyGeometryData(p,a)),nativeInterfacesAndActualCollisionIdentical:true};records.push(record);if(form)variants.push(record);console.log(JSON.stringify({id:row.id,params,instances:a.instances.length,posedPairs:audit.pairs.length,contacts:audit.contacts.length,near,far}));
}
assert.equal(records.length,12);assert.equal(variants.length,6);const gallery=index.studies.find((r:any)=>r.id==='M059-gallery'),gp:Project=JSON.parse(await readFile('projects/'+gallery.file,'utf8')),galleryBounds=Object.values(gp.assemblies!).map(a=>({id:a.id,...assemblyBoundsM(gp,{instances:a.instances.map(i=>gp.instances[i.id])})}));for(let i=0;i<galleryBounds.length;i++)for(let j=i+1;j<galleryBounds.length;j++)assert.ok(galleryBounds[i].min.some((v,k)=>v>=galleryBounds[j].max[k]||galleryBounds[i].max[k]<=galleryBounds[j].min[k]));
await writeFile(latest.evidence+'/assembly-verification.json',JSON.stringify({run:latest.run,status:'passed',records,variants,gallery:gallery.id,galleryBounds,galleryGroupsDisjoint:true,defaultTemplates:6,finiteForms:12,distinctGeometryConfigurations:shapeConfigurations.size,distinctAppearanceConfigurations:configurations.size,newBaseMasters:0,partialSheet:true,remainingSheetIds:['BUILT-025','BUILT-026','BUILT-027','BUILT-028','BUILT-029','BUILT-030']},null,2));
await writeFile(latest.evidence+'/material-audit.json',JSON.stringify({run:latest.run,status:'passed',candidates:6,pendingCandidates:0,newRoles:[],totalRoles:512,creationBatches:[256,256],checks:materialChecks,note:'All inherited component purposes preserved. Fitted wraps retain bandageCloth/garmentStrap/garmentBuckle. Animal soft liners use harnessLiner, original petWebbing/buckles/hardware remain distinct.176 view sleeves explicitly share NPC113 garmentLight/garmentLining purposes with skin/nails unchanged.512-role cap unchanged; no emission, no collision.'},null,2));
