import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {NodeIO} from '@gltf-transform/core';
import {KHRMaterialsEmissiveStrength} from '@gltf-transform/extensions';
import {validationBrowserOptions} from './browser-options';
import {parseCatalogCSV} from '../src/core/catalog';
import {productionProject} from '../src/production/style';
import * as assembly from '../src/production/aerial-assembly';
import type {Command,Project,V3} from '../src/core/types';

const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),out=latest.evidence,runtime=path.join(out,`aerial-mcp-${Date.now()}-runtime`),url='http://127.0.0.1:4357',gallery=index.studies.find((s:any)=>s.id==='M021-gallery');assert.ok(gallery);
await mkdir(runtime,{recursive:true});for(const f of['atlas-production-index.json','production-index.json',gallery.file,...index.entries.filter((e:any)=>e.sheet==='M021').map((e:any)=>e.file)])await copyFile(path.join('projects',f),path.join(runtime,f));
await cp('projects/reference-atlas',path.join(runtime,'reference-atlas'),{recursive:true});await copyFile(path.join(runtime,gallery.file),path.join(runtime,'autosave.ysvox.json'));
const empty=productionProject('M021 · 真实 MCP 拼装');empty.catalog={sourceName:'city-assets.csv',importedAt:'verification',entries:Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]))};await writeFile(path.join(runtime,'empty.ysvox.json'),JSON.stringify(empty));
const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),state=async():Promise<Project>=>(await fetch(url+'/api/state').then(r=>r.json())).project;
const report:any={run:index.run,startedAt:new Date().toISOString(),status:'running',checks:[],errors:[],uiSync:[],assemblies:[]};let server:ChildProcess|undefined,client:Client|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,log='';
async function start(){server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4357',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok)return;}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}throw new Error('Server startup timeout');}
async function stop(){if(server&&server.exitCode===null){const closed=once(server,'exit');server.kill('SIGTERM');await closed;}}
function clean(c:any,unsupported:string[]=[],nearPairs:string[][]=[]){assert.deepEqual(c.unsupported,unsupported);assert.deepEqual(c.gaps.map((g:any)=>g.instances),nearPairs);for(const g of c.gaps)assert.ok(Math.abs(g.distanceM-.1)<1e-8);for(const k of['collisions','warnings'])assert.deepEqual(c[k],[],k);assert.ok(c.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));assert.ok(c.clearances.every((o:any)=>o.clear));}
try{
 await start();client=new Client({name:'aerial-semantic-validation',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],env:{...process.env as Record<string,string>,VOXEL_URL:url},cwd:process.cwd(),stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const t=performance.now(),r:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(JSON.stringify({tool:name,ms:performance.now()-t,error:!!r.isError}));return{...JSON.parse(r.content[0].text),isError:!!r.isError};};
 const call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 browser=await chromium.launch(validationBrowserOptions());report.browser=browser.version();const page=await browser.newPage({viewport:{width:1600,height:1050}});page.setDefaultTimeout(120000);page.on('pageerror',e=>report.errors.push(e.message));await page.goto(url+'/?atlas=1&sheet=M021&asset=built-187&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready,null,{timeout:120000});
 report.webgl=await page.evaluate(()=>{const gl=(document.querySelector('#viewport canvas') as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return gl.getParameter(ext?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);});
 const sync=async(v:number)=>{const t=performance.now();await page.waitForFunction(n=>(window as any).voxelStudio.performance.renderedVersion===n,v,{timeout:120000});report.uiSync.push({version:v,ms:performance.now()-t});};
 const before=await state(),roles=before.styles.yunshan,check=await call('check_geometry');clean(check);assert.equal(check.collisionGrids.length,12);report.gallery=check;
 for(const [assetId,point,role]of[
  ['built-186',[.4,.15,.03],'metalBright'],['built-187',[.5,.07,.03],'rotorBlade'],['built-188',[.1,.03,.1],'landingPadRubber'],
  ['built-189',[.1,.05,.5],'aircraftSkin'],['built-189',[.09,.5,.5],'glass'],['built-190',[.6,.15,.8],'glass'],
  ['built-191',[2.1,.01,1],'aircraftSkin'],['built-192',[.19,1.5,1.5],'aircraftSkin'],['built-193',[1,.01,.5],'aircraftSkin'],['built-194',[.61,.5,.3],'aircraftSkin'],
  ['built-195',[.26,.175,1.17],'displayGlyph'],['built-205',[4,.45,4],'pavementConcrete'],['built-206',[4,1.1,-.05],'metal'],
 ] as [string,V3,string][]){const a=before.assets[assetId],v=point.map(n=>Math.floor((n+1e-8)/a.cellSize)),r=await call('query_voxels',{assetId,region:{min:v,max:v.map(n=>n+1)}});assert.equal(r.cells[0]?.[1],roles[role]);}
 for(const x of[.07,.13,1.67,1.73]){const a=before.assets['built-189'],v=[x,.5,.5].map(n=>Math.floor((n+1e-8)/a.cellSize)),r=await call('query_voxels',{assetId:'built-189',region:{min:v,max:v.map(n=>n+1)}});assert.equal(r.total,0,'Both glass faces are clear of opaque seal cells');}
 report.checks.push('Twelve M021 masters verified from actual native coordinates: aircraft coating, golden metal blade, landing rubber, optical glass, control pixels and bridge layers');
 const changed=['aircraftSkin','rotorBlade','landingPadRubber','glass'],request={expectedVersion:before.version,requestId:crypto.randomUUID(),label:'M021航空独立外观包验证',commands:[{op:'definePalette',name:'航空独立材质',materials:Object.fromEntries(changed.map((r,i)=>[roles[r],{color:['#703943','#33806b','#455456','#85abb6'][i]}]))},{op:'palette',name:'航空独立材质'}]};
 const dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(before));const applied=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(applied.version);const after=await state();assert.equal(applied.modifiedVoxels,0);for(const k of['assets','styles']as const)assert.equal(hash(after[k]),hash(before[k]));
 for(const[id,m]of Object.entries(before.materials)){assert.equal(after.materials[id].solid,m.solid);assert.equal(after.materials[id].category,m.category);if(!changed.some(r=>String(roles[r])===id))assert.deepEqual(after.materials[id],m);}assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(after.materials));
 await page.locator('#material-category-filter').selectOption('rubber');const buttons=await page.locator('[data-material]').evaluateAll(nodes=>nodes.map(n=>Number((n as HTMLElement).dataset.material)));assert.ok(buttons.includes(roles.landingPadRubber));for(const id of buttons)assert.equal(after.materials[id].category,'rubber');await page.locator('[data-material="'+roles.landingPadRubber+'"]').click();assert.match(await page.locator('#material-role').innerText(),/yunshan.landingPadRubber/);await page.screenshot({path:path.join(out,'mcp-aerial-roles.png')});
 assert.equal((await call('edit_transaction',request)).version,applied.version);assert.equal((await raw('edit_transaction',{...request,requestId:crypto.randomUUID()})).code,'VERSION_CONFLICT');const failed=await raw('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:roles.landingPadRubber,properties:{color:'#ff00ff'}},{op:'produceCatalogAsset',catalogId:'BUILT-191',id:'bad',params:{depth:8}}]});assert.ok(failed.isError);assert.equal(hash(await state()),hash(after));
 const undo=await call('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(undo.version);for(const k of['assets','styles','materials','palettes']as const)assert.equal(hash((await state())[k]),hash(before[k]));await page.screenshot({path:path.join(out,'mcp-aerial-roles-restored.png')});report.checks.push('Four independent aircraft appearance roles, canonical UI hashes, rubber filtering, dry run, version conflicts, idempotency, failure rollback and one undo all verified');
 const scenario=async(name:string,commands:Command[],clearances:{name:string;min:V3;max:V3}[],unsupported:string[]=[],nearPairs:string[][]=[])=>{
  const loaded=await call('load_project',{filename:'empty.ysvox.json',expectedVersion:(await state()).version});await sync(loaded.version);const request={expectedVersion:loaded.version,requestId:crypto.randomUUID(),commands},initial=await state(),dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(initial));const built=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(built.version);await page.evaluate(()=>(window as any).voxelStudio.mode('scene'));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const geometry=await call('check_geometry',{clearances});clean(geometry,unsupported,nearPairs);const doc=await state();assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets)),hash(doc.assets));await page.screenshot({path:path.join(out,'mcp-'+name+'.png')});
  const saved=await call('save_project',{filename:name+'.ysvox.json'});await copyFile(saved.path,path.join(out,name+'.ysvox.json'));const exported=await call('export_project',{name}),round=JSON.parse(await readFile(path.join(exported.directory,'voxels.ysvox.json'),'utf8'));for(const k of['assets','instances','materials','styles']as const)assert.equal(hash(round[k]),hash(doc[k]));await cp(exported.directory,path.join(out,name+'-export'),{recursive:true});
  const previews=await call('generate_previews',{appearance:'baseColor',views:['isometric','front']});assert.equal(previews.files.length,2);for(let i=0;i<2;i++){assert.ok((await readFile(previews.files[i])).length>1000);await copyFile(previews.files[i],path.join(out,name+'-view-'+i+'.png'));}report.assemblies.push({name,masters:Object.keys(doc.assets).length,placements:Object.keys(doc.instances).length,geometry,expectedUnsupported:unsupported,expectedNearPairs:nearPairs,exported,previews});return doc;
 };
 await page.locator('#material-category-filter').selectOption('all');
 const quad=await scenario('aerial-quad',assembly.aerialQuadCommands(roles),assembly.aerialQuadClearances);assert.equal(Object.keys(quad.instances).length,13);report.checks.push('Four arm, blade and landing-leg copies dock with real vertical contact to a clearly auxiliary test block; only three catalogue masters, no flight or rotor-sweep claim');
 const cockpit=await scenario('aerial-cockpit',assembly.aerialCockpitCommands(roles),assembly.aerialCockpitClearances);assert.deepEqual(cockpit.instances['roof-1'].position,[0,1.4,0]);report.checks.push('Two independent 0.2x1.2x2m windows and separate roof preserve a clear authored Y1.1m eye line above the 0.4m installed console; unavailable original vehicle state remains explicit');
 await scenario('aerial-wing',assembly.aerialWingCommands(roles),assembly.aerialWingClearances);report.checks.push('Full 8.4m main wing docks to its root saddle without filling the native wing cavity');
 await scenario('aerial-tail',assembly.aerialTailCommands(),assembly.aerialTailClearances);report.checks.push('4m horizontal tail, 1.8m fin and authored power box align with clear intake openings; no flight dynamics claim');
 const bridge=await scenario('aerial-bridge',assembly.aerialBridgeCommands(),assembly.aerialBridgeClearances,assembly.aerialBridgeUnsupported,assembly.aerialBridgeNearPairs);assert.equal(Object.keys(bridge.instances).length,17);assert.equal(new Set(Object.values(bridge.assets).map(a=>a.source?.catalogId)).size,2);report.checks.push('Six decks, five joints and six beams use two catalogue families at exact 254.6/254/252.8m datums; terrain support and ten non-mating proximity notices remain explicit, original-game negative history retained');
 const glb=await new NodeIO().registerExtensions([KHRMaterialsEmissiveStrength]).read(path.join(out,'aerial-bridge-export','visual.glb')),node=glb.getRoot().listNodes().find(n=>n.getExtras().instanceId==='deck-0')!;assert.ok(node);assert.deepEqual(node.getTranslation(),[0,254,0]);const positions=node.getMesh()!.listPrimitives().flatMap(p=>Array.from(p.getAttribute('POSITION')!.getArray()!).filter((_,i)=>i%3===1)),top=Math.max(...positions)+node.getTranslation()[1];assert.ok(Math.abs(top-254.6)<1e-6);report.highBridgeGLB={deck0Translation:node.getTranslation(),worldTopYM:top};
 // Use the actual UI toggle in scene mode, on both rendering paths. No crop or model substitute.
 const canvas=page.locator('#viewport canvas'),clipChecks=[];
 for(const clay of[true,false]){
  await page.evaluate(v=>(window as any).voxelStudio.clay(v),clay);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const capture=async(label:string)=>{const file=path.join(out,`high-bridge-${clay?'base':'material'}-${label}.png`);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const data=await canvas.evaluate(node=>(node as HTMLCanvasElement).toDataURL('image/png'));await writeFile(file,Buffer.from(data.split(',')[1],'base64'));return{file,sha256:createHash('sha256').update(await readFile(file)).digest('hex')};};
  const off=await capture('off');await page.locator('#clip').click();await page.locator('#clip-height').fill('254.2');const sliced=await capture('slice');await page.locator('#clip-height').fill('100');const legacy=await capture('legacy-100');await page.locator('#clip').click();const restored=await capture('restored');
  assert.notEqual(off.sha256,sliced.sha256);assert.notEqual(off.sha256,legacy.sha256);assert.equal(off.sha256,restored.sha256);clipChecks.push({clay,off,sliced,legacy,restored,exactRestore:true});
 }
 report.clipping=clipChecks;report.checks.push('Real UI clipping at 254.2m and former 100m limit changes both base and material pixels; disabled clipping restores the identical high-bridge framebuffer and exports retain world Y254.6');
 report.checks.push('All five scenarios save real stdio MCP multiview previews plus GLB/native/collision/interface/material-atlas exports');
 const last=await call('save_project',{filename:'verified-aerial-bridge.ysvox.json'}),saved=await state();assert.equal(hash(JSON.parse(await readFile(last.path,'utf8'))),hash(saved));await stop();await start();assert.equal(hash(await state()),hash(saved));report.checks.push('Native save and server restart restore the exact canonical document');
 assert.deepEqual(report.errors,[]);report.status='passed';report.completedAt=new Date().toISOString();console.log(JSON.stringify({status:report.status,checks:report.checks.length,out}));
}catch(error){report.status='failed';report.errors.push(String(error));throw error;}finally{await browser?.close();await client?.close();await stop();await writeFile(path.join(out,'aerial-mcp-verification.json'),JSON.stringify(report,null,2));await writeFile(path.join(out,'aerial-mcp-server.log'),log);}
