import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import path from 'node:path';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {chromium} from 'playwright';
import {validationBrowserOptions} from './browser-options';
import {productionProject} from '../src/production/style';
import {parseCatalogCSV} from '../src/core/catalog';
import {referenceFinishCommands} from '../src/production/reference-finish';
import {outfitHash as rawHash} from '../src/production/outfit-components';
import {livingAudit} from './lib/living-audit';
import {Grid} from '../src/core/grid';
import type {Project} from '../src/core/types';
const hash=(value:unknown)=>rawHash(value??null);
const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),verification=JSON.parse(await readFile(latest.evidence+'/assembly-verification.json','utf8')),out=latest.evidence,runtime=path.join(out,'living-mcp-runtime'),url='http://127.0.0.1:4400',rows=latest.models;assert.equal(rows.length,6);
await mkdir(runtime,{recursive:true});for(const file of['atlas-production-index.json','production-index.json','architecture-index.json','material-index.json',...rows.map((r:any)=>r.file)])await copyFile('projects/'+file,runtime+'/'+file);await cp('projects/reference-atlas',runtime+'/reference-atlas',{recursive:true});await copyFile('projects/'+rows[0].file,runtime+'/autosave.ysvox.json');
for(const v of verification.variants){v.runtimeFile='variant-'+v.id+'-'+Object.values(v.params).join('-')+'.ysvox.json';await copyFile(v.file,runtime+'/'+v.runtimeFile);}
const empty=productionProject('M059 MCP character and animal assemblies');empty.catalog={sourceName:'catalog',importedAt:latest.createdAt,entries:Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]))};await writeFile(runtime+'/empty.ysvox.json',JSON.stringify(empty));
let server:ChildProcess|undefined,client:Client|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,log='';const report:any={run:latest.run,status:'running',checks:[],errors:[],views:[],notifications:[]},state=async():Promise<Project>=>(await fetch(url+'/api/state').then(r=>r.json())).project;
async function start(){server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4400',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok)return;}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}throw new Error('startup timeout');}
async function stop(){if(server&&server.exitCode===null){const closed=once(server,'exit');server.kill();await closed;}}
try{
 await start();client=new Client({name:'living-assemblies-verification',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],cwd:process.cwd(),env:{...process.env as Record<string,string>,VOXEL_URL:url},stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const r:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(name,r.isError?'ERROR':'OK');return{...JSON.parse(r.content[0].text),isError:!!r.isError};},call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 browser=await chromium.launch(validationBrowserOptions());report.browser=browser.version();const page=await browser.newPage({viewport:{width:1400,height:1000}});page.setDefaultTimeout(120000);page.on('pageerror',e=>report.errors.push(e.message));page.on('websocket',socket=>socket.on('framereceived',f=>{const n=JSON.parse(f.payload.toString());report.notifications.push({event:n.event,version:n.version,bytes:Buffer.byteLength(f.payload.toString()),fullProject:!!n.project});}));await page.goto(url+'/?atlas=1&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready);
 const sync=async(v:number)=>page.waitForFunction(n=>(window as any).voxelStudio.performance.renderedVersion===n,v),frames=async()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))),edit=async(commands:any[])=>{const req={expectedVersion:(await state()).version,requestId:crypto.randomUUID(),commands},dry=await call('edit_transaction',{...req,dryRun:true}),result=await call('edit_transaction',{...req,previewToken:dry.previewToken});await sync(result.version);return result;},load=async(file:string)=>{const r=await call('load_project',{filename:file,expectedVersion:(await state()).version});await sync(r.version);return state();};
 const capture=async(key:string,view='isometric')=>{await page.evaluate(async view=>{const v=(window as any).voxelStudio;await v.mode('scene');v.view(view);v.clip(Infinity);v.clay(false);v.studio(true);v.ao(false);v.bloom(false);},view);await frames();await page.locator('#viewport').screenshot({path:out+'/assembly-'+key+'.png'});const perf=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.equal(perf.meshError,null);report.views.push({key,file:'assembly-'+key+'.png',triangles:perf.triangles});};
 report.webgl=await page.evaluate(()=>{const g=(document.querySelector('#viewport canvas')as HTMLCanvasElement).getContext('webgl2')!,ext=g.getExtension('WEBGL_debug_renderer_info');return g.getParameter(ext?.UNMASKED_RENDERER_WEBGL??g.RENDERER);});
 const lib=await call('read_production_library',{query:'CHAR-332'});assert.equal(lib.counts.atlasReferenceCandidates,702);assert.equal(lib.counts.atlasAssemblyCandidates,186);assert.equal(lib.counts.baseModels,532);const recipes=await call('list_production_recipes',{query:'CHAR-176',limit:100});assert.deepEqual(recipes.entries.find((r:any)=>r.id==='CHAR-176').parameters.view.enum,['observer','first-person-open','first-person-grip']);report.libraryCounts=lib.counts;await writeFile('docs/tool-schemas.json',JSON.stringify((await client.listTools()).tools,null,2));report.checks.push('Actual MCP exposes702 reference candidates and186 assemblies;6 building variants remain unproduced, base count unchanged532. Public finite player view choices match the saved recipes.');
 await page.locator('#atlas-sheet').selectOption('M059');await page.locator('[data-atlas-open][data-catalog="CHAR-174"]').first().click();await page.waitForFunction(()=>Object.values((window as any).voxelStudio.project.assemblies??{}).some((a:any)=>a.source?.catalogId==='CHAR-174'));await sync((await state()).version);report.checks.push('Actual atlas button opens the patient with real124 pajamas, preserved145 and fitted bandage components.');
 for(const row of rows){await load(row.file);await edit([...referenceFinishCommands(await state()),{op:'palette',name:'参考材质试作'}]);await capture(row.id+'-back','back');if(row.id==='CHAR-174')await capture(row.id+'-side','right');}
 for(const v of verification.variants){await load(v.runtimeFile);await edit([...referenceFinishCommands(await state()),{op:'palette',name:'参考材质试作'}]);await capture(v.id+'-'+Object.values(v.params).join('-'));}
 report.checks.push('Six actual default back views, patient side and all six nondefault finite forms captured through public project loading.');
 await load('empty.ysvox.json');const before=await state(),request={expectedVersion:before.version,requestId:crypto.randomUUID(),commands:[{op:'produceCatalogAssembly',catalogId:'CHAR-332',id:'pets',place:true,params:{wear:'harnesses'}}]},dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(before));const made=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(made.version);assert.equal((await call('edit_transaction',request)).version,made.version);assert.equal((await raw('edit_transaction',{...request,requestId:crypto.randomUUID()})).code,'VERSION_CONFLICT');const pets=await state(),audit=livingAudit(pets,pets.assemblies!.pets);assert.ok(audit.contactsPassed&&audit.groundPassed&&audit.pairs.every(r=>!r.contained&&!r.crossing));assert.equal(audit.contacts.length,5);report.publicPets=audit;
 const failed=await raw('edit_transaction',{expectedVersion:pets.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:pets.styles.yunshan.petWebbing,properties:{color:'#ff0000'}},{op:'produceCatalogAssembly',catalogId:'CHAR-332',id:'bad',params:{wear:'rabbit-harness'}}]});assert.ok(failed.isError);assert.equal(hash(await state()),hash(pets));assert.ok((await raw('edit_transaction',{expectedVersion:pets.version,requestId:crypto.randomUUID(),commands:[{op:'produceCatalogAsset',catalogId:'CHAR-332',id:'wrong-type'}]})).isError);assert.equal(hash(await state()),hash(pets));await capture('pets-public-create');report.checks.push('Actual public pets creation validates dry-run, CAS, idempotency and five body-liner contacts. Unsupported rabbit harness and wrong base-asset kind roll back without partial edits.');
 await edit([{op:'instantiateAssembly',assemblyId:'pets',prefix:'quarter',position:[2,0,2],rotation:1}]);const placed=await state();assert.equal(Object.keys(placed.instances).length,12);await capture('pets-quarter-turn');const exported=await call('export_project',{name:'living-quarter-turn-'+Date.now()}),native=JSON.parse(await readFile(exported.directory+'/voxels.ysvox.json','utf8'));for(const k of['assets','instances','assemblies','styles']as const)assert.equal(hash(native[k]),hash(placed[k]));report.export=exported;await edit([{op:'undo'}]);assert.equal(hash((await state()).instances),hash(pets.instances));await edit([{op:'undo'}]);for(const k of['assets','instances','assemblies','materials']as const)assert.equal(hash((await state())[k]),hash(before[k]));report.checks.push('Public assembly quarter-turn exports exact native definitions; placement and creation each undo as one transaction.');
 const patient=await load(rows.find((r:any)=>r.id==='CHAR-174').file),wrap=Object.values(patient.instances).map(i=>patient.assets[i.assetId]).find(a=>(a.source?.retainedAuthorSource as any)?.kind==='author-patient-wrap-fit')!,cell=[...new Grid(wrap.chunks).cells()][0][0],query=await call('query_voxels',{assetId:wrap.id,region:{min:cell,max:cell.map(v=>v+1)}});assert.equal(query.cells[0][1],patient.styles.yunshan.garmentBuckle);
 await edit([{op:'definePalette',name:'M059病衣绷带用途',materials:{[patient.styles.yunshan.sleepCloth]:{color:'#76a1b2'},[patient.styles.yunshan.bandageCloth]:{color:'#dbbd95'},[patient.styles.yunshan.garmentStrap]:{color:'#956684'}}},{op:'palette',name:'M059病衣绷带用途'}]);const changed=await state();for(const k of['assets','instances','assemblies','styles']as const)assert.equal(hash(changed[k]),hash(patient[k]));await capture('patient-purpose-palette');await edit([{op:'undo'}]);assert.equal(hash((await state()).materials),hash(patient.materials));report.checks.push('Actual native clamp query and independent pajama/bandage/support-strap purpose palette change preserve geometry and all ten contacts; one undo restores materials.');
 const petDoc=await load(rows.find((r:any)=>r.id==='CHAR-332').file);await edit([{op:'definePalette',name:'M059宠物穿戴用途',materials:{[petDoc.styles.yunshan.petWebbing]:{color:'#ad748c'},[petDoc.styles.yunshan.harnessLiner]:{color:'#739b92'},[petDoc.styles.yunshan.petHardware]:{color:'#c4b77a'}}},{op:'palette',name:'M059宠物穿戴用途'}]);for(const k of['assets','instances','assemblies','styles']as const)assert.equal(hash((await state())[k]),hash(petDoc[k]));await capture('pets-purpose-palette');await edit([{op:'undo'}]);assert.equal(hash((await state()).materials),hash(petDoc.materials));report.checks.push('Woven strap, soft liner and metal hardware can change independently on real collar geometry; source bodies and native detail remain unchanged.');
 const authority=hash(await state());report.details=[];for(const mode of['far','near']){await page.evaluate(async mode=>(window as any).voxelStudio.meshMode(mode),mode);await frames();const perf=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.equal(perf.meshMode,mode);report.details.push({mode,triangles:perf.triangles});}assert.equal(hash(await state()),authority);report.checks.push('Actual renderer near/far modes preserve all original species and fitted wearable authority.');
 // Independently display the exported skinned GLBs from the actual first-person camera, without editor auto-framing.
 const html='<!doctype html><html><head><style>html,body{margin:0;background:#d9ddd7}canvas{display:block}</style></head><body><script type="module">import * as THREE from "/node_modules/three/build/three.module.js";import {GLTFLoader} from "/node_modules/three/examples/jsm/loaders/GLTFLoader.js";const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(1280,720);renderer.setPixelRatio(1);document.body.appendChild(renderer.domElement);const scene=new THREE.Scene();scene.background=new THREE.Color("#d9ddd7");scene.add(new THREE.HemisphereLight(0xffffff,0x687466,2.1));const sun=new THREE.DirectionalLight(0xffffff,2.2);sun.position.set(-1,3,-1);scene.add(sun);const camera=new THREE.PerspectiveCamera(70,16/9,.05,50);camera.position.set(0,0,0);camera.lookAt(0,0,-1);let model;window.showView=async(data)=>{if(model)scene.remove(model);const bytes=Uint8Array.from(atob(data),c=>c.charCodeAt(0));model=(await new GLTFLoader().parseAsync(bytes.buffer,"")).scene;scene.add(model);scene.updateMatrixWorld(true);renderer.render(scene,camera);return{triangles:renderer.info.render.triangles,fov:camera.fov,aspect:camera.aspect,near:camera.near,position:camera.position.toArray()};};window.captureReady=true;</script></body></html>';
 const cameraModule=html.slice(html.indexOf('<script type="module">')+22,html.indexOf('</script>')).replace('/node_modules/three/build/three.module.js','three').replace('/node_modules/three/examples/jsm/loaders/GLTFLoader.js','three/examples/jsm/loaders/GLTFLoader.js');
 const bundled=await(await import('esbuild')).build({stdin:{contents:cameraModule,resolveDir:process.cwd(),sourcefile:'M059-camera-preview.js'},bundle:true,platform:'browser',format:'iife',write:false,minify:true}),cameraScript=bundled.outputFiles![0].text,blank='<!doctype html><html><head><style>html,body{margin:0;background:#d9ddd7}canvas{display:block}</style></head><body></body></html>';
 await writeFile(out+'/first-person-preview.html',blank.replace('</body>','<script>'+cameraScript+'</script></body>'));const cameraPage=await browser.newPage({viewport:{width:1280,height:720}});cameraPage.on('pageerror',e=>report.errors.push(e.message));await cameraPage.setContent(blank);await cameraPage.addScriptTag({content:cameraScript});await cameraPage.waitForFunction(()=>!!(window as any).captureReady);
 for(const r of verification.records.filter((r:any)=>r.living.view)){const key=r.id+'-'+Object.values(r.params).join('-')+'-camera',bytes=await readFile(r.directory+'/visual-material.glb'),actual=await cameraPage.evaluate(async data=>(window as any).showView(data),bytes.toString('base64'));assert.equal(actual.fov,70);assert.ok(actual.triangles>0);await cameraPage.screenshot({path:out+'/assembly-'+key+'.png'});report.views.push({key,file:'assembly-'+key+'.png',...actual,actualExportedGLB:r.directory+'/visual-material.glb',fixedAuthorCamera:true});}await cameraPage.close();report.checks.push('Four actual exported skinned GLBs rendered from fixed70-degree first-person camera at16:9 and5cm near plane. Both empty-hand poses and shared NPC sleeve appearances inspected without auto-framing.');
 const doc=await state(),saved=await call('save_project',{filename:'verified-assembly.ysvox.json'});assert.equal(hash(JSON.parse(await readFile(saved.path,'utf8'))),hash(doc));await stop();await start();assert.equal(hash(await state()),hash(doc));report.checks.push('Native save and real server restart preserve exact definitions, components, materials and fitting provenance.');assert.ok(report.notifications.length>=10);assert.ok(report.notifications.every((n:any)=>n.event==='state-invalidated'&&!n.fullProject&&n.bytes<65536));assert.deepEqual(report.errors,[]);report.status='passed';console.log(JSON.stringify({status:report.status,checks:report.checks.length,views:report.views.length}));
}catch(e){report.status='failed';report.errors.push(String(e));throw e;}finally{await browser?.close();await client?.close();await stop();await writeFile(out+'/assembly-mcp-verification.json',JSON.stringify(report,null,2));await writeFile(out+'/assembly-mcp-server.txt',log);}
