import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {validationBrowserOptions} from './browser-options';
import {parseCatalogCSV} from '../src/core/catalog';
import {productionProject} from '../src/production/style';
import * as assembly from '../src/production/transport-assembly';
import type {Command,Project,V3} from '../src/core/types';

const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),out=latest.evidence,runtime=path.join(out,'transport-mcp-runtime'),url='http://127.0.0.1:4353',gallery=index.studies.find((s:any)=>s.id==='M018-gallery');assert.ok(gallery);
await mkdir(runtime,{recursive:true});for(const f of['atlas-production-index.json','production-index.json',gallery.file,...index.entries.filter((e:any)=>e.sheet==='M018').map((e:any)=>e.file)])await copyFile(path.join('projects',f),path.join(runtime,f));
await cp('projects/reference-atlas',path.join(runtime,'reference-atlas'),{recursive:true});await copyFile(path.join(runtime,gallery.file),path.join(runtime,'autosave.ysvox.json'));
const empty=productionProject('M018 · 真实 MCP 拼装');empty.catalog={sourceName:'city-assets.csv',importedAt:'verification',entries:Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]))};await writeFile(path.join(runtime,'empty.ysvox.json'),JSON.stringify(empty));
const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),state=async():Promise<Project>=>(await fetch(url+'/api/state').then(r=>r.json())).project;
const report:any={run:index.run,startedAt:new Date().toISOString(),status:'running',checks:[],errors:[],uiSync:[],assemblies:[]};let server:ChildProcess|undefined,client:Client|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,log='';
async function start(){server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4353',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok)return;}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}throw new Error('Server startup timeout');}
async function stop(){if(server&&server.exitCode===null){const closed=once(server,'exit');server.kill('SIGTERM');await closed;}}
function clean(c:any,unsupported:string[]=[]){assert.deepEqual(c.unsupported,unsupported);for(const k of['collisions','gaps','warnings'])assert.deepEqual(c[k],[],k);assert.ok(c.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));assert.ok(c.clearances.every((o:any)=>o.clear));}
try{
 await start();client=new Client({name:'transport-semantic-validation',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],env:{...process.env as Record<string,string>,VOXEL_URL:url},cwd:process.cwd(),stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const t=performance.now(),r:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(JSON.stringify({tool:name,ms:performance.now()-t,error:!!r.isError}));return{...JSON.parse(r.content[0].text),isError:!!r.isError};};
 const call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 browser=await chromium.launch(validationBrowserOptions());report.browser=browser.version();const page=await browser.newPage({viewport:{width:1600,height:1050}});page.setDefaultTimeout(120000);page.on('pageerror',e=>report.errors.push(e.message));await page.goto(url+'/?atlas=1&sheet=M018&asset=built-138&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready,null,{timeout:120000});
 report.webgl=await page.evaluate(()=>{const gl=(document.querySelector('#viewport canvas') as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return gl.getParameter(ext?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);});if(process.argv.includes('--metal'))assert.match(report.webgl,/Metal Renderer/);
 const sync=async(v:number)=>{const t=performance.now();await page.waitForFunction(n=>(window as any).voxelStudio.performance.renderedVersion===n,v,{timeout:120000});report.uiSync.push({version:v,ms:performance.now()-t});};
 const before=await state(),roles=before.styles.yunshan,check=await call('check_geometry');clean(check);assert.equal(check.collisionGrids.length,12);report.gallery=check;
 for(const [assetId,v,role]of [
  ['built-116',[50,50,1],'printedRed'],['built-117',[50,5,1],'glass'],['built-117',[50,5,6],'energy'],['built-117',[230,50,6],'warm'],
  ['built-131',[50,23,25],'pavementConcrete'],['built-131',[50,21,25],'structuralConcrete'],
  ['built-132',[1,3,10],'roadInlay'],['built-132',[1,0,10],'jointSeal'],['built-133',[50,2,2],'jointSeal'],
  ['built-138',[15,17,15],'bridgeBearing'],['built-139',[10,2,2],'wood'],
 ] as const){const r=await call('query_voxels',{assetId,region:{min:v,max:v.map(n=>n+1)}});assert.equal(r.cells[0]?.[1],roles[role]);}
 assert.equal(before.materials[roles.roadInlay].category,'ceramic');assert.equal(before.materials[roles.bridgeBearing].category,'rubber');report.checks.push('Twelve M018 native masters with actual medical ink, lamp, glass, concrete, ceramic inlay, seal and bearing cells verified through stdio MCP');
 const changed=['pavementConcrete','roadInlay','bridgeBearing','jointSeal'],request={expectedVersion:before.version,requestId:crypto.randomUUID(),label:'M018独立材质包验证',commands:[{op:'definePalette',name:'交通组件独立材质',materials:Object.fromEntries(changed.map((r,i)=>[roles[r],{color:['#70bd94','#745ce0','#798399','#943a3a'][i]}]))},{op:'palette',name:'交通组件独立材质'}]};
 const dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(before));const applied=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(applied.version);const after=await state();assert.equal(applied.modifiedVoxels,0);for(const k of['assets','styles']as const)assert.equal(hash(after[k]),hash(before[k]));
 for(const[id,m]of Object.entries(before.materials)){assert.equal(after.materials[id].solid,m.solid);assert.equal(after.materials[id].category,m.category);if(!changed.some(r=>String(roles[r])===id))assert.deepEqual(after.materials[id],m);}assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(after.materials));
 await page.locator('#material-category-filter').selectOption('rubber');const buttons=await page.locator('[data-material]').evaluateAll(nodes=>nodes.map(n=>Number((n as HTMLElement).dataset.material)));assert.ok(buttons.includes(roles.bridgeBearing));for(const id of buttons)assert.equal(after.materials[id].category,'rubber');await page.locator('[data-material="'+roles.bridgeBearing+'"]').click();assert.match(await page.locator('#material-role').innerText(),/yunshan.bridgeBearing/);await page.screenshot({path:path.join(out,'mcp-transport-roles.png')});
 assert.equal((await call('edit_transaction',request)).version,applied.version);assert.equal((await raw('edit_transaction',{...request,requestId:crypto.randomUUID()})).code,'VERSION_CONFLICT');const failed=await raw('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:roles.bridgeBearing,properties:{color:'#ff00ff'}},{op:'produceCatalogAsset',catalogId:'BUILT-999',id:'bad'}]});assert.ok(failed.isError);assert.equal(hash(await state()),hash(after));
 const undo=await call('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(undo.version);for(const k of['assets','styles','materials','palettes']as const)assert.equal(hash((await state())[k]),hash(before[k]));await page.screenshot({path:path.join(out,'mcp-transport-roles-restored.png')});report.checks.push('Pavement/inlay/bearing/joint appearance changes exactly four roles, no geometry or collision, with matching canonical UI hashes, rubber filtering, dry-run, idempotency, version conflict, failure rollback and one undo');
 const scenario=async(name:string,commands:Command[],clearances:{name:string;min:V3;max:V3}[])=>{
  const loaded=await call('load_project',{filename:'empty.ysvox.json',expectedVersion:(await state()).version});await sync(loaded.version);const request={expectedVersion:loaded.version,requestId:crypto.randomUUID(),commands},initial=await state(),dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(initial));const built=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(built.version);await page.evaluate(()=>(window as any).voxelStudio.mode('scene'));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const geometry=await call('check_geometry',{clearances});clean(geometry);const doc=await state();assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets)),hash(doc.assets));await page.screenshot({path:path.join(out,'mcp-'+name+'.png')});
  const saved=await call('save_project',{filename:name+'.ysvox.json'});await copyFile(saved.path,path.join(out,name+'.ysvox.json'));const exported=await call('export_project',{name}),round=JSON.parse(await readFile(path.join(exported.directory,'voxels.ysvox.json'),'utf8'));for(const k of['assets','instances','materials','styles']as const)assert.equal(hash(round[k]),hash(doc[k]));await cp(exported.directory,path.join(out,name+'-export'),{recursive:true});
  const previews=await call('generate_previews',{appearance:'baseColor',views:['isometric','front']});assert.equal(previews.files.length,2);for(let i=0;i<2;i++){assert.ok((await readFile(previews.files[i])).length>1000);await copyFile(previews.files[i],path.join(out,name+'-view-'+i+'.png'));}report.assemblies.push({name,masters:Object.keys(doc.assets).length,placements:Object.keys(doc.instances).length,geometry,exported,previews});return doc;
 };
 await page.locator('#material-category-filter').selectOption('all');
 const assembled=await scenario('transport-road',assembly.transportRoadCommands(),assembly.transportRoadClearances);assert.equal(Object.keys(assembled.assets).length,4);assert.equal(Object.keys(assembled.instances).length,4);assert.deepEqual(assembled.instances['curbs-1'].position,[.05,.5,0]);report.checks.push('10m road, 0.16m centre inlay, 7m joint and two 0.4m curbs: four masters, no collision, clear drainage and travel space on shared 10mm grid');
 const wrong=await raw('edit_transaction',{expectedVersion:assembled.version,requestId:crypto.randomUUID(),commands:[{op:'createAsset',id:'fine',name:'10mm incompatible',template:'empty',cellSize:.01},{op:'metadata',assetId:'fine',ports:[{id:'p',kind:'road-line',position:[.08,0,1],normal:[0,-1,0],size:[.16,0,2],pitch:.01}]},{op:'connect',id:'bad',assetId:'fine',portId:'p',targetInstanceId:'road-1',targetPortId:'line',rotation:0}]});assert.ok(wrong.isError);assert.match(JSON.stringify(wrong),/格距/);assert.equal(hash(await state()),hash(assembled));report.checks.push('10/20mm direct docking mismatch rejected with complete transaction rollback');
 const viaduct=await scenario('transport-viaduct',assembly.transportViaductCommands(),[]);assert.deepEqual(viaduct.instances['bed-1'].position,[.5,35.8,-.5]);report.checks.push('7m foundation, 3m by 32m pier, 7m by 1.8m cap and 6m by 1.4m bed dock through all four true bearing interfaces');
 const tie=await scenario('transport-tie',assembly.transportTieCommands(),[]);assert.equal(Object.keys(tie.assets).length,3);assert.equal(Object.keys(tie.instances).length,5);report.checks.push('Two reused high piers support one timber tie at shaft level 16m; repeated instances do not inflate master counts');
 const fixtures=await scenario('transport-fixtures',assembly.transportFixtureCommands(roles),assembly.transportFixtureClearances);assert.equal(Object.values(fixtures.assets).filter(a=>a.source?.catalogId).length,2);report.checks.push('Medical sign and 1.1m-centre-height rails mounted to explicit auxiliary fixtures; 2m intersection cut remains open; fixtures are not catalogue masters');
 report.checks.push('All four scenarios save genuine MCP multi-view previews and GLB/native/collision/interface/material-atlas exports');
 const last=await call('save_project',{filename:'verified-transport-fixtures.ysvox.json'}),saved=await state();assert.equal(hash(JSON.parse(await readFile(last.path,'utf8'))),hash(saved));await stop();await start();assert.equal(hash(await state()),hash(saved));report.checks.push('Native save and server restart restore the exact canonical document');
 assert.deepEqual(report.errors,[]);report.status='passed';report.completedAt=new Date().toISOString();console.log(JSON.stringify({status:report.status,checks:report.checks.length,out}));
}catch(error){report.status='failed';report.errors.push(String(error));throw error;}finally{await browser?.close();await client?.close();await stop();await writeFile(path.join(out,'transport-mcp-verification.json'),JSON.stringify(report,null,2));await writeFile(path.join(out,'transport-mcp-server.log'),log);}
