import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {validationBrowserOptions} from './browser-options';
import {parseCatalogCSV} from '../src/core/catalog';
import {productionProject} from '../src/production/style';
import {exteriorAssemblyCommands,exteriorClearances} from '../src/production/exterior-assembly';
import type {Command,Project,V3} from '../src/core/types';

const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),out=latest.evidence,runtime=path.join(out,'exterior-mcp-runtime'),url='http://127.0.0.1:4351',gallery=index.studies.find((s:any)=>s.id==='M016-gallery');assert.ok(gallery);
await mkdir(runtime,{recursive:true});for(const f of['atlas-production-index.json','production-index.json',gallery.file,...index.entries.filter((e:any)=>e.sheet==='M016').map((e:any)=>e.file)])await copyFile(path.join('projects',f),path.join(runtime,f));
await cp('projects/reference-atlas',path.join(runtime,'reference-atlas'),{recursive:true});await copyFile(path.join(runtime,gallery.file),path.join(runtime,'autosave.ysvox.json'));
const empty=productionProject('M016 · 真实 MCP 拼装');empty.catalog={sourceName:'city-assets.csv',importedAt:'verification',entries:Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]))};await writeFile(path.join(runtime,'empty.ysvox.json'),JSON.stringify(empty));
const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),state=async():Promise<Project>=>(await fetch(url+'/api/state').then(r=>r.json())).project;
const report:any={run:index.run,startedAt:new Date().toISOString(),status:'running',checks:[],errors:[],uiSync:[],assemblies:[]};let server:ChildProcess|undefined,client:Client|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,log='';
async function start(){server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4351',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok)return;}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}throw new Error('Server startup timeout');}
async function stop(){if(server&&server.exitCode===null){const closed=once(server,'exit');server.kill('SIGTERM');await closed;}}
function clean(c:any,unsupported:string[]=[]){assert.deepEqual(c.unsupported,unsupported);for(const k of['collisions','gaps','warnings'])assert.deepEqual(c[k],[],k);assert.ok(c.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));assert.ok(c.clearances.every((o:any)=>o.clear));}
try{
 await start();client=new Client({name:'exterior-semantic-validation',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],env:{...process.env as Record<string,string>,VOXEL_URL:url},cwd:process.cwd(),stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const t=performance.now(),r:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(JSON.stringify({tool:name,ms:performance.now()-t,error:!!r.isError}));return{...JSON.parse(r.content[0].text),isError:!!r.isError};};
 const call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 browser=await chromium.launch(validationBrowserOptions());report.browser=browser.version();const page=await browser.newPage({viewport:{width:1600,height:1050}});page.on('pageerror',e=>report.errors.push(e.message));await page.goto(url+'/?atlas=1&sheet=M016&asset=built-101&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready,null,{timeout:120000});
 report.webgl=await page.evaluate(()=>{const gl=(document.querySelector('#viewport canvas') as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return gl.getParameter(ext?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);});if(process.argv.includes('--metal'))assert.match(report.webgl,/Metal Renderer/);
 const sync=async(v:number)=>{const t=performance.now();await page.waitForFunction(n=>(window as any).voxelStudio.performance.renderedVersion===n,v,{timeout:120000});report.uiSync.push({version:v,ms:performance.now()-t});};
 const before=await state(),roles=before.styles.yunshan,check=await call('check_geometry');clean(check);assert.equal(check.collisionGrids.length,12);report.gallery=check;
 for(const [assetId,v,role]of [
  ['built-101',[6,6,3],'signDiffuser'],['built-101',[21,37,2],'printedDark'],['built-101',[10,10,7],'warm'],
  ['built-095',[50,200,50],'energyField'],['built-095',[40,200,36],'glass'],
  ['built-102',[3,42,15],'flueLiner'],['built-102',[1,42,15],'wall'],['built-102',[1,40,15],'mortar'],
 ] as const){const r=await call('query_voxels',{assetId,region:{min:v,max:v.map(n=>n+1)}});assert.equal(r.cells[0]?.[1],roles[role]);}
 assert.equal(before.materials[roles.signDiffuser].category,'plastic');assert.equal(before.materials[roles.energyField].solid,false);assert.equal(before.materials[roles.flueLiner].category,'ceramic');report.checks.push('Twelve M016 masters retain their 20/40/100/200mm grids; actual diffuser, ink, lamp core, glass, non-solid energy, ceramic flue, masonry and mortar cells are queried through MCP');
 const changed=['signDiffuser','energyField','flueLiner','printedDark'],request={expectedVersion:before.version,requestId:crypto.randomUUID(),label:'灯箱、能量区与陶质内衬独立材质包验证',commands:[{op:'definePalette',name:'外立面独立材质',materials:Object.fromEntries(changed.map((r,i)=>[roles[r],{color:['#70bd94','#745ce0','#798399','#943a3a'][i]}]))},{op:'palette',name:'外立面独立材质'}]};
 const dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(before));const applied=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(applied.version);const after=await state();assert.equal(applied.modifiedVoxels,0);for(const k of['assets','styles']as const)assert.equal(hash(after[k]),hash(before[k]));
 for(const[id,m]of Object.entries(before.materials)){assert.equal(after.materials[id].solid,m.solid);assert.equal(after.materials[id].category,m.category);if(!changed.some(r=>String(roles[r])===id))assert.deepEqual(after.materials[id],m);}assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(after.materials));
 await page.locator('#material-category-filter').selectOption('plastic');const buttons=await page.locator('[data-material]').evaluateAll(nodes=>nodes.map(n=>Number((n as HTMLElement).dataset.material)));assert.ok(buttons.includes(roles.signDiffuser));for(const id of buttons)assert.equal(after.materials[id].category,'plastic');await page.locator('[data-material="'+roles.signDiffuser+'"]').click();assert.match(await page.locator('#material-role').innerText(),/yunshan.signDiffuser/);await page.screenshot({path:path.join(out,'mcp-exterior-roles.png')});
 assert.equal((await call('edit_transaction',request)).version,applied.version);assert.equal((await raw('edit_transaction',{...request,requestId:crypto.randomUUID()})).code,'VERSION_CONFLICT');const failed=await raw('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:roles.signDiffuser,properties:{color:'#ff00ff'}},{op:'produceCatalogAsset',catalogId:'BUILT-999',id:'bad'}]});assert.ok(failed.isError);assert.equal(hash(await state()),hash(after));
 const undo=await call('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(undo.version);for(const k of['assets','styles','materials','palettes']as const)assert.equal(hash((await state())[k]),hash(before[k]));await page.screenshot({path:path.join(out,'mcp-exterior-roles-restored.png')});report.checks.push('Diffuser/energy/flue/ink appearance changes exactly four roles, no geometry or collision, with matching canonical UI hashes, plastic filtering, dry-run, idempotency, version conflict, failure rollback and one undo');
 const scenario=async(name:string,commands:Command[],clearances:{name:string;min:V3;max:V3}[])=>{
  const loaded=await call('load_project',{filename:'empty.ysvox.json',expectedVersion:(await state()).version});await sync(loaded.version);const request={expectedVersion:loaded.version,requestId:crypto.randomUUID(),commands},initial=await state(),dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(initial));const built=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(built.version);await page.evaluate(()=>(window as any).voxelStudio.mode('scene'));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const geometry=await call('check_geometry',{clearances});clean(geometry);const doc=await state();assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets)),hash(doc.assets));await page.screenshot({path:path.join(out,'mcp-'+name+'.png')});
  const saved=await call('save_project',{filename:name+'.ysvox.json'});await copyFile(saved.path,path.join(out,name+'.ysvox.json'));const exported=await call('export_project',{name}),round=JSON.parse(await readFile(path.join(exported.directory,'voxels.ysvox.json'),'utf8'));for(const k of['assets','instances','materials','styles']as const)assert.equal(hash(round[k]),hash(doc[k]));await cp(exported.directory,path.join(out,name+'-export'),{recursive:true});
  const previews=await call('generate_previews',{appearance:'baseColor',views:['isometric','front']});assert.equal(previews.files.length,2);for(let i=0;i<2;i++){assert.ok((await readFile(previews.files[i])).length>1000);await copyFile(previews.files[i],path.join(out,name+'-view-'+i+'.png'));}report.assemblies.push({name,masters:Object.keys(doc.assets).length,placements:Object.keys(doc.instances).length,geometry,exported,previews});return doc;
 };
 await page.locator('#material-category-filter').selectOption('all');
 const assembled=await scenario('exterior-assembly',exteriorAssemblyCommands(roles),exteriorClearances);assert.equal(Object.keys(assembled.assets).length,9);assert.equal(Object.keys(assembled.instances).length,13);assert.equal(Object.values(assembled.instances).filter(i=>i.assetId==='column').length,4);assert.equal(Object.values(assembled.instances).filter(i=>i.assetId==='apron').length,2);report.checks.push('Observation stairs, bracket-supported balcony with independent rail, two side platforms and double canopies with four instances of one column and hung sign form 13 placements from 9 masters, without collision, unsupported instance or blocked entrance');
 const wrong=await raw('edit_transaction',{expectedVersion:assembled.version,requestId:crypto.randomUUID(),commands:[{op:'createAsset',id:'fine',name:'20mm incompatible',template:'empty',cellSize:.02},{op:'metadata',assetId:'fine',ports:[{id:'p',kind:'shop-canopy-column',position:[0,0,0],normal:[0,1,0],size:[.4,0,.4],pitch:.02}]},{op:'connect',id:'bad',assetId:'fine',portId:'p',targetInstanceId:'canopies-1',targetPortId:'column-60',rotation:0}]});assert.ok(wrong.isError);assert.match(JSON.stringify(wrong),/格距/);assert.equal(hash(await state()),hash(assembled));report.checks.push('20/40mm incompatible docking rejects and rolls back the entire transaction without silently resampling');
 const corridor=await scenario('exterior-corridors',[{op:'produceCatalogAsset',catalogId:'BUILT-090',id:'corridor'},{op:'instance',id:'left',assetId:'corridor',position:[0,0,0]},{op:'connect',id:'right',assetId:'corridor',portId:'left',targetInstanceId:'left',targetPortId:'right',rotation:0}],[]);assert.equal(Object.keys(corridor.assets).length,1);assert.equal(Object.keys(corridor.instances).length,2);assert.deepEqual(corridor.instances.right.position,[6.4,0,0]);report.checks.push('Two actual voxel eaves-corridor segments dock with continuous floor, no colliding roof-end ornaments and one shared master');
 const large=await scenario('exterior-starport',[{op:'produceCatalogAsset',catalogId:'BUILT-094',id:'ring'},{op:'produceCatalogAsset',catalogId:'BUILT-095',id:'tower'},{op:'instance',id:'ring-1',assetId:'ring',position:[0,0,0]},{op:'instance',id:'tower-1',assetId:'tower',position:[100,0,0]}],[]);assert.equal((large.assets.ring.source!.ring as any).majorRadiusM,42);assert.equal((large.assets.tower.source!.energyVolume as any).heightM,35);assert.equal(large.materials[large.styles.yunshan.energyField].solid,false);report.checks.push('42m-major-radius ring and separate 35m energy column keep true metre dimensions and independent 200/100mm grids; non-solid energy remains distinct from physical glass and structure');
 report.checks.push('All three scenarios save actual multi-view screenshots and GLB/native/collision/interface/material-atlas exports; native document hashes match canonical assets, instances, materials and styles');
 const last=await call('save_project',{filename:'verified-exterior-starport.ysvox.json'}),saved=await state();assert.equal(hash(JSON.parse(await readFile(last.path,'utf8'))),hash(saved));await stop();await start();assert.equal(hash(await state()),hash(saved));report.checks.push('Saved native project and server restart restore the exact canonical document');
 assert.deepEqual(report.errors,[]);report.status='passed';report.completedAt=new Date().toISOString();console.log(JSON.stringify({status:report.status,checks:report.checks.length,out}));
}catch(error){report.status='failed';report.errors.push(String(error));throw error;}finally{await browser?.close();await client?.close();await stop();await writeFile(path.join(out,'exterior-mcp-verification.json'),JSON.stringify(report,null,2));await writeFile(path.join(out,'exterior-mcp-server.log'),log);}
