import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {chromium} from 'playwright';
import {validationBrowserOptions} from './browser-options';
import {productionProject} from '../src/production/style';
import {Grid} from '../src/core/grid';
import {parseCatalogCSV} from '../src/core/catalog';
import {outfitHash} from '../src/production/outfit-components';
import {auditAgeVariant} from './lib/age-variant-audit';
import {auditCharacterPalette} from './lib/character-palette-audit';
import {rotateY,type Project,type Assembly} from '../src/core/types';
import {assemblyBoundsM} from '../src/production/assembly-geometry';
const hash=(v:unknown)=>outfitHash(v??null),latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),verification=JSON.parse(await readFile(latest.evidence+'/variant-verification.json','utf8')),out=latest.evidence,runtime=path.join(out,'variant-mcp-runtime'),url='http://127.0.0.1:4401',rows=latest.models;
assert.equal(rows.length,27);assert.equal(verification.status,'passed');assert.equal(verification.records.length,39);await mkdir(runtime,{recursive:true});
for(const file of['atlas-production-index.json','production-index.json','architecture-index.json','material-index.json',...rows.map((r:any)=>r.file)])await copyFile('projects/'+file,runtime+'/'+file);await cp('projects/reference-atlas',runtime+'/reference-atlas',{recursive:true});await copyFile('projects/'+rows[0].file,runtime+'/autosave.ysvox.json');
for(const[j,r]of verification.records.entries()){r.runtimeFile=r.isDefault?r.file:'form-'+j+'.ysvox.json';if(!r.isDefault)await copyFile(r.file,runtime+'/'+r.runtimeFile);}
const empty=productionProject('M062–M064人物年龄及用途配色');empty.catalog={sourceName:'city-assets.csv',importedAt:latest.createdAt,entries:Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]))};for(const id of[720,788,789])empty.materials[id]={...empty.materials[empty.styles.yunshan.skinSurface],id,name:'foreign material '+id,color:'#123456'};await writeFile(runtime+'/empty.ysvox.json',JSON.stringify(empty));
let server:ChildProcess|undefined,client:Client|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,log='';
const report:any={run:latest.run,status:'running',checks:[],errors:[],views:[],quarterTurns:[],publicForms:[],notifications:[],expectedInvalidationVersions:[]},state=async():Promise<Project>=>(await fetch(url+'/api/state').then(r=>r.json())).project,fileSHA=async(file:string)=>createHash('sha256').update(await readFile(file)).digest('hex'),audit=(p:Project,a:Assembly)=>a.source!.ageVariant?auditAgeVariant(p,a):auditCharacterPalette(p,a);
try{
 server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4401',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);let ready=false;for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok){ready=true;break;}}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}assert.ok(ready);
 client=new Client({name:'character-palette-verification',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],cwd:process.cwd(),env:{...process.env as Record<string,string>,VOXEL_URL:url},stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const r:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(name,r.isError?'ERROR':'OK');return{...JSON.parse(r.content[0].text),isError:!!r.isError};},call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 browser=await chromium.launch(validationBrowserOptions());report.browser=browser.version();const page=await browser.newPage({viewport:{width:1400,height:1000}});page.setDefaultTimeout(180000);page.on('pageerror',e=>report.errors.push(e.message));page.on('websocket',socket=>socket.on('framereceived',f=>{const n=JSON.parse(f.payload.toString());report.notifications.push({event:n.event,version:n.version,bytes:Buffer.byteLength(f.payload.toString()),fullProject:!!n.project});}));await page.goto(url+'/?atlas=1&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready);
 report.webgl=await page.evaluate(()=>{const gl=(document.querySelector('#viewport canvas')as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return gl.getParameter(ext?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);});
 const sync=async(v:number)=>page.waitForFunction(n=>(window as any).voxelStudio.performance.renderedVersion===n,v),edit=async(commands:any[])=>{const r={expectedVersion:(await state()).version,requestId:crypto.randomUUID(),commands},dry=await call('edit_transaction',{...r,dryRun:true}),result=await call('edit_transaction',{...r,previewToken:dry.previewToken});await sync(result.version);report.expectedInvalidationVersions.push(result.version);return result;},load=async(file:string)=>{const r=await call('load_project',{filename:file,expectedVersion:(await state()).version});await sync(r.version);report.expectedInvalidationVersions.push(r.version);return state();};
 const capture=async(key:string,view='isometric')=>{await page.evaluate(async view=>{const v=(window as any).voxelStudio;await v.mode('scene');v.clay(true);v.studio(false);v.referenceLighting(false);v.ao(false);v.bloom(false);v.view(view);},view);for(let n=0;n<6;n++)await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const box=await page.locator('#viewport').boundingBox();assert.ok(box);const file='variant-'+key+'.png';await page.screenshot({path:out+'/'+file,clip:box});const perf=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.equal(perf.meshError,null);assert.equal(perf.renderedVersion,(await state()).version);report.views.push({key,file,view,triangles:perf.triangles,renderedVersion:perf.renderedVersion,imageSHA256:await fileSHA(out+'/'+file),frameWait:12});};
 const lib=await call('read_production_library',{query:'CHAR-019'});for(const[k,v]of Object.entries({atlasReferenceCandidates:759,atlasAssemblyCandidates:186,atlasVariantCandidates:57,atlasVariantForms:150,baseModels:533,variantEntries:61,variantModels:159}))assert.equal(lib.counts[k],v);report.libraryCounts=lib.counts;
 for(const row of rows){const list=await call('list_production_recipes',{query:row.id,limit:100}),recipe=list.entries.find((r:any)=>r.id===row.id);assert.equal(recipe.kind,'variant');assert.equal(recipe.parentCatalogId,row.parentCatalogId);for(const[k,v]of Object.entries(row.parameters))assert.equal(recipe.parameters[k].default,v);}
 await writeFile('docs/tool-schemas.json',JSON.stringify((await client.listTools()).tools,null,2));report.checks.push('All27reference recipes and exact library counts exposed over official MCP; no new base or assembly counts.');
 await page.locator('#atlas-sheet').selectOption('M062');await page.locator('[data-atlas-open][data-catalog="CHAR-019"]').first().click();await page.waitForFunction(()=>Object.values((window as any).voxelStudio.project.assemblies??{}).some((a:any)=>a.source?.catalogId==='CHAR-019'));const opened=await state();await sync(opened.version);report.expectedInvalidationVersions.push(opened.version);const listed=await call('list_assets');assert.equal(listed.counts.variants,1);assert.equal(listed.counts.assemblies,0);report.checks.push('Actual M062 atlas button opens019as one variant.');
 for(const row of verification.records){
  const before=await load(row.runtimeFile),a=before.assemblies![row.assemblyId];
  if(a.source!.ageVariant){await capture(row.id+'-back','back');await capture(row.id+'-left','left');}
  else if(!row.isDefault)await capture(row.id+'-garment-2','isometric');
  await edit([{op:'instantiateAssembly',assemblyId:row.assemblyId,prefix:'quarter',position:[3,0,4],rotation:1}]);const turned=await state();assert.equal(Object.keys(turned.instances).length,a.instances.length*2);for(const i of a.instances){const copy=turned.instances['quarter-'+i.id];assert.equal(copy.assetId,i.assetId);assert.equal(copy.rotation,(i.rotation+1)%4);assert.equal(hash(copy.position),hash(rotateY(i.position,1).map((n,k)=>n+[3,0,4][k])));}assert.equal(hash(turned.assets),hash(before.assets));await edit([{op:'undo'}]);assert.equal(hash((await state()).instances),hash(before.instances));report.quarterTurns.push({id:row.id,params:row.params,sourceSHA256:await fileSHA(row.isDefault?'projects/'+row.file:row.file),actualQuarterTurnPositionsAndAssetsVerified:true,passed:true});
  await load('empty.ysvox.json');const clean=await state();await edit([{op:'produceCatalogVariant',catalogId:row.id,id:row.assemblyId,params:row.params,place:true}]);const made=await state();for(const id of[720,788,789])assert.deepEqual(made.materials[id],empty.materials[id]);report.publicForms.push({id:row.id,params:row.params,audit:audit(made,made.assemblies![row.assemblyId]),foreignMaterialsPreserved:true});await edit([{op:'undo'}]);for(const field of['assets','assemblies','instances','materials','styles','palettes','catalog']as const)assert.equal(hash((await state())[field]),hash(clean[field]));
 }
 report.checks.push('All39finite forms created via official MCP, each saved form quarterturned and undone with exact asset/placement preservation.');
 await load('empty.ysvox.json');await edit([17,18,19,20,21].flatMap((n,j)=>[{op:'produceCatalogVariant',catalogId:'CHAR-0'+n,id:'age'+n},{op:'instantiateAssembly',assemblyId:'age'+n,prefix:'age-instance-'+n,position:[j*.75,0,0],rotation:0}]));const ages=await state();for(const a of Object.values(ages.assemblies!))assert.ok(auditAgeVariant(ages,a).passed);report.ageComparison={file:'five-age-height-comparison.ysvox.json',models:Object.values(ages.assemblies!).map(a=>({catalogId:a.source!.catalogId,...assemblyBoundsM(ages,a)}))};await writeFile(out+'/five-age-height-comparison.ysvox.json',JSON.stringify(ages));await capture('five-age-height-comparison-front','front');await capture('five-age-height-comparison-isometric');
 await load('empty.ysvox.json');await edit([30,31,32,33,34].flatMap((n,j)=>[{op:'produceCatalogVariant',catalogId:'CHAR-0'+n,id:'skin'+n},{op:'instantiateAssembly',assemblyId:'skin'+n,prefix:'skin-instance-'+n,position:[j*1.05,0,0],rotation:0}]));const skins=await state();for(const a of Object.values(skins.assemblies!))assert.ok(auditCharacterPalette(skins,a).passed);await writeFile(out+'/five-skin-palette-comparison.ysvox.json',JSON.stringify(skins));await capture('five-skin-palette-comparison','front');report.skinComparison={file:'five-skin-palette-comparison.ysvox.json',fiveScopedSkinMaterials:[30,31,32,33,34].map(n=>skins.styles['character-palette-char-0'+n].skinSurface),sameResidentGeometry:true,headAndBothHandsAndFeet:true};
 const skin=skins.styles['character-palette-char-030'].skinSurface;await edit([{op:'definePalette',name:'单个居民换肤色',materials:{[skin]:{color:'#102030'}}},{op:'palette',name:'单个居民换肤色'}]);const changed=await state();assert.equal(hash(changed.assets),hash(skins.assets));for(const[id,m]of Object.entries(skins.materials))if(Number(id)!==skin)assert.deepEqual(changed.materials[id],m);await edit([{op:'undo'}]);assert.equal(hash((await state()).materials),hash(skins.materials));
 for(const command of[{op:'produceCatalogVariant',catalogId:'CHAR-019',id:'bad',params:{ageBand:'teen'}},{op:'produceCatalogVariant',catalogId:'CHAR-030',id:'bad',params:{characterTone:'char-031'}},{op:'produceCatalogVariant',catalogId:'CHAR-043',id:'bad',params:{garment:2}},{op:'produceCatalogVariant',catalogId:'CHAR-035',id:'bad',params:{garment:3}},{op:'produceCatalogVariant',catalogId:'CHAR-049',id:'bad',params:{roofProgram:'farm'}},{op:'produceCatalogVariant',catalogId:'CHAR-002',id:'bad'},{op:'produceCatalogAsset',catalogId:'CHAR-035',id:'bad'}]){const before=await state(),r=await raw('edit_transaction',{expectedVersion:before.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:720,properties:{color:'#ffffff'}},command]});assert.ok(r.isError);assert.equal(hash(await state()),hash(before));}
 report.checks.push('Five exact height bands and five skin instances coexist; one skin appearance edit leaves other people and all geometry unchanged. Seven invalid family/band/type edits roll back atomically.');
 const row=rows.find((r:any)=>r.id==='CHAR-020'),doc=await load(row.file),a=doc.assemblies![row.assemblyId],d=a.source!.ageVariant as any,body=doc.assets[a.instances.find(i=>i.id===d.bodyInstance)!.assetId],cell=(body.source!.ageBodyFit as any).nativeMoves[0].to;const queried=await call('query_voxels',{assetId:body.id,region:{min:cell,max:cell.map((n:number)=>n+1)}});assert.equal(queried.total,1);assert.equal(queried.cellSizeM,.005);assert.deepEqual(queried.cells,[[cell,new Grid(body.chunks).get(cell)]]);report.queriedNativeCell=queried;report.checks.push('Actual moved5mmteen native detail queried via MCP.');
 await call('save_project',{filename:'roundtrip.ysvox.json'});const restored:Project=JSON.parse(await readFile(runtime+'/roundtrip.ysvox.json','utf8'));for(const key of['assets','assemblies','instances','styles','materials']as const)assert.equal(hash(restored[key]),hash(doc[key]));assert.ok(auditAgeVariant(restored,restored.assemblies![row.assemblyId]).passed);report.checks.push('Official save/load retains exact age proportions, native moves and full source graph.');
 assert.equal(report.publicForms.length,39);assert.equal(report.quarterTurns.length,39);assert.equal(report.views.length,21);assert.deepEqual(report.notifications.map((n:any)=>n.version),report.expectedInvalidationVersions);assert.ok(report.notifications.every((n:any)=>n.event==='state-invalidated'&&!n.fullProject&&n.bytes<65536));assert.deepEqual(report.errors,[]);report.status='passed';
}catch(e:any){report.status='failed';report.errors.push(e.stack??e.message);throw e;}
finally{await browser?.close();await client?.close();if(server){server.kill('SIGTERM');await new Promise<void>(resolve=>{if(server!.exitCode!==null)return resolve();const timer=setTimeout(()=>{server!.kill('SIGKILL');resolve();},5000);server!.once('exit',()=>{clearTimeout(timer);resolve();});});}await writeFile(out+'/variant-mcp-server.txt',log);await writeFile(out+'/variant-mcp-verification.json',JSON.stringify(report,null,2));}
console.log(JSON.stringify({status:report.status,publicForms:report.publicForms.length,quarterTurns:report.quarterTurns.length,views:report.views.length,checks:report.checks.length,notifications:report.notifications.length}));
