import assert from 'node:assert/strict';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createHash} from 'node:crypto';import {NodeIO} from '@gltf-transform/core';import {KHRMaterialsEmissiveStrength,KHRMaterialsUnlit} from '@gltf-transform/extensions';import sharp from 'sharp';
import {Engine,validateProject} from '../src/core/engine';import {Grid} from '../src/core/grid';import {displayMesh} from '../src/core/mesh';import {productionProject} from '../src/production/style';import {referenceFinishCommands} from '../src/production/reference-finish';import {makeArchitectureAssembly} from '../src/production/atlas-architecture-assemblies';import {assemblyGeometryData,assemblyBoundsM,assemblyExportToleranceM} from '../src/production/assembly-geometry';import {parseCatalogCSV} from '../src/core/catalog';import {buildGLB,exportProject} from '../src/export/exporter';import {architectureClosed,architecturePointRoles,architectureComponents} from './lib/architecture-audit';import {CivicAudit,civicSupports,civicStairClearance,civicFloorOpenings,civicTransportClearance} from './lib/civic-audit';import {metropolisClearance} from './lib/metropolis-audit';import {geometryData} from '../src/core/sky';import {nativeIslandAttachments} from '../src/production/mixed-review';import {gltfPoints,pointBounds} from './lib/skin-audit';import type {Project,Command,V3} from '../src/core/types';
const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),rows=latest.models,hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex'),io=new NodeIO().registerExtensions([KHRMaterialsEmissiveStrength,KHRMaterialsUnlit]);assert.equal(latest.kind,'assembly-batch');assert.equal(rows.length,12);assert.ok(rows.every((r:any)=>r.sheet==='M046'));
const catalog=Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r])),records:any[]=[],variants:any[]=[],defaults=new Map<string,Project>();
const commit=(e:Engine,commands:Command[])=>{const r={expectedVersion:e.project.version,requestId:crypto.randomUUID(),commands},d=e.execute({...r,dryRun:true});return e.execute({...r,previewToken:d.previewToken});};
async function inspect(p:Project,id:string,params:Record<string,string|number>,directory:string,isDefault:boolean){
 const assembly=Object.values(p.assemblies!)[0],bounds=assemblyBoundsM(p,assembly),q=new CivicAudit(p,assembly),stairs=civicStairClearance(q),supports=civicSupports(q),holes=civicFloorOpenings(q),transport=metropolisClearance(q);for(const r of[...stairs,...transport.checks])assert.ok(r.clear,id+JSON.stringify(r));assert.ok(supports.every(r=>r.supported));assert.ok(holes.every(r=>r.clear));assert.ok(transport.contacts.every(r=>r.supported));const closed=[],pins=[];
 for(const a of Object.values(p.assets))if(a.source?.kind==='assembly-derived-component'){const checked=architectureClosed(a);assert.ok(checked.every(c=>c.closed&&c.oriented));closed.push({assetId:a.id,parts:checked.length});const attachments=nativeIslandAttachments({...a,meshes:architectureComponents(a)});assert.ok(attachments.every(r=>r.attached),a.id);pins.push({assetId:a.id,nativeDetails:attachments.length});}
 const triangleCounts=new Map([...new Set(assembly.instances.map(i=>i.assetId))].map(id=>[id,{near:displayMesh(p.assets[id],p.materials).reduce((n,m)=>n+m.indices.length/3,0),far:displayMesh(p.assets[id],p.materials,'far').reduce((n,m)=>n+m.indices.length/3,0)}])),near=assembly.instances.reduce((n,i)=>n+triangleCounts.get(i.assetId)!.near,0),far=assembly.instances.reduce((n,i)=>n+triangleCounts.get(i.assetId)!.far,0);assert.ok(far<=near);
 const fg=await buildGLB(p,undefined,'far');await writeFile(directory+'/visual-far.glb',fg.glb);const gd=await io.readBinary(fg.glb),nodes=gd.getRoot().listScenes()[0].listChildren();assert.equal(nodes.length,assembly.instances.length);const actual=pointBounds(nodes.flatMap(n=>gltfPoints(n))),error=Math.max(...bounds.min.map((v,d)=>Math.abs(v-actual.min[d])),...bounds.max.map((v,d)=>Math.abs(v-actual.max[d]))),tolerance=assemblyExportToleranceM(p,assembly);assert.ok(error<tolerance);assert.deepEqual(gd.getRoot().listScenes()[0].getExtras().assemblyDefinitions,p.assemblies);
 const e=new Engine(p);commit(e,[{op:'palette',name:'参考材质试作'}]);assert.deepEqual(e.project.assets,p.assets);const material=await buildGLB(e.project),md=await io.readBinary(material.glb),alpha=[];await writeFile(directory+'/visual-material.glb',material.glb);
 for(const[role,expected]of[['glass',.3],['civicGuideOptic',.65],['vehicleInactiveOptic',.7],['architectureOptic',.7]]as const){const mat=md.getRoot().listMaterials().find(m=>m.getExtras().voxelMaterialId===p.styles.yunshan[role]),primitive=md.getRoot().listMeshes().flatMap(m=>m.listPrimitives()).find(p=>p.getMaterial()===mat);if(!primitive)continue;assert.equal(mat!.getAlphaMode(),'BLEND');const uv=primitive.getAttribute('TEXCOORD_0')!.getArray()!,img=await sharp(Buffer.from(mat!.getBaseColorTexture()!.getImage()!)).ensureAlpha().raw().toBuffer({resolveWithObject:true}),x=Math.floor(((uv[0]%1+1)%1)*img.info.width),y=Math.floor(((uv[1]%1+1)%1)*img.info.height),effectiveAlpha=img.data[(y*img.info.width+x)*4+3]/255*mat!.getBaseColorFactor()[3];assert.ok(Math.abs(effectiveAlpha-expected)<1/255);alpha.push({role,effectiveAlpha,actualUVPixel:true});}
 for(const role of['civicGuideOptic','vehicleInactiveOptic','architectureOptic']){const mat=md.getRoot().listMaterials().find(m=>m.getExtras().voxelMaterialId===p.styles.yunshan[role]);if(mat)assert.deepEqual(mat.getEmissiveFactor(),[0,0,0]);}
 const interfaces=JSON.parse(await readFile(directory+'/interfaces.json','utf8')),native=JSON.parse(await readFile(directory+'/voxels.ysvox.json','utf8'));assert.deepEqual(interfaces.assemblies,p.assemblies);assert.deepEqual(interfaces.instances,Object.values(p.instances));for(const k of['assets','instances','assemblies']as const)assert.equal(hash(native[k]),hash(p[k]));
 const r={id,params,isDefault,directory,componentAssets:Object.keys(p.assets).length,instances:assembly.instances.length,closed,pins,supports,stairs,floorOpenings:holes,transport,nearTriangles:near,farTriangles:far,farGLBBoundsErrorM:error,glbBoundsToleranceM:tolerance,alphaChecks:alpha,geometrySHA256:hash(assemblyGeometryData(p,assembly)),actualSharedGLTFMeshes:gd.getRoot().listMeshes().length,scope:'Finite authored geometry and static boarding states. Contacts may intentionally intersect; no original terrain, route controller or human art acceptance.'};records.push(r);console.log(JSON.stringify({id,params,instances:r.instances,stairSamples:stairs.length,transportSamples:transport.checks.length,closedParts:closed.reduce((n,r)=>n+r.parts,0),near,far,error}));
}
for(const row of rows){const p:Project=JSON.parse(await readFile('projects/'+row.file,'utf8')),a=p.assemblies![row.assemblyId];assert.equal(hash(assemblyGeometryData(p,a)),row.sha256);defaults.set(row.id,p);await inspect(p,row.id,{},latest.out+'/exports/'+row.id,true);}
const original=index.entries.find((r:any)=>r.id==='BUILT-188'),originalDoc:Project=JSON.parse(await readFile('projects/'+original.file,'utf8')),originalGeometry=hash(geometryData(originalDoc.assets[original.assetId]));for(const id of['BUILT-184','BUILT-185']){const p=defaults.get(id)!,leg=Object.values(p.assets).find(a=>a.source?.catalogId==='BUILT-188')!;assert.equal(hash(geometryData(leg)),originalGeometry);assert.deepEqual(leg.ports,originalDoc.assets[original.assetId].ports);}
const gallery=index.studies.find((r:any)=>r.id==='M046-gallery'),gp:Project=JSON.parse(await readFile('projects/'+gallery.file,'utf8')),galleryBounds=Object.values(gp.assemblies!).map(a=>({id:a.id,...assemblyBoundsM(gp,{instances:a.instances.map(i=>gp.instances[i.id])})}));for(let i=0;i<galleryBounds.length;i++)for(let j=i+1;j<galleryBounds.length;j++)assert.ok(galleryBounds[i].min.some((v,d)=>v>=galleryBounds[j].max[d]||galleryBounds[i].max[d]<=galleryBounds[j].min[d]));
const points:any[]=[];for(const[id,predicate,point,role]of[['BUILT-181','seven-metre',[0,.202,0],'airfieldYellow'],['BUILT-169','public-three-box',[0,.96,-2.76],'vehicleInactiveOptic'],['BUILT-220','modern-wall-20',[-9.9,.2,.09],'architecturalCladding'],['BUILT-220','modern-crown-spire',[0,11.5,-.168],'architectureOptic']]as [string,string,V3,string][]){const p=defaults.get(id)!,asset=Object.values(p.assets).find(a=>a.id.includes(predicate))!,ids=architecturePointRoles(p,asset,point);assert.ok(ids.includes(p.styles.yunshan[role]),role);points.push({id,assetId:asset.id,point,role,actualMaterialIds:ids});}
await writeFile(latest.evidence+'/assembly-verification.json',JSON.stringify({run:latest.run,status:'passed',records,gallery:gallery.id,galleryBounds,galleryGroupsDisjoint:true,preservedNativeMaster:{id:original.id,geometrySHA256:originalGeometry,forms:['BUILT-184','BUILT-185']},defaultTemplates:12,finiteForms:12,newBaseMasters:0,variants},null,2));await writeFile(latest.evidence+'/material-audit.json',JSON.stringify({run:latest.run,status:'passed',candidates:12,pendingCandidates:0,independentInteriorPoints:points,newRoles:['vehicleInactiveOptic','authorRouteMarker','architecturalCladding','architectureOptic'],totalRoles:496,creationBatches:[256,240],note:'Real airfield paint, aircraft optics, facade metal and architecture optics; original native landing legs unchanged. Effective GLB alpha read at actual primitive UV pixels.'},null,2));
