import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {NodeIO} from '@gltf-transform/core';
import {KHRMaterialsEmissiveStrength} from '@gltf-transform/extensions';
import {validationBrowserOptions} from './browser-options';
import {parseCatalogCSV} from '../src/core/catalog';
import {productionProject} from '../src/production/style';
import * as assembly from '../src/production/terrain-assembly';
import type {Command,Project,V3} from '../src/core/types';

const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),out=latest.evidence,runtime=path.join(out,`terrain-mcp-${Date.now()}-runtime`),url='http://127.0.0.1:4362',gallery=index.studies.find((s:any)=>s.id==='M026-gallery');assert.ok(gallery);
await mkdir(runtime,{recursive:true});for(const f of['atlas-production-index.json','production-index.json',gallery.file,...index.entries.filter((e:any)=>e.sheet==='M026').map((e:any)=>e.file)])await copyFile(path.join('projects',f),path.join(runtime,f));
await cp('projects/reference-atlas',path.join(runtime,'reference-atlas'),{recursive:true});await copyFile(path.join(runtime,gallery.file),path.join(runtime,'autosave.ysvox.json'));
const empty=productionProject('M026 · 真实 MCP 拼装');empty.catalog={sourceName:'city-assets.csv',importedAt:'verification',entries:Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]))};await writeFile(path.join(runtime,'empty.ysvox.json'),JSON.stringify(empty));
const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),state=async():Promise<Project>=>(await fetch(url+'/api/state').then(r=>r.json())).project;
const report:any={run:index.run,startedAt:new Date().toISOString(),status:'running',checks:[],errors:[],uiSync:[],assemblies:[]};let server:ChildProcess|undefined,client:Client|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,log='';
async function start(){server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4362',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok)return;}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}throw new Error('Server startup timeout');}
async function stop(){if(server&&server.exitCode===null){const closed=once(server,'exit');server.kill('SIGTERM');await closed;}}
function clean(c:any,unsupported:string[]=[],nearPairs:string[][]=[]){assert.deepEqual(c.unsupported,unsupported);assert.deepEqual(c.gaps.map((g:any)=>g.instances),nearPairs);for(const g of c.gaps)assert.ok(Math.abs(g.distanceM-.1)<1e-8);for(const k of['collisions','warnings'])assert.deepEqual(c[k],[],k);assert.ok(c.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));assert.ok(c.clearances.every((o:any)=>o.clear));}
try{
 await start();client=new Client({name:'terrain-semantic-validation',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],env:{...process.env as Record<string,string>,VOXEL_URL:url},cwd:process.cwd(),stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const t=performance.now(),r:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(JSON.stringify({tool:name,ms:performance.now()-t,error:!!r.isError}));return{...JSON.parse(r.content[0].text),isError:!!r.isError};};
 const call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 browser=await chromium.launch(validationBrowserOptions());report.browser=browser.version();const page=await browser.newPage({viewport:{width:1600,height:1050}});page.setDefaultTimeout(120000);page.on('pageerror',e=>report.errors.push(e.message));await page.goto(url+'/?atlas=1&sheet=M026&asset=env-013&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready,null,{timeout:120000});
 report.webgl=await page.evaluate(()=>{const gl=(document.querySelector('#viewport canvas') as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return gl.getParameter(ext?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);});
 const sync=async(v:number)=>{const t=performance.now();await page.waitForFunction(n=>(window as any).voxelStudio.performance.renderedVersion===n,v,{timeout:120000});report.uiSync.push({version:v,ms:performance.now()-t});};
 const before=await state(),roles=before.styles.yunshan,check=await call('check_geometry');clean(check);assert.equal(check.collisionGrids.length,12);report.gallery=check;
 for(const [assetId,point,role]of[
 ['built-309',[.1,.1,.1],'structuralConcrete'],['built-310',[.35,7.85,.75],'cableSheave'],['built-312',[.5,1,.5],'wetPileWood'],['built-312',[.5,1.7,.35],'moss'],['built-316',[.05,1,.05],'metal'],['env-012',[10.5,.7,0],'water'],['env-013',[1.9,.5,1.9],'bedrock'],
 ] as [string,V3,string][]){const a=before.assets[assetId],v=point.map(n=>Math.floor((n+1e-8)/a.cellSize)),r=await call('query_voxels',{assetId,region:{min:v,max:v.map(n=>n+1)}});assert.equal(r.cells[0]?.[1],roles[role]);}
 for(const role of['moss','shrubFoliage'])assert.equal(before.materials[roles[role]].solid,false);assert.equal(before.materials[roles.surfaceSoil].category,'soil');
 report.checks.push('Twelve M026 families: actual structural and geology roles, ENV IDs, 0.2m authority and noncollision plants queried through MCP');
 const changed=['bedrock','surfaceSoil','moss','wetPileWood'],request={expectedVersion:before.version,requestId:crypto.randomUUID(),label:'M026地质和木桩独立外观包验证',commands:[{op:'definePalette',name:'地质独立材质',materials:Object.fromEntries(changed.map((r,i)=>[roles[r],{color:['#703943','#33806b','#455456','#85abb6'][i]}]))},{op:'palette',name:'地质独立材质'}]};
 const dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(before));const applied=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(applied.version);const after=await state();assert.equal(applied.modifiedVoxels,0);for(const k of['assets','styles']as const)assert.equal(hash(after[k]),hash(before[k]));
 for(const[id,m]of Object.entries(before.materials)){assert.equal(after.materials[id].solid,m.solid);assert.equal(after.materials[id].category,m.category);if(!changed.some(r=>String(roles[r])===id))assert.deepEqual(after.materials[id],m);}assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(after.materials));
 await page.locator('#material-category-filter').selectOption('soil');const buttons=await page.locator('[data-material]').evaluateAll(nodes=>nodes.map(n=>Number((n as HTMLElement).dataset.material)));assert.ok(buttons.includes(roles.surfaceSoil));for(const id of buttons)assert.equal(after.materials[id].category,'soil');await page.locator('[data-material="'+roles.surfaceSoil+'"]').click();assert.match(await page.locator('#material-role').innerText(),/yunshan.surfaceSoil/);await page.screenshot({path:path.join(out,'mcp-terrain-roles.png')});
 assert.equal((await call('edit_transaction',request)).version,applied.version);assert.equal((await raw('edit_transaction',{...request,requestId:crypto.randomUUID()})).code,'VERSION_CONFLICT');const failed=await raw('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:roles.surfaceSoil,properties:{color:'#ff00ff'}},{op:'produceCatalogAsset',catalogId:'ENV-005',id:'bad',params:{tileX:1}}]});assert.ok(failed.isError);assert.equal(hash(await state()),hash(after));
 const undo=await call('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(undo.version);for(const k of['assets','styles','materials','palettes']as const)assert.equal(hash((await state())[k]),hash(before[k]));await page.screenshot({path:path.join(out,'mcp-terrain-roles-restored.png')});report.checks.push('Four independent geology/soil/moss/wood appearance roles, canonical UI hashes, soil filtering, dry run, version conflicts, idempotency, failure rollback and one undo all verified');
 const scenario=async(name:string,commands:Command[],clearances:{name:string;min:V3;max:V3}[],unsupported:string[]=[],nearPairs:string[][]=[])=>{
  const loaded=await call('load_project',{filename:'empty.ysvox.json',expectedVersion:(await state()).version});await sync(loaded.version);const request={expectedVersion:loaded.version,requestId:crypto.randomUUID(),commands},initial=await state(),dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(initial));const built=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(built.version);await page.evaluate(()=>(window as any).voxelStudio.mode('scene'));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const geometry=await call('check_geometry',{clearances});clean(geometry,unsupported,nearPairs);const doc=await state();assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets)),hash(doc.assets));await page.screenshot({path:path.join(out,'mcp-'+name+'.png')});
  const saved=await call('save_project',{filename:name+'.ysvox.json'});await copyFile(saved.path,path.join(out,name+'.ysvox.json'));const exported=await call('export_project',{name}),round=JSON.parse(await readFile(path.join(exported.directory,'voxels.ysvox.json'),'utf8'));for(const k of['assets','instances','materials','styles']as const)assert.equal(hash(round[k]),hash(doc[k]));await cp(exported.directory,path.join(out,name+'-export'),{recursive:true});
  const previews=await call('generate_previews',{appearance:'baseColor',views:['isometric','front']});assert.equal(previews.files.length,2);for(let i=0;i<2;i++){assert.ok((await readFile(previews.files[i])).length>1000);await copyFile(previews.files[i],path.join(out,name+'-view-'+i+'.png'));}report.assemblies.push({name,masters:Object.keys(doc.assets).length,placements:Object.keys(doc.instances).length,geometry,expectedUnsupported:unsupported,expectedNearPairs:nearPairs,exported,previews});return doc;
 };
 await page.locator('#material-category-filter').selectOption('all');
 const definitions=await client.listTools();await writeFile('docs/tool-schemas.json',JSON.stringify(definitions.tools,null,2));
 const recipes=await call('list_production_recipes',{query:'ENV-001'});assert.equal(recipes.entries[0].parameters.tileX.minimum,-8);assert.equal(recipes.entries[0].cellSizeM,.2);report.checks.push('MCP exposes ENV native recipes and bounded 24m tile sampling without aliasing BUILT or LIFE');
 const docHash=hash(await state());report.terrainViews=[];
 for(const a of Object.values(before.assets).filter(a=>String(a.source?.catalogId).startsWith('ENV-'))){
  await page.evaluate(async id=>{const s=(window as any).voxelStudio;await s.mode('asset',id);s.view('isometric');s.clay(true);await s.meshMode('near');},a.id);
  await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const near=await page.evaluate(()=>(window as any).voxelStudio.performance);
  await page.locator('#viewport').screenshot({path:path.join(out,'terrain-'+a.id+'-near.png')});
  await page.evaluate(()=>(window as any).voxelStudio.meshMode('far'));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const far=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.ok(far.triangles<near.triangles);assert.equal(far.meshMode,'far');assert.equal(far.meshError,null);await page.locator('#viewport').screenshot({path:path.join(out,'terrain-'+a.id+'-far.png')});
  await page.evaluate(()=>{const s=(window as any).voxelStudio;s.clay(false);s.studio(true);s.timeOfDay('day');});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.locator('#viewport').screenshot({path:path.join(out,'terrain-'+a.id+'-day.png')});
  await page.evaluate(()=>(window as any).voxelStudio.timeOfDay('night'));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.locator('#viewport').screenshot({path:path.join(out,'terrain-'+a.id+'-night.png')});
  await page.evaluate(()=>{const s=(window as any).voxelStudio;s.timeOfDay('day');s.focus({min:[0,0,0],max:[35,35,35]});});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.locator('#viewport').screenshot({path:path.join(out,'terrain-'+a.id+'-close.png')});
  // The reverse switch must replace the whole far cache, including retained asset caches.
  await page.evaluate(async()=>{const s=(window as any).voxelStudio;s.clay(true);s.view('isometric');await s.meshMode('near');});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const restored=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.equal(restored.triangles,near.triangles);report.terrainViews.push({assetId:a.id,near,far,restoredTriangles:restored.triangles,files:['near','far','day','night','close'].map(v=>'terrain-'+a.id+'-'+v+'.png')});
 }
 assert.equal(hash(await state()),docHash);report.checks.push('All eight terrain assets rendered near/far/day/night/close in actual WebGL; far reduces triangles, reverse cache switching restores count, native document unchanged');
 const nightPreview=await call('generate_previews',{assetId:'env-013',appearance:'material',lighting:'night',meshMode:'far',views:['isometric']});assert.equal(nightPreview.lighting,'night');assert.equal(nightPreview.meshMode,'far');await copyFile(nightPreview.files[0],path.join(out,'terrain-mcp-night-far.png'));assert.equal(hash(await state()),docHash);assert.ok((await raw('generate_previews',{meshMode:'unverified'})).isError);report.checks.push('MCP night/far preview validates enums and captures unchanged native document');
 const editBefore=await state();await page.evaluate(async()=>{const s=(window as any).voxelStudio;await s.mode('asset','env-013');await s.meshMode('far');});
 const editRequest={expectedVersion:editBefore.version,requestId:crypto.randomUUID(),commands:[{op:'voxels',assetId:'env-013',mode:'remove',region:{min:[0,0,0],max:[1,1,1]}}]};const editDry=await call('edit_transaction',{...editRequest,dryRun:true}),editResult=await call('edit_transaction',{...editRequest,previewToken:editDry.previewToken});await sync(editResult.version);const edited=await state();assert.notEqual(hash(edited.assets['env-013'].chunks),hash(editBefore.assets['env-013'].chunks));assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets['env-013'].chunks)),hash(edited.assets['env-013'].chunks));assert.equal(await page.evaluate(()=>(window as any).voxelStudio.performance.meshMode),'far');
 const restoredEdit=await call('edit_transaction',{expectedVersion:edited.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(restoredEdit.version);assert.equal(hash((await state()).assets['env-013'].chunks),hash(editBefore.assets['env-013'].chunks));await page.evaluate(()=>(window as any).voxelStudio.meshMode('near'));report.checks.push('Native editing while displaying far geometry regenerates the whole cache and undo restores the original occupied cells');
 await page.evaluate(()=>{const s=(window as any).voxelStudio;s.timeOfDay('day');s.clay(true);});
 for(const[name,fn,clear]of assembly.terrainScenarios){const doc=await scenario('terrain-'+name,fn(roles),clear as any);if(name==='residential'){assert.equal((doc.assets.beam.source!.residential as any).sourceInstalled,0);assert.deepEqual(doc.assets.beam.origin,[-.6,-4,-4.8]);}report.checks.push('Real '+name+' installation has exact native collisions, support, openings and body clearances; original runtime is unbound');}
 report.originalRuntimeBound=false;report.checks.push('All five scenarios save actual MCP multiview previews plus GLB/native/collision/interface/material-atlas exports');
 const last=await call('save_project',{filename:'verified-terrain-arch.ysvox.json'}),saved=await state();assert.equal(hash(JSON.parse(await readFile(last.path,'utf8'))),hash(saved));await stop();await start();assert.equal(hash(await state()),hash(saved));report.checks.push('Native save and server restart restore the exact canonical document');
 assert.deepEqual(report.errors,[]);report.status='passed';report.completedAt=new Date().toISOString();console.log(JSON.stringify({status:report.status,checks:report.checks.length,out}));
}catch(error){report.status='failed';report.errors.push(String(error));throw error;}finally{await browser?.close();await client?.close();await stop();await writeFile(path.join(out,'terrain-mcp-verification.json'),JSON.stringify(report,null,2));await writeFile(path.join(out,'terrain-mcp-server.log'),log);}
