import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {validationBrowserOptions} from './browser-options';
import {parseCatalogCSV} from '../src/core/catalog';
import {productionProject} from '../src/production/style';
import {structureAssemblyCommands,structureRouteClearances} from '../src/production/structure-assembly';
import type {Project} from '../src/core/types';

const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8'));
const out=latest.evidence,runtime=path.join(out,'structure-mcp-runtime'),url='http://127.0.0.1:4348',gallery=index.studies.find((s:any)=>s.id==='M013-gallery');assert.ok(gallery);
await mkdir(runtime,{recursive:true});for(const f of['atlas-production-index.json','production-index.json',gallery.file,...index.entries.filter((e:any)=>e.sheet==='M013').map((e:any)=>e.file)])await copyFile(path.join('projects',f),path.join(runtime,f));
await cp('projects/reference-atlas',path.join(runtime,'reference-atlas'),{recursive:true});await copyFile(path.join(runtime,gallery.file),path.join(runtime,'autosave.ysvox.json'));
const empty=productionProject('两层服务翼 · 真实 MCP 拼装');empty.catalog={sourceName:'city-assets.csv',importedAt:'verification',entries:Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]))};await writeFile(path.join(runtime,'empty.ysvox.json'),JSON.stringify(empty));
const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),state=async():Promise<Project>=>(await fetch(url+'/api/state').then(r=>r.json())).project;
const report:any={run:index.run,startedAt:new Date().toISOString(),status:'running',checks:[],errors:[],uiSync:[]};let server:ChildProcess|undefined,client:Client|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,log='';
async function start(){server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4348',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok)return;}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}throw new Error('Server startup timeout');}
async function stop(){if(server&&server.exitCode===null){const closed=once(server,'exit');server.kill('SIGTERM');await closed;}}
try{
 await start();client=new Client({name:'structure-semantic-and-route-validation',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],env:{...process.env as Record<string,string>,VOXEL_URL:url},cwd:process.cwd(),stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const t=performance.now(),r:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(JSON.stringify({tool:name,ms:performance.now()-t,error:!!r.isError}));return{...JSON.parse(r.content[0].text),isError:!!r.isError};};
 const call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 browser=await chromium.launch(validationBrowserOptions());report.browser=browser.version();const page=await browser.newPage({viewport:{width:1600,height:1050}});page.on('pageerror',e=>report.errors.push(e.message));await page.goto(url+'/?atlas=1&sheet=M013&asset=built-018&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready,null,{timeout:120000});
 report.webgl=await page.evaluate(()=>{const gl=(document.querySelector('#viewport canvas') as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return gl.getParameter(ext?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);});if(process.argv.includes('--metal'))assert.match(report.webgl,/Metal Renderer/);
 const sync=async(v:number)=>{const t=performance.now();await page.waitForFunction(n=>(window as any).voxelStudio.performance.renderedVersion===n,v,{timeout:120000});report.uiSync.push({version:v,ms:performance.now()-t});};
 const before=await state(),roles=before.styles.yunshan,checks=await call('check_geometry');assert.equal(checks.collisionGrids.length,12);for(const k of['collisions','unsupported','warnings'])assert.deepEqual(checks[k],[]);assert.ok(checks.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));report.gallery=checks;
 report.checks.push('Twelve saved M013 masters have independent collision grids, no unsupported objects or blocked declared openings');
 for(const [min,role]of [[[25,50,64],'structuralConcrete'],[[25,50,69],'waterproofMembrane'],[[25,50,77],'earthCutaway'],[[3,10,79],'stone']] as const){const q=await call('query_voxels',{assetId:'built-018',region:{min,max:min.map(n=>n+1)}});assert.equal(q.cells[0]?.[1],roles[role]);}
 const changed=['structuralConcrete','mortar','waterproofMembrane','earthCutaway'],request={expectedVersion:before.version,requestId:crypto.randomUUID(),label:'建筑材质独立替换',commands:[{op:'definePalette',name:'分层检查',materials:Object.fromEntries(changed.map((r,i)=>[roles[r],{color:['#e06245','#9673ad','#44b6c6','#a8b556'][i]}]))},{op:'palette',name:'分层检查'}]};
 const dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(before));const applied=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(applied.version);assert.equal(applied.modifiedVoxels,0);const after=await state();
 for(const k of['assets','styles']as const)assert.equal(hash(after[k]),hash(before[k]));for(const [id,m]of Object.entries(before.materials)){assert.equal(after.materials[id].solid,m.solid);assert.equal(after.materials[id].category,m.category);if(!changed.some(r=>String(roles[r])===id))assert.equal(hash(after.materials[id]),hash(m));}assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(after.materials));
 await page.locator('#material-category-filter').selectOption('concrete');const buttons=await page.locator('[data-material]').evaluateAll(nodes=>nodes.map(n=>Number((n as HTMLElement).dataset.material)));assert.deepEqual(buttons.sort((a,b)=>a-b),[roles.structuralConcrete,roles.mortar].sort((a,b)=>a-b));await page.locator('[data-material="'+roles.structuralConcrete+'"]').click();assert.match(await page.locator('#material-role').innerText(),/yunshan.structuralConcrete/);await page.screenshot({path:path.join(out,'mcp-structure-roles.png')});
 assert.equal((await call('edit_transaction',request)).version,applied.version);assert.equal((await raw('edit_transaction',{...request,requestId:crypto.randomUUID()})).code,'VERSION_CONFLICT');const failed=await raw('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:roles.structuralConcrete,properties:{color:'#ff00ff'}},{op:'produceCatalogAsset',catalogId:'BUILT-999',id:'bad'}]});assert.ok(failed.isError);assert.equal(hash(await state()),hash(after));
 const undone=await call('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(undone.version);for(const k of['assets','styles','materials','palettes']as const)assert.equal(hash((await state())[k]),hash(before[k]));await page.screenshot({path:path.join(out,'mcp-structure-roles-restored.png')});report.checks.push('Concrete, membrane, earth and stone are queried from real cells; four-role resource pack preserves other materials, geometry and collision; UI category filter/hashes, idempotency, conflict, rollback and one undo pass');
 await page.locator('#material-category-filter').selectOption('all');await page.locator('#atlas-sheet').selectOption('M013');await page.locator('[data-catalog="BUILT-017"][data-atlas-open]').first().click();await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('built-017'),null,{timeout:120000});const original=await state();
 const resize={expectedVersion:original.version,requestId:crypto.randomUUID(),commands:[{op:'rebuildCatalogAsset',assetId:'built-017',params:{width:7.2}}]},preview=await call('edit_transaction',{...resize,dryRun:true});const windowInstances=Object.values(original.instances).filter(i=>i.assetId==='built-017');assert.ok(windowInstances.length>0);for(const i of windowInstances)assert.ok(preview.affectedInstances.includes(i.id));assert.equal(hash(await state()),hash(original));const resized=await call('edit_transaction',{...resize,previewToken:preview.previewToken});await sync(resized.version);assert.deepEqual((await state()).assets['built-017'].source!.dimensionsM,[7.2,3,.4]);await page.screenshot({path:path.join(out,'mcp-structure-window-rebuilt.png')});const restore=await call('edit_transaction',{expectedVersion:resized.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(restore.version);const restoredAsset=(await state()).assets['built-017'],originalAsset=original.assets['built-017'];assert.ok(restoredAsset.version>originalAsset.version);assert.deepEqual({...restoredAsset,version:0},{...originalAsset,version:0});report.checks.push('Real reference tile opens the window wall; width regeneration previews its affected placement, changes legal voxels in the UI and undoes without resizing a mesh');
 const loaded=await call('load_project',{filename:'empty.ysvox.json',expectedVersion:(await state()).version});await sync(loaded.version);const req={expectedVersion:loaded.version,requestId:crypto.randomUUID(),commands:structureAssemblyCommands((await state()).styles.yunshan)},plan=await call('edit_transaction',{...req,dryRun:true}),built=await call('edit_transaction',{...req,previewToken:plan.previewToken});await sync(built.version);await page.evaluate(()=>(window as any).voxelStudio.mode('scene'));await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('return'),null,{timeout:120000});
 const route=await call('check_geometry',{clearances:structureRouteClearances()});for(const k of['collisions','gaps','unsupported','warnings'])assert.deepEqual(route[k],[]);assert.ok(route.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));assert.ok(route.clearances.every((c:any)=>c.clear));report.route=route;const builtDoc=await state();assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets)),hash(builtDoc.assets));await page.screenshot({path:path.join(out,'mcp-structure-route.png')});
 const mismatch=await raw('edit_transaction',{expectedVersion:builtDoc.version,requestId:crypto.randomUUID(),commands:[{op:'produceCatalogAsset',catalogId:'BUILT-007',id:'narrow'},{op:'connect',id:'bad-join',assetId:'narrow',portId:'bottom-walkway',targetInstanceId:'wing-1',targetPortId:'lower-flight',rotation:0}]});assert.ok(mismatch.isError);assert.equal(hash(await state()),hash(builtDoc));report.checks.push('MCP assembles four catalogue masters plus one support master as six placements; 18 human envelopes have 1.9m clearance, no collision/gap or unsupported objects; incompatible 1.2m/1.6m port transaction rolls back');
 const exported=await call('export_project',{name:'structure-route'}),round=JSON.parse(await readFile(path.join(exported.directory,'voxels.ysvox.json'),'utf8'));for(const k of['assets','instances','styles','materials']as const)assert.equal(hash(round[k]),hash(builtDoc[k]));report.export=exported;await cp(exported.directory,path.join(out,'structure-route-export'),{recursive:true});const views=await call('generate_previews',{appearance:'baseColor',views:['isometric','front']});assert.equal(views.files.length,2);report.previews=views;for(let i=0;i<views.files.length;i++){assert.ok((await readFile(views.files[i])).length>1000);await copyFile(views.files[i],path.join(out,'structure-route-view-'+i+'.png'));}report.checks.push('Actual multi-view previews and GLB/collision/interfaces/native exports preserve the assembled route and material identities');
 const savedFile=await call('save_project',{filename:'structure-route.ysvox.json'}),saved=await state();assert.equal(hash(JSON.parse(await readFile(savedFile.path,'utf8'))),hash(saved));await copyFile(savedFile.path,path.join(out,'structure-route.ysvox.json'));await stop();await start();assert.equal(hash(await state()),hash(saved));report.checks.push('Native save and server restart restore the exact canonical document');
 assert.deepEqual(report.errors,[]);report.status='passed';report.completedAt=new Date().toISOString();console.log(JSON.stringify({status:report.status,checks:report.checks.length,out}));
}catch(error){report.status='failed';report.errors.push(String(error));throw error;}finally{await browser?.close();await client?.close();await stop();await writeFile(path.join(out,'structure-mcp-verification.json'),JSON.stringify(report,null,2));await writeFile(path.join(out,'structure-mcp-server.log'),log);}
