import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';import path from 'node:path';import {spawn} from 'node:child_process';import {once} from 'node:events';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {chromium} from 'playwright';import {validationBrowserOptions} from './browser-options';import {hydrologyCloseRegions} from './hydrology-view-regions';
const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),out=latest.evidence,runtime=path.join(out,'hydrology-downstream-'+Date.now()+'-runtime'),url='http://127.0.0.1:4365',specs=[...['ENV-026','ENV-032'].map(id=>({file:latest.models.find((r:any)=>r.id===id).file,id:id.toLowerCase(),shot:'terrain-'+id.toLowerCase()+'-downstream.png'})),...['hydrology-cascades','hydrology-fall-pool'].map(id=>({file:id+'.ysvox.json',id:null,shot:id+'-view-4.png'}))];
await mkdir(runtime,{recursive:true});for(const f of['atlas-production-index.json','production-index.json'])await copyFile(path.join('projects',f),path.join(runtime,f));await cp('projects/reference-atlas',path.join(runtime,'reference-atlas'),{recursive:true});for(const x of specs)await copyFile(path.join(x.id?'projects':out,x.file),path.join(runtime,x.file));await copyFile(path.join(runtime,specs[0].file),path.join(runtime,'autosave.ysvox.json'));
const server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4365',VOXEL_PROJECT_DIR:runtime},stdio:'ignore'});let browser;const records=[];
try{for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}browser=await chromium.launch(validationBrowserOptions());const page=await browser.newPage({viewport:{width:1600,height:1050}}),errors:string[]=[];page.setDefaultTimeout(120000);page.on('pageerror',e=>errors.push(e.message));await page.goto(url+'/?asset=env-026&view=back');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready,null,{timeout:120000});const call=async(name:string,args:any)=>{const r=await fetch(url+'/api/tool',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,arguments:args})});const data=await r.json();assert.ok(r.ok,JSON.stringify(data));return data;};
for(const spec of specs){const before=(await fetch(url+'/api/state').then(r=>r.json())).project,loaded=await call('load_project',{filename:spec.file,expectedVersion:before.version});await page.waitForFunction(v=>(window as any).voxelStudio.performance.renderedVersion===v,loaded.version,{timeout:120000});let canonical=(await fetch(url+'/api/state').then(r=>r.json())).project;if(spec.id){const req={expectedVersion:canonical.version,requestId:crypto.randomUUID(),commands:[{op:'palette',name:'参考材质试作'}]},dry=await call('edit_transaction',{...req,dryRun:true}),done=await call('edit_transaction',{...req,previewToken:dry.previewToken});await page.waitForFunction(v=>(window as any).voxelStudio.performance.renderedVersion===v,done.version,{timeout:120000});}
await page.evaluate(async id=>{const s=(window as any).voxelStudio;await s.mode(id?'asset':'scene',id??undefined);s.view('back');s.clay(false);s.studio(true);s.timeOfDay('day');await s.meshMode('far');},spec.id);const box=(await page.locator('#viewport canvas').boundingBox())!,cx=box.x+box.width/2,cy=box.y+box.height/2;await page.mouse.move(cx,cy);await page.mouse.down();await page.mouse.move(cx-box.height/8,cy+box.height/8,{steps:12});await page.mouse.up();await page.evaluate("new Promise(resolve=>{let count=0;function tick(){if(++count>=60)resolve();else requestAnimationFrame(tick);}requestAnimationFrame(tick);})");if(spec.id)await page.evaluate(region=>(window as any).voxelStudio.focus(region),hydrologyCloseRegions[spec.id]);else{await page.mouse.wheel(0,400);await page.evaluate("new Promise(resolve=>{let count=0;function tick(){if(++count>=40)resolve();else requestAnimationFrame(tick);}requestAnimationFrame(tick);})");}await page.locator('#viewport').screenshot({path:path.join(out,spec.shot)});const after=(await fetch(url+'/api/state').then(r=>r.json())).project;assert.deepEqual(after.assets,canonical.assets);records.push({file:spec.shot,source:spec.file,assetId:spec.id,view:'downstream oblique: back view then +45 degree elevation and 45 degree orbit',appearance:'reference material',nativeGeometryUnchanged:true,sha256:createHash('sha256').update(await readFile(path.join(out,spec.shot))).digest('hex')});console.log('OBLIQUE',spec.shot);}
assert.deepEqual(errors,[]);const proof=JSON.parse(await readFile(path.join(out,'camera-framing-verification.json'),'utf8'));assert.equal(proof.status,'passed');proof.downstreamOblique=records;await writeFile(path.join(out,'camera-framing-verification.json'),JSON.stringify(proof,null,2));
}finally{await browser?.close();if(server.exitCode===null){const closed=once(server,'exit');server.kill('SIGTERM');await closed;}}
