import {referenceFinishCommands} from '../src/production/reference-finish';
import {environmentAudit} from './lib/environment-audit';
import {lifeSpaceAudit} from './lib/life-space-audit';
import assert from 'node:assert/strict';import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';import {spawn,type ChildProcess} from 'node:child_process';import {once} from 'node:events';import {Client} from '@modelcontextprotocol/sdk/client/index.js';import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';import {chromium} from 'playwright';import {validationBrowserOptions} from './browser-options';import {productionProject} from '../src/production/style';import {parseCatalogCSV} from '../src/core/catalog';import {Grid} from '../src/core/grid';import {CivicAudit,civicStairClearance,civicSupports} from './lib/civic-audit';import {regionalClearance,terrainSeams} from './lib/regional-audit';import {terrainAuthorityInstances} from '../src/export/terrain-authority';import type {Project} from '../src/core/types';
const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),out=latest.evidence,runtime=path.join(out,'life-space-mcp-runtime'),url='http://127.0.0.1:4399',rows=index.entries.filter((r:any)=>r.sheet==='M053'),hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex');assert.equal(rows.length,12);
await mkdir(runtime,{recursive:true});for(const file of['atlas-production-index.json','production-index.json','architecture-index.json','material-index.json',...rows.map((r:any)=>r.file)])await copyFile('projects/'+file,runtime+'/'+file);await cp('projects/reference-atlas',runtime+'/reference-atlas',{recursive:true});await copyFile('projects/'+rows.find((r:any)=>r.id==='LIFE-062').file,runtime+'/autosave.ysvox.json');const empty=productionProject('M053 MCP author assembly');empty.catalog={sourceName:'catalog',importedAt:latest.createdAt,entries:Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]))};await writeFile(runtime+'/empty.ysvox.json',JSON.stringify(empty));
let server:ChildProcess|undefined,client:Client|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,log='';const report:any={run:latest.run,status:'running',checks:[],errors:[],views:[],notifications:[]},state=async():Promise<Project>=>(await fetch(url+'/api/state').then(r=>r.json())).project;
async function start(){server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4399',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok)return;}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}throw new Error('startup timeout');}async function stop(){if(server&&server.exitCode===null){const closed=once(server,'exit');server.kill();await closed;}}
try{
 await start();client=new Client({name:'architecture-assemblies-verification',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],cwd:process.cwd(),env:{...process.env as Record<string,string>,VOXEL_URL:url},stderr:'pipe'}));const raw=async(name:string,args:any={})=>{const r:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(name,r.isError?'ERROR':'OK');return{...JSON.parse(r.content[0].text),isError:!!r.isError};},call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 browser=await chromium.launch(validationBrowserOptions());report.browser=browser.version();const page=await browser.newPage({viewport:{width:1400,height:1000}});page.setDefaultTimeout(120000);page.on('pageerror',e=>report.errors.push(e.message));page.on('websocket',socket=>socket.on('framereceived',f=>{const n=JSON.parse(f.payload.toString());report.notifications.push({event:n.event,version:n.version,bytes:Buffer.byteLength(f.payload.toString()),fullProject:!!n.project});}));await page.goto(url+'/?atlas=1&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready);const sync=async(v:number)=>page.waitForFunction(n=>(window as any).voxelStudio.performance.renderedVersion===n,v),frames=async()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));report.webgl=await page.evaluate(()=>{const g=(document.querySelector('#viewport canvas')as HTMLCanvasElement).getContext('webgl2')!,e=g.getExtension('WEBGL_debug_renderer_info');return g.getParameter(e?.UNMASKED_RENDERER_WEBGL??g.RENDERER);});

 const lib=await call('read_production_library',{query:'LIFE-062'});assert.equal(lib.counts.atlasReferenceCandidates,636);assert.equal(lib.counts.atlasAssemblyCandidates,120);assert.equal(lib.counts.atlasUniqueMasters,513);assert.equal(lib.counts.baseModels,532);const recipes=await call('list_production_recipes',{query:'LIFE-062',limit:100});assert.deepEqual(recipes.entries.find((r:any)=>r.id==='LIFE-062').parameters,{privacyDoor:{enum:['open','closed'],default:'open'}});report.libraryCounts=lib.counts;report.checks.push('Official MCP exposes636 references,120 atlas assemblies,513 unique atlas masters and public privacy-door states');
 const schemas=await client.listTools();await writeFile('docs/tool-schemas.json',JSON.stringify(schemas.tools,null,2));
 await page.locator('#atlas-sheet').selectOption('M053');await page.locator('[data-atlas-open][data-catalog="LIFE-128"]').first().click();await page.waitForFunction(()=>Object.values((window as any).voxelStudio.project.assemblies??{}).some((a:any)=>a.source?.catalogId==='LIFE-128'));await sync((await state()).version);report.checks.push('Actual atlas button opens the complete six-station classroom');
 const edit=async(commands:any[])=>{const req={expectedVersion:(await state()).version,requestId:crypto.randomUUID(),commands},d=await call('edit_transaction',{...req,dryRun:true}),r=await call('edit_transaction',{...req,previewToken:d.previewToken});await sync(r.version);return r;};
 const capture=async(key:string,view='isometric')=>{await page.evaluate(async view=>{const v=(window as any).voxelStudio;await v.mode('scene');v.view(view);v.clip(Infinity);v.clay(false);v.studio(true);v.ao(false);v.bloom(false);},view);await frames();await page.locator('#viewport').screenshot({path:out+'/assembly-'+key+'.png'});const perf=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.equal(perf.meshError,null);report.views.push({key,file:'assembly-'+key+'.png',triangles:perf.triangles});return perf;};
 for(const id of ['LIFE-062','LIFE-102','LIFE-104','LIFE-128']){const loaded=await call('load_project',{filename:rows.find((r:any)=>r.id===id).file,expectedVersion:(await state()).version});await sync(loaded.version);await edit([...referenceFinishCommands(await state()),{op:'palette',name:'参考材质试作'}]);await capture(id+'-top','top');}
 report.checks.push('Additional real browser plan views cover bathroom, restaurant kitchen, warehouse and complete classroom');
 const loaded=await call('load_project',{filename:'empty.ysvox.json',expectedVersion:(await state()).version});await sync(loaded.version);const before=await state(),req={expectedVersion:before.version,requestId:crypto.randomUUID(),commands:[{op:'produceCatalogAssembly',catalogId:'LIFE-062',id:'bath',place:true,params:{privacyDoor:'closed'}}]},dry=await call('edit_transaction',{...req,dryRun:true});assert.equal(hash(await state()),hash(before));const made=await call('edit_transaction',{...req,previewToken:dry.previewToken});await sync(made.version);assert.equal((await call('edit_transaction',req)).version,made.version);assert.equal((await raw('edit_transaction',{...req,requestId:crypto.randomUUID()})).code,'VERSION_CONFLICT');const bath=await state(),audit=lifeSpaceAudit(bath,bath.assemblies!.bath);assert.equal(audit.door!.state,'closed');assert.equal(audit.door!.entry.clear,false);assert.equal(audit.door!.occluded,true);assert.ok(audit.drain!.clear&&audit.basin!.clear);report.bathroom=audit;const bad=await raw('edit_transaction',{expectedVersion:bath.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:bath.styles.yunshan.wood,properties:{color:'#112233'}},{op:'produceCatalogAssembly',catalogId:'LIFE-062',id:'bad',params:{privacyDoor:'automatic'}}]});assert.ok(bad.isError);assert.equal(hash(await state()),hash(bath));assert.ok((await raw('edit_transaction',{expectedVersion:bath.version,requestId:crypto.randomUUID(),commands:[{op:'produceCatalogAsset',catalogId:'LIFE-062',id:'wrong-type'}]})).isError);assert.equal(hash(await state()),hash(bath));await capture('closed-privacy-door');report.checks.push('Public creation, dry-run, CAS and idempotency; invalid door state rolls back prior material edit; closed leaf blocks entry while drain and basin stay open');
 await edit([{op:'undo'}]);for(const k of['assets','instances','assemblies','materials']as const)assert.deepEqual((await state())[k],before[k]);await edit([{op:'produceCatalogAssembly',catalogId:'LIFE-097',id:'meal',place:true}]);const meal=await state(),grain=meal.assets['architecture-food-rice'],pin=[...new Grid(grain.chunks).cells()][0],query=await call('query_voxels',{assetId:grain.id,region:{min:pin[0],max:pin[0].map(v=>v+1)}});assert.equal(query.cells[0][1],meal.styles.yunshan.grainPale);assert.equal(grain.cellSize,.005);
 await edit([{op:'definePalette',name:'M053用途检查',materials:{[meal.styles.yunshan.grainPale]:{color:'#e6c173'},[meal.styles.yunshan.ceramicTeal]:{color:'#31546a'}}},{op:'palette',name:'M053用途检查'}]);const after=await state();for(const k of['assets','assemblies','instances','styles']as const)assert.deepEqual(after[k],meal[k]);assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(after.materials));await capture('rice-material-separation');await edit([{op:'undo'}]);assert.deepEqual((await state()).materials,meal.materials);report.checks.push('Real5mm rice-cell query and independent rice/ceramic appearance edits sync to WebGL and undo without geometric change');
 const prior=hash(await state());report.details=[];for(const mode of ['far','near']){await page.evaluate(async mode=>(window as any).voxelStudio.meshMode(mode),mode);await frames();const perf=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.equal(perf.meshMode,mode);report.details.push({mode,triangles:perf.triangles});}assert.equal(hash(await state()),prior);report.checks.push('Actual near/far/near switches keep saved authoritative geometry unchanged');
 await edit([{op:'instantiateAssembly',assemblyId:'meal',prefix:'quarter',position:[1.5,0,1.5],rotation:1}]);const placed=await state();assert.equal(Object.keys(placed.instances).length,2*Object.keys(meal.instances).length);await capture('quarter-turn-meal');const exported=await call('export_project',{name:'life-space-quarter-turn-'+Date.now()}),native=JSON.parse(await readFile(exported.directory+'/voxels.ysvox.json','utf8'));for(const k of['assets','instances','assemblies','styles']as const)assert.deepEqual(native[k],placed[k]);report.export=exported;await edit([{op:'undo'}]);assert.deepEqual((await state()).instances,meal.instances);report.checks.push('Whole meal quarter-turn placement exports exact native definitions and one undo restores scene');
 const classroomLoad=await call('load_project',{filename:rows.find((r:any)=>r.id==='LIFE-128').file,expectedVersion:(await state()).version});await sync(classroomLoad.version);const doc=await state(),classroom=lifeSpaceAudit(doc,doc.assemblies!['life-128']);assert.equal(classroom.students.length,6);assert.ok(classroom.students.every((r:any)=>r.seatPresent&&r.deskPresent&&r.body.clear&&r.approach.clear));report.classroom=classroom;report.checks.push('Reloaded native classroom verifies seated bodies against own complete desk/chair geometry');
 const saved=await call('save_project',{filename:'verified-assembly.ysvox.json'});assert.equal(hash(JSON.parse(await readFile(saved.path,'utf8'))),hash(doc));await stop();await start();assert.equal(hash(await state()),hash(doc));report.checks.push('Native save and actual server restart preserve exact source provenance, components, materials and assembly definitions');assert.ok(report.notifications.length>=10);assert.ok(report.notifications.every((n:any)=>n.event==='state-invalidated'&&!n.fullProject&&n.bytes<65536));assert.deepEqual(report.errors,[]);report.status='passed';console.log(JSON.stringify({status:report.status,checks:report.checks.length}));
}catch(e){report.status='failed';report.errors.push(String(e));throw e;}finally{await browser?.close();await client?.close();await stop();await writeFile(out+'/assembly-mcp-verification.json',JSON.stringify(report,null,2));await writeFile(out+'/assembly-mcp-server.txt',log);}
