import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';import path from 'node:path';import {spawn,type ChildProcess} from 'node:child_process';import {once} from 'node:events';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {validationBrowserOptions} from './browser-options';
const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),out=latest.evidence,runtime=path.join(out,'groundscape-details-'+Date.now()+'-runtime'),url='http://127.0.0.1:4375',specs=[
 {scene:'groundscape-ponds',asset:'pond-union-1',view:'isometric',min:[-15,0,-15],max:[15,15,15],file:'groundscape-ponds-view-3.png',detail:'Deep authored static pond: actual displaced water, bed contact, petioles and leaves'},
 {scene:'groundscape-walls',asset:'cap-1',view:'left',min:[0,-1,-1],max:[40,3,9],file:'groundscape-walls-view-3.png',detail:'Isolated cap end face: real stepped underside exposes both drip grooves and the central bearing strip'},
 {scene:'groundscape-walls',asset:'sleeve-1',view:'front',min:[0,0,-1],max:[3,3,12],file:'groundscape-walls-view-4.png',detail:'Isolated weep sleeve: actual 0.2m through bore, no rendered plug'},
 {scene:'groundscape-litter',asset:'log',view:'left',min:[-1,0,-5],max:[8,9,6],file:'groundscape-litter-view-3.png',detail:'End-on hollow log: native open bore, cut heartwood and separate bark'}
];
async function readyFile(name:string){for(let i=0;i<1200;i++){try{return JSON.parse(await readFile(path.join(out,name),'utf8'));}catch{}let status;try{status=JSON.parse(await readFile(path.join(out,'groundscape-mcp-verification.json'),'utf8')).status;}catch{}assert.notEqual(status,'failed','Main groundscape MCP verification failed');await new Promise(r=>setTimeout(r,1000));}throw new Error('Missing verified scene '+name);}
await readyFile('groundscape-ponds.ysvox.json');await mkdir(runtime,{recursive:true});await copyFile(path.join(out,'groundscape-ponds.ysvox.json'),path.join(runtime,'autosave.ysvox.json'));let server:ChildProcess|undefined,browser;const onlyAsset=process.argv.find(a=>a.startsWith('--asset='))?.slice(8),prior=onlyAsset?JSON.parse(await readFile(path.join(out,'camera-framing-verification.json'),'utf8')):null;if(prior){assert.equal(prior.run,latest.run);assert.equal(prior.status,'passed');}const records:any[]=prior?prior.sceneSupplement.filter((r:any)=>r.asset!==onlyAsset):[],errors:string[]=[];if(onlyAsset)assert.ok(specs.some(s=>s.asset===onlyAsset));
try{server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4375',VOXEL_PROJECT_DIR:runtime},stdio:'ignore'});for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}browser=await chromium.launch(validationBrowserOptions());const page=await browser.newPage({viewport:{width:1400,height:1050}});page.setDefaultTimeout(120000);page.on('pageerror',e=>errors.push(e.message));await page.goto(url+'/?preview=1&asset=pond-union-1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready);
for(const spec of specs.filter(s=>!onlyAsset||s.asset===onlyAsset)){const saved=await readyFile(spec.scene+'.ysvox.json');await copyFile(path.join(out,spec.scene+'.ysvox.json'),path.join(runtime,spec.scene+'.ysvox.json'));const current=(await fetch(url+'/api/state').then(r=>r.json())).project,response=await fetch(url+'/api/tool',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'load_project',arguments:{filename:spec.scene+'.ysvox.json',expectedVersion:current.version}})});assert.ok(response.ok);const loaded=await response.json();await page.waitForFunction(v=>(window as any).voxelStudio.performance.renderedVersion===v,loaded.version);await page.evaluate(async spec=>{const s=(window as any).voxelStudio;await s.mode('asset',spec.asset);s.view(spec.view);s.clay(false);s.studio(true);s.timeOfDay('day');await s.meshMode('far');s.focus({min:spec.min,max:spec.max});},spec);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.locator('#viewport').screenshot({path:path.join(out,spec.file)});const after=(await fetch(url+'/api/state').then(r=>r.json())).project;for(const k of['assets','instances','styles','materials'])assert.deepEqual(after[k],saved[k]);records.push({...spec,view:spec.view,appearance:'stored reference material',meshMode:'far',nativeGeometryUnchanged:true,sha256:createHash('sha256').update(await readFile(path.join(out,spec.file))).digest('hex')});console.log('DETAIL',spec.file);}
assert.deepEqual(errors,[]);await writeFile(path.join(out,'camera-framing-verification.json'),JSON.stringify({status:'passed',run:latest.run,reason:'Supplementary views expose actual aquatic root/water installation, cap end-face drip grooves, the narrow weep bore, and the hollow-log end. Cap and sleeve are inspected as components; full installed walls are in the main MCP scenes.',browser:browser.version(),sceneSupplement:records,errors},null,2));
}finally{await browser?.close();if(server&&server.exitCode===null){const closed=once(server,'exit');server.kill('SIGTERM');await closed;}}
