import {spawn,type ChildProcess} from 'node:child_process';
import {mkdir,writeFile,readFile,cp,rename,symlink,unlink} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {chromium} from 'playwright';
import {adversarialOBJ} from '../tests/fixtures';
import {Engine} from '../src/core/engine';
import {demoProject} from '../src/core/demo';
import {meshAsset,meshChunk} from '../src/core/mesh';
import {Grid} from '../src/core/grid';
import {loadMesh} from '../src/import/converter';
import type {Project,Command,Envelope} from '../src/core/types';
const base=process.cwd(),runId=new Date().toISOString().replace(/[:.]/g,'-'),runRoot=path.join(base,'artifacts','run-'+runId),port=4327,url=`http://127.0.0.1:${port}`;
await mkdir(runRoot,{recursive:true});await mkdir('projects/fixtures',{recursive:true});
const results:any={startedAt:new Date().toISOString(),environment:{platform:os.platform(),arch:os.arch(),osRelease:os.release(),cpu:os.cpus()[0].model,logicalCPUs:os.cpus().length,totalMemoryGiB:os.totalmem()/1024**3,node:process.version},checks:[],measurements:{},artifacts:{runRoot},limitations:['浏览器数值来自本机无头 Chromium，不能代表所有 GPU。','三角形体素化保留表面格，低于格距的缝隙仍可能闭合。']};
let server:ChildProcess;function start(){server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{cwd:base,env:{...process.env,VOXEL_PORT:String(port),VOXEL_PROJECT_DIR:runRoot},stdio:['ignore','pipe','pipe']});let log='';server.stdout!.on('data',x=>{log+=x;});server.stderr!.on('data',x=>{log+=x;});server.on('exit',()=>void writeFile(path.join(runRoot,'server.log'),log));}
async function waitServer(){for(let i=0;i<100;i++){try{const r=await fetch(url+'/api/state');if(r.ok)return await r.json();}catch{}await new Promise(r=>setTimeout(r,100));}throw new Error('服务器启动超时');}
async function stop(){if(server.exitCode!==null)return;server.kill('SIGTERM');await new Promise<void>(resolve=>server.once('exit',()=>resolve()));}
const http=async(route:string,body?:any)=>{const r=await fetch(url+route,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),result=await r.json();if(!r.ok)throw Object.assign(new Error(result.error),result);return result;};
const snapshot=(p:Project)=>{const q=structuredClone(p);q.version=0;q.modifiedAt='';for(const a of Object.values(q.assets))a.version=0;return createHash('sha256').update(JSON.stringify(q)).digest('hex');};
start();await waitServer();const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1600,height:1080}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
const client=new Client({name:'yunshan-real-verifier',version:'1.0.0'});const transport=new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],cwd:base,env:{...Object.fromEntries(Object.entries(process.env).filter(([,v])=>typeof v==='string')) as Record<string,string>,VOXEL_URL:url},stderr:'pipe'});
await client.connect(transport);
async function mcp(name:string,args:any={},expectError=false){const r:any=await client.callTool({name,arguments:args});const value=JSON.parse(r.content[0].text);if(expectError){assert.ok(r.isError,JSON.stringify(value));return value;}if(r.isError)throw new Error(JSON.stringify(value));return value;}
async function transaction(commands:Command[],label='验证事务'){const state=await mcp('read_project',{includeVoxels:false}),e:Envelope={expectedVersion:state.version,requestId:crypto.randomUUID(),commands,label};const preview=await mcp('edit_transaction',{...e,dryRun:true});return{preview,result:await mcp('edit_transaction',{...e,previewToken:preview.previewToken}),envelope:e};}
const record=(name:string,details:any={})=>{results.checks.push({name,passed:true,...details});console.log('PASS',name);};
try{
 const tools=await client.listTools();assert.ok(tools.tools.length>=13);record('MCP SDK stdio 协议真实握手 / 工具发现',{toolCount:tools.tools.length});
 const loadStart=performance.now();await page.goto(url);await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready,{}, {timeout:60000});results.measurements.initialBrowserReadyMs=performance.now()-loadStart;results.environment.browser=browser.version();results.environment.webgl=await page.evaluate(()=>{const gl=(document.querySelector('#viewport canvas') as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return{renderer:gl.getParameter(ext?.UNMASKED_RENDERER_WEBGL??gl.RENDERER),vendor:gl.getParameter(ext?.UNMASKED_VENDOR_WEBGL??gl.VENDOR),version:gl.getParameter(gl.VERSION)};});await page.waitForTimeout(1500);await page.screenshot({path:'artifacts/editor-exterior.png'});
 const before:Project=await mcp('read_project',{includeVoxels:true}),beforeHash=snapshot(before);const listed=await mcp('list_assets');assert.equal(listed.counts.uniqueAssets,15);assert.equal(listed.counts.placements,16);assert.equal(listed.counts.assemblies,1);record('母版 / 组合模板 / 配色 / 放置实例分开计数',listed.counts);
 const checked=await mcp('check_geometry',{clearances:[{name:'门洞通行',min:[.8,.6,-.6],max:[2.2,2.8,.4]},{name:'首阶上方 2m',min:[.8,.2,-1.2],max:[2.2,2.2,-.8]},{name:'最高阶上方 2m',min:[.8,.6,-.4],max:[2.2,2.6,0]}]});assert.equal(checked.collisions.length,0);assert.equal(checked.unsupported.length,0);assert.ok(checked.clearances.every((x:any)=>x.clear));assert.ok(checked.openings.every((x:any)=>!x.blockedBy.length));record('民居碰撞 / 支撑 / 门窗 / 楼梯净空',checked);await writeFile('artifacts/house-geometry.json',JSON.stringify(checked,null,2));
 await page.click('#clip');await page.waitForTimeout(300);await page.screenshot({path:'artifacts/editor-cutaway.png'});await page.click('#clip');
 const commands:Command[]=[{op:'regenerate',assetId:'window',params:{openingWidth:2.2}},{op:'assignMaterial',assetId:'sidewall',fromMaterial:2,material:1},{op:'assignMaterial',assetId:'backwall',fromMaterial:2,material:1},{op:'instance',id:'planter-mcp',assetId:'planter',position:[2.8,0,-1.1],rotation:0},{op:'material',id:11,properties:{color:'#72aaff',emissive:'#72aaff',intensity:.8}}];
 const batch=await transaction(commands,'MCP · 加宽窗户 / 石墙 / 复制花槽 / 调整灯带');await page.waitForFunction(v=>(window as any).voxelStudio.version===v&&!!(window as any).voxelStudio.ready,batch.result.version);assert.equal(await page.evaluate(()=>(window as any).voxelStudio.project.assets.window.template.params.openingWidth),2.2);assert.ok(await page.evaluate(()=>(window as any).voxelStudio.project.instances['planter-mcp']));await page.waitForTimeout(500);await page.screenshot({path:'artifacts/mcp-batch-applied.png'});record('MCP 一批修改同步可视化界面',batch.result);
 const repeated=await mcp('edit_transaction',{...batch.envelope,previewToken:batch.preview.previewToken});assert.equal(repeated.version,batch.result.version);record('幂等请求不重复创建实例');
 const conflict=await mcp('edit_transaction',{...batch.envelope,requestId:'stale-version'},true);assert.equal(conflict.code,'VERSION_CONFLICT');record('版本冲突被拒绝');
 const undo=await transaction([{op:'undo'}],'撤销 MCP 整批');assert.equal(snapshot(await mcp('read_project',{includeVoxels:true})),beforeHash);await page.waitForFunction(v=>(window as any).voxelStudio.version===v,undo.result.version);await page.waitForTimeout(350);await page.screenshot({path:'artifacts/mcp-batch-undone.png'});record('一次撤销恢复整批体素 / 材质 / 实例');
 const rollbackBefore=await mcp('read_project',{includeVoxels:true}),rollback=await mcp('edit_transaction',{expectedVersion:rollbackBefore.version,requestId:'rollback-case',commands:[{op:'voxels',assetId:'window',mode:'add',cells:[[40,0,0]],material:2},{op:'assignMaterial',assetId:'window',material:999}]},true);assert.equal(snapshot(await mcp('read_project',{includeVoxels:true})),snapshot(rollbackBefore));record('后续命令失败回滚前序修改',rollback);
 const q=await mcp('query_voxels',{assetId:'window',region:{min:[0,0,0],max:[30,30,2]},offset:0,limit:10});assert.equal(q.cells.length,10);assert.ok(q.nextOffset);const mats=await mcp('query_materials_interfaces',{assetId:'window'});assert.equal(mats.assets[0].ports.length,4);record('体素分页查询 / 材质 / 层级 / 接口读取');
 const malformed=await mcp('edit_transaction',{expectedVersion:rollbackBefore.version,requestId:'bad',commands:[{op:'voxels',assetId:'window',mode:'fill',region:{min:[0,0,0],max:[300,300,300]},material:2}]},true);assert.match(malformed.error,/候选格/);record('异常区域 / 输入预算拒绝');
 const badpath=await mcp('save_project',{filename:'../../outside.ysvox.json'},true);assert.equal(badpath.code,'INVALID_INPUT');const crossOrigin=await fetch(url+'/api/state',{headers:{Origin:'https://untrusted.example'}});assert.equal(crossOrigin.status,403);record('目录越界及跨来源 HTTP 拒绝');
 const saved=await mcp('save_project',{filename:'verified-house.ysvox.json'});const savedProject=JSON.parse(await readFile(saved.path,'utf8'));assert.equal(snapshot(savedProject),beforeHash);await cp(saved.path,'projects/verified-house.ysvox.json');record('原生另存为保持全部内容');
 const diskBefore=await mcp('read_project',{includeVoxels:true});await rename(path.join(runRoot,'autosave.ysvox.json'),path.join(runRoot,'autosave-backup.json'));await symlink('blocked-save-target',path.join(runRoot,'autosave.ysvox.json'));
 try{const failure=await mcp('edit_transaction',{expectedVersion:diskBefore.version,requestId:'disk-write-fail',commands:[{op:'renameProject',name:'must-roll-back'}]},true);assert.match(failure.error,/符号链接/);assert.equal(snapshot(await mcp('read_project',{includeVoxels:true})),snapshot(diskBefore));}finally{await unlink(path.join(runRoot,'autosave.ysvox.json'));await rename(path.join(runRoot,'autosave-backup.json'),path.join(runRoot,'autosave.ysvox.json'));}record('自动保存失败回滚内存文档与历史');
 const exported=await mcp('export_project',{name:'verified-house'});await cp(exported.directory,'projects/exports/verified-house',{recursive:true});const glb=await readFile(path.join(exported.directory,'visual.glb')),reimported=await loadMesh({filename:'visual.glb',data:glb.toString('base64')});const reeditable=JSON.parse(await readFile(path.join(exported.directory,'voxels.ysvox.json'),'utf8'));assert.equal(snapshot(reeditable),beforeHash);assert.ok(Math.abs(reimported.bounds.min[2]+1.2)<1e-6);assert.ok(Math.abs(reimported.bounds.max[0]-6.4)<1e-6);record('GLB 重导入坐标 / 开放体素无损重载',{glbBytes:glb.length,boundsM:reimported.bounds,sourceTriangles:reimported.triangles.length});
 const text=adversarialOBJ();await writeFile('projects/fixtures/bonded-thin-holes.obj',text);const upload=await http('/api/upload',{filename:'bonded-thin-holes.obj',data:Buffer.from(text).toString('base64')});
 const importOptions={sourceId:upload.sourceId,name:'粘连薄壁孔洞案例',origin:[0,0,0],scale:1,upAxis:'Y',mode:'surface',colorMode:'sample',material:2,thinPolicy:'conservative',expectedVersion:rollbackBefore.version};
 async function jobDone(id:string){for(let i=0;i<400;i++){const job=await mcp('job_status',{jobId:id});if(job.status!=='running')return job;await new Promise(r=>setTimeout(r,25));}throw new Error('导入超时');}
 const loaded=await loadMesh({filename:'bonded-thin-holes.obj',data:Buffer.from(text).toString('base64')});results.imports=[];
 for(const pitch of[.1,.05]){const job=await mcp('import_mesh',{...importOptions,cellSize:pitch,requestId:'convert-'+pitch}),done=await jobDone(job.id);assert.equal(done.status,'completed',done.error);const r=done.result;assert.ok(r.diagnostics.duplicateFaces>0);results.imports.push({pitch,diagnostics:r.diagnostics,comparison:r.comparison,performance:r.performance});await writeFile(`projects/fixtures/result-${pitch}.json`,JSON.stringify(r,null,2));await page.evaluate(async({triangles,asset,materials})=>{await (window as any).showVoxelComparison(triangles,asset,materials);},{triangles:loaded.triangles.map(t=>({points:t.points,color:t.color})),asset:r.asset,materials:r.materials});await page.waitForTimeout(400);await page.screenshot({path:`artifacts/import-compare-${pitch}.png`});if(pitch===.05){const preview=await mcp('commit_import',{jobId:job.id,expectedVersion:rollbackBefore.version,requestId:'commit-fixture',dryRun:true});const commit=await mcp('commit_import',{jobId:job.id,expectedVersion:rollbackBefore.version,requestId:'commit-fixture',previewToken:preview.previewToken});assert.equal(commit.version,rollbackBefore.version+1);await transaction([{op:'undo'}],'撤销导入测试');}}
 assert.ok(results.imports[1].performance.voxels>results.imports[0].performance.voxels);record('同源缺陷网格双格距转换 / 可视对照 / 导入事务');
 let state=await mcp('read_project');const failureStart=await mcp('import_mesh',{...importOptions,cellSize:.1,expectedVersion:state.version,mode:'solid',requestId:'solid-failure'}),failure=await jobDone(failureStart.id);assert.equal(failure.status,'failed');assert.match(failure.error,/拒绝/);await writeFile('projects/fixtures/solid-failure.json',JSON.stringify(failure,null,2));record('非封闭粘连网格拒绝实体填充并保留失败证据',{error:failure.error});
 // 60k triangles make a real worker job long enough to cancel, without mutating the document.
 const largeOBJ=text+Array(20000).fill('f 1 2 3\nf 4 5 6\n').join(''),largeUpload=await http('/api/upload',{filename:'cancel-long.obj',data:Buffer.from(largeOBJ).toString('base64')}),beforeCancel=snapshot(await mcp('read_project',{includeVoxels:true}));state=await mcp('read_project');const longJob=await mcp('import_mesh',{...importOptions,sourceId:largeUpload.sourceId,cellSize:.01,expectedVersion:state.version,requestId:'long-conversion'}),cancelStart=performance.now(),cancelled=await mcp('cancel_job',{jobId:longJob.id});assert.equal(cancelled.status,'cancelled');assert.equal(snapshot(await mcp('read_project',{includeVoxels:true})),beforeCancel);record('取消真实后台长任务不修改文档',{cancelRoundtripMs:performance.now()-cancelStart});
 await page.reload();await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready);await page.click('#asset-mode');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready);await page.click('#set-region');await page.waitForTimeout(250);await page.click('[data-tool="fill"]');await page.locator('.modal h2').filter({hasText:'检查这次修改'}).waitFor();const uiBefore=await mcp('read_project',{includeVoxels:true});await page.getByRole('button',{name:'取消',exact:true}).click();assert.equal(snapshot(await mcp('read_project',{includeVoxels:true})),snapshot(uiBefore));record('界面大选区预览取消保持文档');
 // Actual brush click against a rendered asset, followed by undo.
 await page.click('[data-tool="brush"]');const viewport=await page.locator('#viewport').boundingBox();const preBrush=await mcp('read_project',{includeVoxels:true});await page.mouse.click(viewport!.x+viewport!.width*.5,viewport!.y+viewport!.height*.54);await page.waitForFunction(v=>(window as any).voxelStudio.version>v,preBrush.version,{timeout:10000});const postBrush=await mcp('read_project',{includeVoxels:true});assert.notEqual(snapshot(postBrush),snapshot(preBrush));await transaction([{op:'undo'}],'撤销浏览器笔刷');record('浏览器按格笔刷真实写回共享文档');
 await page.evaluate(()=>(window as any).voxelStudio.mode('scene'));await page.waitForTimeout(2200);results.measurements.browserSteady=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.equal(errors.length,0,errors.join('\n'));record('实际 WebGL 界面 / 编辑工具无脚本异常',{pageErrors:errors});
 const big=await transaction([{op:'createAsset',id:'large-test',name:'大选区验证',template:'empty',cellSize:.1}]);state=await mcp('read_project');const e:Envelope={expectedVersion:state.version,requestId:'large-262144',commands:[{op:'voxels',assetId:'large-test',mode:'fill',region:{min:[0,0,0],max:[64,64,64]},material:1}]};const t=performance.now(),preview=await mcp('edit_transaction',{...e,dryRun:true});assert.equal(preview.modifiedVoxels,262144);results.measurements.largePreviewRoundtripMs=performance.now()-t;const t2=performance.now(),bigResult=await mcp('edit_transaction',{...e,previewToken:preview.previewToken});results.measurements.largeCommitRoundtripMs=performance.now()-t2;results.measurements.largeCommandComputeMs=bigResult.durationMs;await transaction([{op:'undo'}],'撤销大选区');await transaction([{op:'undo'}],'移除大选区测试资产');record('262,144 格大选区 dry-run / 提交 / 回滚',{previewMs:results.measurements.largePreviewRoundtripMs,commitMs:results.measurements.largeCommitRoundtripMs});
 const nativeBeforeRestart=await mcp('read_project',{includeVoxels:true});await stop();start();await waitServer();const recovered=await mcp('read_project',{includeVoxels:true});assert.equal(snapshot(recovered),snapshot(nativeBeforeRestart));const recovery=await http('/api/state');assert.ok(recovery.recovery.recovered);assert.ok(recovery.history.undo>0);record('进程重启自动恢复原生体素与撤销历史',{recovery:recovery.recovery,history:recovery.history});
 const duplicate=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{cwd:base,env:{...process.env,VOXEL_PORT:'4328',VOXEL_PROJECT_DIR:runRoot},stdio:['ignore','ignore','pipe']});let duplicateError='';duplicate.stderr!.on('data',d=>duplicateError+=d);const duplicateCode=await new Promise<number|null>(resolve=>duplicate.once('exit',resolve));assert.notEqual(duplicateCode,0);assert.match(duplicateError,/已有编辑服务/);record('同项目目录第二服务被锁拒绝');
 const pre=await mcp('generate_previews',{assetId:'window'});assert.equal(pre.files.length,7);await mkdir('artifacts/multiview',{recursive:true});for(const f of pre.files)await cp(f,path.join('artifacts/multiview',path.basename(f)));record('MCP 生成七张真实多视角 PNG',{files:pre.files.map((f:string)=>path.basename(f))});
 // Reproducible headless meshing and localized edit timing.
 const p=demoProject(),meshStart=performance.now(),mem=process.memoryUsage().rss;const meshes=Object.values(p.assets).flatMap(a=>meshAsset(a,p.materials));results.measurements.headlessMesh={milliseconds:performance.now()-meshStart,voxels:Object.values(p.assets).reduce((n,a)=>n+new Grid(a.chunks).count,0),quads:meshes.reduce((n,b)=>n+b.quads,0),rssDeltaBytes:process.memoryUsage().rss-mem};
 const engine=new Engine(p),smallStart=performance.now(),r=engine.execute({expectedVersion:0,requestId:'dirty',commands:[{op:'voxels',assetId:'window',mode:'add',cells:[[35,0,0]],material:1}]});results.measurements.singleCell={commandMs:performance.now()-smallStart,dirtyChunks:r.dirtyChunks.window.length,totalAssetChunks:Object.keys(engine.project.assets.window.chunks).length};record('后台合面与局部脏块真实计时',results.measurements.headlessMesh);
 results.success=true;
}catch(e:any){results.success=false;results.failure=e.stack;console.error(e);process.exitCode=1;}finally{results.finishedAt=new Date().toISOString();await writeFile('artifacts/verification.json',JSON.stringify(results,null,2));await client.close();await browser.close();await stop();}
console.log(JSON.stringify({success:results.success,checks:results.checks.length,measurements:results.measurements},null,2));
