import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {NodeIO} from '@gltf-transform/core';
import {KHRMaterialsEmissiveStrength} from '@gltf-transform/extensions';
import {validationBrowserOptions} from './browser-options';
import {parseCatalogCSV} from '../src/core/catalog';
import {productionProject} from '../src/production/style';
import * as assembly from '../src/production/vessel-assembly';
import type {Command,Project,V3} from '../src/core/types';

const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),out=latest.evidence,runtime=path.join(out,`vessel-mcp-${Date.now()}-runtime`),url='http://127.0.0.1:4361',gallery=index.studies.find((s:any)=>s.id==='M025-gallery');assert.ok(gallery);
await mkdir(runtime,{recursive:true});for(const f of['atlas-production-index.json','production-index.json',gallery.file,...index.entries.filter((e:any)=>e.sheet==='M025').map((e:any)=>e.file)])await copyFile(path.join('projects',f),path.join(runtime,f));
await cp('projects/reference-atlas',path.join(runtime,'reference-atlas'),{recursive:true});await copyFile(path.join(runtime,gallery.file),path.join(runtime,'autosave.ysvox.json'));
const empty=productionProject('M025 · 真实 MCP 拼装');empty.catalog={sourceName:'city-assets.csv',importedAt:'verification',entries:Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]))};await writeFile(path.join(runtime,'empty.ysvox.json'),JSON.stringify(empty));
const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),state=async():Promise<Project>=>(await fetch(url+'/api/state').then(r=>r.json())).project;
const report:any={run:index.run,startedAt:new Date().toISOString(),status:'running',checks:[],errors:[],uiSync:[],assemblies:[]};let server:ChildProcess|undefined,client:Client|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,log='';
async function start(){server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4361',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok)return;}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}throw new Error('Server startup timeout');}
async function stop(){if(server&&server.exitCode===null){const closed=once(server,'exit');server.kill('SIGTERM');await closed;}}
function clean(c:any,unsupported:string[]=[],nearPairs:string[][]=[]){assert.deepEqual(c.unsupported,unsupported);assert.deepEqual(c.gaps.map((g:any)=>g.instances),nearPairs);for(const g of c.gaps)assert.ok(Math.abs(g.distanceM-.1)<1e-8);for(const k of['collisions','warnings'])assert.deepEqual(c[k],[],k);assert.ok(c.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));assert.ok(c.clearances.every((o:any)=>o.clear));}
try{
 await start();client=new Client({name:'vessel-semantic-validation',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],env:{...process.env as Record<string,string>,VOXEL_URL:url},cwd:process.cwd(),stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const t=performance.now(),r:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(JSON.stringify({tool:name,ms:performance.now()-t,error:!!r.isError}));return{...JSON.parse(r.content[0].text),isError:!!r.isError};};
 const call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 browser=await chromium.launch(validationBrowserOptions());report.browser=browser.version();const page=await browser.newPage({viewport:{width:1600,height:1050}});page.setDefaultTimeout(120000);page.on('pageerror',e=>report.errors.push(e.message));await page.goto(url+'/?atlas=1&sheet=M025&asset=built-295&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready,null,{timeout:120000});
 report.webgl=await page.evaluate(()=>{const gl=(document.querySelector('#viewport canvas') as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return gl.getParameter(ext?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);});
 const sync=async(v:number)=>{const t=performance.now();await page.waitForFunction(n=>(window as any).voxelStudio.performance.renderedVersion===n,v,{timeout:120000});report.uiSync.push({version:v,ms:performance.now()-t});};
 const before=await state(),roles=before.styles.yunshan,check=await call('check_geometry');clean(check);assert.equal(check.collisionGrids.length,12);report.gallery=check;
 for(const [assetId,point,role]of[
 ['built-289',[.1,.55,.15],'railWheel'],['built-290',[1.1,.5,.5],'metal'],['built-291',[.05,1.4,3],'marineHull'],['built-291',[3,.1,3],'marineAntifouling'],['built-291',[.05,1.05,3],'printedMark'],['built-292',[.15,.5,3],'glass'],['built-293',[.225,.175,1],'printedWarning'],['built-294',[.05,.6,.05],'rubber'],['built-295',[.05,.35,1.65],'navPortLamp'],['built-296',[.8,1.575,.3],'aircraftSkin'],['built-297',[3,.2,1],'metal'],['built-300',[.9,.475,.6],'mooringLine'],['built-307',[1,1.95,4.3],'bridgeBearing'],['built-308',[2.5,1,.95],'jointSeal'],
 ] as [string,V3,string][]){const a=before.assets[assetId],v=point.map(n=>Math.floor((n+1e-8)/a.cellSize)),r=await call('query_voxels',{assetId,region:{min:v,max:v.map(n=>n+1)}});assert.equal(r.cells[0]?.[1],roles[role]);}
 for(const role of['navPortLamp','navStarboardLamp'])assert.equal(before.materials[roles[role]].intensity,0);assert.equal(before.materials[roles.mooringLine].solid,false);
 report.checks.push('Twelve M025 families queried at native coordinates: steel wheels, rubber tires, separate marine coatings, rope, inactive navigation, bearing pads and joint seals');
 const changed=['marineHull','dockFender','railWheel','navPortLamp'],request={expectedVersion:before.version,requestId:crypto.randomUUID(),label:'M025船壳护舷钢轮及未绑定导航芯独立外观包验证',commands:[{op:'definePalette',name:'海陆空独立材质',materials:Object.fromEntries(changed.map((r,i)=>[roles[r],{color:['#703943','#33806b','#455456','#85abb6'][i]}]))},{op:'palette',name:'海陆空独立材质'}]};
 const dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(before));const applied=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(applied.version);const after=await state();assert.equal(applied.modifiedVoxels,0);for(const k of['assets','styles']as const)assert.equal(hash(after[k]),hash(before[k]));
 for(const[id,m]of Object.entries(before.materials)){assert.equal(after.materials[id].solid,m.solid);assert.equal(after.materials[id].category,m.category);if(!changed.some(r=>String(roles[r])===id))assert.deepEqual(after.materials[id],m);}assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(after.materials));
 await page.locator('#material-category-filter').selectOption('metal');const buttons=await page.locator('[data-material]').evaluateAll(nodes=>nodes.map(n=>Number((n as HTMLElement).dataset.material)));assert.ok(buttons.includes(roles.marineHull));for(const id of buttons)assert.equal(after.materials[id].category,'metal');await page.locator('[data-material="'+roles.marineHull+'"]').click();assert.match(await page.locator('#material-role').innerText(),/yunshan.marineHull/);await page.screenshot({path:path.join(out,'mcp-vessel-roles.png')});
 assert.equal((await call('edit_transaction',request)).version,applied.version);assert.equal((await raw('edit_transaction',{...request,requestId:crypto.randomUUID()})).code,'VERSION_CONFLICT');const failed=await raw('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:roles.marineHull,properties:{color:'#ff00ff'}},{op:'produceCatalogAsset',catalogId:'BUILT-294',id:'bad',params:{component:'portWing'}}]});assert.ok(failed.isError);assert.equal(hash(await state()),hash(after));
 const undo=await call('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(undo.version);for(const k of['assets','styles','materials','palettes']as const)assert.equal(hash((await state())[k]),hash(before[k]));await page.screenshot({path:path.join(out,'mcp-vessel-roles-restored.png')});report.checks.push('Four independent hull/fender/wheel/navigation appearance roles, canonical UI hashes, metal filtering, dry run, version conflicts, idempotency, failure rollback and one undo all verified');
 const scenario=async(name:string,commands:Command[],clearances:{name:string;min:V3;max:V3}[],unsupported:string[]=[],nearPairs:string[][]=[])=>{
  const loaded=await call('load_project',{filename:'empty.ysvox.json',expectedVersion:(await state()).version});await sync(loaded.version);const request={expectedVersion:loaded.version,requestId:crypto.randomUUID(),commands},initial=await state(),dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(initial));const built=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(built.version);await page.evaluate(()=>(window as any).voxelStudio.mode('scene'));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const geometry=await call('check_geometry',{clearances});clean(geometry,unsupported,nearPairs);const doc=await state();assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets)),hash(doc.assets));await page.screenshot({path:path.join(out,'mcp-'+name+'.png')});
  const saved=await call('save_project',{filename:name+'.ysvox.json'});await copyFile(saved.path,path.join(out,name+'.ysvox.json'));const exported=await call('export_project',{name}),round=JSON.parse(await readFile(path.join(exported.directory,'voxels.ysvox.json'),'utf8'));for(const k of['assets','instances','materials','styles']as const)assert.equal(hash(round[k]),hash(doc[k]));await cp(exported.directory,path.join(out,name+'-export'),{recursive:true});
  const previews=await call('generate_previews',{appearance:'baseColor',views:['isometric','front']});assert.equal(previews.files.length,2);for(let i=0;i<2;i++){assert.ok((await readFile(previews.files[i])).length>1000);await copyFile(previews.files[i],path.join(out,name+'-view-'+i+'.png'));}report.assemblies.push({name,masters:Object.keys(doc.assets).length,placements:Object.keys(doc.instances).length,geometry,expectedUnsupported:unsupported,expectedNearPairs:nearPairs,exported,previews});return doc;
 };
 await page.locator('#material-category-filter').selectOption('all');
 const definitions=await client.listTools();await writeFile('docs/tool-schemas.json',JSON.stringify(definitions.tools,null,2));
 const recipes=await call('list_production_recipes',{query:'BUILT-294'});assert.deepEqual(recipes.entries[0].parameters.component.enum,['gearDeployed','gearCompressed','gearRetracted']);report.checks.push('MCP advertises verified guide, gear, wing, tail and dock components without inflating twelve catalogue families');
 for(const[name,fn,clear]of assembly.vesselScenarios){const doc=await scenario('vessel-'+name,fn(roles),clear as any);if(name==='ferry')assert.equal((doc.assets.gangway.source!.boarding as any).stoppedStateBound,false);if(name==='airliner'){assert.equal((doc.assets['left-wing'].source!.wing as any).totalSpanM,18);assert.equal(doc.materials[roles.navPortLamp].intensity,0);assert.equal(doc.materials[roles.navStarboardLamp].intensity,0);}report.checks.push('Real '+name+' installation has exact native collisions, support, openings and body clearances; original runtime is unbound');}
 report.authorCableRoute=assembly.authoredCableRoute;report.authorAirliner=assembly.authoredAirliner;report.originalRuntimeBound=false;
 report.checks.push('All eight scenarios save real stdio MCP multiview previews plus GLB/native/collision/interface/material-atlas exports');
 const last=await call('save_project',{filename:'verified-vessel-bridge.ysvox.json'}),saved=await state();assert.equal(hash(JSON.parse(await readFile(last.path,'utf8'))),hash(saved));await stop();await start();assert.equal(hash(await state()),hash(saved));report.checks.push('Native save and server restart restore the exact canonical document');
 assert.deepEqual(report.errors,[]);report.status='passed';report.completedAt=new Date().toISOString();console.log(JSON.stringify({status:report.status,checks:report.checks.length,out}));
}catch(error){report.status='failed';report.errors.push(String(error));throw error;}finally{await browser?.close();await client?.close();await stop();await writeFile(path.join(out,'vessel-mcp-verification.json'),JSON.stringify(report,null,2));await writeFile(path.join(out,'vessel-mcp-server.log'),log);}
