import assert from 'node:assert/strict';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createHash} from 'node:crypto';import {NodeIO} from '@gltf-transform/core';import {KHRMaterialsEmissiveStrength,KHRMaterialsUnlit,KHRLightsPunctual} from '@gltf-transform/extensions';import sharp from 'sharp';
import {Engine,validateProject} from '../src/core/engine';import {Grid} from '../src/core/grid';import {displayMesh} from '../src/core/mesh';import {productionProject} from '../src/production/style';import {referenceFinishCommands} from '../src/production/reference-finish';import {makeArchitectureAssembly} from '../src/production/atlas-architecture-assemblies';import {assemblyGeometryData,assemblyBoundsM,assemblyExportToleranceM} from '../src/production/assembly-geometry';import {parseCatalogCSV} from '../src/core/catalog';import {buildGLB,exportProject} from '../src/export/exporter';import {geometryData} from '../src/core/sky';import {architectureClosed,architectureComponents,architecturePointRoles} from './lib/architecture-audit';import {nativeIslandAttachments} from '../src/production/mixed-review';import {gltfPoints,pointBounds} from './lib/skin-audit';import {CivicAudit} from './lib/civic-audit';import {districtClearance} from './lib/district-audit';import {environmentAudit} from './lib/environment-audit';import {lifeSpaceAudit} from './lib/life-space-audit';import {institutionalAudit} from './lib/institutional-audit';import type {Project,Command,V3} from '../src/core/types';
const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),rows=latest.models,hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex'),io=new NodeIO().registerExtensions([KHRMaterialsEmissiveStrength,KHRMaterialsUnlit,KHRLightsPunctual]);assert.equal(latest.kind,'assembly-batch');assert.equal(rows.length,12);assert.ok(rows.every((r:any)=>r.sheet==='M055'));
const catalog=Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r])),records:any[]=[],variants:any[]=[],defaults=new Map<string,Project>();
const commit=(e:Engine,commands:Command[])=>{const r={expectedVersion:e.project.version,requestId:crypto.randomUUID(),commands},d=e.execute({...r,dryRun:true});return e.execute({...r,previewToken:d.previewToken});};
async function inspect(p:Project,id:string,params:Record<string,string|number>,directory:string,isDefault:boolean){
 const a=Object.values(p.assemblies!)[0],routes=districtClearance(new CivicAudit(p,a)),room=environmentAudit(p,a),extra=lifeSpaceAudit(p,a);assert.ok(routes.checks.every(r=>r.clear),id);assert.ok(routes.contacts.every(r=>r.supported),id);assert.ok(room.uses.every(r=>r.clear&&r.footPresent),id);assert.ok(room.seats.every(r=>r.seatPresent&&r.torsoClear&&r.approachClear&&r.footPresent),id);assert.ok(room.bearings.every(r=>r.lowerPresent&&r.upperPresent),id);assert.ok(room.mounts.every(r=>r.wallPresent&&r.fixtureTouchesWall),id);if(room.kitchen)assert.ok(room.kitchen.bowlClear.clear&&room.kitchen.hoodOpen.clear&&room.kitchen.hoodOpen.grillePresent);if(extra.drain)assert.ok(extra.drain.clear);if(extra.basin)assert.ok(extra.basin.clear);if(extra.door){assert.equal(extra.door.entry.clear,extra.door.state==='open');assert.equal(extra.door.occluded,extra.door.state==='closed');}assert.ok(extra.students.every((r:any)=>r.seatPresent&&r.deskPresent&&r.body.clear&&r.approach.clear&&r.footPresent));if(extra.awning)assert.ok(extra.awning.contacts.every((r:any)=>r.fabricAndSupport));if(extra.meals){assert.ok(extra.meals.bearings.every((r:any)=>r.upperPresent&&r.lowerPresent));assert.ok(extra.meals.vessels.every((r:any)=>r.bottomPresent&&r.ingredientPresent&&r.ingredientTouchesBowl&&r.cavityProbeNotBowl&&r.rimPresent&&r.airAbove.clear&&r.ingredientContacts.every((c:any)=>c.contact)));}
 const pub=institutionalAudit(p,a);assert.ok(pub.bundledSeats.every((r:any)=>r.seatPresent&&r.lowerBody.clear&&r.torso.clear&&r.approach.clear));assert.ok(pub.volumes.every((r:any)=>r.clear));assert.ok(pub.stage.every((r:any)=>r.actualStageBearing&&r.body.clear&&r.declaredSlopeMatches));
 const closed=[],pins=[],derivatives=[];for(const asset of Object.values(p.assets)){
  if(asset.source?.kind==='assembly-derived-component'&&asset.meshes?.length){const c=architectureClosed(asset);assert.ok(c.every(r=>r.closed&&r.oriented),asset.id);closed.push({assetId:asset.id,parts:c.length});const attached=nativeIslandAttachments({...asset,meshes:architectureComponents(asset)});assert.ok(attached.every(r=>r.attached),asset.id);pins.push({assetId:asset.id,nativeDetails:attached.length});}
  if(asset.source?.removedCells&&!asset.meshes?.length){const native=nativeIslandAttachments(asset);assert.equal(native.length,1,asset.id);assert.equal(native[0].cells,new Grid(asset.chunks).count);pins.push({assetId:asset.id,nativeDetails:native.length,nativeSingleComponent:true,cells:native[0].cells});}
  if(asset.source?.materialOnly){const original=p.assets[String(asset.source!.sourceAssetId)],before=new Grid(original.chunks),after=new Grid(asset.chunks);assert.equal(before.count,after.count);assert.equal(hash(geometryData(original)),asset.source!.sourceGeometrySHA256);for(const k of['origin','cellSize','parts','ports','openings']as const)assert.deepEqual(asset[k],original[k]);const changes:Record<string,number>={};for(const[cell,m]of before.cells()){const next=after.get(cell);assert.ok(next);assert.equal(p.materials[next].solid,p.materials[m].solid);if(m!==next){const key=m+'->'+next;changes[key]=(changes[key]??0)+1;}}assert.deepEqual(changes,asset.source!.materialChanges);derivatives.push({assetId:asset.id,original:original.id,cells:before.count,changes,allCellsCollisionPortsPartsAndOpeningsRetained:true});}
 }
 const bounds=assemblyBoundsM(p,a),tolerance=assemblyExportToleranceM(p,a),exports=[],e=new Engine(p);commit(e,[{op:'palette',name:'参考材质试作'}]);assert.deepEqual(e.project.assets,p.assets);
 for(const [key,doc,mode]of[['visual-far',p,'far'],['visual-material',e.project,'near']]as const){const exportData=await buildGLB(doc,undefined,mode);await writeFile(directory+'/'+key+'.glb',exportData.glb);const gltf=await io.readBinary(exportData.glb),nodes=gltf.getRoot().listScenes()[0].listChildren();assert.equal(nodes.length,a.instances.length);assert.deepEqual(gltf.getRoot().listScenes()[0].getExtras().assemblyDefinitions,p.assemblies);const actual=pointBounds(nodes.flatMap(n=>gltfPoints(n))),error=Math.max(...bounds.min.map((v,k)=>Math.abs(v-actual.min[k])),...bounds.max.map((v,k)=>Math.abs(v-actual.max[k])));assert.ok(error<tolerance);const alpha=[];if(key==='visual-material')for(const role of['glass','rigidClear','fluidBlue']){const material=gltf.getRoot().listMaterials().find(m=>m.getExtras().voxelMaterialId===p.styles.yunshan[role]),primitive=gltf.getRoot().listMeshes().flatMap(m=>m.listPrimitives()).find(r=>r.getMaterial()===material);if(!material||!primitive)continue;let value=material.getBaseColorFactor()[3];if(material.getBaseColorTexture()){const image=await sharp(Buffer.from(material.getBaseColorTexture()!.getImage()!)).ensureAlpha().raw().toBuffer({resolveWithObject:true}),uv=primitive.getAttribute('TEXCOORD_0')!.getArray()!,x=Math.floor(((uv[0]%1+1)%1)*image.info.width),y=Math.floor(((uv[1]%1+1)%1)*image.info.height);value*=image.data[(y*image.info.width+x)*4+3]/255;}assert.ok(Math.abs(value-doc.materials[p.styles.yunshan[role]].opacity)<1/255+.00001);alpha.push({role,effectiveAlpha:value,actualGLTFUVPixel:true});}
  exports.push({key,bytes:exportData.glb.length,boundsErrorM:error,toleranceM:tolerance,alpha});
 }
 const native=JSON.parse(await readFile(directory+'/voxels.ysvox.json','utf8')),interfaces=JSON.parse(await readFile(directory+'/interfaces.json','utf8')),collision=JSON.parse(await readFile(directory+'/collision.json','utf8'));for(const k of['assets','instances','assemblies','styles']as const)assert.deepEqual(native[k],p[k]);assert.deepEqual(interfaces.assemblies,p.assemblies);assert.deepEqual(interfaces.instances,Object.values(p.instances));assert.deepEqual(collision.instances,Object.values(p.instances));for(const asset of Object.values(p.assets)){const actual=collision.assets.find((r:any)=>r.id===asset.id);assert.ok(actual);if(asset.meshes){assert.equal(actual.voxelProxy,false);assert.deepEqual(actual.meshes,asset.meshes.filter(m=>m.collision).map(m=>({name:m.name,positions:m.positions,indices:m.indices,material:m.material})));}assert.deepEqual(actual.cells,[...new Grid(asset.chunks).cells()].filter(([,m])=>p.materials[m].solid).map(([v])=>v));}
 const triangles=new Map([...new Set(a.instances.map(i=>i.assetId))].map(id=>[id,{near:displayMesh(p.assets[id],p.materials).reduce((n,m)=>n+m.indices.length/3,0),far:displayMesh(p.assets[id],p.materials,'far').reduce((n,m)=>n+m.indices.length/3,0)}])),near=a.instances.reduce((n,i)=>n+triangles.get(i.assetId)!.near,0),far=a.instances.reduce((n,i)=>n+triangles.get(i.assetId)!.far,0);assert.ok(far<=near);
 records.push({id,params,isDefault,directory,instances:a.instances.length,closed,pins,routes,room,extra,institutional:pub,materialDerivatives:derivatives,nearTriangles:near,farTriangles:far,exports,geometrySHA256:hash(assemblyGeometryData(p,a)),nativeInterfacesAndActualCollisionIdentical:true});console.log(JSON.stringify({id,params,instances:a.instances.length,near,far,closedParts:closed.reduce((n,r)=>n+r.parts,0)}));
}
for(const row of rows){const p:Project=JSON.parse(await readFile('projects/'+row.file,'utf8'));assert.equal(hash(assemblyGeometryData(p,p.assemblies![row.assemblyId])),row.sha256);defaults.set(row.id,p);await inspect(p,row.id,{},latest.out+'/exports/'+row.id,true);}
const points=[];for(const[id,assetId,point,role]of[['LIFE-165','architecture-institution-material-151',[.235,.845,.155],'opticsGlow'],['LIFE-161','architecture-institution-material-147',[.035,.405,-.015],'opticsGlow'],['LIFE-161','architecture-institution-material-148',[.215,.185,.085],'lightCore'],['LIFE-166','architecture-institution-continuous-three-seat-bench',[.345,.455,.30],'fabric'],['LIFE-162','architecture-institution-closed-record-vault',[.30,.8,.06],'enamel'],['LIFE-203','architecture-institution-stage-ramp',[1.25,.23,4.2],'wood']]as [string,string,V3,string][]){const p=defaults.get(id)!,actual=architecturePointRoles(p,p.assets[assetId],point);assert.ok(actual.includes(p.styles.yunshan[role]),role);points.push({id,assetId,point,role,actualMaterialIds:actual});}
const gallery=index.studies.find((r:any)=>r.id==='M055-gallery'),gp:Project=JSON.parse(await readFile('projects/'+gallery.file,'utf8')),galleryBounds=Object.values(gp.assemblies!).map(a=>({id:a.id,...assemblyBoundsM(gp,{instances:a.instances.map(i=>gp.instances[i.id])})}));for(let i=0;i<galleryBounds.length;i++)for(let j=i+1;j<galleryBounds.length;j++)assert.ok(galleryBounds[i].min.some((v,k)=>v>=galleryBounds[j].max[k]||galleryBounds[i].max[k]<=galleryBounds[j].min[k]));
await writeFile(latest.evidence+'/assembly-verification.json',JSON.stringify({run:latest.run,status:'passed',records,gallery:gallery.id,galleryBounds,galleryGroupsDisjoint:true,defaultTemplates:12,finiteForms:12,newBaseMasters:0,variants},null,2));await writeFile(latest.evidence+'/material-audit.json',JSON.stringify({run:latest.run,status:'passed',candidates:12,pendingCandidates:0,independentInteriorPoints:points,newRoles:[],totalRoles:512,creationBatches:[256,256],note:'Native optical indicators and light cores use actual independent purposes with zero emission. Continuous seats, vault faces and ramp components use material roles by purpose. Canonical/historical originals retained; material-only derivatives preserve every occupied cell, metadata and collision.512-role cap unchanged, no runtime integration or human art acceptance.'},null,2));
