import {readFile,writeFile} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {Box3,Triangle,Vector3,Ray} from 'three';import {NodeIO} from '@gltf-transform/core';import {KHRMaterialsEmissiveStrength,KHRMaterialsUnlit} from '@gltf-transform/extensions';import {checkFloat32Bounds} from '../src/export/precision';import {assetBoundsM,geometryData} from '../src/core/sky';import {figureScenes,figureScene} from '../src/production/figure-assembly';import {makeFigureAsset} from '../src/production/atlas-figure';import {productionProject} from '../src/production/style';import type {Project,V3} from '../src/core/types';
const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),out=latest.evidence,hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex'),report:any={run:latest.run,status:'running',masters:[],scenes:[],wear:[]},io=new NodeIO().registerExtensions([KHRMaterialsEmissiveStrength,KHRMaterialsUnlit]);
type Shape={name:string;vs:Vector3[];ts:Triangle[];box:Box3};
function triangles(p:Project,id:string):Shape[]{const offset=p.instances['i-'+id].position;return p.assets[id].meshes!.map(m=>{const vs=Array.from({length:m.positions.length/3},(_,i)=>new Vector3(...m.positions.slice(i*3,i*3+3).map((v,d)=>v+offset[d]))),ts:Triangle[]=[];for(let i=0;i<m.indices.length;i+=3)ts.push(new Triangle(...m.indices.slice(i,i+3).map(i=>vs[i]) as [Vector3,Vector3,Vector3]));return{name:m.name,vs,ts,box:new Box3().setFromPoints(vs)};});}
function inside(v:Vector3,b:Shape){if(!b.box.containsPoint(v))return false;if(b.ts.some(t=>t.closestPointToPoint(v,new Vector3()).distanceToSquared(v)<1e-14))return false;const ray=new Ray(v,new Vector3(1,.293,.157).normalize()),hits:number[]=[];for(const t of b.ts){const h=ray.intersectTriangle(t.a,t.b,t.c,false,new Vector3());if(h){const d=v.distanceTo(h);if(!hits.some(n=>Math.abs(n-d)<1e-7))hits.push(d);}}return hits.length%2===1;}
function crossings(a:Shape,b:Shape){let hits=0;for(const t of a.ts)for(const [v,w]of[[t.a,t.b],[t.b,t.c],[t.c,t.a]]){const length=v.distanceTo(w),ray=new Ray(v,w.clone().sub(v).normalize());for(const other of b.ts){const p=ray.intersectTriangle(other.a,other.b,other.c,false,new Vector3());if(p){const d=v.distanceTo(p);if(d>1e-7&&d<length-1e-7&& (inside(v.clone().lerp(w,Math.max(0,(d-1e-6)/length)),b)||inside(v.clone().lerp(w,Math.min(1,(d+1e-6)/length)),b)))hits++;}}}return hits;}
for(const row of latest.models){const p:Project=JSON.parse(await readFile(path.join('projects',row.file),'utf8')),a=p.assets[row.assetId],made=makeFigureAsset(row.id,a.name,a.id,p.styles.yunshan,a.source!.parameters as any),native=JSON.parse(await readFile(path.join(latest.out,'exports',row.id,'voxels.ysvox.json'),'utf8'));assert.equal(hash(geometryData(made)),row.sha256);assert.deepEqual(a.ports,made.ports);assert.deepEqual(native.assets[a.id],a);report.masters.push({id:row.id,geometrySHA256:row.sha256,recipeMatchesSavedAndExported:true,portsMatch:true});}
for(const kind of figureScenes){const name='figure-'+kind,p:Project=JSON.parse(await readFile(path.join(out,name+'.ysvox.json'),'utf8')),native=JSON.parse(await readFile(path.join(out,name+'-export/voxels.ysvox.json'),'utf8')),collision=JSON.parse(await readFile(path.join(out,name+'-export/collision.json'),'utf8')),interfaces=JSON.parse(await readFile(path.join(out,name+'-export/interfaces.json'),'utf8')),g=await io.read(path.join(out,name+'-export/visual.glb')),nodes=g.getRoot().listScenes()[0].listChildren(),expected=figureScene(productionProject('verify'),kind);assert.equal(nodes.length,Object.keys(p.instances).length);assert.deepEqual(native.assets,p.assets);assert.deepEqual(native.instances,p.instances);assert.deepEqual(interfaces.instances,Object.values(p.instances));assert.ok(collision.assets.every((a:any)=>!a.cells.length&&!a.meshes.length));assert.deepEqual(p.instances,expected.instances);
 let maxError=0;for(const node of nodes){const a=p.assets[String(node.getExtras().assetId)],actual={min:[Infinity,Infinity,Infinity],max:[-Infinity,-Infinity,-Infinity]},bounds=assetBoundsM(a)!;for(const primitive of node.getMesh()!.listPrimitives()){const arr=primitive.getAttribute('POSITION')!.getArray()!;for(let k=0;k<arr.length;k++){const d=k%3;actual.min[d]=Math.min(actual.min[d],arr[k]);actual.max[d]=Math.max(actual.max[d],arr[k]);}}assert.ok(checkFloat32Bounds(bounds,actual).matchesFloat32Rounding);maxError=Math.max(maxError,...actual.min.map((n,i)=>Math.abs(n-bounds.min[i])),...actual.max.map((n,i)=>Math.abs(n-bounds.max[i])));const instance=Object.values(p.instances).find(i=>i.assetId===a.id)!;assert.deepEqual(node.getTranslation(),instance.position);if(a.source?.catalogId){const made=makeFigureAsset(String(a.source.catalogId),a.name,a.id,p.styles.yunshan,a.source.parameters as any);assert.equal(hash(geometryData(made)),hash(geometryData(a)));assert.deepEqual(made.ports,a.ports);}else assert.equal(a.source?.notCatalogMaster,true);assert.deepEqual(interfaces.assets.find((v:any)=>v.id===a.id).ports,a.ports);}
 report.scenes.push({name,instances:nodes.length,originalRigBound:false,sourceMastersAndEnvelopeLabelsPreserved:true,emptyCollision:true,portRoundtrip:true,maximumFloat32BoundsErrorM:maxError});
 if(kind==='adults')for(const pair of[['char-014','char-060'],['char-013','head-CHAR-059']]){let testedPairs=0,containedSamples=0,surfaceCrossings=0;const a=triangles(p,pair[0]),b=triangles(p,pair[1]);for(const x of a)for(const y of b){if(!x.box.intersectsBox(y.box))continue;testedPairs++;containedSamples+=[...x.vs,...x.ts.map(t=>t.getMidpoint(new Vector3()))].filter(v=>inside(v,y)).length+[...y.vs,...y.ts.map(t=>t.getMidpoint(new Vector3()))].filter(v=>inside(v,x)).length;surfaceCrossings+=crossings(x,y)+crossings(y,x);}assert.equal(containedSamples,0,pair.join('/')+' contained');assert.equal(surfaceCrossings,0,pair.join('/')+' crossing');report.wear.push({pair,testedMeshPairs:testedPairs,containedVerticesOrFaceCenters:containedSamples,penetratingTriangleEdgeIntersections:surfaceCrossings});}
}
// The shoulder bridge underside genuinely contacts the flat sleeve cap via matching ports.
const q:Project=JSON.parse(await readFile(path.join(out,'figure-adults.ysvox.json'),'utf8')),bag=q.assets['char-014'],body=q.assets['char-060'],bp=bag.ports.find(p=>p.id==='shoulder-rest')!,sp=body.ports.find(p=>p.id==='bag-shoulder')!,bagPos=q.instances['i-char-014'].position,bodyPos=q.instances['i-char-060'].position;for(let d=0;d<3;d++)assert.ok(Math.abs(bp.position[d]+bagPos[d]-sp.position[d]-bodyPos[d])<1e-8);const bridge=triangles(q,'char-014').find(m=>m.name==='肩顶连续承接带')!,sleeve=triangles(q,'char-060').find(m=>m.name==='肩肘腕连续袖身-1')!,point=new Vector3(...sp.position.map((v,i)=>v+bodyPos[i]));assert.ok(bridge.ts.some(t=>t.closestPointToPoint(point,new Vector3()).distanceTo(point)<1e-8));assert.ok(sleeve.ts.some(t=>t.closestPointToPoint(point,new Vector3()).distanceTo(point)<1e-8));report.shoulderContact={worldPoint:point.toArray(),opposingSockets:true,actualBridgeAndSleeveTriangleContact:true};
report.status='passed';report.limitations=['Static author proportions and accessory fitting, not original protected clearance, age eligibility, rig, skinning or runtime certification.','Grey envelopes are explicit auxiliary study geometry, not finished child/elder head masters.','Accessory cross-checks cover the saved adult study, not every possible pose, garment or head.'];await writeFile(path.join(out,'figure-installation-verification.json'),JSON.stringify(report,null,2));await writeFile(path.join(out,'final-geometry-recheck.json'),JSON.stringify({run:latest.run,status:'passed',masters:report.masters,scenes:report.scenes},null,2));console.log(JSON.stringify(report,null,2));
