import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {validationBrowserOptions} from './browser-options';
import {parseCatalogCSV} from '../src/core/catalog';
import {productionProject} from '../src/production/style';
import * as assembly from '../src/production/bridge-assembly';
import type {Command,Project,V3} from '../src/core/types';

const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),out=latest.evidence,runtime=path.join(out,'bridge-mcp-runtime'),url='http://127.0.0.1:4354',gallery=index.studies.find((s:any)=>s.id==='M019-gallery');assert.ok(gallery);
await mkdir(runtime,{recursive:true});for(const f of['atlas-production-index.json','production-index.json',gallery.file,...index.entries.filter((e:any)=>e.sheet==='M019').map((e:any)=>e.file)])await copyFile(path.join('projects',f),path.join(runtime,f));
await cp('projects/reference-atlas',path.join(runtime,'reference-atlas'),{recursive:true});await copyFile(path.join(runtime,gallery.file),path.join(runtime,'autosave.ysvox.json'));
const empty=productionProject('M019 · 真实 MCP 拼装');empty.catalog={sourceName:'city-assets.csv',importedAt:'verification',entries:Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]))};await writeFile(path.join(runtime,'empty.ysvox.json'),JSON.stringify(empty));
const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),state=async():Promise<Project>=>(await fetch(url+'/api/state').then(r=>r.json())).project;
const report:any={run:index.run,startedAt:new Date().toISOString(),status:'running',checks:[],errors:[],uiSync:[],assemblies:[]};let server:ChildProcess|undefined,client:Client|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,log='';
async function start(){server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4354',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok)return;}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}throw new Error('Server startup timeout');}
async function stop(){if(server&&server.exitCode===null){const closed=once(server,'exit');server.kill('SIGTERM');await closed;}}
function clean(c:any,unsupported:string[]=[]){assert.deepEqual(c.unsupported,unsupported);for(const k of['collisions','gaps','warnings'])assert.deepEqual(c[k],[],k);assert.ok(c.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));assert.ok(c.clearances.every((o:any)=>o.clear));}
try{
 await start();client=new Client({name:'bridge-semantic-validation',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],env:{...process.env as Record<string,string>,VOXEL_URL:url},cwd:process.cwd(),stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const t=performance.now(),r:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(JSON.stringify({tool:name,ms:performance.now()-t,error:!!r.isError}));return{...JSON.parse(r.content[0].text),isError:!!r.isError};};
 const call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 browser=await chromium.launch(validationBrowserOptions());report.browser=browser.version();const page=await browser.newPage({viewport:{width:1600,height:1050}});page.setDefaultTimeout(120000);page.on('pageerror',e=>report.errors.push(e.message));await page.goto(url+'/?atlas=1&sheet=M019&asset=built-143&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready,null,{timeout:120000});
 report.webgl=await page.evaluate(()=>{const gl=(document.querySelector('#viewport canvas') as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return gl.getParameter(ext?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);});if(process.argv.includes('--metal'))assert.match(report.webgl,/Metal Renderer/);
 const sync=async(v:number)=>{const t=performance.now();await page.waitForFunction(n=>(window as any).voxelStudio.performance.renderedVersion===n,v,{timeout:120000});report.uiSync.push({version:v,ms:performance.now()-t});};
 const before=await state(),roles=before.styles.yunshan,check=await call('check_geometry');clean(check);assert.equal(check.collisionGrids.length,12);report.gallery=check;
 for(const [assetId,v,role]of [
  ['built-141',[0,9,50],'energy'],['built-142',[20,97,20],'wall'],['built-142',[20,92,20],'mortar'],
  ['built-143',[16,26,80],'suspensionCable'],['built-143',[16,6,80],'energy'],['built-144',[2,50,2],'wood'],
  ['built-145',[2,20,-1],'glass'],['built-145',[2,20,0],'energy'],['built-146',[40,4,40],'pavementConcrete'],
  ['built-148',[10,120,800],'suspensionCable'],['built-149',[3,30,3],'suspensionCable'],['built-152',[5,23,12],'roof'],
 ] as const){const r=await call('query_voxels',{assetId,region:{min:v,max:v.map(n=>n+1)}});assert.equal(r.cells[0]?.[1],roles[role]);}
 assert.equal(before.materials[roles.suspensionCable].category,'metal');assert.equal(before.materials[roles.glass].category,'glass');report.checks.push('Twelve M019 native masters with actual load-bearing cable, glass, lamp, concrete, timber, stone and roof cells verified through stdio MCP');
 const changed=['suspensionCable','energy','glass','roof'],request={expectedVersion:before.version,requestId:crypto.randomUUID(),label:'M019独立材质包验证',commands:[{op:'definePalette',name:'交通组件独立材质',materials:Object.fromEntries(changed.map((r,i)=>[roles[r],{color:['#70bd94','#745ce0','#798399','#943a3a'][i]}]))},{op:'palette',name:'交通组件独立材质'}]};
 const dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(before));const applied=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(applied.version);const after=await state();assert.equal(applied.modifiedVoxels,0);for(const k of['assets','styles']as const)assert.equal(hash(after[k]),hash(before[k]));
 for(const[id,m]of Object.entries(before.materials)){assert.equal(after.materials[id].solid,m.solid);assert.equal(after.materials[id].category,m.category);if(!changed.some(r=>String(roles[r])===id))assert.deepEqual(after.materials[id],m);}assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(after.materials));
 await page.locator('#material-category-filter').selectOption('metal');const buttons=await page.locator('[data-material]').evaluateAll(nodes=>nodes.map(n=>Number((n as HTMLElement).dataset.material)));assert.ok(buttons.includes(roles.suspensionCable));for(const id of buttons)assert.equal(after.materials[id].category,'metal');await page.locator('[data-material="'+roles.suspensionCable+'"]').click();assert.match(await page.locator('#material-role').innerText(),/yunshan.suspensionCable/);await page.screenshot({path:path.join(out,'mcp-bridge-roles.png')});
 assert.equal((await call('edit_transaction',request)).version,applied.version);assert.equal((await raw('edit_transaction',{...request,requestId:crypto.randomUUID()})).code,'VERSION_CONFLICT');const failed=await raw('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:roles.suspensionCable,properties:{color:'#ff00ff'}},{op:'produceCatalogAsset',catalogId:'BUILT-999',id:'bad'}]});assert.ok(failed.isError);assert.equal(hash(await state()),hash(after));
 const undo=await call('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(undo.version);for(const k of['assets','styles','materials','palettes']as const)assert.equal(hash((await state())[k]),hash(before[k]));await page.screenshot({path:path.join(out,'mcp-bridge-roles-restored.png')});report.checks.push('Cable/lamp/glass/roof appearance changes exactly four roles, no geometry or collision, with matching canonical UI hashes, metal filtering, dry-run, idempotency, version conflict, failure rollback and one undo');
 const scenario=async(name:string,commands:Command[],clearances:{name:string;min:V3;max:V3}[])=>{
  const loaded=await call('load_project',{filename:'empty.ysvox.json',expectedVersion:(await state()).version});await sync(loaded.version);const request={expectedVersion:loaded.version,requestId:crypto.randomUUID(),commands},initial=await state(),dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(initial));const built=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(built.version);await page.evaluate(()=>(window as any).voxelStudio.mode('scene'));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const geometry=await call('check_geometry',{clearances});clean(geometry);const doc=await state();assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets)),hash(doc.assets));await page.screenshot({path:path.join(out,'mcp-'+name+'.png')});
  const saved=await call('save_project',{filename:name+'.ysvox.json'});await copyFile(saved.path,path.join(out,name+'.ysvox.json'));const exported=await call('export_project',{name}),round=JSON.parse(await readFile(path.join(exported.directory,'voxels.ysvox.json'),'utf8'));for(const k of['assets','instances','materials','styles']as const)assert.equal(hash(round[k]),hash(doc[k]));await cp(exported.directory,path.join(out,name+'-export'),{recursive:true});
  const previews=await call('generate_previews',{appearance:'baseColor',views:['isometric','front']});assert.equal(previews.files.length,2);for(let i=0;i<2;i++){assert.ok((await readFile(previews.files[i])).length>1000);await copyFile(previews.files[i],path.join(out,name+'-view-'+i+'.png'));}report.assemblies.push({name,masters:Object.keys(doc.assets).length,placements:Object.keys(doc.instances).length,geometry,exported,previews});return doc;
 };
 await page.locator('#material-category-filter').selectOption('all');
 const assembled=await scenario('bridge-track',assembly.bridgeTrackCommands(),assembly.bridgeTrackClearances);assert.equal(Object.keys(assembled.assets).length,3);assert.equal(Object.keys(assembled.instances).length,5);assert.deepEqual(assembled.instances['guides-1'].position,[1.06,1.4,0]);report.checks.push('Revised M018 bed, 0.28m by 0.24m guides and 0.35m by 0.5m guard strips preserve exact +/-1.8m and +/-2.75m offsets; row intervals verify over 300 million shared-grid cells with no collisions or blocked platform opening');
 const wrong=await raw('edit_transaction',{expectedVersion:assembled.version,requestId:crypto.randomUUID(),commands:[{op:'createAsset',id:'fine',name:'5mm incompatible dock',template:'empty',cellSize:.005},{op:'metadata',assetId:'fine',ports:[{id:'p',kind:'track-datum',position:[3,0,4],normal:[0,-1,0],size:[6,0,8],pitch:.005}]},{op:'connect',id:'bad',assetId:'fine',portId:'p',targetInstanceId:'bed-1',targetPortId:'track-datum',rotation:0}]});assert.ok(wrong.isError);assert.match(JSON.stringify(wrong),/格距/);assert.equal(hash(await state()),hash(assembled));report.checks.push('Fine/coarse direct docking mismatch still rejects atomically; accurate placement does not relax the docking contract');
 const shaft=await scenario('bridge-shaft',assembly.bridgeShaftCommands(),assembly.bridgeShaftClearances);assert.deepEqual(shaft.instances['guide-1'].position,[5.85,.8,2.65]);report.checks.push('Four-post shaft keeps its 4.4m centre empty; side rail at x+3.2m is supported by actual external brackets');
 const rail=await scenario('bridge-rail',assembly.bridgeRailCommands(),assembly.bridgeRailClearances);assert.equal(Object.keys(rail.assets).length,3);assert.equal(Object.keys(rail.instances).length,9);report.checks.push('One 9m bridge deck, four independent posts and four reused M018 rails have no overlap or blocked travel layer');
 const suspension=await scenario('bridge-suspension',assembly.bridgeSuspensionCommands(),assembly.bridgeSuspensionClearances);assert.equal(Object.keys(suspension.instances).length,37);assert.equal(new Set(Object.values(suspension.assets).map(a=>a.source!.catalogId)).size,6);report.checks.push('160m main cable geometry uses exact 0.16/0.84 tower positions and 30m peaks; six central hangers use two verified heights at 8m intervals, with exact steel clamp faces and clear vehicle passage; static interface study, not structural certification');
 const cable=await scenario('bridge-cable',assembly.bridgeCableFixtureCommands(roles),[]);assert.equal(cable.instances['cable-1'].position[1]+.65,9);report.checks.push('Cable fixture realizes a 9m carrier and 8.5m energy line; test supports are explicitly auxiliary, not catalogue masters');
 report.checks.push('All five scenarios save genuine MCP multi-view previews and GLB/native/collision/interface/material-atlas exports');
 const last=await call('save_project',{filename:'verified-bridge-cable.ysvox.json'}),saved=await state();assert.equal(hash(JSON.parse(await readFile(last.path,'utf8'))),hash(saved));await stop();await start();assert.equal(hash(await state()),hash(saved));report.checks.push('Native save and server restart restore the exact canonical document');
 assert.deepEqual(report.errors,[]);report.status='passed';report.completedAt=new Date().toISOString();console.log(JSON.stringify({status:report.status,checks:report.checks.length,out}));
}catch(error){report.status='failed';report.errors.push(String(error));throw error;}finally{await browser?.close();await client?.close();await stop();await writeFile(path.join(out,'bridge-mcp-verification.json'),JSON.stringify(report,null,2));await writeFile(path.join(out,'bridge-mcp-server.log'),log);}
