import assert from 'node:assert/strict';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createHash} from 'node:crypto';import {NodeIO} from '@gltf-transform/core';import {KHRMaterialsEmissiveStrength,KHRMaterialsUnlit} from '@gltf-transform/extensions';import sharp from 'sharp';
import {geometryData} from '../src/core/sky';import {rotateY,type V3} from '../src/core/types';
import {Engine,validateProject} from '../src/core/engine';import {Grid} from '../src/core/grid';import {displayMesh} from '../src/core/mesh';import {productionProject} from '../src/production/style';import {referenceFinishCommands} from '../src/production/reference-finish';import {makeArchitectureAssembly} from '../src/production/atlas-architecture-assemblies';import {assemblyGeometryData,assemblyBoundsM} from '../src/production/assembly-geometry';import {parseCatalogCSV} from '../src/core/catalog';import {buildGLB,exportProject} from '../src/export/exporter';import {architectureClosed,architectureClearance,architecturePointRoles,architectureComponents,architectureRoofSupports} from './lib/architecture-audit';import {nativeIslandAttachments} from '../src/production/mixed-review';import {gltfPoints,pointBounds} from './lib/skin-audit';import type {Project,Command} from '../src/core/types';
const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),rows=latest.models,hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex'),io=new NodeIO().registerExtensions([KHRMaterialsEmissiveStrength,KHRMaterialsUnlit]);assert.equal(latest.kind,'assembly-batch');assert.equal(rows.length,12);
const catalog=Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r])),records:any[]=[],roleSamples=new Map<string,unknown>(),variants:any[]=[],defaults=new Map<string,Project>();
const commit=(e:Engine,commands:Command[])=>{const r={expectedVersion:e.project.version,requestId:crypto.randomUUID(),commands},d=e.execute({...r,dryRun:true});return e.execute({...r,previewToken:d.previewToken});};
async function inspect(p:Project,id:string,params:Record<string,string|number>,directory:string,isDefault:boolean){
 const assembly=Object.values(p.assemblies!)[0],bounds=assemblyBoundsM(p,assembly),clearance=architectureClearance(p,assembly);assert.ok(clearance.every(c=>c.clear),JSON.stringify(clearance.filter(c=>!c.clear)));const supports=architectureRoofSupports(p,assembly);assert.ok(supports.every(r=>r.supported),JSON.stringify(supports.filter(r=>!r.supported)));const closed=[],pins=[];
 for(const a of Object.values(p.assets))if(a.source?.kind==='assembly-derived-component'){const checked=architectureClosed(a);assert.ok(checked.every(c=>c.closed&&c.oriented));closed.push({assetId:a.id,parts:checked.length});const attachments=nativeIslandAttachments(a);assert.ok(attachments.every(r=>r.attached),a.id+JSON.stringify(attachments.filter(r=>!r.attached)));pins.push({assetId:a.id,nativeDetails:attachments.length});}
 for(const assetId of new Set(assembly.instances.map(i=>i.assetId))){const a=p.assets[assetId];for(const m of architectureComponents(a)){for(const role of Object.keys(p.styles.yunshan).filter(r=>p.styles.yunshan[r]===m.material)){if(roleSamples.has(role)||!['distant','architecture'].some(prefix=>role.startsWith(prefix)))continue;const points=m.indices.slice(0,3).map(i=>m.positions.slice(i*3,i*3+3)),centroid=[0,1,2].map(d=>points.reduce((n,v)=>n+v[d]/3,0));roleSamples.set(role,{id,assetId,component:m.name,material:m.material,role,category:p.materials[m.material].category,solid:p.materials[m.material].solid,emissive:p.materials[m.material].intensity,actualSurfaceCentroidM:centroid});}}for(const[cell,material]of new Grid(a.chunks).cells())if(material===p.styles.yunshan.architecturePin&&!roleSamples.has('architecturePin'))roleSamples.set('architecturePin',{id,assetId,role:'architecturePin',material,category:p.materials[material].category,solid:false,cell});}
 const near=assembly.instances.reduce((n,i)=>n+displayMesh(p.assets[i.assetId],p.materials).reduce((n,m)=>n+m.indices.length/3,0),0),far=assembly.instances.reduce((n,i)=>n+displayMesh(p.assets[i.assetId],p.materials,'far').reduce((n,m)=>n+m.indices.length/3,0),0);assert.ok(far<=near);const fg=await buildGLB(p,undefined,'far');await writeFile(directory+'/visual-far.glb',fg.glb);const gd=await io.readBinary(fg.glb),nodes=gd.getRoot().listScenes()[0].listChildren();assert.equal(nodes.length,assembly.instances.length);const actual=pointBounds(nodes.flatMap(n=>gltfPoints(n))),error=Math.max(...bounds.min.map((v,d)=>Math.abs(v-actual.min[d])),...bounds.max.map((v,d)=>Math.abs(v-actual.max[d])));assert.ok(error<5e-6);assert.deepEqual(gd.getRoot().listScenes()[0].getExtras().assemblyDefinitions,p.assemblies);
 const e=new Engine(p);commit(e,[{op:'palette',name:'参考材质试作'}]);assert.deepEqual(e.project.assets,p.assets);const material=await buildGLB(e.project),md=await io.readBinary(material.glb),alpha=[];await writeFile(directory+'/visual-material.glb',material.glb);
 for(const role of['glass','distantGlazing']){const mat=md.getRoot().listMaterials().find(m=>m.getExtras().voxelMaterialId===p.styles.yunshan[role]),primitive=md.getRoot().listMeshes().flatMap(m=>m.listPrimitives()).find(p=>p.getMaterial()===mat);if(!primitive)continue;assert.equal(mat!.getAlphaMode(),'BLEND');const uv=primitive.getAttribute('TEXCOORD_0')!.getArray()!,img=await sharp(Buffer.from(mat!.getBaseColorTexture()!.getImage()!)).ensureAlpha().raw().toBuffer({resolveWithObject:true}),x=Math.floor(((uv[0]%1+1)%1)*img.info.width),y=Math.floor(((uv[1]%1+1)%1)*img.info.height),effectiveAlpha=img.data[(y*img.info.width+x)*4+3]/255*mat!.getBaseColorFactor()[3];assert.ok(Math.abs(effectiveAlpha-.3)<1/255);alpha.push({role,effectiveAlpha,actualUVPixel:true});}
 const interfaces=JSON.parse(await readFile(directory+'/interfaces.json','utf8'));assert.deepEqual(interfaces.assemblies,p.assemblies);assert.deepEqual(interfaces.instances,Object.values(p.instances));const r={id,params,isDefault,directory,componentAssets:Object.keys(p.assets).length,instances:assembly.instances.length,closed,pins,supports,clearance,nearTriangles:near,farTriangles:far,farGLBBoundsErrorM:error,alphaChecks:alpha,geometrySHA256:hash(assemblyGeometryData(p,assembly)),actualSharedGLTFMeshes:gd.getRoot().listMeshes().length,scope:'Finite author geometry; joints may intentionally intersect. No original FloorPlan/controller or human art acceptance.'};records.push(r);console.log(JSON.stringify({id,params,instances:r.instances,clearance:clearance.length,closed:closed.reduce((n,r)=>n+r.parts,0),near,far}));
}
const distantParity:any[]=[];
function verifyDistant(p:Project){for(const a of Object.values(p.assets)){const src=a.source!;if(src.kind!=='assembly-distant-display')continue;const near=defaults.get(String(src.sourceAssemblyCatalogId))!,assembly=Object.values(near.assemblies!)[0],groups=assembly.source!.instanceGroups as Record<string,string>,expected=new Map<number,ReturnType<typeof createHash>>();const mappings=src.roleMapping as Record<string,string>;for(const record of src.sourceInstances as any[]){const sourceAsset=near.assets[record.assetId];assert.ok(sourceAsset);assert.equal(hash(geometryData(sourceAsset)),record.geometrySHA256);assert.ok(assembly.instances.some(i=>i.assetId===record.assetId&&hash(i.position)===hash(record.position)&&i.rotation===record.rotation&&groups[i.id]!=='fixture'));for(const b of displayMesh(sourceAsset,near.materials,'far')){const role=Object.keys(mappings).find(role=>near.styles.yunshan[role]===b.material)!;assert.ok(role);const material=p.styles.yunshan[mappings[role]],digest=expected.get(material)??createHash('sha256');for(const index of b.indices){const v=rotateY(b.positions.slice(index*3,index*3+3)as V3,record.rotation).map((v,d)=>Math.round((v+record.position[d])*1e9)/1e9||0);digest.update(v.join(',')+';');}expected.set(material,digest);}}for(const m of a.meshes!){const digest=createHash('sha256');for(const index of m.indices)digest.update(m.positions.slice(index*3,index*3+3).map(v=>v||0).join(',')+';');assert.equal(digest.digest('hex'),expected.get(m.material)!.digest('hex'),a.id+' transformed surface parity');}assert.equal(a.meshes!.length,expected.size);distantParity.push({id:a.id,sourceCatalogId:src.sourceAssemblyCatalogId,actualInstanceSources:(src.sourceInstances as any[]).length,allOrientedTriangleVerticesMatch:true,fixturesOmitted:true});}}
for(const row of rows){const p:Project=JSON.parse(await readFile('projects/'+row.file,'utf8')),a=p.assemblies![row.assemblyId];assert.equal(hash(assemblyGeometryData(p,a)),row.sha256);defaults.set(row.id,p);if(row.id==='BUILT-040')verifyDistant(p);await inspect(p,row.id,{},latest.out+'/exports/'+row.id,true);}
const choices:[string,Record<string,string|number>][]=[['BUILT-023',{program:'medical'}],['BUILT-042',{layoutSeed:19}],...['BUILT-075','BUILT-076','BUILT-077','BUILT-078'].map(id=>[id,{roofWidth:'wide'}]as [string,Record<string,string|number>])];
for(const[id,params]of choices){const p=productionProject(id+' alternative');p.catalog={sourceName:'catalog',importedAt:latest.createdAt,entries:structuredClone(catalog)};if(id==='BUILT-042')p.assets=structuredClone(defaults.get(id)!.assets);const a=makeArchitectureAssembly(p,id,id.toLowerCase(),catalog[id].source['中文名称'],params);p.assemblies={[a.id]:a};p.instances=Object.fromEntries(a.instances.map(i=>[i.id,i]));const used=new Set([id,...a.source!.dependencies as string[],...Object.values(p.assets).map(a=>String(a.source?.catalogId??''))]);p.catalog.entries=Object.fromEntries(Object.entries(p.catalog.entries).filter(([id])=>used.has(id)));const e=new Engine(p);commit(e,[...referenceFinishCommands(p),{op:'palette',name:'原始素色'}]);validateProject(e.project);const directory=latest.out+'/variants/'+id;await mkdir(directory,{recursive:true});await exportProject(e.project,directory);variants.push({id,params,dependencyCatalogIds:a.source!.dependencies,file:directory+'/voxels.ysvox.json',directory});await inspect(e.project,id,params,directory,false);}
const gallery=index.studies.find((r:any)=>r.id==='M044-gallery'),gp:Project=JSON.parse(await readFile('projects/'+gallery.file,'utf8')),galleryBounds=Object.values(gp.assemblies!).map(a=>{const placed={instances:a.instances.map(i=>gp.instances[i.id])};return{id:a.id,...assemblyBoundsM(gp,placed)};});for(let i=0;i<galleryBounds.length;i++)for(let j=i+1;j<galleryBounds.length;j++)assert.ok(galleryBounds[i].min.some((v,d)=>v>=galleryBounds[j].max[d]||galleryBounds[i].max[d]<=galleryBounds[j].min[d]));
const points:any[]=[];const first=defaults.get('BUILT-019')!;for(const[asset,point,role]of[['architecture-floor-3p2-3p2',[.4,.08,.4],'structuralConcrete'],['architecture-floor-3p2-3p2',[.4,.17,.4],'mortar'],['architecture-floor-3p2-3p2',[.4,.19,.4],'wall'],['architecture-wall-window',[1.2,1.3,.12],'glass'],['architecture-wall-window',[1.32,1.3,.12],'wood']]as const){const ids=architecturePointRoles(first,first.assets[asset],[...point]);assert.ok(ids.includes(first.styles.yunshan[role]));points.push({asset,point,role,actualMaterialIds:ids});}
await writeFile(latest.evidence+'/assembly-verification.json',JSON.stringify({run:latest.run,status:'passed',records,distantParity,gallery:gallery.id,galleryBounds,galleryGroupsDisjoint:true,defaultTemplates:12,finiteForms:18,newBaseMasters:0,variants},null,2));await writeFile(latest.evidence+'/material-audit.json',JSON.stringify({run:latest.run,status:'passed',candidates:12,pendingCandidates:0,roleSamples:[...roleSamples.values()],independentInteriorPoints:points,note:'Near structure uses existing structural semantics. Fourteen distant visual roles and one native non-bearing pin role remain distinct; derived distant cells are not physical voxel authority.'},null,2));
