import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import {spawn,type ChildProcess} from 'node:child_process';
import {createHash} from 'node:crypto';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {chromium} from 'playwright';
import {validationBrowserOptions} from './browser-options';
import {productionProject} from '../src/production/style';
import {parseCatalogCSV} from '../src/core/catalog';
import {faceAtlasPixels} from '../src/core/face-atlas';
import {Grid} from '../src/core/grid';
import {rotateY,type Project} from '../src/core/types';
import {outfitHash as hash} from '../src/production/outfit-components';
import {auditFaceVariant} from './lib/face-variant-audit';

const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),out=latest.evidence,runtime=out+'/variant-mcp-runtime',url='http://127.0.0.1:4401',rows=latest.models;assert.equal(rows.length,6);assert.equal(JSON.parse(await readFile(out+'/variant-verification.json','utf8')).status,'passed');await mkdir(runtime,{recursive:true});
for(const file of ['atlas-production-index.json','production-index.json','architecture-index.json','material-index.json',...latest.files.map((r:any)=>r.file)])await copyFile('projects/'+file,runtime+'/'+file);await cp('projects/reference-atlas',runtime+'/reference-atlas',{recursive:true});await copyFile('projects/'+rows[0].file,runtime+'/autosave.ysvox.json');
const empty=productionProject('共享面孔六格实际比较');empty.catalog={sourceName:'city-assets.csv',importedAt:latest.createdAt,entries:Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]))};empty.materials[1800]={...empty.materials[empty.styles.yunshan.skinSurface],id:1800,name:'foreign1800',color:'#123456'};await writeFile(runtime+'/empty.ysvox.json',JSON.stringify(empty));
let server:ChildProcess|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,client:Client|undefined,log='';const report:any={run:latest.run,status:'running',checks:[],errors:[],views:[],publicForms:[],quarterTurns:[],notifications:[],expectedInvalidationVersions:[],textureUploads:[]},state=async():Promise<Project>=>(await fetch(url+'/api/state').then(r=>r.json())).project;
try{
 server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4401',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);let ready=false;for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok){ready=true;break;}}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}assert.ok(ready);
 client=new Client({name:'shared-face-atlas-verification',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],cwd:process.cwd(),env:{...process.env as Record<string,string>,VOXEL_URL:url},stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const r:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(name,r.isError?'ERROR':'OK');return{...JSON.parse(r.content[0].text),isError:!!r.isError};},call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 browser=await chromium.launch(validationBrowserOptions());report.browser=browser.version();const page=await browser.newPage({viewport:{width:1400,height:1000}});page.setDefaultTimeout(180000);page.on('pageerror',e=>report.errors.push(e.message));page.on('websocket',socket=>socket.on('framereceived',f=>{const n=JSON.parse(f.payload.toString());report.notifications.push({event:n.event,version:n.version,bytes:Buffer.byteLength(f.payload.toString()),fullProject:!!n.project});}));
 await page.addInitScript(()=>{
  const ids=new WeakMap<object,number>();let next=0;(window as any).__faceTextureUploads=[];
  for(const name of ['texImage2D','texSubImage2D']as const){const original=(WebGL2RenderingContext.prototype as any)[name];(WebGL2RenderingContext.prototype as any)[name]=function(...args:any[]){const result=original.apply(this,args),w=args[name==='texImage2D'?3:4],h=args[name==='texImage2D'?4:5],pixels=args[8];if(args.length>=9&&w===192&&h===16&&ArrayBuffer.isView(pixels)){const texture=this.getParameter(this.TEXTURE_BINDING_2D);if(!ids.has(texture))ids.set(texture,++next);(window as any).__faceTextureUploads.push({method:name,textureId:ids.get(texture),width:w,height:h,pixels:Array.from(new Uint8Array(pixels.buffer,pixels.byteOffset,pixels.byteLength))});}return result;};}
 });
 await page.goto(url+'/?atlas=1&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready);report.webgl=await page.evaluate(()=>{const gl=(document.querySelector('#viewport canvas')as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return gl.getParameter(ext?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);});
 const frames=async()=>{for(let k=0;k<6;k++)await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));},sync=async(v:number)=>page.waitForFunction(n=>(window as any).voxelStudio.performance.renderedVersion===n,v),edit=async(commands:any[])=>{const request={expectedVersion:(await state()).version,requestId:crypto.randomUUID(),commands},dry=await call('edit_transaction',{...request,dryRun:true}),r=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(r.version);report.expectedInvalidationVersions.push(r.version);return r;},load=async(file:string)=>{const r=await call('load_project',{filename:file,expectedVersion:(await state()).version});await sync(r.version);report.expectedInvalidationVersions.push(r.version);return state();};
 const capture=async(key:string,view='front',material=false)=>{await page.evaluate(async({view,material})=>{const v=(window as any).voxelStudio;await v.mode('scene');v.clay(!material);v.studio(false);v.referenceLighting(material);v.ao(false);v.bloom(false);v.view(view);},{view,material});await frames();const clip=await page.locator('#viewport').boundingBox();assert.ok(clip);const file='variant-'+key+'.png';await page.screenshot({path:out+'/'+file,clip});const perf=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.equal(perf.meshError,null);assert.equal(perf.renderedVersion,(await state()).version);report.views.push({key,file,view,material,triangles:perf.triangles,renderedVersion:perf.renderedVersion,imageSHA256:createHash('sha256').update(await readFile(out+'/'+file)).digest('hex')});};
 const textureProof=async(label:string,p:Project)=>{await frames();const uploads=await page.evaluate(()=>(window as any).__faceTextureUploads);assert.ok(uploads.length,label+' must upload actual RGBA pixels');assert.equal(new Set(uploads.map((r:any)=>r.textureId)).size,1,label+' must share one GPU texture');const descriptor=Object.values(p.assets).find(a=>a.source?.kind==='catalog-material')!.meshes![0].faceAtlas!,expected=[...faceAtlasPixels(descriptor,p.materials).data];for(const u of uploads)assert.deepEqual(u.pixels,expected,label+' actual GPU bytes');report.textureUploads.push({label,uploads:uploads.length,gpuTextureCount:1,width:192,height:16,pixelsSHA256:hash(expected),actualBytesMatched:true});};
 const lib=await call('read_production_library',{query:'CHAR-023'});assert.equal(lib.entries[0].stage,'material-candidate');assert.equal(lib.entries[0].type,'材质贴图');for(const[k,v]of Object.entries({atlasReferenceCandidates:765,atlasAssemblyCandidates:186,atlasVariantCandidates:63,atlasVariantForms:156,baseModels:533,variantEntries:67,variantModels:165,materialEntries:1,generatedEntries:790,notProduced:278}))assert.equal(lib.counts[k],v);report.libraryCounts=lib.counts;
 for(const row of rows){const recipes=await call('list_production_recipes',{query:row.id}),r=recipes.entries.find((r:any)=>r.id===row.id);assert.equal(r.kind,'variant');assert.equal(r.parentKind,'material');assert.equal(r.parentCatalogId,'CHAR-023');assert.deepEqual(r.parameters.faceCell,{enum:[row.parameters.faceCell],default:row.parameters.faceCell});}await writeFile('docs/tool-schemas.json',JSON.stringify((await client.listTools()).tools,null,2));
 await page.locator('#atlas-sheet').selectOption('M062');await page.locator('[data-atlas-open][data-catalog="CHAR-024"]').first().click();await page.waitForFunction(()=>Object.values((window as any).voxelStudio.project.assemblies??{}).some((a:any)=>a.source?.catalogId==='CHAR-024'));const opened=await state();await sync(opened.version);report.expectedInvalidationVersions.push(opened.version);report.checks.push('Actual M062button opens024; all6official recipes expose exact material parent and UV cell;023library resource is material-candidate,base count533unchanged.');
 for(const row of rows){
  const p=await load(row.file),a=p.assemblies![row.assemblyId];await capture(row.id+'-back','back');await capture(row.id+'-left','left');await edit([{op:'instantiateAssembly',assemblyId:a.id,prefix:'quarter',position:[1,0,1],rotation:1}]);const turned=await state();assert.equal(Object.keys(turned.instances).length,2);const original=a.instances[0],copy=turned.instances['quarter-'+original.id];assert.equal(copy.assetId,original.assetId);assert.deepEqual(copy.position,rotateY(original.position,1).map((v,k)=>v+[1,0,1][k]));assert.equal(copy.rotation,(original.rotation+1)%4);assert.equal(hash(turned.assets),hash(p.assets));await edit([{op:'undo'}]);assert.equal(hash((await state()).instances),hash(p.instances));report.quarterTurns.push({id:row.id,params:row.parameters,passed:true,actualPositionsAndUnchangedAssetsVerified:true});
  const clean=await load('empty.ysvox.json');await edit([{op:'produceCatalogVariant',catalogId:row.id,id:row.assemblyId,params:row.parameters,place:true}]);const made=await state();assert.deepEqual(made.materials[1800],empty.materials[1800]);report.publicForms.push({id:row.id,params:row.parameters,audit:auditFaceVariant(made,made.assemblies![row.assemblyId]),foreignMaterialPreserved:true});await edit([{op:'undo'}]);const undone=await state();for(const key of ['assets','assemblies','instances','materials','styles','palettes','catalog']as const)assert.equal(hash(undone[key]??null),hash(clean[key]??null));
 }
 report.checks.push('All6official creations,6quarterturns and undo retain actual sources,cell choices,ports,native ear details and foreign material1800.');
 await load('empty.ysvox.json');await page.evaluate(()=>(window as any).__faceTextureUploads=[]);await edit(rows.flatMap((r:any,tile:number)=>[{op:'produceCatalogVariant',catalogId:r.id,id:r.assemblyId,params:r.parameters},{op:'instantiateAssembly',assemblyId:r.assemblyId,prefix:'all-'+tile,position:[tile%3*.32,tile<3?.32:0,0],rotation:0}]));const all=await state();for(const a of Object.values(all.assemblies!))assert.ok(auditFaceVariant(all,a).passed);await textureProof('six cells share one actual GPU atlas',all);await writeFile(out+'/six-face-comparison.ysvox.json',JSON.stringify(all));await capture('six-face-comparison');await capture('six-face-comparison-isometric','isometric');await capture('six-face-comparison-material','isometric',true);
 const descriptor=Object.values(all.assets).find(a=>a.source?.kind==='catalog-material')!.meshes![0].faceAtlas!,skin=descriptor.materials.skinSurface,iris=descriptor.materials.eyeIris,gray=descriptor.materials.sparseHair;await page.evaluate(()=>(window as any).__faceTextureUploads=[]);await edit([{op:'definePalette',name:'三用途面孔换色验证',materials:{[skin]:{color:'#234567'},[iris]:{color:'#abcdef'},[gray]:{color:'#556677'}}},{op:'palette',name:'三用途面孔换色验证'}]);const changed=await state();assert.equal(hash(changed.assets),hash(all.assets));for(const[id,m]of Object.entries(all.materials))if(![skin,iris,gray].includes(Number(id)))assert.deepEqual(changed.materials[id],m);await textureProof('skin iris gray recolour actual GPU bytes without geometry change',changed);await capture('three-purpose-palette-change');await page.evaluate(()=>(window as any).__faceTextureUploads=[]);await edit([{op:'undo'}]);const undone=await state();assert.deepEqual(undone.materials,all.materials);assert.equal(hash(undone.assets),hash(all.assets));await textureProof('undo restores original GPU atlas',undone);report.checks.push('Six simultaneous heads share one real GPU texture. Skin/iris/gray-hair edit changes actual texImage2D/texSubImage2D bytes and preserves geometry/other materials;undo restores exact pixels.');
 for(const command of[{op:'produceCatalogVariant',catalogId:'CHAR-024',id:'bad',params:{faceCell:5}},{op:'produceCatalogVariant',catalogId:'CHAR-025',id:'bad',params:{characterTone:'char-030'}},{op:'produceCatalogVariant',catalogId:'CHAR-026',id:'bad',params:{garment:2}},{op:'produceCatalogVariant',catalogId:'CHAR-027',id:'bad',params:{faceCell:6}},{op:'produceCatalogVariant',catalogId:'CHAR-023',id:'bad'},{op:'produceCatalogAsset',catalogId:'CHAR-023',id:'bad'}]){const before=await state(),r=await raw('edit_transaction',{expectedVersion:before.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:1800,properties:{color:'#ffffff'}},command]});assert.ok(r.isError);assert.equal(hash(await state()),hash(before));}
 const malformed=structuredClone(all);Object.values(malformed.assets).find(a=>a.source?.kind==='catalog-material')!.meshes![0].faceAtlas!.width=191 as any;await writeFile(runtime+'/invalid-atlas.ysvox.json',JSON.stringify(malformed));const before=await state(),invalid=await raw('load_project',{filename:'invalid-atlas.ysvox.json',expectedVersion:before.version});assert.ok(invalid.isError);assert.equal(hash(await state()),hash(before));report.checks.push('Six invalid family/cell/type edits and malformed191pxnative atlas reject atomically with no partial material or state edits.');
 const parent=latest.additionalMaterialParents[0];await load(parent.file);await capture('shared-material-parent');const doc=await load(rows[0].file),head=doc.assets[(doc.assemblies![rows[0].assemblyId].source!.faceAtlasVariant as any).installedHeadAssetId],[cell,material]=new Grid(head.chunks).cells().next().value!,queried=await call('query_voxels',{assetId:head.id,region:{min:cell,max:cell.map((v:number)=>v+1)}});assert.equal(queried.total,1);assert.equal(queried.cellSizeM,.005);assert.deepEqual(queried.cells,[[cell,material]]);report.queriedNativeEarCell=queried;
 await call('save_project',{filename:'roundtrip.ysvox.json'});const saved:Project=JSON.parse(await readFile(runtime+'/roundtrip.ysvox.json','utf8'));for(const key of ['assets','assemblies','instances','materials','styles']as const)assert.equal(hash(saved[key]),hash(doc[key]));assert.ok(auditFaceVariant(saved,saved.assemblies![rows[0].assemblyId]).passed);report.checks.push('Material parent opens as actual six-cell swatch;5mmear queried through officialMCP. Native save roundtrip preserves full descriptor,UV,source/removal records and roles.');
 assert.equal(report.publicForms.length,6);assert.equal(report.quarterTurns.length,6);assert.equal(report.views.length,17);assert.deepEqual(report.notifications.map((n:any)=>n.version),report.expectedInvalidationVersions);assert.ok(report.notifications.every((n:any)=>n.event==='state-invalidated'&&!n.fullProject&&n.bytes<65536));assert.deepEqual(report.errors,[]);report.status='passed';
}catch(e:any){report.status='failed';report.errors.push(e.stack??e.message);throw e;}
finally{await browser?.close();await client?.close();if(server){server.kill('SIGTERM');await new Promise<void>(resolve=>{if(server!.exitCode!==null)return resolve();const timer=setTimeout(()=>{server!.kill('SIGKILL');resolve();},5000);server!.once('exit',()=>{clearTimeout(timer);resolve();});});}await writeFile(out+'/variant-mcp-server.txt',log);await writeFile(out+'/variant-mcp-verification.json',JSON.stringify(report,null,2));}
console.log(JSON.stringify({status:report.status,publicForms:report.publicForms.length,quarterTurns:report.quarterTurns.length,views:report.views.length,checks:report.checks.length,notifications:report.notifications.length}));
