import {nativeIslandAttachments} from '../src/production/mixed-review';
import {careSceneAudit,careApertureAudit} from './lib/care-audit';
import {readFile,writeFile} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {Matrix4,Vector3} from 'three';import {NodeIO} from '@gltf-transform/core';import {KHRMaterialsEmissiveStrength,KHRMaterialsUnlit} from '@gltf-transform/extensions';import {makeCareAsset,careRecipes} from '../src/production/atlas-care';import {careScenes,careScene} from '../src/production/care-assembly';import {makeFigureAsset,figureProportions} from '../src/production/atlas-figure';import {productionProject} from '../src/production/style';import {geometryData} from '../src/core/sky';import {posedRigPorts} from '../src/core/rig';import {displayMesh} from '../src/core/mesh';import {auditShape,penetration} from './lib/mesh-audit';import {gltfPoints,pointBounds} from './lib/skin-audit';import type {Asset,Project} from '../src/core/types';
const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),out=latest.evidence,hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex'),report:any={run:latest.run,status:'running',masters:[],scenes:[],fits:[],turns:[],openings:{}},io=new NodeIO().registerExtensions([KHRMaterialsEmissiveStrength,KHRMaterialsUnlit]);
for(const row of latest.models){const p:Project=JSON.parse(await readFile(path.join('projects',row.file),'utf8')),a=p.assets[row.assetId],made=makeCareAsset(row.id,a.name,a.id,p.styles.yunshan,a.source!.parameters as any),native=JSON.parse(await readFile(path.join(latest.out,'exports',row.id,'voxels.ysvox.json'),'utf8'));assert.equal(hash(geometryData(made)),row.sha256);assert.deepEqual(a.ports,made.ports);assert.deepEqual(native.assets[a.id],a);report.masters.push({id:row.id,geometrySHA256:row.sha256,recipeMatchesSavedAndExported:true,portsMatch:true});}
for(const kind of careScenes){const name='care-'+kind,p:Project=JSON.parse(await readFile(path.join(out,name+'.ysvox.json'),'utf8')),native=JSON.parse(await readFile(path.join(out,name+'-export/voxels.ysvox.json'),'utf8')),collision=JSON.parse(await readFile(path.join(out,name+'-export/collision.json'),'utf8')),interfaces=JSON.parse(await readFile(path.join(out,name+'-export/interfaces.json'),'utf8')),g=await io.read(path.join(out,name+'-export/visual.glb')),nodes=g.getRoot().listScenes()[0].listChildren(),expected=careScene(productionProject('verify'),kind);assert.equal(nodes.length,Object.keys(p.instances).length);assert.deepEqual(native.assets,p.assets);assert.deepEqual(native.instances,p.instances);assert.deepEqual(interfaces.instances,Object.values(p.instances));assert.ok(collision.assets.filter((a:any)=>Object.values(p.instances).some(i=>i.assetId===a.id)).every((a:any)=>!a.cells.length&&!(a.meshes??[]).length));assert.deepEqual(p.instances,expected.instances);for(const[id,a]of Object.entries(p.assets)){assert.equal(hash(geometryData(a)),hash(geometryData(expected.assets[id])),kind+'/'+id);if(a.category==='import')assert.equal(a.source!.notCatalogMaster,true);}
 let maxError=0;for(const node of nodes){const a=p.assets[String(node.getExtras().assetId)],matrix=new Matrix4().fromArray(node.getWorldMatrix()),expected=pointBounds(displayMesh(a,p.materials).flatMap(b=>Array.from({length:b.positions.length/3},(_,i)=>new Vector3(...b.positions.slice(i*3,i*3+3)).applyMatrix4(matrix)))),actual=pointBounds(gltfPoints(node)),error=Math.max(...actual.min.map((v,i)=>Math.abs(v-expected.min[i])),...actual.max.map((v,i)=>Math.abs(v-expected.max[i])));assert.ok(error<3e-7,name);maxError=Math.max(maxError,error);const port=interfaces.assets.find((v:any)=>v.id===a.id);assert.deepEqual(port.ports,a.ports);if(a.rig){assert.deepEqual(port.rig,a.rig);assert.deepEqual(port.posedPorts,posedRigPorts(a));assert.equal(node.getSkin()!.listJoints().length,a.rig.joints.length);}}
 const underlayers=Object.values(p.assets).filter(a=>a.category==='import'&&a.source?.sourceAssetId).map(a=>({id:a.id,sourceRetained:!!p.assets[String(a.source!.sourceAssetId)]}));assert.ok(underlayers.every(r=>r.sourceRetained));
 report.scenes.push({name,underlayers,instances:nodes.length,retainedSources:Object.keys(p.assets).length,sourceAndDerivativeGeometryMatch:true,GLBIndependentPoseBoundsMaxErrorM:maxError,placedAssetsHaveEmptyCollision:true,retainedUnplacedSourceCollisionPreserved:true,portRoundtrip:true,skins:g.getRoot().listSkins().length});
}
report.fits=careSceneAudit();report.openings=careApertureAudit();
report.status='passed';report.limitations=['Twenty-four finite static forms, seven finite grips; variants shown off-hand.','Empty carrier remains unvalidated on an actual infant/adult; package and food bag have no two-arm support study.','Independent cat/dog silhouettes have only a single prop root; no gait, soft fur or animal runtime.','Exact original LIFE069 cells and pitch retained with semantic remap; continuous bail and separate contents added.','Source dimensions, protected clearance and original controller unavailable.'];await writeFile(path.join(out,'care-installation-verification.json'),JSON.stringify(report,null,2));await writeFile(path.join(out,'final-geometry-recheck.json'),JSON.stringify({run:latest.run,status:'passed',masters:report.masters,scenes:report.scenes},null,2));console.log(JSON.stringify(report,null,2));
