import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {NodeIO} from '@gltf-transform/core';
import {KHRMaterialsEmissiveStrength} from '@gltf-transform/extensions';
import {validationBrowserOptions} from './browser-options';
import {parseCatalogCSV} from '../src/core/catalog';
import {productionProject} from '../src/production/style';
import * as assembly from '../src/production/urban-assembly';
import type {Command,Project,V3} from '../src/core/types';

const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),out=latest.evidence,runtime=path.join(out,`urban-mcp-${Date.now()}-runtime`),url='http://127.0.0.1:4358',gallery=index.studies.find((s:any)=>s.id==='M022-gallery');assert.ok(gallery);
await mkdir(runtime,{recursive:true});for(const f of['atlas-production-index.json','production-index.json',gallery.file,...index.entries.filter((e:any)=>e.sheet==='M022').map((e:any)=>e.file)])await copyFile(path.join('projects',f),path.join(runtime,f));
await cp('projects/reference-atlas',path.join(runtime,'reference-atlas'),{recursive:true});await copyFile(path.join(runtime,gallery.file),path.join(runtime,'autosave.ysvox.json'));
const empty=productionProject('M022 · 真实 MCP 拼装');empty.catalog={sourceName:'city-assets.csv',importedAt:'verification',entries:Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]))};await writeFile(path.join(runtime,'empty.ysvox.json'),JSON.stringify(empty));
const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),state=async():Promise<Project>=>(await fetch(url+'/api/state').then(r=>r.json())).project;
const report:any={run:index.run,startedAt:new Date().toISOString(),status:'running',checks:[],errors:[],uiSync:[],assemblies:[]};let server:ChildProcess|undefined,client:Client|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,log='';
async function start(){server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4358',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok)return;}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}throw new Error('Server startup timeout');}
async function stop(){if(server&&server.exitCode===null){const closed=once(server,'exit');server.kill('SIGTERM');await closed;}}
function clean(c:any,unsupported:string[]=[],nearPairs:string[][]=[]){assert.deepEqual(c.unsupported,unsupported);assert.deepEqual(c.gaps.map((g:any)=>g.instances),nearPairs);for(const g of c.gaps)assert.ok(Math.abs(g.distanceM-.1)<1e-8);for(const k of['collisions','warnings'])assert.deepEqual(c[k],[],k);assert.ok(c.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));assert.ok(c.clearances.every((o:any)=>o.clear));}
try{
 await start();client=new Client({name:'urban-semantic-validation',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],env:{...process.env as Record<string,string>,VOXEL_URL:url},cwd:process.cwd(),stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const t=performance.now(),r:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(JSON.stringify({tool:name,ms:performance.now()-t,error:!!r.isError}));return{...JSON.parse(r.content[0].text),isError:!!r.isError};};
 const call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 browser=await chromium.launch(validationBrowserOptions());report.browser=browser.version();const page=await browser.newPage({viewport:{width:1600,height:1050}});page.setDefaultTimeout(120000);page.on('pageerror',e=>report.errors.push(e.message));await page.goto(url+'/?atlas=1&sheet=M022&asset=built-218&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready,null,{timeout:120000});
 report.webgl=await page.evaluate(()=>{const gl=(document.querySelector('#viewport canvas') as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return gl.getParameter(ext?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);});
 const sync=async(v:number)=>{const t=performance.now();await page.waitForFunction(n=>(window as any).voxelStudio.performance.renderedVersion===n,v,{timeout:120000});report.uiSync.push({version:v,ms:performance.now()-t});};
 const before=await state(),roles=before.styles.yunshan,check=await call('check_geometry');clean(check);assert.equal(check.collisionGrids.length,12);report.gallery=check;
 for(const [assetId,point,role]of[
  ['built-207',[1,.2,2],'structuralConcrete'],['built-208',[1.9,3,1.5],'structuralConcrete'],['built-209',[1,.85,1],'structuralConcrete'],['built-210',[.5,.6,.175],'glass'],
  ['built-212',[2.2,1.95,2.2],'wall'],['built-213',[.5,1.075,6.075],'wall'],['built-214',[.125,.175,.4],'metalBright'],['built-215',[1.1,.15,.1],'wall'],
  ['built-216',[.4,.25,.05],'wall'],['built-217',[1.6,.375,.6],'wall'],['built-218',[.5,1,.17],'glass'],['built-218',[.215,1,.17],'facadeSeal'],['built-218',[1.35,1,.15],'facadeFrame'],['built-219',[.09,1,.3],'sunshadeMetal'],
 ] as [string,V3,string][]){const a=before.assets[assetId],v=point.map(n=>Math.floor((n+1e-8)/a.cellSize)),r=await call('query_voxels',{assetId,region:{min:v,max:v.map(n=>n+1)}});assert.equal(r.cells[0]?.[1],roles[role]);}
 for(const z of[.13,.21]){const a=before.assets['built-218'],v=[.5,1,z].map(n=>Math.floor((n+1e-8)/a.cellSize)),r=await call('query_voxels',{assetId:'built-218',region:{min:v,max:v.map(n=>n+1)}});assert.equal(r.total,0,'Both glass faces are clear of opaque seal cells');}
 report.checks.push('Twelve M022 families verified from actual native coordinates: stone, concrete, metal grating, optical glass, facade seal, coated frame and anodised shade aluminium');
 const changed=['facadeFrame','sunshadeMetal','facadeSeal','glass'],request={expectedVersion:before.version,requestId:crypto.randomUUID(),label:'M022街台幕墙独立外观包验证',commands:[{op:'definePalette',name:'幕墙独立材质',materials:Object.fromEntries(changed.map((r,i)=>[roles[r],{color:['#703943','#33806b','#455456','#85abb6'][i]}]))},{op:'palette',name:'幕墙独立材质'}]};
 const dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(before));const applied=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(applied.version);const after=await state();assert.equal(applied.modifiedVoxels,0);for(const k of['assets','styles']as const)assert.equal(hash(after[k]),hash(before[k]));
 for(const[id,m]of Object.entries(before.materials)){assert.equal(after.materials[id].solid,m.solid);assert.equal(after.materials[id].category,m.category);if(!changed.some(r=>String(roles[r])===id))assert.deepEqual(after.materials[id],m);}assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(after.materials));
 await page.locator('#material-category-filter').selectOption('rubber');const buttons=await page.locator('[data-material]').evaluateAll(nodes=>nodes.map(n=>Number((n as HTMLElement).dataset.material)));assert.ok(buttons.includes(roles.facadeSeal));for(const id of buttons)assert.equal(after.materials[id].category,'rubber');await page.locator('[data-material="'+roles.facadeSeal+'"]').click();assert.match(await page.locator('#material-role').innerText(),/yunshan.facadeSeal/);await page.screenshot({path:path.join(out,'mcp-urban-roles.png')});
 assert.equal((await call('edit_transaction',request)).version,applied.version);assert.equal((await raw('edit_transaction',{...request,requestId:crypto.randomUUID()})).code,'VERSION_CONFLICT');const failed=await raw('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:roles.facadeSeal,properties:{color:'#ff00ff'}},{op:'produceCatalogAsset',catalogId:'BUILT-207',id:'bad',params:{component:'cap'}}]});assert.ok(failed.isError);assert.equal(hash(await state()),hash(after));
 const undo=await call('edit_transaction',{expectedVersion:after.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(undo.version);for(const k of['assets','styles','materials','palettes']as const)assert.equal(hash((await state())[k]),hash(before[k]));await page.screenshot({path:path.join(out,'mcp-urban-roles-restored.png')});report.checks.push('Four independent architectural appearance roles, canonical UI hashes, rubber filtering, dry run, version conflicts, idempotency, failure rollback and one undo all verified');
 const scenario=async(name:string,commands:Command[],clearances:{name:string;min:V3;max:V3}[],unsupported:string[]=[],nearPairs:string[][]=[])=>{
  const loaded=await call('load_project',{filename:'empty.ysvox.json',expectedVersion:(await state()).version});await sync(loaded.version);const request={expectedVersion:loaded.version,requestId:crypto.randomUUID(),commands},initial=await state(),dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash(await state()),hash(initial));const built=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(built.version);await page.evaluate(()=>(window as any).voxelStudio.mode('scene'));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const geometry=await call('check_geometry',{clearances});clean(geometry,unsupported,nearPairs);const doc=await state();assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets)),hash(doc.assets));await page.screenshot({path:path.join(out,'mcp-'+name+'.png')});
  const saved=await call('save_project',{filename:name+'.ysvox.json'});await copyFile(saved.path,path.join(out,name+'.ysvox.json'));const exported=await call('export_project',{name}),round=JSON.parse(await readFile(path.join(exported.directory,'voxels.ysvox.json'),'utf8'));for(const k of['assets','instances','materials','styles']as const)assert.equal(hash(round[k]),hash(doc[k]));await cp(exported.directory,path.join(out,name+'-export'),{recursive:true});
  const previews=await call('generate_previews',{appearance:'baseColor',views:['isometric','front']});assert.equal(previews.files.length,2);for(let i=0;i<2;i++){assert.ok((await readFile(previews.files[i])).length>1000);await copyFile(previews.files[i],path.join(out,name+'-view-'+i+'.png'));}report.assemblies.push({name,masters:Object.keys(doc.assets).length,placements:Object.keys(doc.instances).length,geometry,expectedUnsupported:unsupported,expectedNearPairs:nearPairs,exported,previews});return doc;
 };
 await page.locator('#material-category-filter').selectOption('all');
 const recipes=await call('list_production_recipes',{query:'BUILT-207'});assert.deepEqual(recipes.entries[0].parameters.component.enum,['liftLanding','bankLanding']);report.checks.push('MCP exposes named, recipe-specific component choices; family counts do not increase when producing a second structural component');
 const landing=await scenario('urban-landing',assembly.urbanLandingCommands(),assembly.urbanLandingClearances);assert.equal(landing.assets.bank.source!.component,'bankLanding');assert.equal(landing.assets.corner.source!.component,'corner');report.checks.push('Independent lift and bank landings plus straight/corner guardrails preserve a real shaft opening and authored 0.35m-radius,1.72m body clearance');
 const foundation=await scenario('urban-foundation',assembly.urbanFoundationCommands(roles),assembly.urbanFoundationClearances,assembly.urbanFoundationUnsupported);assert.deepEqual(foundation.instances['cap-1'].position,[0,251.6,2.4]);assert.equal(foundation.instances['beam-1'].position[1],252.8);assert.equal((foundation.assets.footing.source!.isolatedBridge as any).countsReconstructed,false);report.checks.push('Four positive-height footings mate to twenty explicit sample contact bands, then support foundation/pier/cap/M021 beam/deck; finite sample terrain retains its unsupported lower boundary and original-game failures remain unresolved');
 const glb=await new NodeIO().registerExtensions([KHRMaterialsEmissiveStrength]).read(path.join(out,'urban-foundation-export','visual.glb')),node=glb.getRoot().listNodes().find(n=>n.getExtras().instanceId==='deck-1')!;assert.ok(node);assert.deepEqual(node.getTranslation(),[0,254,0]);const positions=node.getMesh()!.listPrimitives().flatMap(p=>Array.from(p.getAttribute('POSITION')!.getArray()!).filter((_,i)=>i%3===1)),top=Math.max(...positions)+node.getTranslation()[1];assert.ok(Math.abs(top-254.6)<1e-6);report.highBridgeGLB={deckTranslation:node.getTranslation(),worldTopYM:top};
 const market=await scenario('urban-market',assembly.urbanMarketCommands(),assembly.urbanMarketClearances);assert.equal((market.assets.stairs.source!.stair as any).count,10);assert.equal((market.assets.ramp.source!.ramp as any).analyticSlope,false);report.checks.push('Finite 2m platform, solid voxel ramp, ten 0.2m steps and low kerb align; native top surfaces and closed bottoms remain authoritative without claiming original MarketSurface or 24tick behaviour');
 const drain=await scenario('urban-drain',assembly.urbanDrainCommands(roles),assembly.urbanDrainClearances);assert.equal(drain.assets.ring.source!.component,'treeRing');report.checks.push('Separate drain cover has real grille slots; tree ring stays hollow and all three retaining-wall weeps remain clear through finite auxiliary soil');
 const facade=await scenario('urban-facade',assembly.urbanFacadeCommands(roles),assembly.urbanFacadeClearances);assert.equal(Object.values(facade.instances).filter(i=>i.assetId==='shade').length,9);assert.equal((facade.assets.facade.source!.facade as any).originalFloorPlanAvailable,false);report.checks.push('Two storeys of recessed glass and independent seals receive nine shade blades through actual bracket pockets; interior, side route and above-roof volumes stay clear');
 report.checks.push('All five scenarios save real stdio MCP multiview previews plus GLB/native/collision/interface/material-atlas exports');
 const last=await call('save_project',{filename:'verified-urban-facade.ysvox.json'}),saved=await state();assert.equal(hash(JSON.parse(await readFile(last.path,'utf8'))),hash(saved));await stop();await start();assert.equal(hash(await state()),hash(saved));report.checks.push('Native save and server restart restore the exact canonical document');
 assert.deepEqual(report.errors,[]);report.status='passed';report.completedAt=new Date().toISOString();console.log(JSON.stringify({status:report.status,checks:report.checks.length,out}));
}catch(error){report.status='failed';report.errors.push(String(error));throw error;}finally{await browser?.close();await client?.close();await stop();await writeFile(path.join(out,'urban-mcp-verification.json'),JSON.stringify(report,null,2));await writeFile(path.join(out,'urban-mcp-server.log'),log);}
