import {readFile,writeFile} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {Box3,Triangle,Vector3,Ray} from 'three';import {NodeIO} from '@gltf-transform/core';import {KHRMaterialsEmissiveStrength,KHRMaterialsUnlit} from '@gltf-transform/extensions';import {checkFloat32Bounds} from '../src/export/precision';import {assetBoundsM} from '../src/core/sky';import {Grid} from '../src/core/grid';import {nativeIslandAttachments} from '../src/production/mixed-review';import type {Project,V3} from '../src/core/types';
const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),out=latest.evidence,report:any={run:latest.run,status:'running',scenes:[]},io=new NodeIO().registerExtensions([KHRMaterialsEmissiveStrength,KHRMaterialsUnlit]);
for(const name of ['standing','seated','far','robe','bonsai']){const p:Project=JSON.parse(await readFile(path.join(out,'character-'+name+'.ysvox.json'),'utf8')),collision=JSON.parse(await readFile(path.join(out,'character-'+name+'-export/collision.json'),'utf8')),g=await io.read(path.join(out,'character-'+name+'-export/visual.glb')),nodes=g.getRoot().listScenes()[0].listChildren();assert.equal(nodes.length,Object.keys(p.instances).length);
 const checks:any={name,sourceMasters:Object.values(p.assets).filter(a=>a.category==='base').length,geometrySource:'saved scene, saved GLB and saved collision',maxBoundsErrorM:0};for(const node of nodes){const a=p.assets[String(node.getExtras().assetId)],actual={min:[Infinity,Infinity,Infinity],max:[-Infinity,-Infinity,-Infinity]},expected=assetBoundsM(a)!;for(const prim of node.getMesh()!.listPrimitives()){const arr=prim.getAttribute('POSITION')!.getArray()!;for(let k=0;k<arr.length;k++){const d=k%3;actual.min[d]=Math.min(actual.min[d],arr[k]);actual.max[d]=Math.max(actual.max[d],arr[k]);}assert.equal(prim.getAttribute('POSITION')!.getCount(),prim.getAttribute('NORMAL')!.getCount());}assert.ok(checkFloat32Bounds(expected,actual).matchesFloat32Rounding);checks.maxBoundsErrorM=Math.max(checks.maxBoundsErrorM,...actual.min.map((n,i)=>Math.abs(n-expected.min[i])),...actual.max.map((n,i)=>Math.abs(n-expected.max[i])));}
 if(name!=='bonsai'){assert.ok(collision.assets.every((a:any)=>a.cells.length===0&&a.meshes.length===0));assert.equal((g.getRoot().listMeshes()[0].getExtras().authorStaticPose as Record<string,unknown>)?.pose,name);const a=p.assets['pose-'+name],source=a.source!;assert.equal(source.originalSkeletonBound,false);checks.collisionGeometryCount=0;checks.retainedEditableMasters=true;checks.rigBinding=false;checks.skinning=false;checks.robeVisible=source.robeVisible;checks.sourcePlacements=source.placements;}
 else{const tree=p.assets['env-134'],pot=p.assets['env-097'],pg=new Grid(pot.chunks),plant=new Grid(tree.chunks);let contacts=0;for(const[v,m]of plant.cells())if(v[1]===4&&p.materials[m].solid){const local=[v[0]+17,3,v[2]+11] as V3;if(pg.get(local)&&p.materials[pg.get(local)].solid)contacts++;}assert.ok(contacts>=400);checks.actualSoilBottomContacts=contacts;
 const potBoxes=[...pg.cells()].filter(([,m])=>p.materials[m].solid).map(([v])=>new Box3(new Vector3(...v.map((n,i)=>n*.04+p.instances.pot.position[i])),new Vector3(...v.map((n,i)=>(n+1)*.04+p.instances.pot.position[i]))).expandByScalar(-1e-7)),drain=new Box3(new Vector3(-.08,.08,-.08),new Vector3(.08,.24,.08)).expandByScalar(-1e-7);let testedTriangles=0,penetrations=0,drainHits=0,containedPotCells=0;
 for(const m of tree.meshes!.filter(m=>m.collision)){const triangles:Triangle[]=[];for(let k=0;k<m.indices.length;k+=3){const tri=new Triangle(...m.indices.slice(k,k+3).map(i=>new Vector3(...m.positions.slice(i*3,i*3+3))) as [Vector3,Vector3,Vector3]);triangles.push(tri);testedTriangles++;if(drain.intersectsTriangle(tri))drainHits++;for(const b of potBoxes)if(b.intersectsTriangle(tri))penetrations++;}
 const bounds=new Box3().setFromPoints(triangles.flatMap(t=>[t.a,t.b,t.c]));for(const b of potBoxes){const c=b.getCenter(new Vector3());if(!bounds.containsPoint(c))continue;const ray=new Ray(c,new Vector3(1,.293,.157).normalize()),hits:number[]=[];for(const t of triangles){const hit=ray.intersectTriangle(t.a,t.b,t.c,false,new Vector3());if(hit){const d=c.distanceTo(hit);if(!hits.some(v=>Math.abs(v-d)<1e-8))hits.push(d);}}if(hits.length%2)containedPotCells++;}}
 assert.equal(penetrations,0,'branch mesh penetrates pot wall');assert.equal(containedPotCells,0);assert.equal(drainHits,0,'real mesh blocks retained drain');const actualCollision=collision.assets.find((a:any)=>a.id===tree.id);assert.deepEqual(actualCollision.meshes.map((m:any)=>({positions:m.positions,indices:m.indices})),tree.meshes!.filter(m=>m.collision).map(m=>({positions:m.positions,indices:m.indices})));const attachments=nativeIslandAttachments(tree);assert.ok(attachments.every(r=>r.attached));checks.continuousMesh={testedTriangles,potSurfacePenetrations:penetrations,containedPotCells,drainHits,collisionMatchesVisualVertices:true};checks.nativeAttachments=attachments;checks.centerOfMass='not computed: material density and overlapping-volume union are not provided; no physical stability claim';checks.actualPotBoundsM=assetBoundsM(pot);}
 report.scenes.push(checks);
}
report.status='passed';report.limitations=['Four character studies are static rigid transforms of retained component masters, not animation/skin weighting or original runtime integration.','ENV097 shallow pot is an explicit dependency variant of its existing master; original square and jar are retained.','Triangle checks verify branch/pot separation and the reserved drain. They do not certify structural strength, physics or centre of mass.'];await writeFile(path.join(out,'character-installation-verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
