import {mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {chromium} from 'playwright';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {validateProject} from '../src/core/engine';
import {Grid} from '../src/core/grid';
import type {Project,Command} from '../src/core/types';
const root=path.resolve('artifacts/catalog'),runtime=path.join(root,'runtime'),url='http://127.0.0.1:4340';
await mkdir(runtime,{recursive:true});
const p:Project=(await fetch('http://127.0.0.1:4317/api/state').then(r=>r.json())).project;
validateProject(p);await writeFile(path.join(runtime,'autosave.ysvox.json'),JSON.stringify(p));
const csv=await readFile('projects/catalog/city-assets.csv','utf8'),hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4340',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});
let log='';server.stdout.on('data',d=>log+=d);server.stderr.on('data',d=>log+=d);
let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,client:Client|undefined;
const report:any={startedAt:new Date().toISOString(),environment:{os:os.release(),arch:os.arch(),cpu:os.cpus()[0].model,memoryBytes:os.totalmem(),node:process.version},sourceMasters:Object.keys(p.assets).length,sourceVoxels:Object.values(p.assets).reduce((n,a)=>n+new Grid(a.chunks).count,0),checks:[],errors:[]};
try{
 for(let i=0;i<100;i++){try{if((await fetch(url+'/api/state')).ok)break;}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}
 client=new Client({name:'catalog-regression',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],cwd:process.cwd(),env:{...process.env as Record<string,string>,VOXEL_URL:url},stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const result:any=await client!.callTool({name,arguments:args});return{...JSON.parse(result.content[0].text),isError:result.isError};};
 const call=async(name:string,args:any={})=>{const result=await raw(name,args);if(result.isError)throw new Error(JSON.stringify(result));delete result.isError;return result;};
 const state=()=>fetch(url+'/api/state').then(r=>r.json());
 const edit=async(commands:Command[])=>{const e={expectedVersion:(await state()).project.version,requestId:crypto.randomUUID(),commands},dry=await call('edit_transaction',{...e,dryRun:true});return call('edit_transaction',{...e,previewToken:dry.previewToken});};
 browser=await chromium.launch({headless:true});report.environment.browser=browser.version();
 const page=await browser.newPage({viewport:{width:1660,height:1100}});page.on('pageerror',e=>report.errors.push(e.message));
 const wait=()=>page.waitForFunction(()=>!!(window as any).voxelStudio?.ready,null,{timeout:120000});
 const sync=(v:number)=>page.waitForFunction(v=>(window as any).voxelStudio?.performance.renderedVersion===v,v,{timeout:120000});
 const perf=()=>page.evaluate(()=>(window as any).voxelStudio.performance);
 const start=performance.now();await page.goto(url+'/?asset=study-lantern&view=perspective&flat=1');await wait();
 report.coldLantern={navigationToReadyMs:performance.now()-start,...await perf()};
 report.environment.webgl=await page.evaluate(()=>{const gl=(document.querySelector('canvas') as HTMLCanvasElement).getContext('webgl2')!,e=gl.getExtension('WEBGL_debug_renderer_info');return gl.getParameter(e?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);});
 assert.deepEqual(report.coldLantern.cachedAssetIds,['study-lantern']);assert.equal(report.coldLantern.meshJobs,1);report.checks.push('direct asset URL meshes one master only');
 const baseJobs=(await perf()).meshJobs,version=(await state()).project.version,env={expectedVersion:version,requestId:'catalog-'+crypto.randomUUID(),commands:[{op:'importCatalog',csv,sourceName:'city-assets.csv'}]};
 const dry=await call('edit_transaction',{...env,dryRun:true});assert.equal((await call('read_catalog')).summary.total,0);
 const committed=await call('edit_transaction',{...env,previewToken:dry.previewToken});await sync(committed.version);assert.equal((await perf()).meshJobs,baseJobs);assert.equal((await call('edit_transaction',env)).version,committed.version);
 const catalog=await call('read_catalog',{limit:2});assert.equal(catalog.summary.total,1068);assert.equal(catalog.entries.length,2);assert.equal(catalog.summary.stages.accepted,0);assert.equal(Object.keys((await state()).project.assets).length,report.sourceMasters);
 report.catalog=catalog.summary;report.checks.push('1068 real CSV records through stdio MCP; dry-run/idempotency/versioned WebSocket sync; no geometry jobs or artificial model counts');
 await page.locator('[data-tab="catalog"]').click();await page.locator('#catalog-search').fill('BUILT-249');await page.locator('[data-catalog-id="BUILT-249"]').click();
 await page.locator('#catalog-assets').selectOption(['study-lantern']);await page.locator('#catalog-edit-stage').selectOption('modeling');await page.locator('#catalog-note').fill('隔离测试：灯笼候选母版，尚未游戏内验收。');
 await page.getByRole('button',{name:'保存制作记录',exact:true}).click();await page.waitForFunction(v=>(window as any).voxelStudio.version>v,committed.version);await wait();
 assert.deepEqual((await call('read_catalog',{id:'BUILT-249'})).entries[0].assetIds,['study-lantern']);
 await page.locator('#toast').waitFor({state:'hidden',timeout:15000});await page.screenshot({path:path.join(root,'catalog-editor.png')});
 report.checks.push('visible UI search/filter and editing production records persisted to shared MCP document');
 await sync((await edit([{op:'undo'}])).version);assert.deepEqual((await call('read_catalog',{id:'BUILT-249'})).entries[0].assetIds,[]);
 await sync((await edit([{op:'undo'}])).version);assert.equal((await call('read_catalog')).summary.total,0);
 await sync((await edit([{op:'redo'}])).version);assert.equal((await call('read_catalog')).summary.total,1068);report.checks.push('undo removes newly introduced catalog field; redo restores all source rows');
 const before=await state(),bad=await raw('edit_transaction',{expectedVersion:before.project.version,requestId:crypto.randomUUID(),commands:[{op:'catalogEntry',id:'BUILT-001',note:'rollback'},{op:'catalogEntry',id:'missing',note:'fail'}]});assert.ok(bad.isError);assert.equal(hash((await state()).project),hash(before.project));assert.equal((await raw('edit_transaction',{expectedVersion:version,requestId:crypto.randomUUID(),commands:[{op:'renameProject',name:'stale'}]})).code,'VERSION_CONFLICT');report.checks.push('invalid catalog batch rollback and stale-version conflict');
 const startPlanter=performance.now();await page.evaluate(()=>(window as any).voxelStudio.mode('asset','study-planter'));await wait();report.firstPlanter={openToReadyMs:performance.now()-startPlanter,...await perf()};
 const nativeHash=hash((await state()).project.assets['study-planter'].chunks),region={min:[28,40,5],max:[94,86,55]};
 await page.evaluate(r=>(window as any).voxelStudio.isolate(r),region);await wait();assert.deepEqual((await perf()).isolatedRegion,region);assert.equal(hash((await state()).project.assets['study-planter'].chunks),nativeHash);await page.locator('#toast').waitFor({state:'hidden',timeout:15000});await page.screenshot({path:path.join(root,'isolated-leaves.png')});
 await page.evaluate(()=>(window as any).voxelStudio.isolate(null));await wait();assert.equal(hash((await state()).project.assets['study-planter'].chunks),nativeHash);report.checks.push('selection isolation shows real cut geometry and restores full model without modifying native cells');
 await page.evaluate(()=>(window as any).voxelStudio.mode('asset','study-railing'));await wait();
 await page.evaluate(()=>(window as any).voxelStudio.mode('asset','study-planter'));await wait();const jobs=(await perf()).meshJobs;
 const cell=[...new Grid((await state()).project.assets['study-railing'].chunks).cells()][0][0];const change=await edit([{op:'voxels',assetId:'study-railing',mode:'replace',cells:[cell],material:11}]);await sync(change.version);assert.equal((await perf()).meshJobs,jobs);
 await page.evaluate(()=>(window as any).voxelStudio.mode('asset','study-railing'));await wait();assert.deepEqual((await perf()).meshedAssetIds,['study-railing']);assert.equal((await perf()).meshJobs,jobs+1);report.checks.push('hidden master edit defers meshing and invalidates its own cached snapshot when reopened');
 const paletteJobs=(await perf()).meshJobs;await sync((await edit([{op:'material',id:201,properties:{roughness:.7,color:'#c5c0a8'}}])).version);assert.equal((await perf()).meshJobs,paletteJobs);await sync((await edit([{op:'material',id:201,properties:{opacity:.5}}])).version);assert.equal((await perf()).meshJobs,paletteJobs+1);report.checks.push('colour/roughness reuse geometry; transparent boundary changes rebuild it');
 // Independent tiny fixtures exercise eviction, never installed into the user's library.
 const fixtures=Array.from({length:10},(_,i)=>'cache-test-'+i);await sync((await edit(fixtures.flatMap(id=>[{op:'createAsset',id,name:id,template:'empty',cellSize:.1},{op:'voxels',assetId:id,mode:'add',cells:[[0,0,0]],material:1}]))).version);
 for(const id of fixtures){await page.evaluate(id=>(window as any).voxelStudio.mode('asset',id),id);await wait();}
 report.cacheEviction=await perf();assert.ok(report.cacheEviction.cachedAssetIds.length<=9);assert.ok(!report.cacheEviction.cachedAssetIds.includes('study-lantern'));report.checks.push('inactive geometry cache evicts old masters (8 inactive + visible; 128 MiB inactive pressure limit)');
 const saved=await call('save_project',{filename:'catalog-regression.ysvox.json'}),disk=JSON.parse(await readFile(saved.path,'utf8'));validateProject(disk);assert.equal(hash(disk),hash((await state()).project));report.checks.push('native save retains source records and all geometry without loss');
 const list=await client.listTools();await writeFile(path.join(root,'tool-schemas.json'),JSON.stringify(list.tools,null,2));assert.ok(list.tools.some(t=>t.name==='read_catalog'));
 assert.deepEqual(report.errors,[]);report.completedAt=new Date().toISOString();await writeFile(path.join(root,'verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({checks:report.checks.length,coldLanternMs:report.coldLantern.navigationToReadyMs,planterMs:report.firstPlanter.openToReadyMs,catalog:report.catalog,errors:report.errors},null,2));
}finally{await browser?.close();await client?.close();server.kill('SIGTERM');await writeFile(path.join(root,'server.log'),log);}
