import assert from 'node:assert/strict';import {readFile,writeFile} from 'node:fs/promises';import {spawn} from 'node:child_process';import {once} from 'node:events';import {createHash} from 'node:crypto';import {chromium} from 'playwright';import {validationBrowserOptions} from './browser-options';
const latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),out=latest.evidence,mcp=JSON.parse(await readFile(out+'/assembly-mcp-verification.json','utf8'));assert.equal(mcp.status,'passed');assert.equal(mcp.run,latest.run);const url='http://127.0.0.1:4397',hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4397',VOXEL_PROJECT_DIR:out+'/park-assembly-mcp-runtime'},stdio:['ignore','pipe','pipe']});let log='',browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;server.stdout.on('data',d=>log+=d);server.stderr.on('data',d=>log+=d);const report:any={run:latest.run,status:'running',errors:[],scope:'Actual manual near/far/back browser switching; no automatic distance LOD or physics binding claim.'};
try{
 let ready=false;for(let i=0;i<200;i++){try{if((await fetch(url+'/api/state')).ok){ready=true;break;}}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}assert.ok(ready);const before=(await fetch(url+'/api/state').then(r=>r.json())).project;assert.equal(before.assemblies.trail.source.catalogId,'ENV-102');assert.equal(before.assemblies.trail.source.park.mountainWalk.mode,'ramp');
 browser=await chromium.launch(validationBrowserOptions());const page=await browser.newPage({viewport:{width:1400,height:1000}});page.setDefaultTimeout(120000);page.on('pageerror',e=>report.errors.push(e.message));await page.goto(url+'/?flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready);await page.evaluate(async()=>{const v=(window as any).voxelStudio;await v.mode('scene');v.view('isometric');v.clay(false);v.clip(Infinity);await v.meshMode('near');});const frames=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await frames();report.near=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.equal(report.near.meshError,null);assert.ok(report.near.triangles>0);await page.locator('#viewport').screenshot({path:out+'/assembly-ramp-near.png'});
 await page.evaluate(()=>(window as any).voxelStudio.meshMode('far'));await frames();report.far=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.equal(report.far.meshError,null);assert.ok(report.far.triangles>0&&report.far.triangles<=report.near.triangles);assert.deepEqual([...report.far.assetIds].sort(),[...report.near.assetIds].sort());await page.locator('#viewport').screenshot({path:out+'/assembly-ramp-far.png'});
 await page.evaluate(()=>(window as any).voxelStudio.meshMode('near'));await frames();report.restored=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.equal(report.restored.triangles,report.near.triangles);assert.equal(report.restored.meshError,null);assert.equal(hash((await fetch(url+'/api/state').then(r=>r.json())).project),hash(before));assert.deepEqual(report.errors,[]);report.nativeProjectUnchanged=true;report.status='passed';console.log(JSON.stringify({status:report.status,near:report.near.triangles,far:report.far.triangles}));
}catch(e){report.status='failed';report.errors.push(String(e));throw e;}finally{await browser?.close();if(server.exitCode===null){const closed=once(server,'exit');server.kill();await closed;}await writeFile(out+'/render-mode-verification.json',JSON.stringify(report,null,2));await writeFile(out+'/render-mode-server.log',log);}
