import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {validationBrowserOptions} from './browser-options';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {productionStyleCommands} from '../src/production/style';

const production=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),index=JSON.parse(await readFile('projects/atlas-production-index.json','utf8')),atlas=JSON.parse(await readFile('projects/reference-atlas/index.json','utf8')),root=production.evidence,runtime=path.join(root,'mcp-runtime'),url='http://127.0.0.1:4346',hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
await mkdir(runtime,{recursive:true});for(const file of['atlas-production-index.json','production-index.json',...index.entries.map((e:any)=>e.file),...index.studies.map((e:any)=>e.file)])await copyFile(path.join('projects',file),path.join(runtime,file));await cp('projects/reference-atlas',path.join(runtime,'reference-atlas'),{recursive:true});
await copyFile(path.join(runtime,index.studies.find((e:any)=>e.id==='M001-gallery').file),path.join(runtime,'autosave.ysvox.json'));
let server:ChildProcess|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,client:Client|undefined,log='';const report:any={run:index.run,status:'running',startedAt:new Date().toISOString(),checks:[],errors:[],uiSync:[],environment:{cpu:os.cpus()[0].model,memoryBytes:os.totalmem(),os:os.release(),node:process.version}};
const state=()=>fetch(url+'/api/state').then(r=>r.json());
async function start(){server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4346',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);for(let n=0;n<180;n++){try{if((await fetch(url+'/api/state')).ok)return;}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}throw new Error('Server startup timeout');}
async function stop(){if(server&&server.exitCode===null){const closed=once(server,'exit');server.kill('SIGTERM');await closed;}}
await writeFile(path.join(root,'mcp-verification.json'),JSON.stringify(report,null,2));
try{
 await start();client=new Client({name:'atlas-production-validation',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],env:{...process.env as Record<string,string>,VOXEL_URL:url},cwd:process.cwd(),stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const started=performance.now();const result:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(JSON.stringify({tool:name,elapsedMs:performance.now()-started,isError:!!result.isError}));return{...JSON.parse(result.content[0].text),isError:!!result.isError};};
 const call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 const definitions=await client.listTools();assert.ok(definitions.tools.some(t=>t.name==='read_reference_atlas'));await writeFile('docs/tool-schemas.json',JSON.stringify(definitions.tools,null,2));
 const seen:string[]=[];let offset:number|null=0;while(offset!==null){const r=await call('read_reference_atlas',{offset,limit:100});seen.push(...r.entries.map((e:any)=>e.id));offset=r.nextOffset;assert.equal(r.counts.references,793);assert.equal(r.counts.referenceCandidates,index.entries.length);assert.equal(r.counts.pendingReference,793-index.entries.length);}
 assert.equal(seen.length,793);assert.equal(new Set(seen).size,793);assert.deepEqual(seen,atlas.entries.map((e:any)=>e.id));const last=await call('read_reference_atlas',{sheet:'M067'});assert.equal(last.total,1);assert.equal(last.entries[0].build,undefined);assert.ok((await raw('read_reference_atlas',{sheet:'../../private'})).isError);report.checks.push(`67 verified sheets, 793 unique IDs, ${index.entries.length} saved candidates and ${793-index.entries.length} pending references are paginated over official MCP; variants/layouts are not counted as base models`);
 const library=await call('read_production_library',{query:'LIFE-026'});const originalLibrary=JSON.parse(await readFile('projects/production-index.json','utf8')),newModels=index.entries.filter((x:any)=>originalLibrary.entries.some((o:any)=>o.id===x.id&&o.stage==='not-produced')).length;assert.equal(library.counts.baseModels,originalLibrary.counts.baseModels+newModels);assert.equal(library.counts.generatedEntries,originalLibrary.counts.generatedEntries+newModels);assert.equal(library.entries[0].file,index.entries.find((e:any)=>e.id==='LIFE-026').file);report.checks.push('library counts each newly modelled catalogue ID once while existing upgrades do not duplicate base counts');
 const image=await fetch(url+'/api/reference-atlas/M001.png');assert.ok(image.ok);assert.equal(createHash('sha256').update(Buffer.from(await image.arrayBuffer())).digest('hex'),atlas.sheets[0].sha256);assert.equal((await fetch(url+'/api/reference-atlas/M999.png')).status,400);
 browser=await chromium.launch(validationBrowserOptions());report.environment.browser=browser.version();const page=await browser.newPage({viewport:{width:1600,height:1050}});page.on('pageerror',e=>report.errors.push(e.message));await page.goto(url+'/?atlas=1&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready,null,{timeout:120000});report.environment.webgl=await page.evaluate(()=>{const gl=(document.querySelector('#viewport canvas') as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return gl.getParameter(ext?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);});if(process.argv.includes('--metal'))assert.match(report.environment.webgl,/Metal Renderer/);const sync=async(v:number)=>{const started=performance.now();try{await page.waitForFunction(x=>(window as any).voxelStudio.performance.renderedVersion===x,v,{timeout:120000,polling:100});const measured={version:v,elapsedMs:performance.now()-started};report.uiSync.push(measured);console.log(JSON.stringify({uiSync:measured}));}catch(error){const diagnostic=await Promise.race([page.evaluate(()=>({version:(window as any).voxelStudio.version,performance:(window as any).voxelStudio.performance,toast:document.querySelector('#toast')?.textContent,connection:document.querySelector('#sync')?.textContent,contextLost:(document.querySelector('#viewport canvas') as HTMLCanvasElement).getContext('webgl2')?.isContextLost()})),new Promise<any>(resolve=>setTimeout(()=>resolve({unresponsive:true}),3000))]);await writeFile(path.join(root,'mcp-sync-failure.json'),JSON.stringify({expectedVersion:v,...diagnostic},null,2));throw error;}};
 const catalogCSV=await readFile('projects/catalog/city-assets.csv','utf8'),before=(await state()).project,request={expectedVersion:before.version,requestId:crypto.randomUUID(),label:'图册 MCP 建模验证',commands:[...productionStyleCommands(),{op:'importCatalog',sourceName:'city-assets.csv',csv:catalogCSV},{op:'createAsset',id:'mcp-fine-grid',name:'5mm 网格验证',template:'empty',cellSize:.005},{op:'voxels',assetId:'mcp-fine-grid',mode:'add',cells:[[0,0,0],[1,0,0]],material:2},{op:'produceCatalogAsset',catalogId:'LIFE-158',id:'mcp-camera'},{op:'produceCatalogAsset',catalogId:'LIFE-148',id:'mcp-banner'},{op:'produceCatalogAsset',catalogId:'LIFE-089',id:'mcp-finance'},{op:'produceCatalogAsset',catalogId:'LIFE-094',id:'mcp-fish'},{op:'produceCatalogAsset',catalogId:'LIFE-125',id:'mcp-stretcher'},{op:'produceCatalogAsset',catalogId:'LIFE-145',id:'mcp-evidence'},{op:'produceCatalogAsset',catalogId:'LIFE-114',id:'mcp-microscope'},{op:'produceCatalogAsset',catalogId:'LIFE-122',id:'mcp-scanner'},{op:'produceCatalogAsset',catalogId:'LIFE-024',id:'mcp-shoe'},{op:'produceCatalogAsset',catalogId:'LIFE-082',id:'mcp-machine'},{op:'produceCatalogAsset',catalogId:'LIFE-078',id:'mcp-conveyor'},{op:'instance',id:'mcp-conveyor-a',assetId:'mcp-conveyor',position:[10,0,3]},{op:'connect',id:'mcp-conveyor-b',assetId:'mcp-conveyor',targetInstanceId:'mcp-conveyor-a',portId:'input',targetPortId:'output',rotation:0},{op:'instance',id:'mcp-shoe-placement',assetId:'mcp-shoe',position:[10,0,0]},{op:'assignMaterial',assetId:'mcp-shoe',fromMaterial:2,material:7}]},dry=await call('edit_transaction',{...request,dryRun:true});assert.equal(hash((await state()).project),hash(before));assert.ok(dry.modifiedVoxels>4096);
 const t=performance.now(),commit=await call('edit_transaction',{...request,previewToken:dry.previewToken});await sync(commit.version);report.mcpCommitAndUISyncMs=performance.now()-t;const after=(await state()).project;
 assert.equal(after.assets['mcp-shoe'].source.reference.sheet,'M001');assert.equal(after.assets['mcp-shoe'].source.reference.slot,6);assert.equal(after.assets['mcp-shoe'].source.recipeRevision,3);assert.equal(after.assets['mcp-machine'].source.reference.sheet,'M005');const cavity=await call('query_voxels',{assetId:'mcp-machine',region:{min:[26,35,16],max:[88,120,65]},limit:1000});assert.equal(cavity.total,0);const joined=await call('check_geometry');assert.ok(!joined.collisions.some((v:any)=>v.instances.includes('mcp-conveyor-a')&&v.instances.includes('mcp-conveyor-b')));assert.ok(!joined.gaps.some((v:any)=>v.instances.includes('mcp-conveyor-a')&&v.instances.includes('mcp-conveyor-b')));assert.ok(Math.abs(after.instances['mcp-conveyor-b'].position[0]-after.instances['mcp-conveyor-a'].position[0]-1.6)<1e-8);await page.evaluate(()=>(window as any).voxelStudio.mode('asset','mcp-machine'));await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('mcp-machine'),null,{timeout:120000});await page.screenshot({path:path.join(root,'mcp-created-machine.png')});report.checks.push('MCP-created M005 enclosure is visibly rendered; two conveyor instances dock with no collision or gap');assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets)),hash(after.assets));assert.equal((await call('edit_transaction',request)).version,commit.version);assert.equal((await raw('edit_transaction',{...request,requestId:crypto.randomUUID()})).code,'VERSION_CONFLICT');
 assert.equal(after.assets['mcp-fish'].cellSize,.005);assert.equal(after.assets['mcp-fish'].source.reference.sheet,'M006');assert.equal(after.assets['mcp-finance'].cellSize,.01);const fineCells=await call('query_voxels',{assetId:'mcp-fine-grid',region:{min:[0,0,0],max:[2,1,1]}});assert.equal(fineCells.total,2);const fork=await call('query_voxels',{assetId:'mcp-fish',region:{min:[88,12,15],max:[89,14,17]}});assert.equal(fork.total,0);
 await page.evaluate(()=>(window as any).voxelStudio.mode('asset','mcp-fish'));await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('mcp-fish'),null,{timeout:120000});await page.screenshot({path:path.join(root,'mcp-created-fish.png')});assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets['mcp-fish'])),hash(after.assets['mcp-fish']));const fineExport=await call('export_project',{name:'mcp-fine-fish-'+crypto.randomUUID().slice(0,8),assetId:'mcp-fish'}),fineRound=JSON.parse(await readFile(path.join(fineExport.directory,'voxels.ysvox.json'),'utf8'));assert.equal(hash(fineRound.assets['mcp-fish']),hash(after.assets['mcp-fish']));report.fineExport=fineExport;report.checks.push('MCP creates a 5 mm empty grid and edits exact integer cells; M006 finance and fish masters share the canonical UI document, fork clearance is empty and exported native fish hashes match');
 assert.equal(after.assets['mcp-microscope'].cellSize,.005);assert.equal(after.assets['mcp-scanner'].cellSize,.02);for(const id of['mcp-microscope','mcp-scanner']){const a=after.assets[id];assert.equal(a.source.reference.sheet,'M007');for(const region of a.openings)assert.equal((await call('query_voxels',{assetId:id,region,limit:1000})).total,0);}
 await page.evaluate(()=>(window as any).voxelStudio.mode('asset','mcp-microscope'));await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('mcp-microscope'),null,{timeout:120000});await page.screenshot({path:path.join(root,'mcp-created-microscope.png')});assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets['mcp-microscope'])),hash(after.assets['mcp-microscope']));report.checks.push('MCP reconstructs the 5 mm microscope and 20 mm scanner from M007; exact optical and patient passages are empty, and the rendered microscope uses identical canonical voxels');

 for(const id of['mcp-stretcher','mcp-evidence']){const a=after.assets[id];assert.equal(a.source.reference.sheet,'M008');for(const region of a.openings)assert.equal((await call('query_voxels',{assetId:id,region,limit:1000})).total,0);}
 assert.equal(after.assets['mcp-evidence'].cellSize,.005);await page.evaluate(()=>(window as any).voxelStudio.mode('asset','mcp-stretcher'));await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('mcp-stretcher'),null,{timeout:120000});assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets['mcp-stretcher'])),hash(after.assets['mcp-stretcher']));await page.screenshot({path:path.join(root,'mcp-created-stretcher.png')});
 const evidenceExport=await call('export_project',{name:'mcp-evidence-'+crypto.randomUUID().slice(0,8),assetId:'mcp-evidence'}),evidenceRound=JSON.parse(await readFile(path.join(evidenceExport.directory,'voxels.ysvox.json'),'utf8'));assert.equal(hash(evidenceRound.assets['mcp-evidence']),hash(after.assets['mcp-evidence']));report.civicExport=evidenceExport;
 report.checks.push('MCP creates M008 stretcher and 5 mm evidence case, queries actual grip/cavity clearances, renders the canonical stretcher and exports lossless evidence-case voxels');
 for(const id of['mcp-camera','mcp-banner']){const a=after.assets[id];assert.equal(a.source.reference.sheet,'M009');for(const region of a.openings)assert.equal((await call('query_voxels',{assetId:id,region,limit:1000})).total,0);}
 assert.equal(after.assets['mcp-camera'].cellSize,.005);const cameraMaterials=await call('query_materials_interfaces',{assetId:'mcp-camera'}),cameraRoles=cameraMaterials.styles.yunshan;
 for(const [region,role]of [[{min:[34,78,0],max:[35,79,1]},'glass'],[{min:[32,78,2],max:[33,79,3]},'lightCore'],[{min:[37,78,3],max:[38,79,4]},'opticsGlow']] as const){const q=await call('query_voxels',{assetId:'mcp-camera',region});assert.equal(q.cells[0]?.[1],cameraRoles[role]);}
 await page.evaluate(()=>(window as any).voxelStudio.mode('asset','mcp-camera'));await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('mcp-camera'),null,{timeout:120000});assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets['mcp-camera'])),hash(after.assets['mcp-camera']));await page.screenshot({path:path.join(root,'mcp-created-camera.png')});
 const cameraExport=await call('export_project',{name:'mcp-camera-'+crypto.randomUUID().slice(0,8),assetId:'mcp-camera'}),cameraRound=JSON.parse(await readFile(path.join(cameraExport.directory,'voxels.ysvox.json'),'utf8'));assert.equal(hash(cameraRound.assets['mcp-camera']),hash(after.assets['mcp-camera']));assert.equal(hash(cameraRound.styles),hash(after.styles));report.publicServiceExport=cameraExport;report.checks.push('MCP constructs M009 camera and banner; exact 5 mm optical glass/core/emitter cells and hollow spaces are queryable, rendered canonical hashes match and native export preserves role bindings');
 const failed=await raw('edit_transaction',{expectedVersion:commit.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:2,properties:{color:'#ff0000'}},{op:'assignMaterial',assetId:'does-not-exist',material:2}]});assert.ok(failed.isError);assert.equal(hash((await state()).project),hash(after));
 const undo=await call('edit_transaction',{expectedVersion:commit.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(undo.version);const undone=(await state()).project;assert.equal(hash(undone.assets),hash(before.assets));assert.equal(hash(undone.materials),hash(before.materials));assert.equal(hash(undone.instances),hash(before.instances));assert.equal(hash(undone.catalog),hash(before.catalog));report.checks.push('MCP creates M001 cabinet, M005 machinery, M006 terminal and fine fish, M007 microscope and scanner, updates materials, places and connects instances atomically; UI matches voxel hash; dry-run, CAS, idempotency, runtime failure rollback and one-step undo pass');
 const correctedLoad=await call('load_project',{filename:index.studies.find((e:any)=>e.id==='M003-gallery').file,expectedVersion:(await state()).project.version});await sync(correctedLoad.version);
 const correctedBefore=(await state()).project,correctedInfo=await call('query_materials_interfaces',{assetId:'life-057'}),correctedRoles=correctedInfo.styles.yunshan;
 for(const [role,category]of Object.entries({ceramicWhite:'ceramic',ceramicTeal:'ceramic',wovenLight:'fabric',cottonWhite:'fabric',polymerDark:'plastic',glassEtch:'glass',bottleAmber:'glass',inkTeal:'ink',bookCloth:'fabric',fishPale:'food'}))assert.equal(correctedBefore.materials[correctedRoles[role]].category,category);
 for(const [assetId,region,role]of [['life-051',{min:[2,8,2],max:[3,9,3]},'ceramicWhite'],['life-052',{min:[20,40,8],max:[21,41,9]},'polymer'],['life-057',{min:[9,2,-1],max:[10,3,0]},'cottonWhite']] as const){const q=await call('query_voxels',{assetId,region});assert.equal(q.cells[0]?.[1],correctedRoles[role]);}
 await page.locator('#material-category-filter').selectOption('ceramic');const ceramicButtons=await page.locator('[data-material]').evaluateAll(nodes=>nodes.map(n=>Number((n as HTMLElement).dataset.material)));assert.ok(ceramicButtons.length>=3);for(const id of ceramicButtons)assert.equal(correctedBefore.materials[id].category,'ceramic');await page.locator('[data-material="'+correctedRoles.ceramicWhite+'"]').click();assert.match(await page.locator('#material-category').innerText(),/陶瓷/);await page.locator('#material-category-filter').selectOption('all');
 report.checks.push('Corrected M003 ceramic basin, plastic toilet seat and cotton towel use independent IDs in queried native cells; Schema and MCP preserve all new semantic categories');
 await page.evaluate(()=>{const v=(window as any).voxelStudio;v.mode('asset','life-057');v.clay(true);v.view('isometric');});
 const clothRoles=['cottonWhite','wovenLight','fabric','fabricEdge'],clothRequest={expectedVersion:correctedBefore.version,requestId:crypto.randomUUID(),label:'只替换织物，不修改陶瓷、玻璃和屏幕',commands:[{op:'definePalette',name:'织物独立换装检查',materials:Object.fromEntries(clothRoles.map(r=>[correctedRoles[r],{color:'#ad3471',roughness:1}]))},{op:'palette',name:'织物独立换装检查'}]},clothDry=await call('edit_transaction',{...clothRequest,dryRun:true});assert.equal(clothDry.modifiedVoxels,0);assert.equal(hash((await state()).project),hash(correctedBefore));
 const clothEdit=await call('edit_transaction',{...clothRequest,previewToken:clothDry.previewToken});await sync(clothEdit.version);const clothAfter=(await state()).project;for(const field of['assets','styles'])assert.equal(hash(clothAfter[field]),hash(correctedBefore[field]));
 const changedIds=new Set(clothRoles.map(r=>String(correctedRoles[r])));for(const[id,m]of Object.entries(clothAfter.materials) as [string,any][]){assert.equal(m.solid,correctedBefore.materials[id].solid);assert.equal(m.category,correctedBefore.materials[id].category);if(!changedIds.has(id))assert.equal(hash(m),hash(correctedBefore.materials[id]));}
 assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(clothAfter.materials));await page.locator('[data-material="'+correctedRoles.cottonWhite+'"]').click();assert.match(await page.locator('#material-role').innerText(),/yunshan.cottonWhite/);await page.screenshot({path:path.join(root,'mcp-classification-roles.png')});
 const clothUndo=await call('edit_transaction',{expectedVersion:clothEdit.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(clothUndo.version);const clothRestored=(await state()).project;for(const field of['assets','styles','materials','palettes'])assert.equal(hash(clothRestored[field]),hash(correctedBefore[field]));await page.screenshot({path:path.join(root,'mcp-classification-roles-restored.png')});
 report.classificationSwap={modifiedVoxels:clothEdit.modifiedVoxels,roles:clothRoles,bindings:correctedRoles,uiMaterialHash:hash(clothAfter.materials),undoRestored:true};report.checks.push('MCP changes only textile appearances in corrected M003; ceramic, plastic, glass, display pixels and all voxel/collision data remain unchanged; UI shows the same assignments and a single undo restores the whole pack');
 const sceneVersion=(await state()).project.version,sceneFile=index.studies.find((e:any)=>e.id==='M006-gallery').file,sceneLoad=await call('load_project',{filename:sceneFile,expectedVersion:sceneVersion});await sync(sceneLoad.version);const checkStart=performance.now(),mixedGallery=await call('check_geometry');report.mixedGalleryCheckMs=performance.now()-checkStart;assert.deepEqual(mixedGallery.collisions,[]);assert.deepEqual(mixedGallery.unsupported,[]);assert.deepEqual(mixedGallery.warnings,[]);assert.equal(mixedGallery.collisionGrids.length,12);report.mixedGallery={grids:mixedGallery.collisionGrids,occupiedCollisionCells:mixedGallery.occupiedCollisionCells};report.checks.push('All twelve M006 placements pass mixed 5/10 mm scene checks; independent groups keep local precision without subdividing every coarse master');
 const researchLoad=await call('load_project',{filename:index.studies.find((e:any)=>e.id==='M007-gallery').file,expectedVersion:(await state()).project.version});await sync(researchLoad.version);const researchStart=performance.now(),researchCheck=await call('check_geometry');report.researchGalleryCheckMs=performance.now()-researchStart;assert.deepEqual(researchCheck.collisions,[]);assert.deepEqual(researchCheck.unsupported,[]);assert.deepEqual(researchCheck.warnings,[]);assert.ok(researchCheck.openings.every((o:any)=>o.ownSolidCells===0&&o.blockedBy.length===0));assert.equal(researchCheck.collisionGrids.length,12);report.researchGallery=researchCheck;const clamps=await call('query_materials_interfaces',{assetId:'life-120'});assert.equal(clamps.assets[0].ports.filter((p:any)=>p.kind==='bed-rail-clamp-80').length,2);report.checks.push('M007 gallery passes all twelve placement and clearance checks across 5/10/20 mm grids; bed rail clamp ports retain authored metre coordinates');
 // A resource-pack change updates appearances by semantic role, without remapping cells.
 const roleInfo=await call('query_materials_interfaces',{assetId:'life-114'}),roles=roleInfo.styles.yunshan,roleBefore=(await state()).project;
 assert.equal(new Set(['glass','screen','displayGlyph','opticsGlow','lightCore','enamel','metal','bronze'].map(r=>roles[r])).size,8);
 await page.evaluate(()=>(window as any).voxelStudio.mode('asset','life-114'));
 const appearanceRequest={expectedVersion:roleBefore.version,requestId:crypto.randomUUID(),label:'独立更换显示与镜芯材质',commands:[{op:'palette',name:'参考材质试作'},{op:'material',id:roles.opticsGlow,properties:{color:'#9813ac',emissive:'#bd2ee4',intensity:2.4}},{op:'material',id:roles.displayGlyph,properties:{color:'#69bf9d',emissive:'#48e1a2',intensity:1.6}}]},roleDry=await call('edit_transaction',{...appearanceRequest,dryRun:true});
 assert.equal(roleDry.modifiedVoxels,0);assert.equal(hash((await state()).project),hash(roleBefore));const roleCommit=await call('edit_transaction',{...appearanceRequest,previewToken:roleDry.previewToken});await sync(roleCommit.version);
 const roleAfter=(await state()).project;assert.equal(hash(roleAfter.assets),hash(roleBefore.assets));assert.equal(hash(roleAfter.styles),hash(roleBefore.styles));assert.equal(roleAfter.materials[roles.glass].color,roleBefore.palettes['参考材质试作'][roles.glass].color);assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(roleAfter.materials));
 await page.evaluate(()=>{const v=(window as any).voxelStudio;v.clay(false);v.studio(true);v.referenceLighting(true);v.ao(true);v.bloom(true);v.view('isometric');});await page.locator('[data-material="'+roles.opticsGlow+'"]').click();assert.match(await page.locator('#material-role').innerText(),/yunshan.opticsGlow/);await page.screenshot({path:path.join(root,'mcp-material-roles.png')});
 const roleUndo=await call('edit_transaction',{expectedVersion:roleCommit.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(roleUndo.version);const roleRestored=(await state()).project;assert.equal(hash(roleRestored.materials),hash(roleBefore.materials));assert.equal(hash(roleRestored.assets),hash(roleBefore.assets));assert.equal(hash(roleRestored.styles),hash(roleBefore.styles));
 await page.screenshot({path:path.join(root,'mcp-material-roles-restored.png')});report.materialRoles={bindings:roles,modifiedVoxels:roleCommit.modifiedVoxels,uiMaterialHash:hash(roleAfter.materials),undoRestored:true};report.checks.push('MCP changes optical emission and display glyphs independently from glass/metal, UI exposes and renders the same roles, native voxel assignments remain identical, and one undo restores the complete palette');

 const civicLoaded=await call('load_project',{filename:index.studies.find((e:any)=>e.id==='M008-gallery').file,expectedVersion:(await state()).project.version});await sync(civicLoaded.version);const civicStart=performance.now(),civicCheck=await call('check_geometry');report.civicGalleryCheckMs=performance.now()-civicStart;assert.deepEqual(civicCheck.collisions,[]);assert.deepEqual(civicCheck.unsupported,[]);assert.deepEqual(civicCheck.warnings,[]);assert.ok(civicCheck.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));assert.equal(civicCheck.collisionGrids.length,12);report.civicGallery=civicCheck;
 const civicInfo=await call('query_materials_interfaces',{assetId:'life-125'}),civicRoles=civicInfo.styles.yunshan,civicBefore=(await state()).project;
 for(const [r,category]of Object.entries({rubber:'rubber',safetyFabric:'fabric',webbing:'fabric',flexibleClear:'plastic',fluidBlue:'water',fluidAmber:'water',bookCover:'paper',archiveBoard:'paper',displayWhite:'emissive',printedDark:'ink'}))assert.equal(civicBefore.materials[civicRoles[r]].category,category);
 const tyreQuery=await call('query_voxels',{assetId:'life-125',region:{min:[8,1,24],max:[9,2,25]}});assert.equal(tyreQuery.cells[0]?.[1],civicRoles.rubber);
 report.checks.push('M008 native gallery passes twelve mixed-pitch placement/clearance checks; actual tyre cell and all ten added semantic material roles are queryable through MCP');
 await page.evaluate(()=>(window as any).voxelStudio.mode('asset','life-125'));const civicRequest={expectedVersion:civicBefore.version,requestId:crypto.randomUUID(),label:'独立替换橡胶与织物材质包',commands:[{op:'definePalette',name:'分类验证',materials:{[civicRoles.rubber]:{color:'#2762a3',roughness:.9},[civicRoles.safetyFabric]:{color:'#9c4467',roughness:.95}}},{op:'palette',name:'分类验证'}]},civicDry=await call('edit_transaction',{...civicRequest,dryRun:true});assert.equal(civicDry.modifiedVoxels,0);assert.equal(hash((await state()).project),hash(civicBefore));const civicEdit=await call('edit_transaction',{...civicRequest,previewToken:civicDry.previewToken});await sync(civicEdit.version);const civicAfter=(await state()).project;assert.equal(hash(civicAfter.assets),hash(civicBefore.assets));assert.equal(hash(civicAfter.styles),hash(civicBefore.styles));for(const role of['webbing','metal','bronze','polymer'])assert.equal(hash(civicAfter.materials[civicRoles[role]]),hash(civicBefore.materials[civicRoles[role]]));
 assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(civicAfter.materials));await page.locator('[data-material="'+civicRoles.rubber+'"]').click();assert.match(await page.locator('#material-role').innerText(),/yunshan.rubber/);await page.screenshot({path:path.join(root,'mcp-civic-roles.png')});const civicUndo=await call('edit_transaction',{expectedVersion:civicEdit.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(civicUndo.version);const civicRestored=(await state()).project;for(const field of['assets','styles','materials','palettes'])assert.equal(hash(civicRestored[field]),hash(civicBefore[field]));await page.screenshot({path:path.join(root,'mcp-civic-roles-restored.png')});report.civicRoleSwap={modifiedVoxels:civicEdit.modifiedVoxels,bindings:civicRoles,uiMaterialHash:hash(civicAfter.materials),undoRestored:true};report.checks.push('Rubber tyres and orange stretcher textile accept an independent resource-pack swap without touching straps, metal or canonical cells; UI material-role label and material hashes match, one undo restores the whole pack');
 await page.locator('#atlas-sheet').selectOption('M008');await page.locator('[data-catalog="LIFE-125"][data-atlas-open]').first().click();await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('life-125'),null,{timeout:120000});await page.waitForFunction(()=>document.querySelector('#atlas-reference')?.textContent?.includes('LIFE-125'),null,{timeout:30000});await page.screenshot({path:path.join(root,'mcp-civic-editor.png')});
 const publicLoaded=await call('load_project',{filename:index.studies.find((e:any)=>e.id==='M009-gallery').file,expectedVersion:(await state()).project.version});await sync(publicLoaded.version);const publicStart=performance.now(),publicCheck=await call('check_geometry');report.publicGalleryCheckMs=performance.now()-publicStart;assert.deepEqual(publicCheck.collisions,[]);assert.deepEqual(publicCheck.unsupported,[]);assert.deepEqual(publicCheck.warnings,[]);assert.ok(publicCheck.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));assert.equal(publicCheck.collisionGrids.length,12);report.publicGallery=publicCheck;
 const publicInfo=await call('query_materials_interfaces',{assetId:'life-148'}),publicRoles=publicInfo.styles.yunshan,publicBefore=(await state()).project;
 for(const[role,category]of Object.entries({bannerCloth:'fabric',bannerPattern:'fabric',cottonWhite:'fabric',printedRed:'ink',rigidClear:'plastic'}))assert.equal(publicBefore.materials[publicRoles[role]].category,category);
 const ink=await call('query_voxels',{assetId:'life-150',region:{min:[28,107,6],max:[29,108,7]}});assert.equal(ink.cells[0]?.[1],publicRoles.printedRed);report.checks.push('M009 twelve-model gallery passes actual 5/10/20 mm placement, support and void checks; cloth, motif, cotton, red ink and rigid plastic have separate queryable IDs');
 await page.evaluate(()=>(window as any).voxelStudio.mode('asset','life-148'));const publicRequest={expectedVersion:publicBefore.version,requestId:crypto.randomUUID(),label:'独立替换旗布、织纹和印刷标记',commands:[{op:'definePalette',name:'M009 分类换装',materials:{[publicRoles.bannerCloth]:{color:'#9b4842'},[publicRoles.bannerPattern]:{color:'#d5d0bc'},[publicRoles.printedRed]:{color:'#37599a'}}},{op:'palette',name:'M009 分类换装'}]},publicDry=await call('edit_transaction',{...publicRequest,dryRun:true});assert.equal(publicDry.modifiedVoxels,0);assert.equal(hash((await state()).project),hash(publicBefore));const publicEdit=await call('edit_transaction',{...publicRequest,previewToken:publicDry.previewToken});await sync(publicEdit.version);const publicAfter=(await state()).project;for(const field of['assets','styles'])assert.equal(hash(publicAfter[field]),hash(publicBefore[field]));for(const role of['cottonWhite','bronze','signalRed','rigidClear','fluidBlue','glass','opticsGlow'])assert.equal(hash(publicAfter.materials[publicRoles[role]]),hash(publicBefore.materials[publicRoles[role]]));assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(publicAfter.materials));
 await page.locator('[data-material="'+publicRoles.bannerCloth+'"]').click();assert.match(await page.locator('#material-role').innerText(),/yunshan.bannerCloth/);await page.screenshot({path:path.join(root,'mcp-public-roles.png')});const publicUndo=await call('edit_transaction',{expectedVersion:publicEdit.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(publicUndo.version);const publicRestored=(await state()).project;for(const field of['assets','styles','materials','palettes'])assert.equal(hash(publicRestored[field]),hash(publicBefore[field]));await page.screenshot({path:path.join(root,'mcp-public-roles-restored.png')});report.publicRoleSwap={modifiedVoxels:publicEdit.modifiedVoxels,bindings:publicRoles,uiMaterialHash:hash(publicAfter.materials),undoRestored:true};report.checks.push('MCP changes banner cloth, woven motif and printed red mark as one resource pack; other fabrics, optical layers, glass, plastic and metal stay unchanged, UI hashes agree and one undo restores the entire batch');
 await page.locator('#atlas-sheet').selectOption('M009');await page.locator('[data-catalog="LIFE-158"][data-atlas-open]').first().click();await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('life-158'),null,{timeout:120000});await page.waitForFunction(()=>document.querySelector('#atlas-reference')?.textContent?.includes('LIFE-158'),null,{timeout:30000});assert.equal((await state()).project.assets['life-158'].cellSize,.005);await page.screenshot({path:path.join(root,'mcp-public-editor.png')});report.checks.push('M009 camera opens from its own atlas reference tile in the real editor with the correct 5 mm native grid');

 const cultureLoaded=await call('load_project',{filename:index.studies.find((e:any)=>e.id==='M010-gallery').file,expectedVersion:(await state()).project.version});await sync(cultureLoaded.version);
 const cultureBefore=(await state()).project,cultureRoles=cultureBefore.styles.yunshan,cultureStart=performance.now(),cultureCheck=await call('check_geometry');report.cultureGalleryCheckMs=performance.now()-cultureStart;assert.deepEqual(cultureCheck.collisions,[]);assert.deepEqual(cultureCheck.unsupported,[]);assert.deepEqual(cultureCheck.warnings,[]);assert.ok(cultureCheck.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));assert.equal(cultureCheck.collisionGrids.length,12);report.cultureGallery=cultureCheck;
 for(const[role,category]of Object.entries({safetyMetal:'metal',lacquerWood:'wood',canvas:'fabric',pigmentInk:'ink',pigmentMist:'ink',drumSkin:'plastic',instrumentWire:'metal',brushFibre:'fabric',redHose:'rubber',incense:'plant',ember:'emissive',polymerRed:'plastic',speakerCone:'plastic'}))assert.equal(cultureBefore.materials[cultureRoles[role]].category,category);
 for(const [assetId,point,role]of [['life-159',[85,41,22],'safetyMetal'],['life-159',[20,110,20],'polymerRed'],['life-159',[48,43,19],'redHose'],['life-170',[50,120,16],'canvas'],['life-175',[52,82,9],'drumSkin'],['life-174',[35,88,5],'instrumentWire']] as const){const q=await call('query_voxels',{assetId,region:{min:point,max:point.map(v=>v+1)}});assert.equal(q.cells[0]?.[1],cultureRoles[role]);}
 report.checks.push('M010 twelve native placements pass actual mixed-pitch support, collision and declared-void checks; queried fire metal, hose rubber, plastic case, canvas, drum membrane and strings have distinct physical roles');
 await page.evaluate(()=>{const v=(window as any).voxelStudio;v.mode('asset','life-159');v.clay(true);v.view('isometric');});
 const cultureRequest={expectedVersion:cultureBefore.version,requestId:crypto.randomUUID(),label:'只替换红漆钢瓶及绘画绷布',commands:[{op:'definePalette',name:'M010 分类验证',materials:{[cultureRoles.safetyMetal]:{color:'#2f629e'},[cultureRoles.canvas]:{color:'#dbaec5'}}},{op:'palette',name:'M010 分类验证'}]},cultureDry=await call('edit_transaction',{...cultureRequest,dryRun:true});assert.equal(cultureDry.modifiedVoxels,0);assert.equal(hash((await state()).project),hash(cultureBefore));
 const cultureEdit=await call('edit_transaction',{...cultureRequest,previewToken:cultureDry.previewToken});await sync(cultureEdit.version);const cultureAfter=(await state()).project;
 for(const field of['assets','styles'])assert.equal(hash(cultureAfter[field]),hash(cultureBefore[field]));for(const [id,m]of Object.entries(cultureBefore.materials) as [string,any][]){assert.equal(cultureAfter.materials[id].solid,m.solid);assert.equal(cultureAfter.materials[id].category,m.category);if(![cultureRoles.safetyMetal,cultureRoles.canvas].includes(Number(id)))assert.equal(hash(cultureAfter.materials[id]),hash(m));}
 assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(cultureAfter.materials));await page.locator('[data-material="'+cultureRoles.safetyMetal+'"]').click();assert.match(await page.locator('#material-role').innerText(),/yunshan.safetyMetal/);await page.screenshot({path:path.join(root,'mcp-culture-roles.png')});
 const cultureUndo=await call('edit_transaction',{expectedVersion:cultureEdit.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(cultureUndo.version);const cultureRestored=(await state()).project;for(const field of['assets','styles','materials','palettes'])assert.equal(hash(cultureRestored[field]),hash(cultureBefore[field]));await page.screenshot({path:path.join(root,'mcp-culture-roles-restored.png')});report.cultureRoleSwap={modifiedVoxels:cultureEdit.modifiedVoxels,bindings:cultureRoles,uiMaterialHash:hash(cultureAfter.materials),undoRestored:true};report.checks.push('Changing fire-cylinder coating and stretched canvas leaves hose, case, pigments, membrane and all canonical/collision cells intact; UI hashes agree and one undo restores the complete material pack');
 const stageLoaded=await call('load_project',{filename:index.entries.find((e:any)=>e.id==='LIFE-176').file,expectedVersion:(await state()).project.version});await sync(stageLoaded.version);
 const stageBefore=(await state()).project,cultureCreate={expectedVersion:stageBefore.version,requestId:crypto.randomUUID(),label:'M010 接台与文房原生建模',commands:[{op:'importCatalog',sourceName:'city-assets.csv',csv:catalogCSV},{op:'produceCatalogAsset',catalogId:'LIFE-171',id:'mcp-calligraphy'},{op:'connect',id:'joined-stage',assetId:'life-176',targetInstanceId:'life-176-preview',portId:'join-left',targetPortId:'join-right',rotation:0},{op:'instance',id:'calligraphy-placement',assetId:'mcp-calligraphy',position:[5,0,0]}]};
 const cultureCreateDry=await call('edit_transaction',{...cultureCreate,dryRun:true});assert.equal(hash((await state()).project),hash(stageBefore));const cultureCreated=await call('edit_transaction',{...cultureCreate,previewToken:cultureCreateDry.previewToken});await sync(cultureCreated.version);const createdCulture=(await state()).project;assert.deepEqual(createdCulture.instances['joined-stage'].position,[2,0,0]);const joinedCulture=await call('check_geometry');assert.deepEqual(joinedCulture.collisions,[]);assert.deepEqual(joinedCulture.gaps,[]);assert.deepEqual(joinedCulture.unsupported,[]);assert.ok(joinedCulture.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));
 const tip=await call('query_voxels',{assetId:'mcp-calligraphy',region:{min:[32,38,71],max:[33,39,72]}});assert.equal(tip.cells[0]?.[1],createdCulture.styles.yunshan.brushFibre);assert.equal(createdCulture.assets['mcp-calligraphy'].cellSize,.005);
 await page.evaluate(()=>(window as any).voxelStudio.mode('asset','mcp-calligraphy'));await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('mcp-calligraphy'),null,{timeout:120000});assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets['mcp-calligraphy'])),hash(createdCulture.assets['mcp-calligraphy']));await page.screenshot({path:path.join(root,'mcp-created-calligraphy.png')});
 const cultureExport=await call('export_project',{name:'mcp-culture-'+crypto.randomUUID().slice(0,8),assetId:'mcp-calligraphy'}),cultureRound=JSON.parse(await readFile(path.join(cultureExport.directory,'voxels.ysvox.json'),'utf8'));assert.equal(hash(cultureRound.assets['mcp-calligraphy']),hash(createdCulture.assets['mcp-calligraphy']));assert.equal(hash(cultureRound.styles),hash(createdCulture.styles));report.cultureExport=cultureExport;
 const cultureFailed=await raw('edit_transaction',{expectedVersion:cultureCreated.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:createdCulture.styles.yunshan.canvas,properties:{color:'#123456'}},{op:'assignMaterial',assetId:'missing',material:2}]});assert.ok(cultureFailed.isError);assert.equal(hash((await state()).project),hash(createdCulture));
 const creationUndo=await call('edit_transaction',{expectedVersion:cultureCreated.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(creationUndo.version);const restoredStage=(await state()).project;for(const field of['assets','styles','materials','instances','catalog'])assert.equal(hash(restoredStage[field]),hash(stageBefore[field]));report.checks.push('Official MCP builds a 5 mm calligraphy master and docks two 20 mm stages in one previewed transaction; real brush-fibre cells and voids are queryable, UI/native-export hashes agree, failed edits roll back and one undo restores creation and docking');
 await page.locator('#atlas-sheet').selectOption('M010');await page.locator('[data-catalog="LIFE-175"][data-atlas-open]').first().click();await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('life-175'),null,{timeout:120000});await page.waitForFunction(()=>document.querySelector('#atlas-reference')?.textContent?.includes('LIFE-175'),null,{timeout:30000});await page.screenshot({path:path.join(root,'mcp-culture-editor.png')});report.checks.push('M010 drum opens from its matching atlas tile as an editable native grid with independent membrane, lacquered wood and printed motif roles');
 const festivalLoaded=await call('load_project',{filename:index.studies.find((e:any)=>e.id==='M011-gallery').file,expectedVersion:(await state()).project.version});await sync(festivalLoaded.version);
 const festivalBefore=(await state()).project,festivalRoles=festivalBefore.styles.yunshan,festivalStart=performance.now(),festivalCheck=await call('check_geometry');report.festivalGalleryCheckMs=performance.now()-festivalStart;assert.deepEqual(festivalCheck.collisions,[]);assert.deepEqual(festivalCheck.unsupported,[]);assert.deepEqual(festivalCheck.warnings,[]);assert.ok(festivalCheck.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));report.festivalGallery=festivalCheck;
 for(const [assetId,point,role]of [['life-181',[62,20,62],'gameWhite'],['life-184',[30,80,30],'gameFelt'],['life-185',[30,50,11],'festivalRed'],['life-187',[10,103,26],'giftPaper'],['life-191',[62,73,44],'candleWax'],['life-191',[62,84,44],'candleWick'],['life-191',[62,88,44],'candleFlame'],['life-191',[70,28,44],'cakeCrumb']] as const){const q=await call('query_voxels',{assetId,region:{min:point,max:point.map(v=>v+1)}});assert.equal(q.cells[0]?.[1],festivalRoles[role],role);}
 assert.equal(festivalBefore.materials[festivalRoles.candleWax].category,'wax');report.checks.push('M011 twelve saved masters have queryable ceramic pieces, felt, cloth, gift paper, food, wax, wick and flame cells; gallery collision and real-void checks pass');
 const festivalRequest={expectedVersion:festivalBefore.version,requestId:crypto.randomUUID(),label:'只换礼仪织物，保留其他红色用途',commands:[{op:'definePalette',name:'M011 红色用途隔离',materials:{[festivalRoles.festivalRed]:{color:'#386395'}}},{op:'palette',name:'M011 红色用途隔离'}]},festivalDry=await call('edit_transaction',{...festivalRequest,dryRun:true});assert.equal(festivalDry.modifiedVoxels,0);assert.equal(hash((await state()).project),hash(festivalBefore));const festivalEdit=await call('edit_transaction',{...festivalRequest,previewToken:festivalDry.previewToken});await sync(festivalEdit.version);const festivalAfter=(await state()).project;
 for(const field of['assets','styles'])assert.equal(hash(festivalAfter[field]),hash(festivalBefore[field]));for(const [id,m]of Object.entries(festivalBefore.materials)as[string,any][]){assert.equal(festivalAfter.materials[id].category,m.category);assert.equal(festivalAfter.materials[id].solid,m.solid);if(Number(id)!==festivalRoles.festivalRed)assert.equal(hash(festivalAfter.materials[id]),hash(m));}
 assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.materials)),hash(festivalAfter.materials));await page.locator('[data-material="'+festivalRoles.festivalRed+'"]').click();assert.match(await page.locator('#material-role').innerText(),/yunshan.festivalRed/);await page.screenshot({path:path.join(root,'mcp-festival-roles.png')});const festivalUndo=await call('edit_transaction',{expectedVersion:festivalEdit.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(festivalUndo.version);for(const f of['assets','styles','materials','palettes'])assert.equal(hash((await state()).project[f]),hash(festivalBefore[f]));await page.screenshot({path:path.join(root,'mcp-festival-roles-restored.png')});report.checks.push('An isolated festive cloth palette update changes no gift ribbon, synthetic ball, ceramic glaze, wax or food; the UI agrees and one undo restores the full document');
 const chessLoaded=await call('load_project',{filename:index.entries.find((e:any)=>e.id==='LIFE-181').file,expectedVersion:(await state()).project.version});await sync(chessLoaded.version);const chessBefore=(await state()).project,festivalCreate={expectedVersion:chessBefore.version,requestId:crypto.randomUUID(),commands:[{op:'importCatalog',sourceName:'city-assets.csv',csv:catalogCSV},{op:'produceCatalogAsset',catalogId:'LIFE-191',id:'mcp-celebration'},{op:'instance',id:'celebration-placement',assetId:'mcp-celebration',position:[2,0,0]}]},festivalCreateDry=await call('edit_transaction',{...festivalCreate,dryRun:true});assert.equal(hash((await state()).project),hash(chessBefore));const festivalCreated=await call('edit_transaction',{...festivalCreate,previewToken:festivalCreateDry.previewToken});await sync(festivalCreated.version);const createdFestival=(await state()).project,festivalGeom=await call('check_geometry');assert.deepEqual(festivalGeom.collisions,[]);assert.deepEqual(festivalGeom.unsupported,[]);assert.ok(festivalGeom.openings.every((o:any)=>!o.ownSolidCells&&!o.blockedBy.length));
 await page.evaluate(()=>(window as any).voxelStudio.mode('asset','mcp-celebration'));await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('mcp-celebration'),null,{timeout:120000});assert.equal(hash(await page.evaluate(()=>(window as any).voxelStudio.project.assets['mcp-celebration'])),hash(createdFestival.assets['mcp-celebration']));await page.screenshot({path:path.join(root,'mcp-created-celebration.png')});const festivalExport=await call('export_project',{name:'mcp-festival-'+crypto.randomUUID().slice(0,8),assetId:'mcp-celebration'}),festivalRound=JSON.parse(await readFile(path.join(festivalExport.directory,'voxels.ysvox.json'),'utf8'));assert.equal(hash(festivalRound.assets['mcp-celebration']),hash(createdFestival.assets['mcp-celebration']));assert.equal(hash(festivalRound.styles),hash(createdFestival.styles));report.festivalExport=festivalExport;
 const festivalFailed=await raw('edit_transaction',{expectedVersion:festivalCreated.version,requestId:crypto.randomUUID(),commands:[{op:'materialBatch',entries:[{id:createdFestival.styles.yunshan.candleWax,properties:{color:'#123456'}},{id:65000,properties:{color:'#abcdef'}}]}]});assert.ok(festivalFailed.isError);assert.equal(hash((await state()).project),hash(createdFestival));const festivalCreateUndo=await call('edit_transaction',{expectedVersion:festivalCreated.version,requestId:crypto.randomUUID(),commands:[{op:'undo'}]});await sync(festivalCreateUndo.version);for(const f of['assets','styles','materials','instances','catalog'])assert.equal(hash((await state()).project[f]),hash(chessBefore[f]));report.checks.push('Official stdio MCP creates a 5mm celebration grid with classified food/wax, synchronizes and exports it, rolls back a partially invalid bulk material update, and undoes creation and placement together');
 await page.locator('#atlas-sheet').selectOption('M011');await page.locator('[data-catalog="LIFE-180"][data-atlas-open]').first().click();await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('life-180'),null,{timeout:120000});await page.waitForFunction(()=>document.querySelector('#atlas-reference')?.textContent?.includes('LIFE-180'),null,{timeout:30000});await page.screenshot({path:path.join(root,'mcp-festival-editor.png')});report.checks.push('M011 lectern loads as the matching editable atlas master, with real paper pages and independent static display glyphs');
 await page.locator('#atlas-sheet').selectOption('M007');await page.locator('[data-catalog="LIFE-114"][data-atlas-open]').first().click();await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('life-114'),null,{timeout:120000});await page.waitForFunction(()=>document.querySelector('#atlas-reference')?.textContent?.includes('LIFE-114'),null,{timeout:30000});assert.equal((await state()).project.assets['life-114'].cellSize,.005);await page.screenshot({path:path.join(root,'mcp-research-editor.png')});report.checks.push('M007 microscope opens from its matching reference tile in the editor at 5 mm');
 await page.locator('#atlas-sheet').selectOption('M006');await page.locator('[data-catalog="LIFE-094"][data-atlas-open]').first().click();await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('life-094'),null,{timeout:120000});await page.waitForFunction(()=>document.querySelector('#atlas-reference')?.textContent?.includes('LIFE-094'),null,{timeout:30000});assert.equal((await state()).project.assets['life-094'].cellSize,.005);await page.screenshot({path:path.join(root,'mcp-commerce-editor.png')});report.checks.push('M006 fine fish opens from its matching image tile in the real UI with 5 mm grid metadata');
 await page.locator('#atlas-sheet').selectOption('M005');await page.locator('[data-catalog="LIFE-082"][data-atlas-open]').first().click();await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('life-082'),null,{timeout:120000});await page.waitForFunction(()=>document.querySelector('#atlas-reference')?.textContent?.includes('LIFE-082'),null,{timeout:30000});assert.match(await page.locator('#atlas-reference').innerText(),/LIFE-082/);await page.screenshot({path:path.join(root,'mcp-workshop-editor.png')});report.checks.push('M005 machine enclosure opens from the matching image tile in the real UI');
 await page.locator('#atlas-sheet').selectOption('M003');await page.locator('[data-catalog="LIFE-056"][data-atlas-open]').first().click();await page.waitForFunction(()=>(window as any).voxelStudio.performance.assetIds.includes('life-056'),null,{timeout:120000});await page.waitForFunction(()=>document.querySelector('#atlas-reference')?.textContent?.includes('LIFE-056'),null,{timeout:30000});assert.match(await page.locator('#atlas-reference').innerText(),/LIFE-056/);assert.equal(await page.evaluate(()=>(window as any).voxelStudio.clayEnabled),true);report.checks.push('UI sheet navigation opens the correct native master and matching reference tile, in pure-colour inspection');
 const ports=await call('query_materials_interfaces',{assetId:'life-056'});assert.equal(ports.assets[0].ports.length,4);const query=await call('query_voxels',{assetId:'life-056',region:{min:[15,0,13],max:[19,38,15]},limit:1000});assert.equal(query.total,0);report.checks.push('MCP sees four authored pipe ports and verifies the entire vertical bore is empty');
 await page.screenshot({path:path.join(root,'mcp-editor.png')});await page.close();
 const preview=await call('generate_previews',{assetId:'life-056',appearance:'baseColor',views:['perspective','front']});assert.equal(preview.files.length,2);for(const f of preview.files)assert.ok((await readFile(f)).length>1000);report.previews=preview;report.checks.push('MCP multi-view preview renders the real edited pipe master with its captured version');
 const saved=await call('save_project',{filename:'atlas-verified.ysvox.json'}),snapshot=(await state()).project;assert.equal(hash(JSON.parse(await readFile(saved.path,'utf8'))),hash(snapshot));await stop();await start();assert.equal(hash((await state()).project),hash(snapshot));assert.equal((await state()).recovery.recovered,true);report.checks.push('save and process restart restore exact canonical voxels, references, material palettes and interfaces');
 assert.deepEqual(report.errors,[]);report.completedAt=new Date().toISOString();report.status='passed';await writeFile(path.join(root,'mcp-verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(error){report.status='failed';report.errors.push(error instanceof Error?error.message:String(error));throw error;}finally{await writeFile(path.join(root,'mcp-verification.json'),JSON.stringify(report,null,2));await browser?.close();await client?.close();await stop();await writeFile(path.join(root,'mcp-server.log'),log);await writeFile(path.join(root,'mcp-partial.json'),JSON.stringify(report,null,2));}
