import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile,cp} from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {chromium} from 'playwright';
import {validationBrowserOptions} from './browser-options';
import {productionProject} from '../src/production/style';
import {parseCatalogCSV} from '../src/core/catalog';
import {outfitHash} from '../src/production/outfit-components';
import {roofWallVariantForms} from '../src/production/roof-wall-variant-spec';
import {auditRoofWallVariant,roofWallClearBox} from './lib/roof-wall-variant-audit';
import {rotateY,type Project} from '../src/core/types';

const hash=(x:unknown)=>outfitHash(x??null),latest=JSON.parse(await readFile('artifacts/atlas/latest.json','utf8')),verification=JSON.parse(await readFile(latest.evidence+'/variant-verification.json','utf8')),out=latest.evidence,runtime=path.join(out,'variant-mcp-runtime'),url='http://127.0.0.1:4401',rows=latest.models;
assert.equal(rows.length,5);assert.equal(verification.records.length,14);assert.equal(verification.status,'passed');await mkdir(runtime,{recursive:true});
for(const file of['atlas-production-index.json','production-index.json','architecture-index.json','material-index.json',...rows.map((r:any)=>r.file)])await copyFile('projects/'+file,runtime+'/'+file);await cp('projects/reference-atlas',runtime+'/reference-atlas',{recursive:true});await copyFile('projects/'+rows[0].file,runtime+'/autosave.ysvox.json');
const empty=productionProject('M060屋顶墙面公开接口');empty.catalog={sourceName:'city-assets.csv',importedAt:latest.createdAt,entries:Object.fromEntries(parseCatalogCSV(await readFile('projects/catalog/city-assets.csv','utf8')).map(r=>[r.id,r]))};empty.materials[539]={...empty.materials[empty.styles.yunshan.wall],id:539,name:'foreign user material',color:'#123456'};await writeFile(runtime+'/empty.ysvox.json',JSON.stringify(empty));
let server:ChildProcess|undefined,client:Client|undefined,browser:Awaited<ReturnType<typeof chromium.launch>>|undefined,log='';
const report:any={run:latest.run,status:'running',checks:[],errors:[],views:[],quarterTurns:[],publicForms:[],notifications:[],expectedInvalidationVersions:[]},state=async():Promise<Project>=>(await fetch(url+'/api/state').then(r=>r.json())).project;
const fileSHA=async(file:string)=>createHash('sha256').update(await readFile(file)).digest('hex');
try{
 server=spawn(process.execPath,['--import','tsx','src/server/main.ts'],{env:{...process.env,VOXEL_PORT:'4401',VOXEL_PROJECT_DIR:runtime},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>log+=d);server.stderr!.on('data',d=>log+=d);let ready=false;for(let i=0;i<180;i++){try{if((await fetch(url+'/api/state')).ok){ready=true;break;}}catch{}if(server.exitCode!==null)throw new Error(log);await new Promise(r=>setTimeout(r,100));}assert.ok(ready);
 client=new Client({name:'roof-wall-variant-verification',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:['--import','tsx','src/server/mcp.ts'],cwd:process.cwd(),env:{...process.env as Record<string,string>,VOXEL_URL:url},stderr:'pipe'}));
 const raw=async(name:string,args:any={})=>{const r:any=await client!.callTool({name,arguments:args},undefined,{timeout:180000});console.log(name,r.isError?'ERROR':'OK');return{...JSON.parse(r.content[0].text),isError:!!r.isError};},call=async(name:string,args:any={})=>{const r=await raw(name,args);assert.ok(!r.isError,JSON.stringify(r));return r;};
 browser=await chromium.launch(validationBrowserOptions());report.browser=browser.version();const page=await browser.newPage({viewport:{width:1400,height:1000}});page.setDefaultTimeout(180000);page.on('pageerror',e=>report.errors.push(e.message));page.on('websocket',socket=>socket.on('framereceived',f=>{const n=JSON.parse(f.payload.toString());report.notifications.push({event:n.event,version:n.version,bytes:Buffer.byteLength(f.payload.toString()),fullProject:!!n.project});}));await page.goto(url+'/?atlas=1&flat=1&view=isometric');await page.waitForFunction(()=>!!(window as any).voxelStudio?.ready);
 report.webgl=await page.evaluate(()=>{const gl=(document.querySelector('#viewport canvas')as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return gl.getParameter(ext?.UNMASKED_RENDERER_WEBGL??gl.RENDERER);});
 const sync=async(v:number)=>page.waitForFunction(n=>(window as any).voxelStudio.performance.renderedVersion===n,v),edit=async(commands:any[])=>{const req={expectedVersion:(await state()).version,requestId:crypto.randomUUID(),commands},dry=await call('edit_transaction',{...req,dryRun:true}),result=await call('edit_transaction',{...req,previewToken:dry.previewToken});await sync(result.version);report.expectedInvalidationVersions.push(result.version);return result;},load=async(file:string)=>{const r=await call('load_project',{filename:file,expectedVersion:(await state()).version});await sync(r.version);report.expectedInvalidationVersions.push(r.version);return state();};
 const capture=async(key:string,view='isometric',assetId?:string,clip=Infinity)=>{await page.evaluate(async({view,assetId,clip})=>{const v=(window as any).voxelStudio;await v.mode(assetId?'asset':'scene',assetId);v.view(view);v.clip(clip);v.clay(true);v.studio(false);v.referenceLighting(false);v.ao(false);v.bloom(false);},{view,assetId,clip});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const box=await page.locator('#viewport').boundingBox();assert.ok(box);const file='variant-'+key+'.png';await page.screenshot({path:out+'/'+file,clip:box});const perf=await page.evaluate(()=>(window as any).voxelStudio.performance);assert.equal(perf.meshError,null);report.views.push({key,file,assetId,view,triangles:perf.triangles,imageSHA256:await fileSHA(out+'/'+file)});};
 const lib=await call('read_production_library',{query:'BUILT-041'});for(const[key,value]of Object.entries({atlasReferenceCandidates:720,atlasAssemblyCandidates:186,atlasVariantCandidates:18,atlasVariantForms:84,baseModels:533}))assert.equal(lib.counts[key],value);report.libraryCounts=lib.counts;
 for(const id of ['BUILT-004',...rows.map((r:any)=>r.id)]){const list=await call('list_production_recipes',{query:id,limit:100}),recipe=list.entries.find((r:any)=>r.id===id);assert.equal(recipe.kind,id==='BUILT-004'?'base':'variant');if(id==='BUILT-041')assert.equal(recipe.parentKind,'base');}
 await writeFile('docs/tool-schemas.json',JSON.stringify((await client.listTools()).tools,null,2));report.checks.push('Official MCP exposes5roof/wall variant recipes and the real004base,720references,533bases,186assemblies,18atlas variants and84forms.');
 await page.locator('#atlas-sheet').selectOption('M060');await page.locator('[data-atlas-open][data-catalog="BUILT-038"]').first().click();await page.waitForFunction(()=>Object.values((window as any).voxelStudio.project.assemblies??{}).some((a:any)=>a.source?.catalogId==='BUILT-038'));const opened=await state();await sync(opened.version);report.expectedInvalidationVersions.push(opened.version);const listed=await call('list_assets');assert.equal(listed.counts.variants,1);assert.equal(listed.counts.assemblies,0);report.checks.push('Actual atlas button opens one whole variant, with correct variant/assembly counts.');
 for(const row of rows){const p=await load(row.file);await capture(row.id+'-back','back');if(row.id==='BUILT-083'){const d=p.assemblies![row.assemblyId].source!.roofWallVariant as any,lower=p.assemblies![row.assemblyId].instances.find(i=>i.id===d.roofInstance)!;await capture(row.id+'-actual-hole','isometric',lower.assetId);await capture(row.id+'-wall-cutaway','isometric',undefined,7.0);}}
 for(const v of verification.records){
  await copyFile(v.directory+'/voxels.ysvox.json',runtime+'/finite-form.ysvox.json');const before=await load('finite-form.ysvox.json');await edit([{op:'instantiateAssembly',assemblyId:v.assemblyId,prefix:'quarter',position:[30,0,30],rotation:1}]);const turned=await state();assert.equal(Object.keys(turned.instances).length,2*Object.keys(before.instances).length);for(const i of before.assemblies![v.assemblyId].instances){const copy=turned.instances['quarter-'+i.id];assert.equal(copy.assetId,i.assetId);assert.equal(copy.rotation,(i.rotation+1)%4);assert.equal(hash(copy.position),hash(rotateY(i.position,1).map((n,k)=>n+[30,0,30][k])));}assert.equal(hash(turned.assets),hash(before.assets));await edit([{op:'undo'}]);assert.equal(hash((await state()).instances),hash(before.instances));report.quarterTurns.push({id:v.id,params:v.params,sourceSHA256:await fileSHA(v.directory+'/voxels.ysvox.json'),actualQuarterTurnPositionsAndAssetsVerified:true,passed:true});if(!v.isDefault)await capture(v.id+'-'+Object.values(v.params).join('-'));
  await load('empty.ysvox.json');const clean=await state();await edit([{op:'produceCatalogVariant',catalogId:v.id,id:v.assemblyId,params:v.params,place:true}]);const made=await state();assert.deepEqual(made.materials[539],empty.materials[539]);const audit=auditRoofWallVariant(made,made.assemblies![v.assemblyId]);assert.ok(audit.passed);report.publicForms.push({id:v.id,params:v.params,audit,foreignMaterialPreserved:true});await edit([{op:'undo'}]);for(const field of['assets','assemblies','instances','materials','styles','palettes','catalog']as const)assert.equal(hash((await state())[field]),hash(clean[field]));
 }
 report.checks.push('All14finite forms created via official MCP; saved exports separately loaded, instantiated at90degrees and undone, with exact geometry and original positions restored.');
 await load('empty.ysvox.json');const beforeWalls=await state(),commands=roofWallVariantForms('BUILT-041').flatMap((params,i)=>[{op:'produceCatalogVariant',catalogId:'BUILT-041',id:'wall-'+i,params},{op:'instantiateAssembly',assemblyId:'wall-'+i,prefix:'colors-'+i,position:[i%4*8,0,Math.floor(i/4)*4],rotation:0}]);await edit(commands);const walls=await state();assert.equal(Object.keys(walls.assemblies!).length,8);assert.equal(new Set(Object.entries(walls.styles).filter(([s])=>s.startsWith('wall-purpose-')).map(([,s])=>s.wall)).size,8);await capture('wall-colors-coexisting');
 const tone=walls.styles['wall-purpose-clinic'].wall;await edit([{op:'definePalette',name:'单墙外观验证',materials:{[tone]:{color:'#935bb1'}}},{op:'palette',name:'单墙外观验证'}]);const changed=await state();assert.equal(hash(changed.assets),hash(walls.assets));for(const[id,m]of Object.entries(walls.materials))if(Number(id)!==tone)assert.deepEqual(changed.materials[id],m);await edit([{op:'undo'}]);assert.equal(hash((await state()).materials),hash(walls.materials));
 for(const command of[{op:'produceCatalogVariant',catalogId:'BUILT-038',id:'bad',params:{gableAxis:'z'}},{op:'produceCatalogVariant',catalogId:'BUILT-041',id:'bad',params:{wallTone:'clinic',upperFootprint:'compact'}},{op:'produceCatalogAsset',catalogId:'BUILT-041',id:'bad'}]){const before=await state(),result=await raw('edit_transaction',{expectedVersion:before.version,requestId:crypto.randomUUID(),commands:[{op:'material',id:539,properties:{color:'#ffffff'}},command]});assert.ok(result.isError);assert.equal(hash(await state()),hash(before));}
 await edit([{op:'undo'}]);for(const field of['assets','assemblies','instances','materials','styles','palettes','catalog']as const)assert.equal(hash((await state())[field]),hash(beforeWalls[field]));report.checks.push('Eight wall colors coexist; one palette changes only its scoped wall. Invalid axis, cross-kind parameters and invalid base type rollback atomically; one undo restores original document.');
 await load('empty.ysvox.json');await edit([{op:'produceCatalogAsset',catalogId:'BUILT-004',id:'new-wall'}]);const base=await state();assert.deepEqual(roofWallClearBox(base.assets['new-wall'],[.65,.01,-.1],[1.35,1.73,.5]),[]);const pins=await call('query_voxels',{assetId:'new-wall',region:{min:[3,10,-2],max:[4,11,-1]}});assert.equal(pins.cells[0][1],base.styles.yunshan.architecturePin);await capture('new-base-004','isometric','new-wall');await edit([{op:'undo'}]);report.checks.push('New004canonical base is publicly generated; true0.4m wall and open door checked from actual mesh, actual20mmfastener queried through MCP.');
 const formBoard=verification.records.map((r:any)=>({id:r.id,params:r.params,file:r.isDefault?'screenshots/'+r.id+'-material.png':'variant-'+r.id+'-'+Object.values(r.params).join('-')+'.png'}));
 const html='<!doctype html><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;background:#dfe1dd;color:#273d34;font:17px system-ui}header,footer{padding:24px}main{display:grid;grid-template-columns:repeat(4,1fr)}figure{margin:0;border:1px solid #b7c0b6}img{display:block;width:100%}figcaption{padding:12px}</style><header><h1>M060 · 屋顶与墙色 · 5项 / 14种形态</h1>实际模型截图 · 连续坡面与原生最小细件 · 每格独立构图</header><main>'+formBoard.map((r:any)=>'<figure><img src="'+r.file+'"><figcaption>'+r.id+'<br>'+Object.values(r.params).join(' / ')+'</figcaption></figure>').join('')+'</main><footer>保留真实父组件；墙色为作者预设，手选远档需显式加载近景物理权威。候选资产，未完成人工美术验收。</footer>';
 await writeFile(out+'/roof-wall-variants.html',html);const board=await browser.newPage({viewport:{width:2000,height:1300}});await board.goto(pathToFileURL(path.resolve(out+'/roof-wall-variants.html')).href);await board.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await board.screenshot({path:out+'/roof-wall-variants.png',fullPage:true});await board.close();report.formBoard=formBoard;
 const savedDoc=await load(rows.find((r:any)=>r.id==='BUILT-083').file),saved=await call('save_project',{filename:'verified-roof-wall.ysvox.json'});assert.equal(hash(JSON.parse(await readFile(saved.path,'utf8'))),hash(savedDoc));report.checks.push('Actual save_project roundtrip preserves parent graph, instances, scoped materials and parameters.');
 await new Promise(r=>setTimeout(r,250));assert.deepEqual(report.errors,[]);assert.ok(report.notifications.every((r:any)=>!r.fullProject&&r.bytes<65536));assert.ok(report.notifications.every((r:any)=>r.event==='state-invalidated'));assert.deepEqual(report.notifications.map((r:any)=>r.version),report.expectedInvalidationVersions);report.status='passed';
}finally{await browser?.close();await client?.close();if(server&&server.exitCode===null){const done=once(server,'exit');server.kill();await done;}await writeFile(out+'/variant-mcp-server.log',log);await writeFile(out+'/variant-mcp-verification.json',JSON.stringify(report,null,2));}
console.log(JSON.stringify({status:report.status,publicForms:report.publicForms.length,quarterTurns:report.quarterTurns.length,views:report.views.length,checks:report.checks.length}));
