import type {Project} from '../core/types';
const esc=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export class AtlasPanel{
 sheet='M001';query='';offset=0;token=0;selected='';
 constructor(private o:{el:HTMLElement;project:()=>Project;tool:(name:string,args?:any)=>Promise<any>;open:(file:string,assetId?:string)=>Promise<void>;safe:(fn:()=>any)=>any}){}
 render(){
  // Document updates can arrive twice (HTTP and WebSocket). Keep the last
  // complete reference visible while refreshing, instead of flashing empty.
  if(!this.o.el.querySelector('.atlas-pane'))this.o.el.innerHTML=`<div class="pane atlas-pane"><h2>67 张参考图册</h2><div id="atlas-stats"></div><label for="atlas-sheet">按图册验模</label><select id="atlas-sheet"></select><input id="atlas-search" aria-label="搜索图册资产" placeholder="资产 ID / 名称" value="${esc(this.query)}"><div id="atlas-reference"></div><div id="atlas-entries"></div></div>`;
  const search=this.o.el.querySelector<HTMLInputElement>('#atlas-search');if(search&&search.value!==this.query)search.value=this.query;
  void this.o.safe(()=>this.rows());
 }
 async rows(){const token=++this.token,r=await this.o.tool('read_reference_atlas',{...(this.query?{query:this.query,offset:this.offset}:{sheet:this.sheet}),limit:12});if(token!==this.token||!this.o.el.querySelector('#atlas-entries'))return;
 const el=this.o.el,stats=el.querySelector('#atlas-stats')!;if(!r.available){stats.textContent='尚未导入图册。运行 npm run atlas:index。';return;}
 stats.innerHTML=`<p><b>${r.counts.references} 项 · ${r.counts.sheets} 张参考</b><br>${r.counts.referenceCandidates} 项已按图重建候选<br><span class="subtle">${r.counts.pendingReference} 项待按新图制作或复核<br>${r.counts.base} 基础 · ${r.counts.assembly} 组合 · ${r.counts.variant} 变体<br>候选还需美术验收；升级母版不新增计数。</span></p>`;
 const select=el.querySelector<HTMLSelectElement>('#atlas-sheet')!;select.innerHTML=r.sheets.map((s:any)=>`<option value="${s.id}" ${s.id===this.sheet?'selected':''}>${s.id} · ${esc(s.theme)}</option>`).join('');select.onchange=()=>{this.sheet=select.value;this.query='';this.offset=0;this.selected='';this.render();};el.querySelector<HTMLInputElement>('#atlas-search')!.oninput=e=>{this.query=(e.target as HTMLInputElement).value;this.offset=0;void this.o.safe(()=>this.rows());};
 const row=r.entries.find((e:any)=>e.id===this.selected)??r.entries[0];if(row){this.selected=row.id;const selectedSheet=r.sheets.find((s:any)=>s.id===row.sheet),x=(row.slot-1)%4,y=Math.floor((row.slot-1)/4),context=el.querySelector('#atlas-reference')!;
  context.innerHTML=`<figure class="atlas-focus"><div class="atlas-tile" style="background-image:url('${row.imageURL}');background-position:${x*100/3}% ${y*50}%"></div><figcaption>${row.sheet} / ${row.slot} · <b>${esc(row.id)} ${esc(row.name)}</b><br><a href="${row.imageURL}" target="_blank" rel="noopener">打开完整参考图</a></figcaption></figure><details><summary>构造说明与来源</summary><p class="atlas-description">${esc(row.description)}</p><small>图像 ${selectedSheet.width} × ${selectedSheet.height} · SHA256 ${row.imageSHA256.slice(0,16)}…<br>图格各自缩放，模型尺寸是制作假设。</small></details>`;
 }else{el.querySelector('#atlas-reference')!.textContent='没有匹配的参考条目';this.selected='';}
 const names:Record<string,string>={'reference-candidate':'按图重建 · 待验收','legacy-candidate':'旧粗模 · 待复核','outdated-reference':'参考已变 · 待更新','not-produced':'待制作'},gallery=r.studies.find((s:any)=>s.id===this.sheet+'-gallery');
 el.querySelector('#atlas-entries')!.innerHTML=`${gallery&&!this.query?`<button id="atlas-gallery">打开 ${this.sheet} 图册总览</button>`:''}${r.entries.map((e:any)=>`<div class="catalog-source-field ${e.id===this.selected?'atlas-selected':''}"><button class="atlas-pick" data-id="${e.id}">${e.sheet} / ${e.slot} · ${esc(e.id)}<br><b>${esc(e.name)}</b></button><small>${names[e.stage]}</small>${e.build?`<div class="row"><button data-catalog="${e.id}" data-atlas-open="${e.build.file}" data-asset="${e.build.kind==='assembly'?'':e.build.assetId}">打开新版</button>${e.legacy?`<button data-catalog="${e.id}" data-atlas-open="${e.legacy.file}" data-asset="${e.legacy.assetIds[0]}">旧版对照</button>`:''}</div><small>${e.build.kind==='assembly'?e.build.instances+' 实例 · ':''}${e.build.voxels.toLocaleString()} ${e.build.kind==='assembly'?'组件原生格':'格'} · ${e.build.triangles.toLocaleString()} 三角形</small>`:e.legacy?`<button data-catalog="${e.id}" data-atlas-open="${e.legacy.file}" data-asset="${e.legacy.assetIds[0]}">打开旧粗模</button>`:''}</div>`).join('')}<div class="row"><button id="atlas-prev" ${!this.offset||!this.query?'disabled':''}>上一页</button><small>${this.offset+1}–${Math.min(this.offset+12,r.total)} / ${r.total}</small><button id="atlas-next" ${r.nextOffset===null?'disabled':''}>下一页</button></div>`;
 el.querySelector('#atlas-gallery')?.addEventListener('click',()=>this.o.safe(()=>this.o.open(gallery.file)));el.querySelectorAll<HTMLButtonElement>('[data-atlas-open]').forEach(b=>b.onclick=()=>this.o.safe(async()=>{this.selected=b.dataset.catalog!;await this.o.open(b.dataset.atlasOpen!,b.dataset.asset||undefined);}));el.querySelectorAll<HTMLButtonElement>('[data-id]').forEach(b=>b.onclick=()=>{this.selected=b.dataset.id!;void this.o.safe(()=>this.rows());});el.querySelector('#atlas-prev')!.addEventListener('click',()=>{this.offset=Math.max(0,this.offset-12);void this.o.safe(()=>this.rows());});el.querySelector('#atlas-next')!.addEventListener('click',()=>{this.offset+=12;void this.o.safe(()=>this.rows());});
 }
}
