import type {Project} from '../core/types';
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export class ProductionPanel{
 query='';offset=0;generatedOnly=true;request=0;studyFile='';
 constructor(private options:{el:HTMLElement;project:()=>Project;tool:(name:string,args?:any)=>Promise<any>;open:(file:string,assetId?:string)=>Promise<void>;safe:(fn:()=>any)=>any}){}
 render(){const el=this.options.el;el.innerHTML=`<div class="pane"><h2>城市批量资产库</h2><p class="subtle">按清单 ID 检查实际文件。母版、组合与尺寸变体分别统计；材质、动画不以静态模型代替。</p><div class="field-stack"><input id="production-search" aria-label="搜索批量资产" placeholder="LIFE-018、病床、柜…" value="${esc(this.query)}"><label><input id="production-generated" type="checkbox" ${this.generatedOnly?'checked':''}> 只看已生成候选</label></div><div id="production-stats"></div><div id="production-rows"></div></div>`;
 el.querySelector<HTMLInputElement>('#production-search')!.oninput=e=>{this.query=(e.target as HTMLInputElement).value;this.offset=0;void this.options.safe(()=>this.rows());};
 el.querySelector<HTMLInputElement>('#production-generated')!.onchange=e=>{this.generatedOnly=(e.target as HTMLInputElement).checked;this.offset=0;void this.options.safe(()=>this.rows());};void this.options.safe(()=>this.rows());}
 async rows(){const token=++this.request,r=await this.options.tool('read_production_library',{query:this.query,generatedOnly:this.generatedOnly,offset:this.offset,limit:24});if(token!==this.request||!this.options.el.querySelector('#production-rows'))return;
 const stats=this.options.el.querySelector('#production-stats')!,el=this.options.el.querySelector('#production-rows')!;
 if(!r.available){stats.innerHTML='<p>尚无已生成批次。运行 npm run produce:life 创建实际体素文件。</p>';return;}
 stats.innerHTML=`<p><b>${r.counts.catalogEntries} 项总清单</b><br>${r.counts.baseModels} 个基础模型候选 · ${r.counts.assemblies} 个组合草案 · ${r.counts.variantEntries} 类尺寸变体<br><span class="subtle">${r.counts.materialStudies?`${r.counts.materialStudies} 件已有设计附带材质试作 · 不新增资产<br>`:""}${r.counts.notProduced} 项待制作 · 人工验收 ${r.counts.accepted}${r.counts.referenceDesigns?`<br>另有 ${r.counts.referenceDesigns} 件建筑图鉴细化设计`:""}</span></p><p class="subtle">生成时索引。每次打开会保存当前项目并支持撤销；文件中的母版改动以当前项目为准。</p>`;
 if(r.studies?.length){if(!r.studies.some((s:any)=>s.file===this.studyFile)){const project=this.options.project(),ids=Object.keys(project.assets).sort().join('|'),finished=!!project.palettes['参考材质试作'];this.studyFile=(r.studies.find((s:any)=>s.assetIds.slice().sort().join('|')===ids&&s.id.startsWith('finish-')===finished)??r.studies[0]).file;}stats.insertAdjacentHTML('beforeend',`<div class="field-stack"><label for="production-study">参考图鉴 · 几何与材质</label><select id="production-study">${[...new Set(r.studies.map((s:any)=>s.group??'家居十二件'))].map(group=>`<optgroup label="${esc(group)}">${r.studies.filter((s:any)=>(s.group??'家居十二件')===group).map((s:any)=>`<option value="${esc(s.file)}" ${s.file===this.studyFile?'selected':''}>${esc(s.name)}</option>`).join('')}</optgroup>`).join('')}</select><button id="production-open-study">打开参考组合</button><small>图鉴设计与清单数量分别统计。材质试作可切换纯色检查；配色方案保留原始参数。门扇、灯具和屏幕尚无运行时交互。</small></div>`);stats.querySelector<HTMLSelectElement>('#production-study')!.onchange=e=>{this.studyFile=(e.target as HTMLSelectElement).value;};stats.querySelector<HTMLButtonElement>('#production-open-study')!.onclick=()=>this.options.safe(()=>this.options.open(this.studyFile));}
 const names:Record<string,string>={'geometry-candidate':'几何候选','layout-candidate':'组合草案','variant-candidate':'尺寸变体','not-produced':'待制作'};
 el.innerHTML=`<div class="row between"><button id="production-prev" ${!this.offset?'disabled':''}>上一页</button><small>${this.offset+1}–${Math.min(this.offset+24,r.total)} / ${r.total}</small><button id="production-next" ${r.nextOffset===null?'disabled':''}>下一页</button></div>${r.entries.map((e:any)=>`<div class="catalog-source-field"><small>${esc(e.id)} · ${names[e.stage]}</small><p><b>${esc(e.name)}</b></p><p class="subtle">${esc(e.note)}</p>${e.file?`<button data-production-file="${esc(e.file)}" data-production-asset="${e.stage==='geometry-candidate'?esc(e.assetIds[0]):''}">${e.stage==='geometry-candidate'?'打开母版':'打开组合 / 变体'}</button>`:''}${e.voxels?`<small> ${e.voxels.toLocaleString()} 格 · ${e.triangles.toLocaleString()} 三角形</small>`:''}</div>`).join('')}`;
 el.querySelector('#production-prev')!.addEventListener('click',()=>{this.offset=Math.max(0,this.offset-24);void this.options.safe(()=>this.rows());});el.querySelector('#production-next')!.addEventListener('click',()=>{this.offset+=24;void this.options.safe(()=>this.rows());});
 el.querySelectorAll<HTMLButtonElement>('[data-production-file]').forEach(button=>button.onclick=()=>this.options.safe(()=>this.options.open(button.dataset.productionFile!,button.dataset.productionAsset||undefined)));
 }
}
